nidas: nidas/apps/config/AddDSMComboDialog.cc File Reference
AddDSMComboDialog.cc File Reference
#include "AddDSMComboDialog.h"
#include "configwindow.h"
#include "exceptions/InternalProcessingException.h"
#include <nidas/util/InvalidParameterException.h>
#include "DeviceValidator.h"
Functions
QRegExp _dsmNameRegEx ("[a-zA-Z/_0-9.\\-+]+")
QRegExp _dsmIdRegEx ("\\d\\d?")
QRegExp _dsmLocRegEx ("\\S[\\S\\s]+")
Function Documentation
QRegExp _dsmIdRegEx ("\\d\\d?")
Referenced by config::AddDSMComboDialog::AddDSMComboDialog().
QRegExp _dsmLocRegEx ("\\S+" [\\S\\s])
Referenced by config::AddDSMComboDialog::AddDSMComboDialog().
QRegExp _dsmNameRegEx ("+" [a-zA-Z/_0-9.\\-+])
Referenced by config::AddDSMComboDialog::AddDSMComboDialog().