nidas: nidas/apps/arinc_out.cc File Reference
arinc_out.cc File Reference
#include <iostream>
#include <cmath>
#include <cstdlib>
#include <cstdio>
#include <sys/time.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <nidas/dynld/raf/DSMArincSensor.h>
Classes
class TestArinc
Macros
#define SSM 0x60000000
Functions
int usage (const char *argv0)
int parseRunstring (int argc, char **argv)
int main (int argc, char **argv)
Variables
int FREQ = 1
double MAXPTCHDEG = 5.0
double MAXROLLDEG = 10.0
int PTCHSTEP = 10
int ROLLSTEP = 20
int GAP = 0
bool SWEEP = false
char DEVICE [64] = "/dev/arinc4"
Macro Definition Documentation
#define SSM 0x60000000
Referenced by main(), nidas::dynld::raf::IRS_HW_YG1854::processLabel(), nidas::dynld::raf::ADC_HW_EB7022597::processLabel(), nidas::dynld::raf::IRS_HW_HG2001GD::processLabel(), and nidas::dynld::raf::GPS_HW_HG2021GB02::processLabel().
Function Documentation
int main (int argc, char ** argv)
References nidas::dynld::raf::DSMArincSensor::close(), DEVICE, FREQ, GAP, nidas::core::DSMSensor::getWriteFd(), MAXPTCHDEG, MAXROLLDEG, nidas::dynld::raf::DSMArincSensor::open(), parseRunstring(), printf(), PTCHSTEP, ROLLSTEP, nidas::core::DSMSensor::setDeviceName(), SSM, SWEEP, and nidas::util::Exception::what().
int parseRunstring (int argc, char ** argv)
References DEVICE, FREQ, GAP, MAXPTCHDEG, MAXROLLDEG, PTCHSTEP, ROLLSTEP, SWEEP, and usage().
Referenced by main().
int usage (const char * argv0)
References DEVICE, FREQ, GAP, MAXPTCHDEG, MAXROLLDEG, PTCHSTEP, and ROLLSTEP.
Referenced by main(), parse_args(), HeaderUtil::parseRunstring(), PConfig::parseRunstring(), NidsMerge::parseRunstring(), PacketDecode::parseRunstring(), MergeVerifier::parseRunstring(), SensorExtract::parseRunstring(), StatsProcess::parseRunstring(), ARLIngest::parseRunstring(), nidas::core::DSMEngine::parseRunstring(), parseRunstring(), and Extract2D::parseRunstring().
Variable Documentation
char DEVICE[64] = "/dev/arinc4"
Referenced by main(), parseRunstring(), and usage().
int FREQ = 1
Referenced by main(), parseRunstring(), and usage().
int GAP = 0
Referenced by main(), parseRunstring(), and usage().
double MAXPTCHDEG = 5.0
Referenced by main(), parseRunstring(), and usage().
double MAXROLLDEG = 10.0
Referenced by main(), parseRunstring(), and usage().
int PTCHSTEP = 10
Referenced by main(), parseRunstring(), and usage().
int ROLLSTEP = 20
Referenced by main(), parseRunstring(), and usage().
bool SWEEP = false
Referenced by main(), and parseRunstring().