nidas: nidas/apps/ck_a2d.cc File Reference
ck_a2d.cc File Reference
#include <nidas/linux/ncar_a2d.h>
#include <nidas/dynld/raf/DSMAnalogSensor.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References nidas::core::Variable::addParameter(), nidas::dynld::raf::DSMAnalogSensor::addSampleTag(), nidas::core::SampleTag::addVariable(), nidas::dynld::raf::DSMAnalogSensor::close(), dsm_sample::data, dsm_sample::length, NUM_NCAR_A2D_CHANNELS, nidas::dynld::raf::DSMAnalogSensor::open(), printf(), nidas::core::DSMSensor::read(), nidas::core::DSMSensor::setDeviceName(), nidas::core::SampleTag::setDSMId(), nidas::core::Parameter::setName(), nidas::core::Variable::setName(), nidas::core::SampleTag::setRate(), nidas::core::SampleTag::setSampleId(), nidas::core::SampleTag::setSensorId(), nidas::core::Variable::setUnits(), nidas::core::ParameterT< T >::setValue(), SIZEOF_DSM_SAMPLE_HEADER, dsm_sample::timetag, and nidas::util::Exception::what().