nidas: nidas/apps/ck_aout.cc File Reference
ck_aout.cc File Reference
#include <iostream>
#include <nidas/dynld/DSC_AnalogOut.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References nidas::dynld::DSC_AnalogOut::getMaxVoltage(), nidas::dynld::DSC_AnalogOut::getMinVoltage(), nidas::dynld::DSC_AnalogOut::getNumOutputs(), nidas::dynld::DSC_AnalogOut::open(), nidas::dynld::DSC_AnalogOut::setDeviceName(), and nidas::dynld::DSC_AnalogOut::setVoltages().