nidas: nidas/apps/ck_mesa.cc File Reference
ck_mesa.cc File Reference
#include <unistd.h>
#include <iostream>
#include <iomanip>
#include <bits/posix1_lim.h>
#include <csignal>
#include <nidas/core/DSMSensor.h>
#include <nidas/core/RTL_IODevice.h>
#include <nidas/rtlinux/mesa.h>
Classes
class TestMesa
Macros
#define err(format, arg...) printf("%s: %s: " format "\n",__FILE__, __FUNCTION__ , ## arg)
Functions
void sigAction (int sig, siginfo_t *siginfo, void *vptr)
int main (int argc, char **argv)
Variables
int running = 1
Macro Definition Documentation
#define err (format, arg...) printf("%s: %s: " format "\n",__FILE__, __FUNCTION__ , ## arg)
Referenced by main(), and sigAction().
Function Documentation
int main (int argc, char ** argv)
References buffer, COUNTERS_SET, err, len, MAX_BUFFER, MESA_STOP, counters_set::nChannels, radar_set::nChannels, RADAR_SET, counters_set::rate, radar_set::rate, running, nidas::core::DSMSensor::setDeviceName(), sigAction(), and nidas::util::Exception::what().
void sigAction (int sig, siginfo_t * siginfo, void * vptr)
References err, and running.
Referenced by main(), TeeTTy::setupSignals(), setupSignals(), and nidas::core::NidasApp::setupSignals().
Variable Documentation
int running = 1
Referenced by main(), Csat3Sim::run(), and sigAction().