nidas: nidas::dynld::psql::PSQLSampleOutput Class Reference
nidas::dynld::psql::PSQLSampleOutput Class Reference
#include <PSQLSampleOutput.h>
Public Member Functions
PSQLSampleOutput ()
PSQLSampleOutput (const PSQLSampleOutput &)
virtual ~PSQLSampleOutput ()
PSQLSampleOutput * clone (IOChannel *iochannel=0) const
void setName (const std::string &val)
const std::string & getName () const
bool isRaw () const
void setPseudoPort (int val)
int getPseudoPort () const
void setDSMConfigs (const std::list< const DSMConfig * > &val)
void addDSMConfig (const DSMConfig *)
const std::list< const
DSMConfig * > & getDSMConfigs () const
void addSampleTag (const SampleTag *tag) throw (nidas::util::InvalidParameterException)
void requestConnection (SampleConnectionRequester *) throw (nidas::util::IOException)
Request a connection, but don't wait for it.
void connected (SampleOutput *origout, SampleOutput *newout) throw ()
void connect () throw (nidas::util::IOException)
void connected (IOChannel *output) throw ()
Implementation of IOChannelRequester::connected().
void init () throw ()
bool receive (const Sample *) throw ()
Method called to pass a sample to this client.
int getFd () const
void flush () throw (nidas::util::IOException)
Ask that this SampleClient send out any buffered Samples that it may be holding.
void close () throw (nidas::util::IOException)
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
IOStream * getIOStream ()
Get the IOStream of this SampleOutputStream.
size_t write (const void *buf, size_t len, bool streamFlush) throw (nidas::util::IOException)
size_t write (const void *buf, size_t len) throw (nidas::util::IOException)
Raw write method, typically used to write the initial header.
void setLatency (float val) throw (nidas::util::InvalidParameterException)
Outgoing data is buffered in an IOStream.
virtual void setIOChannel (IOChannel *val)
Set the IOChannel for this SampleOutput.
SampleOutput * getOriginal () const
Get pointer to SampleOutput that was cloned.
void addRequestedSampleTag (SampleTag *tag) throw (nidas::util::InvalidParameterException)
Some SampleOutputs don't send out all the Samples that they receive.
std::list< const SampleTag * > getRequestedSampleTags () const
void addSourceSampleTag (const SampleTag *tag) throw (nidas::util::InvalidParameterException)
Some SampleOutputs like to be informed of what SampleTags they will be receiving from their SampleSources before they make a connection.
void addSourceSampleTags (const std::list< const SampleTag * > &tags) throw (nidas::util::InvalidParameterException)
std::list< const SampleTag * > getSourceSampleTags () const
int getReconnectDelaySecs () const
Base class implementation.
void setReconnectDelaySecs (int val)
dsm_time_t getNextFileTime () const
void createNextFile (dsm_time_t) throw (nidas::util::IOException)
IOChannel * getIOChannel () const
void setHeaderSource (HeaderSource *val)
void setDSMConfig (const DSMConfig *val)
const DSMConfig * getDSMConfig () const
size_t getNumDiscardedSamples () const
void addParameter (Parameter *val)
Add a parameter to this DSMSensor.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
float getLatency () const
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void submitCommand (const std::string &command) throw (nidas::util::IOException)
void createTables () throw (nidas::util::IOException)
void dropAllTables () throw ()
void initializeGlobalAttributes () throw (nidas::util::IOException)
void addVariable (const Variable *var) throw (nidas::util::IOException)
void addCategory (const std::string &varName, const std::string &category) throw (nidas::util::IOException)
size_t write (const Sample *samp, bool streamFlush) throw (nidas::util::IOException)
SampleOutputStream * clone (IOChannel *iochannel)
size_t incrementDiscardedSamples ()
SampleConnectionRequester * getSampleConnectionRequester ()
void disconnect () throw (nidas::util::IOException)
Close the IOChannel and notify whoever did the requestConnection that it is time to disconnect, perhaps because of an IOException.
Protected Attributes
std::string name
SampleConnectionRequester * connectionRequester
std::list< const DSMConfig * > dsms
PSQLChannel * psqlChannel
std::map< float, const
SampleTag * > tagsByRate
std::map< float, std::string > tablesByRate
std::map< dsm_sample_id_t,
const SampleTag * > tagsById
float missingValue
bool first
int dberrors
IOStream * _iostream
std::string _name
Constructor & Destructor Documentation
PSQLSampleOutput::PSQLSampleOutput ()
Referenced by clone().
PSQLSampleOutput::PSQLSampleOutput (const PSQLSampleOutput & x)
PSQLSampleOutput::~PSQLSampleOutput () virtual
References psqlChannel.
Member Function Documentation
void PSQLSampleOutput::addCategory (const std::string & varName, const std::string & category) throw (nidas::util::IOException) protected
void PSQLSampleOutput::addDSMConfig (const DSMConfig * val)
References dsms.
void SampleOutputBase::addParameter (Parameter * val) inherited
Add a parameter to this DSMSensor.
DSMSensor will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::SampleOutputBase::_constParameters, nidas::core::SampleOutputBase::_parameters, and nidas::core::Parameter::getName().
void SampleOutputBase::addRequestedSampleTag (SampleTag * tag) throw (nidas::util::InvalidParameterException) virtual inherited
Some SampleOutputs don't send out all the Samples that they receive.
At configuration time, one can use this method to request the SampleTags that should be output from a SampleOutput. SampleOutput will own the pointer.
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::isff::GOESOutput, and nidas::dynld::raf::CVIOutput.
Referenced by nidas::dynld::raf::CVIOutput::addRequestedSampleTag(), nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), and nidas::core::SampleOutputBase::SampleOutputBase().
void nidas::dynld::psql::PSQLSampleOutput::addSampleTag (const SampleTag * tag) throw (nidas::util::InvalidParameterException)
Referenced by nidas::dynld::psql::PSQLProcessor::connected().
void SampleOutputBase::addSourceSampleTag (const SampleTag * tag) throw (nidas::util::InvalidParameterException) virtual inherited
Some SampleOutputs like to be informed of what SampleTags they will be receiving from their SampleSources before they make a connection.
Users of SampleOutputs should call this method before calling requestConnection().
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::isff::GOESOutput.
Referenced by nidas::dynld::isff::GOESOutput::addSourceSampleTag(), and nidas::core::SampleOutputBase::SampleOutputBase().
void SampleOutputBase::addSourceSampleTags (const std::list< const SampleTag * > & tags) throw (nidas::util::InvalidParameterException) virtual inherited
Implements nidas::core::SampleOutput.
void nidas::dynld::psql::PSQLSampleOutput::addVariable (const Variable * var) throw (nidas::util::IOException) protected
Referenced by createTables().
PSQLSampleOutput * PSQLSampleOutput::clone (IOChannel * iochannel = 0) const
References DLOG, name, psqlChannel, and PSQLSampleOutput().
SampleOutputStream * SampleOutputStream::clone (IOChannel * iochannel) protected virtual inherited
Implements nidas::core::SampleOutput.
References nidas::dynld::SampleOutputStream::SampleOutputStream().
void PSQLSampleOutput::close () throw (nidas::util::IOException) virtual
Reimplemented from nidas::core::SampleOutputBase.
References nidas::dynld::psql::PSQLChannel::close(), and psqlChannel.
void PSQLSampleOutput::connect () throw (nidas::util::IOException)
References nidas::dynld::psql::PSQLChannel::connect(), DLOG, name, and psqlChannel.
void PSQLSampleOutput::connected (SampleOutput * origout, SampleOutput * newout) throw ()
References DLOG.
void PSQLSampleOutput::connected (IOChannel * ochan) throw () virtual
Implementation of IOChannelRequester::connected().
How an IOChannel calls back to a SampleConnectionRequester that it is connected. The ConnectionRequester can then return a clone of itself if the IOChannel is a new instance.
Reimplemented from nidas::core::SampleOutputBase.
References nidas::dynld::SampleOutputStream::connected(), and DLOG.
void SampleOutputBase::createNextFile (dsm_time_t tt) throw (nidas::util::IOException) inherited
References nidas::core::HeaderSource::sendDefaultHeader().
void PSQLSampleOutput::createTables () throw (nidas::util::IOException) protected
References addVariable(), nidas::core::Variable::getName(), nidas::core::SampleTag::getVariables(), rate, submitCommand(), and tagsByRate.
Referenced by init().
void SampleOutputBase::disconnect () throw (nidas::util::IOException) protected inherited
Close the IOChannel and notify whoever did the requestConnection that it is time to disconnect, perhaps because of an IOException.
This is typically called in the receive() method of a SampleOutput if it gets an IOException when writing data. A common implementation of a connection requester is to delete this SampleOutput after the removing it from the sample stream. So the caller method should immediately return after calling disconnect().
References nidas::core::SampleOutputBase::_connectionRequester, nidas::core::SampleOutputBase::close(), nidas::core::SampleConnectionRequester::disconnect(), nidas::core::SampleOutputBase::getName(), and ILOG.
void PSQLSampleOutput::dropAllTables () throw () protected
References DLOG, getName(), PLOG, submitCommand(), and nidas::util::Exception::what().
Referenced by init().
void PSQLSampleOutput::flush () throw (nidas::util::IOException) virtual
Ask that this SampleClient send out any buffered Samples that it may be holding.
Implements nidas::core::SampleClient.
References nidas::dynld::psql::PSQLChannel::flush(), and psqlChannel.
void PSQLSampleOutput::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Reimplemented from nidas::core::SampleOutputBase.
References nidas::core::IOChannel::createIOChannel(), and DLOG.
const DSMConfig* nidas::core::SampleOutputBase::getDSMConfig () const inline virtual inherited
Implements nidas::core::SampleOutput.
Referenced by nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
const std::list< const DSMConfig * > & PSQLSampleOutput::getDSMConfigs () const
References dsms.
int nidas::dynld::psql::PSQLSampleOutput::getFd () const inline virtual
Reimplemented from nidas::core::SampleOutputBase.
IOChannel* nidas::core::SampleOutputBase::getIOChannel () const inline virtual inherited
Implements nidas::core::SampleOutput.
Referenced by nidas::dynld::AsciiOutput::AsciiOutput(), nidas::dynld::raf::CVIOutput::CVIOutput(), nidas::dynld::isff::GOESOutput::GOESOutput(), nidas::dynld::AsciiOutput::printHeader(), nidas::dynld::RawSampleOutputStream::RawSampleOutputStream(), nidas::dynld::SampleOutputStream::SampleOutputStream(), nidas::dynld::isff::GOESOutput::setIOChannel(), and nidas::dynld::raf::CVIOutput::setIOChannel().
IOStream* nidas::dynld::SampleOutputStream::getIOStream () inline inherited
Get the IOStream of this SampleOutputStream.
SampleOutputStream owns the pointer and will delete the IOStream in its destructor. The IOStream is available after a SammpleOutputStream is constructed with an connected IOChannel, or after the connected() method has been called and before close().
float nidas::core::SampleOutputBase::getLatency () const inline virtual inherited
Implements nidas::core::SampleOutput.
Referenced by nidas::dynld::SampleOutputStream::SampleOutputStream().
const std::string& nidas::dynld::psql::PSQLSampleOutput::getName () const inline virtual
Reimplemented from nidas::core::SampleOutputBase.
References name.
Referenced by dropAllTables(), and init().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
dsm_time_t nidas::core::SampleOutputBase::getNextFileTime () const inline inherited
size_t nidas::core::SampleOutputBase::getNumDiscardedSamples () const inline inherited
SampleOutput* nidas::core::SampleOutputBase::getOriginal () const inline virtual inherited
Get pointer to SampleOutput that was cloned.
Will be NULL if this SampleOutput is an un-cloned original.
Implements nidas::core::SampleOutput.
const Parameter * SampleOutputBase::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::SampleOutputBase::_parameters.
const std::list<const Parameter*>& nidas::core::SampleOutputBase::getParameters () const inline inherited
Get list of parameters.
int nidas::dynld::psql::PSQLSampleOutput::getPseudoPort () const inline
int SampleOutputBase::getReconnectDelaySecs () const virtual inherited
Base class implementation.
If setReconnectDelaySecs() has been called on this SampleOutput, then that value will be returned. Otherwise this will return the value of the IOChannel.
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_iochan, nidas::core::SampleOutputBase::_reconnectDelaySecs, and nidas::core::IOChannel::getReconnectDelaySecs().
std::list< const SampleTag * > SampleOutputBase::getRequestedSampleTags () const virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_constRequestedTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::dynld::isff::GOESProject::GOESProject(), nidas::dynld::isff::GOESOutput::run(), and nidas::core::SampleOutputBase::SampleOutputBase().
SampleConnectionRequester* nidas::core::SampleOutputBase::getSampleConnectionRequester () inline protected inherited
list< const SampleTag * > SampleOutputBase::getSourceSampleTags () const virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_sourceTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::core::SampleOutputBase::SampleOutputBase().
size_t nidas::core::SampleOutputBase::incrementDiscardedSamples () inline protected inherited
void PSQLSampleOutput::init () throw ()
References createTables(), DLOG, dropAllTables(), nidas::util::Logger::getInstance(), getName(), initializeGlobalAttributes(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
void PSQLSampleOutput::initializeGlobalAttributes () throw (nidas::util::IOException) protected
References DLOG, nidas::core::Project::getInstance(), nidas::core::Project::getName(), and submitCommand().
Referenced by init().
bool nidas::dynld::psql::PSQLSampleOutput::isRaw () const inline virtual
Reimplemented from nidas::core::SampleOutputBase.
bool PSQLSampleOutput::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Implements nidas::core::SampleClient.
References nidas::core::FLOAT_ST, nidas::core::SampleT< DataT >::getConstDataPtr(), nidas::core::SampleT< DataT >::getDataLength(), nidas::util::Logger::getInstance(), nidas::core::SampleTag::getRate(), nidas::util::Logger::log(), LOG_ERR, USECS_PER_MSEC, USECS_PER_SEC, and nidas::util::Exception::what().
void PSQLSampleOutput::requestConnection (SampleConnectionRequester * requester) throw (nidas::util::IOException) virtual
Request a connection, but don't wait for it.
Requester will be notified via SampleConnectionRequester interface when the connection has been made. It is not necessary to call this method if a SampleOutput is constructed with a connected IOChannel.
Reimplemented from nidas::core::SampleOutputBase.
References DLOG.
void nidas::core::SampleOutputBase::setDSMConfig (const DSMConfig * val) inline virtual inherited
Implements nidas::core::SampleOutput.
void PSQLSampleOutput::setDSMConfigs (const std::list< const DSMConfig * > & val)
References dsms.
void nidas::core::SampleOutputBase::setHeaderSource (HeaderSource * val) inline virtual inherited
Implements nidas::core::SampleOutput.
Referenced by NidsMerge::run(), SensorExtract::run(), and ARLIngest::run().
void SampleOutputBase::setIOChannel (IOChannel * val) virtual inherited
Set the IOChannel for this SampleOutput.
This IOChannel is not yet connected. The IOChannel must be connected before the SampleOutput is used for I/O, using the requestConnection() method, or by IOChannel::connect() followed by SampleOutput::connected(IOChannel*).
Reimplemented in nidas::dynld::raf::CVIOutput, and nidas::dynld::isff::GOESOutput.
References nidas::core::SampleOutputBase::_iochan, nidas::core::SampleOutputBase::getDSMConfig(), and nidas::core::IOChannel::setDSMConfig().
Referenced by nidas::dynld::isff::GOESOutput::setIOChannel(), and nidas::dynld::raf::CVIOutput::setIOChannel().
void SampleOutputStream::setLatency (float val) throw (nidas::util::InvalidParameterException) virtual inherited
Outgoing data is buffered in an IOStream.
The stream will be flushed when the difference between successive time tags exceeds this value. This is a useful parameter for real-time applications.
Parameters
val Number of seconds between physical writes. Default is set in SampleOutputBase.
Reimplemented from nidas::core::SampleOutputBase.
References nidas::core::SampleOutputBase::setLatency(), and USECS_PER_SEC.
void nidas::dynld::psql::PSQLSampleOutput::setName (const std::string & val) inline virtual
Reimplemented from nidas::core::SampleOutputBase.
References name.
void nidas::dynld::psql::PSQLSampleOutput::setPseudoPort (int val) inline
void SampleOutputBase::setReconnectDelaySecs (int val) virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_reconnectDelaySecs.
Referenced by nidas::dynld::raf::SyncServer::init().
void PSQLSampleOutput::submitCommand (const std::string & command) throw (nidas::util::IOException) protected
Referenced by createTables(), dropAllTables(), and initializeGlobalAttributes().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
size_t SampleOutputStream::write (const void * buf, size_t len, bool streamFlush) throw (nidas::util::IOException) inherited
References len.
size_t SampleOutputStream::write (const Sample * samp, bool streamFlush) throw (nidas::util::IOException) protected inherited
References nidas::core::SampleHeader::getSizeOf(), and nidas::core::SampleHeader::setTimeTag().
size_t SampleOutputBase::write (const void * buf, size_t len) throw (nidas::util::IOException) virtual inherited
Raw write method, typically used to write the initial header.
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::isff::GOESOutput.
References len.
Member Data Documentation
IOStream* nidas::dynld::SampleOutputStream::_iostream protected inherited
Referenced by nidas::dynld::SampleOutputStream::close(), nidas::dynld::SampleOutputStream::flush(), nidas::dynld::SampleOutputStream::SampleOutputStream(), and nidas::dynld::SampleOutputStream::~SampleOutputStream().
std::string nidas::core::SampleOutputBase::_name protected inherited
SampleConnectionRequester* nidas::dynld::psql::PSQLSampleOutput::connectionRequester protected
int nidas::dynld::psql::PSQLSampleOutput::dberrors protected
std::list<const DSMConfig*> nidas::dynld::psql::PSQLSampleOutput::dsms protected
Referenced by addDSMConfig(), getDSMConfigs(), and setDSMConfigs().
bool nidas::dynld::psql::PSQLSampleOutput::first protected
float nidas::dynld::psql::PSQLSampleOutput::missingValue protected
std::string nidas::dynld::psql::PSQLSampleOutput::name protected
Referenced by clone(), connect(), getName(), and setName().
PSQLChannel* nidas::dynld::psql::PSQLSampleOutput::psqlChannel protected
Referenced by clone(), close(), connect(), flush(), and ~PSQLSampleOutput().
std::map<float,std::string> nidas::dynld::psql::PSQLSampleOutput::tablesByRate protected
std::map<dsm_sample_id_t,const SampleTag*> nidas::dynld::psql::PSQLSampleOutput::tagsById protected
std::map<float,const SampleTag*> nidas::dynld::psql::PSQLSampleOutput::tagsByRate protected
Referenced by createTables().
The documentation for this class was generated from the following files:
nidas/dynld/psql/PSQLSampleOutput.h
nidas/dynld/psql/PSQLSampleOutput.cc