nidas: nidas::core::RemoteSerialListener Class Reference
nidas::core::RemoteSerialListener Class Reference
#include <RemoteSerialListener.h>
Public Member Functions
throw (nidas::util::IOException)
~RemoteSerialListener ()
bool handlePollEvents (uint32_t events) throw ()
void close () throw (nidas::util::IOException)
int getFd () const
const std::string getName () const
Private Member Functions
RemoteSerialListener (const RemoteSerialListener &)
Open a ServerSocket for listening on a given port.
RemoteSerialListener & operator= (const RemoteSerialListener &)
Private Attributes
nidas::util::ServerSocket _socket
SensorHandler * _handler
Constructor & Destructor Documentation
RemoteSerialListener::~RemoteSerialListener ()
References PLOG, and nidas::util::Exception::what().
RemoteSerialListener::RemoteSerialListener (const RemoteSerialListener &) private
Open a ServerSocket for listening on a given port.
Member Function Documentation
void RemoteSerialListener::close () throw (nidas::util::IOException)
Referenced by nidas::core::SensorHandler::run().
int nidas::core::RemoteSerialListener::getFd () const inline virtual
Implements nidas::core::Polled.
References _socket, and nidas::util::ServerSocket::getFd().
Referenced by nidas::core::SensorHandler::handlePollingChange().
const std::string nidas::core::RemoteSerialListener::getName () const inline
References _socket, nidas::util::ServerSocket::getLocalSocketAddress(), and nidas::util::SocketAddress::toAddressString().
bool RemoteSerialListener::handlePollEvents (uint32_t events) throw () virtual
Returns
: true: read consumed all available data, false otherwise. This return value is required for edge-triggered polling with epoll, since a read event won't be re-triggered on a file descriptor until all available data is read.
Implements nidas::core::Polled.
References N_POLLERR, N_POLLHUP, N_POLLIN, N_POLLRDHUP, PLOG, and nidas::util::Exception::what().
RemoteSerialListener& nidas::core::RemoteSerialListener::operator= (const RemoteSerialListener &) private
nidas::core::RemoteSerialListener::throw (nidas::util::IOException)
Member Data Documentation
SensorHandler* nidas::core::RemoteSerialListener::_handler private
nidas::util::ServerSocket nidas::core::RemoteSerialListener::_socket private
Referenced by getFd(), and getName().
The documentation for this class was generated from the following files:
nidas/core/RemoteSerialListener.h
nidas/core/RemoteSerialListener.cc