nidas: config::NewProjectDialog Class Reference
config::NewProjectDialog Class Reference
#include <NewProjectDialog.h>
Public Slots
void reject ()
void show ()
bool setUpDialog ()
Public Member Functions
NewProjectDialog (QString projDir, QWidget *parent=0)
~NewProjectDialog ()
void accept ()
Protected Attributes
QMessageBox * _errorMessage
QString * _fileName
Private Attributes
QString _defaultDir
ConfigWindow * _confWin
Constructor & Destructor Documentation
NewProjectDialog::NewProjectDialog (QString projDir, QWidget * parent = 0)
References _confWin, _defaultDir, _errorMessage, and _projNameRegEx().
config::NewProjectDialog::~NewProjectDialog () inline
Member Function Documentation
void NewProjectDialog::accept ()
References _confWin, _defaultDir, _errorMessage, ConfigWindow::openFile(), ConfigWindow::setFilename(), and ConfigWindow::writeProjectName().
void config::NewProjectDialog::reject () inline slot
bool NewProjectDialog::setUpDialog () slot
Referenced by show().
void NewProjectDialog::show () slot
References setUpDialog().
Referenced by ConfigWindow::newProj().
Member Data Documentation
ConfigWindow* config::NewProjectDialog::_confWin private
Referenced by accept(), and NewProjectDialog().
QString config::NewProjectDialog::_defaultDir private
Referenced by accept(), and NewProjectDialog().
QMessageBox* config::NewProjectDialog::_errorMessage protected
Referenced by accept(), and NewProjectDialog().
QString* config::NewProjectDialog::_fileName protected
The documentation for this class was generated from the following files:
nidas/apps/config/NewProjectDialog.h
nidas/apps/config/NewProjectDialog.cc