nidas: VariableItem Class Reference
VariableItem Class Reference
#include <VariableItem.h>
Public Member Functions
VariableItem (Variable *variable, SampleTag *sampleTag, int row, NidasModel *theModel, NidasItem *parent=0)
~VariableItem ()
bool removeChild (NidasItem *item)
std::string variableName ()
const QVariant & childLabel (int column) const
int childColumnCount () const
QString dataField (int column)
QString name ()
QString getLongName ()
std::string getBaseName ()
Variable * getVariable () const
SampleTag * getSampleTag ()
std::vector< std::string > getCalibrationInfo ()
xercesc::DOMNode * getSampleDOMNode ()
float getRate ()
unsigned int getSampleId ()
xercesc::DOMNode * getVariableDOMNode (QString name)
void clearVarItem ()
std::string sSampleId ()
void setDOMName (QString fromName, std::string toName)
void fromDOM ()
SensorItem * getSensorItem ()
QString getCalValues ()
QString getCalSrc ()
QString getCalDate ()
virtual NidasItem * child (int i)
return the ith child of this item.
NidasItem * parent () const
int row () const
int childCount ()
bool removeChildren (int first, int last)
QModelIndex createIndex ()
NidasItem * getParentItem ()
Protected Member Functions
xercesc::DOMNode * findSampleDOMNode ()
xercesc::DOMNode * findVariableDOMNode (QString name)
Protected Attributes
Variable * _variable
SampleTag * _sampleTag
xercesc::DOMNode * domNode
QList< NidasItem * > childItems
NidasItem * parentItem
int rowNumber
NidasModel * model
Static Protected Attributes
static const QVariant _Project_Label
static const QVariant _Site_Label
static const QVariant _DSM_Label
static const QVariant _Device_Label
static const QVariant _SN_Label
static const QVariant _ID_Label
static const QVariant _Sensor_Label
static const QVariant _Sample_Label
static const QVariant _DevChan_Label
static const QVariant _Suffix_Label
static const QVariant _Rate_Label
static const QVariant _Volt_Label
static const QVariant _Variable_Label
static const QVariant _CalCoefSrc_Label
static const QVariant _CalCoef_Label
static const QVariant _CalDate_Label
static const QVariant _Name_Label
static const QVariant _Channel_Label
static const QVariant _Unknown_Label
Private Attributes
xercesc::DOMNode * _sampleDOMNode
xercesc::DOMNode * _variableDOMNode
unsigned int _sampleID
VariableConverter * _varConverter
CalFile * _calFile
std::string _calFileName
bool _gotCalDate
bool _gotCalVals
std::string _calDate
std::string _calVals
Constructor & Destructor Documentation
VariableItem::VariableItem (Variable * variable, SampleTag * sampleTag, int row, NidasModel * theModel, NidasItem * parent = 0)
References nidas::core::VariableConverter::getCalFile(), nidas::core::Variable::getConverter(), nidas::core::CalFile::getFile(), and nidas::core::SampleTag::getSampleId().
VariableItem::~VariableItem ()
References NidasItem::removeChild().
Member Function Documentation
virtual NidasItem* NidasItem::child (int i) inline virtual inherited
return the ith child of this item.
The primary mechanism for building the NidasItem tree. When Qt asks the NidasModel for info, it calls child(). Subclasses reimplement to build items for each type of Nidas object based on the parent's unique child iterators.
N.B. there is a QObject::child(objName,inheritsClass,recursiveSearch) from Qt3. Watch out...
Reimplemented in SensorItem, A2DSensorItem, DSMItem, ProjectItem, and SiteItem.
Referenced by NidasItem::childCount(), NidasModel::index(), and NidasModel::insertRows().
int VariableItem::childColumnCount () const inline virtual
Reimplemented from NidasItem.
int NidasItem::childCount () inherited
NidasItem is a proxy for the actual Nidas objects in the Project tree and their corresponding DOMNodes. Qt indexing is mapped to the Project tree via parent/child with row the ordinal number of the siblings and columns used for data fields (attributes/properties) of each level of Nidas object.
Pointers to Nidas objects are void* since Nidas uses different classes at every level. NidasItem is (should/will be) subclassed for specialized Items corresponding to each kind of Nidas object in the Project tree and implementing their own logic for the API used by NidasModel (like the data and header returned for Qt columns).
The NidasItem tree is a mirror/proxy of the Nidas object Project tree, with children lazily initialized by child(). Row number, parent pointer, and a list of children are cached.
N.B. can only add children to end of list due to Nidas API and use of children list in child()
NidasItem could also become a QObject to get the parent/children stuff. This could be useful in future for findChild()/findChildren(). Except for the fact that it didn't work - something about Qt's cleanup of children caused problems for us.
References NidasItem::child(), and NidasItem::childItems.
Referenced by Document::addA2DVariable(), Document::insertA2DVariable(), NidasModel::insertRows(), and NidasModel::rowCount().
const QVariant& VariableItem::childLabel (int column) const inline virtual
Reimplemented from NidasItem.
References NidasItem::_Name_Label.
void VariableItem::clearVarItem ()
Referenced by Document::updateVariable().
QModelIndex NidasItem::createIndex () inline inherited
Asks the model to create an index for this item. Requires us to be a friend of NidasModel and for the model to ask NidasItem for the parent item.
Returns
a QModelIndex for this NidasItem
Referenced by Document::addA2DVariable(), NidasModel::appendChild(), NidasModel::removeChildren(), and NidasModel::removeIndexes().
QString VariableItem::dataField (int column) virtual
Reimplemented from NidasItem.
DOMNode * VariableItem::findSampleDOMNode () protected
References nidas::core::XDOMElement::getAttributeValue(), and SensorItem::getDOMNode().
DOMNode * VariableItem::findVariableDOMNode (QString name) protected
References nidas::core::XDOMElement::getAttributeValue().
void VariableItem::fromDOM ()
Referenced by Document::updateVariable().
std::string VariableItem::getBaseName ()
References SensorItem::getDSMSensor(), and nidas::core::DSMSensor::getSuffix().
Referenced by config::VariableComboDialog::show(), and Document::updateVariable().
QString VariableItem::getCalDate ()
References nidas::util::UTime::format(), nidas::core::Polynomial::setCalFile(), and nidas::util::Exception::toString().
std::vector< std::string > VariableItem::getCalibrationInfo ()
References nidas::core::VariableConverter::getUnits().
Referenced by config::VariableComboDialog::show().
QString VariableItem::getCalSrc ()
Referenced by config::VariableComboDialog::show().
QString VariableItem::getCalValues ()
References nidas::util::UTime::format(), nidas::core::Polynomial::readCalFile(), nidas::core::Polynomial::setCalFile(), nidas::util::Exception::toString(), nidas::core::Polynomial::toString(), and nidas::util::UTime::toUsecs().
QString VariableItem::getLongName () inline
Referenced by config::VariableComboDialog::show().
NidasItem* NidasItem::getParentItem () inline inherited
float VariableItem::getRate () inline
Referenced by config::VariableComboDialog::show().
xercesc::DOMNode* VariableItem::getSampleDOMNode () inline
unsigned int VariableItem::getSampleId () inline
Referenced by Document::updateVariable().
SampleTag* VariableItem::getSampleTag () inline
Referenced by SensorItem::removeChild(), and Document::updateVariable().
SensorItem* VariableItem::getSensorItem () inline
Variable* VariableItem::getVariable () const inline
Referenced by config::VariableComboDialog::show().
xercesc::DOMNode* VariableItem::getVariableDOMNode (QString name) inline
QString VariableItem::name () virtual
Reimplemented from NidasItem.
Referenced by SensorItem::removeChild(), and Document::updateVariable().
NidasItem* NidasItem::parent () const inline inherited
Referenced by NidasModel::parent(), and NidasModel::removeIndexes().
bool VariableItem::removeChild (NidasItem * item) inline virtual
subclasses implement to remove item from Project tree and remove and release from DOM tree
Reimplemented from NidasItem.
bool NidasItem::removeChildren (int first, int last) inherited
References NidasItem::childItems, and NidasItem::rowNumber.
Referenced by NidasModel::removeRows().
int NidasItem::row () const inline inherited
Referenced by NidasModel::parent(), and NidasModel::removeIndexes().
void VariableItem::setDOMName (QString fromName, std::string toName)
std::string VariableItem::sSampleId () inline
Referenced by SensorItem::removeChild().
std::string VariableItem::variableName () inline
Member Data Documentation
const QVariant NidasItem::_CalCoef_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_CalCoefSrc_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
std::string VariableItem::_calDate private
const QVariant NidasItem::_CalDate_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
CalFile* VariableItem::_calFile private
std::string VariableItem::_calFileName private
std::string VariableItem::_calVals private
const QVariant NidasItem::_Channel_Label static protected inherited
Referenced by A2DSensorItem::childLabel().
const QVariant NidasItem::_DevChan_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Device_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_DSM_Label static protected inherited
Referenced by SiteItem::childLabel().
bool VariableItem::_gotCalDate private
bool VariableItem::_gotCalVals private
const QVariant NidasItem::_ID_Label static protected inherited
Referenced by SiteItem::childLabel(), and DSMItem::childLabel().
const QVariant NidasItem::_Name_Label static protected inherited
Referenced by childLabel(), SiteItem::childLabel(), A2DVariableItem::childLabel(), and DSMItem::childLabel().
const QVariant NidasItem::_Project_Label static protected inherited
const QVariant NidasItem::_Rate_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Sample_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
xercesc::DOMNode* VariableItem::_sampleDOMNode private
unsigned int VariableItem::_sampleID private
SampleTag* VariableItem::_sampleTag protected
const QVariant NidasItem::_Sensor_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Site_Label static protected inherited
Referenced by ProjectItem::childLabel().
const QVariant NidasItem::_SN_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Suffix_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Unknown_Label static protected inherited
Referenced by A2DSensorItem::childLabel().
VariableConverter* VariableItem::_varConverter private
Variable* VariableItem::_variable protected
const QVariant NidasItem::_Variable_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
xercesc::DOMNode* VariableItem::_variableDOMNode private
const QVariant NidasItem::_Volt_Label static protected inherited
Referenced by A2DSensorItem::childLabel().
QList<NidasItem*> NidasItem::childItems protected inherited
Referenced by A2DSensorItem::child(), NidasItem::childCount(), A2DSensorItem::refreshChildItems(), NidasItem::removeChildren(), and A2DSensorItem::updateDOMA2DTempSfx().
xercesc::DOMNode* NidasItem::domNode protected inherited
NidasModel* NidasItem::model protected inherited
Referenced by A2DSensorItem::child(), and A2DSensorItem::refreshChildItems().
NidasItem* NidasItem::parentItem protected inherited
int NidasItem::rowNumber protected inherited
Referenced by NidasItem::removeChildren().
The documentation for this class was generated from the following files:
nidas/apps/config/nidas_qmv/VariableItem.h
nidas/apps/config/nidas_qmv/VariableItem.cc