nidas: nidas::dynld::isff::CS_Krypton Class Reference
nidas::dynld::isff::CS_Krypton Class Reference
A data converter from voltage to water vapor density in gm/m^3 for a Campbell Scientfic krypton hygrometer.
#include <CS_Krypton.h>
Public Member Functions
CS_Krypton ()
CS_Krypton (const CS_Krypton &)
CS_Krypton & operator= (const CS_Krypton &)
~CS_Krypton ()
CS_Krypton * clone () const
void setCalFile (CalFile *val)
CalFile * getCalFile ()
const CalFile * getCalFile () const
void setKw (float val)
float getKw () const
void setV0 (float val)
float getV0 () const
void setPathLength (float val)
float getPathLength () const
void setBias (float val)
float getBias () const
void readCalFile (dsm_time_t t) throw ()
double convert (dsm_time_t t, double volts)
Convert a voltage to water vapor density in g/m^3.
std::string toString () const
Generate a string description of this VariableConverter.
void fromString (const std::string &) throw (nidas::util::InvalidParameterException)
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
void setUnits (const std::string &val)
virtual const std::string & getUnits () const
void setVariable (const Variable *val)
const Variable * getVariable () const
const DSMSensor * getDSMSensor () const
const DSMConfig * getDSMConfig () const
void addParameter (Parameter *val)
Add a parameter to this VariableConverter.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static VariableConverter * createVariableConverter (XDOMElement &child)
static VariableConverter * createFromString (const std::string &) throw (nidas::util::InvalidParameterException)
static const XMLCh * getNamespaceURI ()
Private Attributes
float _Kw
float _V0
float _logV0
float _pathLength
float _bias
float _pathLengthKw
CalFile * _calFile
Detailed Description
A data converter from voltage to water vapor density in gm/m^3 for a Campbell Scientfic krypton hygrometer.
Constructor & Destructor Documentation
CS_Krypton::CS_Krypton ()
Referenced by clone().
CS_Krypton::CS_Krypton (const CS_Krypton & x)
References nidas::core::VariableConverter::getUnits(), and nidas::core::VariableConverter::setUnits().
CS_Krypton::~CS_Krypton ()
References _calFile.
Member Function Documentation
void VariableConverter::addParameter (Parameter * val) inherited
Add a parameter to this VariableConverter.
VariableConverter will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::VariableConverter::_constParameters, nidas::core::VariableConverter::_parameters, and nidas::core::Parameter::getName().
Referenced by nidas::core::VariableConverter::operator=(), and nidas::core::VariableConverter::VariableConverter().
CS_Krypton * CS_Krypton::clone () const virtual
Implements nidas::core::VariableConverter.
References CS_Krypton().
double CS_Krypton::convert (dsm_time_t t, double volts) virtual
Convert a voltage to water vapor density in g/m^3.
Implements nidas::core::VariableConverter.
References _bias, _logV0, _pathLengthKw, and readCalFile().
VariableConverter * VariableConverter::createFromString (const std::string & str) throw (nidas::util::InvalidParameterException) static inherited
References nidas::core::VariableConverter::fromString().
VariableConverter * VariableConverter::createVariableConverter (XDOMElement & child) static inherited
References nidas::core::DOMObjectFactory::createObject(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::XDOMElement::getNodeName(), and nidas::util::Exception::what().
Referenced by nidas::core::Variable::fromDOMElement().
void CS_Krypton::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Reimplemented from nidas::core::VariableConverter.
References nidas::core::VariableConverter::fromDOMElement(), nidas::core::Parameter::getLength(), nidas::core::Parameter::getNumericValue(), setBias(), setKw(), setPathLength(), and setV0().
void CS_Krypton::fromString (const std::string &) throw (nidas::util::InvalidParameterException) virtual
Reimplemented from nidas::core::VariableConverter.
float nidas::dynld::isff::CS_Krypton::getBias () const inline
Referenced by operator=().
CalFile * CS_Krypton::getCalFile () virtual
Implements nidas::core::VariableConverter.
References _calFile.
const CalFile* nidas::dynld::isff::CS_Krypton::getCalFile () const inline virtual
Implements nidas::core::VariableConverter.
const DSMConfig * VariableConverter::getDSMConfig () const inherited
References nidas::core::DSMSensor::getDSMConfig(), and nidas::core::VariableConverter::getDSMSensor().
const DSMSensor * VariableConverter::getDSMSensor () const inherited
References nidas::core::SampleTag::getDSMSensor(), nidas::core::Variable::getSampleTag(), and nidas::core::VariableConverter::getVariable().
Referenced by nidas::core::VariableConverter::getDSMConfig().
float nidas::dynld::isff::CS_Krypton::getKw () const inline
Referenced by operator=().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
const Parameter * VariableConverter::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::VariableConverter::_parameters.
const std::list<const Parameter*>& nidas::core::VariableConverter::getParameters () const inline inherited
Get list of parameters.
References nidas::core::VariableConverter::_constParameters.
Referenced by nidas::core::VariableConverter::operator=(), and nidas::core::VariableConverter::VariableConverter().
float nidas::dynld::isff::CS_Krypton::getPathLength () const inline
Referenced by operator=().
virtual const std::string& nidas::core::VariableConverter::getUnits () const inline virtual inherited
References nidas::core::VariableConverter::_units.
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), CS_Krypton(), A2DVariableItem::dataField(), VariableItem::getCalibrationInfo(), DumpClient::printHeader(), nidas::core::Variable::toDOMElement(), nidas::core::Linear::toString(), and nidas::core::Polynomial::toString().
float nidas::dynld::isff::CS_Krypton::getV0 () const inline
Referenced by operator=().
const Variable* nidas::core::VariableConverter::getVariable () const inline inherited
References nidas::core::VariableConverter::_variable.
Referenced by nidas::core::VariableConverter::getDSMSensor().
CS_Krypton & CS_Krypton::operator= (const CS_Krypton & rhs)
References _calFile, getBias(), getKw(), getPathLength(), getV0(), setBias(), setKw(), setPathLength(), and setV0().
void CS_Krypton::readCalFile (dsm_time_t t) throw () virtual
Reimplemented from nidas::core::VariableConverter.
References nidas::core::floatNAN, nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_WARNING, and nidas::util::Exception::what().
Referenced by convert().
void nidas::dynld::isff::CS_Krypton::setBias (float val) inline
Parameters
val Bias (g/m^3) to be removed from data values.
Referenced by fromDOMElement(), and operator=().
void CS_Krypton::setCalFile (CalFile * val) virtual
Implements nidas::core::VariableConverter.
References _calFile.
void nidas::dynld::isff::CS_Krypton::setKw (float val) inline
Parameters
val Kw parameter from sensor calibration.
Referenced by fromDOMElement(), and operator=().
void nidas::dynld::isff::CS_Krypton::setPathLength (float val) inline
Parameters
val Pathlength of sensor, in cm.
Referenced by fromDOMElement(), and operator=().
void nidas::core::VariableConverter::setUnits (const std::string & val) inline inherited
References nidas::core::VariableConverter::_units.
Referenced by CS_Krypton(), nidas::core::Variable::fromDOMElement(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
void nidas::dynld::isff::CS_Krypton::setV0 (float val) inline
Parameters
val V0 value in millivolts.
Referenced by fromDOMElement(), and operator=().
void nidas::core::VariableConverter::setVariable (const Variable * val) inline inherited
References nidas::core::VariableConverter::_variable.
Referenced by nidas::core::Variable::fromDOMElement().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
std::string CS_Krypton::toString () const virtual
Generate a string description of this VariableConverter.
May be used in meta-data, for example Netcdf comment.
Implements nidas::core::VariableConverter.
Member Data Documentation
float nidas::dynld::isff::CS_Krypton::_bias private
Referenced by convert().
CalFile* nidas::dynld::isff::CS_Krypton::_calFile private
Referenced by getCalFile(), operator=(), setCalFile(), and ~CS_Krypton().
float nidas::dynld::isff::CS_Krypton::_Kw private
float nidas::dynld::isff::CS_Krypton::_logV0 private
Referenced by convert().
float nidas::dynld::isff::CS_Krypton::_pathLength private
float nidas::dynld::isff::CS_Krypton::_pathLengthKw private
Referenced by convert().
float nidas::dynld::isff::CS_Krypton::_V0 private
The documentation for this class was generated from the following files:
nidas/dynld/isff/CS_Krypton.h
nidas/dynld/isff/CS_Krypton.cc