nidas: nidas::core::DSMServerApp Class Reference
nidas::core::DSMServerApp Class Reference
#include <DSMServerApp.h>
Public Member Functions
DSMServerApp ()
~DSMServerApp ()
void initLogger ()
int initProcess (const char *argv0)
int run () throw ()
int parseRunstring (int argc, char **argv)
int usage (const char *argv0)
Send usage message to cerr.
void parseXMLConfigFile (const std::string &xmlFileName, Project &) throw (nidas::core::XMLException, nidas::util::InvalidParameterException,nidas::util::IOException)
Invoke a XMLCachingParser to parse the XML and initialize the Project.
void startXmlRpcThread () throw (nidas::util::Exception)
void killXmlRpcThread () throw ()
void startStatusThread (DSMServer *svr) throw (nidas::util::Exception)
void killStatusThread () throw ()
const std::string & getXMLFileName ()
What is the XML configuration file name.
std::string getUserName ()
uid_t getUserID ()
uid_t getGroupID ()
Dataset getDataset () throw (nidas::util::InvalidParameterException, XMLException)
Static Public Member Functions
static int main (int argc, char **argv) throw ()
Run DSMServerApp from the unix command line.
static DSMServerApp * getInstance ()
Private Types
enum runState { RUN, QUIT, RESTART, ERROR }
Private Member Functions
void setupSignals ()
Create a signal mask, and block those masked signals.
void waitForSignal (int timeoutSecs)
Unblock and wait for signals of interest up to timeoutSecs.
DSMServerApp (const DSMServerApp &)
Copy not needed.
DSMServerApp & operator= (const DSMServerApp &)
Assignment not needed.
Private Attributes
bool _debug
-d option.
std::string _xmlFileName
The xml file that is being used for configuration information.
std::string _configsXMLName
The xml file that contains all the project configurations, by date.
std::string _rafXML
std::string _isffXML
std::string _isfsXML
enum runState _runState
std::string _username
uid_t _userid
gid_t _groupid
DSMServerIntf * _xmlrpcThread
This thread provides XML-based Remote Procedure calls.
DSMServerStat * _statusThread
bool _externalControl
int _logLevel
bool _optionalProcessing
sigset_t _signalMask
pthread_t _myThreadId
std::string _datasetName
Static Private Attributes
static DSMServerApp * _instance = 0
Member Enumeration Documentation
enum nidas::core::DSMServerApp::runState private
Enumerator
RUN
QUIT
RESTART
ERROR
Constructor & Destructor Documentation
DSMServerApp::DSMServerApp ()
References setupSignals().
DSMServerApp::~DSMServerApp ()
References nidas::core::SamplePools::deleteInstance(), and nidas::core::SampleOutputRequestThread::destroyInstance().
nidas::core::DSMServerApp::DSMServerApp (const DSMServerApp &) private
Copy not needed.
Member Function Documentation
Dataset DSMServerApp::getDataset () throw (nidas::util::InvalidParameterException, XMLException)
References _datasetName, nidas::util::Process::expandEnvVars(), nidas::core::Datasets::getDataset(), nidas::core::Datasets::parseXML(), and nidas::core::Dataset::putenv().
Referenced by run().
uid_t nidas::core::DSMServerApp::getGroupID () inline
References _groupid.
Referenced by initProcess().
static DSMServerApp* nidas::core::DSMServerApp::getInstance () inline static
References _instance.
uid_t nidas::core::DSMServerApp::getUserID () inline
References _userid.
Referenced by initProcess().
std::string nidas::core::DSMServerApp::getUserName () inline
References _username.
Referenced by initProcess().
const std::string& nidas::core::DSMServerApp::getXMLFileName () inline
What is the XML configuration file name.
References _xmlFileName.
void DSMServerApp::initLogger ()
References _debug, _logLevel, nidas::util::LogScheme::addConfig(), nidas::util::Logger::createInstance(), nidas::util::LogConfig::level, nidas::util::Logger::setScheme(), nidas::util::LogScheme::setShowFields(), and nidas::util::Exception::toString().
Referenced by main().
int DSMServerApp::initProcess (const char * argv0)
References _debug, nidas::util::Process::addEffectiveCapability(), nidas::util::Process::checkPidFile(), nidas::util::FileSet::createDirectory(), DLOG, nidas::util::Process::getEffectiveCapability(), getGroupID(), getUserID(), getUserName(), PLOG, nidas::util::Exception::what(), and WLOG.
Referenced by main().
void DSMServerApp::killStatusThread () throw ()
References _statusThread, DLOG, nidas::util::Thread::isRunning(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::util::Exception::what(), and WLOG.
Referenced by run().
void DSMServerApp::killXmlRpcThread () throw ()
References _xmlrpcThread, DLOG, nidas::core::XmlRpcThread::interrupt(), nidas::util::Thread::join(), nidas::util::Exception::what(), and WLOG.
Referenced by main().
int DSMServerApp::main (int argc, char ** argv) throw () static
Run DSMServerApp from the unix command line.
References nidas::core::XMLCachingParser::destroyInstance(), initLogger(), initProcess(), killXmlRpcThread(), parseRunstring(), PLOG, run(), startXmlRpcThread(), nidas::core::XMLImplementation::terminate(), and nidas::util::Exception::what().
Referenced by main().
DSMServerApp& nidas::core::DSMServerApp::operator= (const DSMServerApp &) private
Assignment not needed.
int DSMServerApp::parseRunstring (int argc, char ** argv)
References _configsXMLName, _datasetName, _debug, _externalControl, _groupid, _isffXML, _isfsXML, _logLevel, _optionalProcessing, _rafXML, _userid, _username, _xmlFileName, nidas::util::Exception::errnoToString(), nidas::util::Process::expandEnvVars(), nidas::core::Version::getSoftwareVersion(), nidas::util::LOGGER_DEBUG, and usage().
Referenced by main().
void DSMServerApp::parseXMLConfigFile (const std::string & xmlFileName, Project &) throw (nidas::core::XMLException, nidas::util::InvalidParameterException, nidas::util::IOException)
Invoke a XMLCachingParser to parse the XML and initialize the Project.
References nidas::util::Process::expandEnvVars(), nidas::core::XMLCachingParser::getInstance(), NLOG, nidas::core::XMLCachingParser::parse(), nidas::core::XMLParser::setDOMDatatypeNormalization(), nidas::core::XMLParser::setDOMNamespaces(), nidas::core::XMLParser::setDOMValidateIfSchema(), nidas::core::XMLParser::setDOMValidation(), nidas::core::XMLParser::setXercesDoXInclude(), nidas::core::XMLParser::setXercesHandleMultipleImports(), nidas::core::XMLParser::setXercesSchema(), and nidas::core::XMLParser::setXercesSchemaFullChecking().
Referenced by run().
int DSMServerApp::run () throw ()
References _configsXMLName, _datasetName, _optionalProcessing, _runState, _xmlFileName, _xmlrpcThread, ERROR, nidas::core::Project::findServers(), nidas::core::ProjectConfigs::getConfig(), getDataset(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::util::SocketAddress::getPort(), nidas::core::DSMServer::getStatusSocketAddr(), nidas::core::ProjectConfig::getXMLName(), nidas::core::ProjectConfig::initProject(), nidas::core::DSMServer::interruptServices(), nidas::core::DSMServer::joinServices(), killStatusThread(), nidas::core::ProjectConfigs::parseXML(), parseXMLConfigFile(), PLOG, QUIT, RUN, nidas::core::DSMServer::scheduleServices(), nidas::core::Project::setConfigName(), nidas::core::Project::setDataset(), nidas::core::DSMServerIntf::setDSMServer(), nidas::core::DSMServer::setXMLConfigFileName(), nidas::util::Thread::start(), startStatusThread(), waitForSignal(), and nidas::util::Exception::what().
Referenced by main().
void DSMServerApp::setupSignals () private
Create a signal mask, and block those masked signals.
DSMEngine uses sigwait, and does not register asynchronous signal handlers.
References _signalMask.
Referenced by DSMServerApp().
void DSMServerApp::startStatusThread (DSMServer * svr) throw (nidas::util::Exception)
Referenced by run().
void DSMServerApp::startXmlRpcThread () throw (nidas::util::Exception)
References _externalControl, _xmlrpcThread, and nidas::util::Thread::start().
Referenced by main().
int DSMServerApp::usage (const char * argv0)
Send usage message to cerr.
References _isfsXML, and _rafXML.
Referenced by parseRunstring().
void DSMServerApp::waitForSignal (int timeoutSecs) private
Unblock and wait for signals of interest up to timeoutSecs.
After return, _runState will be set depending on the signal received.
References _runState, _signalMask, nidas::util::Exception::errnoToString(), ILOG, PLOG, QUIT, RESTART, timeoutSecs, and WLOG.
Referenced by run().
Member Data Documentation
std::string nidas::core::DSMServerApp::_configsXMLName private
The xml file that contains all the project configurations, by date.
Referenced by parseRunstring(), and run().
std::string nidas::core::DSMServerApp::_datasetName private
Referenced by getDataset(), parseRunstring(), and run().
bool nidas::core::DSMServerApp::_debug private
-d option.
If user wants messages on stderr rather than syslog.
Referenced by initLogger(), initProcess(), and parseRunstring().
bool nidas::core::DSMServerApp::_externalControl private
Referenced by parseRunstring(), and startXmlRpcThread().
gid_t nidas::core::DSMServerApp::_groupid private
Referenced by getGroupID(), and parseRunstring().
DSMServerApp * DSMServerApp::_instance = 0 static private
Referenced by getInstance().
std::string nidas::core::DSMServerApp::_isffXML private
Referenced by parseRunstring().
std::string nidas::core::DSMServerApp::_isfsXML private
Referenced by parseRunstring(), and usage().
int nidas::core::DSMServerApp::_logLevel private
Referenced by initLogger(), and parseRunstring().
pthread_t nidas::core::DSMServerApp::_myThreadId private
bool nidas::core::DSMServerApp::_optionalProcessing private
Referenced by parseRunstring(), and run().
std::string nidas::core::DSMServerApp::_rafXML private
Referenced by parseRunstring(), and usage().
enum runState nidas::core::DSMServerApp::_runState private
Referenced by run(), and waitForSignal().
sigset_t nidas::core::DSMServerApp::_signalMask private
Referenced by setupSignals(), and waitForSignal().
DSMServerStat* nidas::core::DSMServerApp::_statusThread private
Referenced by killStatusThread().
uid_t nidas::core::DSMServerApp::_userid private
Referenced by getUserID(), and parseRunstring().
std::string nidas::core::DSMServerApp::_username private
Referenced by getUserName(), and parseRunstring().
std::string nidas::core::DSMServerApp::_xmlFileName private
The xml file that is being used for configuration information.
Referenced by getXMLFileName(), parseRunstring(), and run().
DSMServerIntf* nidas::core::DSMServerApp::_xmlrpcThread private
This thread provides XML-based Remote Procedure calls.
Referenced by killXmlRpcThread(), run(), and startXmlRpcThread().
The documentation for this class was generated from the following files:
nidas/core/DSMServerApp.h
nidas/core/DSMServerApp.cc