nidas: Extract2D Class Reference
Extract2D Class Reference
Public Member Functions
Extract2D ()
int parseRunstring (int argc, char **argv) throw ()
int run () throw ()
void sendHeader (dsm_time_t, SampleOutput *out) throw (n_u::IOException)
Method called to write a header to an SampleOutput.
Static Public Member Functions
static void sigAction (int sig, siginfo_t *siginfo, void *)
static void setupSignals ()
static int main (int argc, char **argv) throw ()
static int usage (const char *argv0)
static void setDefaults (SampleInputHeader &header)
static void sendDefaultHeader (SampleOutput *output) throw (nidas::util::IOException)
Private Member Functions
size_t countParticles (Probe *probe, P2d_rec &record)
Count number of particles in a record, also report miss-aligned data.
size_t computeDiodeCount (Probe *probe, P2d_rec &record)
Sum occluded diodes along the flight path.
void setTimeStamp (P2d_rec &record, Sample *samp)
Decode Sample time tag and place into outgoing record.
Private Attributes
bool outputHeader
bool outputDiodeCount
Whether to output diode count histogram.
bool outputParticleCount
Whether to output particle count histogram.
bool copyAllRecords
Copy 100% of 2D records from source file to output file, no filtering.
string xmlFileName
list< string > inputFileNames
string outputFileName
int outputFileLength
SampleInputHeader header
set< dsm_sample_id_t > includeIds
set< dsm_sample_id_t > excludeIds
map< dsm_sample_id_t,
dsm_sample_id_t > newids
size_t minNumberParticlesRequired
Static Private Attributes
static bool interrupted = false
Constructor & Destructor Documentation
Extract2D::Extract2D ()
Member Function Documentation
size_t Extract2D::computeDiodeCount (Probe * probe, P2d_rec & record) private
Sum occluded diodes along the flight path.
This increments for the whole flight. Help find stuck bits.
Returns
the number of diodes that had positives in the record.
References P2d_rec::data, Probe::diodeCount, Fast2DsyncStr, FastOverloadSync, Probe::nDiodes, and P2D_DATA.
Referenced by run().
size_t Extract2D::countParticles (Probe * probe, P2d_rec & record) private
Count number of particles in a record, also report miss-aligned data.
References P2d_rec::data, Fast2DsyncStr, FastOverloadSync, nidas::core::DSMSensor::getCatalogName(), nidas::core::DSMSensor::getSuffix(), P2d_rec::hour, P2d_rec::minute, P2d_rec::msec, Probe::nDiodes, Probe::particleCount, Probe::recordCount, P2d_rec::second, and Probe::sensor.
Referenced by run().
int Extract2D::main (int argc, char ** argv) throw () static
References parseRunstring(), run(), and setupSignals().
Referenced by main().
int Extract2D::parseRunstring (int argc, char ** argv) throw ()
References usage().
Referenced by main().
int Extract2D::run () throw ()
References bigEndian, computeDiodeCount(), copyAllRecords, countParticles(), P2d_rec::data, Probe::diodeCount, _Tap2D_v2::div10, nidas::util::Process::expandEnvVars(), FILE_VERSION, nidas::core::Sample::freeReference(), nidas::core::DSMSensor::getCatalogName(), nidas::core::SampleInputHeader::getConfigName(), nidas::core::Sample::getConstVoidDataPtr(), nidas::core::Sample::getDataByteLength(), nidas::core::FileSet::getFileSet(), nidas::core::Sample::getId(), nidas::dynld::SampleInputStream::getInputHeader(), nidas::core::Parameter::getNumericValue(), nidas::core::DSMSensor::getParameter(), nidas::core::SampleInputHeader::getProjectName(), nidas::core::DSMConfig::getSensors(), nidas::core::Parameter::getStringValue(), nidas::core::DSMSensor::getSuffix(), nidas::core::SampleInputHeader::getSystemName(), nidas::core::DSMConfigIterator::hasNext(), Probe::hasOverloadCount, header, Probe::id, P2d_rec::id, includeIds, inputFileNames, nidas::util::EndianConverter::int32Value(), interrupted, minNumberParticlesRequired, Probe::nDiodes, nidas::core::DSMConfigIterator::next(), _Tap2D_v2::ntap, outputDiodeCount, outputFileName, outputHeader, outputParticleCount, P2d_rec::overld, overLoadSync, P2D_DATA, nidas::core::parseXMLConfigFile(), Probe::particleCount, nidas::dynld::SampleInputStream::readInputHeader(), nidas::dynld::SampleInputStream::readSample(), Probe::recordCount, Probe::rejectRecordCount, Probe::resolution, Probe::resolutionM, Probe::sensor, Probe::serialNumber, setTimeStamp(), P2d_rec::tas, TWOD_IMG_TYPE, TWOD_IMGv2_TYPE, TWOD_SOR_TYPE, nidas::util::Exception::what(), and xmlFileName.
Referenced by main().
void HeaderSource::sendDefaultHeader (SampleOutput * output) throw (nidas::util::IOException) static inherited
References nidas::core::SampleInputHeader::write().
Referenced by nidas::core::SampleOutputBase::createNextFile(), and nidas::dynld::raf::SyncRecordGenerator::sendHeader().
void Extract2D::sendHeader (dsm_time_t , SampleOutput * output) throw (n_u::IOException) virtual
Method called to write a header to an SampleOutput.
Derived classes implement as they see fit.
Implements nidas::core::HeaderSource.
void HeaderSource::setDefaults (SampleInputHeader & header) static inherited
References nidas::core::Version::getArchiveVersion(), nidas::core::Project::getInstance(), nidas::core::Version::getSoftwareVersion(), nidas::core::Project::getSystemName(), nidas::core::SampleInputHeader::setArchiveVersion(), nidas::core::SampleInputHeader::setConfigName(), nidas::core::SampleInputHeader::setConfigVersion(), nidas::core::SampleInputHeader::setProjectName(), nidas::core::SampleInputHeader::setSoftwareVersion(), and nidas::core::SampleInputHeader::setSystemName().
void Extract2D::setTimeStamp (P2d_rec & record, Sample * samp) private
Decode Sample time tag and place into outgoing record.
References P2d_rec::day, nidas::core::Sample::getTimeTag(), P2d_rec::hour, P2d_rec::minute, P2d_rec::month, P2d_rec::msec, P2d_rec::second, nidas::util::UTime::toTm(), and P2d_rec::year.
Referenced by run().
void Extract2D::setupSignals () static
References sigAction().
void Extract2D::sigAction (int sig, siginfo_t * siginfo, void *) static
References interrupted.
Referenced by setupSignals().
int Extract2D::usage (const char * argv0) static
Member Data Documentation
bool Extract2D::copyAllRecords private
Copy 100% of 2D records from source file to output file, no filtering.
Referenced by run().
set<dsm_sample_id_t> Extract2D::excludeIds private
SampleInputHeader Extract2D::header private
Referenced by run().
set<dsm_sample_id_t> Extract2D::includeIds private
Referenced by run().
list<string> Extract2D::inputFileNames private
Referenced by run().
bool Extract2D::interrupted = false static private
Referenced by run(), and sigAction().
size_t Extract2D::minNumberParticlesRequired private
Referenced by run().
map<dsm_sample_id_t,dsm_sample_id_t> Extract2D::newids private
bool Extract2D::outputDiodeCount private
Whether to output diode count histogram.
Referenced by run().
int Extract2D::outputFileLength private
string Extract2D::outputFileName private
Referenced by run().
bool Extract2D::outputHeader private
Referenced by run().
bool Extract2D::outputParticleCount private
Whether to output particle count histogram.
Referenced by run().
string Extract2D::xmlFileName private
Referenced by run().
The documentation for this class was generated from the following file:
nidas/apps/extract2d.cc