nidas: nidas::core::UnixIOChannel Class Reference
nidas::core::UnixIOChannel Class Reference
Simple implementation of an IOChannel, over an opened file descriptor.
#include <UnixIOChannel.h>
Public Member Functions
UnixIOChannel (const std::string &name, int fd)
Constructor.
~UnixIOChannel ()
Destructor.
UnixIOChannel * clone () const
Clone invokes default copy constructor.
void requestConnection (IOChannelRequester *rqstr) throw (nidas::util::IOException)
RequestConnection just returns connected immediately.
IOChannel * connect () throw (nidas::util::IOException)
Pretty simple, we're connected already.
void setNonBlocking (bool val) throw (nidas::util::IOException)
Set the state of O_NONBLOCK with fcntl system call.
bool isNonBlocking () const throw (nidas::util::IOException)
Do fcntl to determine value of O_NONBLOCK flag.
virtual bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
size_t read (void *buf, size_t len) throw (nidas::util::IOException)
Do the actual hardware read.
size_t write (const void *buf, size_t len) throw (nidas::util::IOException)
Do the actual hardware write.
size_t write (const struct iovec *iov, int iovcnt) throw (nidas::util::IOException)
Do the actual hardware write.
void close () throw (nidas::util::IOException)
int getFd () const
const std::string & getName () const
void setName (const std::string &val)
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual void setRequestType (enum McSocketRequest)
virtual enum McSocketRequest getRequestType () const
virtual int getReconnectDelaySecs () const
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual size_t getBufferSize () const throw ()
Return suggested buffer length.
virtual void flush () throw (nidas::util::IOException)
Default flush implementation does nothing.
virtual dsm_time_t createFile (dsm_time_t t, bool exact)
Request that an IOChannel open a new file, with a name based on a time.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static IOChannel * createIOChannel (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
UnixIOChannel (const UnixIOChannel &x)
Constructor.
Protected Attributes
std::string _name
int _fd
bool _newInput
Detailed Description
Simple implementation of an IOChannel, over an opened file descriptor.
Constructor & Destructor Documentation
nidas::core::UnixIOChannel::UnixIOChannel (const std::string & name, int fd) inline
Constructor.
Referenced by clone().
nidas::core::UnixIOChannel::~UnixIOChannel () inline
Destructor.
Does not close the device.
nidas::core::UnixIOChannel::UnixIOChannel (const UnixIOChannel & x) inline protected
Constructor.
Member Function Documentation
UnixIOChannel* nidas::core::UnixIOChannel::clone () const inline virtual
Clone invokes default copy constructor.
Implements nidas::core::IOChannel.
References UnixIOChannel().
void nidas::core::UnixIOChannel::close () throw (nidas::util::IOException) inline virtual
Implements nidas::core::IOChannel.
References _fd, and getName().
Referenced by HeaderUtil::run().
IOChannel* nidas::core::UnixIOChannel::connect () throw (nidas::util::IOException) inline virtual
Pretty simple, we're connected already.
Implements nidas::core::IOChannel.
virtual dsm_time_t nidas::core::IOChannel::createFile (dsm_time_t t, bool exact) inline virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::IOStream::createFile().
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) throw (nidas::util::InvalidParameterException) static inherited
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
virtual void nidas::core::IOChannel::flush () throw (nidas::util::IOException) inline virtual inherited
Default flush implementation does nothing.
Reimplemented in nidas::dynld::isff::GOESXmtr, nidas::dynld::isff::SE_GOESXmtr, and nidas::dynld::psql::PSQLChannel.
Referenced by nidas::core::SampleArchiver::disconnect(), and nidas::core::IOStream::flush().
void nidas::core::UnixIOChannel::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) inline virtual
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
virtual size_t nidas::core::IOChannel::getBufferSize () const throw () inline virtual inherited
Return suggested buffer length.
Reimplemented in nidas::core::Socket, nidas::core::DatagramSocket, and nidas::core::MultipleUDPSockets.
Referenced by nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::isff::PacketInputStream::PacketInputStream(), and nidas::dynld::SampleInputStream::SampleInputStream().
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
int nidas::core::UnixIOChannel::getFd () const inline virtual
Implements nidas::core::IOChannel.
References _fd.
const std::string& nidas::core::UnixIOChannel::getName () const inline virtual
Implements nidas::core::IOChannel.
References _name.
Referenced by close(), isNonBlocking(), read(), and write().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
virtual int nidas::core::IOChannel::getReconnectDelaySecs () const inline virtual inherited
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs().
virtual enum McSocketRequest nidas::core::IOChannel::getRequestType () const inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
virtual bool nidas::core::UnixIOChannel::isNewInput () const inline virtual
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented from nidas::core::IOChannel.
References _newInput.
bool UnixIOChannel::isNonBlocking () const throw (nidas::util::IOException) virtual
Do fcntl to determine value of O_NONBLOCK flag.
Implements nidas::core::IOChannel.
References _fd, and getName().
size_t nidas::core::UnixIOChannel::read (void * buf, size_t len) throw (nidas::util::IOException) inline virtual
Do the actual hardware read.
Implements nidas::core::IOChannel.
References _fd, _newInput, getName(), and len.
void nidas::core::UnixIOChannel::requestConnection (IOChannelRequester * rqstr) throw (nidas::util::IOException) inline virtual
RequestConnection just returns connected immediately.
Implements nidas::core::IOChannel.
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
Referenced by nidas::core::MultipleUDPSockets::connect(), nidas::core::Socket::connect(), nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::McSocket::connected(), and nidas::core::McSocketUDP::connected().
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
void nidas::core::UnixIOChannel::setName (const std::string & val) inline virtual
Implements nidas::core::IOChannel.
References _name.
void UnixIOChannel::setNonBlocking (bool val) throw (nidas::util::IOException) virtual
Set the state of O_NONBLOCK with fcntl system call.
Implements nidas::core::IOChannel.
virtual void nidas::core::IOChannel::setRequestType (enum McSocketRequest) inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::XMLConfigService::schedule().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
size_t nidas::core::UnixIOChannel::write (const void * buf, size_t len) throw (nidas::util::IOException) inline virtual
Do the actual hardware write.
Implements nidas::core::IOChannel.
References _fd, _newInput, getName(), and len.
size_t nidas::core::UnixIOChannel::write (const struct iovec * iov, int iovcnt) throw (nidas::util::IOException) inline virtual
Do the actual hardware write.
Implements nidas::core::IOChannel.
References _fd, _newInput, and getName().
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
int nidas::core::UnixIOChannel::_fd protected
Referenced by close(), getFd(), isNonBlocking(), read(), and write().
std::string nidas::core::UnixIOChannel::_name protected
Referenced by getName(), and setName().
bool nidas::core::UnixIOChannel::_newInput protected
Referenced by isNewInput(), read(), and write().
The documentation for this class was generated from the following files:
nidas/core/UnixIOChannel.h
nidas/core/UnixIOChannel.cc