nidas: config::AddA2DVariableComboDialog Class Reference
config::AddA2DVariableComboDialog Class Reference
#include <AddA2DVariableComboDialog.h>
Public Slots
void accept ()
void reject ()
void show (NidasModel *model, QModelIndexList indexList)
void dialogSetup (const QString &variable)
bool setup (std::string filename)
Public Member Functions
AddA2DVariableComboDialog (QWidget *parent)
~AddA2DVariableComboDialog ()
void setDocument (Document *document)
Protected Attributes
Document * _document
Private Member Functions
void SetUpChannelBox ()
void showVoltErr (int32_t vDBvLow, int32_t vDBvHi, int confIndx)
void showSRErr (int vDBsr, int srIndx)
QString removeSuffix (const QString &varName)
QString getSuffix (const QString &varName)
void checkUnitsAndCalCoefs ()
void clearForm ()
bool openVarDB (std::string filename)
bool fileExists (QString filename)
void buildA2DVarDB ()
void setCalLabels ()
void clearCalLabels ()
Private Attributes
QModelIndexList _indexList
NidasModel * _model
bool _addMode
int _origSRBoxIndex
VDBFile * _vardb
Constructor & Destructor Documentation
AddA2DVariableComboDialog::AddA2DVariableComboDialog (QWidget * parent)
References _unitRegEx(), and _vardb.
config::AddA2DVariableComboDialog::~AddA2DVariableComboDialog () inline
Member Function Documentation
void AddA2DVariableComboDialog::accept () slot
References _document, _indexList, _model, _origSRBoxIndex, Document::addA2DVariable(), NidasModel::removeIndexes(), Document::setIsChanged(), Document::setIsChangedBig(), and nidas::util::Exception::toString().
void AddA2DVariableComboDialog::buildA2DVarDB () private
References _vardb, and dialogSetup().
Referenced by setup().
void AddA2DVariableComboDialog::checkUnitsAndCalCoefs () private
void AddA2DVariableComboDialog::clearCalLabels () private
Referenced by show().
void AddA2DVariableComboDialog::clearForm () private
Referenced by dialogSetup(), and show().
void AddA2DVariableComboDialog::dialogSetup (const QString & variable) slot
References _addMode, _vardb, clearForm(), SetUpChannelBox(), showSRErr(), and showVoltErr().
Referenced by buildA2DVarDB().
bool AddA2DVariableComboDialog::fileExists (QString filename) private
References buffer.
QString AddA2DVariableComboDialog::getSuffix (const QString & varName) private
Referenced by show().
bool AddA2DVariableComboDialog::openVarDB (std::string filename) private
References _vardb.
Referenced by setup().
void config::AddA2DVariableComboDialog::reject () inline slot
QString AddA2DVariableComboDialog::removeSuffix (const QString & varName) private
Referenced by show().
void AddA2DVariableComboDialog::setCalLabels () private
Referenced by show().
void config::AddA2DVariableComboDialog::setDocument (Document * document) inline
References _document.
Referenced by ConfigWindow::openFile().
bool AddA2DVariableComboDialog::setup (std::string filename) slot
References buildA2DVarDB(), and openVarDB().
Referenced by ConfigWindow::openFile().
void AddA2DVariableComboDialog::SetUpChannelBox () private
References _document, and Document::getAvailableA2DChannels().
Referenced by dialogSetup(), and show().
void AddA2DVariableComboDialog::show (NidasModel * model, QModelIndexList indexList) slot
References _addMode, _indexList, _model, _origSRBoxIndex, clearCalLabels(), clearForm(), A2DVariableItem::getA2DChannel(), A2DVariableItem::getBipolar(), A2DVariableItem::getCalibrationInfo(), A2DVariableItem::getGain(), NidasModel::getItem(), A2DVariableItem::getLongName(), A2DVariableItem::getRate(), getSuffix(), A2DVariableItem::name(), rate, removeSuffix(), setCalLabels(), and SetUpChannelBox().
Referenced by ConfigWindow::addA2DVariableCombo(), and ConfigWindow::editA2DVariableCombo().
void AddA2DVariableComboDialog::showSRErr (int vDBsr, int srIndx) private
Referenced by dialogSetup().
void AddA2DVariableComboDialog::showVoltErr (int32_t vDBvLow, int32_t vDBvHi, int confIndx) private
Referenced by dialogSetup().
Member Data Documentation
bool config::AddA2DVariableComboDialog::_addMode private
Referenced by dialogSetup(), and show().
Document* config::AddA2DVariableComboDialog::_document protected
Referenced by accept(), setDocument(), and SetUpChannelBox().
QModelIndexList config::AddA2DVariableComboDialog::_indexList private
Referenced by accept(), and show().
NidasModel* config::AddA2DVariableComboDialog::_model private
Referenced by accept(), and show().
int config::AddA2DVariableComboDialog::_origSRBoxIndex private
Referenced by accept(), and show().
VDBFile* config::AddA2DVariableComboDialog::_vardb private
Referenced by AddA2DVariableComboDialog(), buildA2DVarDB(), dialogSetup(), and openVarDB().
The documentation for this class was generated from the following files:
nidas/apps/config/AddA2DVariableComboDialog.h
nidas/apps/config/AddA2DVariableComboDialog.cc