nidas: nidas::core::MessageStreamScanner Class Reference
nidas::core::MessageStreamScanner Class Reference
A SampleScanner which supports the set/get of message separation parameters and extracts samples from the internal buffer by recognizing separators in the message stream.
#include <SampleScanner.h>
Public Member Functions
MessageStreamScanner (int bufsize=2048)
void setMessageParameters (unsigned int len, const std::string &val, bool eom) throw (nidas::util::InvalidParameterException)
Set the parameters associated with scanning of character messages.
const std::string & getMessageSeparator () const
Get message separator string.
const std::string getBackslashedMessageSeparator () const
Get message separator with backslash sequences added back.
bool getMessageSeparatorAtEOM () const
unsigned int getMessageLength () const
Returns 0.
void setNullTerminate (bool val)
bool getNullTerminate () const
Should the SampleScanner append a null character, '\0', to the messages.
Sample * nextSample (DSMSensor *sensor)
Extract the next sample from the buffer.
size_t readBuffer (DSMSensor *sensor, bool &exhausted) throw (nidas::util::IOException)
Read from the sensor into the internal buffer of this SampleScanner.
size_t readBuffer (DSMSensor *sensor, bool &exhausted, int msecTimeout) throw (nidas::util::IOException)
Read from the sensor into the internal buffer of this SampleScanner, providing a timeout in milliseconds.
virtual void init ()
Initialize the scanner.
void setUsecsPerByte (int val)
int getUsecsPerByte () const
virtual void clearBuffer ()
unsigned int getBytesInBuffer () const
virtual void resetStatistics ()
virtual void calcStatistics (unsigned int periodUsec)
Update the sensor sampling statistics: samples/sec, bytes/sec, min/max sample size, that can be accessed via getObservedSamplingRate(), getObservedDataRate() etc.
unsigned int getMaxSampleLength () const
unsigned int getMinSampleLength () const
unsigned int getBadTimeTagCount () const
float getObservedSamplingRate () const
float getObservedDataRate () const
void addNumBytesToStats (size_t val)
void addSampleToStats (unsigned int val)
void incrementBadTimeTags ()
Protected Member Functions
virtual Sample * nextSampleSepBOM (DSMSensor *sensor)
Method to read input and break it into samples where the message separator occurs at the beginning of the message.
virtual Sample * nextSampleSepEOM (DSMSensor *sensor)
Method to read input and break it into samples where the message separator occurs at the end of the message.
Sample * nextSampleByLength (DSMSensor *sensor)
Method to read input and break it into samples strictly by record length.
Sample * requestBiggerSample (unsigned int nc)
If a new sample can be allocated without exceeding MAX_MESSAGE_STREAM_SAMPLE_SIZE then get a new, larger sample, copying the timetag, id and existing data from the current sample, and return null.
Protected Attributes
Sample *(MessageStreamScanner::* _nextSampleFunc)(DSMSensor *)
dsm_time_t _tfirstchar
const unsigned int MAX_MESSAGE_STREAM_SAMPLE_SIZE
int _separatorCnt
dsm_time_t _bomtt
int _sampleOverflows
unsigned int _sampleLengthAlloc
Size of samples to allocate.
bool _nullTerminate
int _nsmallSamples
Count of number of consecutive samples smaller than _sampleLengthAlloc.
unsigned int _outSampLengthAlloc
Number of bytes allocated in data portion of current output sample.
const unsigned int BUFSIZE
Buffer size for reading from sensor.
char * _buffer
unsigned int _bufhead
unsigned int _buftail
Sample * _osamp
struct dsm_sample _header
unsigned int _outSampRead
unsigned int _outSampToRead
char * _outSampDataPtr
std::string _messageSeparator
int _messageLength
bool _separatorAtEOM
char * _separator
messageSeparator in a C string.
int _separatorLen
Length of messageSeparator.
Detailed Description
A SampleScanner which supports the set/get of message separation parameters and extracts samples from the internal buffer by recognizing separators in the message stream.
Timetags are applied to the samples based on the time of receipt of each chunk of data, corrected backwards by the computed tranmission time of each byte in the chunk.
See Also
setUsecsPerByte().
Constructor & Destructor Documentation
MessageStreamScanner::MessageStreamScanner (int bufsize = 2048)
Member Function Documentation
void nidas::core::SampleScanner::addNumBytesToStats (size_t val) inline inherited
References nidas::core::SampleScanner::_nbytes.
void nidas::core::SampleScanner::addSampleToStats (unsigned int val) inline inherited
References nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_maxSampleLength, nidas::core::SampleScanner::_minSampleLength, and nidas::core::SampleScanner::_nsamples.
Referenced by nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and requestBiggerSample().
void SampleScanner::calcStatistics (unsigned int periodUsec) virtual inherited
Update the sensor sampling statistics: samples/sec, bytes/sec, min/max sample size, that can be accessed via getObservedSamplingRate(), getObservedDataRate() etc.
Should be called every periodUsec by a user of this sensor.
Parameters
periodUsec Statistics period.
References nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_dataRateObs, nidas::core::SampleScanner::_maxSampleLength, nidas::core::SampleScanner::_minSampleLength, nidas::core::SampleScanner::_nbytes, nidas::core::SampleScanner::_nsamples, nidas::core::SampleScanner::_reportIndex, nidas::core::SampleScanner::_sampleRateObs, and USECS_PER_SEC.
Referenced by nidas::core::DSMSensor::calcStatistics().
void SampleScanner::clearBuffer () virtual inherited
References nidas::core::SampleScanner::_bufhead, and nidas::core::SampleScanner::_buftail.
Referenced by nidas::core::DSMSensor::clearBuffer().
const string MessageStreamScanner::getBackslashedMessageSeparator () const virtual
Get message separator with backslash sequences added back.
Reimplemented from nidas::core::SampleScanner.
References nidas::core::SampleScanner::_messageSeparator, and nidas::util::addBackslashSequences().
unsigned int nidas::core::SampleScanner::getBadTimeTagCount () const inline inherited
References nidas::core::SampleScanner::_badTimeTags.
Referenced by nidas::core::DSMSensor::getBadTimeTagCount().
unsigned int nidas::core::SampleScanner::getBytesInBuffer () const inline inherited
References nidas::core::SampleScanner::_bufhead, and nidas::core::SampleScanner::_buftail.
unsigned int nidas::core::SampleScanner::getMaxSampleLength () const inline inherited
References nidas::core::SampleScanner::_maxSampleLength, and nidas::core::SampleScanner::_reportIndex.
Referenced by nidas::core::DSMSensor::getMaxSampleLength().
unsigned int nidas::core::MessageStreamScanner::getMessageLength () const inline virtual
Returns 0.
Reimplemented from nidas::core::SampleScanner.
References nidas::core::SampleScanner::_messageLength.
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
const std::string& nidas::core::MessageStreamScanner::getMessageSeparator () const inline virtual
Get message separator string.
Any backslash sequences will have been replaced by their intended value.
Reimplemented from nidas::core::SampleScanner.
References nidas::core::SampleScanner::_messageSeparator.
bool nidas::core::MessageStreamScanner::getMessageSeparatorAtEOM () const inline virtual
Reimplemented from nidas::core::SampleScanner.
References nidas::core::SampleScanner::_separatorAtEOM.
unsigned int nidas::core::SampleScanner::getMinSampleLength () const inline inherited
References nidas::core::SampleScanner::_maxSampleLength, nidas::core::SampleScanner::_minSampleLength, and nidas::core::SampleScanner::_reportIndex.
Referenced by nidas::core::DSMSensor::getMinSampleLength().
bool nidas::core::MessageStreamScanner::getNullTerminate () const inline virtual
Should the SampleScanner append a null character, '\0', to the messages.
Reimplemented from nidas::core::SampleScanner.
References _nullTerminate.
Referenced by nextSampleSepBOM(), nextSampleSepEOM(), and requestBiggerSample().
float SampleScanner::getObservedDataRate () const inherited
References nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_dataRateObs, nidas::core::SampleScanner::_initialTimeSecs, nidas::core::SampleScanner::_nbytes, and nidas::core::SampleScanner::_reportIndex.
Referenced by nidas::core::DSMSensor::getObservedDataRate().
float SampleScanner::getObservedSamplingRate () const inherited
References nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_initialTimeSecs, nidas::core::SampleScanner::_nsamples, nidas::core::SampleScanner::_reportIndex, and nidas::core::SampleScanner::_sampleRateObs.
Referenced by nidas::core::DSMSensor::getObservedSamplingRate().
int nidas::core::SampleScanner::getUsecsPerByte () const inline inherited
References nidas::core::SampleScanner::_usecsPerByte.
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
void nidas::core::SampleScanner::incrementBadTimeTags () inline inherited
References nidas::core::SampleScanner::_badTimeTags.
Referenced by nidas::core::DriverSampleScanner::nextSample().
void SampleScanner::init () virtual inherited
Initialize the scanner.
Must be called by a user of SampleScanner prior to calling readSamples().
References nidas::core::SampleScanner::resetStatistics().
Sample* nidas::core::MessageStreamScanner::nextSample (DSMSensor * sensor) inline virtual
Extract the next sample from the buffer.
Returns NULL if there are no more samples in the buffer.
Implements nidas::core::SampleScanner.
References _nextSampleFunc.
Sample * MessageStreamScanner::nextSampleByLength (DSMSensor * sensor) protected
Method to read input and break it into samples strictly by record length.
References nidas::core::SampleScanner::_buffer, nidas::core::SampleScanner::_bufhead, nidas::core::SampleScanner::_buftail, nidas::core::SampleScanner::_osamp, nidas::core::SampleScanner::_outSampDataPtr, _outSampLengthAlloc, nidas::core::SampleScanner::_outSampRead, _sampleLengthAlloc, _separatorCnt, _tfirstchar, nidas::core::SampleScanner::addSampleToStats(), nidas::core::Sample::getAllocByteLength(), nidas::core::DSMSensor::getId(), getMessageLength(), nidas::core::SampleScanner::getUsecsPerByte(), nidas::core::Sample::getVoidDataPtr(), requestBiggerSample(), nidas::core::Sample::setId(), and nidas::core::Sample::setTimeTag().
Referenced by setMessageParameters().
Sample * MessageStreamScanner::nextSampleSepBOM (DSMSensor * sensor) protected virtual
Method to read input and break it into samples where the message separator occurs at the beginning of the message.
References _bomtt, nidas::core::SampleScanner::_buffer, nidas::core::SampleScanner::_bufhead, nidas::core::SampleScanner::_buftail, _nsmallSamples, nidas::core::SampleScanner::_osamp, nidas::core::SampleScanner::_outSampDataPtr, _outSampLengthAlloc, nidas::core::SampleScanner::_outSampRead, _sampleLengthAlloc, nidas::core::SampleScanner::_separator, _separatorCnt, nidas::core::SampleScanner::_separatorLen, _tfirstchar, nidas::core::SampleScanner::addSampleToStats(), nidas::core::Sample::getAllocByteLength(), nidas::core::DSMSensor::getId(), getMessageLength(), getNullTerminate(), nidas::core::SampleScanner::getUsecsPerByte(), nidas::core::Sample::getVoidDataPtr(), MAX_MESSAGE_STREAM_SAMPLE_SIZE, requestBiggerSample(), nidas::core::Sample::setDataLength(), nidas::core::Sample::setId(), and nidas::core::Sample::setTimeTag().
Referenced by setMessageParameters().
Sample * MessageStreamScanner::nextSampleSepEOM (DSMSensor * sensor) protected virtual
Method to read input and break it into samples where the message separator occurs at the end of the message.
References nidas::core::SampleScanner::_buffer, nidas::core::SampleScanner::_bufhead, nidas::core::SampleScanner::_buftail, _nsmallSamples, nidas::core::SampleScanner::_osamp, nidas::core::SampleScanner::_outSampDataPtr, _outSampLengthAlloc, nidas::core::SampleScanner::_outSampRead, _sampleLengthAlloc, nidas::core::SampleScanner::_separator, _separatorCnt, nidas::core::SampleScanner::_separatorLen, _tfirstchar, nidas::core::SampleScanner::addSampleToStats(), nidas::core::Sample::getAllocByteLength(), nidas::core::DSMSensor::getId(), getMessageLength(), getNullTerminate(), nidas::core::SampleScanner::getUsecsPerByte(), nidas::core::Sample::getVoidDataPtr(), MAX_MESSAGE_STREAM_SAMPLE_SIZE, requestBiggerSample(), nidas::core::Sample::setDataLength(), nidas::core::Sample::setId(), and nidas::core::Sample::setTimeTag().
Referenced by setMessageParameters().
size_t MessageStreamScanner::readBuffer (DSMSensor * sensor, bool & exhausted) throw (nidas::util::IOException) virtual
Read from the sensor into the internal buffer of this SampleScanner.
Reimplemented from nidas::core::SampleScanner.
References nidas::util::getSystemTime(), and nidas::core::SampleScanner::readBuffer().
size_t MessageStreamScanner::readBuffer (DSMSensor * sensor, bool & exhausted, int msecTimeout) throw (nidas::util::IOException) virtual
Read from the sensor into the internal buffer of this SampleScanner, providing a timeout in milliseconds.
This will throw nidas::util::IOTimeoutException if the read fails due to a timeout.
Reimplemented from nidas::core::SampleScanner.
References nidas::util::getSystemTime(), and nidas::core::SampleScanner::readBuffer().
Sample * MessageStreamScanner::requestBiggerSample (unsigned int nc) protected
If a new sample can be allocated without exceeding MAX_MESSAGE_STREAM_SAMPLE_SIZE then get a new, larger sample, copying the timetag, id and existing data from the current sample, and return null.
The data members _osamp, and _outSampDataPtr are updated to point to the new sample. Otherwise, since we've reached the MAX limit, more data will not be added to the sample, so return a pointer to the existing max'd out sample, which should then be returned as the value of the nextSample() method.
References nidas::core::SampleScanner::_osamp, nidas::core::SampleScanner::_outSampDataPtr, _outSampLengthAlloc, nidas::core::SampleScanner::_outSampRead, _sampleOverflows, nidas::core::SampleScanner::addSampleToStats(), nidas::core::Sample::freeReference(), nidas::core::Sample::getAllocByteLength(), nidas::core::Sample::getId(), getNullTerminate(), nidas::core::Sample::getTimeTag(), nidas::core::Sample::getVoidDataPtr(), nidas::core::SampleT< DataT >::getVoidDataPtr(), MAX_MESSAGE_STREAM_SAMPLE_SIZE, nidas::core::Sample::setDataLength(), nidas::core::Sample::setId(), and nidas::core::Sample::setTimeTag().
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
void SampleScanner::resetStatistics () virtual inherited
References nidas::core::SampleScanner::_badTimeTags, nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_dataRateObs, nidas::core::SampleScanner::_initialTimeSecs, nidas::core::SampleScanner::_maxSampleLength, nidas::core::SampleScanner::_minSampleLength, nidas::core::SampleScanner::_nbytes, nidas::core::SampleScanner::_nsamples, nidas::core::SampleScanner::_reportIndex, and nidas::core::SampleScanner::_sampleRateObs.
Referenced by nidas::core::SampleScanner::init(), and nidas::core::SampleScanner::SampleScanner().
void MessageStreamScanner::setMessageParameters (unsigned int len, const std::string & val, bool eom) throw (nidas::util::InvalidParameterException) virtual
Set the parameters associated with scanning of character messages.
Implements nidas::core::SampleScanner.
References len, nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and nidas::util::replaceBackslashSequences().
Referenced by nidas::dynld::GPS_NMEA_Serial::buildSampleScanner().
void nidas::core::MessageStreamScanner::setNullTerminate (bool val) inline
References _nullTerminate.
Referenced by nidas::dynld::GPS_NMEA_Serial::buildSampleScanner(), and nidas::core::CharacterSensor::buildSampleScanner().
void nidas::core::SampleScanner::setUsecsPerByte (int val) inline inherited
References nidas::core::SampleScanner::_usecsPerByte.
Referenced by nidas::dynld::GPS_NMEA_Serial::buildSampleScanner(), and nidas::core::SerialSensor::buildSampleScanner().
Member Data Documentation
dsm_time_t nidas::core::MessageStreamScanner::_bomtt protected
Referenced by nextSampleSepBOM().
char* nidas::core::SampleScanner::_buffer protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and nidas::core::SampleScanner::~SampleScanner().
unsigned int nidas::core::SampleScanner::_bufhead protected inherited
Referenced by nidas::core::SampleScanner::clearBuffer(), nidas::core::SampleScanner::getBytesInBuffer(), nidas::core::DriverSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
unsigned int nidas::core::SampleScanner::_buftail protected inherited
Referenced by nidas::core::SampleScanner::clearBuffer(), nidas::core::SampleScanner::getBytesInBuffer(), nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
struct dsm_sample nidas::core::SampleScanner::_header protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample().
int nidas::core::SampleScanner::_messageLength protected inherited
Referenced by nidas::core::MessageSampleScanner::getMessageLength(), and getMessageLength().
std::string nidas::core::SampleScanner::_messageSeparator protected inherited
Referenced by nidas::core::MessageSampleScanner::getBackslashedMessageSeparator(), getBackslashedMessageSeparator(), nidas::core::MessageSampleScanner::getMessageSeparator(), and getMessageSeparator().
Sample*(MessageStreamScanner::* nidas::core::MessageStreamScanner::_nextSampleFunc)(DSMSensor *) protected
Referenced by nextSample().
int nidas::core::MessageStreamScanner::_nsmallSamples protected
Count of number of consecutive samples smaller than _sampleLengthAlloc.
Referenced by nextSampleSepBOM(), and nextSampleSepEOM().
bool nidas::core::MessageStreamScanner::_nullTerminate protected
Referenced by getNullTerminate(), and setNullTerminate().
Sample* nidas::core::SampleScanner::_osamp protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), requestBiggerSample(), and nidas::core::SampleScanner::~SampleScanner().
char* nidas::core::SampleScanner::_outSampDataPtr protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and requestBiggerSample().
unsigned int nidas::core::MessageStreamScanner::_outSampLengthAlloc protected
Number of bytes allocated in data portion of current output sample.
Referenced by nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and requestBiggerSample().
unsigned int nidas::core::SampleScanner::_outSampRead protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample(), nextSampleByLength(), nextSampleSepBOM(), nextSampleSepEOM(), and requestBiggerSample().
unsigned int nidas::core::SampleScanner::_outSampToRead protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample().
unsigned int nidas::core::MessageStreamScanner::_sampleLengthAlloc protected
Size of samples to allocate.
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
int nidas::core::MessageStreamScanner::_sampleOverflows protected
Referenced by requestBiggerSample().
char* nidas::core::SampleScanner::_separator protected inherited
messageSeparator in a C string.
Referenced by nextSampleSepBOM(), nextSampleSepEOM(), and nidas::core::SampleScanner::~SampleScanner().
bool nidas::core::SampleScanner::_separatorAtEOM protected inherited
Referenced by nidas::core::MessageSampleScanner::getMessageSeparatorAtEOM(), and getMessageSeparatorAtEOM().
int nidas::core::MessageStreamScanner::_separatorCnt protected
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
int nidas::core::SampleScanner::_separatorLen protected inherited
Length of messageSeparator.
Referenced by nextSampleSepBOM(), and nextSampleSepEOM().
dsm_time_t nidas::core::MessageStreamScanner::_tfirstchar protected
Referenced by nextSampleByLength(), nextSampleSepBOM(), and nextSampleSepEOM().
const unsigned int nidas::core::SampleScanner::BUFSIZE protected inherited
Buffer size for reading from sensor.
const unsigned int nidas::core::MessageStreamScanner::MAX_MESSAGE_STREAM_SAMPLE_SIZE protected
Referenced by nextSampleSepBOM(), nextSampleSepEOM(), and requestBiggerSample().
The documentation for this class was generated from the following files:
nidas/core/SampleScanner.h
nidas/core/SampleScanner.cc