nidas: config::AddDSMComboDialog Class Reference
config::AddDSMComboDialog Class Reference
#include <AddDSMComboDialog.h>
Public Slots
void reject ()
void show (NidasModel *model, QModelIndexList indexList)
bool setUpDialog ()
void existingDSM (DSMItem *dsmItem)
Public Member Functions
AddDSMComboDialog (QWidget *parent=0)
~AddDSMComboDialog ()
void setDocument (Document *document)
void accept ()
Protected Attributes
QMessageBox * _errorMessage
Document * _document
Private Attributes
QModelIndexList _indexList
NidasModel * _model
Constructor & Destructor Documentation
AddDSMComboDialog::AddDSMComboDialog (QWidget * parent = 0)
References _dsmIdRegEx(), _dsmLocRegEx(), _dsmNameRegEx(), and _errorMessage.
config::AddDSMComboDialog::~AddDSMComboDialog () inline
Member Function Documentation
void AddDSMComboDialog::accept ()
References _document, _errorMessage, _indexList, Document::addDSM(), Document::setIsChanged(), nidas::util::Exception::toString(), and Document::updateDSM().
void AddDSMComboDialog::existingDSM (DSMItem * dsmItem) slot
References DSMItem::getDSMConfig(), nidas::core::DSMConfig::getId(), nidas::core::DSMConfig::getLocation(), and nidas::core::DSMConfig::getName().
Referenced by setUpDialog().
void config::AddDSMComboDialog::reject () inline slot
void config::AddDSMComboDialog::setDocument (Document * document) inline
References _document.
Referenced by ConfigWindow::openFile().
bool AddDSMComboDialog::setUpDialog () slot
References _document, _errorMessage, _indexList, _model, existingDSM(), NidasModel::getItem(), Document::getNextDSMId(), and nidas::util::Exception::toString().
Referenced by show().
void AddDSMComboDialog::show (NidasModel * model, QModelIndexList indexList) slot
References _indexList, _model, and setUpDialog().
Referenced by ConfigWindow::addDSMCombo(), and ConfigWindow::editDSMCombo().
Member Data Documentation
Document* config::AddDSMComboDialog::_document protected
Referenced by accept(), setDocument(), and setUpDialog().
QMessageBox* config::AddDSMComboDialog::_errorMessage protected
Referenced by accept(), AddDSMComboDialog(), and setUpDialog().
QModelIndexList config::AddDSMComboDialog::_indexList private
Referenced by accept(), setUpDialog(), and show().
NidasModel* config::AddDSMComboDialog::_model private
Referenced by setUpDialog(), and show().
The documentation for this class was generated from the following files:
nidas/apps/config/AddDSMComboDialog.h
nidas/apps/config/AddDSMComboDialog.cc