nidas: nidas::core::Polynomial Class Reference
nidas::core::Polynomial Class Reference
#include <VariableConverter.h>
Public Member Functions
Polynomial ()
Polynomial (const Polynomial &)
Copy constructor.
Polynomial & operator= (const Polynomial &)
~Polynomial ()
Polynomial * clone () const
void setCalFile (CalFile *)
CalFile * getCalFile ()
const CalFile * getCalFile () const
void setCoefficients (const std::vector< float > &vals)
void setCoefficients (const float *fp, unsigned int n)
const std::vector< float > & getCoefficients () const
const float * getCoefficients (unsigned int &n) const
void readCalFile (dsm_time_t t) throw ()
double convert (dsm_time_t t, double val)
std::string toString () const
Generate a string description of this VariableConverter.
void fromString (const std::string &) throw (nidas::util::InvalidParameterException)
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
void setUnits (const std::string &val)
virtual const std::string & getUnits () const
void setVariable (const Variable *val)
const Variable * getVariable () const
const DSMSensor * getDSMSensor () const
const DSMConfig * getDSMConfig () const
void addParameter (Parameter *val)
Add a parameter to this VariableConverter.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static double eval (double x, float *p, unsigned int np)
static VariableConverter * createVariableConverter (XDOMElement &child)
static VariableConverter * createFromString (const std::string &) throw (nidas::util::InvalidParameterException)
static const XMLCh * getNamespaceURI ()
Private Attributes
dsm_time_t _calTime
std::vector< float > _coefs
CalFile * _calFile
Static Private Attributes
static const int MAX_NUM_COEFS = 6
Maximum number of coefficients that can be read from a CalFile.
Constructor & Destructor Documentation
Polynomial::Polynomial ()
References setCoefficients().
Referenced by clone().
Polynomial::Polynomial (const Polynomial & x)
Copy constructor.
References _calFile, getCoefficients(), and setCoefficients().
Polynomial::~Polynomial ()
References _calFile.
Member Function Documentation
void VariableConverter::addParameter (Parameter * val) inherited
Add a parameter to this VariableConverter.
VariableConverter will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::VariableConverter::_constParameters, nidas::core::VariableConverter::_parameters, and nidas::core::Parameter::getName().
Referenced by nidas::core::VariableConverter::operator=(), and nidas::core::VariableConverter::VariableConverter().
Polynomial * Polynomial::clone () const virtual
Implements nidas::core::VariableConverter.
Reimplemented in nidas::dynld::isff::RebsLinear.
References Polynomial().
double Polynomial::convert (dsm_time_t t, double val) virtual
Implements nidas::core::VariableConverter.
References _coefs, eval(), and readCalFile().
VariableConverter * VariableConverter::createFromString (const std::string & str) throw (nidas::util::InvalidParameterException) static inherited
References nidas::core::VariableConverter::fromString().
VariableConverter * VariableConverter::createVariableConverter (XDOMElement & child) static inherited
References nidas::core::DOMObjectFactory::createObject(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::XDOMElement::getNodeName(), and nidas::util::Exception::what().
Referenced by nidas::core::Variable::fromDOMElement().
double nidas::core::Polynomial::eval (double x, float * p, unsigned int np) inline static
Referenced by nidas::dynld::ParoSci_202BG_Calibration::computePressure(), nidas::dynld::ParoSci_202BG_Calibration::computeTemperature(), and convert().
void Polynomial::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Reimplemented from nidas::core::VariableConverter.
References nidas::core::VariableConverter::fromDOMElement(), and nidas::core::XDOMAttr::getName().
void Polynomial::fromString (const std::string & str) throw (nidas::util::InvalidParameterException) virtual
Reimplemented from nidas::core::VariableConverter.
CalFile* nidas::core::Polynomial::getCalFile () inline virtual
Implements nidas::core::VariableConverter.
const CalFile* nidas::core::Polynomial::getCalFile () const inline virtual
Implements nidas::core::VariableConverter.
const std::vector<float>& nidas::core::Polynomial::getCoefficients () const inline
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), operator=(), Polynomial(), and nidas::dynld::raf::SyncRecordSource::preLoadCalibrations().
const float* nidas::core::Polynomial::getCoefficients (unsigned int & n) const inline
const DSMConfig * VariableConverter::getDSMConfig () const inherited
References nidas::core::DSMSensor::getDSMConfig(), and nidas::core::VariableConverter::getDSMSensor().
const DSMSensor * VariableConverter::getDSMSensor () const inherited
References nidas::core::SampleTag::getDSMSensor(), nidas::core::Variable::getSampleTag(), and nidas::core::VariableConverter::getVariable().
Referenced by nidas::core::VariableConverter::getDSMConfig().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
const Parameter * VariableConverter::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::VariableConverter::_parameters.
const std::list<const Parameter*>& nidas::core::VariableConverter::getParameters () const inline inherited
Get list of parameters.
References nidas::core::VariableConverter::_constParameters.
Referenced by nidas::core::VariableConverter::operator=(), and nidas::core::VariableConverter::VariableConverter().
virtual const std::string& nidas::core::VariableConverter::getUnits () const inline virtual inherited
References nidas::core::VariableConverter::_units.
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), nidas::dynld::isff::CS_Krypton::CS_Krypton(), A2DVariableItem::dataField(), VariableItem::getCalibrationInfo(), DumpClient::printHeader(), nidas::core::Variable::toDOMElement(), nidas::core::Linear::toString(), and toString().
const Variable* nidas::core::VariableConverter::getVariable () const inline inherited
References nidas::core::VariableConverter::_variable.
Referenced by nidas::core::VariableConverter::getDSMSensor().
Polynomial & Polynomial::operator= (const Polynomial & rhs)
References _calFile, _calTime, getCoefficients(), and setCoefficients().
void Polynomial::readCalFile (dsm_time_t t) throw () virtual
Reimplemented from nidas::core::VariableConverter.
References DLOG, nidas::core::floatNAN, nidas::util::UTime::format(), nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_WARNING, nidas::util::UTime::toUsecs(), and nidas::util::Exception::what().
Referenced by convert(), A2DVariableItem::dataField(), and VariableItem::getCalValues().
void Polynomial::setCalFile (CalFile * val) virtual
Implements nidas::core::VariableConverter.
References _calFile.
Referenced by A2DVariableItem::dataField(), VariableItem::getCalDate(), VariableItem::getCalValues(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
void Polynomial::setCoefficients (const std::vector< float > & vals)
Referenced by operator=(), Polynomial(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
void Polynomial::setCoefficients (const float * fp, unsigned int n)
References _coefs.
void nidas::core::VariableConverter::setUnits (const std::string & val) inline inherited
References nidas::core::VariableConverter::_units.
Referenced by nidas::dynld::isff::CS_Krypton::CS_Krypton(), nidas::core::Variable::fromDOMElement(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
void nidas::core::VariableConverter::setVariable (const Variable * val) inline inherited
References nidas::core::VariableConverter::_variable.
Referenced by nidas::core::Variable::fromDOMElement().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
std::string Polynomial::toString () const virtual
Generate a string description of this VariableConverter.
May be used in meta-data, for example Netcdf comment.
Implements nidas::core::VariableConverter.
References _coefs, and nidas::core::VariableConverter::getUnits().
Referenced by A2DVariableItem::dataField(), and VariableItem::getCalValues().
Member Data Documentation
CalFile* nidas::core::Polynomial::_calFile private
Referenced by operator=(), Polynomial(), setCalFile(), and ~Polynomial().
dsm_time_t nidas::core::Polynomial::_calTime private
Referenced by operator=().
std::vector<float> nidas::core::Polynomial::_coefs private
Referenced by convert(), setCoefficients(), and toString().
const int nidas::core::Polynomial::MAX_NUM_COEFS = 6 static private
Maximum number of coefficients that can be read from a CalFile.
The documentation for this class was generated from the following files:
nidas/core/VariableConverter.h
nidas/core/VariableConverter.cc