nidas: PacketReader Class Reference
PacketReader Class Reference
Public Member Functions
PacketReader ()
~PacketReader ()
int parseRunstring (int argc, char **argv)
int usage (const char *argv0)
const deque
< n_u::DatagramPacket * > & getPackets () const
nidas::util::Cond & dataReady ()
void loop () throw ()
const string & getHeader () const
int getTCPPort () const
bool debug () const
int getMaxPacketSize () const
void checkPacket (n_u::DatagramPacket &)
void logBadPacket (const n_u::DatagramPacket &pkt, const string &msg)
Private Attributes
int _udpport
int _tcpport
int _packetsize
string _header
deque< n_u::DatagramPacket * > _packets
nidas::util::Cond _dataReady
bool _debug
size_t _rejectedPackets
long long _minSampleTime
long long _maxSampleTime
int _maxDsmId
unsigned int _maxSampleLength
Static Private Attributes
static const int DEFAULT_PACKET_SIZE = 16384
Constructor & Destructor Documentation
PacketReader::PacketReader ()
PacketReader::~PacketReader ()
References _dataReady, _packets, CLOG, nidas::util::DatagramPacketT< DataT >::getData(), nidas::util::Cond::lock(), nidas::util::Cond::unlock(), and nidas::util::Exception::what().
Member Function Documentation
void PacketReader::checkPacket (n_u::DatagramPacket & pkt)
References _maxDsmId, _maxSampleLength, _maxSampleTime, _minSampleTime, _rejectedPackets, nidas::core::CHAR_ST, GET_DSM_ID, GET_SPS_ID, nidas::util::DatagramPacketT< DataT >::getConstDataVoidPtr(), nidas::core::SampleHeader::getDataByteLength(), nidas::core::SampleHeader::getId(), nidas::util::DatagramPacketBase::getLength(), nidas::core::SampleHeader::getSizeOf(), nidas::core::SampleHeader::getTimeTag(), nidas::core::SampleHeader::getType(), logBadPacket(), and nidas::util::DatagramPacketBase::setLength().
Referenced by loop().
nidas::util::Cond& PacketReader::dataReady () inline
Referenced by WriterThread::run().
bool PacketReader::debug () const inline
Referenced by main().
const string& PacketReader::getHeader () const inline
int PacketReader::getMaxPacketSize () const inline
Referenced by WriterThread::run().
const deque<n_u::DatagramPacket*>& PacketReader::getPackets () const inline
Referenced by WriterThread::run().
int PacketReader::getTCPPort () const inline
void PacketReader::logBadPacket (const n_u::DatagramPacket & pkt, const string & msg)
References _rejectedPackets, nidas::util::DatagramPacketT< DataT >::getConstDataVoidPtr(), nidas::util::DatagramPacketBase::getLength(), nidas::util::DatagramPacketBase::getSocketAddress(), nidas::util::SocketAddress::toString(), and WLOG.
Referenced by checkPacket().
void PacketReader::loop () throw ()
References _dataReady, _packets, _packetsize, _udpport, nidas::util::Cond::broadcast(), checkPacket(), nidas::util::DatagramSocket::close(), nidas::util::DatagramPacketBase::getLength(), nidas::util::DatagramPacketBase::getSocketAddress(), interrupted, nidas::util::Cond::lock(), PLOG, nidas::util::DatagramSocket::receive(), nidas::util::SocketAddress::toString(), nidas::util::Cond::unlock(), and nidas::util::Exception::what().
Referenced by main().
int PacketReader::parseRunstring (int argc, char ** argv)
References _debug, _header, _packetsize, _tcpport, _udpport, fclose(), fp, usage(), and nidas::util::Exception::what().
Referenced by main().
int PacketReader::usage (const char * argv0)
References DEFAULT_PACKET_SIZE.
Referenced by parseRunstring().
Member Data Documentation
nidas::util::Cond PacketReader::_dataReady private
Referenced by loop(), and ~PacketReader().
bool PacketReader::_debug private
Referenced by parseRunstring().
string PacketReader::_header private
Referenced by parseRunstring().
int PacketReader::_maxDsmId private
Referenced by checkPacket().
unsigned int PacketReader::_maxSampleLength private
Referenced by checkPacket().
long long PacketReader::_maxSampleTime private
Referenced by checkPacket().
long long PacketReader::_minSampleTime private
Referenced by checkPacket().
deque<n_u::DatagramPacket*> PacketReader::_packets private
Referenced by loop(), and ~PacketReader().
int PacketReader::_packetsize private
Referenced by loop(), and parseRunstring().
size_t PacketReader::_rejectedPackets private
Referenced by checkPacket(), and logBadPacket().
int PacketReader::_tcpport private
Referenced by parseRunstring().
int PacketReader::_udpport private
Referenced by loop(), and parseRunstring().
const int PacketReader::DEFAULT_PACKET_SIZE = 16384 static private
Referenced by usage().
The documentation for this class was generated from the following file:
nidas/apps/nidas_udp_relay.cc