nidas: nidas::core::Parameter Class Reference
nidas::core::Parameter Class Reference abstract
#include <Parameter.h>
Public Types
enum parType { STRING_PARAM, FLOAT_PARAM, INT_PARAM, BOOL_PARAM }
typedef enum parType parType
Public Member Functions
virtual void assign (const Parameter &)=0
virtual ~Parameter ()
virtual Parameter * clone () const =0
const std::string & getName () const
void setName (const std::string &val)
parType getType () const
virtual int getLength () const =0
virtual double getNumericValue (int i) const
virtual std::string getStringValue (int i) const
virtual void fromDOMElement (const xercesc::DOMElement *, const Dictionary *dict)=0 throw (nidas::util::InvalidParameterException)
virtual void fromDOMElement (const xercesc::DOMElement *)=0 throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static Parameter * createParameter (const xercesc::DOMElement *, const Dictionary *d=0) throw (nidas::util::InvalidParameterException)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
Parameter (parType t)
Protected Attributes
std::string _name
parType _type
Member Typedef Documentation
typedef enum parType nidas::core::Parameter::parType
Member Enumeration Documentation
enum nidas::core::Parameter::parType
Enumerator
STRING_PARAM
FLOAT_PARAM
INT_PARAM
BOOL_PARAM
Constructor & Destructor Documentation
virtual nidas::core::Parameter::~Parameter () inline virtual
nidas::core::Parameter::Parameter (parType t) inline protected
Member Function Documentation
virtual void nidas::core::Parameter::assign (const Parameter &) pure virtual
Implemented in nidas::core::ParameterT< T >.
virtual Parameter* nidas::core::Parameter::clone () const pure virtual
Implemented in nidas::core::ParameterT< T >.
Referenced by nidas::core::VariableConverter::operator=(), nidas::core::Variable::operator=(), nidas::core::SampleTag::operator=(), nidas::core::SampleTag::SampleTag(), nidas::core::Variable::Variable(), and nidas::core::VariableConverter::VariableConverter().
Parameter * Parameter::createParameter (const xercesc::DOMElement * node, const Dictionary * d = 0) throw (nidas::util::InvalidParameterException) static
References fromDOMElement(), getLength(), and nidas::core::XDOMAttr::getName().
Referenced by nidas::core::VariableConverter::fromDOMElement(), nidas::core::Project::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::Site::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::Variable::fromDOMElement(), and nidas::core::DSMSensor::fromDOMElement().
virtual void nidas::core::DOMable::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) pure virtual inherited
Initialize myself from a xercesc::DOMElement.
Implemented in nidas::core::DSMSensor, nidas::core::ServerSocket, nidas::core::Variable, nidas::core::CalFile, nidas::core::SampleTag, nidas::dynld::SampleInputStream, nidas::core::Site, nidas::core::Polynomial, nidas::core::CharacterSensor, nidas::core::SampleOutputBase, nidas::core::SampleIOProcessor, nidas::core::Project, nidas::core::Socket, nidas::core::DSMConfig, nidas::dynld::isff::GOESXmtr, nidas::core::DatagramSocket, nidas::core::Linear, nidas::core::ParameterT< T >, nidas::core::SerialSensor, nidas::core::McSocket, nidas::core::McSocketUDP, nidas::core::UnixIOChannel, nidas::core::FileSet, nidas::dynld::raf::DSMArincSensor, nidas::core::FsMount, nidas::dynld::isff::CS_Krypton, nidas::core::VariableConverter, nidas::dynld::isff::GOESOutput, nidas::dynld::raf::CVIProcessor, nidas::core::DSMService, nidas::core::DSMServer, nidas::dynld::psql::PSQLChannel, nidas::dynld::raf::IRIGSensor, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::UDPSampleOutput, nidas::dynld::A2DSensor, nidas::dynld::isff::PropVane, nidas::dynld::DSC_A2DSensor, nidas::core::MultipleUDPSockets, nidas::core::DSMCatalog, nidas::dynld::RawSampleInputStream, nidas::dynld::Twins, nidas::core::SensorCatalog, nidas::dynld::RawSampleService, nidas::core::ServiceCatalog, nidas::dynld::raf::LamsSensor, nidas::dynld::raf::Arinc_IRS, and nidas::dynld::RawSampleOutputStream.
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
virtual void nidas::core::Parameter::fromDOMElement (const xercesc::DOMElement * , const Dictionary * dict) throw (nidas::util::InvalidParameterException) pure virtual
Implemented in nidas::core::ParameterT< T >.
Referenced by createParameter().
virtual int nidas::core::Parameter::getLength () const pure virtual
Implemented in nidas::core::ParameterT< T >.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::A2DSensor::addSampleTag(), nidas::dynld::raf::DSMAnalogSensor::addSampleTag(), nidas::dynld::isff::GOESOutput::addSourceSampleTag(), createParameter(), nidas::dynld::isff::WisardMote::createSampleTags(), nidas::dynld::raf::LamsSensor::fromDOMElement(), nidas::dynld::Twins::fromDOMElement(), nidas::dynld::isff::PropVane::fromDOMElement(), nidas::dynld::A2DSensor::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), nidas::dynld::isff::CS_Krypton::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::Aircraft::getTailNumber(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::WxtSensor::init(), nidas::dynld::isff::MOSMote::open(), nidas::dynld::raf::UHSAS_Serial::open(), nidas::dynld::raf::DSMAnalogSensor::open(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSI_IRGA_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::SonicAnemometer::parseParameters(), nidas::dynld::ParoSci_202BG_P::readParams(), nidas::dynld::ParoSci_202BG_T::readParams(), nidas::dynld::DSC_FreqCounter::readParams(), nidas::dynld::raf::DSMMesaSensor::sendFPGACodeToDriver(), nidas::dynld::IEEE_Float::validate(), nidas::dynld::raf::SppSerial::validate(), and nidas::dynld::isff::WisardMote::validate().
const std::string& nidas::core::Parameter::getName () const inline
References _name.
Referenced by nidas::core::VariableConverter::addParameter(), nidas::core::Site::addParameter(), nidas::core::SampleOutputBase::addParameter(), nidas::core::SampleTag::addParameter(), nidas::core::DSMSensor::addParameter(), nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::A2DSensor::addSampleTag(), nidas::core::ParameterT< T >::assign(), nidas::dynld::A2DSensor::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::Project::getParameter(), nidas::core::SampleTag::getParameter(), nidas::core::ParameterNameTypeComparator::operator()(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSI_IRGA_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::SonicAnemometer::parseParameters(), nidas::dynld::ParoSci_202BG_P::readParams(), nidas::dynld::ParoSci_202BG_T::readParams(), nidas::dynld::DSC_FreqCounter::readParams(), and nidas::dynld::IEEE_Float::validate().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
double Parameter::getNumericValue (int i) const virtual
References nidas::core::floatNAN.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::A2DSensor::addSampleTag(), nidas::dynld::isff::GOESOutput::addSourceSampleTag(), nidas::dynld::isff::WisardMote::createSampleTags(), nidas::dynld::raf::LamsSensor::fromDOMElement(), nidas::dynld::Twins::fromDOMElement(), nidas::dynld::A2DSensor::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::dynld::isff::CS_Krypton::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::TwoD_USB::init_parameters(), nidas::dynld::isff::MOSMote::open(), nidas::dynld::raf::UHSAS_Serial::open(), parseAnalog(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSI_IRGA_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::SonicAnemometer::parseParameters(), nidas::dynld::ParoSci_202BG_P::readParams(), nidas::dynld::ParoSci_202BG_T::readParams(), nidas::dynld::DSC_FreqCounter::readParams(), Extract2D::run(), AutoCalClient::Setup(), nidas::dynld::raf::CDP_Serial::validate(), nidas::dynld::raf::SPP300_Serial::validate(), nidas::dynld::raf::SPP100_Serial::validate(), nidas::dynld::raf::SPP200_Serial::validate(), nidas::dynld::raf::SppSerial::validate(), and nidas::dynld::isff::WisardMote::validate().
std::string Parameter::getStringValue (int i) const virtual
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::A2DSensor::addSampleTag(), nidas::dynld::isff::PropVane::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), PMSSensorItem::getSerialNumberString(), nidas::dynld::raf::Aircraft::getTailNumber(), nidas::dynld::WxtSensor::init(), nidas::dynld::raf::DSMAnalogSensor::open(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::SonicAnemometer::parseParameters(), Extract2D::run(), nidas::dynld::raf::DSMMesaSensor::sendFPGACodeToDriver(), sensorTitle(), and nidas::dynld::IEEE_Float::validate().
parType nidas::core::Parameter::getType () const inline
References _type.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::A2DSensor::addSampleTag(), nidas::core::ParameterT< T >::assign(), nidas::dynld::isff::WisardMote::createSampleTags(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::isff::PacketInputStream::getGOESProject(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::dynld::isff::MOSMote::open(), nidas::dynld::raf::DSMAnalogSensor::open(), nidas::core::ParameterNameTypeComparator::operator()(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSI_IRGA_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::SonicAnemometer::parseParameters(), nidas::dynld::ParoSci_202BG_P::readParams(), nidas::dynld::ParoSci_202BG_T::readParams(), nidas::dynld::DSC_FreqCounter::readParams(), nidas::dynld::raf::DSMMesaSensor::sendFPGACodeToDriver(), nidas::dynld::IEEE_Float::validate(), and nidas::dynld::isff::WisardMote::validate().
void nidas::core::Parameter::setName (const std::string & val) inline
References _name.
Referenced by main(), and nidas::dynld::raf::Aircraft::setTailNumber().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
std::string nidas::core::Parameter::_name protected
Referenced by getName(), and setName().
parType nidas::core::Parameter::_type protected
Referenced by getType().
The documentation for this class was generated from the following files:
nidas/core/Parameter.h
nidas/core/Parameter.cc