nidas: nidas::dynld::StatisticsProcessor Class Reference
nidas::dynld::StatisticsProcessor Class Reference
Interface of a processor of samples.
#include <StatisticsProcessor.h>
Classes
struct OutputInfo
Public Member Functions
StatisticsProcessor ()
~StatisticsProcessor ()
void addRequestedSampleTag (SampleTag *tag) throw (nidas::util::InvalidParameterException)
Request a sample from this StatisticsProcessor, containing Parameters indicating what variables to process and what kind of statistics to compute.
void selectRequestedSampleTags (const std::vector< unsigned int > &sampleIds)
void connect (SampleSource *) throw ()
Do common operations necessary when a input has connected:
void disconnect (SampleSource *) throw ()
Disconnect a SampleInput from this StatisticsProcessor.
void connect (SampleOutput *output) throw ()
Implementation of SampleConnectionRequester::connect.
void disconnect (SampleOutput *output) throw ()
Implementation of SampleConnectionRequester::disconnect.
void flush () throw ()
Implementation of SampleSource::flush().
void setStartTime (const nidas::util::UTime &val)
nidas::util::UTime getStartTime () const
void setEndTime (const nidas::util::UTime &val)
nidas::util::UTime getEndTime () const
float getPeriod () const
bool getFillGaps () const
Whether to generate output samples over time gaps.
void setFillGaps (bool val)
std::string getUniqueCountsName (const std::string &val)
All output samples (and StatisticsCrunchers) should have a unique name for their counts output variable.
virtual const std::string & getName () const
virtual void setName (const std::string &val)
virtual void setOptional (bool val)
virtual bool isOptional () const
virtual const DSMService * getService () const
What DSMService am I associated with?
virtual void setService (const DSMService *val)
virtual const DSMConfig * getDSMConfig () const
What DSM am I associated with?
virtual void setDSMConfig (const DSMConfig *val)
dsm_sample_id_t getId () const
void setSampleId (int val)
unsigned int getSampleId () const
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual std::list< const
SampleTag * > getRequestedSampleTags () const
void addSampleTag (const SampleTag *tag) throw ()
Implementation of SampleSource::addSampleTag().
void removeSampleTag (const SampleTag *tag) throw ()
std::list< const SampleTag * > getSampleTags () const
Implementation of SampleSource::getSampleTags().
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
const SampleStats & getSampleStats () const
virtual void addOutput (SampleOutput *val)
Add an SampleOutput to this SampleIOProcessor.
virtual const std::list
< SampleOutput * > & getOutputs () const
void addParameter (Parameter *val) throw (nidas::util::InvalidParameterException)
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual void printStatus (std::ostream &, float, int &) throw ()
virtual void init (dsm_time_t) throw ()
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void removeRequestedSampleTag (SampleTag *tag)
Allow subclasses to remove requested SampleTags.
Protected Attributes
SampleSourceSupport _source
nidas::util::Mutex _tagsMutex
std::list< SampleTag * > _requestedTags
Private Member Functions
StatisticsProcessor (const StatisticsProcessor &)
Copy not supported.
StatisticsProcessor & operator= (const StatisticsProcessor &)
Assignment not supported.
Private Attributes
nidas::util::Mutex _cruncherListMutex
Implementation of SampleIOProcessor::addSampleTag(SampleTag*).
std::set< SampleSource * > _connectedSources
std::set< SampleOutput * > _connectedOutputs
std::list< StatisticsCruncher * > _crunchers
std::map< dsm_sample_id_t,
struct OutputInfo > _infoBySampleId
nidas::util::UTime _startTime
nidas::util::UTime _endTime
float _statsPeriod
bool _fillGaps
std::set< std::string > _cntsNames
Set of counts variables for output samples.
Detailed Description
Interface of a processor of samples.
A StatisticsProcessor reads input Samples from a single SampleInput, and sends its processed output Samples to one or more SampleOutputs.
Constructor & Destructor Documentation
StatisticsProcessor::StatisticsProcessor ()
References nidas::core::SampleIOProcessor::setName().
StatisticsProcessor::~StatisticsProcessor ()
References _connectedOutputs, _cruncherListMutex, _crunchers, nidas::core::SampleOutput::close(), nidas::core::SampleClient::flush(), nidas::dynld::StatisticsCruncher::flush(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getName(), nidas::core::SampleIOProcessor::getName(), nidas::core::SampleOutput::getOriginal(), nidas::util::Mutex::lock(), nidas::util::Logger::log(), LOG_ERR, nidas::dynld::StatisticsCruncher::removeSampleClient(), nidas::util::Mutex::unlock(), and nidas::util::Exception::what().
nidas::dynld::StatisticsProcessor::StatisticsProcessor (const StatisticsProcessor &) private
Copy not supported.
Member Function Documentation
virtual void nidas::core::SampleIOProcessor::addOutput (SampleOutput * val) inline virtual inherited
Add an SampleOutput to this SampleIOProcessor.
This is used to add a desired SampleOutput to this SampleIOProcessor. SampleIOProcessor will own the SampleOutput. Once a SampleSource has connected, then SampleIOProcessor is responsible for do SampleOutput::requestConnection, or SampleOutputRequestThread::addConnectRequest() on all these as-yet disconnected outputs.
References nidas::core::SampleIOProcessor::_origOutputs.
void SampleIOProcessor::addParameter (Parameter * val) throw (nidas::util::InvalidParameterException) inherited
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
If a Parameter exists with the same name, it will be replaced with the new Parameter.
void StatisticsProcessor::addRequestedSampleTag (SampleTag * tag) throw (nidas::util::InvalidParameterException) virtual
Request a sample from this StatisticsProcessor, containing Parameters indicating what variables to process and what kind of statistics to compute.
Reimplemented from nidas::core::SampleIOProcessor.
References nidas::core::SampleIOProcessor::addRequestedSampleTag(), nidas::core::Parameter::BOOL_PARAM, nidas::dynld::StatisticsProcessor::OutputInfo::countsName, nidas::core::Project::expandString(), GET_DSM_ID, GET_SPS_ID, nidas::core::Project::getInstance(), nidas::core::Parameter::getLength(), nidas::core::Parameter::getName(), nidas::core::Parameter::getNumericValue(), nidas::core::Project::getParameter(), nidas::dynld::StatisticsCruncher::getStatisticsType(), nidas::core::Parameter::getStringValue(), nidas::core::Parameter::getType(), nidas::dynld::StatisticsProcessor::OutputInfo::higherMoments, ILOG, nidas::core::Parameter::INT_PARAM, nidas::core::Variable::setName(), nidas::dynld::StatisticsCruncher::STATS_UNKNOWN, nidas::dynld::StatisticsCruncher::STATS_WINDDIR, nidas::core::Parameter::STRING_PARAM, and nidas::dynld::StatisticsProcessor::OutputInfo::type.
void nidas::core::SampleIOProcessor::addSampleClient (SampleClient * client) throw () inline virtual inherited
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::addSampleClient().
void nidas::core::SampleIOProcessor::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
void SampleIOProcessor::addSampleTag (const SampleTag * tag) throw () virtual inherited
Implementation of SampleSource::addSampleTag().
Implements nidas::core::SampleSource.
void StatisticsProcessor::connect (SampleSource * source) throw () virtual
Do common operations necessary when a input has connected:
Copy the DSMConfig information from the input to the disconnected outputs.
Request connections for all disconnected outputs.
connect() methods in subclasses should do whatever initialization necessary before invoking this StatisticsProcessor::connect().
Implements nidas::core::SampleIOProcessor.
References nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutput::addSourceSampleTags(), nidas::core::Variable::closeMatch(), nidas::dynld::StatisticsCruncher::connect(), nidas::dynld::StatisticsProcessor::OutputInfo::countsName, nidas::core::SampleTag::getDSMId(), nidas::core::SampleTag::getId(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::util::Logger::getInstance(), nidas::core::Site::getName(), nidas::core::Variable::getName(), nidas::core::Variable::getSampleTag(), nidas::dynld::StatisticsCruncher::getSampleTags(), nidas::core::Variable::getSite(), nidas::core::SampleTag::getSpSId(), nidas::core::Variable::getStation(), nidas::core::Site::getSuffix(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTag::getVariables(), nidas::core::VariableIterator::hasNext(), nidas::dynld::StatisticsProcessor::OutputInfo::higherMoments, nidas::util::Logger::log(), LOG_WARNING, nidas::core::SampleTag::setDSMId(), nidas::dynld::StatisticsCruncher::setEndTime(), nidas::dynld::StatisticsCruncher::setFillGaps(), nidas::core::Variable::setSite(), nidas::dynld::StatisticsCruncher::setStartTime(), nidas::core::Variable::setStation(), and nidas::dynld::StatisticsProcessor::OutputInfo::type.
Referenced by StatsProcess::run().
void StatisticsProcessor::connect (SampleOutput * output) throw () virtual
Implementation of SampleConnectionRequester::connect.
Do common operations necessary when a output has connected:
do: output->init().
add output to a list of connected outputs.
Implements nidas::core::SampleConnectionRequester.
References nidas::dynld::StatisticsCruncher::addSampleClient().
void StatisticsProcessor::disconnect (SampleSource * source) throw () virtual
Disconnect a SampleInput from this StatisticsProcessor.
Right now just does a flush() of all connected outputs.
Implements nidas::core::SampleIOProcessor.
References nidas::dynld::StatisticsCruncher::disconnect(), and nidas::dynld::StatisticsCruncher::flush().
Referenced by StatsProcess::run().
void StatisticsProcessor::disconnect (SampleOutput * output) throw () virtual
Implementation of SampleConnectionRequester::disconnect.
Do common operations necessary when a output has disconnected:
do: output->close().
remove output from a list of connected outputs.
Implements nidas::core::SampleConnectionRequester.
References nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutputRequestThread::addDeleteRequest(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getOriginal(), nidas::core::SampleOutput::getReconnectDelaySecs(), nidas::util::Logger::log(), LOG_ERR, nidas::dynld::StatisticsCruncher::removeSampleClient(), and nidas::util::Exception::what().
void StatisticsProcessor::flush () throw () virtual
Implementation of SampleSource::flush().
Finish the current statistics and send them on.
Implements nidas::core::SampleSource.
References _connectedOutputs, _cruncherListMutex, _crunchers, nidas::core::SampleClient::flush(), nidas::dynld::StatisticsCruncher::flush(), nidas::util::Mutex::lock(), and nidas::util::Mutex::unlock().
void SampleIOProcessor::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual inherited
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::raf::CVIProcessor.
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Parameter::createParameter(), nidas::core::DOMable::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::Project::getInstance(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::SampleTag::getSampleId(), nidas::core::SampleTag::setSampleId(), nidas::core::SampleTag::setSensorId(), and nidas::util::Exception::what().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), and nidas::core::DSMConfig::fromDOMElement().
int nidas::core::SampleIOProcessor::getClientCount () const throw () inline virtual inherited
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getClientCount().
virtual const DSMConfig* nidas::core::SampleIOProcessor::getDSMConfig () const inline virtual inherited
What DSM am I associated with?
References nidas::core::SampleIOProcessor::_dsm.
nidas::util::UTime nidas::dynld::StatisticsProcessor::getEndTime () const inline
bool nidas::dynld::StatisticsProcessor::getFillGaps () const inline
Whether to generate output samples over time gaps.
In some circumstances one might be generating statistics for separate time periods, and one does not want to output samples of missing data for the gaps between the periods.
dsm_sample_id_t nidas::core::SampleIOProcessor::getId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_FULL_ID.
const std::string & SampleIOProcessor::getName () const virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by nidas::dynld::raf::CVIProcessor::fromDOMElement(), nidas::dynld::RawSampleService::schedule(), and ~StatisticsProcessor().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
virtual const std::list<SampleOutput*>& nidas::core::SampleIOProcessor::getOutputs () const inline virtual inherited
References nidas::core::SampleIOProcessor::_origOutputs.
Referenced by nidas::core::Project::findServerSampleOutputStreamFileSets(), nidas::dynld::isff::GOESProject::GOESProject(), and StatsProcess::run().
const std::list<const Parameter*>& nidas::core::SampleIOProcessor::getParameters () const inline inherited
Get list of parameters.
References nidas::core::SampleIOProcessor::_constParameters.
float nidas::dynld::StatisticsProcessor::getPeriod () const inline
Referenced by StatsProcess::getStatisticsProcessor().
SampleSource* nidas::core::SampleIOProcessor::getProcessedSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References nidas::core::SampleIOProcessor::_source.
SampleSource* nidas::core::SampleIOProcessor::getRawSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
std::list< const SampleTag * > SampleIOProcessor::getRequestedSampleTags () const virtual inherited
References nidas::core::SampleIOProcessor::_constRequestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::core::SampleTagIterator::hasNext(), and StatsProcess::listOutputSamples().
unsigned int nidas::core::SampleIOProcessor::getSampleId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_SPS_ID.
Referenced by StatsProcess::listOutputSamples(), and selectRequestedSampleTags().
const SampleStats& nidas::core::SampleIOProcessor::getSampleStats () const inline virtual inherited
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleStats().
SampleTagIterator nidas::core::SampleIOProcessor::getSampleTagIterator () const inline virtual inherited
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleTagIterator().
std::list<const SampleTag*> nidas::core::SampleIOProcessor::getSampleTags () const inline virtual inherited
Implementation of SampleSource::getSampleTags().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::psql::PSQLProcessor.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleTags().
virtual const DSMService* nidas::core::SampleIOProcessor::getService () const inline virtual inherited
What DSMService am I associated with?
References nidas::core::SampleIOProcessor::_service.
nidas::util::UTime nidas::dynld::StatisticsProcessor::getStartTime () const inline
string StatisticsProcessor::getUniqueCountsName (const std::string & val)
All output samples (and StatisticsCrunchers) should have a unique name for their counts output variable.
This will check if val exists in _cntsNames. If not, it is added to _cntsNames and returned as a unique name. If it is in _cntsName, a suffix of "_N" where N is 1:Inf is appended until it is unique.
References _cntsNames.
Referenced by nidas::dynld::StatisticsCruncher::initStats().
virtual void nidas::core::SampleIOProcessor::init (dsm_time_t) throw () inline virtual inherited
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
Referenced by nidas::dynld::RawSampleService::schedule().
virtual bool nidas::core::SampleIOProcessor::isOptional () const inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
Referenced by nidas::dynld::RawSampleService::schedule().
StatisticsProcessor& nidas::dynld::StatisticsProcessor::operator= (const StatisticsProcessor &) private
Assignment not supported.
virtual void nidas::core::SampleIOProcessor::printStatus (std::ostream & , float , int &) throw () inline virtual inherited
Reimplemented in nidas::dynld::raf::SyncRecordGenerator, and nidas::core::SampleArchiver.
Referenced by nidas::dynld::RawSampleService::printStatus().
void SampleIOProcessor::removeRequestedSampleTag (SampleTag * tag) protected inherited
Allow subclasses to remove requested SampleTags.
The tag will be deleted.
References nidas::core::SampleIOProcessor::_constRequestedTags, nidas::core::SampleIOProcessor::_requestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by selectRequestedSampleTags().
void nidas::core::SampleIOProcessor::removeSampleClient (SampleClient * c) throw () inline virtual inherited
Remove a SampleClient from this SampleSource.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::removeSampleClient().
void nidas::core::SampleIOProcessor::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
void SampleIOProcessor::removeSampleTag (const SampleTag * tag) throw () virtual inherited
Implements nidas::core::SampleSource.
void StatisticsProcessor::selectRequestedSampleTags (const std::vector< unsigned int > & sampleIds)
References nidas::core::SampleIOProcessor::_requestedTags, nidas::core::SampleIOProcessor::_tagsMutex, nidas::core::SampleIOProcessor::getSampleId(), nidas::core::SampleTag::getSpSId(), nidas::util::Mutex::lock(), nidas::core::SampleIOProcessor::removeRequestedSampleTag(), and nidas::util::Mutex::unlock().
Referenced by StatsProcess::run().
virtual void nidas::core::SampleIOProcessor::setDSMConfig (const DSMConfig * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_dsm.
Referenced by nidas::core::DSMConfig::fromDOMElement().
void nidas::dynld::StatisticsProcessor::setEndTime (const nidas::util::UTime & val) inline
Referenced by StatsProcess::run().
void nidas::dynld::StatisticsProcessor::setFillGaps (bool val) inline
Referenced by StatsProcess::run().
void SampleIOProcessor::setName (const std::string & val) virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by nidas::dynld::psql::PSQLProcessor::PSQLProcessor(), nidas::core::SampleArchiver::SampleArchiver(), StatisticsProcessor(), and nidas::dynld::raf::SyncRecordGenerator::SyncRecordGenerator().
virtual void nidas::core::SampleIOProcessor::setOptional (bool val) inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
void nidas::core::SampleIOProcessor::setSampleId (int val) inline inherited
References nidas::core::SampleIOProcessor::_id, and SET_SPS_ID.
virtual void nidas::core::SampleIOProcessor::setService (const DSMService * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_service.
Referenced by nidas::core::DSMService::fromDOMElement().
void nidas::dynld::StatisticsProcessor::setStartTime (const nidas::util::UTime & val) inline
Referenced by StatsProcess::run().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
std::set<std::string> nidas::dynld::StatisticsProcessor::_cntsNames private
Set of counts variables for output samples.
Referenced by getUniqueCountsName().
std::set<SampleOutput*> nidas::dynld::StatisticsProcessor::_connectedOutputs private
Referenced by flush(), and ~StatisticsProcessor().
std::set<SampleSource*> nidas::dynld::StatisticsProcessor::_connectedSources private
nidas::util::Mutex nidas::dynld::StatisticsProcessor::_cruncherListMutex private
Implementation of SampleIOProcessor::addSampleTag(SampleTag*).
Referenced by flush(), and ~StatisticsProcessor().
std::list<StatisticsCruncher*> nidas::dynld::StatisticsProcessor::_crunchers private
Referenced by flush(), and ~StatisticsProcessor().
nidas::util::UTime nidas::dynld::StatisticsProcessor::_endTime private
bool nidas::dynld::StatisticsProcessor::_fillGaps private
std::map<dsm_sample_id_t,struct OutputInfo> nidas::dynld::StatisticsProcessor::_infoBySampleId private
std::list<SampleTag*> nidas::core::SampleIOProcessor::_requestedTags protected inherited
Referenced by nidas::core::SampleIOProcessor::removeRequestedSampleTag(), selectRequestedSampleTags(), and nidas::core::SampleIOProcessor::~SampleIOProcessor().
SampleSourceSupport nidas::core::SampleIOProcessor::_source protected inherited
Referenced by nidas::core::SampleIOProcessor::addSampleClient(), nidas::core::SampleIOProcessor::addSampleClientForTag(), nidas::core::SampleIOProcessor::getClientCount(), nidas::core::SampleIOProcessor::getProcessedSampleSource(), nidas::core::SampleIOProcessor::getSampleStats(), nidas::core::SampleIOProcessor::getSampleTagIterator(), nidas::core::SampleIOProcessor::getSampleTags(), nidas::core::SampleIOProcessor::removeSampleClient(), and nidas::core::SampleIOProcessor::removeSampleClientForTag().
nidas::util::UTime nidas::dynld::StatisticsProcessor::_startTime private
float nidas::dynld::StatisticsProcessor::_statsPeriod private
nidas::util::Mutex nidas::core::SampleIOProcessor::_tagsMutex mutable protected inherited
Referenced by nidas::core::SampleIOProcessor::getRequestedSampleTags(), nidas::core::SampleIOProcessor::removeRequestedSampleTag(), and selectRequestedSampleTags().
The documentation for this class was generated from the following files:
nidas/dynld/StatisticsProcessor.h
nidas/dynld/StatisticsProcessor.cc