nidas: A2DSensorItem Class Reference
A2DSensorItem Class Reference
#include <A2DSensorItem.h>
Public Member Functions
A2DSensorItem (DSMAnalogSensor *sensor, int row, NidasModel *theModel, NidasItem *parent)
NidasItem * child (int i)
return the ith child of this item.
void refreshChildItems ()
const QVariant & childLabel (int column) const
int childColumnCount () const
QString getA2DTempSuffix ()
bool removeChild (NidasItem *item)
remove the sample item from this Sensor's Nidas and DOM trees
void setNidasA2DTempSuffix (std::string a2dTempSfx)
void updateDOMA2DTempSfx (QString oldSfx, std::string newSfx)
void updateDOMCalFile (const std::string &calFileName)
update the A2D Calibration Filename to calFileName.
std::string getCalFileName ()
std::string getSerialNumberString ()
DSMAnalogSensor * getDSMAnalogSensor () const
void fromDOM ()
Re-initialize the nidas model from the DOM element.
std::string devicename ()
QString dataField (int column)
xercesc::DOMNode * getDOMNode ()
QString getBaseName ()
QString getDevice ()
DSMSensor * getDSMSensor () const
xercesc::DOMNode * findSampleDOMNode (unsigned int sampleId)
find the DOM node for the given sample tag
NidasItem * parent () const
int row () const
int childCount ()
bool removeChildren (int first, int last)
QModelIndex createIndex ()
NidasItem * getParentItem ()
Protected Member Functions
QString viewName ()
xercesc::DOMNode * findDOMNode ()
find the DOM node which defines this Sensor
virtual QString name ()
Protected Attributes
DSMSensor * _sensor
xercesc::DOMNode * domNode
QList< NidasItem * > childItems
NidasItem * parentItem
int rowNumber
NidasModel * model
Static Protected Attributes
static const QVariant _Project_Label
static const QVariant _Site_Label
static const QVariant _DSM_Label
static const QVariant _Device_Label
static const QVariant _SN_Label
static const QVariant _ID_Label
static const QVariant _Sensor_Label
static const QVariant _Sample_Label
static const QVariant _DevChan_Label
static const QVariant _Suffix_Label
static const QVariant _Rate_Label
static const QVariant _Volt_Label
static const QVariant _Variable_Label
static const QVariant _CalCoefSrc_Label
static const QVariant _CalCoef_Label
static const QVariant _CalDate_Label
static const QVariant _Name_Label
static const QVariant _Channel_Label
static const QVariant _Unknown_Label
Constructor & Destructor Documentation
A2DSensorItem::A2DSensorItem (DSMAnalogSensor * sensor, int row, NidasModel * theModel, NidasItem * parent)
Member Function Documentation
NidasItem * A2DSensorItem::child (int i) virtual
return the ith child of this item.
The primary mechanism for building the NidasItem tree. When Qt asks the NidasModel for info, it calls child(). Subclasses reimplement to build items for each type of Nidas object based on the parent's unique child iterators.
N.B. there is a QObject::child(objName,inheritsClass,recursiveSearch) from Qt3. Watch out...
Reimplemented from NidasItem.
References SensorItem::_sensor, NidasItem::childItems, nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::core::VariableIterator::hasNext(), NidasItem::model, and nidas::core::SampleTagIterator::next().
Referenced by Document::addA2DVariable(), Document::insertA2DVariable(), and removeChild().
int A2DSensorItem::childColumnCount () const inline virtual
Reimplemented from NidasItem.
int NidasItem::childCount () inherited
NidasItem is a proxy for the actual Nidas objects in the Project tree and their corresponding DOMNodes. Qt indexing is mapped to the Project tree via parent/child with row the ordinal number of the siblings and columns used for data fields (attributes/properties) of each level of Nidas object.
Pointers to Nidas objects are void* since Nidas uses different classes at every level. NidasItem is (should/will be) subclassed for specialized Items corresponding to each kind of Nidas object in the Project tree and implementing their own logic for the API used by NidasModel (like the data and header returned for Qt columns).
The NidasItem tree is a mirror/proxy of the Nidas object Project tree, with children lazily initialized by child(). Row number, parent pointer, and a list of children are cached.
N.B. can only add children to end of list due to Nidas API and use of children list in child()
NidasItem could also become a QObject to get the parent/children stuff. This could be useful in future for findChild()/findChildren(). Except for the fact that it didn't work - something about Qt's cleanup of children caused problems for us.
References NidasItem::child(), and NidasItem::childItems.
Referenced by Document::addA2DVariable(), Document::insertA2DVariable(), NidasModel::insertRows(), and NidasModel::rowCount().
const QVariant& A2DSensorItem::childLabel (int column) const inline virtual
Reimplemented from NidasItem.
References NidasItem::_CalCoef_Label, NidasItem::_CalCoefSrc_Label, NidasItem::_CalDate_Label, NidasItem::_Channel_Label, NidasItem::_Rate_Label, NidasItem::_Sample_Label, NidasItem::_Unknown_Label, NidasItem::_Variable_Label, and NidasItem::_Volt_Label.
QModelIndex NidasItem::createIndex () inline inherited
Asks the model to create an index for this item. Requires us to be a friend of NidasModel and for the model to ask NidasItem for the parent item.
Returns
a QModelIndex for this NidasItem
Referenced by Document::addA2DVariable(), NidasModel::appendChild(), NidasModel::removeChildren(), and NidasModel::removeIndexes().
QString SensorItem::dataField (int column) virtual inherited
Reimplemented from NidasItem.
References DeviceValidator::getDevicePrefix(), and DeviceValidator::getInstance().
std::string SensorItem::devicename () inline inherited
Referenced by DSMItem::removeChild().
DOMNode * SensorItem::findDOMNode () protected inherited
find the DOM node which defines this Sensor
References nidas::core::XDOMElement::getAttributeValue(), and DSMItem::getDOMNode().
DOMNode * SensorItem::findSampleDOMNode (unsigned int sampleId) inherited
find the DOM node for the given sample tag
Search through the Sensor DOM Node children looking for nodes with the name sample and for every one found, see if the id attribute of that node is equal to the sampleId passed in. Note that we search through all children of the sensor node because we want the last such node. Nidas allows multiple definitions, using the last one as the 'final' say so.
References nidas::core::XDOMElement::getAttributeValue().
Referenced by Document::insertA2DVariable(), removeChild(), and Document::updateVariable().
void SensorItem::fromDOM () inherited
Re-initialize the nidas model from the DOM element.
Referenced by Document::updateSensor(), and Document::updateVariable().
QString A2DSensorItem::getA2DTempSuffix ()
References SensorItem::_sensor, nidas::core::Variable::getName(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::core::VariableIterator::hasNext(), and nidas::core::SampleTagIterator::next().
Referenced by config::AddSensorComboDialog::existingSensor(), and Document::updateSensor().
QString SensorItem::getBaseName () inherited
Referenced by config::AddSensorComboDialog::existingSensor(), and Document::updateVariable().
std::string A2DSensorItem::getCalFileName ()
References SensorItem::_sensor, and nidas::core::DSMSensor::getCalFiles().
Referenced by config::AddSensorComboDialog::existingSensor().
QString SensorItem::getDevice () inline inherited
Referenced by config::AddSensorComboDialog::existingSensor().
xercesc::DOMNode* SensorItem::getDOMNode () inline inherited
Referenced by Document::addA2DVariable(), A2DVariableItem::findSampleDOMNode(), VariableItem::findSampleDOMNode(), removeChild(), updateDOMCalFile(), PMSSensorItem::updateDOMPMSParams(), Document::updateSensorDOM(), and Document::updateVariable().
DSMAnalogSensor* A2DSensorItem::getDSMAnalogSensor () const inline
Referenced by A2DVariableItem::dataField(), A2DVariableItem::getBipolar(), and A2DVariableItem::getGain().
DSMSensor* SensorItem::getDSMSensor () const inline inherited
Referenced by Document::addA2DVariable(), config::AddSensorComboDialog::existingSensor(), Document::getAvailableA2DChannels(), VariableItem::getBaseName(), removeChild(), Document::updateSensor(), and Document::updateVariable().
NidasItem* NidasItem::getParentItem () inline inherited
std::string A2DSensorItem::getSerialNumberString () virtual
Reimplemented from SensorItem.
References SensorItem::_sensor, and nidas::core::DSMSensor::getCalFiles().
virtual QString NidasItem::name () inline protected virtual inherited
Reimplemented in DSMItem, SiteItem, ProjectItem, A2DVariableItem, and VariableItem.
Referenced by removeChild().
NidasItem* NidasItem::parent () const inline inherited
Referenced by NidasModel::parent(), and NidasModel::removeIndexes().
void A2DSensorItem::refreshChildItems ()
References SensorItem::_sensor, NidasItem::childItems, nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::core::VariableIterator::hasNext(), NidasItem::model, and nidas::core::SampleTagIterator::next().
bool A2DSensorItem::removeChild (NidasItem * item) virtual
remove the sample item from this Sensor's Nidas and DOM trees
current implementation confused between returning bool and throwing exceptions due to refactoring from Document
Reimplemented from NidasItem.
References child(), SensorItem::findSampleDOMNode(), nidas::core::XDOMElement::getAttributeValue(), SensorItem::getDOMNode(), SensorItem::getDSMSensor(), nidas::core::Variable::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::SampleTag::getSampleId(), A2DVariableItem::getSampleTag(), nidas::core::DSMSensor::getSampleTags(), nidas::core::SampleTag::getVariableIterator(), nidas::core::VariableIterator::hasNext(), A2DVariableItem::name(), NidasItem::name(), nidas::core::DSMSensor::removeSampleTag(), and nidas::core::SampleTag::removeVariable().
bool NidasItem::removeChildren (int first, int last) inherited
References NidasItem::childItems, and NidasItem::rowNumber.
Referenced by NidasModel::removeRows().
int NidasItem::row () const inline inherited
Referenced by NidasModel::parent(), and NidasModel::removeIndexes().
void A2DSensorItem::setNidasA2DTempSuffix (std::string a2dTempSfx)
References SensorItem::_sensor, nidas::core::Variable::getName(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::core::VariableIterator::hasNext(), nidas::core::SampleTagIterator::next(), and nidas::core::Variable::setName().
void A2DSensorItem::updateDOMA2DTempSfx (QString oldSfx, std::string newSfx)
References NidasItem::childItems, A2DVariableItem::name(), and A2DVariableItem::setDOMName().
Referenced by Document::updateSensor().
void A2DSensorItem::updateDOMCalFile (const std::string & calFileName)
update the A2D Calibration Filename to calFileName.
Assumes that the DOM already has a calibration file for the A2D Sensor.
References SensorItem::getDOMNode().
Referenced by Document::updateSensor().
QString SensorItem::viewName () protected inherited
Member Data Documentation
const QVariant NidasItem::_CalCoef_Label static protected inherited
Referenced by childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_CalCoefSrc_Label static protected inherited
Referenced by childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_CalDate_Label static protected inherited
Referenced by childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Channel_Label static protected inherited
Referenced by childLabel().
const QVariant NidasItem::_DevChan_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Device_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_DSM_Label static protected inherited
Referenced by SiteItem::childLabel().
const QVariant NidasItem::_ID_Label static protected inherited
Referenced by SiteItem::childLabel(), and DSMItem::childLabel().
const QVariant NidasItem::_Name_Label static protected inherited
Referenced by VariableItem::childLabel(), SiteItem::childLabel(), A2DVariableItem::childLabel(), and DSMItem::childLabel().
const QVariant NidasItem::_Project_Label static protected inherited
const QVariant NidasItem::_Rate_Label static protected inherited
Referenced by childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Sample_Label static protected inherited
Referenced by childLabel(), and SensorItem::childLabel().
DSMSensor* SensorItem::_sensor protected inherited
Referenced by child(), getA2DTempSuffix(), getCalFileName(), PMSSensorItem::getSerialNumberString(), getSerialNumberString(), refreshChildItems(), and setNidasA2DTempSuffix().
const QVariant NidasItem::_Sensor_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Site_Label static protected inherited
Referenced by ProjectItem::childLabel().
const QVariant NidasItem::_SN_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Suffix_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Unknown_Label static protected inherited
Referenced by childLabel().
const QVariant NidasItem::_Variable_Label static protected inherited
Referenced by childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Volt_Label static protected inherited
Referenced by childLabel().
QList<NidasItem*> NidasItem::childItems protected inherited
Referenced by child(), NidasItem::childCount(), refreshChildItems(), NidasItem::removeChildren(), and updateDOMA2DTempSfx().
xercesc::DOMNode* NidasItem::domNode protected inherited
NidasModel* NidasItem::model protected inherited
Referenced by child(), and refreshChildItems().
NidasItem* NidasItem::parentItem protected inherited
int NidasItem::rowNumber protected inherited
Referenced by NidasItem::removeChildren().
The documentation for this class was generated from the following files:
nidas/apps/config/nidas_qmv/A2DSensorItem.h
nidas/apps/config/nidas_qmv/A2DSensorItem.cc