nidas: nidas::core::Linear Class Reference
nidas::core::Linear Class Reference
#include <VariableConverter.h>
Public Member Functions
Linear ()
Linear (const Linear &x)
Linear & operator= (const Linear &x)
Linear * clone () const
~Linear ()
void setCalFile (CalFile *)
CalFile * getCalFile ()
const CalFile * getCalFile () const
void setSlope (float val)
float getSlope () const
void setIntercept (float val)
float getIntercept () const
void readCalFile (dsm_time_t t) throw ()
double convert (dsm_time_t t, double val)
std::string toString () const
Generate a string description of this VariableConverter.
void fromString (const std::string &) throw (nidas::util::InvalidParameterException)
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
void setUnits (const std::string &val)
virtual const std::string & getUnits () const
void setVariable (const Variable *val)
const Variable * getVariable () const
const DSMSensor * getDSMSensor () const
const DSMConfig * getDSMConfig () const
void addParameter (Parameter *val)
Add a parameter to this VariableConverter.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static VariableConverter * createVariableConverter (XDOMElement &child)
static VariableConverter * createFromString (const std::string &) throw (nidas::util::InvalidParameterException)
static const XMLCh * getNamespaceURI ()
Private Attributes
dsm_time_t _calTime
float _slope
float _intercept
CalFile * _calFile
Constructor & Destructor Documentation
Linear::Linear ()
Referenced by clone().
Linear::Linear (const Linear & x)
References _calFile.
Linear::~Linear ()
References _calFile.
Member Function Documentation
void VariableConverter::addParameter (Parameter * val) inherited
Add a parameter to this VariableConverter.
VariableConverter will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::VariableConverter::_constParameters, nidas::core::VariableConverter::_parameters, and nidas::core::Parameter::getName().
Referenced by nidas::core::VariableConverter::operator=(), and nidas::core::VariableConverter::VariableConverter().
Linear * Linear::clone () const virtual
Implements nidas::core::VariableConverter.
References Linear().
double Linear::convert (dsm_time_t t, double val) virtual
Implements nidas::core::VariableConverter.
References _intercept, _slope, and readCalFile().
VariableConverter * VariableConverter::createFromString (const std::string & str) throw (nidas::util::InvalidParameterException) static inherited
References nidas::core::VariableConverter::fromString().
VariableConverter * VariableConverter::createVariableConverter (XDOMElement & child) static inherited
References nidas::core::DOMObjectFactory::createObject(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::XDOMElement::getNodeName(), and nidas::util::Exception::what().
Referenced by nidas::core::Variable::fromDOMElement().
void Linear::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Reimplemented from nidas::core::VariableConverter.
References nidas::core::VariableConverter::fromDOMElement(), and nidas::core::XDOMAttr::getName().
void Linear::fromString (const std::string & str) throw (nidas::util::InvalidParameterException) virtual
Reimplemented from nidas::core::VariableConverter.
CalFile* nidas::core::Linear::getCalFile () inline virtual
Implements nidas::core::VariableConverter.
const CalFile* nidas::core::Linear::getCalFile () const inline virtual
Implements nidas::core::VariableConverter.
const DSMConfig * VariableConverter::getDSMConfig () const inherited
References nidas::core::DSMSensor::getDSMConfig(), and nidas::core::VariableConverter::getDSMSensor().
const DSMSensor * VariableConverter::getDSMSensor () const inherited
References nidas::core::SampleTag::getDSMSensor(), nidas::core::Variable::getSampleTag(), and nidas::core::VariableConverter::getVariable().
Referenced by nidas::core::VariableConverter::getDSMConfig().
float nidas::core::Linear::getIntercept () const inline
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), and nidas::dynld::raf::SyncRecordSource::preLoadCalibrations().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
const Parameter * VariableConverter::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::VariableConverter::_parameters.
const std::list<const Parameter*>& nidas::core::VariableConverter::getParameters () const inline inherited
Get list of parameters.
References nidas::core::VariableConverter::_constParameters.
Referenced by nidas::core::VariableConverter::operator=(), and nidas::core::VariableConverter::VariableConverter().
float nidas::core::Linear::getSlope () const inline
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), and nidas::dynld::raf::SyncRecordSource::preLoadCalibrations().
virtual const std::string& nidas::core::VariableConverter::getUnits () const inline virtual inherited
References nidas::core::VariableConverter::_units.
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), nidas::dynld::isff::CS_Krypton::CS_Krypton(), A2DVariableItem::dataField(), VariableItem::getCalibrationInfo(), DumpClient::printHeader(), nidas::core::Variable::toDOMElement(), toString(), and nidas::core::Polynomial::toString().
const Variable* nidas::core::VariableConverter::getVariable () const inline inherited
References nidas::core::VariableConverter::_variable.
Referenced by nidas::core::VariableConverter::getDSMSensor().
Linear & Linear::operator= (const Linear & x)
References _calFile, _calTime, _intercept, and _slope.
void Linear::readCalFile (dsm_time_t t) throw () virtual
Reimplemented from nidas::core::VariableConverter.
References nidas::core::floatNAN, nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_WARNING, nidas::util::UTime::toUsecs(), and nidas::util::Exception::what().
Referenced by convert().
void Linear::setCalFile (CalFile * val) virtual
Implements nidas::core::VariableConverter.
References _calFile.
void nidas::core::Linear::setIntercept (float val) inline
void nidas::core::Linear::setSlope (float val) inline
void nidas::core::VariableConverter::setUnits (const std::string & val) inline inherited
References nidas::core::VariableConverter::_units.
Referenced by nidas::dynld::isff::CS_Krypton::CS_Krypton(), nidas::core::Variable::fromDOMElement(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
void nidas::core::VariableConverter::setVariable (const Variable * val) inline inherited
References nidas::core::VariableConverter::_variable.
Referenced by nidas::core::Variable::fromDOMElement().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
std::string Linear::toString () const virtual
Generate a string description of this VariableConverter.
May be used in meta-data, for example Netcdf comment.
Implements nidas::core::VariableConverter.
References _intercept, _slope, and nidas::core::VariableConverter::getUnits().
Member Data Documentation
CalFile* nidas::core::Linear::_calFile private
Referenced by Linear(), operator=(), setCalFile(), and ~Linear().
dsm_time_t nidas::core::Linear::_calTime private
Referenced by operator=().
float nidas::core::Linear::_intercept private
Referenced by convert(), operator=(), and toString().
float nidas::core::Linear::_slope private
Referenced by convert(), operator=(), and toString().
The documentation for this class was generated from the following files:
nidas/core/VariableConverter.h
nidas/core/VariableConverter.cc