nidas: nidas::core::SampleArchiver Class Reference
nidas::core::SampleArchiver Class Reference
#include <SampleArchiver.h>
Public Member Functions
SampleArchiver ()
virtual ~SampleArchiver ()
void flush () throw ()
Implementation of SampleSource::flush().
void setRaw (bool val)
By default a SampleArchiver is used for archiving raw samples, and any SampleOutputs that connect will receive samples from source->getRawSampleSource(), even if the output->isRaw() method returns false.
bool getRaw () const
void connect (SampleSource *) throw ()
Implementation of SampleIOProcessor::connect(SampleSource*).
void disconnect (SampleSource *) throw ()
Implementation of SampleIOProcessor::disconnect(SampleSource*).
void connect (SampleOutput *output) throw ()
Implementation of SampleConnectionRequester::connect(SampleOutput*).
void disconnect (SampleOutput *output) throw ()
Implementation of SampleConnectionRequester::disconnect(SampleOutput*).
void printStatus (std::ostream &, float deltat, int &) throw ()
virtual const std::string & getName () const
virtual void setName (const std::string &val)
virtual void setOptional (bool val)
virtual bool isOptional () const
virtual const DSMService * getService () const
What DSMService am I associated with?
virtual void setService (const DSMService *val)
virtual const DSMConfig * getDSMConfig () const
What DSM am I associated with?
virtual void setDSMConfig (const DSMConfig *val)
dsm_sample_id_t getId () const
void setSampleId (int val)
unsigned int getSampleId () const
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual void addRequestedSampleTag (SampleTag *tag) throw (nidas::util::InvalidParameterException)
Add a request for a SampleTag from this SampleIOProcessor.
virtual std::list< const
SampleTag * > getRequestedSampleTags () const
void addSampleTag (const SampleTag *tag) throw ()
Implementation of SampleSource::addSampleTag().
void removeSampleTag (const SampleTag *tag) throw ()
std::list< const SampleTag * > getSampleTags () const
Implementation of SampleSource::getSampleTags().
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
const SampleStats & getSampleStats () const
virtual void addOutput (SampleOutput *val)
Add an SampleOutput to this SampleIOProcessor.
virtual const std::list
< SampleOutput * > & getOutputs () const
void addParameter (Parameter *val) throw (nidas::util::InvalidParameterException)
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual void init (dsm_time_t) throw ()
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void removeRequestedSampleTag (SampleTag *tag)
Allow subclasses to remove requested SampleTags.
Protected Attributes
SampleSourceSupport _source
nidas::util::Mutex _tagsMutex
std::list< SampleTag * > _requestedTags
Private Member Functions
SampleArchiver (const SampleArchiver &x)
Copy not supported.
SampleArchiver & operator= (const SampleArchiver &x)
Assignment not supported.
Private Attributes
nidas::util::Mutex _connectionMutex
std::set< SampleSource * > _connectedSources
std::set< SampleOutput * > _connectedOutputs
std::list< const
nidas::core::FileSet * > _filesets
If my SampleOutput* is a nidas::core::FileSet then save the pointer for use in by printStatus(), so that the status output will contain things like the file size.
nidas::util::Mutex _filesetMutex
Mutex for controlling access to _filesets so that printStatus has valid pointers.
size_t _nsampsLast
Saved between calls to printStatus in order to compute sample rates.
long long _nbytesLast
Saved between calls to printStatus in order to compute data rates.
std::map< const
nidas::core::FileSet *, long
long > _nbytesLastByFileSet
bool _rawArchive
Constructor & Destructor Documentation
SampleArchiver::SampleArchiver ()
References nidas::core::SampleIOProcessor::setName().
SampleArchiver::~SampleArchiver () virtual
References _connectedOutputs, _connectedSources, _connectionMutex, nidas::core::SampleOutput::close(), nidas::core::SampleClient::flush(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getName(), nidas::core::SampleOutput::getOriginal(), nidas::util::Mutex::lock(), nidas::util::Logger::log(), LOG_ERR, nidas::core::SampleSource::removeSampleClient(), nidas::util::Mutex::unlock(), and nidas::util::Exception::what().
nidas::core::SampleArchiver::SampleArchiver (const SampleArchiver & x) private
Copy not supported.
Member Function Documentation
virtual void nidas::core::SampleIOProcessor::addOutput (SampleOutput * val) inline virtual inherited
Add an SampleOutput to this SampleIOProcessor.
This is used to add a desired SampleOutput to this SampleIOProcessor. SampleIOProcessor will own the SampleOutput. Once a SampleSource has connected, then SampleIOProcessor is responsible for do SampleOutput::requestConnection, or SampleOutputRequestThread::addConnectRequest() on all these as-yet disconnected outputs.
References nidas::core::SampleIOProcessor::_origOutputs.
void SampleIOProcessor::addParameter (Parameter * val) throw (nidas::util::InvalidParameterException) inherited
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
If a Parameter exists with the same name, it will be replaced with the new Parameter.
void SampleIOProcessor::addRequestedSampleTag (SampleTag * tag) throw (nidas::util::InvalidParameterException) virtual inherited
Add a request for a SampleTag from this SampleIOProcessor.
This SampleIOProcessor will own the SampleTag.
Reimplemented in nidas::dynld::raf::CVIProcessor, and nidas::dynld::StatisticsProcessor.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), and nidas::dynld::raf::CVIProcessor::addRequestedSampleTag().
void nidas::core::SampleIOProcessor::addSampleClient (SampleClient * client) throw () inline virtual inherited
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::addSampleClient().
void nidas::core::SampleIOProcessor::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
void SampleIOProcessor::addSampleTag (const SampleTag * tag) throw () virtual inherited
Implementation of SampleSource::addSampleTag().
Implements nidas::core::SampleSource.
void SampleArchiver::connect (SampleSource * source) throw () virtual
Implementation of SampleIOProcessor::connect(SampleSource*).
Implements nidas::core::SampleIOProcessor.
References nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutput::addSourceSampleTags(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::core::SampleOutput::getName(), nidas::core::SampleSource::getProcessedSampleSource(), and nidas::core::SampleSource::getRawSampleSource().
Referenced by PacketDecode::run().
void SampleArchiver::connect (SampleOutput * output) throw () virtual
Implementation of SampleConnectionRequester::connect(SampleOutput*).
Implements nidas::core::SampleConnectionRequester.
References nidas::core::SampleSource::addSampleClient(), nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_INFO, and WLOG.
void SampleArchiver::disconnect (SampleSource * source) throw () virtual
Implementation of SampleIOProcessor::disconnect(SampleSource*).
Implements nidas::core::SampleIOProcessor.
References nidas::core::SampleSource::getProcessedSampleSource(), and nidas::core::SampleSource::getRawSampleSource().
Referenced by PacketDecode::run().
void SampleArchiver::disconnect (SampleOutput * output) throw () virtual
Implementation of SampleConnectionRequester::disconnect(SampleOutput*).
Implements nidas::core::SampleConnectionRequester.
References nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutputRequestThread::addDeleteRequest(), nidas::core::IOChannel::flush(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getOriginal(), nidas::core::SampleOutput::getReconnectDelaySecs(), nidas::util::Logger::log(), LOG_ERR, nidas::core::SampleSource::removeSampleClient(), and nidas::util::Exception::what().
void SampleArchiver::flush () throw () virtual
Implementation of SampleSource::flush().
Implements nidas::core::SampleSource.
References _connectedOutputs, _connectionMutex, and nidas::core::SampleClient::flush().
void SampleIOProcessor::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual inherited
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::raf::CVIProcessor.
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Parameter::createParameter(), nidas::core::DOMable::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::Project::getInstance(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::SampleTag::getSampleId(), nidas::core::SampleTag::setSampleId(), nidas::core::SampleTag::setSensorId(), and nidas::util::Exception::what().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), and nidas::core::DSMConfig::fromDOMElement().
int nidas::core::SampleIOProcessor::getClientCount () const throw () inline virtual inherited
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getClientCount().
virtual const DSMConfig* nidas::core::SampleIOProcessor::getDSMConfig () const inline virtual inherited
What DSM am I associated with?
References nidas::core::SampleIOProcessor::_dsm.
dsm_sample_id_t nidas::core::SampleIOProcessor::getId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_FULL_ID.
const std::string & SampleIOProcessor::getName () const virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by nidas::dynld::raf::CVIProcessor::fromDOMElement(), nidas::dynld::RawSampleService::schedule(), and nidas::dynld::StatisticsProcessor::~StatisticsProcessor().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
virtual const std::list<SampleOutput*>& nidas::core::SampleIOProcessor::getOutputs () const inline virtual inherited
References nidas::core::SampleIOProcessor::_origOutputs.
Referenced by nidas::core::Project::findServerSampleOutputStreamFileSets(), nidas::dynld::isff::GOESProject::GOESProject(), and StatsProcess::run().
const std::list<const Parameter*>& nidas::core::SampleIOProcessor::getParameters () const inline inherited
Get list of parameters.
References nidas::core::SampleIOProcessor::_constParameters.
SampleSource* nidas::core::SampleIOProcessor::getProcessedSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References nidas::core::SampleIOProcessor::_source.
bool nidas::core::SampleArchiver::getRaw () const inline
References _rawArchive.
SampleSource* nidas::core::SampleIOProcessor::getRawSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
std::list< const SampleTag * > SampleIOProcessor::getRequestedSampleTags () const virtual inherited
References nidas::core::SampleIOProcessor::_constRequestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::core::SampleTagIterator::hasNext(), and StatsProcess::listOutputSamples().
unsigned int nidas::core::SampleIOProcessor::getSampleId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_SPS_ID.
Referenced by StatsProcess::listOutputSamples(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
const SampleStats& nidas::core::SampleIOProcessor::getSampleStats () const inline virtual inherited
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleStats().
SampleTagIterator nidas::core::SampleIOProcessor::getSampleTagIterator () const inline virtual inherited
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleTagIterator().
std::list<const SampleTag*> nidas::core::SampleIOProcessor::getSampleTags () const inline virtual inherited
Implementation of SampleSource::getSampleTags().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::psql::PSQLProcessor.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleTags().
virtual const DSMService* nidas::core::SampleIOProcessor::getService () const inline virtual inherited
What DSMService am I associated with?
References nidas::core::SampleIOProcessor::_service.
virtual void nidas::core::SampleIOProcessor::init (dsm_time_t) throw () inline virtual inherited
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
Referenced by nidas::dynld::RawSampleService::schedule().
virtual bool nidas::core::SampleIOProcessor::isOptional () const inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
Referenced by nidas::dynld::RawSampleService::schedule().
SampleArchiver& nidas::core::SampleArchiver::operator= (const SampleArchiver & x) private
Assignment not supported.
void SampleArchiver::printStatus (std::ostream & , float deltat, int &) throw () virtual
Reimplemented from nidas::core::SampleIOProcessor.
References err, nidas::util::UTime::format(), nidas::core::FileSet::getCurrentName(), nidas::core::FileSet::getFileSize(), nidas::core::SampleStats::getLastTimeTag(), nidas::core::SampleStats::getNumBytes(), nidas::core::SampleStats::getNumSamples(), and nidas::core::SampleSource::getSampleStats().
void SampleIOProcessor::removeRequestedSampleTag (SampleTag * tag) protected inherited
Allow subclasses to remove requested SampleTags.
The tag will be deleted.
References nidas::core::SampleIOProcessor::_constRequestedTags, nidas::core::SampleIOProcessor::_requestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
void nidas::core::SampleIOProcessor::removeSampleClient (SampleClient * c) throw () inline virtual inherited
Remove a SampleClient from this SampleSource.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::removeSampleClient().
void nidas::core::SampleIOProcessor::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
void SampleIOProcessor::removeSampleTag (const SampleTag * tag) throw () virtual inherited
Implements nidas::core::SampleSource.
virtual void nidas::core::SampleIOProcessor::setDSMConfig (const DSMConfig * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_dsm.
Referenced by nidas::core::DSMConfig::fromDOMElement().
void SampleIOProcessor::setName (const std::string & val) virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by nidas::dynld::psql::PSQLProcessor::PSQLProcessor(), SampleArchiver(), nidas::dynld::StatisticsProcessor::StatisticsProcessor(), and nidas::dynld::raf::SyncRecordGenerator::SyncRecordGenerator().
virtual void nidas::core::SampleIOProcessor::setOptional (bool val) inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
void nidas::core::SampleArchiver::setRaw (bool val) inline
By default a SampleArchiver is used for archiving raw samples, and any SampleOutputs that connect will receive samples from source->getRawSampleSource(), even if the output->isRaw() method returns false.
This is to correct possible human errors in the configuation. If setRaw(false), then this SampleArchiver will archive processed samples, by connecting outputs to source->getProcessedSampleSource(). If the value of an output->isRaw() disgrees with getRaw() of this SampleArchive, a warning message is logged.
References _rawArchive.
void nidas::core::SampleIOProcessor::setSampleId (int val) inline inherited
References nidas::core::SampleIOProcessor::_id, and SET_SPS_ID.
virtual void nidas::core::SampleIOProcessor::setService (const DSMService * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_service.
Referenced by nidas::core::DSMService::fromDOMElement().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
std::set<SampleOutput*> nidas::core::SampleArchiver::_connectedOutputs private
Referenced by flush(), and ~SampleArchiver().
std::set<SampleSource*> nidas::core::SampleArchiver::_connectedSources private
Referenced by ~SampleArchiver().
nidas::util::Mutex nidas::core::SampleArchiver::_connectionMutex private
Referenced by flush(), and ~SampleArchiver().
nidas::util::Mutex nidas::core::SampleArchiver::_filesetMutex private
Mutex for controlling access to _filesets so that printStatus has valid pointers.
std::list<const nidas::core::FileSet*> nidas::core::SampleArchiver::_filesets private
If my SampleOutput* is a nidas::core::FileSet then save the pointer for use in by printStatus(), so that the status output will contain things like the file size.
long long nidas::core::SampleArchiver::_nbytesLast private
Saved between calls to printStatus in order to compute data rates.
std::map<const nidas::core::FileSet*,long long> nidas::core::SampleArchiver::_nbytesLastByFileSet private
size_t nidas::core::SampleArchiver::_nsampsLast private
Saved between calls to printStatus in order to compute sample rates.
bool nidas::core::SampleArchiver::_rawArchive private
Referenced by getRaw(), and setRaw().
std::list<SampleTag*> nidas::core::SampleIOProcessor::_requestedTags protected inherited
Referenced by nidas::core::SampleIOProcessor::removeRequestedSampleTag(), nidas::dynld::StatisticsProcessor::selectRequestedSampleTags(), and nidas::core::SampleIOProcessor::~SampleIOProcessor().
SampleSourceSupport nidas::core::SampleIOProcessor::_source protected inherited
Referenced by nidas::core::SampleIOProcessor::addSampleClient(), nidas::core::SampleIOProcessor::addSampleClientForTag(), nidas::core::SampleIOProcessor::getClientCount(), nidas::core::SampleIOProcessor::getProcessedSampleSource(), nidas::core::SampleIOProcessor::getSampleStats(), nidas::core::SampleIOProcessor::getSampleTagIterator(), nidas::core::SampleIOProcessor::getSampleTags(), nidas::core::SampleIOProcessor::removeSampleClient(), and nidas::core::SampleIOProcessor::removeSampleClientForTag().
nidas::util::Mutex nidas::core::SampleIOProcessor::_tagsMutex mutable protected inherited
Referenced by nidas::core::SampleIOProcessor::getRequestedSampleTags(), nidas::core::SampleIOProcessor::removeRequestedSampleTag(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
The documentation for this class was generated from the following files:
nidas/core/SampleArchiver.h
nidas/core/SampleArchiver.cc