nidas: Document Class Reference
Document Class Reference
#include <Document.h>
Classes
struct A2DVariableInfo
class MyErrorHandler
Public Member Functions
Document (QString engCalDirRoot, ConfigWindow *cw)
~Document ()
const char * getDirectory () const
const std::string getFilename () const
void setFilename (const std::string &f)
xercesc::DOMDocument * getDomDocument () const
void setDomDocument (xercesc::DOMDocument *d)
bool writeDocument ()
string getProjectName () const
void setProjectName (string projectName)
xercesc::DOMNode * getDSMNode (unsigned int dsmId)
bool writeDOM (xercesc::XMLFormatTarget *const target, const xercesc::DOMNode *node)
const xercesc::DOMElement * findSensor (const std::string &sensorIdName)
Find a sensor in Project's DOM sensor catalog based on its XML attribute "ID" (i.e. the Name)
void parseFile ()
void printSiteNames ()
vector< std::string > getSiteNames ()
unsigned int getNextSensorId ()
unsigned int getNextDSMId ()
list< int > getAvailableA2DChannels ()
void addSensor (const std::string &sensorIdName, const std::string &device, const std::string &lcId, const std::string &sfx, const std::string &a2dTempSfx, const std::string &a2dSNFname, const std::string &pmsSN, const std::string &resltn)
void updateSensor (const std::string &sensorIdName, const std::string &device, const std::string &lcId, const std::string &sfx, const std::string &a2dTempSfx, const std::string &a2dSNFname, const std::string &pmsSN, const std::string &resltn, QModelIndexList indexList)
void addA2DRate (xercesc::DOMElement *sensorElem, xercesc::DOMNode *dsmNode, const std::string &a2dSNFname)
void addA2DCalFile (xercesc::DOMElement *sensorElem, xercesc::DOMNode *dsmNode, const std::string &a2dSNFname)
void addSampAndVar (xercesc::DOMElement *sensorElem, xercesc::DOMNode *dsmNode, const std::string &a2dTempSfx)
void updateSampAndVar (xercesc::DOMElement *sensorElem, xercesc::DOMNode *dsmNode, const std::string &a2dTempSfx)
void updateSensorDOM (SensorItem *sItem, const std::string &device, const std::string &lcId, const std::string &sfx)
void addDSM (const std::string &dsmName, const std::string &dsmId, const std::string &dsmLocation)
void updateDSM (const std::string &dsmName, const std::string &dsmId, const std::string &dsmLocation, QModelIndexList indexList)
void updateDSMDOM (DSMItem *dsmItem, const std::string &dsmName, const std::string &dsmId, const std::string &dsmLocation)
unsigned int validateDsmInfo (Site *site, const std::string &dsmName, const std::string &dsmId)
xercesc::DOMElement * createDsmOutputElem (xercesc::DOMNode *siteNode)
xercesc::DOMElement * createDsmServOutElem (xercesc::DOMNode *siteNode)
unsigned int validateSampleInfo (DSMSensor *sensor, const std::string &sampleId)
xercesc::DOMElement * createA2DTempVarElement (xercesc::DOMNode *seniorNode, const std::string &a2dTempSfx)
xercesc::DOMElement * createA2DTempParmElement (xercesc::DOMNode *seniorNode)
xercesc::DOMElement * createSampleElement (xercesc::DOMNode *sensorNode, const std::string &sampleId, const std::string &sampleRate, const std::string &sampleFilter)
void addA2DVariable (const std::string &a2dVarNamePfx, const std::string &a2dVarNameSfx, const std::string &a2dVarLongName, const std::string &a2dVarVolts, const std::string &a2dVarChannel, const std::string &a2dSR, const std::string &a2dVarUnits, vector< std::string > cals)
void insertA2DVariable (NidasModel *model, A2DSensorItem *sensorItem, DOMNode *sensorNode, DSMAnalogSensor *analogSensor, const std::string &a2dVarNamePfx, const std::string &a2dVarNameSfx, const std::string &a2dVarLongName, const std::string &a2dVarVolts, const std::string &a2dVarChannel, const std::string &a2dVarSR, const std::string &a2dVarUnits, vector< std::string > cals)
void updateVariable (VariableItem *varItem, const std::string &VarName, const std::string &VarLongName, const std::string &SR, const std::string &VarUnits, vector< std::string > cals, bool useCalfile)
void addCalibElem (vector< std::string > cals, const std::string &a2dVarUnits, xercesc::DOMNode *sampleNode, xercesc::DOMElement *varElem)
void addVarCalFileElem (std::string varCalFileName, const std::string &varUnits, const std::string &siteName, xercesc::DOMNode *sampleNode, xercesc::DOMElement *varElem)
void addPMSParms (xercesc::DOMElement *sensorElem, xercesc::DOMNode *dsmNode, const std::string &pmsSN, const std::string &pmsResltn)
bool isChanged ()
void setIsChanged (bool changed)
bool isChangedBig ()
void setIsChangedBig (bool changed)
vector< QString > getMissingEngCalFiles ()
void addMissingEngCalFile (QString filename)
bool engCalDirExists ()
QString getEngCalDir ()
Private Member Functions
bool isNum (std::string str)
Private Attributes
Project * _project
std::string * filename
const ConfigWindow * _configWindow
xercesc::DOMDocument * domdoc
Document::MyErrorHandler errorHandler
QString _engCalDir
QString _engCalDirRoot
std::vector< QString > _engCalFiles
bool _engCalDirExists
vector< QString > _missingEngCalFiles
bool _isChanged
bool _isChangedBig
const unsigned int _MIN_WING_DSM_ID
Constructor & Destructor Documentation
Document::Document (QString engCalDirRoot, ConfigWindow * cw) inline
Document::~Document () inline
Member Function Documentation
void Document::addA2DCalFile (xercesc::DOMElement * sensorElem, xercesc::DOMNode * dsmNode, const std::string & a2dSNFname)
void Document::addA2DRate (xercesc::DOMElement * sensorElem, xercesc::DOMNode * dsmNode, const std::string & a2dSNFname)
void Document::addA2DVariable (const std::string & a2dVarNamePfx, const std::string & a2dVarNameSfx, const std::string & a2dVarLongName, const std::string & a2dVarVolts, const std::string & a2dVarChannel, const std::string & a2dSR, const std::string & a2dVarUnits, vector< std::string > cals)
References Document::A2DVariableInfo::a2dVarChannel, Document::A2DVariableInfo::a2dVarLongName, Document::A2DVariableInfo::a2dVarNamePfx, Document::A2DVariableInfo::a2dVarNameSfx, Document::A2DVariableInfo::a2dVarSR, Document::A2DVariableInfo::a2dVarUnits, Document::A2DVariableInfo::a2dVarVolts, Document::A2DVariableInfo::cals, A2DSensorItem::child(), NidasItem::childCount(), NidasItem::createIndex(), A2DVariableItem::getA2DChannel(), A2DVariableItem::getBipolar(), A2DVariableItem::getCalibrationInfo(), NidasModel::getCurrentRootItem(), SensorItem::getDOMNode(), SensorItem::getDSMSensor(), A2DVariableItem::getGain(), A2DVariableItem::getLongName(), A2DVariableItem::getRate(), A2DVariableItem::getUnits(), A2DVariableItem::getVarNamePfx(), A2DVariableItem::getVarNameSfx(), if(), and A2DVariableItem::variableName().
Referenced by config::AddA2DVariableComboDialog::accept().
void Document::addCalibElem (vector< std::string > cals, const std::string & a2dVarUnits, xercesc::DOMNode * sampleNode, xercesc::DOMElement * varElem)
void Document::addDSM (const std::string & dsmName, const std::string & dsmId, const std::string & dsmLocation)
References nidas::core::Site::addDSMConfig(), NidasModel::appendChild(), nidas::core::DSMConfig::fromDOMElement(), NidasModel::getCurrentRootItem(), SiteItem::getDOMNode(), SiteItem::getSite(), nidas::core::Site::removeDSMConfig(), nidas::core::DSMConfig::setId(), nidas::core::DSMConfig::setLocation(), nidas::core::DSMConfig::setName(), and nidas::core::DSMConfig::setSite().
Referenced by config::AddDSMComboDialog::accept().
void Document::addMissingEngCalFile (QString filename)
void Document::addPMSParms (xercesc::DOMElement * sensorElem, xercesc::DOMNode * dsmNode, const std::string & pmsSN, const std::string & pmsResltn)
void Document::addSampAndVar (xercesc::DOMElement * sensorElem, xercesc::DOMNode * dsmNode, const std::string & a2dTempSfx)
void Document::addSensor (const std::string & sensorIdName, const std::string & device, const std::string & lcId, const std::string & sfx, const std::string & a2dTempSfx, const std::string & a2dSNFname, const std::string & pmsSN, const std::string & resltn)
References nidas::core::DSMConfig::addSensor(), NidasModel::appendChild(), NidasModel::getCurrentRootItem(), DSMItem::getDOMNode(), DSMItem::getDSMConfig(), nidas::core::DSMConfig::getSensors(), nidas::core::DSMConfig::getSite(), nidas::core::DSMConfig::removeSensor(), nidas::core::DSMConfig::sensorFromDOMElement(), nidas::core::DSMConfig::validate(), nidas::core::Site::validate(), and nidas::core::DSMSensor::validate().
Referenced by config::AddSensorComboDialog::accept().
void Document::addVarCalFileElem (std::string varCalFileName, const std::string & varUnits, const std::string & siteName, xercesc::DOMNode * sampleNode, xercesc::DOMElement * varElem)
xercesc::DOMElement * Document::createA2DTempParmElement (xercesc::DOMNode * seniorNode)
xercesc::DOMElement * Document::createA2DTempVarElement (xercesc::DOMNode * seniorNode, const std::string & a2dTempSfx)
xercesc::DOMElement * Document::createDsmOutputElem (xercesc::DOMNode * siteNode)
xercesc::DOMElement * Document::createDsmServOutElem (xercesc::DOMNode * siteNode)
xercesc::DOMElement * Document::createSampleElement (xercesc::DOMNode * sensorNode, const std::string & sampleId, const std::string & sampleRate, const std::string & sampleFilter)
bool Document::engCalDirExists () inline
Referenced by ConfigWindow::openFile().
const xercesc::DOMElement * Document::findSensor (const std::string & sensorIdName)
Find a sensor in Project's DOM sensor catalog based on its XML attribute "ID" (i.e. the Name)
Returns
DOMElement pointer from the Sensor Catalog or NULL
std::list< int > Document::getAvailableA2DChannels ()
References nidas::core::Variable::getA2dChannel(), NidasModel::getCurrentRootItem(), SensorItem::getDSMSensor(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTagIterator::hasNext(), and nidas::core::VariableIterator::hasNext().
Referenced by config::AddA2DVariableComboDialog::SetUpChannelBox().
const char * Document::getDirectory () const
Referenced by ConfigWindow::saveAsFile(), and ConfigWindow::writeProjectName().
xercesc::DOMDocument* Document::getDomDocument () const inline
Referenced by ConfigWindow::setupModelView().
xercesc::DOMNode* Document::getDSMNode (unsigned int dsmId)
QString Document::getEngCalDir () inline
Referenced by ConfigWindow::openFile().
const std::string Document::getFilename () const inline
Referenced by ConfigWindow::askSaveFileAndContinue(), ConfigWindow::saveAsFile(), ConfigWindow::saveFile(), and ConfigWindow::saveFileCopy().
vector<QString> Document::getMissingEngCalFiles () inline
Referenced by ConfigWindow::saveFile().
unsigned int Document::getNextDSMId ()
References NidasModel::getCurrentRootItem(), nidas::core::Site::getDSMConfigs(), nidas::core::Site::getName(), and SiteItem::getSite().
Referenced by config::AddDSMComboDialog::setUpDialog().
unsigned int Document::getNextSensorId ()
References NidasModel::getCurrentRootItem(), DSMItem::getDSMConfig(), nidas::core::DSMConfig::getName(), and nidas::core::DSMConfig::getSensors().
Referenced by config::AddSensorComboDialog::setUpDialog().
string Document::getProjectName () const
Referenced by ConfigWindow::editProjName().
vector< std::string > Document::getSiteNames ()
References nidas::core::Site::getName(), and nidas::core::SiteIterator::hasNext().
Referenced by ConfigWindow::openFile().
void Document::insertA2DVariable (NidasModel * model, A2DSensorItem * sensorItem, DOMNode * sensorNode, DSMAnalogSensor * analogSensor, const std::string & a2dVarNamePfx, const std::string & a2dVarNameSfx, const std::string & a2dVarLongName, const std::string & a2dVarVolts, const std::string & a2dVarChannel, const std::string & a2dVarSR, const std::string & a2dVarUnits, vector< std::string > cals)
References nidas::dynld::raf::DSMAnalogSensor::addSampleTag(), nidas::core::SampleTag::addVariable(), NidasModel::appendChild(), A2DSensorItem::child(), NidasItem::childCount(), SensorItem::findSampleDOMNode(), nidas::core::SampleTag::fromDOMElement(), nidas::core::Variable::fromDOMElement(), nidas::core::DSMSensor::getDSMId(), nidas::core::Site::getName(), nidas::core::SampleTag::getParameter(), nidas::core::SampleTag::getRate(), nidas::core::SampleTag::getSampleId(), A2DVariableItem::getSampleTag(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMSensor::getSite(), nidas::core::SampleTag::getSite(), nidas::core::DSMSensor::removeSampleTag(), nidas::core::SampleTag::removeVariable(), nidas::core::Variable::setA2dChannel(), nidas::dynld::raf::DSMAnalogSensor::setA2DParameters(), nidas::core::SampleTag::setDSMId(), nidas::core::Variable::setSampleTag(), nidas::core::SampleTag::setSensorId(), nidas::core::Variable::setSite(), and nidas::core::Site::validate().
bool Document::isChanged () inline
Referenced by ConfigWindow::askSaveFileAndContinue().
bool Document::isChangedBig () inline
Referenced by ConfigWindow::askSaveFileAndContinue().
bool Document::isNum (std::string str) private
void Document::parseFile ()
References nidas::core::XMLParser::parse(), nidas::core::XMLParser::setDOMDatatypeNormalization(), nidas::core::XMLParser::setDOMNamespaces(), nidas::core::XMLParser::setDOMValidateIfSchema(), nidas::core::XMLParser::setDOMValidation(), nidas::core::XMLParser::setXercesDoXInclude(), nidas::core::XMLParser::setXercesHandleMultipleImports(), nidas::core::XMLParser::setXercesSchema(), nidas::core::XMLParser::setXercesSchemaFullChecking(), and nidas::core::XMLParser::setXercesUserAdoptsDOMDocument().
Referenced by ConfigWindow::openFile().
void Document::printSiteNames ()
References nidas::core::Site::getName(), nidas::core::Project::getName(), nidas::core::Site::getNumber(), nidas::core::Site::getProject(), nidas::core::Site::getSuffix(), and nidas::core::SiteIterator::hasNext().
Referenced by ConfigWindow::openFile().
void Document::setDomDocument (xercesc::DOMDocument * d) inline
void Document::setFilename (const std::string & f) inline
Referenced by ConfigWindow::openFile(), and ConfigWindow::saveAsFile().
void Document::setIsChanged (bool changed) inline
Referenced by config::AddSensorComboDialog::accept(), config::VariableComboDialog::accept(), config::AddA2DVariableComboDialog::accept(), config::AddDSMComboDialog::accept(), and ConfigWindow::saveFile().
void Document::setIsChangedBig (bool changed) inline
Referenced by config::AddA2DVariableComboDialog::accept(), ConfigWindow::deleteA2DVariable(), ConfigWindow::deleteDSM(), ConfigWindow::deleteSensor(), and ConfigWindow::saveFile().
void Document::setProjectName (string projectName)
References ProjectItem::getDOMNode(), and NidasModel::getRootItem().
Referenced by ConfigWindow::writeProjectName().
void Document::updateDSM (const std::string & dsmName, const std::string & dsmId, const std::string & dsmLocation, QModelIndexList indexList)
References DSMItem::fromDOM(), DSMItem::getDSMConfig(), nidas::core::DSMConfig::getId(), NidasModel::getItem(), nidas::core::DSMConfig::getLocation(), nidas::core::DSMConfig::getName(), nidas::core::DSMConfig::getSite(), and nidas::core::Site::validate().
Referenced by config::AddDSMComboDialog::accept().
void Document::updateDSMDOM (DSMItem * dsmItem, const std::string & dsmName, const std::string & dsmId, const std::string & dsmLocation)
References DSMItem::getDOMNode().
void Document::updateSampAndVar (xercesc::DOMElement * sensorElem, xercesc::DOMNode * dsmNode, const std::string & a2dTempSfx)
void Document::updateSensor (const std::string & sensorIdName, const std::string & device, const std::string & lcId, const std::string & sfx, const std::string & a2dTempSfx, const std::string & a2dSNFname, const std::string & pmsSN, const std::string & resltn, QModelIndexList indexList)
References SensorItem::fromDOM(), A2DSensorItem::getA2DTempSuffix(), nidas::core::DSMSensor::getCalFiles(), NidasModel::getCurrentRootItem(), nidas::core::DSMSensor::getDeviceName(), DSMItem::getDSMConfig(), SensorItem::getDSMSensor(), NidasModel::getItem(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMSensor::getSuffix(), A2DSensorItem::updateDOMA2DTempSfx(), A2DSensorItem::updateDOMCalFile(), and PMSSensorItem::updateDOMPMSParams().
Referenced by config::AddSensorComboDialog::accept().
void Document::updateSensorDOM (SensorItem * sItem, const std::string & device, const std::string & lcId, const std::string & sfx)
References SensorItem::getDOMNode().
void Document::updateVariable (VariableItem * varItem, const std::string & VarName, const std::string & VarLongName, const std::string & SR, const std::string & VarUnits, vector< std::string > cals, bool useCalfile)
References VariableItem::clearVarItem(), err, SensorItem::findSampleDOMNode(), SensorItem::fromDOM(), VariableItem::fromDOM(), nidas::core::SampleTag::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::XDOMElement::getAttributeValue(), VariableItem::getBaseName(), SensorItem::getBaseName(), NidasModel::getCurrentRootItem(), SensorItem::getDOMNode(), SensorItem::getDSMSensor(), nidas::core::Site::getName(), VariableItem::getSampleId(), VariableItem::getSampleTag(), nidas::core::DSMSensor::getSite(), VariableItem::name(), and nidas::core::Site::validate().
Referenced by config::VariableComboDialog::accept().
unsigned int Document::validateDsmInfo (Site * site, const std::string & dsmName, const std::string & dsmId)
References nidas::core::Site::getDSMConfigs(), nidas::core::DSMConfig::getId(), and nidas::core::DSMConfig::getName().
unsigned int Document::validateSampleInfo (DSMSensor * sensor, const std::string & sampleId)
References nidas::core::SampleTag::getId(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTagIterator::hasNext(), and nidas::core::SampleTagIterator::next().
bool Document::writeDocument ()
Referenced by ConfigWindow::saveFile().
bool Document::writeDOM (xercesc::XMLFormatTarget *const target, const xercesc::DOMNode * node)
References gLS, and gNull.
Member Data Documentation
const ConfigWindow* Document::_configWindow private
QString Document::_engCalDir private
bool Document::_engCalDirExists private
QString Document::_engCalDirRoot private
std::vector<QString> Document::_engCalFiles private
bool Document::_isChanged private
bool Document::_isChangedBig private
const unsigned int Document::_MIN_WING_DSM_ID private
vector<QString> Document::_missingEngCalFiles private
Project* Document::_project private
xercesc::DOMDocument* Document::domdoc private
Document::MyErrorHandler Document::errorHandler private
std::string* Document::filename private
The documentation for this class was generated from the following files:
nidas/apps/config/Document.h
nidas/apps/config/Document.cc