nidas: NidasModel Class Reference
NidasModel Class Reference
#include <NidasModel.h>
Public Member Functions
NidasModel (nidas::core::Project *project, xercesc::DOMDocument *doc, QObject *parent=0)
Implements the Qt Model API for Nidas business model (Project tree and DOM tree)
~NidasModel ()
QVariant data (const QModelIndex &index, int role) const
Qt::ItemFlags flags (const QModelIndex &index) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &child) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
int columnCount (const QModelIndex &parent=QModelIndex()) const
QVariant headerData (int section, Qt::Orientation orientation, int role) const
QVariant headerData (int section, Qt::Orientation orientation, int role, const QModelIndex &parent) const
bool appendChild (NidasItem *parentItem)
Add a child to parentItem by updating the Qt model and thus also the NidasItem tree from Project.
bool insertRows (int row, int count, const QModelIndex &parent)
Create a QModelIndex for the NidasItem that points to nidasData and is a descendant of startItem.
bool removeIndexes (QModelIndexList indexList)
bool removeChildren (std::list< int > &selectedRows, NidasItem *parentItem)
Remove children for the selectedRows from the parentItem.
bool removeRows (int row, int count, const QModelIndex &parent)
xercesc::DOMDocument * getDOMDocument () const
void setCurrentRootIndex (const QModelIndex &index)
NidasItem * getCurrentRootItem ()
NidasItem * getItem (const QModelIndex &index) const
NidasItem * getRootItem () const
Private Attributes
NidasItem * rootItem
xercesc::DOMDocument * domDoc
QPersistentModelIndex _currentRootIndex
Friends
class NidasItem
Constructor & Destructor Documentation
NidasModel::NidasModel (nidas::core::Project * project, xercesc::DOMDocument * doc, QObject * parent = 0)
Implements the Qt Model API for Nidas business model (Project tree and DOM tree)
NidasModel fulfills the requirements to work in the Qt world and uses NidasItem as a proxy for the business models.
References domDoc, and rootItem.
NidasModel::~NidasModel ()
References rootItem.
Member Function Documentation
bool NidasModel::appendChild (NidasItem * parentItem)
Add a child to parentItem by updating the Qt model and thus also the NidasItem tree from Project.
try to get a DSMConfig from the current root index (i.e. current table view's root)
Returns something useful only when a DSM is the current rootIndex
Returns
pointer to the DSMItem or NULL if current root is not a DSM
DSMItem * NidasModel::getCurrentDSMItem() { DSMItem dsmItem = dynamic_cast<DSMItem>(getItem(_currentRootIndex)); if (!dsmItem) throw InternalProcessingException("Current root index is not a DSM."); return dsmItem; }
   Hard work done in insertRows()
See Also
insertRows()
References NidasItem::createIndex(), insertRows(), and rowCount().
Referenced by Document::addDSM(), Document::addSensor(), and Document::insertA2DVariable().
int NidasModel::columnCount (const QModelIndex & parent = QModelIndex()) const
References NidasItem::childColumnCount(), and getItem().
QVariant NidasModel::data (const QModelIndex & index, int role) const
References NidasItem::dataField().
Qt::ItemFlags NidasModel::flags (const QModelIndex & index) const
NidasItem* NidasModel::getCurrentRootItem () inline
References _currentRootIndex, and getItem().
Referenced by Document::addA2DVariable(), Document::addDSM(), Document::addSensor(), Document::getAvailableA2DChannels(), Document::getNextDSMId(), Document::getNextSensorId(), Document::updateSensor(), and Document::updateVariable().
xercesc::DOMDocument* NidasModel::getDOMDocument () const inline
References domDoc.
NidasItem * NidasModel::getItem (const QModelIndex & index) const
References rootItem.
Referenced by ConfigWindow::changeToIndex(), columnCount(), getCurrentRootItem(), headerData(), insertRows(), removeIndexes(), removeRows(), rowCount(), config::AddDSMComboDialog::setUpDialog(), config::AddSensorComboDialog::setUpDialog(), config::VariableComboDialog::show(), config::AddA2DVariableComboDialog::show(), Document::updateDSM(), and Document::updateSensor().
NidasItem* NidasModel::getRootItem () const inline
Referenced by Document::setProjectName().
QVariant NidasModel::headerData (int section, Qt::Orientation orientation, int role) const inline
References _currentRootIndex.
QVariant NidasModel::headerData (int section, Qt::Orientation orientation, int role, const QModelIndex & parent) const
References NidasItem::childLabel(), getItem(), and parent().
QModelIndex NidasModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
References NidasItem::child(), and rootItem.
Referenced by removeIndexes(), and setCurrentRootIndex().
bool NidasModel::insertRows (int row, int count, const QModelIndex & parent)
Create a QModelIndex for the NidasItem that points to nidasData and is a descendant of startItem.
Stoopid recursive search implemented to see what works.
QModelIndex NidasModel::findIndex(void *nidasData, NidasItem *startItem) const { if (startItem == 0) startItem=rootItem; if (startItem == 0) return QModelIndex();
int ct = startItem->childCount();
for (int i=0; i<ct; i++) { NidasItem *item = startItem->child(i); if (item->pointsTo(nidasData)) return createIndex(i,0,item); else { QModelIndex index = findIndex(nidasData,item); if (index.isValid()) return(index); } }
return QModelIndex(); }
References NidasItem::child(), NidasItem::childCount(), and getItem().
Referenced by appendChild().
QModelIndex NidasModel::parent (const QModelIndex & child) const
References NidasItem::parent(), rootItem, and NidasItem::row().
Referenced by headerData().
bool NidasModel::removeChildren (std::list< int > & selectedRows, NidasItem * parentItem)
Remove children for the selectedRows from the parentItem.
   Hard work done in removeRows()
See Also
removeRows()
References NidasItem::createIndex(), and removeRows().
bool NidasModel::removeIndexes (QModelIndexList indexList)
References NidasItem::createIndex(), getItem(), index(), NidasItem::parent(), removeRows(), and NidasItem::row().
Referenced by config::AddA2DVariableComboDialog::accept(), ConfigWindow::deleteA2DVariable(), ConfigWindow::deleteDSM(), and ConfigWindow::deleteSensor().
bool NidasModel::removeRows (int row, int count, const QModelIndex & parent)
References getItem(), and NidasItem::removeChildren().
Referenced by removeChildren(), and removeIndexes().
int NidasModel::rowCount (const QModelIndex & parent = QModelIndex()) const
References NidasItem::childCount(), and getItem().
Referenced by appendChild().
void NidasModel::setCurrentRootIndex (const QModelIndex & index) inline
References _currentRootIndex, and index().
Referenced by ConfigWindow::changeToIndex().
Friends And Related Function Documentation
friend class NidasItem friend
Member Data Documentation
QPersistentModelIndex NidasModel::_currentRootIndex private
Referenced by getCurrentRootItem(), headerData(), and setCurrentRootIndex().
xercesc::DOMDocument* NidasModel::domDoc private
Referenced by getDOMDocument(), and NidasModel().
NidasItem* NidasModel::rootItem private
Referenced by getItem(), index(), NidasModel(), parent(), and ~NidasModel().
The documentation for this class was generated from the following files:
nidas/apps/config/nidas_qmv/NidasModel.h
nidas/apps/config/nidas_qmv/NidasModel.cc