nidas: config::VariableComboDialog Class Reference
config::VariableComboDialog Class Reference
#include <VariableComboDialog.h>
Public Slots
void accept ()
void reject ()
void show (NidasModel *model, QModelIndexList indexList)
Public Member Functions
VariableComboDialog (QWidget *parent=0)
~VariableComboDialog ()
void setDocument (Document *document)
Protected Attributes
QMessageBox * _errorMessage
Document * _document
Private Member Functions
void setCalLabels ()
Private Attributes
VariableItem * _varItem
QModelIndexList _indexList
NidasModel * _model
int _origSRBoxIndex
bool _xmlCals
Constructor & Destructor Documentation
VariableComboDialog::VariableComboDialog (QWidget * parent = 0)
References _errorMessage, _varnameRegEx(), _varunitRegEx(), and _xmlCals.
config::VariableComboDialog::~VariableComboDialog () inline
Member Function Documentation
void VariableComboDialog::accept () slot
References _document, _errorMessage, _indexList, _varItem, _xmlCals, Document::setIsChanged(), nidas::util::Exception::toString(), and Document::updateVariable().
void config::VariableComboDialog::reject () inline slot
void VariableComboDialog::setCalLabels () private
Referenced by show().
void config::VariableComboDialog::setDocument (Document * document) inline
References _document.
Referenced by ConfigWindow::openFile().
void VariableComboDialog::show (NidasModel * model, QModelIndexList indexList) slot
References _indexList, _model, _varItem, _xmlCals, VariableItem::getBaseName(), VariableItem::getCalibrationInfo(), VariableItem::getCalSrc(), NidasModel::getItem(), VariableItem::getLongName(), VariableItem::getRate(), nidas::core::Variable::getUnits(), VariableItem::getVariable(), rate, and setCalLabels().
Referenced by ConfigWindow::editVariableCombo().
Member Data Documentation
Document* config::VariableComboDialog::_document protected
Referenced by accept(), and setDocument().
QMessageBox* config::VariableComboDialog::_errorMessage protected
Referenced by accept(), and VariableComboDialog().
QModelIndexList config::VariableComboDialog::_indexList private
Referenced by accept(), and show().
NidasModel* config::VariableComboDialog::_model private
Referenced by show().
int config::VariableComboDialog::_origSRBoxIndex private
VariableItem* config::VariableComboDialog::_varItem private
Referenced by accept(), and show().
bool config::VariableComboDialog::_xmlCals private
Referenced by accept(), show(), and VariableComboDialog().
The documentation for this class was generated from the following files:
nidas/apps/config/VariableComboDialog.h
nidas/apps/config/VariableComboDialog.cc