nidas: ProjectItem Class Reference
ProjectItem Class Reference
#include <ProjectItem.h>
Public Member Functions
ProjectItem (Project *project, int row, NidasModel *theModel, NidasItem *parent=0)
~ProjectItem ()
NidasItem * child (int i)
return the ith child of this item.
bool removeChild (NidasItem *item)
remove the site item from this Project's Nidas and DOM trees
QString dataField (int column)
const QVariant & childLabel (int column) const
int childColumnCount () const
Project * getProject () const
xercesc::DOMNode * getDOMNode ()
NidasItem * parent () const
int row () const
int childCount ()
bool removeChildren (int first, int last)
QModelIndex createIndex ()
NidasItem * getParentItem ()
Protected Member Functions
xercesc::DOMNode * findDOMNode ()
find the DOM node which defines this Project
QString name ()
Protected Attributes
xercesc::DOMNode * domNode
QList< NidasItem * > childItems
NidasItem * parentItem
int rowNumber
NidasModel * model
Static Protected Attributes
static const QVariant _Project_Label
static const QVariant _Site_Label
static const QVariant _DSM_Label
static const QVariant _Device_Label
static const QVariant _SN_Label
static const QVariant _ID_Label
static const QVariant _Sensor_Label
static const QVariant _Sample_Label
static const QVariant _DevChan_Label
static const QVariant _Suffix_Label
static const QVariant _Rate_Label
static const QVariant _Volt_Label
static const QVariant _Variable_Label
static const QVariant _CalCoefSrc_Label
static const QVariant _CalCoef_Label
static const QVariant _CalDate_Label
static const QVariant _Name_Label
static const QVariant _Channel_Label
static const QVariant _Unknown_Label
Private Attributes
Project * _project
Constructor & Destructor Documentation
ProjectItem::ProjectItem (Project * project, int row, NidasModel * theModel, NidasItem * parent = 0)
ProjectItem::~ProjectItem ()
Member Function Documentation
NidasItem * ProjectItem::child (int i) virtual
return the ith child of this item.
The primary mechanism for building the NidasItem tree. When Qt asks the NidasModel for info, it calls child(). Subclasses reimplement to build items for each type of Nidas object based on the parent's unique child iterators.
N.B. there is a QObject::child(objName,inheritsClass,recursiveSearch) from Qt3. Watch out...
Reimplemented from NidasItem.
References nidas::core::SiteIterator::hasNext(), and nidas::core::SiteIterator::next().
int ProjectItem::childColumnCount () const inline virtual
Reimplemented from NidasItem.
int NidasItem::childCount () inherited
NidasItem is a proxy for the actual Nidas objects in the Project tree and their corresponding DOMNodes. Qt indexing is mapped to the Project tree via parent/child with row the ordinal number of the siblings and columns used for data fields (attributes/properties) of each level of Nidas object.
Pointers to Nidas objects are void* since Nidas uses different classes at every level. NidasItem is (should/will be) subclassed for specialized Items corresponding to each kind of Nidas object in the Project tree and implementing their own logic for the API used by NidasModel (like the data and header returned for Qt columns).
The NidasItem tree is a mirror/proxy of the Nidas object Project tree, with children lazily initialized by child(). Row number, parent pointer, and a list of children are cached.
N.B. can only add children to end of list due to Nidas API and use of children list in child()
NidasItem could also become a QObject to get the parent/children stuff. This could be useful in future for findChild()/findChildren(). Except for the fact that it didn't work - something about Qt's cleanup of children caused problems for us.
References NidasItem::child(), and NidasItem::childItems.
Referenced by Document::addA2DVariable(), Document::insertA2DVariable(), NidasModel::insertRows(), and NidasModel::rowCount().
const QVariant& ProjectItem::childLabel (int column) const inline virtual
Reimplemented from NidasItem.
References NidasItem::_Site_Label.
QModelIndex NidasItem::createIndex () inline inherited
Asks the model to create an index for this item. Requires us to be a friend of NidasModel and for the model to ask NidasItem for the parent item.
Returns
a QModelIndex for this NidasItem
Referenced by Document::addA2DVariable(), NidasModel::appendChild(), NidasModel::removeChildren(), and NidasModel::removeIndexes().
QString ProjectItem::dataField (int column) virtual
Reimplemented from NidasItem.
DOMNode * ProjectItem::findDOMNode () protected
find the DOM node which defines this Project
References nidas::core::XDOMElement::getAttributeValue().
xercesc::DOMNode* ProjectItem::getDOMNode () inline
Referenced by Document::setProjectName().
NidasItem* NidasItem::getParentItem () inline inherited
Project* ProjectItem::getProject () const inline
QString ProjectItem::name () protected virtual
Reimplemented from NidasItem.
NidasItem* NidasItem::parent () const inline inherited
Referenced by NidasModel::parent(), and NidasModel::removeIndexes().
bool ProjectItem::removeChild (NidasItem * item) virtual
remove the site item from this Project's Nidas and DOM trees
current implementation confused between returning bool and throwing exceptions due to refactoring from Document
Reimplemented from NidasItem.
References nidas::core::XDOMElement::getAttributeValue(), nidas::core::Site::getName(), and nidas::core::XDOMElement::getNodeName().
bool NidasItem::removeChildren (int first, int last) inherited
References NidasItem::childItems, and NidasItem::rowNumber.
Referenced by NidasModel::removeRows().
int NidasItem::row () const inline inherited
Referenced by NidasModel::parent(), and NidasModel::removeIndexes().
Member Data Documentation
const QVariant NidasItem::_CalCoef_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_CalCoefSrc_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_CalDate_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Channel_Label static protected inherited
Referenced by A2DSensorItem::childLabel().
const QVariant NidasItem::_DevChan_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Device_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_DSM_Label static protected inherited
Referenced by SiteItem::childLabel().
const QVariant NidasItem::_ID_Label static protected inherited
Referenced by SiteItem::childLabel(), and DSMItem::childLabel().
const QVariant NidasItem::_Name_Label static protected inherited
Referenced by VariableItem::childLabel(), SiteItem::childLabel(), A2DVariableItem::childLabel(), and DSMItem::childLabel().
Project* ProjectItem::_project private
const QVariant NidasItem::_Project_Label static protected inherited
const QVariant NidasItem::_Rate_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Sample_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Sensor_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Site_Label static protected inherited
Referenced by childLabel().
const QVariant NidasItem::_SN_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Suffix_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Unknown_Label static protected inherited
Referenced by A2DSensorItem::childLabel().
const QVariant NidasItem::_Variable_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Volt_Label static protected inherited
Referenced by A2DSensorItem::childLabel().
QList<NidasItem*> NidasItem::childItems protected inherited
Referenced by A2DSensorItem::child(), NidasItem::childCount(), A2DSensorItem::refreshChildItems(), NidasItem::removeChildren(), and A2DSensorItem::updateDOMA2DTempSfx().
xercesc::DOMNode* NidasItem::domNode protected inherited
NidasModel* NidasItem::model protected inherited
Referenced by A2DSensorItem::child(), and A2DSensorItem::refreshChildItems().
NidasItem* NidasItem::parentItem protected inherited
int NidasItem::rowNumber protected inherited
Referenced by NidasItem::removeChildren().
The documentation for this class was generated from the following files:
nidas/apps/config/nidas_qmv/ProjectItem.h
nidas/apps/config/nidas_qmv/ProjectItem.cc