nidas: SensorItem Class Reference
SensorItem Class Reference
#include <SensorItem.h>
Public Member Functions
SensorItem (DSMSensor *sensor, int row, NidasModel *theModel, NidasItem *parent=0)
SensorItem (DSMAnalogSensor *sensor, int row, NidasModel *theModel, NidasItem *parent=0)
~SensorItem ()
NidasItem * child (int i)
return the ith child of this item.
void refreshChildItems ()
void fromDOM ()
Re-initialize the nidas model from the DOM element.
bool removeChild (NidasItem *item)
remove the sample item from this Sensor's Nidas and DOM trees
std::string devicename ()
const QVariant & childLabel (int column) const
int childColumnCount () const
QString dataField (int column)
xercesc::DOMNode * getDOMNode ()
QString getBaseName ()
QString getDevice ()
DSMSensor * getDSMSensor () const
xercesc::DOMNode * findSampleDOMNode (unsigned int sampleId)
find the DOM node for the given sample tag
virtual std::string getSerialNumberString ()
NidasItem * parent () const
int row () const
int childCount ()
bool removeChildren (int first, int last)
QModelIndex createIndex ()
NidasItem * getParentItem ()
Protected Member Functions
QString viewName ()
xercesc::DOMNode * findDOMNode ()
find the DOM node which defines this Sensor
virtual QString name ()
Protected Attributes
DSMSensor * _sensor
xercesc::DOMNode * domNode
QList< NidasItem * > childItems
NidasItem * parentItem
int rowNumber
NidasModel * model
Static Protected Attributes
static const QVariant _Project_Label
static const QVariant _Site_Label
static const QVariant _DSM_Label
static const QVariant _Device_Label
static const QVariant _SN_Label
static const QVariant _ID_Label
static const QVariant _Sensor_Label
static const QVariant _Sample_Label
static const QVariant _DevChan_Label
static const QVariant _Suffix_Label
static const QVariant _Rate_Label
static const QVariant _Volt_Label
static const QVariant _Variable_Label
static const QVariant _CalCoefSrc_Label
static const QVariant _CalCoef_Label
static const QVariant _CalDate_Label
static const QVariant _Name_Label
static const QVariant _Channel_Label
static const QVariant _Unknown_Label
Constructor & Destructor Documentation
SensorItem::SensorItem (DSMSensor * sensor, int row, NidasModel * theModel, NidasItem * parent = 0)
SensorItem::SensorItem (DSMAnalogSensor * sensor, int row, NidasModel * theModel, NidasItem * parent = 0)
SensorItem::~SensorItem ()
References NidasItem::removeChild().
Member Function Documentation
NidasItem * SensorItem::child (int i) virtual
return the ith child of this item.
The primary mechanism for building the NidasItem tree. When Qt asks the NidasModel for info, it calls child(). Subclasses reimplement to build items for each type of Nidas object based on the parent's unique child iterators.
N.B. there is a QObject::child(objName,inheritsClass,recursiveSearch) from Qt3. Watch out...
Reimplemented from NidasItem.
References nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::core::VariableIterator::hasNext(), and nidas::core::SampleTagIterator::next().
int SensorItem::childColumnCount () const inline virtual
Reimplemented from NidasItem.
int NidasItem::childCount () inherited
NidasItem is a proxy for the actual Nidas objects in the Project tree and their corresponding DOMNodes. Qt indexing is mapped to the Project tree via parent/child with row the ordinal number of the siblings and columns used for data fields (attributes/properties) of each level of Nidas object.
Pointers to Nidas objects are void* since Nidas uses different classes at every level. NidasItem is (should/will be) subclassed for specialized Items corresponding to each kind of Nidas object in the Project tree and implementing their own logic for the API used by NidasModel (like the data and header returned for Qt columns).
The NidasItem tree is a mirror/proxy of the Nidas object Project tree, with children lazily initialized by child(). Row number, parent pointer, and a list of children are cached.
N.B. can only add children to end of list due to Nidas API and use of children list in child()
NidasItem could also become a QObject to get the parent/children stuff. This could be useful in future for findChild()/findChildren(). Except for the fact that it didn't work - something about Qt's cleanup of children caused problems for us.
References NidasItem::child(), and NidasItem::childItems.
Referenced by Document::addA2DVariable(), Document::insertA2DVariable(), NidasModel::insertRows(), and NidasModel::rowCount().
const QVariant& SensorItem::childLabel (int column) const inline virtual
Reimplemented from NidasItem.
References NidasItem::_CalCoef_Label, NidasItem::_CalCoefSrc_Label, NidasItem::_CalDate_Label, NidasItem::_Rate_Label, NidasItem::_Sample_Label, and NidasItem::_Variable_Label.
QModelIndex NidasItem::createIndex () inline inherited
Asks the model to create an index for this item. Requires us to be a friend of NidasModel and for the model to ask NidasItem for the parent item.
Returns
a QModelIndex for this NidasItem
Referenced by Document::addA2DVariable(), NidasModel::appendChild(), NidasModel::removeChildren(), and NidasModel::removeIndexes().
QString SensorItem::dataField (int column) virtual
Reimplemented from NidasItem.
References DeviceValidator::getDevicePrefix(), and DeviceValidator::getInstance().
std::string SensorItem::devicename () inline
Referenced by DSMItem::removeChild().
DOMNode * SensorItem::findDOMNode () protected
find the DOM node which defines this Sensor
References nidas::core::XDOMElement::getAttributeValue(), and DSMItem::getDOMNode().
DOMNode * SensorItem::findSampleDOMNode (unsigned int sampleId)
find the DOM node for the given sample tag
Search through the Sensor DOM Node children looking for nodes with the name sample and for every one found, see if the id attribute of that node is equal to the sampleId passed in. Note that we search through all children of the sensor node because we want the last such node. Nidas allows multiple definitions, using the last one as the 'final' say so.
References nidas::core::XDOMElement::getAttributeValue().
Referenced by Document::insertA2DVariable(), A2DSensorItem::removeChild(), and Document::updateVariable().
void SensorItem::fromDOM ()
Re-initialize the nidas model from the DOM element.
Referenced by Document::updateSensor(), and Document::updateVariable().
QString SensorItem::getBaseName ()
Referenced by config::AddSensorComboDialog::existingSensor(), and Document::updateVariable().
QString SensorItem::getDevice () inline
Referenced by config::AddSensorComboDialog::existingSensor().
xercesc::DOMNode* SensorItem::getDOMNode () inline
Referenced by Document::addA2DVariable(), A2DVariableItem::findSampleDOMNode(), VariableItem::findSampleDOMNode(), A2DSensorItem::removeChild(), A2DSensorItem::updateDOMCalFile(), PMSSensorItem::updateDOMPMSParams(), Document::updateSensorDOM(), and Document::updateVariable().
DSMSensor* SensorItem::getDSMSensor () const inline
Referenced by Document::addA2DVariable(), config::AddSensorComboDialog::existingSensor(), Document::getAvailableA2DChannels(), VariableItem::getBaseName(), A2DSensorItem::removeChild(), Document::updateSensor(), and Document::updateVariable().
NidasItem* NidasItem::getParentItem () inline inherited
virtual std::string SensorItem::getSerialNumberString () inline virtual
Reimplemented in A2DSensorItem, and PMSSensorItem.
Referenced by config::AddSensorComboDialog::existingSensor().
virtual QString NidasItem::name () inline protected virtual inherited
Reimplemented in DSMItem, SiteItem, ProjectItem, A2DVariableItem, and VariableItem.
Referenced by A2DSensorItem::removeChild().
NidasItem* NidasItem::parent () const inline inherited
Referenced by NidasModel::parent(), and NidasModel::removeIndexes().
void SensorItem::refreshChildItems ()
References nidas::core::SampleTag::getVariableIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::core::VariableIterator::hasNext(), and nidas::core::SampleTagIterator::next().
bool SensorItem::removeChild (NidasItem * item) virtual
remove the sample item from this Sensor's Nidas and DOM trees
current implementation confused between returning bool and throwing exceptions due to refactoring from Document
Reimplemented from NidasItem.
References nidas::core::XDOMElement::getAttributeValue(), nidas::core::Variable::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::SampleTag::getSampleId(), VariableItem::getSampleTag(), nidas::core::DSMSensor::getSampleTags(), nidas::core::SampleTag::getVariableIterator(), nidas::core::VariableIterator::hasNext(), VariableItem::name(), nidas::core::DSMSensor::removeSampleTag(), nidas::core::SampleTag::removeVariable(), and VariableItem::sSampleId().
bool NidasItem::removeChildren (int first, int last) inherited
References NidasItem::childItems, and NidasItem::rowNumber.
Referenced by NidasModel::removeRows().
int NidasItem::row () const inline inherited
Referenced by NidasModel::parent(), and NidasModel::removeIndexes().
QString SensorItem::viewName () protected
Member Data Documentation
const QVariant NidasItem::_CalCoef_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and childLabel().
const QVariant NidasItem::_CalCoefSrc_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and childLabel().
const QVariant NidasItem::_CalDate_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and childLabel().
const QVariant NidasItem::_Channel_Label static protected inherited
Referenced by A2DSensorItem::childLabel().
const QVariant NidasItem::_DevChan_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Device_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_DSM_Label static protected inherited
Referenced by SiteItem::childLabel().
const QVariant NidasItem::_ID_Label static protected inherited
Referenced by SiteItem::childLabel(), and DSMItem::childLabel().
const QVariant NidasItem::_Name_Label static protected inherited
Referenced by VariableItem::childLabel(), SiteItem::childLabel(), A2DVariableItem::childLabel(), and DSMItem::childLabel().
const QVariant NidasItem::_Project_Label static protected inherited
const QVariant NidasItem::_Rate_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and childLabel().
const QVariant NidasItem::_Sample_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and childLabel().
DSMSensor* SensorItem::_sensor protected
Referenced by A2DSensorItem::child(), A2DSensorItem::getA2DTempSuffix(), A2DSensorItem::getCalFileName(), PMSSensorItem::getSerialNumberString(), A2DSensorItem::getSerialNumberString(), A2DSensorItem::refreshChildItems(), and A2DSensorItem::setNidasA2DTempSuffix().
const QVariant NidasItem::_Sensor_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Site_Label static protected inherited
Referenced by ProjectItem::childLabel().
const QVariant NidasItem::_SN_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Suffix_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Unknown_Label static protected inherited
Referenced by A2DSensorItem::childLabel().
const QVariant NidasItem::_Variable_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and childLabel().
const QVariant NidasItem::_Volt_Label static protected inherited
Referenced by A2DSensorItem::childLabel().
QList<NidasItem*> NidasItem::childItems protected inherited
Referenced by A2DSensorItem::child(), NidasItem::childCount(), A2DSensorItem::refreshChildItems(), NidasItem::removeChildren(), and A2DSensorItem::updateDOMA2DTempSfx().
xercesc::DOMNode* NidasItem::domNode protected inherited
NidasModel* NidasItem::model protected inherited
Referenced by A2DSensorItem::child(), and A2DSensorItem::refreshChildItems().
NidasItem* NidasItem::parentItem protected inherited
int NidasItem::rowNumber protected inherited
Referenced by NidasItem::removeChildren().
The documentation for this class was generated from the following files:
nidas/apps/config/nidas_qmv/SensorItem.h
nidas/apps/config/nidas_qmv/SensorItem.cc