nidas: nidas::core::VariableConverter Class Reference
nidas::core::VariableConverter Class Reference abstract
#include <VariableConverter.h>
Public Member Functions
VariableConverter ()
VariableConverter (const VariableConverter &x)
Copy constructor.
VariableConverter & operator= (const VariableConverter &x)
Assignment.
virtual ~VariableConverter ()
virtual VariableConverter * clone () const =0
virtual void setCalFile (CalFile *)=0
virtual CalFile * getCalFile ()=0
virtual const CalFile * getCalFile () const =0
virtual void readCalFile (dsm_time_t) throw ()
virtual double convert (dsm_time_t, double v)=0
void setUnits (const std::string &val)
virtual const std::string & getUnits () const
void setVariable (const Variable *val)
const Variable * getVariable () const
const DSMSensor * getDSMSensor () const
const DSMConfig * getDSMConfig () const
virtual std::string toString () const =0
Generate a string description of this VariableConverter.
virtual void fromString (const std::string &) throw (nidas::util::InvalidParameterException)
void addParameter (Parameter *val)
Add a parameter to this VariableConverter.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static VariableConverter * createVariableConverter (XDOMElement &child)
static VariableConverter * createFromString (const std::string &) throw (nidas::util::InvalidParameterException)
static const XMLCh * getNamespaceURI ()
Private Attributes
std::string _units
std::map< std::string,
Parameter * > _parameters
Map of parameters by name.
std::list< const Parameter * > _constParameters
List of const pointers to Parameters for providing via getParameters().
const Variable * _variable
Constructor & Destructor Documentation
VariableConverter::VariableConverter ()
VariableConverter::VariableConverter (const VariableConverter & x)
Copy constructor.
References addParameter(), nidas::core::Parameter::clone(), and getParameters().
virtual nidas::core::VariableConverter::~VariableConverter () inline virtual
Member Function Documentation
void VariableConverter::addParameter (Parameter * val)
Add a parameter to this VariableConverter.
VariableConverter will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References _constParameters, _parameters, and nidas::core::Parameter::getName().
Referenced by operator=(), and VariableConverter().
virtual VariableConverter* nidas::core::VariableConverter::clone () const pure virtual
Implemented in nidas::core::Polynomial, nidas::core::Linear, nidas::dynld::isff::CS_Krypton, and nidas::dynld::isff::RebsLinear.
Referenced by nidas::core::Variable::operator=(), and nidas::core::Variable::Variable().
virtual double nidas::core::VariableConverter::convert (dsm_time_t , double v) pure virtual
Implemented in nidas::core::Polynomial, nidas::core::Linear, and nidas::dynld::isff::CS_Krypton.
Referenced by nidas::dynld::isff::WisardMote::convert(), nidas::dynld::isff::CSI_IRGA_Sonic::process(), nidas::dynld::IEEE_Float::process(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::isff::CSAT3_Sonic::process(), nidas::dynld::A2DSensor::process(), nidas::dynld::raf::DSMAnalogSensor::process(), nidas::core::CharacterSensor::process(), and nidas::dynld::isff::WisardMote::unpackTsoil().
VariableConverter * VariableConverter::createFromString (const std::string & str) throw (nidas::util::InvalidParameterException) static
References fromString().
VariableConverter * VariableConverter::createVariableConverter (XDOMElement & child) static
References nidas::core::DOMObjectFactory::createObject(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::XDOMElement::getNodeName(), and nidas::util::Exception::what().
Referenced by nidas::core::Variable::fromDOMElement().
void VariableConverter::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
Reimplemented in nidas::core::Polynomial, nidas::core::Linear, and nidas::dynld::isff::CS_Krypton.
References nidas::core::Parameter::createParameter(), nidas::core::CalFile::fromDOMElement(), nidas::core::XDOMElement::getNodeName(), and nidas::core::CalFile::setDSMSensor().
Referenced by nidas::dynld::isff::CS_Krypton::fromDOMElement(), nidas::core::Linear::fromDOMElement(), nidas::core::Polynomial::fromDOMElement(), and nidas::core::Variable::fromDOMElement().
virtual void nidas::core::VariableConverter::fromString (const std::string &) throw (nidas::util::InvalidParameterException) inline virtual
Reimplemented in nidas::core::Polynomial, nidas::core::Linear, and nidas::dynld::isff::CS_Krypton.
Referenced by createFromString().
virtual CalFile* nidas::core::VariableConverter::getCalFile () pure virtual
Implemented in nidas::core::Polynomial, nidas::core::Linear, and nidas::dynld::isff::CS_Krypton.
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), A2DVariableItem::dataField(), nidas::core::SampleTag::fromDOMElement(), A2DVariableItem::getCalibrationInfo(), PConfig::showCalFiles(), and VariableItem::VariableItem().
virtual const CalFile* nidas::core::VariableConverter::getCalFile () const pure virtual
Implemented in nidas::core::Polynomial, nidas::core::Linear, and nidas::dynld::isff::CS_Krypton.
const DSMConfig * VariableConverter::getDSMConfig () const
References nidas::core::DSMSensor::getDSMConfig(), and getDSMSensor().
const DSMSensor * VariableConverter::getDSMSensor () const
References nidas::core::SampleTag::getDSMSensor(), nidas::core::Variable::getSampleTag(), and getVariable().
Referenced by getDSMConfig().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
const Parameter * VariableConverter::getParameter (const std::string & name) const
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References _parameters.
const std::list<const Parameter*>& nidas::core::VariableConverter::getParameters () const inline
Get list of parameters.
References _constParameters.
Referenced by operator=(), and VariableConverter().
virtual const std::string& nidas::core::VariableConverter::getUnits () const inline virtual
References _units.
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), nidas::dynld::isff::CS_Krypton::CS_Krypton(), A2DVariableItem::dataField(), VariableItem::getCalibrationInfo(), DumpClient::printHeader(), nidas::core::Variable::toDOMElement(), nidas::core::Linear::toString(), and nidas::core::Polynomial::toString().
const Variable* nidas::core::VariableConverter::getVariable () const inline
References _variable.
Referenced by getDSMSensor().
VariableConverter & VariableConverter::operator= (const VariableConverter & x)
Assignment.
References _units, _variable, addParameter(), nidas::core::Parameter::clone(), and getParameters().
virtual void nidas::core::VariableConverter::readCalFile (dsm_time_t) throw () inline virtual
Reimplemented in nidas::core::Polynomial, nidas::core::Linear, and nidas::dynld::isff::CS_Krypton.
Referenced by nidas::dynld::raf::SyncRecordSource::preLoadCalibrations().
virtual void nidas::core::VariableConverter::setCalFile (CalFile *) pure virtual
Implemented in nidas::core::Polynomial, nidas::core::Linear, and nidas::dynld::isff::CS_Krypton.
void nidas::core::VariableConverter::setUnits (const std::string & val) inline
References _units.
Referenced by nidas::dynld::isff::CS_Krypton::CS_Krypton(), nidas::core::Variable::fromDOMElement(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
void nidas::core::VariableConverter::setVariable (const Variable * val) inline
References _variable.
Referenced by nidas::core::Variable::fromDOMElement().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
virtual std::string nidas::core::VariableConverter::toString () const pure virtual
Generate a string description of this VariableConverter.
May be used in meta-data, for example Netcdf comment.
Implemented in nidas::core::Polynomial, nidas::core::Linear, and nidas::dynld::isff::CS_Krypton.
Referenced by A2DVariableItem::dataField(), and A2DVariableItem::getCalibrationInfo().
Member Data Documentation
std::list<const Parameter*> nidas::core::VariableConverter::_constParameters private
List of const pointers to Parameters for providing via getParameters().
Referenced by addParameter(), and getParameters().
std::map<std::string,Parameter*> nidas::core::VariableConverter::_parameters private
Map of parameters by name.
Referenced by addParameter(), and getParameter().
std::string nidas::core::VariableConverter::_units private
Referenced by getUnits(), operator=(), and setUnits().
const Variable* nidas::core::VariableConverter::_variable private
Referenced by getVariable(), operator=(), and setVariable().
The documentation for this class was generated from the following files:
nidas/core/VariableConverter.h
nidas/core/VariableConverter.cc