nidas: nidas::dynld::FileSet Class Reference
nidas::dynld::FileSet Class Reference
Dynamically loadable nidas::core::FileSet.
#include <FileSet.h>
Public Member Functions
int getReconnectDelaySecs () const
bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
const std::string & getName () const
void setDir (const std::string &val)
Set the directory portion of the file search path.
void setFileName (const std::string &val)
Set the file portion of the file search path.
void requestConnection (IOChannelRequester *requester) throw (nidas::util::IOException)
After the IOChannel is configured, a user of IOChannel calls requestConnection to get things started.
IOChannel * connect () throw (nidas::util::IOException)
Establish a connection.
void setNonBlocking (bool val) throw (nidas::util::IOException)
bool isNonBlocking () const throw (nidas::util::IOException)
void setMount (FsMount *val)
FileSet will own the FsMount.
void mounted ()
This method is called by FsMount when it is done.
FileSet * clone () const
Clone myself.
dsm_time_t createFile (dsm_time_t t, bool exact) throw (nidas::util::IOException)
Request that an IOChannel open a new file, with a name based on a time.
size_t read (void *buf, size_t len) throw (nidas::util::IOException)
Physical read method which must be implemented in derived classes.
size_t write (const void *buf, size_t len) throw (nidas::util::IOException)
Physical write method which must be implemented in derived classes.
size_t write (const struct iovec *iov, int iovcnt) throw (nidas::util::IOException)
Physical write method which must be implemented in derived classes.
void close () throw (nidas::util::IOException)
int getFd () const
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
const std::string & getCurrentName () const
Get name of current file.
void setStartTime (const nidas::util::UTime &val)
nidas::util::UTime getStartTime () const
void setEndTime (const nidas::util::UTime &val)
nidas::util::UTime getEndTime () const
void setFileLengthSecs (int val)
Set/get the file length in seconds.
int getFileLengthSecs () const
void addFileName (const std::string &val)
long long getFileSize () const throw (nidas::util::IOException)
int getLastErrno () const
Get last error value.
virtual void setRequestType (enum McSocketRequest)
virtual enum McSocketRequest getRequestType () const
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual size_t getBufferSize () const throw ()
Return suggested buffer length.
virtual void flush () throw (nidas::util::IOException)
Default flush implementation does nothing.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static FileSet * getFileSet (const std::list< std::string > &filenames) throw (nidas::util::InvalidParameterException)
Convienence function to return a pointer to a nidas::core::FileSet, given a list of files.
static IOChannel * createIOChannel (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void setName (const std::string &val)
Recognizeable name of this IOChannel - used for informative messages.
Protected Attributes
nidas::util::FileSet * _fset
std::string _name
IOChannelRequester * _requester
FsMount * _mount
Detailed Description
Dynamically loadable nidas::core::FileSet.
Member Function Documentation
void nidas::core::FileSet::addFileName (const std::string & val) inline inherited
References nidas::core::FileSet::_fset, and nidas::util::FileSet::addFileName().
Referenced by nidas::core::FileSet::getFileSet(), PacketDecode::run(), and MergeVerifier::run().
FileSet* nidas::core::FileSet::clone () const inline virtual inherited
Clone myself.
Implements nidas::core::IOChannel.
References nidas::core::FileSet::FileSet().
Referenced by StatsProcess::run(), and DataPrep::run().
void FileSet::close () throw (nidas::util::IOException) virtual inherited
Implements nidas::core::IOChannel.
References nidas::core::FileSet::_fset, nidas::core::FileSet::_mount, nidas::core::FsMount::cancel(), nidas::util::FileSet::closeFile(), and nidas::core::FsMount::unmount().
IOChannel * FileSet::connect () throw (nidas::util::IOException) virtual inherited
Establish a connection.
On return, the connection has been established. It may return a new instance of an IOChannel.
Implements nidas::core::IOChannel.
References nidas::core::FileSet::_mount, and nidas::core::FsMount::mount().
Referenced by nidas::dynld::raf::SyncServer::openStream(), DataStats::run(), DataDump::run(), and Calibrator::setup().
dsm_time_t FileSet::createFile (dsm_time_t t, bool exact) throw (nidas::util::IOException) virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Reimplemented from nidas::core::IOChannel.
References nidas::util::UTime::toUsecs().
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) throw (nidas::util::InvalidParameterException) static inherited
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
virtual void nidas::core::IOChannel::flush () throw (nidas::util::IOException) inline virtual inherited
Default flush implementation does nothing.
Reimplemented in nidas::dynld::isff::GOESXmtr, nidas::dynld::isff::SE_GOESXmtr, and nidas::dynld::psql::PSQLChannel.
Referenced by nidas::core::SampleArchiver::disconnect(), and nidas::core::IOStream::flush().
void FileSet::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual inherited
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
References nidas::core::XDOMAttr::getName(), and nidas::core::XDOMElement::getNodeName().
virtual size_t nidas::core::IOChannel::getBufferSize () const throw () inline virtual inherited
Return suggested buffer length.
Reimplemented in nidas::core::Socket, nidas::core::DatagramSocket, and nidas::core::MultipleUDPSockets.
Referenced by nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::isff::PacketInputStream::PacketInputStream(), and nidas::dynld::SampleInputStream::SampleInputStream().
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
const std::string& nidas::core::FileSet::getCurrentName () const inline inherited
Get name of current file.
References nidas::core::FileSet::_fset, and nidas::util::FileSet::getCurrentName().
Referenced by nidas::core::GetAdsFileName::execute(), nidas::core::FileSet::getName(), and nidas::core::SampleArchiver::printStatus().
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
nidas::util::UTime nidas::core::FileSet::getEndTime () const inline inherited
References nidas::core::FileSet::_fset, and nidas::util::FileSet::getStartTime().
int nidas::core::FileSet::getFd () const inline virtual inherited
Implements nidas::core::IOChannel.
References nidas::core::FileSet::_fset, and nidas::util::FileSet::getFd().
int nidas::core::FileSet::getFileLengthSecs () const inline inherited
References nidas::core::FileSet::_fset, and nidas::util::FileSet::getFileLengthSecs().
FileSet * FileSet::getFileSet (const std::list< std::string > & filenames) throw (nidas::util::InvalidParameterException) static inherited
Convienence function to return a pointer to a nidas::core::FileSet, given a list of files.
If one or more of the files have a .bz2 suffix, the FileSet returned will be a nidas::core::Bzip2FileSet. Note that a Bzip2FileSet cannot be used to read a non-compressed file, so one should not mix compressed and non-compressed files in the list.
References nidas::core::FileSet::addFileName().
Referenced by nidas::dynld::raf::SyncServer::openStream(), NidsMerge::run(), MergeVerifier::run(), StatsProcess::run(), SensorExtract::run(), SyncDumper::run(), DataPrep::run(), Extract2D::run(), DataStats::run(), DataDump::run(), and Calibrator::setup().
long long nidas::core::FileSet::getFileSize () const throw (nidas::util::IOException) inline inherited
References nidas::core::FileSet::_fset, and nidas::util::FileSet::getFileSize().
Referenced by nidas::core::SampleArchiver::printStatus().
int nidas::core::FileSet::getLastErrno () const inline inherited
Get last error value.
Should be 0. Currently only supported for an output file, to be queried by a system status thread.
References nidas::core::FileSet::_fset, and nidas::util::FileSet::getLastErrno().
const std::string & FileSet::getName () const virtual inherited
Implements nidas::core::IOChannel.
References nidas::core::FileSet::_name, and nidas::core::FileSet::getCurrentName().
Referenced by NidsMerge::run(), MergeVerifier::run(), nidas::core::FileSet::setNonBlocking(), and nidas::core::FileSet::write().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
int nidas::core::FileSet::getReconnectDelaySecs () const inline virtual inherited
Reimplemented from nidas::core::IOChannel.
virtual enum McSocketRequest nidas::core::IOChannel::getRequestType () const inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
nidas::util::UTime nidas::core::FileSet::getStartTime () const inline inherited
References nidas::core::FileSet::_fset, and nidas::util::FileSet::getStartTime().
bool nidas::core::FileSet::isNewInput () const inline virtual inherited
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented from nidas::core::IOChannel.
References nidas::core::FileSet::_fset, and nidas::util::FileSet::isNewFile().
bool nidas::core::FileSet::isNonBlocking () const throw (nidas::util::IOException) inline virtual inherited
Implements nidas::core::IOChannel.
void FileSet::mounted () inherited
This method is called by FsMount when it is done.
References nidas::core::FileSet::_mount, nidas::core::FileSet::_requester, nidas::core::IOChannelRequester::connected(), and nidas::core::FsMount::isMounted().
Referenced by nidas::core::FsMount::finished().
size_t nidas::core::FileSet::read (void * buf, size_t len) throw (nidas::util::IOException) inline virtual inherited
Physical read method which must be implemented in derived classes.
Returns the number of bytes written, which may be less than the number requested.
Implements nidas::core::IOChannel.
References nidas::core::FileSet::_fset, len, and nidas::util::FileSet::read().
void FileSet::requestConnection (IOChannelRequester *) throw (nidas::util::IOException) virtual inherited
After the IOChannel is configured, a user of IOChannel calls requestConnection to get things started.
It is like opening a device, but in the case of server sockets, it just starts a thread to wait on connections. Only when the IOChannelRequester::connected() method is called back is the channel actually open and ready for IO. The IOChannel* returned by IOChannelRequester::connected may be another instance of an IOChannel.
Implements nidas::core::IOChannel.
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
Referenced by nidas::core::MultipleUDPSockets::connect(), nidas::core::Socket::connect(), nidas::core::McSocket::connect(), nidas::core::McSocketUDP::connect(), nidas::core::McSocket::connected(), and nidas::core::McSocketUDP::connected().
void FileSet::setDir (const std::string & val) inherited
Set the directory portion of the file search path.
This may contain environment variables, and tokens like $DSM, $SITE, $AIRCRAFT.
References nidas::core::FileSet::_fset, nidas::core::IOChannel::getDSMConfig(), nidas::core::Project::getInstance(), nidas::util::FileSet::getPath(), nidas::util::FileSet::setDir(), and nidas::core::FileSet::setName().
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
void nidas::core::FileSet::setEndTime (const nidas::util::UTime & val) inline inherited
References nidas::core::FileSet::_fset, and nidas::util::FileSet::setEndTime().
Referenced by NidsMerge::run(), MergeVerifier::run(), StatsProcess::run(), and DataPrep::run().
void nidas::core::FileSet::setFileLengthSecs (int val) inline inherited
Set/get the file length in seconds.
References nidas::core::FileSet::_fset, and nidas::util::FileSet::setFileLengthSecs().
Referenced by NidsMerge::run(), SensorExtract::run(), and ARLIngest::run().
void FileSet::setFileName (const std::string & val) inherited
Set the file portion of the file search path.
This may contain environment variables, and tokens like $DSM, $SITE, $AIRCRAFT.
References nidas::core::FileSet::_fset, nidas::core::IOChannel::getDSMConfig(), nidas::core::Project::getInstance(), nidas::util::FileSet::getPath(), nidas::util::FileSet::setFileName(), and nidas::core::FileSet::setName().
Referenced by NidsMerge::run(), MergeVerifier::run(), SensorExtract::run(), and ARLIngest::run().
void nidas::core::FileSet::setMount (FsMount * val) inline inherited
FileSet will own the FsMount.
References nidas::core::FileSet::_mount.
void FileSet::setName (const std::string & val) protected virtual inherited
Recognizeable name of this IOChannel - used for informative messages.
Implements nidas::core::IOChannel.
References nidas::core::FileSet::_name.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
void nidas::core::FileSet::setNonBlocking (bool val) throw (nidas::util::IOException) inline virtual inherited
Implements nidas::core::IOChannel.
References nidas::core::FileSet::getName(), and PLOG.
virtual void nidas::core::IOChannel::setRequestType (enum McSocketRequest) inline virtual inherited
Reimplemented in nidas::core::Socket, nidas::core::McSocketUDP, and nidas::core::McSocket.
Referenced by nidas::dynld::XMLConfigService::schedule().
void nidas::core::FileSet::setStartTime (const nidas::util::UTime & val) inline inherited
References nidas::core::FileSet::_fset, and nidas::util::FileSet::setStartTime().
Referenced by NidsMerge::run(), MergeVerifier::run(), StatsProcess::run(), and DataPrep::run().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
size_t nidas::core::FileSet::write (const void * buf, size_t len) throw (nidas::util::IOException) inline virtual inherited
Physical write method which must be implemented in derived classes.
Returns the number of bytes written, which may be less than the number requested.
Implements nidas::core::IOChannel.
References nidas::core::FileSet::_fset, nidas::core::FileSet::getName(), len, and nidas::util::FileSet::write().
size_t nidas::core::FileSet::write (const struct iovec * iov, int iovcnt) throw (nidas::util::IOException) inline virtual inherited
Physical write method which must be implemented in derived classes.
Returns the number of bytes written, which may be less than the number requested.
Implements nidas::core::IOChannel.
References nidas::core::FileSet::_fset, and nidas::util::FileSet::write().
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
nidas::util::FileSet* nidas::core::FileSet::_fset protected inherited
Referenced by nidas::core::FileSet::addFileName(), nidas::core::FileSet::close(), nidas::core::FileSet::getCurrentName(), nidas::core::FileSet::getEndTime(), nidas::core::FileSet::getFd(), nidas::core::FileSet::getFileLengthSecs(), nidas::core::FileSet::getFileSize(), nidas::core::FileSet::getLastErrno(), nidas::core::FileSet::getStartTime(), nidas::core::FileSet::isNewInput(), nidas::core::FileSet::read(), nidas::core::FileSet::setDir(), nidas::core::FileSet::setEndTime(), nidas::core::FileSet::setFileLengthSecs(), nidas::core::FileSet::setFileName(), nidas::core::FileSet::setStartTime(), nidas::core::FileSet::write(), and nidas::core::FileSet::~FileSet().
FsMount* nidas::core::FileSet::_mount protected inherited
Referenced by nidas::core::FileSet::close(), nidas::core::FileSet::connect(), nidas::core::FileSet::FileSet(), nidas::core::FileSet::mounted(), nidas::core::FileSet::setMount(), and nidas::core::FileSet::~FileSet().
std::string nidas::core::FileSet::_name protected inherited
Referenced by nidas::core::FileSet::getName(), and nidas::core::FileSet::setName().
IOChannelRequester* nidas::core::FileSet::_requester protected inherited
Referenced by nidas::core::FileSet::mounted().
The documentation for this class was generated from the following file:
nidas/dynld/FileSet.h