nidas: nidas::dynld::raf::CVIProcessor Class Reference
nidas::dynld::raf::CVIProcessor Class Reference
Processor to support Counter-flow Virtual Impactor.
#include <CVIProcessor.h>
Public Member Functions
CVIProcessor ()
~CVIProcessor ()
void flush () throw ()
Implementation of SampleSource and SampleClient flush().
void addRequestedSampleTag (SampleTag *tag) throw (nidas::util::InvalidParameterException)
Add a request for a SampleTag from this SampleIOProcessor.
void connect (SampleSource *) throw (nidas::util::InvalidParameterException,nidas::util::IOException)
Do common operations necessary when a input has connected:
void disconnect (SampleSource *) throw ()
Disconnect a SampleSource from this CVIProcessor.
void connect (SampleOutput *output) throw ()
Do common operations necessary when a output has connected:
void disconnect (SampleOutput *output) throw ()
Do common operations necessary when a output has disconnected:
void setD2ADeviceName (const std::string &val)
const std::string & getD2ADeviceName () const
void setDigIODeviceName (const std::string &val)
const std::string & getDigIODeviceName ()
bool receive (const Sample *s) throw ()
The CVIProcessor receive method is configured to received the processed samples from CVI_LV_Input.
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual const std::string & getName () const
virtual void setName (const std::string &val)
virtual void setOptional (bool val)
virtual bool isOptional () const
virtual const DSMService * getService () const
What DSMService am I associated with?
virtual void setService (const DSMService *val)
virtual const DSMConfig * getDSMConfig () const
What DSM am I associated with?
virtual void setDSMConfig (const DSMConfig *val)
dsm_sample_id_t getId () const
void setSampleId (int val)
unsigned int getSampleId () const
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual std::list< const
SampleTag * > getRequestedSampleTags () const
void addSampleTag (const SampleTag *tag) throw ()
Implementation of SampleSource::addSampleTag().
void removeSampleTag (const SampleTag *tag) throw ()
std::list< const SampleTag * > getSampleTags () const
Implementation of SampleSource::getSampleTags().
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
const SampleStats & getSampleStats () const
virtual void addOutput (SampleOutput *val)
Add an SampleOutput to this SampleIOProcessor.
virtual const std::list
< SampleOutput * > & getOutputs () const
void addParameter (Parameter *val) throw (nidas::util::InvalidParameterException)
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
virtual void printStatus (std::ostream &, float, int &) throw ()
virtual void init (dsm_time_t) throw ()
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void attachLVInput (SampleSource *src, const SampleTag *tag) throw (nidas::util::IOException)
void removeRequestedSampleTag (SampleTag *tag)
Allow subclasses to remove requested SampleTags.
Protected Attributes
SampleSourceSupport _source
nidas::util::Mutex _tagsMutex
std::list< SampleTag * > _requestedTags
Private Member Functions
CVIProcessor (const CVIProcessor &)
Copy not supported.
CVIProcessor & operator= (const CVIProcessor &)
Assignment not supported.
Private Attributes
nidas::util::Mutex _connectionMutex
std::set< SampleSource * > _connectedSources
std::set< SampleOutput * > _connectedOutputs
SampleTag * _outputSampleTag
std::string _d2aDeviceName
std::string _digioDeviceName
std::vector< bool > _varMatched
SampleAverager _averager
float _rate
dsm_sample_id_t _lvSampleId
DSC_AnalogOut _aout
ViperDIO _dout
unsigned int _numD2A
unsigned int _numDigout
float _vouts [5]
int _douts [4]
const Site * _site
Detailed Description
Processor to support Counter-flow Virtual Impactor.
Constructor & Destructor Documentation
CVIProcessor::CVIProcessor ()
CVIProcessor::~CVIProcessor ()
References nidas::core::SampleOutput::close(), nidas::core::SampleClient::flush(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getName(), nidas::core::SampleOutput::getOriginal(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
nidas::dynld::raf::CVIProcessor::CVIProcessor (const CVIProcessor &) private
Copy not supported.
Member Function Documentation
virtual void nidas::core::SampleIOProcessor::addOutput (SampleOutput * val) inline virtual inherited
Add an SampleOutput to this SampleIOProcessor.
This is used to add a desired SampleOutput to this SampleIOProcessor. SampleIOProcessor will own the SampleOutput. Once a SampleSource has connected, then SampleIOProcessor is responsible for do SampleOutput::requestConnection, or SampleOutputRequestThread::addConnectRequest() on all these as-yet disconnected outputs.
References nidas::core::SampleIOProcessor::_origOutputs.
void SampleIOProcessor::addParameter (Parameter * val) throw (nidas::util::InvalidParameterException) inherited
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
If a Parameter exists with the same name, it will be replaced with the new Parameter.
void CVIProcessor::addRequestedSampleTag (SampleTag * tag) throw (nidas::util::InvalidParameterException) virtual
Add a request for a SampleTag from this SampleIOProcessor.
This SampleIOProcessor will own the SampleTag.
Reimplemented from nidas::core::SampleIOProcessor.
References nidas::core::SampleIOProcessor::addRequestedSampleTag(), nidas::core::DSMConfig::getSite(), and nidas::core::Variable::setSite().
void nidas::core::SampleIOProcessor::addSampleClient (SampleClient * client) throw () inline virtual inherited
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::addSampleClient().
void nidas::core::SampleIOProcessor::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
void SampleIOProcessor::addSampleTag (const SampleTag * tag) throw () virtual inherited
Implementation of SampleSource::addSampleTag().
Implements nidas::core::SampleSource.
void CVIProcessor::attachLVInput (SampleSource * src, const SampleTag * tag) throw (nidas::util::IOException) protected
void CVIProcessor::connect (SampleSource * source) throw (nidas::util::InvalidParameterException, nidas::util::IOException) virtual
Do common operations necessary when a input has connected:
Copy the DSMConfig information from the input to the disconnected outputs.
Request connections for all disconnected outputs.
connect() methods in subclasses should do whatever initialization necessary before invoking this CVIProcessor::connect().
Implements nidas::core::SampleIOProcessor.
References nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutput::addSourceSampleTags(), nidas::core::Project::findSensor(), GET_DSM_ID, GET_SHORT_ID, nidas::core::SampleTag::getId(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::core::Project::getInstance(), nidas::core::DSMSensor::getName(), nidas::core::SampleTag::getSampleId(), nidas::core::SampleTagIterator::hasNext(), and nidas::core::SampleTagIterator::next().
void CVIProcessor::connect (SampleOutput * output) throw () virtual
Do common operations necessary when a output has connected:
do: output->init().
add output to a list of connected outputs.
Implements nidas::core::SampleConnectionRequester.
References ILOG.
void CVIProcessor::disconnect (SampleSource * source) throw () virtual
Disconnect a SampleSource from this CVIProcessor.
Calls flush() on the averager and closes the digital and analog outputs.
Implements nidas::core::SampleIOProcessor.
void CVIProcessor::disconnect (SampleOutput * output) throw () virtual
Do common operations necessary when a output has disconnected:
do: output->close().
remove output from a list of connected outputs.
Implements nidas::core::SampleConnectionRequester.
References nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutputRequestThread::addDeleteRequest(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getOriginal(), nidas::core::SampleOutput::getReconnectDelaySecs(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
void CVIProcessor::flush () throw () virtual
Implementation of SampleSource and SampleClient flush().
Implements nidas::core::SampleClient.
References nidas::core::SampleClient::flush().
void CVIProcessor::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Reimplemented from nidas::core::SampleIOProcessor.
References nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::Parameter::getLength(), nidas::core::Parameter::getName(), nidas::core::SampleIOProcessor::getName(), and nidas::core::Parameter::getStringValue().
int nidas::core::SampleIOProcessor::getClientCount () const throw () inline virtual inherited
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getClientCount().
const std::string& nidas::dynld::raf::CVIProcessor::getD2ADeviceName () const inline
const std::string& nidas::dynld::raf::CVIProcessor::getDigIODeviceName () inline
virtual const DSMConfig* nidas::core::SampleIOProcessor::getDSMConfig () const inline virtual inherited
What DSM am I associated with?
References nidas::core::SampleIOProcessor::_dsm.
dsm_sample_id_t nidas::core::SampleIOProcessor::getId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_FULL_ID.
const std::string & SampleIOProcessor::getName () const virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by fromDOMElement(), nidas::dynld::RawSampleService::schedule(), and nidas::dynld::StatisticsProcessor::~StatisticsProcessor().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
virtual const std::list<SampleOutput*>& nidas::core::SampleIOProcessor::getOutputs () const inline virtual inherited
References nidas::core::SampleIOProcessor::_origOutputs.
Referenced by nidas::core::Project::findServerSampleOutputStreamFileSets(), nidas::dynld::isff::GOESProject::GOESProject(), and StatsProcess::run().
const std::list<const Parameter*>& nidas::core::SampleIOProcessor::getParameters () const inline inherited
Get list of parameters.
References nidas::core::SampleIOProcessor::_constParameters.
SampleSource* nidas::core::SampleIOProcessor::getProcessedSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References nidas::core::SampleIOProcessor::_source.
SampleSource* nidas::core::SampleIOProcessor::getRawSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
std::list< const SampleTag * > SampleIOProcessor::getRequestedSampleTags () const virtual inherited
References nidas::core::SampleIOProcessor::_constRequestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::core::SampleTagIterator::hasNext(), and StatsProcess::listOutputSamples().
unsigned int nidas::core::SampleIOProcessor::getSampleId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_SPS_ID.
Referenced by StatsProcess::listOutputSamples(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
const SampleStats& nidas::core::SampleIOProcessor::getSampleStats () const inline virtual inherited
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleStats().
SampleTagIterator nidas::core::SampleIOProcessor::getSampleTagIterator () const inline virtual inherited
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleTagIterator().
std::list<const SampleTag*> nidas::core::SampleIOProcessor::getSampleTags () const inline virtual inherited
Implementation of SampleSource::getSampleTags().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::psql::PSQLProcessor.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleTags().
virtual const DSMService* nidas::core::SampleIOProcessor::getService () const inline virtual inherited
What DSMService am I associated with?
References nidas::core::SampleIOProcessor::_service.
virtual void nidas::core::SampleIOProcessor::init (dsm_time_t) throw () inline virtual inherited
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
Referenced by nidas::dynld::RawSampleService::schedule().
virtual bool nidas::core::SampleIOProcessor::isOptional () const inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
Referenced by nidas::dynld::RawSampleService::schedule().
CVIProcessor& nidas::dynld::raf::CVIProcessor::operator= (const CVIProcessor &) private
Assignment not supported.
virtual void nidas::core::SampleIOProcessor::printStatus (std::ostream & , float , int &) throw () inline virtual inherited
Reimplemented in nidas::dynld::raf::SyncRecordGenerator, and nidas::core::SampleArchiver.
Referenced by nidas::dynld::RawSampleService::printStatus().
bool CVIProcessor::receive (const Sample * s) throw () virtual
The CVIProcessor receive method is configured to received the processed samples from CVI_LV_Input.
These samples contain settings for the analog and digital out channels. receive() reads these values and controls the outputs accordingly.
Implements nidas::core::SampleClient.
References nidas::util::BitArray::any(), nidas::core::FLOAT_ST, nidas::core::SampleT< DataT >::getConstDataPtr(), nidas::core::SampleT< DataT >::getDataLength(), nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_ERR, nidas::util::BitArray::setBit(), and nidas::util::Exception::what().
void SampleIOProcessor::removeRequestedSampleTag (SampleTag * tag) protected inherited
Allow subclasses to remove requested SampleTags.
The tag will be deleted.
References nidas::core::SampleIOProcessor::_constRequestedTags, nidas::core::SampleIOProcessor::_requestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
void nidas::core::SampleIOProcessor::removeSampleClient (SampleClient * c) throw () inline virtual inherited
Remove a SampleClient from this SampleSource.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::removeSampleClient().
void nidas::core::SampleIOProcessor::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
void SampleIOProcessor::removeSampleTag (const SampleTag * tag) throw () virtual inherited
Implements nidas::core::SampleSource.
void nidas::dynld::raf::CVIProcessor::setD2ADeviceName (const std::string & val) inline
void nidas::dynld::raf::CVIProcessor::setDigIODeviceName (const std::string & val) inline
virtual void nidas::core::SampleIOProcessor::setDSMConfig (const DSMConfig * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_dsm.
Referenced by nidas::core::DSMConfig::fromDOMElement().
void SampleIOProcessor::setName (const std::string & val) virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by nidas::dynld::psql::PSQLProcessor::PSQLProcessor(), nidas::core::SampleArchiver::SampleArchiver(), nidas::dynld::StatisticsProcessor::StatisticsProcessor(), and nidas::dynld::raf::SyncRecordGenerator::SyncRecordGenerator().
virtual void nidas::core::SampleIOProcessor::setOptional (bool val) inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
void nidas::core::SampleIOProcessor::setSampleId (int val) inline inherited
References nidas::core::SampleIOProcessor::_id, and SET_SPS_ID.
virtual void nidas::core::SampleIOProcessor::setService (const DSMService * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_service.
Referenced by nidas::core::DSMService::fromDOMElement().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
DSC_AnalogOut nidas::dynld::raf::CVIProcessor::_aout private
SampleAverager nidas::dynld::raf::CVIProcessor::_averager private
std::set<SampleOutput*> nidas::dynld::raf::CVIProcessor::_connectedOutputs private
std::set<SampleSource*> nidas::dynld::raf::CVIProcessor::_connectedSources private
nidas::util::Mutex nidas::dynld::raf::CVIProcessor::_connectionMutex private
std::string nidas::dynld::raf::CVIProcessor::_d2aDeviceName private
std::string nidas::dynld::raf::CVIProcessor::_digioDeviceName private
ViperDIO nidas::dynld::raf::CVIProcessor::_dout private
int nidas::dynld::raf::CVIProcessor::_douts[4] private
dsm_sample_id_t nidas::dynld::raf::CVIProcessor::_lvSampleId private
unsigned int nidas::dynld::raf::CVIProcessor::_numD2A private
unsigned int nidas::dynld::raf::CVIProcessor::_numDigout private
SampleTag* nidas::dynld::raf::CVIProcessor::_outputSampleTag private
float nidas::dynld::raf::CVIProcessor::_rate private
std::list<SampleTag*> nidas::core::SampleIOProcessor::_requestedTags protected inherited
Referenced by nidas::core::SampleIOProcessor::removeRequestedSampleTag(), nidas::dynld::StatisticsProcessor::selectRequestedSampleTags(), and nidas::core::SampleIOProcessor::~SampleIOProcessor().
const Site* nidas::dynld::raf::CVIProcessor::_site private
SampleSourceSupport nidas::core::SampleIOProcessor::_source protected inherited
Referenced by nidas::core::SampleIOProcessor::addSampleClient(), nidas::core::SampleIOProcessor::addSampleClientForTag(), nidas::core::SampleIOProcessor::getClientCount(), nidas::core::SampleIOProcessor::getProcessedSampleSource(), nidas::core::SampleIOProcessor::getSampleStats(), nidas::core::SampleIOProcessor::getSampleTagIterator(), nidas::core::SampleIOProcessor::getSampleTags(), nidas::core::SampleIOProcessor::removeSampleClient(), and nidas::core::SampleIOProcessor::removeSampleClientForTag().
nidas::util::Mutex nidas::core::SampleIOProcessor::_tagsMutex mutable protected inherited
Referenced by nidas::core::SampleIOProcessor::getRequestedSampleTags(), nidas::core::SampleIOProcessor::removeRequestedSampleTag(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
std::vector<bool> nidas::dynld::raf::CVIProcessor::_varMatched private
float nidas::dynld::raf::CVIProcessor::_vouts[5] private
The documentation for this class was generated from the following files:
nidas/dynld/raf/CVIProcessor.h
nidas/dynld/raf/CVIProcessor.cc