nidas: AutoCalClient Class Reference
AutoCalClient Class Reference
Hodge podge class.
#include <AutoCalClient.h>
Classes
struct sA2dSampleInfo
Public Types
typedef map< uint, enum fillState > channel_a_type
typedef map< uint, channel_a_type > device_a_type
typedef map< uint, device_a_type > dsm_a_type
typedef map< int, dsm_a_type > level_a_type
Public Slots
void TestVoltage (int channel, int level)
Signals
void dispVolts ()
void errMessage (const QString &message)
void updateSelection ()
Public Member Functions
AutoCalClient ()
void flush () throw ()
Implementation of SampleClient::flush().
dsm_sample_id_t id (unsigned int dsmId, unsigned int devId)
Reassemble a nidas dsmId and sensorId back into id.
void setTestVoltage (int dsmId, int devId)
bool readCalFile (DSMSensor *sensor)
ncar_a2d_setup GetA2dSetup (int dsmId, int devId)
bool Setup (DSMSensor *sensor)
void createQtTreeModel (map< dsm_sample_id_t, string >dsmLocations)
enum stateEnum SetNextCalVoltage (enum stateEnum state)
bool receive (const Sample *samp) throw ()
Method called to pass a sample to this client.
bool Gathered ()
void DisplayResults ()
int maxProgress ()
string GetTreeModel ()
void SaveAllCalFiles ()
void SaveCalFile (uint dsmId, uint devId)
list< int > GetVoltageLevels ()
list< int > GetVoltageLevels (uint dsmId, uint devId, uint chn)
string GetVarName (uint dsmId, uint devId, uint chn)
string GetOldTimeStamp (uint dsmId, uint devId, uint chn)
string GetNewTimeStamp (uint dsmId, uint devId, uint chn)
float GetOldTemperature (uint dsmId, uint devId, uint chn)
float GetNewTemperature (uint dsmId, uint devId, uint chn)
float GetOldIntcp (uint dsmId, uint devId, uint chn)
float GetNewIntcp (uint dsmId, uint devId, uint chn)
float GetOldSlope (uint dsmId, uint devId, uint chn)
float GetNewSlope (uint dsmId, uint devId, uint chn)
Public Attributes
unsigned int nLevels
int progress
level_a_type calActv
calActv[level][dsmId][devId][chn]
map< uint, map< uint, map
< uint, float > > > testData
testData[dsmId][devId][chn]
Private Types
typedef vector< float > data_d_type
typedef map< int, data_d_type > level_d_type
typedef map< uint, level_d_type > channel_d_type
typedef map< uint, channel_d_type > device_d_type
typedef map< uint, device_d_type > dsm_d_type
Private Member Functions
string ChnSetDesc (unsigned int val)
Private Attributes
bool testVoltage
int tvDsmId
int tvDevId
ostringstream QTreeModel
ostringstream QStrBuf
dsm_time_t lastTimeStamp
map< string, list< int > > voltageLevels
voltageLevels["GB"] indexed by "1T", "2F", "2T", or "4F"
map< dsm_sample_id_t,
sA2dSampleInfo > sampleInfo
map< uint, map< uint,
dsm_sample_id_t > > temperatureId
map< uint, string > dsmNames
map< uint, string > devNames
map< int, uint > slowestRate
dsm_d_type calData
calData[dsmId][devId][chn][level]
int idxVltLvl
index to active voltage level
int VltLvl
active voltage level
map< uint, map< uint, map
< uint, map< uint, bool > > > > isNAN
isNAN[dsmId][devId][chn][level]
map< uint, map< uint, string > > calFilePath
calFilePath[dsmId][devId]
map< uint, map< uint, string > > calFileName
calFileName[dsmId][devId]
map< uint, map< uint, bool > > calFileSaved
calFileSaved[dsmId][devId]
map< uint, map< uint, string > > calFileResults
calFileResults[dsmId][devId]
map< uint, map< uint, float > > resultTemperature
resultTemperature[dsmId][devId]
map< uint, map< uint,
data_d_type > > temperatureData
temperatureData[dsmId][devId]
map< uint, map< uint, map
< uint, string > > > VarNames
VarNames[dsmId][devId][chn].
map< uint, map< uint, map
< uint, int > > > Gains
Gains[dsmId][devId][chn].
map< uint, map< uint, map
< uint, int > > > Bplrs
Bplrs[dsmId][devId][chn].
map< uint, map< uint, map
< uint, dsm_time_t > > > timeStamp
timeStamp[dsmId][devId][chn]
map< uint, map< uint, map
< uint, map< uint, dsm_time_t > > > > calFileTime
calFileTime[dsmId][devId][gain][bplr]
map< uint, map< uint, map
< uint, map< uint, map< uint,
float > > > > > calFileIntcp
calFileIntcp[dsmId][devId][chn][gain][bplr]
map< uint, map< uint, map
< uint, map< uint, map< uint,
float > > > > > calFileSlope
calFileSlope[dsmId][devId][chn][gain][bplr]
map< uint, map< uint, map
< uint, map< uint, map< uint,
float > > > > > resultIntcp
resultIntcp[dsmId][devId][chn][gain][bplr]
map< uint, map< uint, map
< uint, map< uint, map< uint,
float > > > > > resultSlope
resultSlope[dsmId][devId][chn][gain][bplr]
level_a_type::iterator iLevel
dsm_a_type::iterator iDsm
device_a_type::iterator iDevice
channel_a_type::iterator iChannel
Detailed Description
Hodge podge class.
Generates QtTree of DSMs for the Wizard, collects data from dsm_server, progress bar, stores and displays results from all analog cards.
Member Typedef Documentation
typedef map<uint, enum fillState> AutoCalClient::channel_a_type
typedef map<uint, level_d_type> AutoCalClient::channel_d_type private
typedef vector<float> AutoCalClient::data_d_type private
typedef map<uint, channel_a_type> AutoCalClient::device_a_type
typedef map<uint, channel_d_type> AutoCalClient::device_d_type private
typedef map<uint, device_a_type> AutoCalClient::dsm_a_type
typedef map<uint, device_d_type> AutoCalClient::dsm_d_type private
typedef map< int, dsm_a_type> AutoCalClient::level_a_type
typedef map< int, data_d_type> AutoCalClient::level_d_type private
Constructor & Destructor Documentation
AutoCalClient::AutoCalClient ()
References voltageLevels.
Member Function Documentation
string AutoCalClient::ChnSetDesc (unsigned int val) private
Referenced by SetNextCalVoltage(), and TestVoltage().
void AutoCalClient::createQtTreeModel (map< dsm_sample_id_t, string > dsmLocations)
References calActv, calFileName, devNames, dsmNames, id(), iDevice, iDsm, iLevel, and QTreeModel.
void AutoCalClient::DisplayResults ()
References Bplrs, calActv, calData, calFileName, calFileResults, devNames, dsmNames, errMessage(), fillStateDesc, nidas::util::UTime::format(), Gains, iChannel, iDevice, iDsm, iLevel, isNAN, maxProgress(), NUM_NCAR_A2D_CHANNELS, progress, resultIntcp, resultSlope, resultTemperature, temperatureData, and timeStamp.
Referenced by Calibrator::run().
void AutoCalClient::dispVolts () signal
void AutoCalClient::errMessage (const QString & message) signal
Referenced by DisplayResults().
void AutoCalClient::flush () throw () inline virtual
Implementation of SampleClient::flush().
Implements nidas::core::SampleClient.
bool AutoCalClient::Gathered ()
References calActv, AutoCalClient::sA2dSampleInfo::channel, AutoCalClient::sA2dSampleInfo::devId, AutoCalClient::sA2dSampleInfo::dsmId, EMPTY, FULL, AutoCalClient::sA2dSampleInfo::isaTemperatureId, sampleInfo, and VltLvl.
Referenced by Calibrator::run().
ncar_a2d_setup AutoCalClient::GetA2dSetup (int dsmId, int devId)
References Bplrs, ncar_a2d_setup::calset, devNames, DSM_XMLRPC_PORT_TCP, dsmNames, ncar_a2d_setup::gain, Gains, id(), NUM_NCAR_A2D_CHANNELS, ncar_a2d_setup::offset, and ncar_a2d_setup::vcal.
Referenced by TestA2DPage::updateSelection().
float AutoCalClient::GetNewIntcp (uint dsmId, uint devId, uint chn)
References Bplrs, Gains, and resultIntcp.
Referenced by AutoCalPage::selectionChanged().
float AutoCalClient::GetNewSlope (uint dsmId, uint devId, uint chn)
References Bplrs, Gains, and resultSlope.
Referenced by AutoCalPage::selectionChanged().
float AutoCalClient::GetNewTemperature (uint dsmId, uint devId, uint chn)
References resultTemperature.
Referenced by AutoCalPage::selectionChanged().
string AutoCalClient::GetNewTimeStamp (uint dsmId, uint devId, uint chn)
References nidas::util::UTime::format(), and timeStamp.
Referenced by AutoCalPage::selectionChanged().
float AutoCalClient::GetOldIntcp (uint dsmId, uint devId, uint chn)
References Bplrs, calFileIntcp, and Gains.
Referenced by TestA2DPage::dispVolts(), and AutoCalPage::selectionChanged().
float AutoCalClient::GetOldSlope (uint dsmId, uint devId, uint chn)
References Bplrs, calFileSlope, and Gains.
Referenced by TestA2DPage::dispVolts(), and AutoCalPage::selectionChanged().
float AutoCalClient::GetOldTemperature (uint dsmId, uint devId, uint chn)
References nidas::core::floatNAN.
Referenced by AutoCalPage::selectionChanged().
string AutoCalClient::GetOldTimeStamp (uint dsmId, uint devId, uint chn)
References Bplrs, calFileTime, nidas::util::UTime::format(), and Gains.
Referenced by AutoCalPage::selectionChanged().
string AutoCalClient::GetTreeModel () inline
Referenced by AutoCalPage::createTree(), and TestA2DPage::createTree().
string AutoCalClient::GetVarName (uint dsmId, uint devId, uint chn)
References QStrBuf, and VarNames.
Referenced by AutoCalPage::selectionChanged(), and TestA2DPage::updateSelection().
list< int > AutoCalClient::GetVoltageLevels ()
References voltageLevels.
Referenced by TestA2DPage::createGrid(), TestA2DPage::selectionChanged(), TestA2DPage::TestVoltage(), TestA2DPage::updateSelection(), and TestA2DPage::~TestA2DPage().
list< int > AutoCalClient::GetVoltageLevels (uint dsmId, uint devId, uint chn)
References Bplrs, Gains, VarNames, and voltageLevels.
dsm_sample_id_t AutoCalClient::id (unsigned int dsmId, unsigned int devId)
Reassemble a nidas dsmId and sensorId back into id.
References SET_DSM_ID, and SET_SPS_ID.
Referenced by createQtTreeModel(), GetA2dSetup(), SetNextCalVoltage(), Setup(), and TestVoltage().
int AutoCalClient::maxProgress () inline
References NSAMPS.
Referenced by DisplayResults(), and AutoCalPage::initializePage().
bool AutoCalClient::readCalFile (DSMSensor * sensor)
References calFileIntcp, calFileName, calFilePath, calFileSlope, calFileTime, nidas::core::CalFile::close(), nidas::core::CalFile::eof(), nidas::core::DSMSensor::getCalFiles(), nidas::core::DSMSensor::getDeviceName(), nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getDSMName(), nidas::core::CalFile::getFile(), nidas::core::CalFile::getPath(), nidas::core::DSMSensor::getSensorId(), nidas::core::CalFile::nextTime(), NUM_NCAR_A2D_CHANNELS, nidas::core::CalFile::open(), nidas::core::CalFile::readCF(), nidas::util::UTime::toUsecs(), USECS_PER_SEC, and nidas::util::Exception::what().
Referenced by Setup().
bool AutoCalClient::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Implements nidas::core::SampleClient.
References EMPTY, fp, FULL, NSAMPS, rate, TDELAY, and USECS_PER_SEC.
void AutoCalClient::SaveAllCalFiles ()
References calData, and SaveCalFile().
Referenced by AutoCalPage::saveButtonClicked().
void AutoCalClient::SaveCalFile (uint dsmId, uint devId)
References calFileName, calFilePath, calFileResults, calFileSaved, and fd.
Referenced by SaveAllCalFiles().
enum stateEnum AutoCalClient::SetNextCalVoltage (enum stateEnum state)
References calActv, ChnSetDesc(), DEAD, devNames, DONE, DSM_XMLRPC_PORT_TCP, dsmNames, EMPTY, fillStateDesc, iChannel, id(), iDevice, iDsm, idxVltLvl, if(), iLevel, lastTimeStamp, USECS_PER_SEC, and VltLvl.
Referenced by Calibrator::run().
void AutoCalClient::setTestVoltage (int dsmId, int devId)
References testVoltage, tvDevId, and tvDsmId.
Referenced by TestA2DPage::initializePage(), TestA2DPage::selectionChanged(), and TestA2DPage::TestVoltage().
bool AutoCalClient::Setup (DSMSensor * sensor)
References Bplrs, calActv, calData, ncar_a2d_setup::calset, devNames, DSM_XMLRPC_PORT_TCP, dsmNames, fillStateDesc, ncar_a2d_setup::gain, Gains, nidas::core::Variable::getA2dChannel(), nidas::core::DSMSensor::getDeviceName(), nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getDSMName(), nidas::core::SampleTag::getId(), nidas::core::Variable::getName(), nidas::core::Parameter::getNumericValue(), nidas::core::Variable::getParameter(), nidas::core::SampleTag::getRate(), nidas::core::DSMSensor::getSampleTags(), nidas::core::DSMSensor::getSensorId(), nidas::core::SampleTag::getVariable(), nidas::core::SampleTag::getVariables(), id(), lastTimeStamp, nLevels, NSAMPS, NUM_NCAR_A2D_CHANNELS, ncar_a2d_setup::offset, PEND, readCalFile(), sampleInfo, nidas::core::Variable::setConverter(), slowestRate, temperatureData, temperatureId, timeStamp, VarNames, ncar_a2d_setup::vcal, and voltageLevels.
void AutoCalClient::TestVoltage (int channel, int level) slot
References ChnSetDesc(), devNames, DSM_XMLRPC_PORT_TCP, dsmNames, id(), tvDevId, tvDsmId, and updateSelection().
void AutoCalClient::updateSelection () signal
Referenced by TestVoltage().
Member Data Documentation
map<uint, map<uint, map<uint, int> > > AutoCalClient::Bplrs private
Bplrs[dsmId][devId][chn].
Referenced by DisplayResults(), GetA2dSetup(), GetNewIntcp(), GetNewSlope(), GetOldIntcp(), GetOldSlope(), GetOldTimeStamp(), GetVoltageLevels(), and Setup().
level_a_type AutoCalClient::calActv
calActv[level][dsmId][devId][chn]
Referenced by createQtTreeModel(), DisplayResults(), TestA2DPage::dispVolts(), Gathered(), SetNextCalVoltage(), and Setup().
dsm_d_type AutoCalClient::calData private
calData[dsmId][devId][chn][level]
Referenced by DisplayResults(), SaveAllCalFiles(), and Setup().
map<uint, map<uint, map<uint, map<uint, map<uint, float > > > > > AutoCalClient::calFileIntcp private
calFileIntcp[dsmId][devId][chn][gain][bplr]
Referenced by GetOldIntcp(), and readCalFile().
map<uint, map<uint, string > > AutoCalClient::calFileName private
calFileName[dsmId][devId]
Referenced by createQtTreeModel(), DisplayResults(), readCalFile(), and SaveCalFile().
map<uint, map<uint, string > > AutoCalClient::calFilePath private
calFilePath[dsmId][devId]
Referenced by readCalFile(), and SaveCalFile().
map<uint, map<uint, string > > AutoCalClient::calFileResults private
calFileResults[dsmId][devId]
Referenced by DisplayResults(), and SaveCalFile().
map<uint, map<uint, bool > > AutoCalClient::calFileSaved private
calFileSaved[dsmId][devId]
Referenced by SaveCalFile().
map<uint, map<uint, map<uint, map<uint, map<uint, float > > > > > AutoCalClient::calFileSlope private
calFileSlope[dsmId][devId][chn][gain][bplr]
Referenced by GetOldSlope(), and readCalFile().
map<uint, map<uint, map<uint, map<uint, dsm_time_t > > > > AutoCalClient::calFileTime private
calFileTime[dsmId][devId][gain][bplr]
Referenced by GetOldTimeStamp(), and readCalFile().
map<uint, string> AutoCalClient::devNames private
Referenced by createQtTreeModel(), DisplayResults(), GetA2dSetup(), SetNextCalVoltage(), Setup(), and TestVoltage().
map<uint, string> AutoCalClient::dsmNames private
Referenced by createQtTreeModel(), DisplayResults(), GetA2dSetup(), SetNextCalVoltage(), Setup(), and TestVoltage().
map<uint, map<uint, map<uint, int> > > AutoCalClient::Gains private
Gains[dsmId][devId][chn].
Referenced by DisplayResults(), GetA2dSetup(), GetNewIntcp(), GetNewSlope(), GetOldIntcp(), GetOldSlope(), GetOldTimeStamp(), GetVoltageLevels(), and Setup().
channel_a_type::iterator AutoCalClient::iChannel private
Referenced by DisplayResults(), and SetNextCalVoltage().
device_a_type::iterator AutoCalClient::iDevice private
Referenced by createQtTreeModel(), DisplayResults(), and SetNextCalVoltage().
dsm_a_type::iterator AutoCalClient::iDsm private
Referenced by createQtTreeModel(), DisplayResults(), and SetNextCalVoltage().
int AutoCalClient::idxVltLvl private
index to active voltage level
Referenced by SetNextCalVoltage().
level_a_type::iterator AutoCalClient::iLevel private
Referenced by createQtTreeModel(), DisplayResults(), and SetNextCalVoltage().
map<uint, map<uint, map<uint, map<uint, bool> > > > AutoCalClient::isNAN private
isNAN[dsmId][devId][chn][level]
Referenced by DisplayResults().
dsm_time_t AutoCalClient::lastTimeStamp private
Referenced by SetNextCalVoltage(), and Setup().
unsigned int AutoCalClient::nLevels
Referenced by Setup().
int AutoCalClient::progress
Referenced by DisplayResults(), and Calibrator::run().
ostringstream AutoCalClient::QStrBuf private
Referenced by GetVarName().
ostringstream AutoCalClient::QTreeModel private
Referenced by createQtTreeModel().
map<uint, map<uint, map<uint, map<uint, map<uint, float > > > > > AutoCalClient::resultIntcp private
resultIntcp[dsmId][devId][chn][gain][bplr]
Referenced by DisplayResults(), and GetNewIntcp().
map<uint, map<uint, map<uint, map<uint, map<uint, float > > > > > AutoCalClient::resultSlope private
resultSlope[dsmId][devId][chn][gain][bplr]
Referenced by DisplayResults(), and GetNewSlope().
map<uint, map<uint, float > > AutoCalClient::resultTemperature private
resultTemperature[dsmId][devId]
Referenced by DisplayResults(), and GetNewTemperature().
map<dsm_sample_id_t, sA2dSampleInfo> AutoCalClient::sampleInfo private
Referenced by Gathered(), and Setup().
map< int, uint> AutoCalClient::slowestRate private
Referenced by Setup().
map<uint, map<uint, data_d_type > > AutoCalClient::temperatureData private
temperatureData[dsmId][devId]
Referenced by DisplayResults(), and Setup().
map<uint, map<uint, dsm_sample_id_t > > AutoCalClient::temperatureId private
Referenced by Setup().
map<uint, map<uint, map<uint, float > > > AutoCalClient::testData
testData[dsmId][devId][chn]
Referenced by TestA2DPage::dispVolts().
bool AutoCalClient::testVoltage private
Referenced by setTestVoltage().
map<uint, map<uint, map<uint, dsm_time_t> > > AutoCalClient::timeStamp private
timeStamp[dsmId][devId][chn]
Referenced by DisplayResults(), GetNewTimeStamp(), and Setup().
int AutoCalClient::tvDevId private
Referenced by setTestVoltage(), and TestVoltage().
int AutoCalClient::tvDsmId private
Referenced by setTestVoltage(), and TestVoltage().
map<uint, map<uint, map<uint, string> > > AutoCalClient::VarNames private
VarNames[dsmId][devId][chn].
Referenced by GetVarName(), GetVoltageLevels(), and Setup().
int AutoCalClient::VltLvl private
active voltage level
Referenced by Gathered(), and SetNextCalVoltage().
map<string, list <int> > AutoCalClient::voltageLevels private
voltageLevels["GB"] indexed by "1T", "2F", "2T", or "4F"
Referenced by AutoCalClient(), GetVoltageLevels(), and Setup().
The documentation for this class was generated from the following files:
nidas/apps/auto_cal/AutoCalClient.h
nidas/apps/auto_cal/AutoCalClient.cc