nidas: ProjConfigIO Class Reference
ProjConfigIO Class Reference
Public Types
enum tasks {
NUTTIN_TO_DO, LIST_CONFIG_NAMES, LIST_CONFIGS, ADD_CONFIG_BY_TIME,
TERM_CONFIG, GET_CONFIG, GET_CONFIG_FOR_TIME
}
Public Member Functions
ProjConfigIO ()
int parseRunstring (int argc, char **argv)
int run ()
void listConfigs (bool allinfo) throw (nidas::core::XMLException, n_u::InvalidParameterException)
void addConfigByTime () throw (nidas::core::XMLException, n_u::InvalidParameterException,n_u::IOException)
void termConfig () throw (nidas::core::XMLException, n_u::InvalidParameterException,n_u::IOException)
void getConfig ()
void getConfigForTime ()
Static Public Member Functions
static int usage (const char *argv0)
Private Attributes
string xmlFile
XML file containing project configurations.
enum tasks task
What to do, per runstring arguments.
string cname
Name of project configuration.
n_u::UTime cbegin
Time of start of project configuration.
n_u::UTime cend
Time of end of project configuration.
string cxml
Name of xml containing nidas configuration for a project.
string timeformat
ProjectConfigs configs
Member Enumeration Documentation
enum ProjConfigIO::tasks
Enumerator
NUTTIN_TO_DO
LIST_CONFIG_NAMES
LIST_CONFIGS
ADD_CONFIG_BY_TIME
TERM_CONFIG
GET_CONFIG
GET_CONFIG_FOR_TIME
Constructor & Destructor Documentation
ProjConfigIO::ProjConfigIO ()
Member Function Documentation
void ProjConfigIO::addConfigByTime () throw (nidas::core::XMLException, n_u::InvalidParameterException, n_u::IOException)
References nidas::core::ProjectConfigs::addConfigByTime(), cbegin, cend, cname, configs, cxml, nidas::core::ProjectConfigs::getConfigs(), nidas::core::ProjectConfig::getName(), nidas::core::ProjectConfig::setBeginTime(), nidas::core::ProjectConfig::setEndTime(), nidas::core::ProjectConfig::setName(), nidas::core::ProjectConfig::setXMLName(), nidas::core::ProjectConfigs::writeXML(), and xmlFile.
Referenced by run().
void ProjConfigIO::getConfig ()
References cname, configs, nidas::core::ProjectConfig::getBeginTime(), nidas::core::ProjectConfigs::getConfigs(), nidas::core::ProjectConfig::getEndTime(), nidas::core::ProjectConfig::getName(), nidas::core::ProjectConfig::getXMLName(), timeformat, nidas::util::UTime::toUsecs(), and USECS_PER_SEC.
Referenced by run().
void ProjConfigIO::getConfigForTime ()
References cbegin, configs, nidas::core::ProjectConfig::getBeginTime(), nidas::core::ProjectConfigs::getConfigs(), nidas::core::ProjectConfig::getEndTime(), nidas::core::ProjectConfig::getName(), nidas::core::ProjectConfig::getXMLName(), timeformat, nidas::util::UTime::toUsecs(), and USECS_PER_SEC.
Referenced by run().
void ProjConfigIO::listConfigs (bool allinfo) throw (nidas::core::XMLException, n_u::InvalidParameterException)
References nidas::core::ProjectConfig::getBeginTime(), nidas::core::ProjectConfig::getEndTime(), nidas::core::ProjectConfig::getName(), nidas::core::ProjectConfig::getXMLName(), nidas::util::UTime::toUsecs(), and USECS_PER_SEC.
Referenced by run().
int ProjConfigIO::parseRunstring (int argc, char ** argv)
References ADD_CONFIG_BY_TIME, cbegin, cend, cname, cxml, GET_CONFIG, GET_CONFIG_FOR_TIME, LIST_CONFIG_NAMES, LIST_CONFIGS, NUTTIN_TO_DO, nidas::util::UTime::parse(), task, TERM_CONFIG, timeformat, usage(), USECS_PER_DAY, nidas::util::Exception::what(), and xmlFile.
Referenced by main().
int ProjConfigIO::run ()
References ADD_CONFIG_BY_TIME, addConfigByTime(), configs, GET_CONFIG, GET_CONFIG_FOR_TIME, getConfig(), getConfigForTime(), LIST_CONFIG_NAMES, LIST_CONFIGS, listConfigs(), nidas::core::ProjectConfigs::parseXML(), task, TERM_CONFIG, termConfig(), nidas::util::Exception::what(), and xmlFile.
Referenced by main().
void ProjConfigIO::termConfig () throw (nidas::core::XMLException, n_u::InvalidParameterException, n_u::IOException)
References nidas::core::ProjectConfigs::addConfigByTime(), cend, configs, nidas::core::ProjectConfigs::getConfigs(), nidas::core::ProjectConfigs::removeConfig(), nidas::core::ProjectConfig::setEndTime(), nidas::core::ProjectConfigs::writeXML(), and xmlFile.
Referenced by run().
int ProjConfigIO::usage (const char * argv0) static
Referenced by parseRunstring().
Member Data Documentation
n_u::UTime ProjConfigIO::cbegin private
Time of start of project configuration.
Referenced by addConfigByTime(), getConfigForTime(), and parseRunstring().
n_u::UTime ProjConfigIO::cend private
Time of end of project configuration.
Referenced by addConfigByTime(), parseRunstring(), and termConfig().
string ProjConfigIO::cname private
Name of project configuration.
Referenced by addConfigByTime(), getConfig(), and parseRunstring().
ProjectConfigs ProjConfigIO::configs private
Referenced by addConfigByTime(), getConfig(), getConfigForTime(), run(), and termConfig().
string ProjConfigIO::cxml private
Name of xml containing nidas configuration for a project.
Referenced by addConfigByTime(), and parseRunstring().
enum tasks ProjConfigIO::task private
What to do, per runstring arguments.
Referenced by parseRunstring(), and run().
string ProjConfigIO::timeformat private
Referenced by getConfig(), getConfigForTime(), and parseRunstring().
string ProjConfigIO::xmlFile private
XML file containing project configurations.
Referenced by addConfigByTime(), parseRunstring(), run(), and termConfig().
The documentation for this class was generated from the following file:
nidas/apps/proj_configs.cc