nidas: nidas::dynld::raf::CVIOutput Class Reference
nidas::dynld::raf::CVIOutput Class Reference
#include <CVIOutput.h>
Public Member Functions
CVIOutput ()
CVIOutput (IOChannel *iochannel, SampleConnectionRequester *rqstr=0)
~CVIOutput ()
void flush () throw ()
Implementation of SampleClient::flush().
CVIOutput * clone (IOChannel *iochannel=0)
void addRequestedSampleTag (SampleTag *) throw (nidas::util::InvalidParameterException)
Some SampleOutputs don't send out all the Samples that they receive.
void requestConnection (SampleConnectionRequester *requester) throw ()
Request a connection, but don't wait for it.
bool receive (const Sample *samp) throw ()
Method called to pass a sample to this client.
void derivedDataNotify (const DerivedDataReader *s) throw ()
Method called on a DerivedDataClient by the DerivedDataReader thread when a new packet of derived data has been received.
void setIOChannel (IOChannel *val)
Set the IOChannel for this SampleOutput.
SampleOutput * getOriginal () const
Get pointer to SampleOutput that was cloned.
void setName (const std::string &val)
const std::string & getName () const
bool isRaw () const
std::list< const SampleTag * > getRequestedSampleTags () const
void addSourceSampleTag (const SampleTag *tag) throw (nidas::util::InvalidParameterException)
Some SampleOutputs like to be informed of what SampleTags they will be receiving from their SampleSources before they make a connection.
void addSourceSampleTags (const std::list< const SampleTag * > &tags) throw (nidas::util::InvalidParameterException)
std::list< const SampleTag * > getSourceSampleTags () const
SampleOutput * connected (IOChannel *ochan) throw ()
Implementation of IOChannelRequester::connected().
int getReconnectDelaySecs () const
Base class implementation.
void setReconnectDelaySecs (int val)
int getFd () const
void close () throw (nidas::util::IOException)
dsm_time_t getNextFileTime () const
void createNextFile (dsm_time_t) throw (nidas::util::IOException)
size_t write (const void *buf, size_t len) throw (nidas::util::IOException)
Raw write method, typically used to write the initial header.
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
IOChannel * getIOChannel () const
void setHeaderSource (HeaderSource *val)
void setDSMConfig (const DSMConfig *val)
const DSMConfig * getDSMConfig () const
size_t getNumDiscardedSamples () const
void addParameter (Parameter *val)
Add a parameter to this DSMSensor.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
void setLatency (float val) throw (nidas::util::InvalidParameterException)
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
float getLatency () const
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
CVIOutput (CVIOutput &, IOChannel *)
Copy constructor, with a new IOChannel.
size_t incrementDiscardedSamples ()
SampleConnectionRequester * getSampleConnectionRequester ()
void disconnect () throw (nidas::util::IOException)
Close the IOChannel and notify whoever did the requestConnection that it is time to disconnect, perhaps because of an IOException.
Protected Attributes
std::string _name
Private Attributes
std::ostringstream _ostr
std::vector< const Variable * > _variables
dsm_time_t _tt0
float _tas
True airspeed from DerivedDataReader.
Constructor & Destructor Documentation
CVIOutput::CVIOutput ()
Referenced by clone().
CVIOutput::CVIOutput (IOChannel * iochannel, SampleConnectionRequester * rqstr = 0)
References nidas::core::DerivedDataReader::addClient(), nidas::core::DerivedDataReader::getInstance(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::SampleOutputBase::getName(), and nidas::core::SampleOutputBase::setName().
CVIOutput::~CVIOutput ()
References nidas::core::DerivedDataReader::getInstance(), and nidas::core::DerivedDataReader::removeClient().
CVIOutput::CVIOutput (CVIOutput & x, IOChannel * ioc) protected
Copy constructor, with a new IOChannel.
References nidas::core::DerivedDataReader::addClient(), nidas::core::DerivedDataReader::getInstance(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::SampleOutputBase::getName(), and nidas::core::SampleOutputBase::setName().
Member Function Documentation
void SampleOutputBase::addParameter (Parameter * val) inherited
Add a parameter to this DSMSensor.
DSMSensor will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::SampleOutputBase::_constParameters, nidas::core::SampleOutputBase::_parameters, and nidas::core::Parameter::getName().
void CVIOutput::addRequestedSampleTag (SampleTag * tag) throw (nidas::util::InvalidParameterException) virtual
Some SampleOutputs don't send out all the Samples that they receive.
At configuration time, one can use this method to request the SampleTags that should be output from a SampleOutput. SampleOutput will own the pointer.
Reimplemented from nidas::core::SampleOutputBase.
References nidas::core::SampleOutputBase::addRequestedSampleTag(), nidas::core::VariableIterator::hasNext(), and nidas::core::VariableIterator::next().
void SampleOutputBase::addSourceSampleTag (const SampleTag * tag) throw (nidas::util::InvalidParameterException) virtual inherited
Some SampleOutputs like to be informed of what SampleTags they will be receiving from their SampleSources before they make a connection.
Users of SampleOutputs should call this method before calling requestConnection().
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::isff::GOESOutput.
Referenced by nidas::dynld::isff::GOESOutput::addSourceSampleTag(), and nidas::core::SampleOutputBase::SampleOutputBase().
void SampleOutputBase::addSourceSampleTags (const std::list< const SampleTag * > & tags) throw (nidas::util::InvalidParameterException) virtual inherited
Implements nidas::core::SampleOutput.
CVIOutput * CVIOutput::clone (IOChannel * iochannel = 0) virtual
Implements nidas::core::SampleOutput.
References CVIOutput().
void SampleOutputBase::close () throw (nidas::util::IOException) virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::isff::GOESOutput, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::UDPSampleOutput, and nidas::dynld::SampleOutputStream.
References nidas::core::SampleOutputBase::_iochan, nidas::core::SampleOutputBase::_nextFileTime, nidas::core::IOChannel::close(), DLOG, and nidas::core::SampleOutputBase::getName().
Referenced by nidas::dynld::SampleOutputStream::close(), nidas::dynld::UDPSampleOutput::close(), nidas::dynld::isff::GOESOutput::close(), and nidas::core::SampleOutputBase::disconnect().
SampleOutput * SampleOutputBase::connected (IOChannel * ochan) throw () virtual inherited
Implementation of IOChannelRequester::connected().
How an IOChannel calls back to a SampleConnectionRequester that it is connected. The ConnectionRequester can then return a clone of itself if the IOChannel is a new instance.
Implements nidas::core::IOChannelRequester.
Reimplemented in nidas::dynld::isff::GOESOutput, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::UDPSampleOutput, and nidas::dynld::SampleOutputStream.
References nidas::core::SampleOutput::close().
Referenced by nidas::dynld::SampleOutputStream::connected(), nidas::dynld::UDPSampleOutput::connected(), and nidas::dynld::isff::GOESOutput::connected().
void SampleOutputBase::createNextFile (dsm_time_t tt) throw (nidas::util::IOException) inherited
References nidas::core::HeaderSource::sendDefaultHeader().
void CVIOutput::derivedDataNotify (const DerivedDataReader * s) throw () virtual
Method called on a DerivedDataClient by the DerivedDataReader thread when a new packet of derived data has been received.
This method is called on the DerivedDataClients in the sequence that they registered with the DerivedDataReader. The implementation of this method in a client should run quickly, to reduce the delay in calling successive clients in the list.
Implements nidas::core::DerivedDataClient.
void SampleOutputBase::disconnect () throw (nidas::util::IOException) protected inherited
Close the IOChannel and notify whoever did the requestConnection that it is time to disconnect, perhaps because of an IOException.
This is typically called in the receive() method of a SampleOutput if it gets an IOException when writing data. A common implementation of a connection requester is to delete this SampleOutput after the removing it from the sample stream. So the caller method should immediately return after calling disconnect().
References nidas::core::SampleOutputBase::_connectionRequester, nidas::core::SampleOutputBase::close(), nidas::core::SampleConnectionRequester::disconnect(), nidas::core::SampleOutputBase::getName(), and ILOG.
void nidas::dynld::raf::CVIOutput::flush () throw () inline virtual
Implementation of SampleClient::flush().
Implements nidas::core::SampleClient.
void SampleOutputBase::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual inherited
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::isff::GOESOutput, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::UDPSampleOutput, and nidas::dynld::RawSampleOutputStream.
References nidas::core::IOChannel::createIOChannel(), nidas::core::Parameter::createParameter(), nidas::core::DOMable::fromDOMElement(), nidas::core::Project::getInstance(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::IOChannel::setDSMConfig(), and WLOG.
Referenced by nidas::dynld::RawSampleOutputStream::fromDOMElement(), and nidas::dynld::UDPSampleOutput::fromDOMElement().
const DSMConfig* nidas::core::SampleOutputBase::getDSMConfig () const inline virtual inherited
Implements nidas::core::SampleOutput.
Referenced by nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
int SampleOutputBase::getFd () const virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::psql::PSQLSampleOutput.
References nidas::core::SampleOutputBase::_iochan, and nidas::core::IOChannel::getFd().
IOChannel* nidas::core::SampleOutputBase::getIOChannel () const inline virtual inherited
Implements nidas::core::SampleOutput.
Referenced by nidas::dynld::AsciiOutput::AsciiOutput(), CVIOutput(), nidas::dynld::isff::GOESOutput::GOESOutput(), nidas::dynld::AsciiOutput::printHeader(), nidas::dynld::RawSampleOutputStream::RawSampleOutputStream(), nidas::dynld::SampleOutputStream::SampleOutputStream(), nidas::dynld::isff::GOESOutput::setIOChannel(), and setIOChannel().
float nidas::core::SampleOutputBase::getLatency () const inline virtual inherited
Implements nidas::core::SampleOutput.
Referenced by nidas::dynld::SampleOutputStream::SampleOutputStream().
const std::string& nidas::core::SampleOutputBase::getName () const inline virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::psql::PSQLSampleOutput.
Referenced by nidas::dynld::UDPSampleOutput::ConnectionMonitor::addConnection(), nidas::dynld::AsciiOutput::AsciiOutput(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::core::SampleOutputBase::close(), CVIOutput(), nidas::core::SampleOutputBase::disconnect(), nidas::dynld::UDPSampleOutput::XMLSocketListener::fireWorkers(), nidas::dynld::SampleOutputStream::flush(), nidas::dynld::isff::GOESOutput::GOESOutput(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::dynld::isff::GOESOutput::killThread(), nidas::dynld::RawSampleOutputStream::RawSampleOutputStream(), nidas::dynld::UDPSampleOutput::ConnectionMonitor::removeConnection(), nidas::dynld::isff::GOESOutput::run(), nidas::dynld::SampleOutputStream::SampleOutputStream(), nidas::dynld::isff::GOESOutput::setIOChannel(), setIOChannel(), and nidas::dynld::isff::GOESOutput::write().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
dsm_time_t nidas::core::SampleOutputBase::getNextFileTime () const inline inherited
size_t nidas::core::SampleOutputBase::getNumDiscardedSamples () const inline inherited
SampleOutput* nidas::core::SampleOutputBase::getOriginal () const inline virtual inherited
Get pointer to SampleOutput that was cloned.
Will be NULL if this SampleOutput is an un-cloned original.
Implements nidas::core::SampleOutput.
const Parameter * SampleOutputBase::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::SampleOutputBase::_parameters.
const std::list<const Parameter*>& nidas::core::SampleOutputBase::getParameters () const inline inherited
Get list of parameters.
int SampleOutputBase::getReconnectDelaySecs () const virtual inherited
Base class implementation.
If setReconnectDelaySecs() has been called on this SampleOutput, then that value will be returned. Otherwise this will return the value of the IOChannel.
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_iochan, nidas::core::SampleOutputBase::_reconnectDelaySecs, and nidas::core::IOChannel::getReconnectDelaySecs().
std::list< const SampleTag * > SampleOutputBase::getRequestedSampleTags () const virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_constRequestedTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::dynld::isff::GOESProject::GOESProject(), nidas::dynld::isff::GOESOutput::run(), and nidas::core::SampleOutputBase::SampleOutputBase().
SampleConnectionRequester* nidas::core::SampleOutputBase::getSampleConnectionRequester () inline protected inherited
list< const SampleTag * > SampleOutputBase::getSourceSampleTags () const virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_sourceTags, and nidas::core::SampleOutputBase::_tagsMutex.
Referenced by nidas::core::SampleOutputBase::SampleOutputBase().
size_t nidas::core::SampleOutputBase::incrementDiscardedSamples () inline protected inherited
bool nidas::core::SampleOutputBase::isRaw () const inline virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::psql::PSQLSampleOutput, and nidas::dynld::RawSampleOutputStream.
bool CVIOutput::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Implements nidas::core::SampleClient.
References nidas::core::FLOAT_ST, fp, nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_ERR, MSECS_PER_SEC, USECS_PER_DAY, USECS_PER_MSEC, and nidas::util::Exception::what().
void CVIOutput::requestConnection (SampleConnectionRequester * requester) throw () virtual
Request a connection, but don't wait for it.
Requester will be notified via SampleConnectionRequester interface when the connection has been made. It is not necessary to call this method if a SampleOutput is constructed with a connected IOChannel.
Reimplemented from nidas::core::SampleOutputBase.
References nidas::core::DerivedDataReader::addClient(), nidas::core::DerivedDataReader::getInstance(), and nidas::core::SampleOutputBase::requestConnection().
void nidas::core::SampleOutputBase::setDSMConfig (const DSMConfig * val) inline virtual inherited
Implements nidas::core::SampleOutput.
void nidas::core::SampleOutputBase::setHeaderSource (HeaderSource * val) inline virtual inherited
Implements nidas::core::SampleOutput.
Referenced by NidsMerge::run(), SensorExtract::run(), and ARLIngest::run().
void CVIOutput::setIOChannel (IOChannel * val) virtual
Set the IOChannel for this SampleOutput.
This IOChannel is not yet connected. The IOChannel must be connected before the SampleOutput is used for I/O, using the requestConnection() method, or by IOChannel::connect() followed by SampleOutput::connected(IOChannel*).
Reimplemented from nidas::core::SampleOutputBase.
References nidas::core::DerivedDataReader::addClient(), nidas::core::DerivedDataReader::getInstance(), nidas::core::SampleOutputBase::getIOChannel(), nidas::core::SampleOutputBase::getName(), nidas::core::SampleOutputBase::setIOChannel(), and nidas::core::SampleOutputBase::setName().
void nidas::core::SampleOutputBase::setLatency (float val) throw (nidas::util::InvalidParameterException) inline virtual inherited
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
Setting a latency of 1/10 sec means buffer data in the IOStream for a 1/10 sec, then send the data to the physical device.
Parameters
val Latency, in seconds.
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::SampleOutputStream.
Referenced by nidas::dynld::SampleOutputStream::setLatency().
void nidas::core::SampleOutputBase::setName (const std::string & val) inline virtual inherited
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::psql::PSQLSampleOutput.
Referenced by nidas::dynld::AsciiOutput::AsciiOutput(), CVIOutput(), nidas::dynld::isff::GOESOutput::GOESOutput(), nidas::dynld::RawSampleOutputStream::RawSampleOutputStream(), nidas::dynld::SampleOutputStream::SampleOutputStream(), nidas::dynld::isff::GOESOutput::setIOChannel(), and setIOChannel().
void SampleOutputBase::setReconnectDelaySecs (int val) virtual inherited
Implements nidas::core::SampleOutput.
References nidas::core::SampleOutputBase::_reconnectDelaySecs.
Referenced by nidas::dynld::raf::SyncServer::init().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
size_t SampleOutputBase::write (const void * buf, size_t len) throw (nidas::util::IOException) virtual inherited
Raw write method, typically used to write the initial header.
Implements nidas::core::SampleOutput.
Reimplemented in nidas::dynld::isff::GOESOutput.
References len.
Member Data Documentation
std::string nidas::core::SampleOutputBase::_name protected inherited
std::ostringstream nidas::dynld::raf::CVIOutput::_ostr private
float nidas::dynld::raf::CVIOutput::_tas private
True airspeed from DerivedDataReader.
dsm_time_t nidas::dynld::raf::CVIOutput::_tt0 private
std::vector<const Variable*> nidas::dynld::raf::CVIOutput::_variables private
The documentation for this class was generated from the following files:
nidas/dynld/raf/CVIOutput.h
nidas/dynld/raf/CVIOutput.cc