nidas: TestA2DPage Class Reference
TestA2DPage Class Reference
#include <CalibrationWizard.h>
Public Slots
void dispVolts ()
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
void TestVoltage ()
void updateSelection ()
Signals
void TestVoltage (int channel, int level)
Public Member Functions
TestA2DPage (Calibrator *calibrator, AutoCalClient *acc, QWidget *parent=0)
~TestA2DPage ()
void initializePage ()
int nextId () const
Private Types
enum { numA2DChannels = 8 }
Private Member Functions
void createTree ()
void createGrid ()
Private Attributes
int dsmId
int devId
Calibrator * calibrator
AutoCalClient * acc
QTreeView * treeView
TreeModel * treeModel
QGroupBox * gridGroupBox
QVBoxLayout * treeLayout
QButtonGroup * buttonGroup
QHBoxLayout * mainLayout
QLabel * ChannelTitle
QLabel * VarNameTitle
QLabel * RawVoltTitle
QLabel * MesVoltTitle
QLabel * SetVoltTitle
QLabel * Channel [numA2DChannels]
QLabel * VarName [numA2DChannels]
QLabel * RawVolt [numA2DChannels]
QLabel * MesVolt [numA2DChannels]
QHBoxLayout * SetVolt [numA2DChannels]
map< int, map< int,
QPushButton * > > vLvlBtn
QButtonGroup * vLevels [numA2DChannels]
Member Enumeration Documentation
anonymous enum private
Enumerator
numA2DChannels
Constructor & Destructor Documentation
TestA2DPage::TestA2DPage (Calibrator * calibrator, AutoCalClient * acc, QWidget * parent = 0)
TestA2DPage::~TestA2DPage ()
References acc, AutoCalClient::GetVoltageLevels(), numA2DChannels, and vLvlBtn.
Member Function Documentation
void TestA2DPage::createGrid () private
References acc, Channel, ChannelTitle, AutoCalClient::GetVoltageLevels(), gridGroupBox, MesVolt, MesVoltTitle, numA2DChannels, RawVolt, RawVoltTitle, SetVoltTitle, TestVoltage(), VarName, VarNameTitle, vLevels, and vLvlBtn.
Referenced by initializePage().
void TestA2DPage::createTree () private
References acc, AutoCalClient::GetTreeModel(), selectionChanged(), treeModel, and treeView.
Referenced by initializePage().
void TestA2DPage::dispVolts () slot
References acc, AutoCalClient::calActv, devId, dsmId, AutoCalClient::GetOldIntcp(), AutoCalClient::GetOldSlope(), MesVolt, numA2DChannels, numeric::PolyEval(), RawVolt, SKIP, and AutoCalClient::testData.
Referenced by initializePage().
void TestA2DPage::initializePage ()
References acc, calibrator, createGrid(), createTree(), dispVolts(), gridGroupBox, mainLayout, Calibrator::setTestVoltage(), AutoCalClient::setTestVoltage(), Calibrator::setup(), TestVoltage(), treeView, and updateSelection().
int TestA2DPage::nextId () const inline
void TestA2DPage::selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) slot
References acc, TreeModel::data(), devId, dsmId, AutoCalClient::GetVoltageLevels(), MesVolt, numA2DChannels, RawVolt, AutoCalClient::setTestVoltage(), treeModel, updateSelection(), VarName, and vLvlBtn.
Referenced by createTree().
void TestA2DPage::TestVoltage (int channel, int level) signal
void TestA2DPage::TestVoltage () slot
References acc, devId, dsmId, AutoCalClient::GetVoltageLevels(), numA2DChannels, AutoCalClient::setTestVoltage(), and vLvlBtn.
Referenced by createGrid(), and initializePage().
void TestA2DPage::updateSelection () slot
References acc, ncar_a2d_setup::calset, devId, dsmId, AutoCalClient::GetA2dSetup(), AutoCalClient::GetVarName(), AutoCalClient::GetVoltageLevels(), MesVolt, numA2DChannels, RawVolt, VarName, ncar_a2d_setup::vcal, and vLvlBtn.
Referenced by initializePage(), and selectionChanged().
Member Data Documentation
AutoCalClient* TestA2DPage::acc private
Referenced by createGrid(), createTree(), dispVolts(), initializePage(), selectionChanged(), TestVoltage(), updateSelection(), and ~TestA2DPage().
QButtonGroup* TestA2DPage::buttonGroup private
Calibrator* TestA2DPage::calibrator private
Referenced by initializePage().
QLabel* TestA2DPage::Channel[numA2DChannels] private
Referenced by createGrid().
QLabel* TestA2DPage::ChannelTitle private
Referenced by createGrid().
int TestA2DPage::devId private
Referenced by dispVolts(), selectionChanged(), TestVoltage(), and updateSelection().
int TestA2DPage::dsmId private
Referenced by dispVolts(), selectionChanged(), TestVoltage(), and updateSelection().
QGroupBox* TestA2DPage::gridGroupBox private
Referenced by createGrid(), and initializePage().
QHBoxLayout* TestA2DPage::mainLayout private
Referenced by initializePage().
QLabel* TestA2DPage::MesVolt[numA2DChannels] private
Referenced by createGrid(), dispVolts(), selectionChanged(), and updateSelection().
QLabel* TestA2DPage::MesVoltTitle private
Referenced by createGrid().
QLabel* TestA2DPage::RawVolt[numA2DChannels] private
Referenced by createGrid(), dispVolts(), selectionChanged(), and updateSelection().
QLabel* TestA2DPage::RawVoltTitle private
Referenced by createGrid().
QHBoxLayout* TestA2DPage::SetVolt[numA2DChannels] private
QLabel* TestA2DPage::SetVoltTitle private
Referenced by createGrid().
QVBoxLayout* TestA2DPage::treeLayout private
TreeModel* TestA2DPage::treeModel private
Referenced by createTree(), and selectionChanged().
QTreeView* TestA2DPage::treeView private
Referenced by createTree(), and initializePage().
QLabel* TestA2DPage::VarName[numA2DChannels] private
Referenced by createGrid(), selectionChanged(), and updateSelection().
QLabel* TestA2DPage::VarNameTitle private
Referenced by createGrid().
QButtonGroup* TestA2DPage::vLevels[numA2DChannels] private
Referenced by createGrid().
map<int, map< int, QPushButton* > > TestA2DPage::vLvlBtn private
Referenced by createGrid(), selectionChanged(), TestVoltage(), updateSelection(), and ~TestA2DPage().
The documentation for this class was generated from the following files:
nidas/apps/auto_cal/CalibrationWizard.h
nidas/apps/auto_cal/CalibrationWizard.cc