nidas: TreeItem Class Reference
TreeItem Class Reference
#include <TreeItem.h>
Public Member Functions
TreeItem (const QList< QVariant > &data, TreeItem *parent=0)
~TreeItem ()
void appendChild (TreeItem *child)
TreeItem * child (int row)
int childCount () const
int columnCount () const
QVariant data (int column) const
int row () const
TreeItem * parent ()
Private Attributes
QList< TreeItem * > childItems
QList< QVariant > itemData
TreeItem * parentItem
Constructor & Destructor Documentation
TreeItem::TreeItem (const QList< QVariant > & data, TreeItem * parent = 0)
References data(), itemData, parent(), and parentItem.
TreeItem::~TreeItem ()
References childItems.
Member Function Documentation
void TreeItem::appendChild (TreeItem * child)
References childItems.
TreeItem * TreeItem::child (int row)
References childItems.
Referenced by TreeModel::index().
int TreeItem::childCount () const
References childItems.
Referenced by TreeModel::rowCount().
int TreeItem::columnCount () const
References itemData.
Referenced by TreeModel::columnCount().
QVariant TreeItem::data (int column) const
References itemData.
Referenced by TreeModel::data(), TreeModel::headerData(), and TreeItem().
TreeItem * TreeItem::parent ()
References parentItem.
Referenced by TreeModel::parent(), and TreeItem().
int TreeItem::row () const
References childItems, and parentItem.
Referenced by TreeModel::parent().
Member Data Documentation
QList<TreeItem*> TreeItem::childItems private
Referenced by appendChild(), child(), childCount(), row(), and ~TreeItem().
QList<QVariant> TreeItem::itemData private
Referenced by columnCount(), data(), and TreeItem().
TreeItem* TreeItem::parentItem private
Referenced by parent(), row(), and TreeItem().
The documentation for this class was generated from the following files:
nidas/apps/auto_cal/TreeItem.h
nidas/apps/auto_cal/TreeItem.cc