nidas: nidas::core::Site Class Reference
nidas::core::Site Class Reference
A measurement site.
#include <Site.h>
Classes
class MyDictionary
Public Member Functions
Site ()
virtual ~Site ()
void setName (const std::string &val)
Set the name of the Site.
const std::string & getName () const
void setNumber (int val)
Identify the Site by number.
int getNumber () const
bool operator== (const Site &x) const
Equivalence operator for Site, checks name.
bool operator!= (const Site &x) const
Non-equivalence operator for Site.
bool operator< (const Site &x) const
Less than operator for Site, compares the names.
void setSuffix (const std::string &val)
Set the suffix for the Site.
const std::string & getSuffix () const
const Project * getProject () const
Provide pointer to Project.
Project * getProject ()
void setProject (Project *val)
Set the current project for this Site.
void addDSMConfig (DSMConfig *dsm)
A Site contains one or more DSMs.
void removeDSMConfig (DSMConfig *dsm)
const std::list< const
DSMConfig * > & getDSMConfigs () const
const std::list< DSMConfig * > & getDSMConfigs ()
void addServer (DSMServer *srvr)
A Site has one or more DSMServers.
const std::list< DSMServer * > & getServers () const
DSMServer * findServer (const std::string &hostname) const
Look for a server on this aircraft that either has no name or whose name matches hostname.
const DSMConfig * findDSM (const nidas::util::Inet4Address &addr) const
Find a DSM whose name corresponds to a given IP address.
const DSMConfig * findDSM (unsigned int id) const
Find a DSM by id.
const DSMConfig * findDSM (const std::string &name) const
Find a DSM by name.
DSMSensor * findSensor (unsigned int id) const
Find a DSMSensor by the full id, both the DSM id and the sensor id.
void initSensors () throw (nidas::util::IOException)
Initialize all sensors for a Site.
void initSensors (DSMConfig *dsm) throw (nidas::util::IOException)
Initialize all sensors for a given dsm.
virtual void addParameter (Parameter *val)
Add a parameter to this Site.
virtual const Parameter * getParameter (const std::string &name) const
virtual const std::list< const
Parameter * > & getParameters () const
virtual bool getApplyVariableConversions () const
Do we want DSMSensor::process methods at this site to apply variable conversions? Currently on raf.Aircraft we don't want process methods to apply the conversions.
std::string expandString (const std::string &input) const
Utility function to expand ${TOKEN} or $TOKEN fields in a string.
bool getTokenValue (const std::string &token, std::string &value) const
Implement a lookup for tokens that I know about, like $SITE, and $AIRCRAFT.
const Dictionary & getDictionary () const
DSMServerIterator getDSMServerIterator () const
DSMServiceIterator getDSMServiceIterator () const
ProcessorIterator getProcessorIterator () const
DSMConfigIterator getDSMConfigIterator () const
SensorIterator getSensorIterator () const
SampleTagIterator getSampleTagIterator () const
VariableIterator getVariableIterator () const
void validate () throw (nidas::util::InvalidParameterException)
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Attributes
bool _applyCals
Should NIDAS apply calibrations, or defer them to other processing.
Private Member Functions
Site (const Site &)
Copy not supported.
Site & operator= (const Site &)
Assignment not supported.
Private Attributes
Project * _project
Pointer back to my project.
std::string _name
int _number
std::string _suffix
nidas::core::Site::MyDictionary _dictionary
std::list< const DSMConfig * > _dsms
std::list< DSMConfig * > _ncDsms
std::list< DSMServer * > _servers
std::map< std::string,
Parameter * > _parameterMap
Mapping of Parameters, by name.
std::list< const Parameter * > _constParameters
List of const pointers to Parameters for providing via getParameters().
Detailed Description
A measurement site.
It could be an Aircraft, or a grouping of measurement systems (e.g. "meadow" site).
Constructor & Destructor Documentation
Site::Site ()
Site::~Site () virtual
References _ncDsms, _parameterMap, and _servers.
nidas::core::Site::Site (const Site &) private
Copy not supported.
See Project copy constructor: Project(const Project&);
Member Function Documentation
void nidas::core::Site::addDSMConfig (DSMConfig * dsm) inline
A Site contains one or more DSMs.
Site will own the pointer and will delete the DSMConfig in its destructor.
References _dsms, and _ncDsms.
Referenced by Document::addDSM().
void Site::addParameter (Parameter * val) virtual
Add a parameter to this Site.
Site will then own the pointer and will delete it in its destructor.
References _constParameters, _parameterMap, and nidas::core::Parameter::getName().
void nidas::core::Site::addServer (DSMServer * srvr) inline
A Site has one or more DSMServers.
References _servers.
std::string nidas::core::Site::expandString (const std::string & input) const inline
Utility function to expand ${TOKEN} or $TOKEN fields in a string.
Utility function to expand ${TOKEN} or $TOKEN fields in a string with their value from getTokenValue(). If curly brackets are not used, then the TOKEN should be delimited by a '/', a '.' or the end of string, e.g.: xxx/yyy/$ZZZ.dat
References _dictionary, and nidas::core::Dictionary::expandString().
const DSMConfig * Site::findDSM (const nidas::util::Inet4Address & addr) const
Find a DSM whose name corresponds to a given IP address.
References _dsms, nidas::util::Inet4Address::getAllByName(), and nidas::core::DSMConfig::getName().
Referenced by nidas::core::Project::findDSM().
const DSMConfig * Site::findDSM (unsigned int id) const
Find a DSM by id.
References _dsms, nidas::core::DSMConfig::getId(), and nidas::core::DSMConfig::getName().
const DSMConfig * Site::findDSM (const std::string & name) const
Find a DSM by name.
References _dsms, and nidas::core::DSMConfig::getName().
DSMSensor * Site::findSensor (unsigned int id) const
Find a DSMSensor by the full id, both the DSM id and the sensor id.
References GET_DSM_ID, GET_SPS_ID, nidas::core::DSMSensor::getDSMId(), nidas::core::SampleTag::getId(), nidas::core::DSMSensor::getId(), getName(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::DSMSensor::getSensorId(), getSensorIterator(), nidas::core::SensorIterator::hasNext(), nidas::core::SampleTagIterator::hasNext(), nidas::core::SensorIterator::next(), and nidas::core::SampleTagIterator::next().
Referenced by nidas::core::Project::findSensor().
DSMServer * Site::findServer (const std::string & hostname) const
Look for a server on this aircraft that either has no name or whose name matches hostname.
If none found, remove any domain names and try again.
References _servers, and nidas::core::DSMServer::getName().
void Site::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
References nidas::core::Parameter::createParameter(), nidas::core::DSMServer::fromDOMElement(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::DSMConfig::getId(), nidas::core::DSMConfig::getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::DSMServer::setProject(), nidas::core::DSMConfig::setSite(), and nidas::core::DSMServer::setSite().
Referenced by nidas::core::Project::fromDOMElement().
virtual bool nidas::core::Site::getApplyVariableConversions () const inline virtual
Do we want DSMSensor::process methods at this site to apply variable conversions? Currently on raf.Aircraft we don't want process methods to apply the conversions.
References _applyCals.
const Dictionary& nidas::core::Site::getDictionary () const inline
References _dictionary.
DSMConfigIterator Site::getDSMConfigIterator () const
Referenced by nidas::dynld::UDPSampleOutput::connected(), main(), and PConfig::showAll().
const std::list<const DSMConfig*>& nidas::core::Site::getDSMConfigs () const inline
References _dsms.
Referenced by Document::getNextDSMId(), nidas::core::DSMConfigIterator::hasNext(), nidas::core::DSMEngine::initialize(), initSensors(), PConfig::showCalFiles(), validate(), and Document::validateDsmInfo().
const std::list<DSMConfig*>& nidas::core::Site::getDSMConfigs () inline
References _ncDsms.
DSMServerIterator Site::getDSMServerIterator () const
DSMServiceIterator Site::getDSMServiceIterator () const
const std::string& nidas::core::Site::getName () const inline
References _name.
Referenced by nidas::core::Project::addSite(), nidas::dynld::StatisticsProcessor::connect(), nidas::core::SampleAverager::connect(), nidas::dynld::StatisticsCruncher::connect(), nidas::core::NearestResampler::ctorCommon(), DSMItem::findDOMNode(), nidas::core::Project::findDSM(), findSensor(), Document::getNextDSMId(), Document::getSiteNames(), nidas::core::Site::MyDictionary::getTokenValue(), Document::insertA2DVariable(), main(), DataPrep::matchVariables(), Document::printSiteNames(), ProjectItem::removeChild(), PConfig::showAll(), PConfig::showCalFiles(), and Document::updateVariable().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
int nidas::core::Site::getNumber () const inline
References _number.
Referenced by nidas::core::Project::addSite(), nidas::dynld::isff::GOESProject::GOESProject(), Document::printSiteNames(), and PConfig::showAll().
const Parameter * Site::getParameter (const std::string & name) const virtual
References _parameterMap.
const list< const Parameter * > & Site::getParameters () const virtual
References _constParameters.
ProcessorIterator Site::getProcessorIterator () const
Referenced by nidas::dynld::isff::GOESProject::GOESProject().
const Project* nidas::core::Site::getProject () const inline
Provide pointer to Project.
References _project.
Referenced by nidas::core::DSMConfig::getProject(), nidas::core::Site::MyDictionary::getTokenValue(), and Document::printSiteNames().
Project* nidas::core::Site::getProject () inline
References _project.
SampleTagIterator Site::getSampleTagIterator () const
SensorIterator Site::getSensorIterator () const
Referenced by findSensor(), and nidas::core::DSMServer::getSensorIterator().
const std::list<DSMServer*>& nidas::core::Site::getServers () const inline
References _servers.
Referenced by nidas::core::DSMServerIterator::hasNext().
const std::string& nidas::core::Site::getSuffix () const inline
References _suffix.
Referenced by nidas::dynld::StatisticsProcessor::connect(), Document::printSiteNames(), nidas::core::Variable::setSite(), and nidas::core::Variable::setStation().
bool nidas::core::Site::getTokenValue (const std::string & token, std::string & value) const inline
Implement a lookup for tokens that I know about, like $SITE, and $AIRCRAFT.
For other tokens, call getProject()->getTokenValue(token,value);
References _dictionary, and nidas::core::Site::MyDictionary::getTokenValue().
Referenced by nidas::core::DSMConfig::MyDictionary::getTokenValue().
VariableIterator Site::getVariableIterator () const
void Site::initSensors () throw (nidas::util::IOException)
Initialize all sensors for a Site.
References getDSMConfigs(), and nidas::core::DSMConfig::initSensors().
Referenced by nidas::core::Project::initSensors().
void Site::initSensors (DSMConfig * dsm) throw (nidas::util::IOException)
Initialize all sensors for a given dsm.
References nidas::core::DSMConfig::initSensors().
bool nidas::core::Site::operator!= (const Site & x) const inline
Non-equivalence operator for Site.
References operator==().
bool nidas::core::Site::operator< (const Site & x) const inline
Less than operator for Site, compares the names.
References _name.
Site& nidas::core::Site::operator= (const Site &) private
Assignment not supported.
bool nidas::core::Site::operator== (const Site & x) const inline
Equivalence operator for Site, checks name.
References _name, _number, and _suffix.
Referenced by operator!=().
void nidas::core::Site::removeDSMConfig (DSMConfig * dsm) inline
References _dsms, and _ncDsms.
Referenced by Document::addDSM().
void nidas::core::Site::setName (const std::string & val) inline
Set the name of the Site.
References _name.
void nidas::core::Site::setNumber (int val) inline
Identify the Site by number.
The site number can be used for things like a NetCDF station dimension.
Parameters
Site number, 0 means no number is associated with the site.
References _number.
void nidas::core::Site::setProject (Project * val) inline
Set the current project for this Site.
References _project.
Referenced by nidas::core::Project::fromDOMElement().
void nidas::core::Site::setSuffix (const std::string & val) inline
Set the suffix for the Site.
All variable names from this site will have the suffix.
References _suffix.
xercesc::DOMElement * Site::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual
Add my content into a DOMElement.
Reimplemented from nidas::core::DOMable.
References nidas::core::DSMConfigIterator::hasNext(), nidas::core::XDOMElement::setAttributeValue(), and nidas::core::DSMConfig::toDOMParent().
xercesc::DOMElement * Site::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual
Create a DOMElement and append it to the parent.
Reimplemented from nidas::core::DOMable.
References nidas::core::DOMable::getNamespaceURI().
Referenced by nidas::core::Project::toDOMElement().
void Site::validate () throw (nidas::util::InvalidParameterException)
References getDSMConfigs(), nidas::core::DSMSensor::getDSMId(), nidas::core::DSMSensor::getDuplicateIdOK(), nidas::core::DSMConfig::getId(), nidas::core::DSMConfig::getName(), nidas::core::DSMSensor::getName(), nidas::core::Variable::getName(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMConfig::getSensorIterator(), nidas::core::DSMSensor::getVariableIterator(), nidas::core::SensorIterator::hasNext(), nidas::core::VariableIterator::hasNext(), and nidas::core::DSMConfig::validate().
Referenced by Document::addSensor(), nidas::core::Project::fromDOMElement(), Document::insertA2DVariable(), Document::updateDSM(), and Document::updateVariable().
Member Data Documentation
bool nidas::core::Site::_applyCals protected
Should NIDAS apply calibrations, or defer them to other processing.
Referenced by getApplyVariableConversions().
std::list<const Parameter*> nidas::core::Site::_constParameters private
List of const pointers to Parameters for providing via getParameters().
Referenced by addParameter(), and getParameters().
nidas::core::Site::MyDictionary nidas::core::Site::_dictionary private
Referenced by expandString(), getDictionary(), and getTokenValue().
std::list<const DSMConfig*> nidas::core::Site::_dsms private
Referenced by addDSMConfig(), findDSM(), getDSMConfigs(), and removeDSMConfig().
std::string nidas::core::Site::_name private
Referenced by getName(), operator<(), operator==(), and setName().
std::list<DSMConfig*> nidas::core::Site::_ncDsms private
Referenced by addDSMConfig(), getDSMConfigs(), removeDSMConfig(), and ~Site().
int nidas::core::Site::_number private
Referenced by getNumber(), operator==(), and setNumber().
std::map<std::string,Parameter*> nidas::core::Site::_parameterMap private
Mapping of Parameters, by name.
Referenced by addParameter(), getParameter(), and ~Site().
Project* nidas::core::Site::_project private
Pointer back to my project.
Referenced by getProject(), and setProject().
std::list<DSMServer*> nidas::core::Site::_servers private
Referenced by addServer(), findServer(), getServers(), and ~Site().
std::string nidas::core::Site::_suffix private
Referenced by getSuffix(), operator==(), and setSuffix().
The documentation for this class was generated from the following files:
nidas/core/Site.h
nidas/core/Site.cc