nidas: nidas::dynld::raf::TwoD32_USB Class Reference
nidas::dynld::raf::TwoD32_USB Class Reference abstract
Sensor class for the standard PMS2D probes where the data signals are converted to USB by a converter box.
#include <TwoD32_USB.h>
Public Member Functions
TwoD32_USB ()
~TwoD32_USB ()
bool process (const Sample *samp, std::list< const Sample * > &results) throw ()
Apply further necessary processing to a raw sample from this DSMSensor.
virtual int NumberOfDiodes () const
Number of diodes in the probe array.
IODevice * buildIODevice () throw (nidas::util::IOException)
Factory method for an IODevice for this DSMSensor.
SampleScanner * buildSampleScanner () throw (nidas::util::InvalidParameterException)
Factory method for a SampleScanner for this DSMSensor.
void open (int flags) throw (nidas::util::IOException,nidas::util::InvalidParameterException)
open the sensor and perform any intialization to the driver.
void close () throw (nidas::util::IOException)
close my associated device.
int getTASRate () const
void setTASRate (int val)
float getResolution () const
The probe resolution in meters.
unsigned int getResolutionMicron () const
The probe resolution in micrometers.
void init () throw (nidas::util::InvalidParameterException)
Called by post-processing code.
virtual void throw ()
void printStatus (std::ostream &ostr) throw ()
int TASToTap2D (Tap2D *t2d, float tas)
Build the struct above from the true airspeed (in m/s).
virtual float Tap2DToTAS (const Tap2D *t2d) const
Reverse the true airspeed encoding.
virtual float Tap2DToTAS (const Tap2Dv1 *t2d) const
The first generation used the Maxim 5418 chip.
void setDSMConfig (const DSMConfig *val)
Set the DSMConfig for this sensor.
const DSMConfig * getDSMConfig () const
What DSMConfig am I associated with?
const Site * getSite () const
What Site am I associated with?
virtual void setDeviceName (const std::string &val)
Set the name of the system device that the sensor is connected to.
virtual const std::string & getDeviceName () const
Fetch the name of the system device that the sensor is connected to.
virtual void setClassName (const std::string &val)
Set the class name.
virtual const std::string & getClassName () const
Fetch the class name.
virtual void setCatalogName (const std::string &val)
Set the name of the catalog entry for this sensor.
virtual const std::string & getCatalogName () const
Fetch the name of the catalog entry for this sensor.
const std::string & getDSMName () const
Fetch the DSM name.
virtual std::string getName () const
Return a name that should fully identify this sensor.
const std::string & getLocation () const
Location string.
void setLocation (const std::string &val)
const std::string & getSuffix () const
Sensor suffix, which is added to variable names.
void setSuffix (const std::string &val)
int getStation () const
void setStation (int val)
void setHeight (const std::string &val)
Set sensor height above ground via a string which is added to variable names.
void setHeight (float val)
Set sensor height above ground.
const std::string & getHeightString () const
Get sensor height above ground in a string.
float getHeight () const
Get sensor height above ground.
void setDepth (const std::string &val)
Set sensor depth below ground via a string which is added to variable names.
void setDepth (float val)
Set sensor depth below ground.
const std::string & getDepthString () const
Get sensor depth below ground in a string.
float getDepth () const
Get sensor depth below ground.
const std::string & getFullSuffix () const
Full sensor suffix, the concatenation of the sensor suffix, if any, and the height or depth string, if any.
std::string expandString (const std::string &input) const
Utility function to expand ${TOKEN} or $TOKEN fields in a string with their value from getTokenValue().
bool getTokenValue (const std::string &token, std::string &value) const
Implement a lookup for tokens that I know about, like $HEIGHT.
const Dictionary & getDictionary () const
SampleSource * getRawSampleSource ()
Implementation of SampleSource::getRawSampleSource().
SampleSource * getProcessedSampleSource ()
Implementation of SampleSource::getProcessedSampleSource().
const SampleTag * getRawSampleTag () const
Convenience function to get my one-and-only raw SampleTag().
virtual void addSampleTag (SampleTag *val) throw (nidas::util::InvalidParameterException)
Add a SampleTag to this sensor.
virtual void removeSampleTag (SampleTag *val) throw ()
Remove val from the list of SampleTags, and delete it.
std::list< const SampleTag * > getSampleTags () const
Implementation of SampleSource::getSampleTags().
std::list< SampleTag * > & getSampleTags ()
Non-const method to get a list of non-const pointers to SampleTags.
SampleTagIterator getSampleTagIterator () const
void addSampleClient (SampleClient *c) throw ()
Add a SampleClient to this SampleSource.
void removeSampleClient (SampleClient *c) throw ()
Remove a SampleClient from this SampleSource This will also remove a SampleClient if it has been added with addSampleClientForTag().
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a SampleClient to this SampleSource.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void flush () throw ()
Implementation of SampleClient::flush().
void distributeRaw (const Sample *s) throw ()
Distribute a raw sample which has been read from my file descriptor in real time.
const SampleStats & getSampleStats () const
virtual int getReadFd () const
virtual int getWriteFd () const
virtual bool reopenOnIOException () const
Whether to reopen this sensor on an IOException.
void setId (dsm_sample_id_t val)
Set the various levels of the sensor identification.
void setSensorId (unsigned int val)
void setDSMId (unsigned int val)
dsm_sample_id_t getId () const
Get the various levels of the samples identification.
unsigned int getDSMId () const
unsigned int getSensorId () const
virtual void setLatency (float val) throw (nidas::util::InvalidParameterException)
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
virtual float getLatency () const
virtual void setTimeoutMsecs (int val)
Set the sensor timeout value in milliseconds.
virtual int getTimeoutMsecs () const
int getTimeoutCount () const
void incrementTimeoutCount ()
void addParameter (Parameter *val)
Add a parameter to this DSMSensor.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
void setIODevice (IODevice *val)
Set the IODevice for this sensor.
void setSampleScanner (SampleScanner *val)
Set the SampleScanner for this sensor.
virtual void validate () throw (nidas::util::InvalidParameterException)
validate() is called once on a DSMSensor after it has been configured, but before open() or init() are called.
virtual int getDefaultMode () const
How do I want to be opened.
virtual void setDefaultMode (int val)
virtual size_t getBytesAvailable () const throw (nidas::util::IOException)
How many bytes are available to read on this sensor.
virtual size_t read (void *buf, size_t len) throw (nidas::util::IOException)
Read from the device (duh).
virtual size_t read (void *buf, size_t len, int msecTimeout) throw (nidas::util::IOException)
Read from the device with a timeout.
virtual size_t write (const void *buf, size_t len) throw (nidas::util::IOException)
Write to the device (duh).
virtual void ioctl (int request, void *buf, size_t len) throw (nidas::util::IOException)
Perform an ioctl on the device.
virtual bool readSamples () throw (nidas::util::IOException)
Read samples from my associated file descriptor, and distribute() them to my RawSampleClient's.
virtual Sample * nextSample ()
Extract the next sample from the buffer.
bool receive (const Sample *s) throw ()
A DSMSensor can be used as a SampleClient, meaning it receives its own raw samples.
void printStatusHeader (std::ostream &ostr) throw ()
void printStatusTrailer (std::ostream &ostr) throw ()
void calcStatistics (unsigned int periodUsec)
Update the sensor sampling statistics.
unsigned int getMaxSampleLength () const
unsigned int getMinSampleLength () const
float getObservedSamplingRate () const
float getObservedDataRate () const
size_t getBadTimeTagCount () const
VariableIterator getVariableIterator () const
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
virtual void setTypeName (const std::string &val)
Set the type name of this sensor, e.g.
virtual const std::string & getTypeName (void) const
Get the type name of this sensor.
bool getDuplicateIdOK () const
getDuplicateIdOK will be true if it is OK for samples from this sensor to have identical IDs to samples from another sensor.
void setDuplicateIdOK (bool val)
Set the duplicate ID attribute of this DSMSensor.
virtual bool getApplyVariableConversions () const
virtual void setApplyVariableConversions (bool val)
virtual int getDriverTimeTagUsecs () const
virtual void setDriverTimeTagUsecs (int val)
void addCalFile (CalFile *val)
Add a calibration file for this DSMSensor.
const std::map< std::string,
CalFile * > & getCalFiles ()
Return the collection of CalFiles, mapped by name.
CalFile * getCalFile (const std::string &name)
Return a CalFile by its getName().
void removeCalFiles ()
Remove all CalFiles.
virtual void executeXmlRpc (XmlRpc::XmlRpcValue &, XmlRpc::XmlRpcValue &) throw ()
Method invoked when the DSMEngineIntf XmlRpcServer receives a "SensorAction" request, with a "device" string matching the string that this DSMSensor registers via DSMEngine::registerSensorWithXmlRpc(string,DSMServer*).
virtual const std::list
< SampleTag * > & getNonConstSampleTags ()
We'll allow derived classes and calibration applications to change the SampleTags, so this method returns a list of non-constant SampleTags.
virtual void derivedDataNotify (const DerivedDataReader *s)=0 throw ()
Method called on a DerivedDataClient by the DerivedDataReader thread when a new packet of derived data has been received.
Static Public Member Functions
static const std::string getClassName (const xercesc::DOMElement *node, const Project *project) throw (nidas::util::InvalidParameterException)
Crawl through the DOM tree for a DSMSensor to find the class name - scanning the catalog entry if necessary.
static void deleteLooper ()
static const XMLCh * getNamespaceURI ()
Protected Member Functions
bool processImage (const Sample *samp, std::list< const Sample * > &results, int stype) throw ()
virtual void init_parameters () throw (nidas::util::InvalidParameterException)
Initialize parameters for real-time and post-processing.
virtual void sendTrueAirspeed (float tas) throw (nidas::util::IOException)
Encode and send the true airspeed to the USB driver, which will in turn send it to the probe.
virtual void processParticleSlice (Particle &p, const unsigned char *slice)
Process a slice and update the Particle struct area, edgeTouch, width and height.
virtual void countParticle (const Particle &p, float resolutionUsec)
Look at particle stats/info and decide whether to accept or reject.
void saveBuffer (const unsigned char *cp, const unsigned char *eod)
In case of mis-aligned data, we may need to save some bytes at the end of an image block to pre-pend to the next block.
void setupBuffer (const unsigned char **cp, const unsigned char **eod)
Derived Classes should call this at the beginning of processing an image block.
bool readBuffer () throw (nidas::util::IOException)
Read into my SampleScanner's buffer.
bool readBuffer (int msecTimeout) throw (nidas::util::IOException)
Read into my SampleScanner's buffer.
void clearBuffer ()
Clear the internal buffer.
IODevice * getIODevice () const
SampleScanner * getSampleScanner () const
void setFullSuffix (const std::string &val)
virtual int getLagUsecs () const
Return the sampling lag for this sensor in microseconds.
virtual double getLagSecs () const
Return the sampling lag for this sensor in seconds.
virtual void setLagSecs (double val)
Set the sampling lag for this sensor in seconds.
virtual bool acceptThisParticle1D (const Particle &p) const
Accept/reject criteria are in these functions.
virtual bool acceptThisParticle2D (const Particle &p) const
virtual void createSamples (dsm_time_t nextTimeTag, std::list< const Sample * > &results) throw ()
Send derived data and reset.
virtual void clearData ()
Clear size_dist arrays.
Static Protected Member Functions
static Looper * getLooper ()
Fetch a pointer to a static instance of a Looper thread.
Protected Attributes
int _tasRate
How often to send the true air speed.
unsigned int _numImages
Number of image blocks processed by driver at time of last printStatus.
long long _lastStatusTime
Time of last printStatus.
dsm_time_t _prevTime
Time from previous record.
long long _histoEndTime
The end time of the current histogram.
float _twoDAreaRejectRatio
Area of particle rejection ratio.
Particle _particle
Current particle information.
float _trueAirSpeed
True air speed, received from IWGADTS feed.
int _nextraValues
If XML file has a variable RPS (records per second) defined, then _nextravalues will be 2, otherwise 1.
unsigned char * _saveBuffer
The saved buffer.
int _savedBytes
How many bytes were last saved.
int _savedAlloc
Size of the saved buffer.
float _resolutionMeters
Probe resolution in meters.
unsigned int _resolutionMicron
Probe resolution in micrometers.
dsm_sample_id_t _sorID
Shadow OR sample ID.
dsm_sample_id_t _1dcID
dsm_sample_id_t _2dcID
unsigned int * _size_dist_1D
Arrays for size-distribution histograms.
unsigned int * _size_dist_2D
float _dead_time
Amount of time probe was inactive or amount of time consumed by rejected particles.
unsigned int _totalRecords
Statistics variables for processRecord().
unsigned int _totalParticles
unsigned int _rejected1D_Cntr
unsigned int _rejected2D_Cntr
unsigned int _overLoadSliceCount
unsigned int _overSizeCount_2D
unsigned int _tasOutOfRange
unsigned int _misAligned
unsigned int _suspectSlices
unsigned int _recordsPerSecond
Static Protected Attributes
static const unsigned char _overldString [] = {0x55, 0xaa}
static const unsigned char _blankString [] = {0xff, 0xff, 0xff, 0xff}
static const
nidas::util::EndianConverter * bigEndian
static const
nidas::util::EndianConverter * littleEndian
static const float DefaultTrueAirspeed = 33.0
Detailed Description
Sensor class for the standard PMS2D probes where the data signals are converted to USB by a converter box.
These probes have the standard 32 diodes.
Constructor & Destructor Documentation
TwoD32_USB::TwoD32_USB ()
TwoD32_USB::~TwoD32_USB ()
Member Function Documentation
bool TwoD_USB::acceptThisParticle1D (const Particle & p) const protected virtual inherited
Accept/reject criteria are in these functions.
Parameters
p is particle info class.
Returns
boolean whether the particle should be rejected.
References nidas::dynld::raf::TwoD_USB::_twoDAreaRejectRatio, nidas::dynld::raf::TwoD_USB::Particle::area, nidas::dynld::raf::TwoD_USB::Particle::edgeTouch, nidas::dynld::raf::TwoD_USB::Particle::height, and nidas::dynld::raf::TwoD_USB::Particle::width.
Referenced by nidas::dynld::raf::TwoD_USB::countParticle().
bool TwoD_USB::acceptThisParticle2D (const Particle & p) const protected virtual inherited
References nidas::dynld::raf::TwoD_USB::_twoDAreaRejectRatio, nidas::dynld::raf::TwoD_USB::Particle::area, nidas::dynld::raf::TwoD_USB::Particle::edgeTouch, nidas::dynld::raf::TwoD_USB::Particle::height, and nidas::dynld::raf::TwoD_USB::Particle::width.
Referenced by nidas::dynld::raf::TwoD_USB::countParticle().
void DSMSensor::addCalFile (CalFile * val) inherited
Add a calibration file for this DSMSensor.
After this method is finished, DSMSensor will own the pointer, and will delete it in the DSMSensor destructor.
References nidas::core::DSMSensor::_calFiles, and nidas::core::CalFile::getName().
Referenced by nidas::core::DSMSensor::fromDOMElement().
void DSMSensor::addParameter (Parameter * val) inherited
Add a parameter to this DSMSensor.
DSMSensor will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::DSMSensor::_constParameters, nidas::core::DSMSensor::_parameters, and nidas::core::Parameter::getName().
Referenced by nidas::core::DSMSensor::fromDOMElement().
void nidas::core::DSMSensor::addSampleClient (SampleClient * c) throw () inline virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::addSampleClient().
Referenced by nidas::core::SamplePipeline::addSampleClient(), and nidas::core::SamplePipeline::addSampleClientForTag().
void nidas::core::DSMSensor::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
Referenced by nidas::core::SamplePipeline::addSampleClientForTag().
void DSMSensor::addSampleTag (SampleTag * val) throw (nidas::util::InvalidParameterException) virtual inherited
Add a SampleTag to this sensor.
DSMSensor will own the SampleTag. Throw an exception the DSMSensor cannot support the sample (bad rate, wrong number of variables, etc). Note that a SampleTag may be changed after it has been added. addSampleTag() is called when a sensor is initialized from the sensor catalog. The SampleTag may be modified later if it is overridden in the actual sensor entry. For this reason, it is wise to wait to scan the SampleTags of a DSMSensor in the validate(), init() or open() methods, which are invoked after fromDOMElement.
Reimplemented in nidas::dynld::raf::DSMAnalogSensor, nidas::dynld::DSC_A2DSensor, nidas::dynld::A2DSensor, nidas::dynld::raf::PSI9116_Sensor, nidas::dynld::iss::TiltSensor, nidas::dynld::isff::PropVane, nidas::dynld::TSI_CPC3772, nidas::dynld::GPS_NMEA_Serial, and nidas::dynld::GPS_Novatel_Serial.
References GET_DSM_ID, GET_SHORT_ID, nidas::util::Logger::getInstance(), nidas::util::Logger::log(), and LOG_WARNING.
Referenced by nidas::dynld::GPS_NMEA_Serial::addSampleTag(), nidas::dynld::TSI_CPC3772::addSampleTag(), nidas::dynld::isff::PropVane::addSampleTag(), nidas::dynld::iss::TiltSensor::addSampleTag(), nidas::dynld::raf::PSI9116_Sensor::addSampleTag(), nidas::dynld::A2DSensor::addSampleTag(), nidas::dynld::RawSampleService::connect(), and nidas::core::DSMSensor::fromDOMElement().
IODevice * TwoD_USB::buildIODevice () throw (nidas::util::IOException) virtual inherited
Factory method for an IODevice for this DSMSensor.
Must be implemented by derived classes.
Implements nidas::core::DSMSensor.
SampleScanner * TwoD_USB::buildSampleScanner () throw (nidas::util::InvalidParameterException) virtual inherited
Factory method for a SampleScanner for this DSMSensor.
Must be implemented by derived classes.
Implements nidas::core::DSMSensor.
void nidas::core::DSMSensor::calcStatistics (unsigned int periodUsec) inline inherited
Update the sensor sampling statistics.
Should be called every periodUsec by a user of this sensor.
Parameters
periodUsec Statistics period.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::calcStatistics().
Referenced by nidas::core::SensorHandler::calcStatistics().
void nidas::core::DSMSensor::clearBuffer () inline protected inherited
Clear the internal buffer.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::clearBuffer().
Referenced by nidas::dynld::raf::UHSAS_Serial::sendInitString().
void TwoD_USB::clearData () protected virtual inherited
Clear size_dist arrays.
References nidas::dynld::raf::TwoD_USB::_dead_time, nidas::dynld::raf::TwoD_USB::_recordsPerSecond, nidas::dynld::raf::TwoD_USB::_size_dist_1D, nidas::dynld::raf::TwoD_USB::_size_dist_2D, and nidas::dynld::raf::TwoD_USB::NumberOfDiodes().
Referenced by nidas::dynld::raf::TwoD_USB::init().
void TwoD_USB::close () throw (nidas::util::IOException) virtual inherited
close my associated device.
Reimplemented from nidas::core::DSMSensor.
References nidas::core::DSMSensor::close(), nidas::core::DerivedDataReader::getInstance(), and nidas::core::DerivedDataReader::removeClient().
void TwoD_USB::countParticle (const Particle & p, float resolutionUsec) protected virtual inherited
Look at particle stats/info and decide whether to accept or reject.
Parameters
p is the particle information.
resolutionUsec is the current probe clocking rate.
References nidas::dynld::raf::TwoD_USB::_overSizeCount_2D, nidas::dynld::raf::TwoD_USB::_rejected1D_Cntr, nidas::dynld::raf::TwoD_USB::_rejected2D_Cntr, nidas::dynld::raf::TwoD_USB::_size_dist_1D, nidas::dynld::raf::TwoD_USB::_size_dist_2D, nidas::dynld::raf::TwoD_USB::acceptThisParticle1D(), nidas::dynld::raf::TwoD_USB::acceptThisParticle2D(), nidas::util::LogContext::active(), nidas::util::endlog(), nidas::dynld::raf::TwoD_USB::Particle::height, LOG_VERBOSE, nidas::dynld::raf::TwoD_USB::NumberOfDiodes(), nidas::dynld::raf::stream_histogram(), and nidas::dynld::raf::TwoD_USB::Particle::width.
void TwoD_USB::createSamples (dsm_time_t nextTimeTag, std::list< const Sample * > & results) throw () protected virtual inherited
Send derived data and reset.
The process() method for image data is to build size-distribution histograms for 1 second of data and then send that.
Parameters
results is the output results.
nextTimeTag is the timetag of a sample that is past the end of the current histogram period. The end
References nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), and USECS_PER_SEC.
void DSMSensor::deleteLooper () static inherited
References nidas::core::DSMSensor::_looper, and nidas::core::DSMSensor::_looperMutex.
Referenced by nidas::core::DSMEngine::main().
virtual void nidas::core::DerivedDataClient::derivedDataNotify (const DerivedDataReader * s) throw () pure virtual inherited
Method called on a DerivedDataClient by the DerivedDataReader thread when a new packet of derived data has been received.
This method is called on the DerivedDataClients in the sequence that they registered with the DerivedDataReader. The implementation of this method in a client should run quickly, to reduce the delay in calling successive clients in the list.
Implemented in nidas::dynld::raf::CVIOutput.
Referenced by nidas::core::DerivedDataReader::notifyClients().
void nidas::core::DSMSensor::distributeRaw (const Sample * s) throw () inline inherited
Distribute a raw sample which has been read from my file descriptor in real time.
References nidas::core::DSMSensor::_rawSource, and nidas::core::SampleSourceSupport::distribute().
virtual void nidas::core::DSMSensor::executeXmlRpc (XmlRpc::XmlRpcValue & , XmlRpc::XmlRpcValue &) throw () inline virtual inherited
Method invoked when the DSMEngineIntf XmlRpcServer receives a "SensorAction" request, with a "device" string matching the string that this DSMSensor registers via DSMEngine::registerSensorWithXmlRpc(string,DSMServer*).
The default base class method does nothing.
Reimplemented in nidas::dynld::raf::DSMAnalogSensor, and nidas::dynld::raf::PSI9116_Sensor.
Referenced by nidas::core::DSMEngineIntf::SensorAction::execute().
std::string nidas::core::DSMSensor::expandString (const std::string & input) const inline inherited
Utility function to expand ${TOKEN} or $TOKEN fields in a string with their value from getTokenValue().
If curly brackets are not used, then the TOKEN should be delimited by a '/', a '.' or the end of string, e.g.: xxx/yyy/$ZZZ.dat
References nidas::core::DSMSensor::_dictionary, and nidas::core::Dictionary::expandString().
Referenced by nidas::core::DSMSensor::fromDOMElement(), and nidas::core::CalFile::open().
void nidas::core::DSMSensor::flush () throw () inline virtual inherited
Implementation of SampleClient::flush().
This is where a DSMSensor's process() method could send out any buffered results that might be ready.
Implements nidas::core::SampleClient.
Referenced by nidas::dynld::psql::PSQLProcessor::disconnect().
void DSMSensor::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual inherited
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
Reimplemented in nidas::core::SerialSensor, nidas::dynld::raf::DSMArincSensor, nidas::dynld::raf::IRIGSensor, nidas::dynld::A2DSensor, nidas::dynld::isff::PropVane, nidas::dynld::DSC_A2DSensor, nidas::dynld::Twins, nidas::dynld::raf::LamsSensor, and nidas::dynld::raf::Arinc_IRS.
References nidas::core::DSMSensor::_dictionary, nidas::core::DSMSensor::_rawSampleTag, nidas::core::DSMSensor::_rawSource, nidas::core::DSMSensor::_sampleTags, nidas::core::DSMSensor::addCalFile(), nidas::core::DSMSensor::addParameter(), nidas::core::SampleSourceSupport::addSampleTag(), nidas::core::DSMSensor::addSampleTag(), nidas::core::Parameter::createParameter(), nidas::core::DSMSensor::expandString(), nidas::core::SensorCatalog::find(), nidas::core::Parameter::FLOAT_PARAM, nidas::core::SampleTag::fromDOMElement(), nidas::core::CalFile::fromDOMElement(), nidas::core::DSMSensor::getApplyVariableConversions(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::DSMSensor::getClassName(), nidas::core::DSMSensor::getDefaultMode(), nidas::core::DSMSensor::getDSMConfig(), nidas::core::SampleTag::getDSMId(), nidas::core::DSMSensor::getFullSuffix(), nidas::core::SampleTag::getId(), nidas::core::DSMSensor::getId(), nidas::util::Logger::getInstance(), nidas::core::Parameter::getLength(), nidas::core::Parameter::getName(), nidas::core::DSMConfig::getName(), nidas::core::XDOMAttr::getName(), nidas::core::DSMSensor::getName(), nidas::core::Variable::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::Parameter::getNumericValue(), nidas::core::DSMConfig::getProject(), nidas::core::SampleTag::getRate(), nidas::core::SampleTag::getSampleId(), nidas::core::DSMSensor::getSampleTags(), nidas::core::Project::getSensorCatalog(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMSensor::getSite(), nidas::core::SampleTag::getSpSId(), nidas::core::DSMSensor::getStation(), nidas::core::DSMSensor::getSuffix(), nidas::core::Parameter::getType(), nidas::core::DSMSensor::getVariableIterator(), nidas::core::VariableIterator::hasNext(), nidas::core::Parameter::INT_PARAM, nidas::util::Logger::log(), LOG_WARNING, MSECS_PER_SEC, nidas::core::VariableIterator::next(), nidas::core::DSMSensor::setApplyVariableConversions(), nidas::core::DSMSensor::setCatalogName(), nidas::core::DSMSensor::setClassName(), nidas::core::DSMSensor::setDefaultMode(), nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setDeviceName(), nidas::core::SampleTag::setDSMConfig(), nidas::core::SampleTag::setDSMId(), nidas::core::SampleTag::setDSMSensor(), nidas::core::CalFile::setDSMSensor(), nidas::core::DSMSensor::setDuplicateIdOK(), nidas::core::DSMSensor::setHeight(), nidas::core::DSMSensor::setLagSecs(), nidas::core::DSMSensor::setLatency(), nidas::core::DSMSensor::setLocation(), nidas::core::SampleTag::setRate(), nidas::core::SampleTag::setSampleId(), nidas::core::SampleTag::setSensorId(), nidas::core::DSMSensor::setSensorId(), nidas::core::SampleTag::setStation(), nidas::core::DSMSensor::setStation(), nidas::core::SampleTag::setSuffix(), nidas::core::DSMSensor::setSuffix(), nidas::core::DSMSensor::setTimeoutMsecs(), nidas::core::DSMSensor::setTypeName(), and nidas::util::Exception::what().
Referenced by nidas::dynld::A2DSensor::fromDOMElement(), nidas::dynld::raf::DSMArincSensor::fromDOMElement(), nidas::core::CharacterSensor::fromDOMElement(), nidas::core::DSMConfig::sensorFromDOMElement(), and Document::updateVariable().
virtual bool nidas::core::DSMSensor::getApplyVariableConversions () const inline virtual inherited
References nidas::core::DSMSensor::_applyVariableConversions.
Referenced by nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::raf::DSMArincSensor::init(), and nidas::dynld::raf::SppSerial::validate().
size_t nidas::core::DSMSensor::getBadTimeTagCount () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getBadTimeTagCount().
Referenced by nidas::core::DSMSensor::printStatus().
virtual size_t nidas::core::DSMSensor::getBytesAvailable () const throw (nidas::util::IOException) inline virtual inherited
How many bytes are available to read on this sensor.
See Also
IODevice::getBytesAvailable().
References nidas::core::DSMSensor::_iodev, and nidas::core::IODevice::getBytesAvailable().
CalFile * DSMSensor::getCalFile (const std::string & name) inherited
Return a CalFile by its getName().
Will return NULL if not found.
References nidas::core::DSMSensor::_calFiles.
const std::map<std::string,CalFile*>& nidas::core::DSMSensor::getCalFiles () inline inherited
Return the collection of CalFiles, mapped by name.
References nidas::core::DSMSensor::_calFiles.
Referenced by A2DSensorItem::getCalFileName(), A2DSensorItem::getSerialNumberString(), AutoCalClient::readCalFile(), sensorTitle(), PConfig::showCalFiles(), and Document::updateSensor().
virtual const std::string& nidas::core::DSMSensor::getCatalogName () const inline virtual inherited
Fetch the name of the catalog entry for this sensor.
References nidas::core::DSMSensor::_catalogName.
Referenced by DSMItem::child(), Extract2D::countParticles(), parseOther(), nidas::core::DSMSensor::printStatus(), Extract2D::run(), sensorTitle(), and PConfig::showCalFiles().
virtual const std::string& nidas::core::DSMSensor::getClassName () const inline virtual inherited
Fetch the class name.
References nidas::core::DSMSensor::_className.
Referenced by DSMItem::child(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMSensor::getClassName(), parseAnalog(), parseOther(), nidas::core::DSMSensor::printStatus(), nidas::core::DSMConfig::sensorFromDOMElement(), sensorTitle(), Calibrator::setup(), PConfig::showAll(), PConfig::showCalFiles(), and PConfig::showSensorClasses().
const string DSMSensor::getClassName (const xercesc::DOMElement * node, const Project * project) throw (nidas::util::InvalidParameterException) static inherited
Crawl through the DOM tree for a DSMSensor to find the class name - scanning the catalog entry if necessary.
References nidas::core::XDOMElement::getAttributeValue(), and nidas::core::DSMSensor::getClassName().
int nidas::core::DSMSensor::getClientCount () const throw () inline virtual inherited
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::getClientCount().
virtual int nidas::core::DSMSensor::getDefaultMode () const inline virtual inherited
How do I want to be opened.
The user can ignore it if they want to.
Returns
one of O_RDONLY, O_WRONLY or O_RDWR.
References nidas::core::DSMSensor::_defaultMode.
Referenced by nidas::core::DSMSensor::fromDOMElement(), and nidas::core::SensorOpener::run().
float nidas::core::DSMSensor::getDepth () const inline inherited
Get sensor depth below ground.
Returns
Depth of sensor below ground, in meters.
References nidas::core::DSMSensor::_height.
const std::string& nidas::core::DSMSensor::getDepthString () const inline inherited
Get sensor depth below ground in a string.
Returns
Depth of sensor below ground, e.g. "5cm".
References nidas::core::DSMSensor::_depthString.
virtual const std::string& nidas::core::DSMSensor::getDeviceName () const inline virtual inherited
Fetch the name of the system device that the sensor is connected to.
References nidas::core::DSMSensor::_devname.
Referenced by nidas::core::SensorHandler::add(), nidas::core::CharacterSensor::buildIODevice(), nidas::core::SerialSensor::buildIODevice(), nidas::core::CharacterSensor::buildSampleScanner(), nidas::core::DSMSensor::close(), CounterClient::CounterClient(), nidas::core::DSMSensor::getName(), parseOther(), nidas::core::DSMSensor::printStatus(), AutoCalClient::readCalFile(), DSMItem::removeChild(), nidas::core::CharacterSensor::sendInitString(), nidas::core::DSMConfig::sensorFromDOMElement(), sensorTitle(), AutoCalClient::Setup(), PConfig::showCalFiles(), Document::updateSensor(), and nidas::core::DSMSensor::validate().
const Dictionary& nidas::core::DSMSensor::getDictionary () const inline inherited
References nidas::core::DSMSensor::_dictionary.
virtual int nidas::core::DSMSensor::getDriverTimeTagUsecs () const inline virtual inherited
References nidas::core::DSMSensor::_driverTimeTagUsecs.
Referenced by nidas::core::DriverSampleScanner::nextSample().
const DSMConfig* nidas::core::DSMSensor::getDSMConfig () const inline inherited
What DSMConfig am I associated with?
References nidas::core::DSMSensor::_dsm.
Referenced by CounterClient::CounterClient(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::VariableConverter::getDSMConfig(), nidas::core::DSMSensor::MyDictionary::getTokenValue(), nidas::core::DSMSensor::printStatusHeader(), nidas::core::DSMSensor::readSamples(), nidas::core::SampleTag::setDSMSensor(), and nidas::core::DSMSensor::validate().
unsigned int nidas::core::DSMSensor::getDSMId () const inline inherited
References nidas::core::DSMSensor::_id, and GET_DSM_ID.
Referenced by nidas::core::Site::findSensor(), Document::insertA2DVariable(), AutoCalClient::readCalFile(), nidas::core::DSMSensor::readSamples(), sensorTitle(), Calibrator::setup(), AutoCalClient::Setup(), PConfig::showAll(), PConfig::showSensorClasses(), nidas::core::Site::validate(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
const std::string & DSMSensor::getDSMName () const inherited
Fetch the DSM name.
References nidas::core::DSMSensor::_dsm, and nidas::core::DSMConfig::getName().
Referenced by nidas::core::DSMSensor::getName(), AutoCalClient::readCalFile(), and AutoCalClient::Setup().
bool nidas::core::DSMSensor::getDuplicateIdOK () const inline inherited
getDuplicateIdOK will be true if it is OK for samples from this sensor to have identical IDs to samples from another sensor.
That other sensor must also agree that dupicateIdOK are OK. This can be useful if one may not be certain of the device name, e.g. /dev/ttyUSB*, that the system will assign to a sensor may use, but there are identifiers in the data returned that allow one to sort things out. In general, getDuplicateID is false.
References nidas::core::DSMSensor::_duplicateIdOK.
Referenced by nidas::core::Site::validate(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
const std::string& nidas::core::DSMSensor::getFullSuffix () const inline inherited
Full sensor suffix, the concatenation of the sensor suffix, if any, and the height or depth string, if any.
The full sensor suffix are words 2 and 3 in the dot-separated name: variable[.sensor][.height][.site]
References nidas::core::DSMSensor::_fullSuffix.
Referenced by nidas::core::DSMSensor::fromDOMElement().
float nidas::core::DSMSensor::getHeight () const inline inherited
Get sensor height above ground.
Returns
Height of sensor above ground, in meters. Nan if unknown.
References nidas::core::DSMSensor::_height.
const std::string& nidas::core::DSMSensor::getHeightString () const inline inherited
Get sensor height above ground in a string.
Returns
Height of sensor above ground, e.g. "15m".
References nidas::core::DSMSensor::_heightString.
Referenced by nidas::core::DSMSensor::MyDictionary::getTokenValue(), ARLIngest::prepareHeaderIds(), and PConfig::showCalFiles().
dsm_sample_id_t nidas::core::DSMSensor::getId () const inline inherited
Get the various levels of the samples identification.
A sample tag ID is a 32-bit value comprised of four parts: 6-bit sample type id(not used by DSMSensor), a 10-bit DSM id, 16-bit sensor+sample ids.
References nidas::core::DSMSensor::_id, and GET_FULL_ID.
Referenced by CounterClient::CounterClient(), nidas::core::Site::findSensor(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), nidas::core::MessageStreamScanner::nextSampleSepEOM(), nidas::core::SampleTag::SampleTag(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
IODevice* nidas::core::DSMSensor::getIODevice () const inline protected inherited
References nidas::core::DSMSensor::_iodev.
virtual double nidas::core::DSMSensor::getLagSecs () const inline protected virtual inherited
Return the sampling lag for this sensor in seconds.
See getLagUsecs().
References nidas::core::DSMSensor::_lag, and USECS_PER_SEC.
virtual int nidas::core::DSMSensor::getLagUsecs () const inline protected virtual inherited
Return the sampling lag for this sensor in microseconds.
A positive lag means one should adjust the sample time tags for this sensor earlier in time to achieve a better estimate of the actual time to be associated for each sample. Derived classes can use this method in their process method to correct for inherent, constant, sampling lags of a sensor. A fixed sample lag, in fractional seconds, can be set for a sensor in the XML:
* <sensor>
*     <parameter name="lag" type = "float" value="0.186"/>
* </sensor>
*
The DSMSensor::fromDOM() method parses this parameter and sets the value of the lag.
References nidas::core::DSMSensor::_lag.
virtual float nidas::core::DSMSensor::getLatency () const inline virtual inherited
References nidas::core::DSMSensor::_latency.
const std::string & DSMSensor::getLocation () const inherited
Location string.
A DSMConfig also has a Location. If the location has not been set for this DSMSensor, then the location of the DSMConfig will be returned.
References nidas::core::DSMSensor::_dsm, nidas::core::DSMSensor::_location, and nidas::core::DSMConfig::getLocation().
Referenced by nidas::core::DSMSensor::printStatusHeader().
Looper * DSMSensor::getLooper () static protected inherited
Fetch a pointer to a static instance of a Looper thread.
Use this Looper for periodic callbacks, as for prompting, in support of a DSMSensor.
References nidas::core::DSMSensor::_looper, nidas::core::DSMSensor::_looperMutex, nidas::util::Logger::getInstance(), nidas::util::Thread::getPolicyString(), nidas::util::Logger::log(), LOG_WARNING, nidas::util::Thread::NU_THREAD_RR, nidas::util::Thread::setThreadScheduler(), and nidas::util::Exception::what().
Referenced by nidas::core::SerialSensor::startPrompting(), and nidas::core::SerialSensor::stopPrompting().
unsigned int nidas::core::DSMSensor::getMaxSampleLength () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getMaxSampleLength().
Referenced by nidas::core::DSMSensor::printStatus().
unsigned int nidas::core::DSMSensor::getMinSampleLength () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getMinSampleLength().
Referenced by nidas::core::DSMSensor::printStatus().
virtual std::string nidas::core::DSMSensor::getName () const inline virtual inherited
Return a name that should fully identify this sensor.
This name could be used in informative messages. The returned name has this format: dsmName:deviceName.
References nidas::core::DSMSensor::getDeviceName(), and nidas::core::DSMSensor::getDSMName().
Referenced by nidas::core::SensorHandler::add(), nidas::core::SamplePipeline::addSampleClient(), nidas::core::SerialSensor::buildSampleScanner(), nidas::dynld::psql::PSQLProcessor::connect(), nidas::dynld::raf::CVIProcessor::connect(), nidas::core::SamplePipeline::connect(), nidas::dynld::raf::DSMArincSensor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::SensorHandler::PolledDSMSensor::getName(), nidas::core::SensorHandler::incrementFullBufferReads(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::WxtSensor::init(), nidas::core::CharacterSensor::init(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::TwoD64_USB::init_parameters(), nidas::dynld::raf::TwoD_USB::init_parameters(), nidas::core::DSMSensor::printStatusHeader(), nidas::core::DSMSensor::readSamples(), nidas::core::SensorOpener::run(), nidas::dynld::WxtSensor::scanSample(), nidas::dynld::raf::UHSAS_Serial::sendInitString(), nidas::core::DSMConfig::sensorFromDOMElement(), PConfig::showAll(), nidas::core::CharacterSensor::startPrompting(), nidas::core::CharacterSensor::stopPrompting(), nidas::core::CharacterSensor::validate(), nidas::dynld::raf::SppSerial::validate(), nidas::core::Site::validate(), nidas::core::DSMSensor::validate(), nidas::core::DSMConfig::validateSensorAndSampleIds(), nidas::core::CharacterSensor::validateSscanfs(), and nidas::dynld::raf::UHSAS_Serial::~UHSAS_Serial().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
virtual const std::list<SampleTag*>& nidas::core::DSMSensor::getNonConstSampleTags () inline virtual inherited
We'll allow derived classes and calibration applications to change the SampleTags, so this method returns a list of non-constant SampleTags.
References nidas::core::DSMSensor::_sampleTags.
float nidas::core::DSMSensor::getObservedDataRate () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getObservedDataRate().
Referenced by nidas::core::DSMSensor::printStatus().
float nidas::core::DSMSensor::getObservedSamplingRate () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getObservedSamplingRate().
Referenced by nidas::core::DSMSensor::printStatus().
const Parameter * DSMSensor::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::DSMSensor::_parameters.
Referenced by PMSSensorItem::getSerialNumberString(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::WxtSensor::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::TwoD_USB::init_parameters(), Extract2D::run(), sensorTitle(), and nidas::dynld::raf::SppSerial::validate().
const std::list<const Parameter*>& nidas::core::DSMSensor::getParameters () const inline inherited
Get list of parameters.
References nidas::core::DSMSensor::_constParameters.
SampleSource* nidas::core::DSMSensor::getProcessedSampleSource () inline virtual inherited
Implementation of SampleSource::getProcessedSampleSource().
Return the SampleSource for processed samples from this DSMSensor.
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::RawSampleService::schedule().
SampleSource* nidas::core::DSMSensor::getRawSampleSource () inline virtual inherited
Implementation of SampleSource::getRawSampleSource().
Return the SampleSource for raw samples from this DSMSensor. A DSMSensor is only a SampleSource of raw samples when running in real-time, not during post-processing.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_rawSource.
Referenced by nidas::core::RemoteSerialConnection::close(), and nidas::dynld::RawSampleService::schedule().
const SampleTag* nidas::core::DSMSensor::getRawSampleTag () const inline inherited
Convenience function to get my one-and-only raw SampleTag().
Equivalent to: getRawSampleSource()->getSampleTags()->front()
References nidas::core::DSMSensor::_rawSampleTag.
Referenced by nidas::core::SamplePipeline::addSampleClient(), nidas::core::SamplePipeline::addSampleClientForTag(), nidas::dynld::RawSampleService::connect(), nidas::dynld::RawSampleService::fromDOMElement(), nidas::dynld::raf::SyncServer::initSensors(), nidas::core::SamplePipeline::removeSampleClient(), nidas::core::SamplePipeline::removeSampleClientForTag(), StatsProcess::run(), DataPrep::run(), DataStats::run(), DataDump::run(), and Calibrator::setup().
virtual int nidas::core::DSMSensor::getReadFd () const inline virtual inherited
References nidas::core::DSMSensor::_iodev, and nidas::core::IODevice::getReadFd().
Referenced by nidas::core::SensorHandler::PolledDSMSensor::getFd().
float nidas::dynld::raf::TwoD_USB::getResolution () const inline inherited
The probe resolution in meters.
Probe resolution is also the diameter of the each diode. Typical values are 25 for the 2DC and 200 micrometers for the 2DP.
Returns
The probe resolution in meters.
Referenced by nidas::dynld::raf::TwoD_USB::Tap2DToTAS(), and nidas::dynld::raf::TwoD_USB::TASToTap2D().
unsigned int nidas::dynld::raf::TwoD_USB::getResolutionMicron () const inline inherited
The probe resolution in micrometers.
Probe resolution is also the diameter of the each diode. Typical values are 25 for the 2DC and 200 micrometers for the 2DP.
Returns
The probe resolution in micrometers.
SampleScanner* nidas::core::DSMSensor::getSampleScanner () const inline protected inherited
References nidas::core::DSMSensor::_scanner.
Referenced by nidas::core::CharacterSensor::getNullTerminated().
const SampleStats& nidas::core::DSMSensor::getSampleStats () const inline virtual inherited
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::getSampleStats().
SampleTagIterator nidas::core::DSMSensor::getSampleTagIterator () const inline virtual inherited
Implements nidas::core::SampleSource.
Referenced by A2DSensorItem::child(), nidas::core::SamplePipeline::connect(), CounterClient::CounterClient(), nidas::core::SamplePipeline::disconnect(), nidas::core::CharacterSensor::doesAsciiSscanfs(), nidas::core::Site::findSensor(), A2DSensorItem::getA2DTempSuffix(), Document::getAvailableA2DChannels(), nidas::dynld::WxtSensor::init(), parseAnalog(), parseOther(), A2DSensorItem::refreshChildItems(), StatsProcess::run(), DataPrep::run(), A2DSensorItem::setNidasA2DTempSuffix(), PConfig::showAll(), nidas::core::DSMSensor::toDOMParent(), and Document::validateSampleInfo().
std::list<const SampleTag*> nidas::core::DSMSensor::getSampleTags () const inline virtual inherited
Implementation of SampleSource::getSampleTags().
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::getSampleTags().
Referenced by nidas::dynld::psql::PSQLProcessor::connect(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::SampleTagIterator::hasNext(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::core::CharacterSensor::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::TwoD64_USB::init_parameters(), SensorItem::removeChild(), A2DSensorItem::removeChild(), nidas::dynld::raf::SyncRecordSource::selectVariablesFromSensor(), AutoCalClient::Setup(), PConfig::showCalFiles(), nidas::core::CharacterSensor::validate(), nidas::dynld::raf::SppSerial::validate(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
std::list<SampleTag*>& nidas::core::DSMSensor::getSampleTags () inline inherited
Non-const method to get a list of non-const pointers to SampleTags.
References nidas::core::DSMSensor::_sampleTags.
unsigned int nidas::core::DSMSensor::getSensorId () const inline inherited
References nidas::core::DSMSensor::_id, and GET_SPS_ID.
Referenced by nidas::core::Site::findSensor(), nidas::core::DSMSensor::fromDOMElement(), Document::insertA2DVariable(), ARLIngest::prepareHeaderIds(), AutoCalClient::readCalFile(), nidas::core::DSMSensor::readSamples(), sensorTitle(), Calibrator::setup(), AutoCalClient::Setup(), PConfig::showAll(), PConfig::showSensorClasses(), Document::updateSensor(), nidas::core::Site::validate(), nidas::core::DSMSensor::validate(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
const Site * DSMSensor::getSite () const inherited
What Site am I associated with?
References nidas::core::DSMSensor::_dsm, and nidas::core::DSMConfig::getSite().
Referenced by nidas::core::DSMSensor::fromDOMElement(), Document::insertA2DVariable(), and Document::updateVariable().
int nidas::core::DSMSensor::getStation () const inline inherited
References nidas::core::DSMSensor::_station.
Referenced by nidas::core::DSMSensor::fromDOMElement().
const std::string& nidas::core::DSMSensor::getSuffix () const inline inherited
Sensor suffix, which is added to variable names.
It is only necessary to have a sensor suffix to make variable names unique. For example, if there are multiple sensors at the same height, with common variable names, then one can use a sensor suffix to make unique names. The sensor suffix is the second dot-separated word in a variable name, where only the first word is required: variable[.sensor][.height][.site]
References nidas::core::DSMSensor::_suffix.
Referenced by Extract2D::countParticles(), nidas::core::DSMSensor::fromDOMElement(), VariableItem::getBaseName(), nidas::core::DSMSensor::MyDictionary::getTokenValue(), Extract2D::run(), sensorTitle(), nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setHeight(), and Document::updateSensor().
int nidas::dynld::raf::TwoD_USB::getTASRate () const inline inherited
Referenced by nidas::dynld::raf::TwoD64_USB::init_parameters().
int nidas::core::DSMSensor::getTimeoutCount () const inline inherited
References nidas::core::DSMSensor::_nTimeouts.
Referenced by nidas::core::DSMSensor::close().
virtual int nidas::core::DSMSensor::getTimeoutMsecs () const inline virtual inherited
References nidas::core::DSMSensor::_timeoutMsecs.
Referenced by nidas::core::RemoteSerialConnection::close(), nidas::core::SensorHandler::PolledDSMSensor::getTimeoutMsecs(), and nidas::core::RemoteSerialConnection::setSensor().
bool nidas::core::DSMSensor::getTokenValue (const std::string & token, std::string & value) const inline inherited
Implement a lookup for tokens that I know about, like $HEIGHT.
For other tokens, call getDSMConfig()->getTokenValue(token,value);
References nidas::core::DSMSensor::_dictionary, and nidas::core::DSMSensor::MyDictionary::getTokenValue().
virtual const std::string& nidas::core::DSMSensor::getTypeName (void) const inline virtual inherited
Get the type name of this sensor.
References nidas::core::DSMSensor::_typeName.
VariableIterator DSMSensor::getVariableIterator () const inherited
Referenced by nidas::core::DSMSensor::fromDOMElement(), DataPrep::matchVariables(), and nidas::core::Site::validate().
virtual int nidas::core::DSMSensor::getWriteFd () const inline virtual inherited
References nidas::core::DSMSensor::_iodev, and nidas::core::IODevice::getWriteFd().
Referenced by main().
void nidas::core::DSMSensor::incrementTimeoutCount () inline inherited
References nidas::core::DSMSensor::_nTimeouts.
Referenced by nidas::core::SensorOpener::run().
void TwoD_USB::init () throw (nidas::util::InvalidParameterException) virtual inherited
Called by post-processing code.
Reimplemented from nidas::core::DSMSensor.
References nidas::dynld::raf::TwoD_USB::_1dcID, nidas::dynld::raf::TwoD_USB::_2dcID, nidas::dynld::raf::TwoD_USB::_nextraValues, nidas::dynld::raf::TwoD_USB::_prevTime, nidas::dynld::raf::TwoD_USB::_size_dist_1D, nidas::dynld::raf::TwoD_USB::_size_dist_2D, nidas::dynld::raf::TwoD_USB::_twoDAreaRejectRatio, nidas::dynld::raf::TwoD_USB::clearData(), nidas::core::SampleTag::getId(), nidas::core::Variable::getName(), nidas::core::Parameter::getNumericValue(), nidas::core::DSMSensor::getParameter(), nidas::core::DSMSensor::getSampleTags(), nidas::core::SampleTag::getVariables(), nidas::core::DSMSensor::init(), nidas::dynld::raf::TwoD_USB::init_parameters(), and nidas::dynld::raf::TwoD_USB::NumberOfDiodes().
void TwoD_USB::init_parameters () throw (nidas::util::InvalidParameterException) protected virtual inherited
Initialize parameters for real-time and post-processing.
Reimplemented in nidas::dynld::raf::TwoD64_USB.
References nidas::dynld::raf::TwoD_USB::_resolutionMeters, nidas::dynld::raf::TwoD_USB::_resolutionMicron, nidas::core::DSMSensor::getName(), nidas::core::Parameter::getNumericValue(), nidas::core::DSMSensor::getParameter(), and nidas::dynld::raf::TwoD_USB::setTASRate().
Referenced by nidas::dynld::raf::TwoD_USB::init(), and nidas::dynld::raf::TwoD64_USB::init_parameters().
virtual void nidas::core::DSMSensor::ioctl (int request, void * buf, size_t len) throw (nidas::util::IOException) inline virtual inherited
Perform an ioctl on the device.
request is an integer value which must be supported by the device. Normally this is a value from a header file for the device.
References nidas::core::DSMSensor::_iodev, nidas::core::IODevice::ioctl(), and len.
virtual Sample* nidas::core::DSMSensor::nextSample () inline virtual inherited
Extract the next sample from the buffer.
Returns a null pointer if there are no samples left in the buffer.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::nextSample().
Referenced by nidas::core::DSMSensor::readSamples(), and nidas::dynld::raf::UHSAS_Serial::sendInitString().
virtual int nidas::dynld::raf::TwoD32_USB::NumberOfDiodes () const inline virtual
Number of diodes in the probe array.
This is also the bits-per-slice value. Traditional 2D probes have 32 diodes, the HVPS has 128 and the Fast2DC has 64.
Returns
the number of bits per data slice.
Implements nidas::dynld::raf::TwoD_USB.
void TwoD_USB::open (int flags) throw (nidas::util::IOException, nidas::util::InvalidParameterException) virtual inherited
open the sensor and perform any intialization to the driver.
Reimplemented from nidas::core::DSMSensor.
References nidas::core::DerivedDataReader::addClient(), nidas::core::DerivedDataReader::getInstance(), nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_WARNING, nidas::core::DSMSensor::open(), and USB2D_SET_SOR_RATE.
void TwoD_USB::printStatus (std::ostream & ostr) throw () virtual inherited
Reimplemented from nidas::core::DSMSensor.
References nidas::util::Logger::getInstance(), nidas::util::getSystemTime(), nidas::util::Logger::log(), LOG_ERR, usb_twod_stats::lostImages, usb_twod_stats::lostSORs, usb_twod_stats::lostTASs, usb_twod_stats::numImages, nidas::core::DSMSensor::printStatus(), usb_twod_stats::urbErrors, USB2D_GET_STATUS, USECS_PER_SEC, and nidas::util::Exception::what().
void DSMSensor::printStatusHeader (std::ostream & ostr) throw () inherited
References nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getLocation(), nidas::core::DSMSensor::getName(), and nidas::core::DSMSensor::zebra.
Referenced by nidas::core::DSMEngineStat::run().
void DSMSensor::printStatusTrailer (std::ostream & ostr) throw () inherited
Referenced by nidas::core::DSMEngineStat::run().
bool TwoD32_USB::process (const Sample * , std::list< const Sample * > & result) throw () virtual
Apply further necessary processing to a raw sample from this DSMSensor.
Return the resultant sample(s) in result. The default implementation of process() simply puts the input Sample into result.
Implements nidas::core::DSMSensor.
References bigEndian, nidas::util::EndianConverter::int32Value(), and TWOD_SOR_TYPE.
bool TwoD32_USB::processImage (const Sample * samp, std::list< const Sample * > & results, int stype) throw () protected
References bigEndian, nidas::util::UTime::format(), nidas::util::EndianConverter::int32Value(), _Tap2D_v2::ntap, TWOD_IMG_TYPE, TWOD_IMGv2_TYPE, and WLOG.
void TwoD_USB::processParticleSlice (Particle & p, const unsigned char * slice) protected virtual inherited
Process a slice and update the Particle struct area, edgeTouch, width and height.
Parameters
p is particle info class.
slice is a pointer to the start of the slice, in big-endian and uncomplemented.
References nidas::dynld::raf::TwoD_USB::Particle::area, nidas::dynld::raf::TwoD_USB::Particle::edgeTouch, nidas::dynld::raf::TwoD_USB::Particle::height, nidas::dynld::raf::TwoD_USB::NumberOfDiodes(), and nidas::dynld::raf::TwoD_USB::Particle::width.
virtual size_t nidas::core::DSMSensor::read (void * buf, size_t len) throw (nidas::util::IOException) inline virtual inherited
Read from the device (duh).
Behaves like the read(2) system call, without a file descriptor argument, and with an IOException.
References nidas::core::DSMSensor::_iodev, len, and nidas::core::IODevice::read().
Referenced by main().
virtual size_t nidas::core::DSMSensor::read (void * buf, size_t len, int msecTimeout) throw (nidas::util::IOException) inline virtual inherited
Read from the device with a timeout.
References nidas::core::DSMSensor::_iodev, len, and nidas::core::IODevice::read().
bool nidas::core::DSMSensor::readBuffer () throw (nidas::util::IOException) inline protected inherited
Read into my SampleScanner's buffer.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::readBuffer().
Referenced by nidas::core::DSMSensor::readSamples(), and nidas::dynld::raf::UHSAS_Serial::sendInitString().
bool nidas::core::DSMSensor::readBuffer (int msecTimeout) throw (nidas::util::IOException) inline protected inherited
Read into my SampleScanner's buffer.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::readBuffer().
bool DSMSensor::readSamples () throw (nidas::util::IOException) virtual inherited
Read samples from my associated file descriptor, and distribute() them to my RawSampleClient's.
This method is called by SensorHander, when select/poll indicates that data is available on the file descriptor returned by getReadFd(). This is a convienence method which does a readBuffer() to read available data from the DSMSensor into a buffer, and then repeatedly calls nextSample() to extract all samples out of that buffer.
References nidas::core::DSMSensor::_rawSource, nidas::core::SampleSourceSupport::distribute(), DLOG, nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getDSMId(), nidas::core::Project::getName(), nidas::core::DSMSensor::getName(), nidas::core::DSMConfig::getProject(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMSensor::nextSample(), and nidas::core::DSMSensor::readBuffer().
bool DSMSensor::receive (const Sample * s) throw () virtual inherited
A DSMSensor can be used as a SampleClient, meaning it receives its own raw samples.
In real-time operations, a DSMSensor can be added as a raw SampleClient of itself, using addRawSampleClient(). In post-processing, a DSMSensor typically receives samples with its own sample id from a SampleSorter. receive() then applies further processing via the process() method.
Implements nidas::core::SampleClient.
void DSMSensor::removeCalFiles () inherited
Remove all CalFiles.
References nidas::core::DSMSensor::_calFiles.
Referenced by Calibrator::setup(), and nidas::core::DSMSensor::~DSMSensor().
void nidas::core::DSMSensor::removeSampleClient (SampleClient * c) throw () inline virtual inherited
Remove a SampleClient from this SampleSource This will also remove a SampleClient if it has been added with addSampleClientForTag().
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::removeSampleClient().
Referenced by nidas::core::SamplePipeline::removeSampleClient(), and nidas::core::SamplePipeline::removeSampleClientForTag().
void nidas::core::DSMSensor::removeSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
Referenced by nidas::core::SamplePipeline::removeSampleClientForTag().
void DSMSensor::removeSampleTag (SampleTag * val) throw () virtual inherited
Remove val from the list of SampleTags, and delete it.
Referenced by Document::insertA2DVariable(), SensorItem::removeChild(), and A2DSensorItem::removeChild().
virtual bool nidas::core::DSMSensor::reopenOnIOException () const inline virtual inherited
Whether to reopen this sensor on an IOException.
The base method returns true. Over-ride if a reopen should not be attempted.
void TwoD_USB::saveBuffer (const unsigned char * cp, const unsigned char * eod) protected inherited
In case of mis-aligned data, we may need to save some bytes at the end of an image block to pre-pend to the next block.
Parameters
cp,: Pointer to next byte in the image block to be saved.
eod,: Pointer to one-past-the-end of the image block. If cp is equal to eod, then nothing is saved, and this function does not need to be called.
References nidas::dynld::raf::TwoD_USB::_saveBuffer, nidas::dynld::raf::TwoD_USB::_savedAlloc, and nidas::dynld::raf::TwoD_USB::_savedBytes.
void TwoD_USB::sendTrueAirspeed (float tas) throw (nidas::util::IOException) protected virtual inherited
Encode and send the true airspeed to the USB driver, which will in turn send it to the probe.
References nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_WARNING, and USB2D_SET_TAS.
virtual void nidas::core::DSMSensor::setApplyVariableConversions (bool val) inline virtual inherited
References nidas::core::DSMSensor::_applyVariableConversions.
Referenced by nidas::core::DSMSensor::fromDOMElement().
virtual void nidas::core::DSMSensor::setCatalogName (const std::string & val) inline virtual inherited
Set the name of the catalog entry for this sensor.
References nidas::core::DSMSensor::_catalogName.
Referenced by nidas::core::DSMSensor::fromDOMElement().
virtual void nidas::core::DSMSensor::setClassName (const std::string & val) inline virtual inherited
Set the class name.
In the usual usage this method is not used, and getClassName() is over-ridden in a derived class to return a constant string.
References nidas::core::DSMSensor::_className.
Referenced by nidas::core::DSMSensor::fromDOMElement().
virtual void nidas::core::DSMSensor::setDefaultMode (int val) inline virtual inherited
References nidas::core::DSMSensor::_defaultMode.
Referenced by nidas::core::DSMSensor::fromDOMElement(), nidas::core::SerialSensor::SerialSensor(), and nidas::dynld::raf::TwoD_USB::TwoD_USB().
void DSMSensor::setDepth (const std::string & val) inherited
Set sensor depth below ground via a string which is added to variable names.
Parameters
val String containing sensor below and units in meters (m) or centimeters(cm), e.g. "5cm". This depth string is added to all the variable names, with a "." separator, so that a variable "Tsoil" for this sensor becomes "Tsoil.5cm".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::floatNAN, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
void DSMSensor::setDepth (float val) inherited
Set sensor depth below ground.
Parameters
val depth below ground, in meters. The depth is converted to centimeters and is added to all the variable names, with a "." separator, so that a variable "Tsoil" for this sensor becomes "Tsoil.5cm".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
virtual void nidas::core::DSMSensor::setDeviceName (const std::string & val) inline virtual inherited
Set the name of the system device that the sensor is connected to.
Parameters
val Name of device, e.g. "/dev/xxx0".
References nidas::core::DSMSensor::_devname.
Referenced by nidas::core::DSMSensor::fromDOMElement(), and main().
virtual void nidas::core::DSMSensor::setDriverTimeTagUsecs (int val) inline virtual inherited
References nidas::core::DSMSensor::_driverTimeTagUsecs.
Referenced by nidas::dynld::raf::DSMArincSensor::buildIODevice().
void DSMSensor::setDSMConfig (const DSMConfig * val) inherited
Set the DSMConfig for this sensor.
References nidas::core::DSMSensor::_dsm, nidas::core::DSMConfig::getId(), and nidas::core::DSMSensor::setDSMId().
Referenced by nidas::core::DSMConfig::sensorFromDOMElement(), and nidas::core::SensorHandler::~SensorHandler().
void nidas::core::DSMSensor::setDSMId (unsigned int val) inline inherited
References nidas::core::DSMSensor::_id, and SET_DSM_ID.
Referenced by nidas::core::DSMSensor::setDSMConfig().
void nidas::core::DSMSensor::setDuplicateIdOK (bool val) inline inherited
Set the duplicate ID attribute of this DSMSensor.
References nidas::core::DSMSensor::_duplicateIdOK.
Referenced by nidas::core::DSMSensor::fromDOMElement().
void nidas::core::DSMSensor::setFullSuffix (const std::string & val) inline protected inherited
References nidas::core::DSMSensor::_fullSuffix.
Referenced by nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setHeight(), and nidas::core::DSMSensor::setSuffix().
void DSMSensor::setHeight (const std::string & val) inherited
Set sensor height above ground via a string which is added to variable names.
Parameters
val String containing sensor height and units in meters (m) or centimeters(cm), e.g. "15m". This height string is added to all the variable names, with a "." separator, so that a variable "u" for this sensor becomes "u.15m".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::floatNAN, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
void DSMSensor::setHeight (float val) inherited
Set sensor height above ground.
Parameters
val height above ground, in meters. The height is added to all the variable names, with a "." separator, so that a variable "u" for this sensor becomes "u.15m".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
void nidas::core::DSMSensor::setId (dsm_sample_id_t val) inline inherited
Set the various levels of the sensor identification.
A sensor ID is a 32-bit value comprised of four parts: 6-bit sample type id (not used by DSMSensor), 10-bit DSM id, and 16-bit sensor+sample ids.
References nidas::core::DSMSensor::_id, and SET_FULL_ID.
void nidas::core::DSMSensor::setIODevice (IODevice * val) inline inherited
Set the IODevice for this sensor.
DSMSensor then owns the pointer and will delete it in its destructor.
References nidas::core::DSMSensor::_iodev.
virtual void nidas::core::DSMSensor::setLagSecs (double val) inline protected virtual inherited
Set the sampling lag for this sensor in seconds.
This lag should then used to correct the timetags of the processed samples in the process() method of derived classes. Note that this lag is not used to alter the timetags of the raw samples. Raw samples are saved with the un-altered timetag that was determined at the moment they were sampled.
The lag is stored as a signed integer of microseconds, so lags should be between += 2147 seconds. No warning or exception is given if the value exceeds that limit. If your lag is greater than that I suggest you junk your sensor! A positive lag means one should adjust the sample time tags for this sensor earlier in time to achieve a better estimate of the actual time to be associated for each sample. A fixed sample lag, in fractional seconds, can be set for a sensor in the XML:
* <parameter name="lag" type = "float" value="0.186"/>
*
The DSMSensor::fromDOM() method parses this parameter and calls this method to set the lag. process() methods in derived classes must apply this lag value. The DSMSensor base class does not adjust time tags of processed samples.
References nidas::core::DSMSensor::_lag, and USECS_PER_SEC.
Referenced by nidas::core::DSMSensor::fromDOMElement().
virtual void nidas::core::DSMSensor::setLatency (float val) throw (nidas::util::InvalidParameterException) inline virtual inherited
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
Setting a latency of 1/10 sec means buffer data in the driver for a 1/10 sec, then send the data to user space. Generally it should be set before doing a sensor open().
Parameters
val Latency, in seconds.
References nidas::core::DSMSensor::_latency.
Referenced by nidas::dynld::A2DSensor::A2DSensor(), and nidas::core::DSMSensor::fromDOMElement().
void nidas::core::DSMSensor::setLocation (const std::string & val) inline inherited
References nidas::core::DSMSensor::_location.
Referenced by nidas::core::DSMSensor::fromDOMElement().
void nidas::core::DSMSensor::setSampleScanner (SampleScanner * val) inline inherited
Set the SampleScanner for this sensor.
DSMSensor then owns the pointer and will delete it in its destructor.
References nidas::core::DSMSensor::_scanner.
void nidas::core::DSMSensor::setSensorId (unsigned int val) inline inherited
References nidas::core::DSMSensor::_id, and SET_SPS_ID.
Referenced by nidas::core::DSMSensor::fromDOMElement().
void DSMSensor::setStation (int val) inherited
References nidas::core::DSMSensor::_sampleTags, nidas::core::DSMSensor::_station, and nidas::core::SampleTag::setStation().
Referenced by nidas::core::DSMSensor::fromDOMElement().
void DSMSensor::setSuffix (const std::string & val) inherited
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_heightString, nidas::core::DSMSensor::_suffix, and nidas::core::DSMSensor::setFullSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
void nidas::dynld::raf::TwoD_USB::setTASRate (int val) inline inherited
Referenced by nidas::dynld::raf::TwoD_USB::init_parameters().
virtual void nidas::core::DSMSensor::setTimeoutMsecs (int val) inline virtual inherited
Set the sensor timeout value in milliseconds.
A value of 0 means no timeout (e.g. infinite). If no data is received for this period, then the sensor is closed, and re-opened. For efficiency reasons, the system may not actually detect a sensor timeout of less than 1 second, so setting it to less than 1000 milliseconds will likely not reduce the time before a sensor timeout is detected.
References nidas::core::DSMSensor::_timeoutMsecs.
Referenced by nidas::core::RemoteSerialConnection::close(), and nidas::core::DSMSensor::fromDOMElement().
virtual void nidas::core::DSMSensor::setTypeName (const std::string & val) inline virtual inherited
Set the type name of this sensor, e.g.
: "ACME Model 99 Mach7 Particle Disambiguator". This is meant for descriptive purposes only, and is not meant to change the behavior of a sensor object.
References nidas::core::DSMSensor::_typeName.
Referenced by nidas::core::DSMSensor::fromDOMElement().
void TwoD_USB::setupBuffer (const unsigned char ** cp, const unsigned char ** eod) protected inherited
Derived Classes should call this at the beginning of processing an image block.
If bytes were saved from the end of the last image block, then the pointers are adjusted to point to a new buffer that contains the saved and the new data.
Parameters
cp,: Pointer to pointer of first slice in the new image block to be processed, after the TAS word.
eod,: Pointer to pointer to one-past-the-end of the image block.
References nidas::dynld::raf::TwoD_USB::_saveBuffer, nidas::dynld::raf::TwoD_USB::_savedAlloc, and nidas::dynld::raf::TwoD_USB::_savedBytes.
float TwoD_USB::Tap2DToTAS (const Tap2D * t2d) const virtual inherited
Reverse the true airspeed encoding.
Used to extract TAS from recorded records. The *v1 method is for the first generation TAS clock, the second generation gives finer resolution (07/01/2009). Second generation chip is an Analog Devices AD5255.
Parameters
t2d the Tap2D to extract from.
the probe frequency.
Returns
true airspeed in m/s.
Todo:
2DP is going to need an extra divide by 10 at the end.
References _Tap2D_v2::div10, nidas::dynld::raf::TwoD_USB::getResolution(), and _Tap2D_v2::ntap.
float TwoD_USB::Tap2DToTAS (const Tap2Dv1 * t2d) const virtual inherited
The first generation used the Maxim 5418 chip.
This is for legacy data (PACDEX through VOCALS).
References _Tap2D_v1::div10, nidas::dynld::raf::TwoD_USB::getResolution(), and _Tap2D_v1::ntap.
int TwoD_USB::TASToTap2D (Tap2D * t2d, float tas) inherited
Build the struct above from the true airspeed (in m/s).
Encodes for Analog Devices AD5255.
Parameters
t2d the Tap2D to be filled
tas the true airspeed in m/s
References nidas::dynld::raf::TwoD_USB::DefaultTrueAirspeed, _Tap2D_v2::div10, nidas::dynld::raf::TwoD_USB::getResolution(), and _Tap2D_v2::ntap.
virtual void nidas::dynld::raf::TwoD_USB::throw () virtual inherited
xercesc::DOMElement * DSMSensor::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented from nidas::core::DOMable.
Referenced by nidas::core::DSMSensor::toDOMParent().
xercesc::DOMElement * DSMSensor::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented from nidas::core::DOMable.
References nidas::core::DOMable::getNamespaceURI(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::core::DSMSensor::toDOMElement(), and nidas::core::SampleTag::toDOMParent().
Referenced by nidas::core::DSMConfig::toDOMElement().
void DSMSensor::validate () throw (nidas::util::InvalidParameterException) virtual inherited
validate() is called once on a DSMSensor after it has been configured, but before open() or init() are called.
Reimplemented in nidas::dynld::isff::SonicAnemometer, nidas::dynld::isff::WisardMote, nidas::dynld::raf::SppSerial, nidas::core::CharacterSensor, nidas::dynld::DSC_FreqCounter, nidas::dynld::DSC_PulseCounter, nidas::dynld::isff::NCAR_TRH, nidas::dynld::isff::CSI_CRX_Binary, nidas::dynld::IEEE_Float, nidas::dynld::isff::CU_Coldwire, nidas::dynld::isff::Licor7500, nidas::dynld::raf::SPP200_Serial, nidas::dynld::raf::BCPD_Serial, nidas::dynld::raf::CDP_Serial, nidas::dynld::raf::SPP100_Serial, and nidas::dynld::raf::SPP300_Serial.
References nidas::core::DSMSensor::getDeviceName(), nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getName(), and nidas::core::DSMSensor::getSensorId().
Referenced by Document::addSensor(), nidas::dynld::DSC_PulseCounter::validate(), nidas::dynld::DSC_FreqCounter::validate(), nidas::core::CharacterSensor::validate(), and nidas::core::DSMConfig::validate().
virtual size_t nidas::core::DSMSensor::write (const void * buf, size_t len) throw (nidas::util::IOException) inline virtual inherited
Write to the device (duh).
Behaves like write(2) system call, without a file descriptor argument, and with an IOException.
References nidas::core::DSMSensor::_iodev, len, and nidas::core::IODevice::write().
Referenced by nidas::dynld::raf::UHSAS_Serial::sendInitString(), and nidas::core::CharacterSensor::sendInitString().
Member Data Documentation
dsm_sample_id_t nidas::dynld::raf::TwoD_USB::_1dcID protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::init().
dsm_sample_id_t nidas::dynld::raf::TwoD_USB::_2dcID protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::init().
const unsigned char TwoD32_USB::_blankString = {0xff, 0xff, 0xff, 0xff} static protected
float nidas::dynld::raf::TwoD_USB::_dead_time protected inherited
Amount of time probe was inactive or amount of time consumed by rejected particles.
nimbus will then subtract this deadtime out of the sample volume.
Referenced by nidas::dynld::raf::TwoD_USB::clearData().
long long nidas::dynld::raf::TwoD_USB::_histoEndTime protected inherited
The end time of the current histogram.
long long nidas::dynld::raf::TwoD_USB::_lastStatusTime protected inherited
Time of last printStatus.
unsigned int nidas::dynld::raf::TwoD_USB::_misAligned protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::~TwoD_USB().
int nidas::dynld::raf::TwoD_USB::_nextraValues protected inherited
If XML file has a variable RPS (records per second) defined, then _nextravalues will be 2, otherwise 1.
This keeps us from having to retrofit old XML files.
See Also
init()
process()
Referenced by nidas::dynld::raf::TwoD_USB::init().
unsigned int nidas::dynld::raf::TwoD_USB::_numImages protected inherited
Number of image blocks processed by driver at time of last printStatus.
const unsigned char TwoD32_USB::_overldString = {0x55, 0xaa} static protected
unsigned int nidas::dynld::raf::TwoD_USB::_overLoadSliceCount protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::~TwoD_USB().
unsigned int nidas::dynld::raf::TwoD_USB::_overSizeCount_2D protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::countParticle(), and nidas::dynld::raf::TwoD_USB::~TwoD_USB().
Particle nidas::dynld::raf::TwoD_USB::_particle protected inherited
Current particle information.
This is in here, since a particle can cross samples/records.
dsm_time_t nidas::dynld::raf::TwoD_USB::_prevTime protected inherited
Time from previous record.
Time belongs to end of record it came with, or start of the next record. Save it so we can use it as a start.
Referenced by nidas::dynld::raf::TwoD_USB::init().
unsigned int nidas::dynld::raf::TwoD_USB::_recordsPerSecond protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::clearData().
unsigned int nidas::dynld::raf::TwoD_USB::_rejected1D_Cntr protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::countParticle(), and nidas::dynld::raf::TwoD_USB::~TwoD_USB().
unsigned int nidas::dynld::raf::TwoD_USB::_rejected2D_Cntr protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::countParticle(), and nidas::dynld::raf::TwoD_USB::~TwoD_USB().
float nidas::dynld::raf::TwoD_USB::_resolutionMeters protected inherited
Probe resolution in meters.
Acquired from XML config file.
Referenced by nidas::dynld::raf::TwoD_USB::init_parameters().
unsigned int nidas::dynld::raf::TwoD_USB::_resolutionMicron protected inherited
Probe resolution in micrometers.
Acquired from XML config file.
Referenced by nidas::dynld::raf::TwoD_USB::init_parameters().
unsigned char* nidas::dynld::raf::TwoD_USB::_saveBuffer protected inherited
The saved buffer.
Referenced by nidas::dynld::raf::TwoD_USB::saveBuffer(), nidas::dynld::raf::TwoD_USB::setupBuffer(), and nidas::dynld::raf::TwoD_USB::~TwoD_USB().
int nidas::dynld::raf::TwoD_USB::_savedAlloc protected inherited
Size of the saved buffer.
Referenced by nidas::dynld::raf::TwoD_USB::saveBuffer(), and nidas::dynld::raf::TwoD_USB::setupBuffer().
int nidas::dynld::raf::TwoD_USB::_savedBytes protected inherited
How many bytes were last saved.
Referenced by nidas::dynld::raf::TwoD_USB::saveBuffer(), and nidas::dynld::raf::TwoD_USB::setupBuffer().
unsigned int* nidas::dynld::raf::TwoD_USB::_size_dist_1D protected inherited
Arrays for size-distribution histograms.
Referenced by nidas::dynld::raf::TwoD_USB::clearData(), nidas::dynld::raf::TwoD_USB::countParticle(), nidas::dynld::raf::TwoD_USB::init(), and nidas::dynld::raf::TwoD_USB::~TwoD_USB().
unsigned int* nidas::dynld::raf::TwoD_USB::_size_dist_2D protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::clearData(), nidas::dynld::raf::TwoD_USB::countParticle(), nidas::dynld::raf::TwoD_USB::init(), and nidas::dynld::raf::TwoD_USB::~TwoD_USB().
dsm_sample_id_t nidas::dynld::raf::TwoD_USB::_sorID protected inherited
Shadow OR sample ID.
Shadow-OR is the total number of particle triggers the probes saw, regardless of how many images were downloaded. The 32 bit 2D probes which use the white USB box, don't send shadow-OR via USB. So this sample ID is only used by the Fast2DC. We need to stash sample ID's since the XML will not quite look the same between Fast2DC and 2Ds using the white USB box. The sample IDs will be acquired in the formDOM looking for specific (read hard-coded) string names. Not sure what the best approach is....
Referenced by nidas::dynld::raf::TwoD64_USB::init_parameters().
unsigned int nidas::dynld::raf::TwoD_USB::_suspectSlices protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::~TwoD_USB().
unsigned int nidas::dynld::raf::TwoD_USB::_tasOutOfRange protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::~TwoD_USB().
int nidas::dynld::raf::TwoD_USB::_tasRate protected inherited
How often to send the true air speed.
Probes also send back the shadowOR when they receive the true airspeed, so in general this is also the receive rate of the shadowOR.
unsigned int nidas::dynld::raf::TwoD_USB::_totalParticles protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::~TwoD_USB().
unsigned int nidas::dynld::raf::TwoD_USB::_totalRecords protected inherited
Statistics variables for processRecord().
Referenced by nidas::dynld::raf::TwoD_USB::~TwoD_USB().
float nidas::dynld::raf::TwoD_USB::_trueAirSpeed protected inherited
True air speed, received from IWGADTS feed.
float nidas::dynld::raf::TwoD_USB::_twoDAreaRejectRatio protected inherited
Area of particle rejection ratio.
Actual area of particle divided area of bounding box must be greater than this.
See Also
acceptThisParticle1D()
Referenced by nidas::dynld::raf::TwoD_USB::acceptThisParticle1D(), nidas::dynld::raf::TwoD_USB::acceptThisParticle2D(), and nidas::dynld::raf::TwoD_USB::init().
const n_u::EndianConverter * TwoD_USB::bigEndian static protected inherited
Initial value:
=
    n_u::EndianConverter::getConverter(n_u::EndianConverter::
                                       EC_BIG_ENDIAN)
const float TwoD_USB::DefaultTrueAirspeed = 33.0 static protected inherited
Referenced by nidas::dynld::raf::TwoD_USB::TASToTap2D().
const n_u::EndianConverter * TwoD_USB::littleEndian static protected inherited
Initial value:
=
    n_u::EndianConverter::getConverter(n_u::EndianConverter::
                                       EC_LITTLE_ENDIAN)
The documentation for this class was generated from the following files:
nidas/dynld/raf/TwoD32_USB.h
nidas/dynld/raf/TwoD32_USB.cc