nidas: nidas::core::CalFile Class Reference
nidas::core::CalFile Class Reference
A class for reading ASCII files containing a time series of calibration data.
#include <CalFile.h>
Public Member Functions
CalFile ()
CalFile (const CalFile &)
Copy constructor.
CalFile & operator= (const CalFile &)
Assignment operator, like the copy constructor.
~CalFile ()
Closes the file if necessary.
const std::string & getFile () const
void setFile (const std::string &val)
Set the base name of the file to be opened.
const std::string & getPath () const
Set the search path to find the file, and any included files: one or more directory paths separated by colons ':'.
void setPath (const std::string &val)
Set the search path to find the file, and any included files: one or more directory paths separated by colons ':'.
const std::string & getCurrentFileName () const
Return the full file path of the current file.
void setName (const std::string &val)
An instance of CalFile can have a name.
const std::string & getName () const
int getLineNumber () const
void open () throw (nidas::util::IOException)
Open the file.
void close () throw ()
Close file.
bool eof () const
Have we reached eof.
const std::string & getTimeZone () const
void setTimeZone (const std::string &val)
const std::string & getDateTimeFormat () const
void setDateTimeFormat (const std::string &val)
Set the format for reading the date & time from the file.
nidas::util::UTime search (const nidas::util::UTime &tsearch) throw (nidas::util::IOException,nidas::util::ParseException)
Search forward in a file, returning the time of the last record in the file with a time less than or equal to tsearch.
int readCF (nidas::util::UTime &time, float *data, int ndata) throw (nidas::util::IOException,nidas::util::ParseException)
Read the time and data from the current record.
nidas::util::UTime nextTime () throw ()
void setDSMSensor (const DSMSensor *val)
Set the DSMSensor associated with this CalFile.
const DSMSensor * getDSMSensor () const
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static std::vector< std::string > getAllPaths ()
Return all the paths that have been set in all CalFile instances, in the order they were seen.
static const XMLCh * getNamespaceURI ()
Protected Member Functions
nidas::util::UTime parseTime () throw (nidas::util::ParseException)
void readLine () throw (nidas::util::IOException,nidas::util::ParseException)
void openInclude (const std::string &name) throw (nidas::util::IOException,nidas::util::ParseException)
Private Member Functions
nidas::util::UTime readTime () throw (nidas::util::IOException,nidas::util::ParseException)
Read the time from the next record.
int readCFNoLock (nidas::util::UTime &time, float *data, int ndata) throw (nidas::util::IOException,nidas::util::ParseException)
Static Private Member Functions
static void freeREs ()
static void compileREs () throw (nidas::util::ParseException)
Private Attributes
std::string _name
std::string _fileName
std::string _path
std::string _currentFileName
std::string _timeZone
bool _utcZone
std::string _dateTimeFormat
std::ifstream _fin
int _curlineLength
char * _curline
int _curpos
bool _eofState
int _nline
nidas::util::UTime _nextTime
nidas::util::UTime _includeTime
Time stamp of include "file" record.
nidas::util::UTime _timeAfterInclude
Time stamp of record after include "file".
nidas::util::UTime _timeFromInclude
Time stamp of last record in include file with time <= _includeTime.
CalFile * _include
const DSMSensor * _sensor
nidas::util::Mutex _mutex
Static Private Attributes
static const int INITIAL_CURLINE_LENGTH = 128
static nidas::util::Mutex _staticMutex
static int _reUsers = 0
static bool _reCompiled = false
static regex_t _dateFormatPreg
static regex_t _timeZonePreg
static regex_t _includePreg
static std::vector< std::string > _allPaths
Detailed Description
A class for reading ASCII files containing a time series of calibration data.
CalFile supports reading files like the following:
 # example cal file
 # dateFormat = "%Y %b %d %H:%M:%S"
 # timeZone = "US/Mountain"
 #
 2006 Sep 23 00:00:00    0.0 1.0
 # Offset of 1.0 after Sep 29 01:13:00
 2006 Sep 29 01:13:00    1.0 1.0
 # use calibrations for ACME sensor SN#99 after Oct 1
 2006 Oct 01 00:00:00    include "acme_sn99.dat"
As shown, comment lines begin with a '#'. There are two special comment lines, of the form 'dateFormat="blahblah"' and 'timeZone="blahblah". These specify the format of time in the calibration file. The dateFormat should contain date and time format descriptors as supported by the UNIX strftime function or as supported by the java.text.SimpleDateFormat class. Typically the dateFormat comment is found once in the file, before any data records.
If the dateFormat comment is not found in a file, and the dateTimeFormat attribute is not set on the instance of CalFile, then times must be in a format supported by nidas::util::UTime::parse.
field example UNIX java
year 2006 %Y YYYY
month abrev Sep %b MMM
numeric month 9 %m MM
day of month 14 %d dd
day of year (1-366) 257 %j DDD
hour in day (00-23) 13 %H HH
minute(00-59) 24 %M mm
second(00-59) 47 %S ss
millisecond(000-999) 447 %3f
(UTime extension) SSS
Following the time fields in each record should be either numeric values or an "include" directive.
The numeric values should be space or tab separated values compatible with the usual floating point syntax, or the strings "na" or "nan" in either upper or lower case, representing not-a-number, or NaN. Since math operations using NaN result in a NaN, a calibration record containing a NaN value is a way to generate output values of NaN, indicating non-recoverable data.
An "include" directive causes another calibration file to be opened for input. The included file will be sequentially searched to set the input position to the last record with a time less than or equal to the time value of the "include directive. What this means is that the next readCF() will return data from the included file which is valid for the time of the include directive.
An included file can also contain "include" directives.
The include directive is useful when sensors are swapped during a data acquisition period. One can keep the sensor specific calibrations in separate files, and then create a CalFile which includes the sensor calibrations for the periods that a sensor was deployed. Example:
 # initially krypton hygrometer 1101 at this site
 2006 Sep 23 00:00:00    include "krypton1101"
 # Replaced 1101 with 1393 on Oct 3.
 2006 Oct  3 01:13:00    include "krypton1393"
A typical usage of a CalFile is as follows:
 CalFile calfile;
 calfile.setFile("acme_sn1.dat")
 calfile.setPath("$ROOT/projects/$PROJECT/cal_files:$ROOT/cal_files");
 ...
 while (tsample > calfile.nextTime()) {
     try {
         dsm_time_t calTime;
         float caldata[5];
         int n = calfile.readCF(calTime, caldata, 5);
         for (int i = 0; i < n; i++) coefs[i] = caldata[i];
     }
     catch(const nidas::util::IOException& e) {
         log(e.what);
         break;
     }
     catch(const nidas::util::ParseException& e) {
         log(e.what);
         break;
     }
 }
 // use coefs[] to calibrate sample.
Constructor & Destructor Documentation
CalFile::CalFile ()
References _curline, _reUsers, _staticMutex, and setTimeZone().
CalFile::CalFile (const CalFile & x)
Copy constructor.
Copies the value of getFileName() and getPath() attributes. The CalFile will not be opened in the new copy.
References _curline, _reUsers, _staticMutex, getTimeZone(), and setTimeZone().
CalFile::~CalFile ()
Closes the file if necessary.
References _curline, _include, _reCompiled, _reUsers, _staticMutex, close(), and freeREs().
Member Function Documentation
void CalFile::close () throw ()
Close file.
An opened CalFile is closed in the destructor, so it is not necessary to call close.
References _fin, _include, _nline, and close().
Referenced by close(), operator=(), AutoCalClient::readCalFile(), readTime(), and ~CalFile().
void CalFile::compileREs () throw (nidas::util::ParseException) static private
Referenced by readLine().
bool nidas::core::CalFile::eof () const inline
Have we reached eof.
References _eofState, and _include.
Referenced by main(), AutoCalClient::readCalFile(), readLine(), and readTime().
void CalFile::freeREs () static private
Referenced by ~CalFile().
void CalFile::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
References nidas::core::XDOMAttr::getName(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::VariableConverter::fromDOMElement(), and nidas::core::DSMSensor::fromDOMElement().
static std::vector<std::string> nidas::core::CalFile::getAllPaths () inline static
Return all the paths that have been set in all CalFile instances, in the order they were seen.
These have been separated at the colons.
References _allPaths, _staticMutex, nidas::util::Mutex::lock(), and nidas::util::Mutex::unlock().
const std::string& nidas::core::CalFile::getCurrentFileName () const inline
Return the full file path of the current file.
References _currentFileName, _include, and getCurrentFileName().
Referenced by getCurrentFileName(), parseTime(), readLine(), and PConfig::showCalFiles().
const std::string& nidas::core::CalFile::getDateTimeFormat () const inline
References _dateTimeFormat.
const DSMSensor * CalFile::getDSMSensor () const
References _sensor.
const string & CalFile::getFile () const
References _fileName.
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), A2DVariableItem::dataField(), open(), AutoCalClient::readCalFile(), sensorTitle(), and VariableItem::VariableItem().
int nidas::core::CalFile::getLineNumber () const inline
References _include, _nline, and getLineNumber().
Referenced by getLineNumber(), main(), and parseTime().
const std::string& nidas::core::CalFile::getName () const inline
References _name.
Referenced by nidas::core::DSMSensor::addCalFile().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
const std::string & CalFile::getPath () const
Set the search path to find the file, and any included files: one or more directory paths separated by colons ':'.
References _path.
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), open(), and AutoCalClient::readCalFile().
const std::string& nidas::core::CalFile::getTimeZone () const inline
References _timeZone.
Referenced by CalFile(), and operator=().
nidas::util::UTime nidas::core::CalFile::nextTime () throw () inline
References _nextTime.
Referenced by AutoCalClient::readCalFile().
void CalFile::open () throw (nidas::util::IOException)
Open the file.
It is not necessary to call open(). If the user has not done an open() it will be done in the first readCF(), or search().
References _curline, _curpos, _currentFileName, _eofState, _fin, _nextTime, _path, _sensor, nidas::core::DSMSensor::expandString(), getFile(), nidas::util::Logger::getInstance(), getPath(), nidas::util::Logger::log(), and LOG_INFO.
Referenced by AutoCalClient::readCalFile(), readLine(), and PConfig::showCalFiles().
void CalFile::openInclude (const std::string & name) throw (nidas::util::IOException, nidas::util::ParseException) protected
CalFile & CalFile::operator= (const CalFile & rhs)
Assignment operator, like the copy constructor.
If a file is currently open it will be closed before the assignment.
References _curpos, _dateTimeFormat, _eofState, _fileName, _include, _name, _nline, _path, _sensor, close(), getTimeZone(), and setTimeZone().
n_u::UTime CalFile::parseTime () throw (nidas::util::ParseException) protected
References _curline, _curpos, _dateTimeFormat, _timeZone, _utcZone, getCurrentFileName(), getLineNumber(), nidas::util::UTime::getTZ(), nidas::util::UTime::parse(), nidas::util::UTime::setTZ(), and nidas::util::Exception::what().
Referenced by readTime().
int CalFile::readCF (nidas::util::UTime & time, float * data, int ndata) throw (nidas::util::IOException, nidas::util::ParseException)
Read the time and data from the current record.
The return value may be less than ndata, in which case values in data after n will be filled with NANs. As part of this call, the next time in the file is also read, and its result is available with nextTime(). This method uses a mutex so that multi-threaded calls should not result in crashes or unparseable data. However two threads reading the same CalFile will "steal" each other's data, meaning each thread won't read a full copy of the CalFile.
Referenced by main(), and AutoCalClient::readCalFile().
int CalFile::readCFNoLock (nidas::util::UTime & time, float * data, int ndata) throw (nidas::util::IOException, nidas::util::ParseException) private
References nidas::core::floatNAN, nidas::util::UTime::format(), and nidas::util::UTime::toUsecs().
void CalFile::readLine () throw (nidas::util::IOException, nidas::util::ParseException) protected
References _curline, _curlineLength, _curpos, _dateFormatPreg, _eofState, _fin, _nline, _reCompiled, _staticMutex, _timeZonePreg, compileREs(), eof(), getCurrentFileName(), open(), setDateTimeFormat(), and setTimeZone().
Referenced by readTime().
n_u::UTime CalFile::readTime () throw (nidas::util::IOException, nidas::util::ParseException) private
Read the time from the next record.
If the EOF is found the returned time will be a huge value, far off in the mega-distant future. Does not return an EOFException on EOF.
References _nextTime, close(), eof(), parseTime(), and readLine().
n_u::UTime CalFile::search (const nidas::util::UTime & tsearch) throw (nidas::util::IOException, nidas::util::ParseException)
Search forward in a file, returning the time of the last record in the file with a time less than or equal to tsearch.
The time is available by calling nextTime(). The next call to readCF() will return that record.
Referenced by A2DVariableItem::dataField().
void CalFile::setDateTimeFormat (const std::string & val)
Set the format for reading the date & time from the file.
If a "dateFormat" comment is found at the beginning of the file, this attribute will be set to that value.
References _dateTimeFormat, and nidas::util::replaceCharsIn().
Referenced by readLine().
void CalFile::setDSMSensor (const DSMSensor * val)
Set the DSMSensor associated with this CalFile.
CalFile may need this in order to substitute for tokens like $DSM and $HEIGHT in the file or path names. Otherwise it is not necessary to setDSMSensor.
References _sensor.
Referenced by nidas::core::VariableConverter::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), and nidas::core::DSMSensor::fromDOMElement().
void CalFile::setFile (const std::string & val)
Set the base name of the file to be opened.
References _fileName.
Referenced by main(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
void nidas::core::CalFile::setName (const std::string & val) inline
An instance of CalFile can have a name.
Then more than one CalFile can be associated with an object, such as a DSMSensor, and it can differentiate them by name.
References _name.
void CalFile::setPath (const std::string & val)
Set the search path to find the file, and any included files: one or more directory paths separated by colons ':'.
References _allPaths, _path, _staticMutex, nidas::util::Mutex::lock(), and nidas::util::Mutex::unlock().
Referenced by main(), and nidas::dynld::raf::SyncRecordReader::scanHeader().
void nidas::core::CalFile::setTimeZone (const std::string & val) inline
References _timeZone, and _utcZone.
Referenced by CalFile(), operator=(), and readLine().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
vector< string > CalFile::_allPaths static private
Referenced by getAllPaths(), and setPath().
char* nidas::core::CalFile::_curline private
Referenced by CalFile(), open(), parseTime(), readLine(), and ~CalFile().
int nidas::core::CalFile::_curlineLength private
Referenced by readLine().
int nidas::core::CalFile::_curpos private
Referenced by open(), operator=(), parseTime(), and readLine().
std::string nidas::core::CalFile::_currentFileName private
Referenced by getCurrentFileName(), and open().
regex_t CalFile::_dateFormatPreg static private
Referenced by readLine().
std::string nidas::core::CalFile::_dateTimeFormat private
Referenced by getDateTimeFormat(), operator=(), parseTime(), and setDateTimeFormat().
bool nidas::core::CalFile::_eofState private
Referenced by eof(), open(), operator=(), and readLine().
std::string nidas::core::CalFile::_fileName private
Referenced by getFile(), operator=(), and setFile().
std::ifstream nidas::core::CalFile::_fin private
Referenced by close(), open(), and readLine().
CalFile* nidas::core::CalFile::_include private
Referenced by close(), eof(), getCurrentFileName(), getLineNumber(), operator=(), and ~CalFile().
regex_t CalFile::_includePreg static private
nidas::util::UTime nidas::core::CalFile::_includeTime private
Time stamp of include "file" record.
nidas::util::Mutex nidas::core::CalFile::_mutex private
std::string nidas::core::CalFile::_name private
Referenced by getName(), operator=(), and setName().
nidas::util::UTime nidas::core::CalFile::_nextTime private
Referenced by nextTime(), open(), and readTime().
int nidas::core::CalFile::_nline private
Referenced by close(), getLineNumber(), operator=(), and readLine().
std::string nidas::core::CalFile::_path private
Referenced by getPath(), open(), operator=(), and setPath().
bool CalFile::_reCompiled = false static private
Referenced by readLine(), and ~CalFile().
int CalFile::_reUsers = 0 static private
Referenced by CalFile(), and ~CalFile().
const DSMSensor* nidas::core::CalFile::_sensor private
Referenced by getDSMSensor(), open(), operator=(), and setDSMSensor().
n_u::Mutex CalFile::_staticMutex static private
Referenced by CalFile(), getAllPaths(), readLine(), setPath(), and ~CalFile().
nidas::util::UTime nidas::core::CalFile::_timeAfterInclude private
Time stamp of record after include "file".
nidas::util::UTime nidas::core::CalFile::_timeFromInclude private
Time stamp of last record in include file with time <= _includeTime.
std::string nidas::core::CalFile::_timeZone private
Referenced by getTimeZone(), parseTime(), and setTimeZone().
regex_t CalFile::_timeZonePreg static private
Referenced by readLine().
bool nidas::core::CalFile::_utcZone private
Referenced by parseTime(), and setTimeZone().
const int nidas::core::CalFile::INITIAL_CURLINE_LENGTH = 128 static private
The documentation for this class was generated from the following files:
nidas/core/CalFile.h
nidas/core/CalFile.cc