nidas: nidas::core::DSMService Class Reference
nidas::core::DSMService Class Reference abstract
Base class for a service, as built from a <service> XML tag.
#include <DSMService.h>
Public Member Functions
DSMService (const std::string &name)
Constructor.
virtual ~DSMService ()
const std::string & getName () const
virtual void setDSMServer (DSMServer *val)
virtual DSMServer * getDSMServer () const
virtual void connect (SampleInput *)=0 throw ()
virtual void addProcessor (SampleIOProcessor *proc)
Add a processor to this RawSampleService.
virtual const std::list
< SampleIOProcessor * > & getProcessors () const
const std::list< SampleInput * > & getInputs () const
ProcessorIterator getProcessorIterator () const
virtual void schedule (bool optionalProcessing)=0 throw (nidas::util::Exception)
schedule this service to run.
virtual int checkSubThreads () throw ()
virtual void cancel () throw ()
virtual void interrupt () throw ()
virtual int join () throw ()
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
nidas::util::Thread::SchedPolicy getSchedPolicy () const
int getSchedPriority () const
virtual void printClock (std::ostream &) throw ()
virtual void printStatus (std::ostream &, float) throw ()
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const std::string getClassName (const xercesc::DOMElement *node, const Project *) throw (nidas::util::InvalidParameterException)
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void addSubThread (nidas::util::Thread *) throw ()
Protected Attributes
std::string _name
DSMServer * _server
std::set< nidas::util::Thread * > _subThreads
nidas::util::Mutex _subThreadMutex
std::list< SampleInput * > _inputs
std::list< SampleIOProcessor * > _processors
std::list< IOChannel * > _ochans
nidas::util::Thread::SchedPolicy _threadPolicy
int _threadPriority
Private Member Functions
DSMService (const DSMService &x)
Copying not supported.
DSMService & operator= (const DSMService &x)
Assignment not supported.
Detailed Description
Base class for a service, as built from a <service> XML tag.
Constructor & Destructor Documentation
DSMService::DSMService (const std::string & name)
Constructor.
DSMService::~DSMService () virtual
References _inputs, _ochans, _processors, nidas::core::SampleInput::close(), and nidas::core::IOChannel::close().
nidas::core::DSMService::DSMService (const DSMService & x) private
Copying not supported.
Member Function Documentation
virtual void nidas::core::DSMService::addProcessor (SampleIOProcessor * proc) inline virtual
Add a processor to this RawSampleService.
This is done at configuration (XML) time.
References _processors.
void DSMService::addSubThread (nidas::util::Thread * thd) throw () protected
void DSMService::cancel () throw () virtual
References _subThreadMutex, _subThreads, nidas::util::Thread::cancel(), nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::isRunning(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
int DSMService::checkSubThreads () throw () virtual
References _subThreadMutex, _subThreads, nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::isRunning(), nidas::util::Thread::join(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
virtual void nidas::core::DSMService::connect (SampleInput *) throw () pure virtual
Implemented in nidas::dynld::RawSampleService, and nidas::dynld::XMLConfigService.
void DSMService::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::RawSampleService.
References nidas::core::IOChannel::createIOChannel(), nidas::core::DOMObjectFactory::createObject(), nidas::core::ServiceCatalog::find(), nidas::core::DOMable::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::XDOMElement::getAttributeValue(), nidas::util::Logger::getInstance(), nidas::core::Project::getName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::DSMServer::getProject(), nidas::core::Project::getServiceCatalog(), nidas::util::Logger::log(), LOG_WARNING, nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_RR, nidas::core::SampleIOProcessor::setService(), and nidas::util::Exception::what().
Referenced by nidas::dynld::RawSampleService::fromDOMElement(), and nidas::core::DSMServer::fromDOMElement().
const string DSMService::getClassName (const xercesc::DOMElement * node, const Project * project) throw (nidas::util::InvalidParameterException) static
References nidas::core::XDOMElement::getAttributeValue().
Referenced by nidas::core::DSMServer::fromDOMElement().
virtual DSMServer* nidas::core::DSMService::getDSMServer () const inline virtual
References _server.
Referenced by nidas::dynld::RawSampleService::fromDOMElement().
const std::list<SampleInput*>& nidas::core::DSMService::getInputs () const inline
References _inputs.
const std::string& nidas::core::DSMService::getName () const inline
References _name.
Referenced by nidas::dynld::RawSampleService::fromDOMElement(), nidas::core::DSMServer::joinServices(), and nidas::core::DSMServer::~DSMServer().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
ProcessorIterator DSMService::getProcessorIterator () const
Referenced by nidas::dynld::RawSampleService::printStatus().
virtual const std::list<SampleIOProcessor*>& nidas::core::DSMService::getProcessors () const inline virtual
References _processors.
Referenced by nidas::core::ProcessorIterator::hasNext().
nidas::util::Thread::SchedPolicy nidas::core::DSMService::getSchedPolicy () const inline
References _threadPolicy.
int nidas::core::DSMService::getSchedPriority () const inline
References _threadPriority.
void DSMService::interrupt () throw () virtual
Reimplemented in nidas::dynld::RawSampleService, and nidas::dynld::XMLConfigService.
References _subThreadMutex, _subThreads, nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::interrupt(), nidas::util::Thread::isRunning(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
Referenced by nidas::dynld::XMLConfigService::interrupt(), nidas::dynld::RawSampleService::interrupt(), and nidas::core::DSMServer::interruptServices().
int DSMService::join () throw () virtual
References _subThreadMutex, _subThreads, nidas::util::Logger::getInstance(), nidas::util::Thread::getName(), nidas::util::Thread::join(), nidas::util::Logger::log(), LOG_ERR, nidas::util::Thread::RUN_OK, and nidas::util::Exception::what().
Referenced by nidas::core::DSMServer::joinServices(), and nidas::dynld::RawSampleService::~RawSampleService().
DSMService& nidas::core::DSMService::operator= (const DSMService & x) private
Assignment not supported.
virtual void nidas::core::DSMService::printClock (std::ostream &) throw () inline virtual
Reimplemented in nidas::dynld::RawSampleService.
Referenced by nidas::core::DSMServerStat::run().
virtual void nidas::core::DSMService::printStatus (std::ostream & , float) throw () inline virtual
Reimplemented in nidas::dynld::RawSampleService.
Referenced by nidas::core::DSMServerStat::run().
virtual void nidas::core::DSMService::schedule (bool optionalProcessing) throw (nidas::util::Exception) pure virtual
schedule this service to run.
Implemented in nidas::dynld::RawSampleService, and nidas::dynld::XMLConfigService.
Referenced by nidas::core::DSMServer::scheduleServices().
void DSMService::setDSMServer (DSMServer * val) virtual
References _server.
Referenced by nidas::core::DSMServer::fromDOMElement().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
std::list<SampleInput*> nidas::core::DSMService::_inputs protected
Referenced by nidas::dynld::RawSampleService::fromDOMElement(), getInputs(), and ~DSMService().
std::string nidas::core::DSMService::_name protected
Referenced by getName().
std::list<IOChannel*> nidas::core::DSMService::_ochans protected
Referenced by ~DSMService().
std::list<SampleIOProcessor*> nidas::core::DSMService::_processors protected
Referenced by addProcessor(), getProcessors(), and ~DSMService().
DSMServer* nidas::core::DSMService::_server protected
Referenced by getDSMServer(), and setDSMServer().
nidas::util::Mutex nidas::core::DSMService::_subThreadMutex protected
Referenced by cancel(), checkSubThreads(), interrupt(), and join().
std::set<nidas::util::Thread*> nidas::core::DSMService::_subThreads protected
Referenced by cancel(), checkSubThreads(), interrupt(), and join().
nidas::util::Thread::SchedPolicy nidas::core::DSMService::_threadPolicy protected
Referenced by getSchedPolicy().
int nidas::core::DSMService::_threadPriority protected
Referenced by getSchedPriority().
The documentation for this class was generated from the following files:
nidas/core/DSMService.h
nidas/core/DSMService.cc