nidas: nidas::core::Version Class Reference
nidas::core::Version Class Reference
Class of static member functions providing version strings.
#include <Version.h>
Static Public Member Functions
static const char * getSoftwareVersion ()
static const char * getArchiveVersion ()
Static Private Attributes
static const char * _version = REPO_REVISION
Detailed Description
Class of static member functions providing version strings.
Member Function Documentation
static const char* nidas::core::Version::getArchiveVersion () inline static
Referenced by ARLIngest::prepareHeaderIds(), and nidas::core::HeaderSource::setDefaults().
static const char* nidas::core::Version::getSoftwareVersion () inline static
References _version.
Referenced by nidas::dynld::raf::SyncRecordSource::createHeader(), nidas::core::NidasApp::parseArguments(), nidas::core::DSMServerApp::parseRunstring(), nidas::core::DSMEngine::parseRunstring(), ARLIngest::prepareHeaderIds(), and nidas::core::HeaderSource::setDefaults().
Member Data Documentation
const char * nidas::core::Version::_version = REPO_REVISION static private
Referenced by getSoftwareVersion().
The documentation for this class was generated from the following files:
nidas/core/Version.h
nidas/core/Version.cc