nidas: A2DVariableItem Class Reference
A2DVariableItem Class Reference
#include <A2DVariableItem.h>
Public Member Functions
A2DVariableItem (Variable *variable, SampleTag *sampleTag, int row, NidasModel *theModel, NidasItem *parent=0)
~A2DVariableItem ()
bool removeChild (NidasItem *item)
std::string variableName ()
std::string getVarNamePfx ()
std::string getVarNameSfx ()
const QVariant & childLabel (int column) const
int childColumnCount () const
QString dataField (int column)
QString name ()
SampleTag * getSampleTag () const
xercesc::DOMNode * getSampleDOMNode ()
std::string sSampleId ()
int getA2DChannel ()
int getGain ()
int getBipolar ()
QString getLongName ()
float getRate ()
std::vector< std::string > getCalibrationInfo ()
const std::string & getUnits ()
void setDOMName (QString fromName, std::string toName)
virtual NidasItem * child (int i)
return the ith child of this item.
NidasItem * parent () const
int row () const
int childCount ()
bool removeChildren (int first, int last)
QModelIndex createIndex ()
NidasItem * getParentItem ()
Protected Member Functions
Variable * getVariable () const
xercesc::DOMNode * findSampleDOMNode ()
xercesc::DOMNode * findVariableDOMNode (QString name)
Protected Attributes
Variable * _variable
SampleTag * _sampleTag
xercesc::DOMNode * domNode
QList< NidasItem * > childItems
NidasItem * parentItem
int rowNumber
NidasModel * model
Static Protected Attributes
static const QVariant _Project_Label
static const QVariant _Site_Label
static const QVariant _DSM_Label
static const QVariant _Device_Label
static const QVariant _SN_Label
static const QVariant _ID_Label
static const QVariant _Sensor_Label
static const QVariant _Sample_Label
static const QVariant _DevChan_Label
static const QVariant _Suffix_Label
static const QVariant _Rate_Label
static const QVariant _Volt_Label
static const QVariant _Variable_Label
static const QVariant _CalCoefSrc_Label
static const QVariant _CalCoef_Label
static const QVariant _CalDate_Label
static const QVariant _Name_Label
static const QVariant _Channel_Label
static const QVariant _Unknown_Label
Private Attributes
xercesc::DOMNode * _sampleDOMNode
xercesc::DOMNode * _variableDOMNode
bool _gotCalDate
bool _gotCalVals
std::string _calDate
std::string _calVals
Constructor & Destructor Documentation
A2DVariableItem::A2DVariableItem (Variable * variable, SampleTag * sampleTag, int row, NidasModel * theModel, NidasItem * parent = 0)
A2DVariableItem::~A2DVariableItem ()
References NidasItem::removeChild().
Member Function Documentation
virtual NidasItem* NidasItem::child (int i) inline virtual inherited
return the ith child of this item.
The primary mechanism for building the NidasItem tree. When Qt asks the NidasModel for info, it calls child(). Subclasses reimplement to build items for each type of Nidas object based on the parent's unique child iterators.
N.B. there is a QObject::child(objName,inheritsClass,recursiveSearch) from Qt3. Watch out...
Reimplemented in SensorItem, A2DSensorItem, DSMItem, ProjectItem, and SiteItem.
Referenced by NidasItem::childCount(), NidasModel::index(), and NidasModel::insertRows().
int A2DVariableItem::childColumnCount () const inline virtual
Reimplemented from NidasItem.
int NidasItem::childCount () inherited
NidasItem is a proxy for the actual Nidas objects in the Project tree and their corresponding DOMNodes. Qt indexing is mapped to the Project tree via parent/child with row the ordinal number of the siblings and columns used for data fields (attributes/properties) of each level of Nidas object.
Pointers to Nidas objects are void* since Nidas uses different classes at every level. NidasItem is (should/will be) subclassed for specialized Items corresponding to each kind of Nidas object in the Project tree and implementing their own logic for the API used by NidasModel (like the data and header returned for Qt columns).
The NidasItem tree is a mirror/proxy of the Nidas object Project tree, with children lazily initialized by child(). Row number, parent pointer, and a list of children are cached.
N.B. can only add children to end of list due to Nidas API and use of children list in child()
NidasItem could also become a QObject to get the parent/children stuff. This could be useful in future for findChild()/findChildren(). Except for the fact that it didn't work - something about Qt's cleanup of children caused problems for us.
References NidasItem::child(), and NidasItem::childItems.
Referenced by Document::addA2DVariable(), Document::insertA2DVariable(), NidasModel::insertRows(), and NidasModel::rowCount().
const QVariant& A2DVariableItem::childLabel (int column) const inline virtual
Reimplemented from NidasItem.
References NidasItem::_Name_Label.
QModelIndex NidasItem::createIndex () inline inherited
Asks the model to create an index for this item. Requires us to be a friend of NidasModel and for the model to ask NidasItem for the parent item.
Returns
a QModelIndex for this NidasItem
Referenced by Document::addA2DVariable(), NidasModel::appendChild(), NidasModel::removeChildren(), and NidasModel::removeIndexes().
QString A2DVariableItem::dataField (int column) virtual
Reimplemented from NidasItem.
References nidas::util::UTime::format(), nidas::dynld::A2DSensor::getBipolar(), nidas::core::VariableConverter::getCalFile(), A2DSensorItem::getDSMAnalogSensor(), nidas::core::CalFile::getFile(), nidas::dynld::A2DSensor::getGain(), nidas::core::VariableConverter::getUnits(), nidas::core::Polynomial::readCalFile(), nidas::core::CalFile::search(), nidas::core::Polynomial::setCalFile(), nidas::util::Exception::toString(), nidas::core::VariableConverter::toString(), nidas::core::Polynomial::toString(), and nidas::util::UTime::toUsecs().
DOMNode * A2DVariableItem::findSampleDOMNode () protected
References nidas::core::XDOMElement::getAttributeValue(), and SensorItem::getDOMNode().
DOMNode * A2DVariableItem::findVariableDOMNode (QString name) protected
References nidas::core::XDOMElement::getAttributeValue().
int A2DVariableItem::getA2DChannel () inline
Referenced by Document::addA2DVariable(), and config::AddA2DVariableComboDialog::show().
int A2DVariableItem::getBipolar ()
References nidas::dynld::A2DSensor::getBipolar(), and A2DSensorItem::getDSMAnalogSensor().
Referenced by Document::addA2DVariable(), and config::AddA2DVariableComboDialog::show().
std::vector< std::string > A2DVariableItem::getCalibrationInfo ()
References nidas::core::VariableConverter::getCalFile(), and nidas::core::VariableConverter::toString().
Referenced by Document::addA2DVariable(), and config::AddA2DVariableComboDialog::show().
int A2DVariableItem::getGain ()
References A2DSensorItem::getDSMAnalogSensor(), and nidas::dynld::A2DSensor::getGain().
Referenced by Document::addA2DVariable(), and config::AddA2DVariableComboDialog::show().
QString A2DVariableItem::getLongName () inline
Referenced by Document::addA2DVariable(), and config::AddA2DVariableComboDialog::show().
NidasItem* NidasItem::getParentItem () inline inherited
float A2DVariableItem::getRate () inline
Referenced by Document::addA2DVariable(), and config::AddA2DVariableComboDialog::show().
xercesc::DOMNode* A2DVariableItem::getSampleDOMNode () inline
SampleTag* A2DVariableItem::getSampleTag () const inline
Referenced by Document::insertA2DVariable(), and A2DSensorItem::removeChild().
const std::string& A2DVariableItem::getUnits () inline
Referenced by Document::addA2DVariable().
Variable* A2DVariableItem::getVariable () const inline protected
std::string A2DVariableItem::getVarNamePfx ()
Referenced by Document::addA2DVariable().
std::string A2DVariableItem::getVarNameSfx ()
Referenced by Document::addA2DVariable().
QString A2DVariableItem::name () virtual
Reimplemented from NidasItem.
Referenced by A2DSensorItem::removeChild(), config::AddA2DVariableComboDialog::show(), and A2DSensorItem::updateDOMA2DTempSfx().
NidasItem* NidasItem::parent () const inline inherited
Referenced by NidasModel::parent(), and NidasModel::removeIndexes().
bool A2DVariableItem::removeChild (NidasItem * item) inline virtual
subclasses implement to remove item from Project tree and remove and release from DOM tree
Reimplemented from NidasItem.
bool NidasItem::removeChildren (int first, int last) inherited
References NidasItem::childItems, and NidasItem::rowNumber.
Referenced by NidasModel::removeRows().
int NidasItem::row () const inline inherited
Referenced by NidasModel::parent(), and NidasModel::removeIndexes().
void A2DVariableItem::setDOMName (QString fromName, std::string toName)
Referenced by A2DSensorItem::updateDOMA2DTempSfx().
std::string A2DVariableItem::sSampleId () inline
std::string A2DVariableItem::variableName () inline
Referenced by Document::addA2DVariable().
Member Data Documentation
const QVariant NidasItem::_CalCoef_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_CalCoefSrc_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
std::string A2DVariableItem::_calDate private
const QVariant NidasItem::_CalDate_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
std::string A2DVariableItem::_calVals private
const QVariant NidasItem::_Channel_Label static protected inherited
Referenced by A2DSensorItem::childLabel().
const QVariant NidasItem::_DevChan_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Device_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_DSM_Label static protected inherited
Referenced by SiteItem::childLabel().
bool A2DVariableItem::_gotCalDate private
bool A2DVariableItem::_gotCalVals private
const QVariant NidasItem::_ID_Label static protected inherited
Referenced by SiteItem::childLabel(), and DSMItem::childLabel().
const QVariant NidasItem::_Name_Label static protected inherited
Referenced by VariableItem::childLabel(), SiteItem::childLabel(), childLabel(), and DSMItem::childLabel().
const QVariant NidasItem::_Project_Label static protected inherited
const QVariant NidasItem::_Rate_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Sample_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
xercesc::DOMNode* A2DVariableItem::_sampleDOMNode private
SampleTag* A2DVariableItem::_sampleTag protected
const QVariant NidasItem::_Sensor_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Site_Label static protected inherited
Referenced by ProjectItem::childLabel().
const QVariant NidasItem::_SN_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Suffix_Label static protected inherited
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Unknown_Label static protected inherited
Referenced by A2DSensorItem::childLabel().
Variable* A2DVariableItem::_variable protected
const QVariant NidasItem::_Variable_Label static protected inherited
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
xercesc::DOMNode* A2DVariableItem::_variableDOMNode private
const QVariant NidasItem::_Volt_Label static protected inherited
Referenced by A2DSensorItem::childLabel().
QList<NidasItem*> NidasItem::childItems protected inherited
Referenced by A2DSensorItem::child(), NidasItem::childCount(), A2DSensorItem::refreshChildItems(), NidasItem::removeChildren(), and A2DSensorItem::updateDOMA2DTempSfx().
xercesc::DOMNode* NidasItem::domNode protected inherited
NidasModel* NidasItem::model protected inherited
Referenced by A2DSensorItem::child(), and A2DSensorItem::refreshChildItems().
NidasItem* NidasItem::parentItem protected inherited
int NidasItem::rowNumber protected inherited
Referenced by NidasItem::removeChildren().
The documentation for this class was generated from the following files:
nidas/apps/config/nidas_qmv/A2DVariableItem.h
nidas/apps/config/nidas_qmv/A2DVariableItem.cc