nidas: nidas::dynld::raf::SyncRecordSource Class Reference
nidas::dynld::raf::SyncRecordSource Class Reference
#include <SyncRecordSource.h>
Public Member Functions
SyncRecordSource ()
SyncRecordSource builds "sync records" from a sample stream.
virtual ~SyncRecordSource ()
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
std::list< const SampleTag * > getSampleTags () const
Get the output SampleTags.
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void flush () throw ()
Implementation of Resampler::flush().
const SampleStats & getSampleStats () const
void connect (SampleSource *source) throw ()
Connect the resampler to a source.
void disconnect (SampleSource *source) throw ()
void sendSyncHeader () throw ()
Generate and send a sync record header sample.
bool receive (const Sample *) throw ()
Method called to pass a sample to this client.
void preLoadCalibrations (dsm_time_t sampleTime) throw ()
Static Public Member Functions
static void selectVariablesFromProject (Project *project, std::list< const Variable * > &variables)
This method and selectVariablesFromSensor() are used to select the list of variables from a Project configuration in order of sensor, with variables in order for each sensor, accepting only the variables which make sense for Aircraft SyncRecords.
static void selectVariablesFromSensor (DSMSensor *sensor, std::list< const Variable * > &variables)
See selectVariablesFromProject().
Static Public Attributes
static const int NSYNCREC = 2
Protected Member Functions
void init ()
Private Member Functions
void addSampleTag (const SampleTag *tag) throw ()
Add a SampleTag to this SampleSource.
void removeSampleTag (const SampleTag *tag) throw ()
void createHeader (std::ostream &) throw ()
void sendSyncRecord ()
void allocateRecord (int isync, dsm_time_t timetag)
int advanceRecord (dsm_time_t timetag)
int sampleIndexFromId (dsm_sample_id_t sampleId)
void layoutSyncRecord ()
Construct all the sync record layout artifacts from the list of variables set in _variables.
SyncRecordSource (const SyncRecordSource &)
No copying.
SyncRecordSource & operator= (const SyncRecordSource &)
No assignment.
Private Attributes
SampleSourceSupport _source
std::vector< std::list< const
Variable * > > _varsByIndex
A vector, with each element being a list of variables from a sample.
std::map< dsm_sample_id_t, int > _sampleIndices
A mapping between sample ids and sample indices.
std::vector< int > _intSamplesPerSec
For each sample, by its index, the sampling rate, rounded up to an integer.
std::vector< float > _rates
For each sample, the sampling rate, in floats.
std::vector< int > _usecsPerSample
For each sample, number of microseconds per sample, 1000000/rate, truncated to an integer.
int _halfMaxUsecsPerSample
std::vector< int > _offsetUsec [2]
For the first sample of each variable, its time offset in microseconds into the second.
std::vector< size_t > _sampleLengths
Number of values of each sample in the sync record.
std::vector< size_t > _sampleOffsets
For each sample, its offset into the whole record.
std::vector< int * > _varOffsets
Offsets into the sync record of each variable in a sample, indexed by sampleId.
std::vector< size_t * > _varLengths
Lengths of each variable in a sample, indexed by sampleId.
std::vector< size_t > _numVars
Number of variables in each sample.
std::list< const Variable * > _variables
List of all variables in the sync record.
SampleTag _syncRecordHeaderSampleTag
SampleTag _syncRecordDataSampleTag
int _recSize
dsm_time_t _syncHeaderTime
dsm_time_t _syncTime [2]
int _current
Index of current sync record.
SampleT< double > * _syncRecord [2]
double * _dataPtr [2]
size_t _unrecognizedSamples
std::ostringstream _headerStream
int _badLaterTimes
int _badEarlierTimes
const Aircraft * _aircraft
bool _initialized
int _unknownSampleType
Constructor & Destructor Documentation
SyncRecordSource::SyncRecordSource ()
SyncRecordSource builds "sync records" from a sample stream.
This is a lossy process whete data is being munged into a one-second, ragged matrix of double precision values, called a sync record. Each row of the matrix contains the data for the variables with a given sample id. In NIDAS, a sample is a group of variables all with the same timetag. In order to build sync records a sample also must have a known sampling rate, SampleTag::getRate().
Each row of the matrix is formatted as follows, where the sample row includes variables var0, var1, etc: toffset, var0[0], var0[1], ... var0[N-1], var1[0], var1[1], ... toffset is the number of microseconds into the second to associate with the zeroth value of each variable. N is the sampling rate (#/sec) of all the variables in the sample, rounded up to the next highest integer if the rate is not integral. var[i] are the vector of values of the variable at time i in the record. The vector may have more then one element, if for example the variable is a histogram.
So a sync record is a 4D ragged array with the following dimensions, where time varies most rapidly:
 syncrec[sample][var][time][element]
The number of elements may vary with each variable. The time dimension can vary between samples. toffset is like an initial variable in the sample with a time and element dimension of 1.
Typical sampling rates are:
rate usec/sample N 1000 1000 1000 100 10000 100 50 20000 50 12.5 80000 13 (next highest integer) 10 100000 10 8 125000 8 3 333333 in-exact 3 1 1000000 1
When a sync record is read, the timetags of the variables are re-constructed with the following information:
sync record sample time, the time at beginning of the second
time offset into the second for each sample, in microseconds
timeIndex of the variable, from 0 to (N-1)
The information to unpack a sync record is stored in the header, which is passed first to clients.
The timetags for each sample of a variable are then: sampleTime = syncTime + toffset + (timeIndex * usecsPerSamp) Inverting this to compute the timeIndex: timeIndex = (sampleTime - syncTime - toffset) / usecsPerSamp So that all samples, plus or minus 1/2 sample delta-T, are given the same timeIndex, we use: timeIndex = (sampleTime - syncTime - toffset + usecsPerSamp/2) / usecsPerSamp
If the samples are not actually evenly spaced, then exact time information is lost in resampling into the sync record. Data can also be lost, if two samples are near in time and so have the same resulting timeIndex.
For example, assume these timetags for a 10 Hz variable, with some usual timetag jitter:
sample times 00:00:00.09 00:00:00.18 00:00:00.32 00:00:00.38 00:00:00.50 00:00:00.52 major timetag jitter 00:00:00.71 00:00:00.79 00:00:00.92 00:00:01.01
The corresponding values will be put into a row of a sync record whose time is 00:00:00. The time offset for the sample row will be .09 sec (the offset of the first sample).
Placing this data in the sync record looses time information for all but the first sample. The re-created timetags will be (syncTime + toffset + N * dT), where N=[0,9], and dT=0.1 sec:
re-created times difference(sec) 00:00:00.09 0.0 00:00:00.19 +0.1 00:00:00.29 -0.3 00:00:00.39 +0.1 00:00:00.49 -0.3 will contain value from 00:00:00.52 00:00:00.59 data will be NaN, a loss of data 00:00:00.69 -0.2 00:00:00.79 0.0 00:00:00.89 -0.3 00:00:00.99 -0.2
Note that the original time tag for the last value was in the next second, but is placed in the sync record for the previous second. The received samples are sorted in time before they are placed in the sync record, but because a sample from the next second may be placed in the previous sync record, we have maintain two sync records as they are filled.
References _syncRecordDataSampleTag, _syncRecordHeaderSampleTag, _syncTime, addSampleTag(), nidas::core::SampleTag::setDSMId(), nidas::core::SampleTag::setRate(), nidas::core::SampleTag::setSampleId(), nidas::core::SampleTag::setSensorId(), SYNC_RECORD_HEADER_ID, and SYNC_RECORD_ID.
SyncRecordSource::~SyncRecordSource () virtual
References _syncRecord, _varLengths, _varOffsets, and nidas::core::SampleT< DataT >::freeReference().
nidas::dynld::raf::SyncRecordSource::SyncRecordSource (const SyncRecordSource &) private
No copying.
Member Function Documentation
void nidas::dynld::raf::SyncRecordSource::addSampleClient (SampleClient * client) throw () inline virtual
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
void nidas::dynld::raf::SyncRecordSource::addSampleClientForTag (SampleClient * client, const SampleTag *) throw () inline virtual
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
void nidas::dynld::raf::SyncRecordSource::addSampleTag (const SampleTag * tag) throw () inline private virtual
Add a SampleTag to this SampleSource.
Implements nidas::core::SampleSource.
References nidas::core::SampleSourceSupport::addSampleTag().
Referenced by SyncRecordSource().
int SyncRecordSource::advanceRecord (dsm_time_t timetag) private
References _current, _syncRecord, allocateRecord(), and sendSyncRecord().
void SyncRecordSource::allocateRecord (int isync, dsm_time_t timetag) private
References _dataPtr, _offsetUsec, _recSize, _syncRecord, _syncTime, nidas::util::LogContext::active(), nidas::core::doubleNAN, nidas::util::LogContext::log(), LOG_DEBUG, nidas::core::Sample::setTimeTag(), SYNC_RECORD_ID, and USECS_PER_SEC.
Referenced by advanceRecord().
void SyncRecordSource::connect (SampleSource * source) throw () virtual
Connect the resampler to a source.
Implements nidas::core::Resampler.
References DLOG, nidas::dynld::raf::Aircraft::getAircraft(), and nidas::core::Project::getInstance().
void SyncRecordSource::createHeader (std::ostream &) throw () private
References nidas::core::VariableConverter::getCalFile(), nidas::core::Polynomial::getCoefficients(), nidas::core::Variable::getConverter(), nidas::core::CalFile::getFile(), nidas::core::Linear::getIntercept(), nidas::core::Variable::getLength(), nidas::core::Variable::getLongName(), nidas::core::Variable::getName(), nidas::core::CalFile::getPath(), nidas::core::Linear::getSlope(), nidas::core::Version::getSoftwareVersion(), nidas::core::Variable::getType(), nidas::core::VariableConverter::getUnits(), nidas::core::Variable::getUnits(), rate, and WLOG.
Referenced by sendSyncHeader().
void SyncRecordSource::disconnect (SampleSource * source) throw () virtual
Implements nidas::core::Resampler.
void SyncRecordSource::flush () throw () virtual
Implementation of Resampler::flush().
Send current sync record, whether finished or not.
Implements nidas::core::Resampler.
References DLOG, NSYNCREC, and sendSyncRecord().
int nidas::dynld::raf::SyncRecordSource::getClientCount () const throw () inline virtual
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
SampleSource* nidas::dynld::raf::SyncRecordSource::getProcessedSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
SampleSource* nidas::dynld::raf::SyncRecordSource::getRawSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
const SampleStats& nidas::dynld::raf::SyncRecordSource::getSampleStats () const inline virtual
Implements nidas::core::SampleSource.
SampleTagIterator nidas::dynld::raf::SyncRecordSource::getSampleTagIterator () const inline virtual
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
std::list<const SampleTag*> nidas::dynld::raf::SyncRecordSource::getSampleTags () const inline virtual
Get the output SampleTags.
Implements nidas::core::SampleSource.
void SyncRecordSource::init () protected
References _initialized, _numVars, _recSize, _sampleLengths, _sampleOffsets, _varOffsets, and _varsByIndex.
void SyncRecordSource::layoutSyncRecord () private
Construct all the sync record layout artifacts from the list of variables set in _variables.
The layout includes settings like variable lengths, sample indices, sample sizes and offsets, and rates.
SyncRecordSource first generates the list of variables with selectVariablesFromProject() prior to calling layoutSyncRecord().
References _halfMaxUsecsPerSample, _intSamplesPerSec, _numVars, _offsetUsec, _rates, _sampleIndices, _sampleLengths, _sampleOffsets, _syncRecordDataSampleTag, _syncRecordHeaderSampleTag, _usecsPerSample, _variables, _varLengths, _varOffsets, _varsByIndex, nidas::core::SampleTag::addVariable(), nidas::core::SampleTag::getId(), nidas::core::Variable::getLength(), nidas::core::SampleTag::getRate(), nidas::core::Variable::getSampleTag(), nidas::core::SampleTag::getVariables(), rate, and USECS_PER_SEC.
SyncRecordSource& nidas::dynld::raf::SyncRecordSource::operator= (const SyncRecordSource &) private
No assignment.
void SyncRecordSource::preLoadCalibrations (dsm_time_t sampleTime) throw ()
References nidas::util::LogContext::active(), nidas::util::endlog(), nidas::core::Polynomial::getCoefficients(), nidas::core::Variable::getConverter(), nidas::core::Linear::getIntercept(), nidas::core::Variable::getName(), nidas::core::Linear::getSlope(), ILOG, LOG_INFO, and nidas::core::VariableConverter::readCalFile().
bool SyncRecordSource::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Implements nidas::core::SampleClient.
References nidas::core::SampleTracer::active(), nidas::util::LogContext::active(), nidas::core::DOUBLE_ST, ELOG, nidas::util::endlog(), nidas::core::FLOAT_ST, nidas::util::UTime::format(), nidas::core::SampleTracer::format_time(), format_time(), GET_DSM_ID, GET_SHORT_ID, GET_SPS_ID, nidas::util::Logger::getInstance(), nidas::util::LogContext::log(), nidas::util::Logger::log(), LOG_DEBUG, LOG_WARNING, nidas::core::SampleTracer::msg(), nidas::core::UINT32_ST, USECS_PER_SEC, and WLOG.
void nidas::dynld::raf::SyncRecordSource::removeSampleClient (SampleClient * c) throw () inline virtual
Remove a SampleClient from this SampleSource.
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::raf::SyncRecordGenerator::~SyncRecordGenerator().
void nidas::dynld::raf::SyncRecordSource::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
void nidas::dynld::raf::SyncRecordSource::removeSampleTag (const SampleTag * tag) throw () inline private virtual
Implements nidas::core::SampleSource.
int SyncRecordSource::sampleIndexFromId (dsm_sample_id_t sampleId) private
References _sampleIndices, _unrecognizedSamples, DLOG, GET_DSM_ID, and GET_SPS_ID.
void SyncRecordSource::selectVariablesFromProject (Project * project, std::list< const Variable * > & variables) static
This method and selectVariablesFromSensor() are used to select the list of variables from a Project configuration in order of sensor, with variables in order for each sensor, accepting only the variables which make sense for Aircraft SyncRecords.
The variables are appended to the variables list.
Rather than rely on the sample tags from the source, this allows a single function to be shared to accumulate processed sample tags and variables directly from the Project. Applications (like nimbus) can use this to get the same list of Variables as would be retrieved from SyncRecordReader, except they include all the metadata directly from the Project instead of the sync record header.
References nidas::core::Project::getSensorIterator(), nidas::core::SensorIterator::hasNext(), nidas::core::SensorIterator::next(), and selectVariablesFromSensor().
void SyncRecordSource::selectVariablesFromSensor (DSMSensor * sensor, std::list< const Variable * > & variables) static
See selectVariablesFromProject().
References nidas::core::Variable::CONTINUOUS, nidas::core::Variable::COUNTER, GET_DSM_ID, GET_SPS_ID, nidas::core::SampleTag::getId(), nidas::util::Logger::getInstance(), nidas::core::DSMSensor::getSampleTags(), nidas::core::Variable::getType(), nidas::core::SampleTag::getVariables(), nidas::core::SampleTag::isProcessed(), nidas::util::Logger::log(), and LOG_WARNING.
Referenced by selectVariablesFromProject().
void SyncRecordSource::sendSyncHeader () throw ()
Generate and send a sync record header sample.
The sync record should have been laid out already, but that happens when a source is connected with connect(SampleSource*). Typically sendSyncHeader() should be called after clients are connected with addSampleClient(). The header time tag is the time of the first raw sample read from the input stream, set in the call to preLoadCalibrations(). This is not to be confused with a NIDAS stream header, like would be generated by a HeaderSource, thus the distinction in the name.
References _headerStream, _source, _syncHeaderTime, createHeader(), nidas::core::SampleSourceSupport::distribute(), DLOG, nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::Sample::getTimeTag(), nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), and SYNC_RECORD_HEADER_ID.
void SyncRecordSource::sendSyncRecord () private
References _current, _offsetUsec, _source, _syncRecord, nidas::util::LogContext::active(), nidas::core::SampleSourceSupport::distribute(), format_time(), nidas::core::Sample::getTimeTag(), nidas::util::LogContext::log(), LOG_DEBUG, and NSYNCREC.
Referenced by advanceRecord(), and flush().
Member Data Documentation
const Aircraft* nidas::dynld::raf::SyncRecordSource::_aircraft private
int nidas::dynld::raf::SyncRecordSource::_badEarlierTimes private
int nidas::dynld::raf::SyncRecordSource::_badLaterTimes private
int nidas::dynld::raf::SyncRecordSource::_current private
Index of current sync record.
Referenced by advanceRecord(), and sendSyncRecord().
double* nidas::dynld::raf::SyncRecordSource::_dataPtr[2] private
Referenced by allocateRecord().
int nidas::dynld::raf::SyncRecordSource::_halfMaxUsecsPerSample private
Referenced by layoutSyncRecord().
std::ostringstream nidas::dynld::raf::SyncRecordSource::_headerStream private
Referenced by sendSyncHeader().
bool nidas::dynld::raf::SyncRecordSource::_initialized private
Referenced by init().
std::vector<int> nidas::dynld::raf::SyncRecordSource::_intSamplesPerSec private
For each sample, by its index, the sampling rate, rounded up to an integer.
Referenced by layoutSyncRecord().
std::vector<size_t> nidas::dynld::raf::SyncRecordSource::_numVars private
Number of variables in each sample.
Referenced by init(), and layoutSyncRecord().
std::vector<int> nidas::dynld::raf::SyncRecordSource::_offsetUsec[2] private
For the first sample of each variable, its time offset in microseconds into the second.
Referenced by allocateRecord(), layoutSyncRecord(), and sendSyncRecord().
std::vector<float> nidas::dynld::raf::SyncRecordSource::_rates private
For each sample, the sampling rate, in floats.
Referenced by layoutSyncRecord().
int nidas::dynld::raf::SyncRecordSource::_recSize private
Referenced by allocateRecord(), and init().
std::map<dsm_sample_id_t, int> nidas::dynld::raf::SyncRecordSource::_sampleIndices private
A mapping between sample ids and sample indices.
Sample indices range from 0 to the total number of different input samples -1. When we receive a sample, what is its sampleIndex.
Referenced by layoutSyncRecord(), and sampleIndexFromId().
std::vector<size_t> nidas::dynld::raf::SyncRecordSource::_sampleLengths private
Number of values of each sample in the sync record.
This will be the rate * the number of values in each sample.
Referenced by init(), and layoutSyncRecord().
std::vector<size_t> nidas::dynld::raf::SyncRecordSource::_sampleOffsets private
For each sample, its offset into the whole record.
Referenced by init(), and layoutSyncRecord().
SampleSourceSupport nidas::dynld::raf::SyncRecordSource::_source private
Referenced by sendSyncHeader(), and sendSyncRecord().
dsm_time_t nidas::dynld::raf::SyncRecordSource::_syncHeaderTime private
Referenced by sendSyncHeader().
SampleT<double>* nidas::dynld::raf::SyncRecordSource::_syncRecord[2] private
Referenced by advanceRecord(), allocateRecord(), sendSyncRecord(), and ~SyncRecordSource().
SampleTag nidas::dynld::raf::SyncRecordSource::_syncRecordDataSampleTag private
Referenced by layoutSyncRecord(), and SyncRecordSource().
SampleTag nidas::dynld::raf::SyncRecordSource::_syncRecordHeaderSampleTag private
Referenced by layoutSyncRecord(), and SyncRecordSource().
dsm_time_t nidas::dynld::raf::SyncRecordSource::_syncTime[2] private
Referenced by allocateRecord(), and SyncRecordSource().
int nidas::dynld::raf::SyncRecordSource::_unknownSampleType private
size_t nidas::dynld::raf::SyncRecordSource::_unrecognizedSamples private
Referenced by sampleIndexFromId().
std::vector<int> nidas::dynld::raf::SyncRecordSource::_usecsPerSample private
For each sample, number of microseconds per sample, 1000000/rate, truncated to an integer.
Referenced by layoutSyncRecord().
std::list<const Variable*> nidas::dynld::raf::SyncRecordSource::_variables private
List of all variables in the sync record.
Referenced by layoutSyncRecord().
std::vector<size_t*> nidas::dynld::raf::SyncRecordSource::_varLengths private
Lengths of each variable in a sample, indexed by sampleId.
Referenced by layoutSyncRecord(), and ~SyncRecordSource().
std::vector<int*> nidas::dynld::raf::SyncRecordSource::_varOffsets private
Offsets into the sync record of each variable in a sample, indexed by sampleId.
Referenced by init(), layoutSyncRecord(), and ~SyncRecordSource().
std::vector<std::list<const Variable*> > nidas::dynld::raf::SyncRecordSource::_varsByIndex private
A vector, with each element being a list of variables from a sample.
The order of elements in the vector is the order of the variables in the sync record. By definition, every variable in a sample has the same sampling rate.
Referenced by init(), and layoutSyncRecord().
const int nidas::dynld::raf::SyncRecordSource::NSYNCREC = 2 static
Referenced by flush(), and sendSyncRecord().
The documentation for this class was generated from the following files:
nidas/dynld/raf/SyncRecordSource.h
nidas/dynld/raf/SyncRecordSource.cc