nidas: nidas::core::DSMCatalog Class Reference
nidas::core::DSMCatalog Class Reference
A catalog of DSM DOMElements, implemented with std::map, containing dsm DOMElements, keyed by the ID attributes.
#include <DSMCatalog.h>
Public Member Functions
DSMCatalog ()
DSMCatalog (const DSMCatalog &)
~DSMCatalog ()
DSMCatalog & operator= (const DSMCatalog &)
xercesc::DOMElement *& operator[] (const std::string &id)
Get or set a DOMElement in this catalog by the DSM name.
const xercesc::DOMElement * find (const std::string &id) const
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Build this DSMCatalog from a catalog element.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Private Attributes
std::map< std::string,
xercesc::DOMElement * > _dsms
Detailed Description
A catalog of DSM DOMElements, implemented with std::map, containing dsm DOMElements, keyed by the ID attributes.
Constructor & Destructor Documentation
DSMCatalog::DSMCatalog ()
DSMCatalog::DSMCatalog (const DSMCatalog & x)
DSMCatalog::~DSMCatalog ()
Member Function Documentation
const xercesc::DOMElement * DSMCatalog::find (const std::string & id) const
References _dsms.
Referenced by nidas::core::DSMConfig::fromDOMElement().
void DSMCatalog::fromDOMElement (const xercesc::DOMElement * node) throw (nidas::util::InvalidParameterException) virtual
Build this DSMCatalog from a catalog element.
The DSMCatalog does not own the DOM elements.
Implements nidas::core::DOMable.
References nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::core::Project::fromDOMElement().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
DSMCatalog & DSMCatalog::operator= (const DSMCatalog & rhs)
References _dsms.
xercesc::DOMElement* & nidas::core::DSMCatalog::operator[] (const std::string & id) inline
Get or set a DOMElement in this catalog by the DSM name.
This catalog does not own the DOMElement.
References _dsms.
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
std::map<std::string,xercesc::DOMElement*> nidas::core::DSMCatalog::_dsms private
Referenced by find(), operator=(), and operator[]().
The documentation for this class was generated from the following files:
nidas/core/DSMCatalog.h
nidas/core/DSMCatalog.cc