nidas: CounterClient Class Reference
CounterClient Class Reference
Public Member Functions
CounterClient (const list< DSMSensor * > &sensors, bool hexIds)
virtual ~CounterClient ()
void flush () throw ()
Ask that this SampleClient send out any buffered Samples that it may be holding.
bool receive (const Sample *samp) throw ()
Method called to pass a sample to this client.
void printResults ()
Private Attributes
map< dsm_sample_id_t, string > sensorNames
set< dsm_sample_id_t > sampids
map< dsm_sample_id_t, dsm_time_t > t1s
map< dsm_sample_id_t, dsm_time_t > t2s
map< dsm_sample_id_t, size_t > nsamps
map< dsm_sample_id_t, size_t > minlens
map< dsm_sample_id_t, size_t > maxlens
map< dsm_sample_id_t, int > minDeltaTs
map< dsm_sample_id_t, int > maxDeltaTs
bool _hexIds
Constructor & Destructor Documentation
CounterClient::CounterClient (const list< DSMSensor * > & sensors, bool hexIds)
References nidas::core::DSMSensor::getDeviceName(), nidas::core::DSMSensor::getDSMConfig(), nidas::core::SampleTag::getId(), nidas::core::DSMSensor::getId(), nidas::core::DSMConfig::getName(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTag::getVariables(), nidas::core::SampleTagIterator::hasNext(), nidas::core::SampleTagIterator::next(), and sensorNames.
virtual CounterClient::~CounterClient () inline virtual
Member Function Documentation
void CounterClient::flush () throw () inline virtual
Ask that this SampleClient send out any buffered Samples that it may be holding.
Implements nidas::core::SampleClient.
void CounterClient::printResults ()
References _hexIds, GET_DSM_ID, GET_SPS_ID, maxDeltaTs, maxlens, minDeltaTs, minlens, MSECS_PER_SEC, nsamps, sampids, sensorNames, t1s, t2s, USECS_PER_MSEC, and USECS_PER_SEC.
Referenced by DataStats::run().
bool CounterClient::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Implements nidas::core::SampleClient.
References USECS_PER_MSEC.
Member Data Documentation
bool CounterClient::_hexIds private
Referenced by printResults().
map<dsm_sample_id_t,int> CounterClient::maxDeltaTs private
Referenced by printResults().
map<dsm_sample_id_t,size_t> CounterClient::maxlens private
Referenced by printResults().
map<dsm_sample_id_t,int> CounterClient::minDeltaTs private
Referenced by printResults().
map<dsm_sample_id_t,size_t> CounterClient::minlens private
Referenced by printResults().
map<dsm_sample_id_t,size_t> CounterClient::nsamps private
Referenced by printResults().
set<dsm_sample_id_t> CounterClient::sampids private
Referenced by printResults().
map<dsm_sample_id_t,string> CounterClient::sensorNames private
Referenced by CounterClient(), and printResults().
map<dsm_sample_id_t,dsm_time_t> CounterClient::t1s private
Referenced by printResults().
map<dsm_sample_id_t,dsm_time_t> CounterClient::t2s private
Referenced by printResults().
The documentation for this class was generated from the following file:
nidas/apps/data_stats.cc