nidas: AutoCalPage Class Reference
AutoCalPage Class Reference
#include <CalibrationWizard.h>
Public Slots
void errMessage (const QString &message)
void setValue (int progress)
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Public Member Functions
AutoCalPage (Calibrator *calibrator, AutoCalClient *acc, QWidget *parent=0)
void initializePage ()
int nextId () const
void setVisible (bool visible)
Public Attributes
QProgressDialog * qPD
Private Types
enum { numA2DChannels = 8 }
Private Slots
void saveButtonClicked ()
Private Member Functions
void createTree ()
void createGrid ()
Private Attributes
int dsmId
int devId
Calibrator * calibrator
AutoCalClient * acc
QTreeView * treeView
TreeModel * treeModel
QGroupBox * gridGroupBox
QVBoxLayout * treeLayout
QButtonGroup * buttonGroup
QHBoxLayout * mainLayout
QLabel * ChannelTitle
QLabel * VarNameTitle
QLabel * TimeStampTitle
QLabel * TemperatureTitle
QLabel * IntcpTitle
QLabel * SlopeTitle
QLabel * Channel [numA2DChannels]
QLabel * VarName [numA2DChannels]
QLabel * OldTimeStamp [numA2DChannels]
QLabel * OldTemperature [numA2DChannels]
QLabel * OldIntcp [numA2DChannels]
QLabel * OldSlope [numA2DChannels]
QLabel * NewTimeStamp [numA2DChannels]
QLabel * NewTemperature [numA2DChannels]
QLabel * NewIntcp [numA2DChannels]
QLabel * NewSlope [numA2DChannels]
Member Enumeration Documentation
anonymous enum private
Enumerator
numA2DChannels
Constructor & Destructor Documentation
AutoCalPage::AutoCalPage (Calibrator * calibrator, AutoCalClient * acc, QWidget * parent = 0)
Member Function Documentation
void AutoCalPage::createGrid () private
References Channel, ChannelTitle, gridGroupBox, IntcpTitle, NewIntcp, NewSlope, NewTemperature, NewTimeStamp, numA2DChannels, OldIntcp, OldSlope, OldTemperature, OldTimeStamp, SlopeTitle, TemperatureTitle, TimeStampTitle, VarName, and VarNameTitle.
Referenced by initializePage().
void AutoCalPage::createTree () private
References acc, AutoCalClient::GetTreeModel(), selectionChanged(), treeModel, and treeView.
Referenced by initializePage().
void AutoCalPage::errMessage (const QString & message) slot
Referenced by initializePage().
void AutoCalPage::initializePage ()
References acc, calibrator, createGrid(), createTree(), errMessage(), gridGroupBox, mainLayout, AutoCalClient::maxProgress(), qPD, Calibrator::setup(), setValue(), and treeView.
int AutoCalPage::nextId () const inline
void AutoCalPage::saveButtonClicked () private slot
References acc, and AutoCalClient::SaveAllCalFiles().
Referenced by setVisible().
void AutoCalPage::selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) slot
References acc, TreeModel::data(), devId, dsmId, AutoCalClient::GetNewIntcp(), AutoCalClient::GetNewSlope(), AutoCalClient::GetNewTemperature(), AutoCalClient::GetNewTimeStamp(), AutoCalClient::GetOldIntcp(), AutoCalClient::GetOldSlope(), AutoCalClient::GetOldTemperature(), AutoCalClient::GetOldTimeStamp(), AutoCalClient::GetVarName(), NewIntcp, NewSlope, NewTemperature, NewTimeStamp, numA2DChannels, OldIntcp, OldSlope, OldTemperature, OldTimeStamp, treeModel, and VarName.
Referenced by createTree().
void AutoCalPage::setValue (int progress) slot
References qPD.
Referenced by initializePage().
void AutoCalPage::setVisible (bool visible)
References saveButtonClicked().
Member Data Documentation
AutoCalClient* AutoCalPage::acc private
Referenced by createTree(), initializePage(), saveButtonClicked(), and selectionChanged().
QButtonGroup* AutoCalPage::buttonGroup private
Calibrator* AutoCalPage::calibrator private
Referenced by initializePage().
QLabel* AutoCalPage::Channel[numA2DChannels] private
Referenced by createGrid().
QLabel* AutoCalPage::ChannelTitle private
Referenced by createGrid().
int AutoCalPage::devId private
Referenced by selectionChanged().
int AutoCalPage::dsmId private
Referenced by selectionChanged().
QGroupBox* AutoCalPage::gridGroupBox private
Referenced by createGrid(), and initializePage().
QLabel* AutoCalPage::IntcpTitle private
Referenced by createGrid().
QHBoxLayout* AutoCalPage::mainLayout private
Referenced by initializePage().
QLabel* AutoCalPage::NewIntcp[numA2DChannels] private
Referenced by createGrid(), and selectionChanged().
QLabel* AutoCalPage::NewSlope[numA2DChannels] private
Referenced by createGrid(), and selectionChanged().
QLabel* AutoCalPage::NewTemperature[numA2DChannels] private
Referenced by createGrid(), and selectionChanged().
QLabel* AutoCalPage::NewTimeStamp[numA2DChannels] private
Referenced by createGrid(), and selectionChanged().
QLabel* AutoCalPage::OldIntcp[numA2DChannels] private
Referenced by createGrid(), and selectionChanged().
QLabel* AutoCalPage::OldSlope[numA2DChannels] private
Referenced by createGrid(), and selectionChanged().
QLabel* AutoCalPage::OldTemperature[numA2DChannels] private
Referenced by createGrid(), and selectionChanged().
QLabel* AutoCalPage::OldTimeStamp[numA2DChannels] private
Referenced by createGrid(), and selectionChanged().
QProgressDialog* AutoCalPage::qPD
Referenced by initializePage(), and setValue().
QLabel* AutoCalPage::SlopeTitle private
Referenced by createGrid().
QLabel* AutoCalPage::TemperatureTitle private
Referenced by createGrid().
QLabel* AutoCalPage::TimeStampTitle private
Referenced by createGrid().
QVBoxLayout* AutoCalPage::treeLayout private
TreeModel* AutoCalPage::treeModel private
Referenced by createTree(), and selectionChanged().
QTreeView* AutoCalPage::treeView private
Referenced by createTree(), and initializePage().
QLabel* AutoCalPage::VarName[numA2DChannels] private
Referenced by createGrid(), and selectionChanged().
QLabel* AutoCalPage::VarNameTitle private
Referenced by createGrid().
The documentation for this class was generated from the following files:
nidas/apps/auto_cal/CalibrationWizard.h
nidas/apps/auto_cal/CalibrationWizard.cc