nidas: nidas::core::SerialSensor::Prompter Class Reference
nidas::core::SerialSensor::Prompter Class Reference
Public Member Functions
Prompter (SerialSensor *sensor)
~Prompter ()
void setPrompt (const std::string &val)
const std::string getPrompt () const
void setPromptPeriodMsec (const int)
int getPromptPeriodMsec () const
void setPromptOffsetMsec (const int)
int getPromptOffsetMsec () const
void looperNotify () throw ()
Method called by Looper in order to send a prompt.
Private Member Functions
Prompter (const Prompter &)
copy not necessary
Prompter & operator= (const Prompter &)
assignment not necessary
Private Attributes
SerialSensor * _sensor
char * _prompt
int _promptLen
int _promptPeriodMsec
int _promptOffsetMsec
Constructor & Destructor Documentation
nidas::core::SerialSensor::Prompter::Prompter (SerialSensor * sensor) inline
SerialSensor::Prompter::~Prompter ()
References _prompt.
nidas::core::SerialSensor::Prompter::Prompter (const Prompter &) private
copy not necessary
Member Function Documentation
const std::string nidas::core::SerialSensor::Prompter::getPrompt () const inline
int nidas::core::SerialSensor::Prompter::getPromptOffsetMsec () const inline
Referenced by nidas::core::SerialSensor::startPrompting().
int nidas::core::SerialSensor::Prompter::getPromptPeriodMsec () const inline
Referenced by nidas::core::SerialSensor::startPrompting().
void SerialSensor::Prompter::looperNotify () throw () virtual
Method called by Looper in order to send a prompt.
Implements nidas::core::LooperClient.
References nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
Prompter& nidas::core::SerialSensor::Prompter::operator= (const Prompter &) private
assignment not necessary
void SerialSensor::Prompter::setPrompt (const std::string & val)
Referenced by nidas::core::SerialSensor::initPrompting().
void SerialSensor::Prompter::setPromptOffsetMsec (const int val)
Referenced by nidas::core::SerialSensor::initPrompting().
void SerialSensor::Prompter::setPromptPeriodMsec (const int val)
Referenced by nidas::core::SerialSensor::initPrompting().
Member Data Documentation
char* nidas::core::SerialSensor::Prompter::_prompt private
Referenced by ~Prompter().
int nidas::core::SerialSensor::Prompter::_promptLen private
int nidas::core::SerialSensor::Prompter::_promptOffsetMsec private
int nidas::core::SerialSensor::Prompter::_promptPeriodMsec private
SerialSensor* nidas::core::SerialSensor::Prompter::_sensor private
The documentation for this class was generated from the following files:
nidas/core/SerialSensor.h
nidas/core/SerialSensor.cc