nidas: nidas::core::DOMable Class Reference
nidas::core::DOMable Class Reference abstract
Interface of an object that can be instantiated from a DOM element, via the fromDOMElement method, or that can be serialized into a DOM, via the toDOMParent/toDOMElement method.
#include <DOMable.h>
Public Member Functions
virtual ~DOMable ()
Virtual destructor.
virtual void fromDOMElement (const xercesc::DOMElement *)=0 throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Static Private Attributes
static XMLCh * namespaceURI = 0
Detailed Description
Interface of an object that can be instantiated from a DOM element, via the fromDOMElement method, or that can be serialized into a DOM, via the toDOMParent/toDOMElement method.
Constructor & Destructor Documentation
virtual nidas::core::DOMable::~DOMable () inline virtual
Virtual destructor.
Member Function Documentation
virtual void nidas::core::DOMable::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) pure virtual
Initialize myself from a xercesc::DOMElement.
Implemented in nidas::core::DSMSensor, nidas::core::ServerSocket, nidas::core::Variable, nidas::core::CalFile, nidas::core::SampleTag, nidas::dynld::SampleInputStream, nidas::core::Site, nidas::core::Polynomial, nidas::core::CharacterSensor, nidas::core::SampleOutputBase, nidas::core::SampleIOProcessor, nidas::core::Project, nidas::core::Socket, nidas::core::DSMConfig, nidas::dynld::isff::GOESXmtr, nidas::core::DatagramSocket, nidas::core::Linear, nidas::core::ParameterT< T >, nidas::core::SerialSensor, nidas::core::McSocket, nidas::core::McSocketUDP, nidas::core::UnixIOChannel, nidas::core::FileSet, nidas::dynld::raf::DSMArincSensor, nidas::core::FsMount, nidas::dynld::isff::CS_Krypton, nidas::core::VariableConverter, nidas::dynld::isff::GOESOutput, nidas::dynld::raf::CVIProcessor, nidas::core::DSMService, nidas::core::DSMServer, nidas::dynld::psql::PSQLChannel, nidas::dynld::raf::IRIGSensor, nidas::dynld::psql::PSQLSampleOutput, nidas::dynld::UDPSampleOutput, nidas::dynld::A2DSensor, nidas::dynld::isff::PropVane, nidas::dynld::DSC_A2DSensor, nidas::core::MultipleUDPSockets, nidas::core::DSMCatalog, nidas::dynld::RawSampleInputStream, nidas::dynld::Twins, nidas::core::SensorCatalog, nidas::dynld::RawSampleService, nidas::core::ServiceCatalog, nidas::dynld::raf::LamsSensor, nidas::dynld::raf::Arinc_IRS, and nidas::dynld::RawSampleOutputStream.
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static
References namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
XMLCh * DOMable::namespaceURI = 0 static private
Referenced by getNamespaceURI().
The documentation for this class was generated from the following files:
nidas/core/DOMable.h
nidas/core/DOMable.cc