nidas: DeviceValidator Class Reference
DeviceValidator Class Reference
#include <DeviceValidator.h>
Classes
class _DeviceDefinition
class _DeviceDefinitionStruct
Public Member Functions
std::string & getDevicePrefix (std::string &key)
unsigned int getMin (std::string &key)
unsigned int getMax (std::string &key)
const char * getInterfaceLabel (std::string &key)
Static Public Member Functions
static DeviceValidator * getInstance ()
Protected Attributes
std::map< std::string,
_DeviceDefinition > _devMap
Static Protected Attributes
static _DeviceDefinitionStruct _Definitions []
Private Member Functions
DeviceValidator ()
Static Private Attributes
static DeviceValidator * _instance = NULL
Constructor & Destructor Documentation
DeviceValidator::DeviceValidator () private
References _Definitions, and _devMap.
Referenced by getInstance().
Member Function Documentation
std::string& DeviceValidator::getDevicePrefix (std::string & key) inline
References _devMap.
Referenced by SensorItem::dataField(), config::AddSensorComboDialog::existingSensor(), config::AddSensorComboDialog::newSensor(), and config::AddSensorComboDialog::setDevice().
static DeviceValidator* DeviceValidator::getInstance () inline static
References _instance, and DeviceValidator().
Referenced by SensorItem::dataField(), config::AddSensorComboDialog::existingSensor(), config::AddSensorComboDialog::newSensor(), and config::AddSensorComboDialog::setDevice().
const char* DeviceValidator::getInterfaceLabel (std::string & key) inline
References _devMap, and DeviceValidator::_DeviceDefinitionStruct::_InterfaceLabels.
Referenced by config::AddSensorComboDialog::existingSensor(), and config::AddSensorComboDialog::newSensor().
unsigned int DeviceValidator::getMax (std::string & key) inline
References _devMap.
Referenced by config::AddSensorComboDialog::existingSensor(), and config::AddSensorComboDialog::newSensor().
unsigned int DeviceValidator::getMin (std::string & key) inline
References _devMap.
Referenced by config::AddSensorComboDialog::existingSensor(), and config::AddSensorComboDialog::newSensor().
Member Data Documentation
DeviceValidator::_DeviceDefinitionStruct DeviceValidator::_Definitions static protected
Referenced by DeviceValidator().
std::map<std::string, _DeviceDefinition> DeviceValidator::_devMap protected
Referenced by DeviceValidator(), getDevicePrefix(), getInterfaceLabel(), getMax(), and getMin().
DeviceValidator * DeviceValidator::_instance = NULL static private
Referenced by getInstance().
The documentation for this class was generated from the following files:
nidas/apps/config/DeviceValidator.h
nidas/apps/config/DeviceValidator.cc