nidas: config::AddSensorComboDialog Class Reference
config::AddSensorComboDialog Class Reference
#include <AddSensorComboDialog.h>
Public Slots
void accept ()
void reject ()
void newSensor (QString)
void existingSensor (SensorItem *sensorItem)
void setDevice (int)
void show (NidasModel *model, QModelIndexList indexList)
bool setUpDialog ()
void dialogSetup (const QString &sensor)
Public Member Functions
AddSensorComboDialog (QString a2dCalDir, QString pmsSpecsFile, QWidget *parent=0)
~AddSensorComboDialog ()
void setDocument (Document *document)
void clearSfxMap ()
void addSensorSfx (QString sensor, QString sfx)
void clearDevMap ()
void addSensorDev (QString sensor, QString dev)
Protected Attributes
QMessageBox * _errorMessage
Document * _document
Private Member Functions
void setupPMSSerNums (QString pmsSpecsFile)
void setupA2DSerNums (QString a2dCalDir)
Private Attributes
std::map< std::string,
std::string > _pmsResltn
QModelIndexList _indexList
NidasModel * _model
map< QString, QString > _sfxMap
map< QString, QString > _devMap
Constructor & Destructor Documentation
AddSensorComboDialog::AddSensorComboDialog (QString a2dCalDir, QString pmsSpecsFile, QWidget * parent = 0)
References _errorMessage, _idRegEx(), dialogSetup(), setupA2DSerNums(), and setupPMSSerNums().
config::AddSensorComboDialog::~AddSensorComboDialog () inline
Member Function Documentation
void AddSensorComboDialog::accept () slot
References _document, _errorMessage, _indexList, _pmsResltn, Document::addSensor(), Document::setIsChanged(), nidas::util::Exception::toString(), and Document::updateSensor().
void config::AddSensorComboDialog::addSensorDev (QString sensor, QString dev) inline
References _devMap.
Referenced by ConfigWindow::buildSensorCatalog().
void config::AddSensorComboDialog::addSensorSfx (QString sensor, QString sfx) inline
References _sfxMap.
Referenced by ConfigWindow::buildSensorCatalog().
void config::AddSensorComboDialog::clearDevMap () inline
References _devMap.
Referenced by ConfigWindow::buildSensorCatalog().
void config::AddSensorComboDialog::clearSfxMap () inline
References _sfxMap.
Referenced by ConfigWindow::buildSensorCatalog().
void AddSensorComboDialog::dialogSetup (const QString & sensor) slot
Referenced by AddSensorComboDialog().
void AddSensorComboDialog::existingSensor (SensorItem * sensorItem) slot
References _errorMessage, device, A2DSensorItem::getA2DTempSuffix(), SensorItem::getBaseName(), A2DSensorItem::getCalFileName(), SensorItem::getDevice(), DeviceValidator::getDevicePrefix(), SensorItem::getDSMSensor(), DeviceValidator::getInstance(), DeviceValidator::getInterfaceLabel(), DeviceValidator::getMax(), DeviceValidator::getMin(), SensorItem::getSerialNumberString(), and setDevice().
Referenced by setUpDialog().
void AddSensorComboDialog::newSensor (QString sensor) slot
References _devMap, _sfxMap, buffer, DeviceValidator::getDevicePrefix(), DeviceValidator::getInstance(), DeviceValidator::getInterfaceLabel(), DeviceValidator::getMax(), DeviceValidator::getMin(), and setDevice().
Referenced by setUpDialog().
void config::AddSensorComboDialog::reject () inline slot
void AddSensorComboDialog::setDevice (int channel) slot
References DeviceValidator::getDevicePrefix(), and DeviceValidator::getInstance().
Referenced by existingSensor(), newSensor(), and setUpDialog().
void config::AddSensorComboDialog::setDocument (Document * document) inline
References _document.
Referenced by ConfigWindow::buildSensorCatalog().
void AddSensorComboDialog::setupA2DSerNums (QString a2dCalDir) private
Referenced by AddSensorComboDialog().
bool AddSensorComboDialog::setUpDialog () slot
References _document, _errorMessage, _indexList, _model, existingSensor(), NidasModel::getItem(), Document::getNextSensorId(), newSensor(), setDevice(), and nidas::util::Exception::toString().
Referenced by show().
void AddSensorComboDialog::setupPMSSerNums (QString pmsSpecsFile) private
References _pmsResltn, and buffer.
Referenced by AddSensorComboDialog().
void AddSensorComboDialog::show (NidasModel * model, QModelIndexList indexList) slot
References _indexList, _model, _pmsResltn, and setUpDialog().
Referenced by ConfigWindow::addSensorCombo(), and ConfigWindow::editSensorCombo().
Member Data Documentation
map<QString, QString> config::AddSensorComboDialog::_devMap private
Referenced by addSensorDev(), clearDevMap(), and newSensor().
Document* config::AddSensorComboDialog::_document protected
Referenced by accept(), setDocument(), and setUpDialog().
QMessageBox* config::AddSensorComboDialog::_errorMessage protected
Referenced by accept(), AddSensorComboDialog(), existingSensor(), and setUpDialog().
QModelIndexList config::AddSensorComboDialog::_indexList private
Referenced by accept(), setUpDialog(), and show().
NidasModel* config::AddSensorComboDialog::_model private
Referenced by setUpDialog(), and show().
std::map<std::string, std::string> config::AddSensorComboDialog::_pmsResltn private
Referenced by accept(), setupPMSSerNums(), and show().
map<QString, QString> config::AddSensorComboDialog::_sfxMap private
Referenced by addSensorSfx(), clearSfxMap(), and newSensor().
The documentation for this class was generated from the following files:
nidas/apps/config/AddSensorComboDialog.h
nidas/apps/config/AddSensorComboDialog.cc