nidas: nidas::core::DSMServer Class Reference
nidas::core::DSMServer Class Reference
A provider of services to a DSM.
#include <DSMServer.h>
Public Member Functions
DSMServer ()
virtual ~DSMServer ()
const std::string & getName () const
void setName (const std::string &val)
const std::string & getXMLConfigFileName () const
void setXMLConfigFileName (const std::string &val)
void addService (DSMService *service)
const std::list< DSMService * > & getServices () const
void setProject (Project *val)
const Project * getProject () const
void setSite (const Site *val)
const Site * getSite () const
DSMServiceIterator getDSMServiceIterator () const
ProcessorIterator getProcessorIterator () const
SensorIterator getSensorIterator () const
SampleTagIterator getSampleTagIterator () const
void addThread (nidas::util::Thread *thrd)
void scheduleServices (bool optionalProcessing) throw (nidas::util::Exception)
void interruptServices () throw ()
void joinServices () throw ()
void setStatusSocketAddr (const nidas::util::SocketAddress &val)
const nidas::util::SocketAddress & getStatusSocketAddr () const
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Private Member Functions
DSMServer (const DSMServer &)
Copy not supported.
DSMServer & operator= (const DSMServer &)
Assignment not supported.
Private Attributes
std::string _name
Name of this server.
Project * _project
const Site * _site
What Site to I serve? Can be NULL if this DSMServer is not for a specific Site, but serves the Project.
std::list< DSMService * > _services
The DSMServices that we've been configured to start.
std::string _xmlFileName
nidas::util::SocketAddress * _statusSocketAddr
Detailed Description
A provider of services to a DSM.
Constructor & Destructor Documentation
DSMServer::DSMServer ()
DSMServer::~DSMServer () virtual
References _services, _statusSocketAddr, and nidas::core::DSMService::getName().
nidas::core::DSMServer::DSMServer (const DSMServer &) private
Copy not supported.
Member Function Documentation
void nidas::core::DSMServer::addService (DSMService * service) inline
References _services.
void nidas::core::DSMServer::addThread (nidas::util::Thread * thrd)
void DSMServer::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
References nidas::core::DOMObjectFactory::createObject(), nidas::core::DSMService::fromDOMElement(), nidas::util::Inet4Address::getByName(), nidas::core::DSMService::getClassName(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), NIDAS_MULTICAST_ADDR, port, nidas::core::DSMService::setDSMServer(), and nidas::util::Exception::what().
Referenced by nidas::core::Project::fromDOMElement(), and nidas::core::Site::fromDOMElement().
DSMServiceIterator DSMServer::getDSMServiceIterator () const
const std::string& nidas::core::DSMServer::getName () const inline
References _name.
Referenced by nidas::core::Project::findServer(), nidas::core::Site::findServer(), nidas::core::Project::findServers(), and nidas::core::Project::findServerSampleOutputStreamFileSets().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
ProcessorIterator DSMServer::getProcessorIterator () const
Referenced by nidas::core::Project::findServerSampleOutputStreamFileSets(), and StatsProcess::getStatisticsProcessor().
const Project* nidas::core::DSMServer::getProject () const inline
References _project.
Referenced by nidas::core::GetDsmList::execute(), nidas::core::GetAdsFileName::execute(), and nidas::core::DSMService::fromDOMElement().
SampleTagIterator DSMServer::getSampleTagIterator () const
SensorIterator DSMServer::getSensorIterator () const
References _project, nidas::core::Project::getSensorIterator(), nidas::core::Site::getSensorIterator(), and getSite().
Referenced by nidas::dynld::RawSampleService::fromDOMElement(), StatsProcess::run(), and nidas::dynld::RawSampleService::schedule().
const std::list<DSMService*>& nidas::core::DSMServer::getServices () const inline
References _services.
Referenced by nidas::core::DSMServiceIterator::hasNext(), and nidas::core::DSMServerStat::run().
const Site* nidas::core::DSMServer::getSite () const inline
References _site.
Referenced by getSensorIterator().
const nidas::util::SocketAddress& nidas::core::DSMServer::getStatusSocketAddr () const inline
References _statusSocketAddr.
Referenced by nidas::core::DSMServerApp::run(), and nidas::core::DSMServerStat::run().
const std::string& nidas::core::DSMServer::getXMLConfigFileName () const inline
References _xmlFileName.
void DSMServer::interruptServices () throw ()
References _services, nidas::core::SampleOutputRequestThread::clear(), nidas::core::SampleOutputRequestThread::getInstance(), and nidas::core::DSMService::interrupt().
Referenced by nidas::core::DSMServerApp::run().
void DSMServer::joinServices () throw ()
References _services, nidas::core::DSMService::getName(), ILOG, and nidas::core::DSMService::join().
Referenced by nidas::core::DSMServerApp::run().
DSMServer& nidas::core::DSMServer::operator= (const DSMServer &) private
Assignment not supported.
void DSMServer::scheduleServices (bool optionalProcessing) throw (nidas::util::Exception)
References nidas::core::DSMService::schedule().
Referenced by nidas::core::DSMServerApp::run().
void nidas::core::DSMServer::setName (const std::string & val) inline
References _name.
void nidas::core::DSMServer::setProject (Project * val) inline
References _project.
Referenced by nidas::core::Project::fromDOMElement(), and nidas::core::Site::fromDOMElement().
void nidas::core::DSMServer::setSite (const Site * val) inline
References _site.
Referenced by nidas::core::Site::fromDOMElement().
void nidas::core::DSMServer::setStatusSocketAddr (const nidas::util::SocketAddress & val) inline
References _statusSocketAddr, and nidas::util::SocketAddress::clone().
void nidas::core::DSMServer::setXMLConfigFileName (const std::string & val) inline
References _xmlFileName.
Referenced by nidas::core::DSMServerApp::run().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
std::string nidas::core::DSMServer::_name private
Name of this server.
This should correspond to a hostname of a machine.
Referenced by getName(), and setName().
Project* nidas::core::DSMServer::_project private
Referenced by getProject(), getSensorIterator(), and setProject().
std::list<DSMService*> nidas::core::DSMServer::_services private
The DSMServices that we've been configured to start.
Referenced by addService(), getServices(), interruptServices(), joinServices(), and ~DSMServer().
const Site* nidas::core::DSMServer::_site private
What Site to I serve? Can be NULL if this DSMServer is not for a specific Site, but serves the Project.
Referenced by getSite(), and setSite().
nidas::util::SocketAddress* nidas::core::DSMServer::_statusSocketAddr private
Referenced by getStatusSocketAddr(), setStatusSocketAddr(), and ~DSMServer().
std::string nidas::core::DSMServer::_xmlFileName private
Referenced by getXMLConfigFileName(), and setXMLConfigFileName().
The documentation for this class was generated from the following files:
nidas/core/DSMServer.h
nidas/core/DSMServer.cc