nidas: NidasItem Class Reference
NidasItem Class Reference
#include <NidasItem.h>
Public Member Functions
virtual ~NidasItem ()
virtual NidasItem * child (int i)
return the ith child of this item.
NidasItem * parent () const
int row () const
int childCount ()
bool removeChildren (int first, int last)
virtual bool removeChild (NidasItem *item)
virtual int childColumnCount () const
virtual const QVariant & childLabel (int column) const
virtual QString dataField (int column)
QModelIndex createIndex ()
NidasItem * getParentItem ()
Protected Member Functions
virtual QString name ()
Protected Attributes
xercesc::DOMNode * domNode
QList< NidasItem * > childItems
NidasItem * parentItem
int rowNumber
NidasModel * model
Static Protected Attributes
static const QVariant _Project_Label
static const QVariant _Site_Label
static const QVariant _DSM_Label
static const QVariant _Device_Label
static const QVariant _SN_Label
static const QVariant _ID_Label
static const QVariant _Sensor_Label
static const QVariant _Sample_Label
static const QVariant _DevChan_Label
static const QVariant _Suffix_Label
static const QVariant _Rate_Label
static const QVariant _Volt_Label
static const QVariant _Variable_Label
static const QVariant _CalCoefSrc_Label
static const QVariant _CalCoef_Label
static const QVariant _CalDate_Label
static const QVariant _Name_Label
static const QVariant _Channel_Label
static const QVariant _Unknown_Label
Friends
class NidasModel
Constructor & Destructor Documentation
virtual NidasItem::~NidasItem () inline virtual
subclasses must implement destructor, removing self from parent, then deleting the nidasObject (as its intrinsic type), but not releasing the possibly cached DOMNode (parent should do so in removeChild())
Member Function Documentation
virtual NidasItem* NidasItem::child (int i) inline virtual
return the ith child of this item.
The primary mechanism for building the NidasItem tree. When Qt asks the NidasModel for info, it calls child(). Subclasses reimplement to build items for each type of Nidas object based on the parent's unique child iterators.
N.B. there is a QObject::child(objName,inheritsClass,recursiveSearch) from Qt3. Watch out...
Reimplemented in SensorItem, A2DSensorItem, DSMItem, ProjectItem, and SiteItem.
Referenced by childCount(), NidasModel::index(), and NidasModel::insertRows().
virtual int NidasItem::childColumnCount () const inline virtual
Reimplemented in SensorItem, A2DSensorItem, A2DVariableItem, DSMItem, ProjectItem, SiteItem, and VariableItem.
Referenced by NidasModel::columnCount().
int NidasItem::childCount ()
NidasItem is a proxy for the actual Nidas objects in the Project tree and their corresponding DOMNodes. Qt indexing is mapped to the Project tree via parent/child with row the ordinal number of the siblings and columns used for data fields (attributes/properties) of each level of Nidas object.
Pointers to Nidas objects are void* since Nidas uses different classes at every level. NidasItem is (should/will be) subclassed for specialized Items corresponding to each kind of Nidas object in the Project tree and implementing their own logic for the API used by NidasModel (like the data and header returned for Qt columns).
The NidasItem tree is a mirror/proxy of the Nidas object Project tree, with children lazily initialized by child(). Row number, parent pointer, and a list of children are cached.
N.B. can only add children to end of list due to Nidas API and use of children list in child()
NidasItem could also become a QObject to get the parent/children stuff. This could be useful in future for findChild()/findChildren(). Except for the fact that it didn't work - something about Qt's cleanup of children caused problems for us.
References child(), and childItems.
Referenced by Document::addA2DVariable(), Document::insertA2DVariable(), NidasModel::insertRows(), and NidasModel::rowCount().
virtual const QVariant& NidasItem::childLabel (int column) const inline virtual
Reimplemented in SensorItem, A2DVariableItem, DSMItem, A2DSensorItem, ProjectItem, SiteItem, and VariableItem.
Referenced by NidasModel::headerData().
QModelIndex NidasItem::createIndex () inline
Asks the model to create an index for this item. Requires us to be a friend of NidasModel and for the model to ask NidasItem for the parent item.
Returns
a QModelIndex for this NidasItem
Referenced by Document::addA2DVariable(), NidasModel::appendChild(), NidasModel::removeChildren(), and NidasModel::removeIndexes().
virtual QString NidasItem::dataField (int column) inline virtual
Reimplemented in SensorItem, A2DVariableItem, DSMItem, VariableItem, ProjectItem, and SiteItem.
Referenced by NidasModel::data().
NidasItem* NidasItem::getParentItem () inline
virtual QString NidasItem::name () inline protected virtual
Reimplemented in DSMItem, SiteItem, ProjectItem, A2DVariableItem, and VariableItem.
Referenced by A2DSensorItem::removeChild().
NidasItem* NidasItem::parent () const inline
Referenced by NidasModel::parent(), and NidasModel::removeIndexes().
virtual bool NidasItem::removeChild (NidasItem * item) inline virtual
subclasses implement to remove item from Project tree and remove and release from DOM tree
Reimplemented in A2DSensorItem, SensorItem, DSMItem, A2DVariableItem, ProjectItem, SiteItem, and VariableItem.
Referenced by A2DVariableItem::~A2DVariableItem(), DSMItem::~DSMItem(), SensorItem::~SensorItem(), SiteItem::~SiteItem(), and VariableItem::~VariableItem().
bool NidasItem::removeChildren (int first, int last)
References childItems, and rowNumber.
Referenced by NidasModel::removeRows().
int NidasItem::row () const inline
Referenced by NidasModel::parent(), and NidasModel::removeIndexes().
Friends And Related Function Documentation
friend class NidasModel friend
Member Data Documentation
const QVariant NidasItem::_CalCoef_Label static protected
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_CalCoefSrc_Label static protected
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_CalDate_Label static protected
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Channel_Label static protected
Referenced by A2DSensorItem::childLabel().
const QVariant NidasItem::_DevChan_Label static protected
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Device_Label static protected
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_DSM_Label static protected
Referenced by SiteItem::childLabel().
const QVariant NidasItem::_ID_Label static protected
Referenced by SiteItem::childLabel(), and DSMItem::childLabel().
const QVariant NidasItem::_Name_Label static protected
Referenced by VariableItem::childLabel(), SiteItem::childLabel(), A2DVariableItem::childLabel(), and DSMItem::childLabel().
const QVariant NidasItem::_Project_Label static protected
const QVariant NidasItem::_Rate_Label static protected
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Sample_Label static protected
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Sensor_Label static protected
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Site_Label static protected
Referenced by ProjectItem::childLabel().
const QVariant NidasItem::_SN_Label static protected
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Suffix_Label static protected
Referenced by DSMItem::childLabel().
const QVariant NidasItem::_Unknown_Label static protected
Referenced by A2DSensorItem::childLabel().
const QVariant NidasItem::_Variable_Label static protected
Referenced by A2DSensorItem::childLabel(), and SensorItem::childLabel().
const QVariant NidasItem::_Volt_Label static protected
Referenced by A2DSensorItem::childLabel().
QList<NidasItem*> NidasItem::childItems protected
Referenced by A2DSensorItem::child(), childCount(), A2DSensorItem::refreshChildItems(), removeChildren(), and A2DSensorItem::updateDOMA2DTempSfx().
xercesc::DOMNode* NidasItem::domNode protected
NidasModel* NidasItem::model protected
Referenced by A2DSensorItem::child(), and A2DSensorItem::refreshChildItems().
NidasItem* NidasItem::parentItem protected
int NidasItem::rowNumber protected
Referenced by removeChildren().
The documentation for this class was generated from the following files:
nidas/apps/config/nidas_qmv/NidasItem.h
nidas/apps/config/nidas_qmv/NidasItem.cc