nidas: TreeModel Class Reference
TreeModel Class Reference
#include <TreeModel.h>
Public Member Functions
TreeModel (const QString &data, QObject *parent=0)
~TreeModel ()
QVariant data (const QModelIndex &index, int role) const
Qt::ItemFlags flags (const QModelIndex &index) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &index) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
int columnCount (const QModelIndex &parent=QModelIndex()) const
Private Member Functions
void setupModelData (const QStringList &lines, TreeItem *parent)
Private Attributes
TreeItem * rootItem
Constructor & Destructor Documentation
TreeModel::TreeModel (const QString & data, QObject * parent = 0)
References rootItem, and setupModelData().
TreeModel::~TreeModel ()
References rootItem.
Member Function Documentation
int TreeModel::columnCount (const QModelIndex & parent = QModelIndex()) const
References TreeItem::columnCount(), and rootItem.
QVariant TreeModel::data (const QModelIndex & index, int role) const
References TreeItem::data().
Referenced by AutoCalPage::selectionChanged(), and TestA2DPage::selectionChanged().
Qt::ItemFlags TreeModel::flags (const QModelIndex & index) const
QVariant TreeModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
References TreeItem::data(), and rootItem.
QModelIndex TreeModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
References TreeItem::child(), and rootItem.
QModelIndex TreeModel::parent (const QModelIndex & index) const
References TreeItem::parent(), rootItem, and TreeItem::row().
Referenced by setupModelData().
int TreeModel::rowCount (const QModelIndex & parent = QModelIndex()) const
References TreeItem::childCount(), and rootItem.
void TreeModel::setupModelData (const QStringList & lines, TreeItem * parent) private
References parent().
Referenced by TreeModel().
Member Data Documentation
TreeItem* TreeModel::rootItem private
Referenced by columnCount(), headerData(), index(), parent(), rowCount(), TreeModel(), and ~TreeModel().
The documentation for this class was generated from the following files:
nidas/apps/auto_cal/TreeModel.h
nidas/apps/auto_cal/TreeModel.cc