nidas: nidas::core::XDOMElement Class Reference
nidas::core::XDOMElement Class Reference
Wrapper class providing convienence methods to access the string attributes of a DOMElement.
#include <XDOM.h>
Public Member Functions
XDOMElement (const xercesc::DOMElement *e)
XDOMElement (xercesc::DOMElement *e)
const std::string & getAttributeValue (const std::string &aname)
void setAttributeValue (const std::string &name, const std::string &val)
const std::string & getNodeName () const
const std::string & getNodeType () const
const xercesc::DOMElement * getElement () const
Private Member Functions
XDOMElement (const XDOMElement &)
No copying.
XDOMElement & operator= (const XDOMElement &)
No assignment.
Private Attributes
const xercesc::DOMElement * _elemConst
xercesc::DOMElement * _elemNonConst
std::map< std::string,
std::string > _attrs
std::string _nodename
std::string _nodetype
Detailed Description
Wrapper class providing convienence methods to access the string attributes of a DOMElement.
Constructor & Destructor Documentation
nidas::core::XDOMElement::XDOMElement (const xercesc::DOMElement * e) inline
nidas::core::XDOMElement::XDOMElement (xercesc::DOMElement * e) inline
nidas::core::XDOMElement::XDOMElement (const XDOMElement &) private
No copying.
Member Function Documentation
const std::string& nidas::core::XDOMElement::getAttributeValue (const std::string & aname) inline
Returns
an empty string if attribute does not have a specified or default value.
References _attrs, and _elemConst.
Referenced by nidas::core::XMLConfigWriterFilter::acceptDSMNode(), ConfigWindow::buildSensorCatalog(), nidas::core::IOChannel::createIOChannel(), nidas::core::Socket::createSocket(), nidas::core::VariableConverter::createVariableConverter(), ProjectItem::findDOMNode(), SiteItem::findDOMNode(), DSMItem::findDOMNode(), SensorItem::findDOMNode(), A2DVariableItem::findSampleDOMNode(), SensorItem::findSampleDOMNode(), VariableItem::findSampleDOMNode(), A2DVariableItem::findVariableDOMNode(), VariableItem::findVariableDOMNode(), nidas::core::ServiceCatalog::fromDOMElement(), nidas::core::SensorCatalog::fromDOMElement(), nidas::core::DSMCatalog::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::core::ParameterT< T >::fromDOMElement(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::Project::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::CharacterSensor::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMService::getClassName(), nidas::core::DSMSensor::getClassName(), LogSchemeFromDOMElement(), ProjectItem::removeChild(), SiteItem::removeChild(), DSMItem::removeChild(), SensorItem::removeChild(), A2DSensorItem::removeChild(), nidas::core::DSMConfig::sensorFromDOMElement(), PMSSensorItem::updateDOMPMSParams(), and Document::updateVariable().
const xercesc::DOMElement* nidas::core::XDOMElement::getElement () const inline
References _elemConst.
const std::string& nidas::core::XDOMElement::getNodeName () const inline
References _nodename.
Referenced by nidas::core::XMLConfigWriterFilter::acceptDSMNode(), nidas::core::XMLConfigWriterFilter::acceptNode(), nidas::core::IOChannel::createIOChannel(), nidas::core::VariableConverter::createVariableConverter(), nidas::core::ServiceCatalog::fromDOMElement(), nidas::core::SensorCatalog::fromDOMElement(), nidas::core::DSMCatalog::fromDOMElement(), nidas::core::Dataset::fromDOMElement(), nidas::core::ProjectConfig::fromDOMElement(), nidas::core::DSMServer::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::core::VariableConverter::fromDOMElement(), nidas::core::Datasets::fromDOMElement(), nidas::core::FileSet::fromDOMElement(), nidas::core::SerialSensor::fromDOMElement(), nidas::core::ProjectConfigs::fromDOMElement(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::Project::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::CharacterSensor::fromDOMElement(), nidas::core::Site::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::CalFile::fromDOMElement(), nidas::core::Variable::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), LogSchemeFromDOMElement(), SiteItem::removeChild(), ProjectItem::removeChild(), DSMItem::removeChild(), SensorItem::removeChild(), A2DSensorItem::removeChild(), and nidas::core::DSMConfig::sensorFromDOMElement().
const std::string& nidas::core::XDOMElement::getNodeType () const inline
References _nodetype.
XDOMElement& nidas::core::XDOMElement::operator= (const XDOMElement &) private
No assignment.
void nidas::core::XDOMElement::setAttributeValue (const std::string & name, const std::string & val) inline
References _attrs, and _elemNonConst.
Referenced by nidas::dynld::XMLConfigService::Worker::run(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::DSMConfig::toDOMElement(), nidas::core::Project::toDOMElement(), nidas::core::Site::toDOMElement(), nidas::core::SampleTag::toDOMElement(), and nidas::core::Variable::toDOMElement().
Member Data Documentation
std::map<std::string,std::string> nidas::core::XDOMElement::_attrs private
Referenced by getAttributeValue(), and setAttributeValue().
const xercesc::DOMElement* nidas::core::XDOMElement::_elemConst private
Referenced by getAttributeValue(), and getElement().
xercesc::DOMElement* nidas::core::XDOMElement::_elemNonConst private
Referenced by setAttributeValue().
std::string nidas::core::XDOMElement::_nodename private
Referenced by getNodeName().
std::string nidas::core::XDOMElement::_nodetype private
Referenced by getNodeType().
The documentation for this class was generated from the following file:
nidas/core/XDOM.h