nidas: DumpClient Class Reference
DumpClient Class Reference
Public Types
enum format {
DEFAULT, ASCII, HEX_FMT, SIGNED_SHORT,
UNSIGNED_SHORT, FLOAT, IRIG, INT32,
ASCII_7, NAKED, ASCII, BINARY1,
BINARY2
}
enum format {
DEFAULT, ASCII, HEX_FMT, SIGNED_SHORT,
UNSIGNED_SHORT, FLOAT, IRIG, INT32,
ASCII_7, NAKED, ASCII, BINARY1,
BINARY2
}
typedef enum DumpClient::format format_t
typedef enum DumpClient::format format_t
Public Member Functions
DumpClient (const SampleMatcher &, format_t, ostream &, NidasApp::id_format_t idfmt)
virtual ~DumpClient ()
void flush () throw ()
Ask that this SampleClient send out any buffered Samples that it may be holding.
bool receive (const Sample *samp) throw ()
Method called to pass a sample to this client.
void printHeader ()
DumpClient::format_t typeToFormat (sampleType t)
DumpClient (format_t, ostream &, int asciiPrecision)
virtual ~DumpClient ()
void flush () throw ()
Ask that this SampleClient send out any buffered Samples that it may be holding.
bool receive (const Sample *samp) throw ()
Method called to pass a sample to this client.
void printHeader (vector< const Variable * > vars)
void setStartTime (const n_u::UTime &val)
void setEndTime (const n_u::UTime &val)
void setDOS (bool val)
bool getDOS () const
Private Member Functions
DumpClient (const DumpClient &)
DumpClient & operator= (const DumpClient &)
Private Attributes
SampleMatcher _samples
format_t format
ostream & ostr
const n_u::EndianConverter * fromLittle
NidasApp::id_format_t _idFormat
format_t _format
ostream & _ostr
n_u::UTime _startTime
n_u::UTime _endTime
bool _checkStart
bool _checkEnd
bool _dosOut
int _asciiPrecision
Member Typedef Documentation
typedef enum DumpClient::format DumpClient::format_t
typedef enum DumpClient::format DumpClient::format_t
Member Enumeration Documentation
enum DumpClient::format
Enumerator
DEFAULT
ASCII
HEX_FMT
SIGNED_SHORT
UNSIGNED_SHORT
FLOAT
IRIG
INT32
ASCII_7
NAKED
ASCII
BINARY1
BINARY2
enum DumpClient::format
Enumerator
DEFAULT
ASCII
HEX_FMT
SIGNED_SHORT
UNSIGNED_SHORT
FLOAT
IRIG
INT32
ASCII_7
NAKED
ASCII
BINARY1
BINARY2
Constructor & Destructor Documentation
DumpClient::DumpClient (const SampleMatcher & matcher, format_t fmt, ostream & outstr, NidasApp::id_format_t idfmt)
virtual DumpClient::~DumpClient () inline virtual
DumpClient::DumpClient (const DumpClient &) private
DumpClient::DumpClient (format_t fmt, ostream & outstr, int asciiPrecision)
virtual DumpClient::~DumpClient () inline virtual
Member Function Documentation
void DumpClient::flush () throw () inline virtual
Ask that this SampleClient send out any buffered Samples that it may be holding.
Implements nidas::core::SampleClient.
void DumpClient::flush () throw () inline virtual
Ask that this SampleClient send out any buffered Samples that it may be holding.
Implements nidas::core::SampleClient.
bool DumpClient::getDOS () const inline
DumpClient& DumpClient::operator= (const DumpClient &) private
void DumpClient::printHeader ()
References _samples, and nidas::core::SampleMatcher::exclusiveMatch().
Referenced by DataPrep::run().
void DumpClient::printHeader (vector< const Variable * > vars)
References _dosOut, nidas::core::Variable::getConverter(), nidas::core::Variable::getName(), nidas::core::VariableConverter::getUnits(), and nidas::core::Variable::getUnits().
bool DumpClient::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Implements nidas::core::SampleClient.
References nidas::util::addBackslashSequences(), nidas::core::DOUBLE_ST, nidas::core::FLOAT_ST, nidas::util::UTime::format(), timeval32::tv_sec, timeval32::tv_usec, and USECS_PER_SEC.
bool DumpClient::receive (const Sample * s) throw () virtual
Method called to pass a sample to this client.
This method is typically called by a SampleSource for each of its SampleClients when it has a sample ready. Returns true: success false: sample rejected. This is meant to signal a warning-type situation - like a socket not being available temporarily. True errors will be thrown as an IOException.
Implements nidas::core::SampleClient.
void DumpClient::setDOS (bool val) inline
Referenced by DataPrep::run().
void DumpClient::setEndTime (const n_u::UTime & val) inline
Referenced by DataPrep::run().
void DumpClient::setStartTime (const n_u::UTime & val) inline
Referenced by DataPrep::run().
DumpClient::format_t DumpClient::typeToFormat (sampleType t)
References ASCII, nidas::core::CHAR_ST, nidas::core::DOUBLE_ST, FLOAT, nidas::core::FLOAT_ST, HEX_FMT, INT32, nidas::core::INT32_ST, nidas::core::INT64_ST, nidas::core::SHORT_ST, SIGNED_SHORT, nidas::core::UCHAR_ST, nidas::core::UINT32_ST, nidas::core::UNKNOWN_ST, UNSIGNED_SHORT, and nidas::core::USHORT_ST.
Member Data Documentation
int DumpClient::_asciiPrecision private
bool DumpClient::_checkEnd private
bool DumpClient::_checkStart private
bool DumpClient::_dosOut private
Referenced by printHeader().
n_u::UTime DumpClient::_endTime private
format_t DumpClient::_format private
NidasApp::id_format_t DumpClient::_idFormat private
ostream& DumpClient::_ostr private
SampleMatcher DumpClient::_samples private
Referenced by printHeader().
n_u::UTime DumpClient::_startTime private
format_t DumpClient::format private
const n_u::EndianConverter* DumpClient::fromLittle private
ostream& DumpClient::ostr private
The documentation for this class was generated from the following files:
nidas/apps/data_dump.cc
nidas/apps/isff/prep.cc