nidas: DataStats Class Reference
DataStats Class Reference
Public Member Functions
DataStats ()
~DataStats ()
int run () throw ()
int parseRunstring (int argc, char **argv)
Static Public Member Functions
static int main (int argc, char **argv)
static int usage (const char *argv0)
static void sigAction (int sig, siginfo_t *siginfo, void *)
static void setupSignals ()
Public Attributes
int logLevel
Private Attributes
bool processData
string xmlFileName
list< string > dataFileNames
n_u::auto_ptr< n_u::SocketAddress > sockAddr
bool hexIds
Static Private Attributes
static bool interrupted = false
static const int DEFAULT_PORT = 30000
Constructor & Destructor Documentation
DataStats::DataStats ()
DataStats::~DataStats () inline
Member Function Documentation
int DataStats::main (int argc, char ** argv) static
References nidas::util::Logger::getInstance(), nidas::util::LogConfig::level, logLevel, parseRunstring(), run(), nidas::util::Logger::setScheme(), and setupSignals().
Referenced by main().
int DataStats::parseRunstring (int argc, char ** argv)
References dataFileNames, DEFAULT_PORT, nidas::util::Inet4Address::getByName(), logLevel, port, processData, sockAddr, usage(), nidas::util::Exception::what(), and xmlFileName.
Referenced by main().
int DataStats::run () throw ()
References nidas::core::SampleSource::addSampleClient(), nidas::dynld::SampleInputStream::addSampleClient(), nidas::dynld::SampleInputStream::addSampleTag(), nidas::dynld::SampleInputStream::close(), nidas::core::FileSet::connect(), nidas::core::SamplePipeline::connect(), dataFileNames, nidas::core::SamplePipeline::disconnect(), nidas::util::Process::expandEnvVars(), nidas::core::SamplePipeline::flush(), nidas::core::SampleInputHeader::getConfigName(), nidas::core::FileSet::getFileSet(), nidas::dynld::SampleInputStream::getInputHeader(), nidas::core::SamplePipeline::getProcessedSampleSource(), nidas::core::DSMSensor::getRawSampleTag(), nidas::core::DSMConfig::getSensors(), nidas::core::DSMConfigIterator::hasNext(), nidas::core::DSMSensor::init(), nidas::core::SamplePipeline::interrupt(), interrupted, nidas::core::SamplePipeline::join(), nidas::core::parseXMLConfigFile(), CounterClient::printResults(), processData, nidas::dynld::SampleInputStream::readInputHeader(), nidas::dynld::SampleInputStream::readSamples(), nidas::core::SampleSource::removeSampleClient(), nidas::dynld::SampleInputStream::removeSampleClient(), nidas::dynld::SampleInputStream::setMaxSampleLength(), nidas::core::SamplePipeline::setProcSorterLength(), nidas::core::SamplePipeline::setRawSorterLength(), nidas::core::SamplePipeline::setRealTime(), sockAddr, nidas::util::Exception::what(), and xmlFileName.
Referenced by main().
void DataStats::setupSignals () static
References sigAction().
Referenced by main().
void DataStats::sigAction (int sig, siginfo_t * siginfo, void *) static
References interrupted.
Referenced by setupSignals().
int DataStats::usage (const char * argv0) static
References DEFAULT_PORT.
Referenced by parseRunstring().
Member Data Documentation
list<string> DataStats::dataFileNames private
Referenced by parseRunstring(), and run().
const int DataStats::DEFAULT_PORT = 30000 static private
Referenced by parseRunstring(), and usage().
bool DataStats::hexIds private
bool DataStats::interrupted = false static private
Referenced by run(), and sigAction().
int DataStats::logLevel
Referenced by main(), and parseRunstring().
bool DataStats::processData private
Referenced by parseRunstring(), and run().
n_u::auto_ptr<n_u::SocketAddress> DataStats::sockAddr private
Referenced by parseRunstring(), and run().
string DataStats::xmlFileName private
Referenced by parseRunstring(), and run().
The documentation for this class was generated from the following file:
nidas/apps/data_stats.cc