nidas: QtExceptionHandler Class Reference
QtExceptionHandler Class Reference
#include <QtExceptionHandler.h>
Public Member Functions
virtual void display (std::string &where, std::string &what)
~QtExceptionHandler ()
virtual void handle (std::string &where)
void handle (const char *where)
void display (const char *where, std::string &what)
void display (std::string &where, const char *what)
void display (const char *where, const char *what)
virtual void log (std::string &where, std::string &what)
virtual void show ()
virtual void hide ()
virtual void setVisible (bool)
Constructor & Destructor Documentation
QtExceptionHandler::~QtExceptionHandler () inline
Member Function Documentation
virtual void QtExceptionHandler::display (std::string & where, std::string & what) inline virtual
Implements UserFriendlyExceptionHandler.
void UserFriendlyExceptionHandler::display (const char * where, std::string & what) inline inherited
References UserFriendlyExceptionHandler::display().
void UserFriendlyExceptionHandler::display (std::string & where, const char * what) inline inherited
References UserFriendlyExceptionHandler::display().
void UserFriendlyExceptionHandler::display (const char * where, const char * what) inline inherited
References UserFriendlyExceptionHandler::display().
virtual void UserFriendlyExceptionHandler::handle (std::string & where) inline virtual inherited
References UserFriendlyExceptionHandler::display(), and nidas::util::Exception::what().
Referenced by UserFriendlyExceptionHandler::handle(), and ConfigWindow::openFile().
void UserFriendlyExceptionHandler::handle (const char * where) inline inherited
References UserFriendlyExceptionHandler::handle().
virtual void UserFriendlyExceptionHandler::hide () inline virtual inherited
Reimplemented in CuteLoggingExceptionHandler.
virtual void UserFriendlyExceptionHandler::log (std::string & where, std::string & what) inline virtual inherited
Reimplemented in CuteLoggingExceptionHandler.
References UserFriendlyExceptionHandler::display().
virtual void UserFriendlyExceptionHandler::setVisible (bool) inline virtual inherited
Reimplemented in CuteLoggingExceptionHandler.
Referenced by ConfigWindow::toggleErrorsWindow().
virtual void UserFriendlyExceptionHandler::show () inline virtual inherited
Reimplemented in CuteLoggingExceptionHandler.
The documentation for this class was generated from the following file:
nidas/apps/config/exceptions/QtExceptionHandler.h