nidas: nidas::core::ProjectConfig Class Reference
nidas::core::ProjectConfig Class Reference
#include <ProjectConfigs.h>
Public Member Functions
ProjectConfig ()
const std::string & getName () const
void setName (const std::string &val)
const std::string & getXMLName () const
void setXMLName (const std::string &val)
const nidas::util::UTime & getBeginTime () const
void setBeginTime (const nidas::util::UTime &val)
const nidas::util::UTime & getEndTime () const
void setEndTime (const nidas::util::UTime &val)
void addEnvironmentVariable (const std::string &name, const std::string &value)
Add an environment variable to this ProjectConfig.
std::map< std::string,
std::string > getEnvironmentVariables () const
void putenv () const
Update the process environment with the current list of environment variables in the ProjectConfig.
void initProject (Project &project) const throw (nidas::core::XMLException, nidas::util::InvalidParameterException)
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent) const throw (xercesc::DOMException)
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node) const throw (xercesc::DOMException)
Private Attributes
std::string _name
std::string _xmlName
nidas::util::UTime _beginTime
nidas::util::UTime _endTime
std::map< std::string,
std::string > _envVars
Constructor & Destructor Documentation
ProjectConfig::ProjectConfig ()
References getBeginTime(), setEndTime(), and USECS_PER_DAY.
Member Function Documentation
void ProjectConfig::addEnvironmentVariable (const std::string & name, const std::string & value)
Add an environment variable to this ProjectConfig.
The actual process environment is not effected. After doing addEnvironmentVariable() one or more times, use ProjectConfig::putenv() to update the actual process environment. Set value to an empty string to remove a variable from the environment.
References _envVars.
void ProjectConfig::fromDOMElement (const xercesc::DOMElement * node) throw (nidas::util::InvalidParameterException)
References nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::util::UTime::parse(), and nidas::util::Exception::what().
Referenced by nidas::core::ProjectConfigs::fromDOMElement().
const nidas::util::UTime& nidas::core::ProjectConfig::getBeginTime () const inline
References _beginTime.
Referenced by nidas::core::ProjectConfigs::addConfigByTime(), ProjConfigIO::getConfig(), nidas::core::ProjectConfigs::getConfig(), ProjConfigIO::getConfigForTime(), ProjConfigIO::listConfigs(), nidas::core::ProjectConfigTimeComparator::operator()(), ProjectConfig(), StatsProcess::run(), and DataPrep::run().
const nidas::util::UTime& nidas::core::ProjectConfig::getEndTime () const inline
References _endTime.
Referenced by nidas::core::ProjectConfigs::addConfigByTime(), ProjConfigIO::getConfig(), nidas::core::ProjectConfigs::getConfig(), ProjConfigIO::getConfigForTime(), ProjConfigIO::listConfigs(), nidas::core::ProjectConfigTimeComparator::operator()(), StatsProcess::run(), and DataPrep::run().
std::map<std::string,std::string> nidas::core::ProjectConfig::getEnvironmentVariables () const inline
References _envVars.
const std::string& nidas::core::ProjectConfig::getName () const inline
References _name.
Referenced by nidas::core::ProjectConfigs::addConfigByName(), ProjConfigIO::addConfigByTime(), ProjConfigIO::getConfig(), nidas::core::ProjectConfigs::getConfig(), ProjConfigIO::getConfigForTime(), ProjConfigIO::listConfigs(), and putenv().
const std::string& nidas::core::ProjectConfig::getXMLName () const inline
References _xmlName.
Referenced by ProjConfigIO::getConfig(), ProjConfigIO::getConfigForTime(), ProjConfigIO::listConfigs(), nidas::core::DSMServerApp::run(), StatsProcess::run(), and DataPrep::run().
void ProjectConfig::initProject (Project & project) const throw (nidas::core::XMLException, nidas::util::InvalidParameterException)
Parameters
project,: the project, by reference.
References nidas::util::Process::expandEnvVars(), and nidas::core::parseXMLConfigFile().
Referenced by StatsProcess::listOutputSamples(), nidas::core::DSMServerApp::run(), StatsProcess::run(), and DataPrep::run().
void ProjectConfig::putenv () const
Update the process environment with the current list of environment variables in the ProjectConfig.
References _envVars, nidas::util::Process::getEnvVar(), getName(), and nidas::util::Process::setEnvVar().
void nidas::core::ProjectConfig::setBeginTime (const nidas::util::UTime & val) inline
References _beginTime.
Referenced by ProjConfigIO::addConfigByTime().
void nidas::core::ProjectConfig::setEndTime (const nidas::util::UTime & val) inline
References _endTime.
Referenced by ProjConfigIO::addConfigByTime(), ProjectConfig(), and ProjConfigIO::termConfig().
void nidas::core::ProjectConfig::setName (const std::string & val) inline
References _name.
Referenced by ProjConfigIO::addConfigByTime().
void nidas::core::ProjectConfig::setXMLName (const std::string & val) inline
References _xmlName.
Referenced by ProjConfigIO::addConfigByTime().
xercesc::DOMElement * ProjectConfig::toDOMElement (xercesc::DOMElement * node) const throw (xercesc::DOMException)
References nidas::core::DOMable::getNamespaceURI(), and nidas::core::XDOMElement::setAttributeValue().
xercesc::DOMElement * ProjectConfig::toDOMParent (xercesc::DOMElement * parent) const throw (xercesc::DOMException)
References nidas::core::DOMable::getNamespaceURI().
Referenced by nidas::core::ProjectConfigs::toDOMElement().
Member Data Documentation
nidas::util::UTime nidas::core::ProjectConfig::_beginTime private
Referenced by getBeginTime(), and setBeginTime().
nidas::util::UTime nidas::core::ProjectConfig::_endTime private
Referenced by getEndTime(), and setEndTime().
std::map<std::string,std::string> nidas::core::ProjectConfig::_envVars private
Referenced by addEnvironmentVariable(), getEnvironmentVariables(), and putenv().
std::string nidas::core::ProjectConfig::_name private
Referenced by getName(), and setName().
std::string nidas::core::ProjectConfig::_xmlName private
Referenced by getXMLName(), and setXMLName().
The documentation for this class was generated from the following files:
nidas/core/ProjectConfigs.h
nidas/core/ProjectConfigs.cc