nidas: nidas::dynld::psql::PSQLProcessor Class Reference
nidas::dynld::psql::PSQLProcessor Class Reference abstract
#include <PSQLProcessor.h>
Public Member Functions
PSQLProcessor ()
PSQLProcessor (const PSQLProcessor &x)
Copy constructor.
virtual ~PSQLProcessor ()
PSQLProcessor * clone () const
bool cloneOnConncetion () const
void connect (SampleInput *) throw (nidas::util::IOException)
void disconnect (SampleInput *) throw (nidas::util::IOException)
void connected (SampleOutput *orig, SampleOutput *output) throw ()
void disconnected (SampleOutput *output) throw ()
void setAveragePeriod (int val)
Set average period, in milliseconds.
int getAveragePeriod () const
Get average period, in milliseconds.
const std::set< const
SampleTag * > & getSampleTags () const
Implementation of SampleSource::getSampleTags().
virtual const std::string & getName () const
virtual void setName (const std::string &val)
virtual void setOptional (bool val)
virtual bool isOptional () const
virtual const DSMService * getService () const
What DSMService am I associated with?
virtual void setService (const DSMService *val)
virtual const DSMConfig * getDSMConfig () const
What DSM am I associated with?
virtual void setDSMConfig (const DSMConfig *val)
dsm_sample_id_t getId () const
void setSampleId (int val)
unsigned int getSampleId () const
virtual void connect (SampleSource *)=0 throw (nidas::util::InvalidParameterException,nidas::util::IOException)
Connect a SampleSource to this SampleIOProcessor.
virtual void connect (SampleOutput *output)=0 throw ()
How SampleOutputs notify their SampleConnectionRequester that they are connected.
virtual void disconnect (SampleSource *)=0 throw ()
Disconnect a SampleSource from this SampleIOProcessor.
virtual void disconnect (SampleOutput *output)=0 throw ()
How SampleOutputs notify their SampleConnectionRequester that they wish to be closed, likely do to an IOException.
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual void addRequestedSampleTag (SampleTag *tag) throw (nidas::util::InvalidParameterException)
Add a request for a SampleTag from this SampleIOProcessor.
virtual std::list< const
SampleTag * > getRequestedSampleTags () const
void addSampleTag (const SampleTag *tag) throw ()
Implementation of SampleSource::addSampleTag().
void removeSampleTag (const SampleTag *tag) throw ()
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
const SampleStats & getSampleStats () const
virtual void addOutput (SampleOutput *val)
Add an SampleOutput to this SampleIOProcessor.
virtual const std::list
< SampleOutput * > & getOutputs () const
void addParameter (Parameter *val) throw (nidas::util::InvalidParameterException)
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual void printStatus (std::ostream &, float, int &) throw ()
virtual void init (dsm_time_t) throw ()
virtual void flush ()=0 throw ()
Request that this SampleSource flush it's samples.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void removeRequestedSampleTag (SampleTag *tag)
Allow subclasses to remove requested SampleTags.
Protected Attributes
SampleInput * input
SampleAverager averager
const nidas::core::Site * site
SampleSourceSupport _source
nidas::util::Mutex _tagsMutex
std::list< SampleTag * > _requestedTags
Constructor & Destructor Documentation
PSQLProcessor::PSQLProcessor ()
References MSECS_PER_SEC.
Referenced by clone().
PSQLProcessor::PSQLProcessor (const PSQLProcessor & x)
Copy constructor.
References nidas::core::SampleIOProcessor::setName().
PSQLProcessor::~PSQLProcessor () virtual
Member Function Documentation
virtual void nidas::core::SampleIOProcessor::addOutput (SampleOutput * val) inline virtual inherited
Add an SampleOutput to this SampleIOProcessor.
This is used to add a desired SampleOutput to this SampleIOProcessor. SampleIOProcessor will own the SampleOutput. Once a SampleSource has connected, then SampleIOProcessor is responsible for do SampleOutput::requestConnection, or SampleOutputRequestThread::addConnectRequest() on all these as-yet disconnected outputs.
References nidas::core::SampleIOProcessor::_origOutputs.
void SampleIOProcessor::addParameter (Parameter * val) throw (nidas::util::InvalidParameterException) inherited
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
If a Parameter exists with the same name, it will be replaced with the new Parameter.
void SampleIOProcessor::addRequestedSampleTag (SampleTag * tag) throw (nidas::util::InvalidParameterException) virtual inherited
Add a request for a SampleTag from this SampleIOProcessor.
This SampleIOProcessor will own the SampleTag.
Reimplemented in nidas::dynld::raf::CVIProcessor, and nidas::dynld::StatisticsProcessor.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), and nidas::dynld::raf::CVIProcessor::addRequestedSampleTag().
void nidas::core::SampleIOProcessor::addSampleClient (SampleClient * client) throw () inline virtual inherited
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::addSampleClient().
void nidas::core::SampleIOProcessor::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
void SampleIOProcessor::addSampleTag (const SampleTag * tag) throw () virtual inherited
Implementation of SampleSource::addSampleTag().
Implements nidas::core::SampleSource.
PSQLProcessor * PSQLProcessor::clone () const
References PSQLProcessor().
bool nidas::dynld::psql::PSQLProcessor::cloneOnConncetion () const inline
virtual void nidas::core::SampleConnectionRequester::connect (SampleOutput * output) throw () pure virtual inherited
How SampleOutputs notify their SampleConnectionRequester that they are connected.
Implemented in nidas::core::DSMEngine, nidas::dynld::raf::SyncServer, nidas::core::SampleArchiver, nidas::dynld::StatisticsProcessor, nidas::dynld::raf::CVIProcessor, nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::SampleProcessor.
void PSQLProcessor::connect (SampleInput * newinput) throw (nidas::util::IOException)
References nidas::core::SampleIOProcessor::connect(), nidas::core::Project::findDSM(), nidas::core::SampleTag::getDSMId(), nidas::core::Project::getInstance(), nidas::core::DSMSensor::getName(), nidas::core::DSMSensor::getSampleTags(), nidas::core::DSMConfig::getSensors(), nidas::core::DSMConfig::getSite(), nidas::core::SampleTag::getVariables(), and nidas::core::SampleTag::isProcessed().
virtual void nidas::core::SampleIOProcessor::connect (SampleSource *) throw (nidas::util::InvalidParameterException, nidas::util::IOException) pure virtual inherited
Connect a SampleSource to this SampleIOProcessor.
SampleIOProcessor does not own the SampleSource.
Implemented in nidas::core::SampleArchiver, nidas::dynld::StatisticsProcessor, nidas::dynld::raf::CVIProcessor, nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::SampleProcessor.
Referenced by connect(), nidas::core::DSMEngine::connectProcessors(), and nidas::dynld::RawSampleService::schedule().
void PSQLProcessor::connected (SampleOutput * orig, SampleOutput * output) throw ()
References nidas::dynld::psql::PSQLSampleOutput::addSampleTag(), nidas::util::Logger::getInstance(), nidas::util::Logger::log(), and LOG_ERR.
virtual void nidas::core::SampleConnectionRequester::disconnect (SampleOutput * output) throw () pure virtual inherited
How SampleOutputs notify their SampleConnectionRequester that they wish to be closed, likely do to an IOException.
Implemented in nidas::core::DSMEngine, nidas::dynld::raf::SyncServer, nidas::dynld::StatisticsProcessor, nidas::core::SampleArchiver, nidas::dynld::raf::CVIProcessor, nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::SampleProcessor.
Referenced by nidas::core::SampleOutputBase::disconnect().
void PSQLProcessor::disconnect (SampleInput * oldinput) throw (nidas::util::IOException)
References nidas::core::SampleIOProcessor::disconnect(), nidas::core::DSMSensor::flush(), and nidas::core::DSMConfig::getSensors().
virtual void nidas::core::SampleIOProcessor::disconnect (SampleSource *) throw () pure virtual inherited
Disconnect a SampleSource from this SampleIOProcessor.
Implemented in nidas::core::SampleArchiver, nidas::dynld::StatisticsProcessor, nidas::dynld::raf::CVIProcessor, nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::SampleProcessor.
Referenced by disconnect(), nidas::core::DSMEngine::disconnectProcessors(), and nidas::dynld::RawSampleService::interrupt().
void PSQLProcessor::disconnected (SampleOutput * output) throw ()
virtual void nidas::core::SampleSource::flush () throw () pure virtual inherited
Request that this SampleSource flush it's samples.
One must think about whether to call flush() on SampleClients of this SampleSource. A SampleClient may have multiple SampleSources and a flush() of it when one SampleSource() is done may not be what is wanted.
Implemented in nidas::core::DSMSensor, nidas::dynld::raf::SyncRecordSource, nidas::dynld::SampleInputStream, nidas::core::NearestResamplerAtRate, nidas::core::SamplePipeline, nidas::core::SampleSorter, nidas::core::SampleSourceSupport, nidas::core::SampleBuffer, nidas::core::NearestResampler, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleAverager, nidas::dynld::isff::PacketInputStream, nidas::dynld::StatisticsProcessor, nidas::core::SampleThread, nidas::dynld::raf::CVIProcessor, nidas::core::SampleArchiver, nidas::core::Resampler, and nidas::dynld::SampleProcessor.
Referenced by nidas::core::DSMEngine::disconnectProcessors().
void SampleIOProcessor::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual inherited
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::raf::CVIProcessor.
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Parameter::createParameter(), nidas::core::DOMable::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::Project::getInstance(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::SampleTag::getSampleId(), nidas::core::SampleTag::setSampleId(), nidas::core::SampleTag::setSensorId(), and nidas::util::Exception::what().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), and nidas::core::DSMConfig::fromDOMElement().
int nidas::dynld::psql::PSQLProcessor::getAveragePeriod () const inline
Get average period, in milliseconds.
References averager.
int nidas::core::SampleIOProcessor::getClientCount () const throw () inline virtual inherited
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getClientCount().
virtual const DSMConfig* nidas::core::SampleIOProcessor::getDSMConfig () const inline virtual inherited
What DSM am I associated with?
References nidas::core::SampleIOProcessor::_dsm.
dsm_sample_id_t nidas::core::SampleIOProcessor::getId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_FULL_ID.
const std::string & SampleIOProcessor::getName () const virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by nidas::dynld::raf::CVIProcessor::fromDOMElement(), nidas::dynld::RawSampleService::schedule(), and nidas::dynld::StatisticsProcessor::~StatisticsProcessor().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
virtual const std::list<SampleOutput*>& nidas::core::SampleIOProcessor::getOutputs () const inline virtual inherited
References nidas::core::SampleIOProcessor::_origOutputs.
Referenced by nidas::core::Project::findServerSampleOutputStreamFileSets(), nidas::dynld::isff::GOESProject::GOESProject(), and StatsProcess::run().
const std::list<const Parameter*>& nidas::core::SampleIOProcessor::getParameters () const inline inherited
Get list of parameters.
References nidas::core::SampleIOProcessor::_constParameters.
SampleSource* nidas::core::SampleIOProcessor::getProcessedSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References nidas::core::SampleIOProcessor::_source.
SampleSource* nidas::core::SampleIOProcessor::getRawSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
std::list< const SampleTag * > SampleIOProcessor::getRequestedSampleTags () const virtual inherited
References nidas::core::SampleIOProcessor::_constRequestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::core::SampleTagIterator::hasNext(), and StatsProcess::listOutputSamples().
unsigned int nidas::core::SampleIOProcessor::getSampleId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_SPS_ID.
Referenced by StatsProcess::listOutputSamples(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
const SampleStats& nidas::core::SampleIOProcessor::getSampleStats () const inline virtual inherited
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleStats().
SampleTagIterator nidas::core::SampleIOProcessor::getSampleTagIterator () const inline virtual inherited
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::getSampleTagIterator().
const std::set<const SampleTag*>& nidas::dynld::psql::PSQLProcessor::getSampleTags () const inline virtual
Implementation of SampleSource::getSampleTags().
Reimplemented from nidas::core::SampleIOProcessor.
References averager, and nidas::core::SampleAverager::getSampleTags().
virtual const DSMService* nidas::core::SampleIOProcessor::getService () const inline virtual inherited
What DSMService am I associated with?
References nidas::core::SampleIOProcessor::_service.
virtual void nidas::core::SampleIOProcessor::init (dsm_time_t) throw () inline virtual inherited
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
Referenced by nidas::dynld::RawSampleService::schedule().
virtual bool nidas::core::SampleIOProcessor::isOptional () const inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
Referenced by nidas::dynld::RawSampleService::schedule().
virtual void nidas::core::SampleIOProcessor::printStatus (std::ostream & , float , int &) throw () inline virtual inherited
Reimplemented in nidas::dynld::raf::SyncRecordGenerator, and nidas::core::SampleArchiver.
Referenced by nidas::dynld::RawSampleService::printStatus().
void SampleIOProcessor::removeRequestedSampleTag (SampleTag * tag) protected inherited
Allow subclasses to remove requested SampleTags.
The tag will be deleted.
References nidas::core::SampleIOProcessor::_constRequestedTags, nidas::core::SampleIOProcessor::_requestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
void nidas::core::SampleIOProcessor::removeSampleClient (SampleClient * c) throw () inline virtual inherited
Remove a SampleClient from this SampleSource.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::removeSampleClient().
void nidas::core::SampleIOProcessor::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References nidas::core::SampleIOProcessor::_source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
void SampleIOProcessor::removeSampleTag (const SampleTag * tag) throw () virtual inherited
Implements nidas::core::SampleSource.
void nidas::dynld::psql::PSQLProcessor::setAveragePeriod (int val) inline
Set average period, in milliseconds.
References averager.
virtual void nidas::core::SampleIOProcessor::setDSMConfig (const DSMConfig * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_dsm.
Referenced by nidas::core::DSMConfig::fromDOMElement().
void SampleIOProcessor::setName (const std::string & val) virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by PSQLProcessor(), nidas::core::SampleArchiver::SampleArchiver(), nidas::dynld::StatisticsProcessor::StatisticsProcessor(), and nidas::dynld::raf::SyncRecordGenerator::SyncRecordGenerator().
virtual void nidas::core::SampleIOProcessor::setOptional (bool val) inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
void nidas::core::SampleIOProcessor::setSampleId (int val) inline inherited
References nidas::core::SampleIOProcessor::_id, and SET_SPS_ID.
virtual void nidas::core::SampleIOProcessor::setService (const DSMService * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_service.
Referenced by nidas::core::DSMService::fromDOMElement().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
std::list<SampleTag*> nidas::core::SampleIOProcessor::_requestedTags protected inherited
Referenced by nidas::core::SampleIOProcessor::removeRequestedSampleTag(), nidas::dynld::StatisticsProcessor::selectRequestedSampleTags(), and nidas::core::SampleIOProcessor::~SampleIOProcessor().
SampleSourceSupport nidas::core::SampleIOProcessor::_source protected inherited
Referenced by nidas::core::SampleIOProcessor::addSampleClient(), nidas::core::SampleIOProcessor::addSampleClientForTag(), nidas::core::SampleIOProcessor::getClientCount(), nidas::core::SampleIOProcessor::getProcessedSampleSource(), nidas::core::SampleIOProcessor::getSampleStats(), nidas::core::SampleIOProcessor::getSampleTagIterator(), nidas::core::SampleIOProcessor::getSampleTags(), nidas::core::SampleIOProcessor::removeSampleClient(), and nidas::core::SampleIOProcessor::removeSampleClientForTag().
nidas::util::Mutex nidas::core::SampleIOProcessor::_tagsMutex mutable protected inherited
Referenced by nidas::core::SampleIOProcessor::getRequestedSampleTags(), nidas::core::SampleIOProcessor::removeRequestedSampleTag(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
SampleAverager nidas::dynld::psql::PSQLProcessor::averager protected
Referenced by getAveragePeriod(), getSampleTags(), and setAveragePeriod().
SampleInput* nidas::dynld::psql::PSQLProcessor::input protected
const nidas::core::Site* nidas::dynld::psql::PSQLProcessor::site protected
The documentation for this class was generated from the following files:
nidas/dynld/psql/PSQLProcessor.h
nidas/dynld/psql/PSQLProcessor.cc