nidas: nidas::dynld::isff::SonicAnemometer Class Reference
nidas::dynld::isff::SonicAnemometer Class Reference
A class for performing the common processes on wind data from a 3D sonic anemometer.
#include <SonicAnemometer.h>
Public Member Functions
SonicAnemometer ()
~SonicAnemometer ()
bool process (const nidas::core::Sample *samp, std::list< const nidas::core::Sample * > &results) throw ()
Basic process method for sonic anemometer wind plus temperature: u,v,w,tc parsed from an ASCII sample.
void setBias (int i, double val)
double getBias (int i) const
double getVazimuth () const
void setVazimuth (double val)
Wind vectors in geographic coordinates are expressed by U, the component of the wind blowing toward the east, and V, the component of the wind blowing toward the north.
double getLeanDegrees () const
void setLeanDegrees (double val)
double getLeanAzimuthDegrees () const
void setLeanAzimuthDegrees (double val)
void setDespike (bool val)
bool getDespike () const
void setOutlierProbability (double val)
double getOutlierProbability () const
void setDiscLevelMultiplier (double val)
double getDiscLevelMultiplier () const
double getDiscLevel () const
void setTcOffset (double val)
double getTcOffset () const
void setTcSlope (double val)
double getTcSlope () const
void setDoHorizontalRotation (bool val)
Should 2D horizontal rotations of U,V be applied?
void setDoTiltCorrection (bool val)
Should 3D tilt corrections be applied?
void despike (nidas::core::dsm_time_t tt, float *uvwt, int n, bool *spikeOrMissing) throw ()
void offsetsTiltAndRotate (nidas::core::dsm_time_t tt, float *uvwt) throw ()
Do standard bias removal, tilt correction and horizontal rotation of 3d sonic anemometer data.
void validate () throw (nidas::util::InvalidParameterException)
Validate the configuration of this sensor.
void validateSscanfs () throw (nidas::util::InvalidParameterException)
Warn user if number of scanf fields does not match number expected from variables in sample.
virtual void parseParameters () throw (nidas::util::InvalidParameterException)
Parse the list of nidas::core::Parameter that are associated with this sensor.
virtual void checkSampleTags () throw (nidas::util::InvalidParameterException)
Check the SampleTags that are defined for this sensor.
nidas::util::Termios & termios ()
Expose the Termios.
const nidas::util::Termios & getTermios () const
Get a read-only copy of the Termios.
SampleScanner * buildSampleScanner () throw (nidas::util::InvalidParameterException)
Calls CharacterSensor::buildSampleScanner(), and then sets the per-byte transmission delay for that scanner: SampleScanner::setUsecsPerByte().
IODevice * buildIODevice () throw (nidas::util::IOException)
Creates an IODevice depending on the device name prefix: name prefix type of IODevice inet: TCPSocketIODevice sock: TCPSocketIODevice usock: UDPSocketIODevice btspp: BluetoothRFCommSocketIODevice all others SerialPortIODevice.
void open (int flags) throw (nidas::util::IOException, nidas::util::InvalidParameterException)
Open the device connected to the sensor.
void close () throw (nidas::util::IOException)
close my associated device.
void applyTermios () throw (nidas::util::IOException)
If the underlying IODevice is a SerialPortIODevice, update the current Termios to the device.
void setMessageParameters (unsigned int len, const std::string &sep, bool eom) throw (nidas::util::InvalidParameterException,nidas::util::IOException)
Set message separator and message length parameters, which are used to parse and time-tag samples from the IODevice.
void printStatus (std::ostream &ostr) throw ()
bool isPrompting () const
Is prompting active, i.e.
void startPrompting () throw (nidas::util::IOException)
Start the prompters.
void stopPrompting () throw (nidas::util::IOException)
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
int getUsecsPerByte () const
If the underlying IODevice is a SerialPortIODevice, return the value of SerialPortIODevice::getUsecsPerByte(), otherwise return 0, which means no timetag correction for transmission delay will be applied.
void init () throw (nidas::util::InvalidParameterException)
Initialize the CharacterSensor instance for post-processing.
const std::string & getMessageSeparator () const
Get message separator with backslash sequences replaced by their intended character.
const std::string getBackslashedMessageSeparator () const
Get message separator with backslash sequences added back.
bool getMessageSeparatorAtEOM () const
int getMessageLength () const
virtual void addPrompt (const std::string &promptString, double promptRate, double promptOffset)
Prompting Sensors can have multiple prompts and rates.
const std::list< Prompt > & getPrompts () const
virtual bool isPrompted () const
Is this a prompted sensor.
virtual void togglePrompting () throw (nidas::util::IOException)
void setInitString (const std::string &val)
Set the initialization string(s) for this sensor.
const std::string & getInitString () const
virtual void sendInitString () throw (nidas::util::IOException)
bool getNullTerminated () const
int getNumScanfFailures () const
How many samples have resulted in complete scanf failures - nothing parsed, because the sensor messages do not correspond to the sscanf format.
int getNumScanfPartials () const
How many samples have been partially scanned, because a character in the middle of a message conflicts with the sscanf format.
const std::list< AsciiSscanf * > & getScanfers () const
Return the list of AsciiSscanfs requested for this CharacterSensor.
int getMaxScanfFields () const
The maximum number of fields in any of the AsciiSscanfs for this CharacterSensor.
virtual bool process (const Sample *, std::list< const Sample * > &result) throw ()
Process a raw sample, which in this case means do a sscanf on the character string contents, creating a processed sample of binary floating point data.
bool doesAsciiSscanfs ()
void setDSMConfig (const DSMConfig *val)
Set the DSMConfig for this sensor.
const DSMConfig * getDSMConfig () const
What DSMConfig am I associated with?
const Site * getSite () const
What Site am I associated with?
virtual void setDeviceName (const std::string &val)
Set the name of the system device that the sensor is connected to.
virtual const std::string & getDeviceName () const
Fetch the name of the system device that the sensor is connected to.
virtual void setClassName (const std::string &val)
Set the class name.
virtual const std::string & getClassName () const
Fetch the class name.
virtual void setCatalogName (const std::string &val)
Set the name of the catalog entry for this sensor.
virtual const std::string & getCatalogName () const
Fetch the name of the catalog entry for this sensor.
const std::string & getDSMName () const
Fetch the DSM name.
virtual std::string getName () const
Return a name that should fully identify this sensor.
const std::string & getLocation () const
Location string.
void setLocation (const std::string &val)
const std::string & getSuffix () const
Sensor suffix, which is added to variable names.
void setSuffix (const std::string &val)
int getStation () const
void setStation (int val)
void setHeight (const std::string &val)
Set sensor height above ground via a string which is added to variable names.
void setHeight (float val)
Set sensor height above ground.
const std::string & getHeightString () const
Get sensor height above ground in a string.
float getHeight () const
Get sensor height above ground.
void setDepth (const std::string &val)
Set sensor depth below ground via a string which is added to variable names.
void setDepth (float val)
Set sensor depth below ground.
const std::string & getDepthString () const
Get sensor depth below ground in a string.
float getDepth () const
Get sensor depth below ground.
const std::string & getFullSuffix () const
Full sensor suffix, the concatenation of the sensor suffix, if any, and the height or depth string, if any.
std::string expandString (const std::string &input) const
Utility function to expand ${TOKEN} or $TOKEN fields in a string with their value from getTokenValue().
bool getTokenValue (const std::string &token, std::string &value) const
Implement a lookup for tokens that I know about, like $HEIGHT.
const Dictionary & getDictionary () const
SampleSource * getRawSampleSource ()
Implementation of SampleSource::getRawSampleSource().
SampleSource * getProcessedSampleSource ()
Implementation of SampleSource::getProcessedSampleSource().
const SampleTag * getRawSampleTag () const
Convenience function to get my one-and-only raw SampleTag().
virtual void addSampleTag (SampleTag *val) throw (nidas::util::InvalidParameterException)
Add a SampleTag to this sensor.
virtual void removeSampleTag (SampleTag *val) throw ()
Remove val from the list of SampleTags, and delete it.
std::list< const SampleTag * > getSampleTags () const
Implementation of SampleSource::getSampleTags().
std::list< SampleTag * > & getSampleTags ()
Non-const method to get a list of non-const pointers to SampleTags.
SampleTagIterator getSampleTagIterator () const
void addSampleClient (SampleClient *c) throw ()
Add a SampleClient to this SampleSource.
void removeSampleClient (SampleClient *c) throw ()
Remove a SampleClient from this SampleSource This will also remove a SampleClient if it has been added with addSampleClientForTag().
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a SampleClient to this SampleSource.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void flush () throw ()
Implementation of SampleClient::flush().
void distributeRaw (const Sample *s) throw ()
Distribute a raw sample which has been read from my file descriptor in real time.
const SampleStats & getSampleStats () const
virtual int getReadFd () const
virtual int getWriteFd () const
virtual bool reopenOnIOException () const
Whether to reopen this sensor on an IOException.
void setId (dsm_sample_id_t val)
Set the various levels of the sensor identification.
void setSensorId (unsigned int val)
void setDSMId (unsigned int val)
dsm_sample_id_t getId () const
Get the various levels of the samples identification.
unsigned int getDSMId () const
unsigned int getSensorId () const
virtual void setLatency (float val) throw (nidas::util::InvalidParameterException)
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
virtual float getLatency () const
virtual void setTimeoutMsecs (int val)
Set the sensor timeout value in milliseconds.
virtual int getTimeoutMsecs () const
int getTimeoutCount () const
void incrementTimeoutCount ()
void addParameter (Parameter *val)
Add a parameter to this DSMSensor.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
const Parameter * getParameter (const std::string &name) const
Fetch a parameter by name.
void setIODevice (IODevice *val)
Set the IODevice for this sensor.
void setSampleScanner (SampleScanner *val)
Set the SampleScanner for this sensor.
virtual int getDefaultMode () const
How do I want to be opened.
virtual void setDefaultMode (int val)
virtual size_t getBytesAvailable () const throw (nidas::util::IOException)
How many bytes are available to read on this sensor.
virtual size_t read (void *buf, size_t len) throw (nidas::util::IOException)
Read from the device (duh).
virtual size_t read (void *buf, size_t len, int msecTimeout) throw (nidas::util::IOException)
Read from the device with a timeout.
virtual size_t write (const void *buf, size_t len) throw (nidas::util::IOException)
Write to the device (duh).
virtual void ioctl (int request, void *buf, size_t len) throw (nidas::util::IOException)
Perform an ioctl on the device.
virtual bool readSamples () throw (nidas::util::IOException)
Read samples from my associated file descriptor, and distribute() them to my RawSampleClient's.
virtual Sample * nextSample ()
Extract the next sample from the buffer.
bool receive (const Sample *s) throw ()
A DSMSensor can be used as a SampleClient, meaning it receives its own raw samples.
void printStatusHeader (std::ostream &ostr) throw ()
void printStatusTrailer (std::ostream &ostr) throw ()
void calcStatistics (unsigned int periodUsec)
Update the sensor sampling statistics.
unsigned int getMaxSampleLength () const
unsigned int getMinSampleLength () const
float getObservedSamplingRate () const
float getObservedDataRate () const
size_t getBadTimeTagCount () const
VariableIterator getVariableIterator () const
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
virtual void setTypeName (const std::string &val)
Set the type name of this sensor, e.g.
virtual const std::string & getTypeName (void) const
Get the type name of this sensor.
bool getDuplicateIdOK () const
getDuplicateIdOK will be true if it is OK for samples from this sensor to have identical IDs to samples from another sensor.
void setDuplicateIdOK (bool val)
Set the duplicate ID attribute of this DSMSensor.
virtual bool getApplyVariableConversions () const
virtual void setApplyVariableConversions (bool val)
virtual int getDriverTimeTagUsecs () const
virtual void setDriverTimeTagUsecs (int val)
void addCalFile (CalFile *val)
Add a calibration file for this DSMSensor.
const std::map< std::string,
CalFile * > & getCalFiles ()
Return the collection of CalFiles, mapped by name.
CalFile * getCalFile (const std::string &name)
Return a CalFile by its getName().
void removeCalFiles ()
Remove all CalFiles.
virtual void executeXmlRpc (XmlRpc::XmlRpcValue &, XmlRpc::XmlRpcValue &) throw ()
Method invoked when the DSMEngineIntf XmlRpcServer receives a "SensorAction" request, with a "device" string matching the string that this DSMSensor registers via DSMEngine::registerSensorWithXmlRpc(string,DSMServer*).
virtual const std::list
< SampleTag * > & getNonConstSampleTags ()
We'll allow derived classes and calibration applications to change the SampleTags, so this method returns a list of non-constant SampleTags.
Static Public Member Functions
static const std::string getClassName (const xercesc::DOMElement *node, const Project *project) throw (nidas::util::InvalidParameterException)
Crawl through the DOM tree for a DSMSensor to find the class name - scanning the catalog entry if necessary.
static void deleteLooper ()
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void initPrompting () throw (nidas::util::IOException)
Perform whatever is necessary to initialize prompting right after the device is opened.
void shutdownPrompting () throw (nidas::util::IOException)
Shutdown prompting, typically done when a device is closed.
void unixDevInit (int flags) throw (nidas::util::IOException)
void setPromptRate (const double val)
Set the rate at which <sensor> prompts are sent to this sensor.
double getPromptRate () const
void setPromptOffset (const double val)
double getPromptOffset () const
void setPromptString (const std::string &val)
Set the <sensor> prompt string for this sensor.
const std::string & getPromptString () const
virtual int scanSample (AsciiSscanf *sscanf, const char *inputstr, float *data_ptr)
bool readBuffer () throw (nidas::util::IOException)
Read into my SampleScanner's buffer.
bool readBuffer (int msecTimeout) throw (nidas::util::IOException)
Read into my SampleScanner's buffer.
void clearBuffer ()
Clear the internal buffer.
IODevice * getIODevice () const
SampleScanner * getSampleScanner () const
void setFullSuffix (const std::string &val)
virtual int getLagUsecs () const
Return the sampling lag for this sensor in microseconds.
virtual double getLagSecs () const
Return the sampling lag for this sensor in seconds.
virtual void setLagSecs (double val)
Set the sampling lag for this sensor in seconds.
Static Protected Member Functions
static Looper * getLooper ()
Fetch a pointer to a static instance of a Looper thread.
Protected Attributes
nidas::core::dsm_time_t _ttlast [4]
double _bias [3]
bool _allBiasesNaN
bool _despike
nidas::core::AdaptiveDespiker _despiker [4]
WindRotator _rotator
WindTilter _tilter
double _tcOffset
double _tcSlope
bool _horizontalRotation
Should horizontal rotation of U,V be performed?
bool _tiltCorrection
Should 3D tilt correction be applied?
nidas::core::dsm_sample_id_t _sampleId
Id of output sample.
int _diagIndex
If user requests "diag" or "status", its index in the output sample.
int _ldiagIndex
If user requests "ldiag", its index in the output sample.
int _spdIndex
If user requests wind speed, variable name "spd", its index in the output sample.
int _dirIndex
If user requests wind direction, variable name "dir", its index in the output sample.
unsigned int _noutVals
unsigned int _numParsed
Number of variables that are parsed from input, i.e.
nidas::core::CalFile * _oaCalFile
CalFile containing wind offsets and rotation angles.
bool _unusualOrientation
Is the sonic oriented in a unusual way, e.g.
int _tx [3]
Index transform vector for wind components.
int _sx [3]
Wind component sign conversion.
double _shadowFactor
Transducer shadow (aka flow distortion) correction factor.
Static Protected Attributes
static const int DATA_GAP_USEC = 60000000
Private Member Functions
SonicAnemometer (const SonicAnemometer &x)
SonicAnemometer & operator= (const SonicAnemometer &x)
Detailed Description
A class for performing the common processes on wind data from a 3D sonic anemometer.
Constructor & Destructor Documentation
SonicAnemometer::SonicAnemometer ()
SonicAnemometer::~SonicAnemometer ()
nidas::dynld::isff::SonicAnemometer::SonicAnemometer (const SonicAnemometer & x) private
Member Function Documentation
void DSMSensor::addCalFile (CalFile * val) inherited
Add a calibration file for this DSMSensor.
After this method is finished, DSMSensor will own the pointer, and will delete it in the DSMSensor destructor.
References nidas::core::DSMSensor::_calFiles, and nidas::core::CalFile::getName().
Referenced by nidas::core::DSMSensor::fromDOMElement().
void DSMSensor::addParameter (Parameter * val) inherited
Add a parameter to this DSMSensor.
DSMSensor will then own the pointer and will delete it in its destructor. If a Parameter exists with the same name, it will be replaced with the new Parameter.
References nidas::core::DSMSensor::_constParameters, nidas::core::DSMSensor::_parameters, and nidas::core::Parameter::getName().
Referenced by nidas::core::DSMSensor::fromDOMElement().
virtual void nidas::core::CharacterSensor::addPrompt (const std::string & promptString, double promptRate, double promptOffset) inline virtual inherited
Prompting Sensors can have multiple prompts and rates.
Add another prompt and rate to this sensor.
Parameters
promptString May contain backslash excape sequences.
promptRate prompts/sec.
References nidas::core::CharacterSensor::_prompted, nidas::core::CharacterSensor::_prompts, nidas::core::Prompt::setOffset(), nidas::core::Prompt::setRate(), and nidas::core::Prompt::setString().
Referenced by nidas::core::CharacterSensor::validate().
void nidas::core::DSMSensor::addSampleClient (SampleClient * c) throw () inline virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::addSampleClient().
Referenced by nidas::core::SamplePipeline::addSampleClient(), and nidas::core::SamplePipeline::addSampleClientForTag().
void nidas::core::DSMSensor::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
Referenced by nidas::core::SamplePipeline::addSampleClientForTag().
void DSMSensor::addSampleTag (SampleTag * val) throw (nidas::util::InvalidParameterException) virtual inherited
Add a SampleTag to this sensor.
DSMSensor will own the SampleTag. Throw an exception the DSMSensor cannot support the sample (bad rate, wrong number of variables, etc). Note that a SampleTag may be changed after it has been added. addSampleTag() is called when a sensor is initialized from the sensor catalog. The SampleTag may be modified later if it is overridden in the actual sensor entry. For this reason, it is wise to wait to scan the SampleTags of a DSMSensor in the validate(), init() or open() methods, which are invoked after fromDOMElement.
Reimplemented in nidas::dynld::raf::DSMAnalogSensor, nidas::dynld::DSC_A2DSensor, nidas::dynld::A2DSensor, nidas::dynld::raf::PSI9116_Sensor, nidas::dynld::iss::TiltSensor, nidas::dynld::isff::PropVane, nidas::dynld::TSI_CPC3772, nidas::dynld::GPS_NMEA_Serial, and nidas::dynld::GPS_Novatel_Serial.
References GET_DSM_ID, GET_SHORT_ID, nidas::util::Logger::getInstance(), nidas::util::Logger::log(), and LOG_WARNING.
Referenced by nidas::dynld::GPS_NMEA_Serial::addSampleTag(), nidas::dynld::TSI_CPC3772::addSampleTag(), nidas::dynld::isff::PropVane::addSampleTag(), nidas::dynld::iss::TiltSensor::addSampleTag(), nidas::dynld::raf::PSI9116_Sensor::addSampleTag(), nidas::dynld::A2DSensor::addSampleTag(), nidas::dynld::RawSampleService::connect(), and nidas::core::DSMSensor::fromDOMElement().
void SerialSensor::applyTermios () throw (nidas::util::IOException) inherited
If the underlying IODevice is a SerialPortIODevice, update the current Termios to the device.
References nidas::core::SerialSensor::_serialDevice, nidas::core::SerialSensor::_termios, nidas::core::SerialPortIODevice::applyTermios(), and nidas::core::SerialPortIODevice::termios().
IODevice * SerialSensor::buildIODevice () throw (nidas::util::IOException) virtual inherited
Creates an IODevice depending on the device name prefix: name prefix type of IODevice inet: TCPSocketIODevice sock: TCPSocketIODevice usock: UDPSocketIODevice btspp: BluetoothRFCommSocketIODevice all others SerialPortIODevice.
If a SerialPortIODevice is created, the Termios of this SerialSensor is copied to the device, which will then be applied when the device is opened.
Reimplemented from nidas::core::CharacterSensor.
References nidas::core::SerialSensor::_rts485, nidas::core::SerialSensor::_serialDevice, nidas::core::SerialSensor::_termios, nidas::core::DSMSensor::getDeviceName(), nidas::core::SerialPortIODevice::setRTS485(), and nidas::core::SerialPortIODevice::termios().
SampleScanner * SerialSensor::buildSampleScanner () throw (nidas::util::InvalidParameterException) virtual inherited
Calls CharacterSensor::buildSampleScanner(), and then sets the per-byte transmission delay for that scanner: SampleScanner::setUsecsPerByte().
Reimplemented from nidas::core::CharacterSensor.
Reimplemented in nidas::dynld::GPS_NMEA_Serial.
References nidas::core::CharacterSensor::buildSampleScanner(), DLOG, nidas::core::DSMSensor::getName(), nidas::core::SerialSensor::getUsecsPerByte(), and nidas::core::SampleScanner::setUsecsPerByte().
void nidas::core::DSMSensor::calcStatistics (unsigned int periodUsec) inline inherited
Update the sensor sampling statistics.
Should be called every periodUsec by a user of this sensor.
Parameters
periodUsec Statistics period.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::calcStatistics().
Referenced by nidas::core::SensorHandler::calcStatistics().
void SonicAnemometer::checkSampleTags () throw (nidas::util::InvalidParameterException) virtual
Check the SampleTags that are defined for this sensor.
Reimplemented in nidas::dynld::isff::CSAT3_Sonic, nidas::dynld::isff::CSI_IRGA_Sonic, and nidas::dynld::isff::ATIK_Sonic.
References nidas::core::SampleTag::getId(), nidas::core::Variable::getName(), nidas::core::SampleTag::getVariableIterator(), nidas::core::VariableIterator::hasNext(), and nidas::core::VariableIterator::next().
Referenced by nidas::dynld::isff::ATIK_Sonic::checkSampleTags(), nidas::dynld::isff::CSI_IRGA_Sonic::checkSampleTags(), and nidas::dynld::isff::CSAT3_Sonic::checkSampleTags().
void nidas::core::DSMSensor::clearBuffer () inline protected inherited
Clear the internal buffer.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::clearBuffer().
Referenced by nidas::dynld::raf::UHSAS_Serial::sendInitString().
void SerialSensor::close () throw (nidas::util::IOException) virtual inherited
close my associated device.
Reimplemented from nidas::core::DSMSensor.
Reimplemented in nidas::dynld::raf::PPT_Serial, nidas::dynld::raf::VCSEL_Serial, nidas::dynld::raf::VCSEL2_Serial, and nidas::dynld::isff::MOSMote.
References nidas::core::DSMSensor::close(), and nidas::core::SerialSensor::shutdownPrompting().
Referenced by nidas::dynld::isff::MOSMote::close().
void DSMSensor::deleteLooper () static inherited
References nidas::core::DSMSensor::_looper, and nidas::core::DSMSensor::_looperMutex.
Referenced by nidas::core::DSMEngine::main().
void SonicAnemometer::despike (nidas::core::dsm_time_t tt, float * uvwt, int n, bool * spikeOrMissing) throw ()
void nidas::core::DSMSensor::distributeRaw (const Sample * s) throw () inline inherited
Distribute a raw sample which has been read from my file descriptor in real time.
References nidas::core::DSMSensor::_rawSource, and nidas::core::SampleSourceSupport::distribute().
bool CharacterSensor::doesAsciiSscanfs () inherited
Returns
: true if this CharacterSensor as been configured to use one or more AsciiSscanf objects to parse its data.
References nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTag::getScanfFormat(), and nidas::core::SampleTagIterator::hasNext().
Referenced by nidas::core::CharacterSensor::buildSampleScanner().
virtual void nidas::core::DSMSensor::executeXmlRpc (XmlRpc::XmlRpcValue & , XmlRpc::XmlRpcValue &) throw () inline virtual inherited
Method invoked when the DSMEngineIntf XmlRpcServer receives a "SensorAction" request, with a "device" string matching the string that this DSMSensor registers via DSMEngine::registerSensorWithXmlRpc(string,DSMServer*).
The default base class method does nothing.
Reimplemented in nidas::dynld::raf::DSMAnalogSensor, and nidas::dynld::raf::PSI9116_Sensor.
Referenced by nidas::core::DSMEngineIntf::SensorAction::execute().
std::string nidas::core::DSMSensor::expandString (const std::string & input) const inline inherited
Utility function to expand ${TOKEN} or $TOKEN fields in a string with their value from getTokenValue().
If curly brackets are not used, then the TOKEN should be delimited by a '/', a '.' or the end of string, e.g.: xxx/yyy/$ZZZ.dat
References nidas::core::DSMSensor::_dictionary, and nidas::core::Dictionary::expandString().
Referenced by nidas::core::DSMSensor::fromDOMElement(), and nidas::core::CalFile::open().
void nidas::core::DSMSensor::flush () throw () inline virtual inherited
Implementation of SampleClient::flush().
This is where a DSMSensor's process() method could send out any buffered results that might be ready.
Implements nidas::core::SampleClient.
Referenced by nidas::dynld::psql::PSQLProcessor::disconnect().
void SerialSensor::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual inherited
Initialize myself from a xercesc::DOMElement.
Reimplemented from nidas::core::CharacterSensor.
Reimplemented in nidas::dynld::isff::PropVane.
References nidas::util::Termios::EVEN, nidas::core::CharacterSensor::fromDOMElement(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::util::Termios::NONE, and nidas::util::Termios::ODD.
Referenced by nidas::dynld::isff::PropVane::fromDOMElement(), and nidas::dynld::iss::TiltSensor::throw().
virtual bool nidas::core::DSMSensor::getApplyVariableConversions () const inline virtual inherited
References nidas::core::DSMSensor::_applyVariableConversions.
Referenced by nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::raf::DSMArincSensor::init(), and nidas::dynld::raf::SppSerial::validate().
const std::string nidas::core::CharacterSensor::getBackslashedMessageSeparator () const inline inherited
Get message separator with backslash sequences added back.
References nidas::core::CharacterSensor::_messageSeparator, and nidas::util::addBackslashSequences().
size_t nidas::core::DSMSensor::getBadTimeTagCount () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getBadTimeTagCount().
Referenced by nidas::core::DSMSensor::printStatus().
double nidas::dynld::isff::SonicAnemometer::getBias (int i) const inline
References _bias.
virtual size_t nidas::core::DSMSensor::getBytesAvailable () const throw (nidas::util::IOException) inline virtual inherited
How many bytes are available to read on this sensor.
See Also
IODevice::getBytesAvailable().
References nidas::core::DSMSensor::_iodev, and nidas::core::IODevice::getBytesAvailable().
CalFile * DSMSensor::getCalFile (const std::string & name) inherited
Return a CalFile by its getName().
Will return NULL if not found.
References nidas::core::DSMSensor::_calFiles.
const std::map<std::string,CalFile*>& nidas::core::DSMSensor::getCalFiles () inline inherited
Return the collection of CalFiles, mapped by name.
References nidas::core::DSMSensor::_calFiles.
Referenced by A2DSensorItem::getCalFileName(), A2DSensorItem::getSerialNumberString(), AutoCalClient::readCalFile(), sensorTitle(), PConfig::showCalFiles(), and Document::updateSensor().
virtual const std::string& nidas::core::DSMSensor::getCatalogName () const inline virtual inherited
Fetch the name of the catalog entry for this sensor.
References nidas::core::DSMSensor::_catalogName.
Referenced by DSMItem::child(), Extract2D::countParticles(), parseOther(), nidas::core::DSMSensor::printStatus(), Extract2D::run(), sensorTitle(), and PConfig::showCalFiles().
virtual const std::string& nidas::core::DSMSensor::getClassName () const inline virtual inherited
Fetch the class name.
References nidas::core::DSMSensor::_className.
Referenced by DSMItem::child(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DSMSensor::getClassName(), parseAnalog(), parseOther(), nidas::core::DSMSensor::printStatus(), nidas::core::DSMConfig::sensorFromDOMElement(), sensorTitle(), Calibrator::setup(), PConfig::showAll(), PConfig::showCalFiles(), and PConfig::showSensorClasses().
const string DSMSensor::getClassName (const xercesc::DOMElement * node, const Project * project) throw (nidas::util::InvalidParameterException) static inherited
Crawl through the DOM tree for a DSMSensor to find the class name - scanning the catalog entry if necessary.
References nidas::core::XDOMElement::getAttributeValue(), and nidas::core::DSMSensor::getClassName().
int nidas::core::DSMSensor::getClientCount () const throw () inline virtual inherited
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::getClientCount().
virtual int nidas::core::DSMSensor::getDefaultMode () const inline virtual inherited
How do I want to be opened.
The user can ignore it if they want to.
Returns
one of O_RDONLY, O_WRONLY or O_RDWR.
References nidas::core::DSMSensor::_defaultMode.
Referenced by nidas::core::DSMSensor::fromDOMElement(), and nidas::core::SensorOpener::run().
float nidas::core::DSMSensor::getDepth () const inline inherited
Get sensor depth below ground.
Returns
Depth of sensor below ground, in meters.
References nidas::core::DSMSensor::_height.
const std::string& nidas::core::DSMSensor::getDepthString () const inline inherited
Get sensor depth below ground in a string.
Returns
Depth of sensor below ground, e.g. "5cm".
References nidas::core::DSMSensor::_depthString.
bool nidas::dynld::isff::SonicAnemometer::getDespike () const inline
References _despike.
virtual const std::string& nidas::core::DSMSensor::getDeviceName () const inline virtual inherited
Fetch the name of the system device that the sensor is connected to.
References nidas::core::DSMSensor::_devname.
Referenced by nidas::core::SensorHandler::add(), nidas::core::CharacterSensor::buildIODevice(), nidas::core::SerialSensor::buildIODevice(), nidas::core::CharacterSensor::buildSampleScanner(), nidas::core::DSMSensor::close(), CounterClient::CounterClient(), nidas::core::DSMSensor::getName(), parseOther(), nidas::core::DSMSensor::printStatus(), AutoCalClient::readCalFile(), DSMItem::removeChild(), nidas::core::CharacterSensor::sendInitString(), nidas::core::DSMConfig::sensorFromDOMElement(), sensorTitle(), AutoCalClient::Setup(), PConfig::showCalFiles(), Document::updateSensor(), and nidas::core::DSMSensor::validate().
const Dictionary& nidas::core::DSMSensor::getDictionary () const inline inherited
References nidas::core::DSMSensor::_dictionary.
double nidas::dynld::isff::SonicAnemometer::getDiscLevel () const inline
References _despiker, and nidas::core::AdaptiveDespiker::getDiscLevel().
double nidas::dynld::isff::SonicAnemometer::getDiscLevelMultiplier () const inline
References _despiker, and nidas::core::AdaptiveDespiker::getDiscLevelMultiplier().
virtual int nidas::core::DSMSensor::getDriverTimeTagUsecs () const inline virtual inherited
References nidas::core::DSMSensor::_driverTimeTagUsecs.
Referenced by nidas::core::DriverSampleScanner::nextSample().
const DSMConfig* nidas::core::DSMSensor::getDSMConfig () const inline inherited
What DSMConfig am I associated with?
References nidas::core::DSMSensor::_dsm.
Referenced by CounterClient::CounterClient(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::VariableConverter::getDSMConfig(), nidas::core::DSMSensor::MyDictionary::getTokenValue(), nidas::core::DSMSensor::printStatusHeader(), nidas::core::DSMSensor::readSamples(), nidas::core::SampleTag::setDSMSensor(), and nidas::core::DSMSensor::validate().
unsigned int nidas::core::DSMSensor::getDSMId () const inline inherited
References nidas::core::DSMSensor::_id, and GET_DSM_ID.
Referenced by nidas::core::Site::findSensor(), Document::insertA2DVariable(), AutoCalClient::readCalFile(), nidas::core::DSMSensor::readSamples(), sensorTitle(), Calibrator::setup(), AutoCalClient::Setup(), PConfig::showAll(), PConfig::showSensorClasses(), nidas::core::Site::validate(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
const std::string & DSMSensor::getDSMName () const inherited
Fetch the DSM name.
References nidas::core::DSMSensor::_dsm, and nidas::core::DSMConfig::getName().
Referenced by nidas::core::DSMSensor::getName(), AutoCalClient::readCalFile(), and AutoCalClient::Setup().
bool nidas::core::DSMSensor::getDuplicateIdOK () const inline inherited
getDuplicateIdOK will be true if it is OK for samples from this sensor to have identical IDs to samples from another sensor.
That other sensor must also agree that dupicateIdOK are OK. This can be useful if one may not be certain of the device name, e.g. /dev/ttyUSB*, that the system will assign to a sensor may use, but there are identifiers in the data returned that allow one to sort things out. In general, getDuplicateID is false.
References nidas::core::DSMSensor::_duplicateIdOK.
Referenced by nidas::core::Site::validate(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
const std::string& nidas::core::DSMSensor::getFullSuffix () const inline inherited
Full sensor suffix, the concatenation of the sensor suffix, if any, and the height or depth string, if any.
The full sensor suffix are words 2 and 3 in the dot-separated name: variable[.sensor][.height][.site]
References nidas::core::DSMSensor::_fullSuffix.
Referenced by nidas::core::DSMSensor::fromDOMElement().
float nidas::core::DSMSensor::getHeight () const inline inherited
Get sensor height above ground.
Returns
Height of sensor above ground, in meters. Nan if unknown.
References nidas::core::DSMSensor::_height.
const std::string& nidas::core::DSMSensor::getHeightString () const inline inherited
Get sensor height above ground in a string.
Returns
Height of sensor above ground, e.g. "15m".
References nidas::core::DSMSensor::_heightString.
Referenced by nidas::core::DSMSensor::MyDictionary::getTokenValue(), ARLIngest::prepareHeaderIds(), and PConfig::showCalFiles().
dsm_sample_id_t nidas::core::DSMSensor::getId () const inline inherited
Get the various levels of the samples identification.
A sample tag ID is a 32-bit value comprised of four parts: 6-bit sample type id(not used by DSMSensor), a 10-bit DSM id, 16-bit sensor+sample ids.
References nidas::core::DSMSensor::_id, and GET_FULL_ID.
Referenced by CounterClient::CounterClient(), nidas::core::Site::findSensor(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), nidas::core::MessageStreamScanner::nextSampleSepEOM(), nidas::core::SampleTag::SampleTag(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
const std::string& nidas::core::CharacterSensor::getInitString () const inline inherited
References nidas::core::CharacterSensor::_initString.
Referenced by nidas::core::CharacterSensor::sendInitString().
IODevice* nidas::core::DSMSensor::getIODevice () const inline protected inherited
References nidas::core::DSMSensor::_iodev.
virtual double nidas::core::DSMSensor::getLagSecs () const inline protected virtual inherited
Return the sampling lag for this sensor in seconds.
See getLagUsecs().
References nidas::core::DSMSensor::_lag, and USECS_PER_SEC.
virtual int nidas::core::DSMSensor::getLagUsecs () const inline protected virtual inherited
Return the sampling lag for this sensor in microseconds.
A positive lag means one should adjust the sample time tags for this sensor earlier in time to achieve a better estimate of the actual time to be associated for each sample. Derived classes can use this method in their process method to correct for inherent, constant, sampling lags of a sensor. A fixed sample lag, in fractional seconds, can be set for a sensor in the XML:
* <sensor>
*     <parameter name="lag" type = "float" value="0.186"/>
* </sensor>
*
The DSMSensor::fromDOM() method parses this parameter and sets the value of the lag.
References nidas::core::DSMSensor::_lag.
virtual float nidas::core::DSMSensor::getLatency () const inline virtual inherited
References nidas::core::DSMSensor::_latency.
double nidas::dynld::isff::SonicAnemometer::getLeanAzimuthDegrees () const inline
References _tilter, and nidas::dynld::isff::WindTilter::getLeanAzimuthDegrees().
double nidas::dynld::isff::SonicAnemometer::getLeanDegrees () const inline
References _tilter, and nidas::dynld::isff::WindTilter::getLeanDegrees().
const std::string & DSMSensor::getLocation () const inherited
Location string.
A DSMConfig also has a Location. If the location has not been set for this DSMSensor, then the location of the DSMConfig will be returned.
References nidas::core::DSMSensor::_dsm, nidas::core::DSMSensor::_location, and nidas::core::DSMConfig::getLocation().
Referenced by nidas::core::DSMSensor::printStatusHeader().
Looper * DSMSensor::getLooper () static protected inherited
Fetch a pointer to a static instance of a Looper thread.
Use this Looper for periodic callbacks, as for prompting, in support of a DSMSensor.
References nidas::core::DSMSensor::_looper, nidas::core::DSMSensor::_looperMutex, nidas::util::Logger::getInstance(), nidas::util::Thread::getPolicyString(), nidas::util::Logger::log(), LOG_WARNING, nidas::util::Thread::NU_THREAD_RR, nidas::util::Thread::setThreadScheduler(), and nidas::util::Exception::what().
Referenced by nidas::core::SerialSensor::startPrompting(), and nidas::core::SerialSensor::stopPrompting().
unsigned int nidas::core::DSMSensor::getMaxSampleLength () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getMaxSampleLength().
Referenced by nidas::core::DSMSensor::printStatus().
int nidas::core::CharacterSensor::getMaxScanfFields () const inline inherited
The maximum number of fields in any of the AsciiSscanfs for this CharacterSensor.
Prior to scanning a message, a sample of this size must be allocated.
References nidas::core::CharacterSensor::_maxScanfFields.
int nidas::core::CharacterSensor::getMessageLength () const inline inherited
References nidas::core::CharacterSensor::_messageLength.
Referenced by nidas::core::CharacterSensor::buildSampleScanner().
const std::string& nidas::core::CharacterSensor::getMessageSeparator () const inline inherited
Get message separator with backslash sequences replaced by their intended character.
References nidas::core::CharacterSensor::_messageSeparator.
Referenced by nidas::core::CharacterSensor::buildSampleScanner().
bool nidas::core::CharacterSensor::getMessageSeparatorAtEOM () const inline inherited
References nidas::core::CharacterSensor::_separatorAtEOM.
Referenced by nidas::core::CharacterSensor::buildSampleScanner().
unsigned int nidas::core::DSMSensor::getMinSampleLength () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getMinSampleLength().
Referenced by nidas::core::DSMSensor::printStatus().
virtual std::string nidas::core::DSMSensor::getName () const inline virtual inherited
Return a name that should fully identify this sensor.
This name could be used in informative messages. The returned name has this format: dsmName:deviceName.
References nidas::core::DSMSensor::getDeviceName(), and nidas::core::DSMSensor::getDSMName().
Referenced by nidas::core::SensorHandler::add(), nidas::core::SamplePipeline::addSampleClient(), nidas::core::SerialSensor::buildSampleScanner(), nidas::dynld::psql::PSQLProcessor::connect(), nidas::dynld::raf::CVIProcessor::connect(), nidas::core::SamplePipeline::connect(), nidas::dynld::raf::DSMArincSensor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::SensorHandler::PolledDSMSensor::getName(), nidas::core::SensorHandler::incrementFullBufferReads(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::WxtSensor::init(), nidas::core::CharacterSensor::init(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::TwoD64_USB::init_parameters(), nidas::dynld::raf::TwoD_USB::init_parameters(), nidas::core::DSMSensor::printStatusHeader(), nidas::core::DSMSensor::readSamples(), nidas::core::SensorOpener::run(), nidas::dynld::WxtSensor::scanSample(), nidas::dynld::raf::UHSAS_Serial::sendInitString(), nidas::core::DSMConfig::sensorFromDOMElement(), PConfig::showAll(), nidas::core::CharacterSensor::startPrompting(), nidas::core::CharacterSensor::stopPrompting(), nidas::core::CharacterSensor::validate(), nidas::dynld::raf::SppSerial::validate(), nidas::core::Site::validate(), nidas::core::DSMSensor::validate(), nidas::core::DSMConfig::validateSensorAndSampleIds(), nidas::core::CharacterSensor::validateSscanfs(), and nidas::dynld::raf::UHSAS_Serial::~UHSAS_Serial().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
virtual const std::list<SampleTag*>& nidas::core::DSMSensor::getNonConstSampleTags () inline virtual inherited
We'll allow derived classes and calibration applications to change the SampleTags, so this method returns a list of non-constant SampleTags.
References nidas::core::DSMSensor::_sampleTags.
bool nidas::core::CharacterSensor::getNullTerminated () const inline inherited
References nidas::core::SampleScanner::getNullTerminate(), and nidas::core::DSMSensor::getSampleScanner().
int nidas::core::CharacterSensor::getNumScanfFailures () const inline inherited
How many samples have resulted in complete scanf failures - nothing parsed, because the sensor messages do not correspond to the sscanf format.
References nidas::core::CharacterSensor::_scanfFailures.
int nidas::core::CharacterSensor::getNumScanfPartials () const inline inherited
How many samples have been partially scanned, because a character in the middle of a message conflicts with the sscanf format.
References nidas::core::CharacterSensor::_scanfPartials.
float nidas::core::DSMSensor::getObservedDataRate () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getObservedDataRate().
Referenced by nidas::core::DSMSensor::printStatus().
float nidas::core::DSMSensor::getObservedSamplingRate () const inline inherited
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::getObservedSamplingRate().
Referenced by nidas::core::DSMSensor::printStatus().
double nidas::dynld::isff::SonicAnemometer::getOutlierProbability () const inline
References _despiker, and nidas::core::AdaptiveDespiker::getOutlierProbability().
const Parameter * DSMSensor::getParameter (const std::string & name) const inherited
Fetch a parameter by name.
Returns a NULL pointer if no such parameter exists.
References nidas::core::DSMSensor::_parameters.
Referenced by PMSSensorItem::getSerialNumberString(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::WxtSensor::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::TwoD_USB::init_parameters(), Extract2D::run(), sensorTitle(), and nidas::dynld::raf::SppSerial::validate().
const std::list<const Parameter*>& nidas::core::DSMSensor::getParameters () const inline inherited
Get list of parameters.
References nidas::core::DSMSensor::_constParameters.
SampleSource* nidas::core::DSMSensor::getProcessedSampleSource () inline virtual inherited
Implementation of SampleSource::getProcessedSampleSource().
Return the SampleSource for processed samples from this DSMSensor.
Implements nidas::core::SampleSource.
Referenced by nidas::dynld::RawSampleService::schedule().
double nidas::core::CharacterSensor::getPromptOffset () const inline protected inherited
References nidas::core::CharacterSensor::_promptOffset.
Referenced by nidas::core::CharacterSensor::validate().
double nidas::core::CharacterSensor::getPromptRate () const inline protected inherited
References nidas::core::CharacterSensor::_promptRate.
Referenced by nidas::core::CharacterSensor::validate().
const std::list<Prompt>& nidas::core::CharacterSensor::getPrompts () const inline inherited
References nidas::core::CharacterSensor::_prompts.
Referenced by nidas::core::SerialSensor::initPrompting(), and nidas::core::CharacterSensor::validate().
const std::string& nidas::core::CharacterSensor::getPromptString () const inline protected inherited
References nidas::core::CharacterSensor::_promptString.
Referenced by nidas::core::CharacterSensor::validate().
SampleSource* nidas::core::DSMSensor::getRawSampleSource () inline virtual inherited
Implementation of SampleSource::getRawSampleSource().
Return the SampleSource for raw samples from this DSMSensor. A DSMSensor is only a SampleSource of raw samples when running in real-time, not during post-processing.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_rawSource.
Referenced by nidas::core::RemoteSerialConnection::close(), and nidas::dynld::RawSampleService::schedule().
const SampleTag* nidas::core::DSMSensor::getRawSampleTag () const inline inherited
Convenience function to get my one-and-only raw SampleTag().
Equivalent to: getRawSampleSource()->getSampleTags()->front()
References nidas::core::DSMSensor::_rawSampleTag.
Referenced by nidas::core::SamplePipeline::addSampleClient(), nidas::core::SamplePipeline::addSampleClientForTag(), nidas::dynld::RawSampleService::connect(), nidas::dynld::RawSampleService::fromDOMElement(), nidas::dynld::raf::SyncServer::initSensors(), nidas::core::SamplePipeline::removeSampleClient(), nidas::core::SamplePipeline::removeSampleClientForTag(), StatsProcess::run(), DataPrep::run(), DataStats::run(), DataDump::run(), and Calibrator::setup().
virtual int nidas::core::DSMSensor::getReadFd () const inline virtual inherited
References nidas::core::DSMSensor::_iodev, and nidas::core::IODevice::getReadFd().
Referenced by nidas::core::SensorHandler::PolledDSMSensor::getFd().
SampleScanner* nidas::core::DSMSensor::getSampleScanner () const inline protected inherited
References nidas::core::DSMSensor::_scanner.
Referenced by nidas::core::CharacterSensor::getNullTerminated().
const SampleStats& nidas::core::DSMSensor::getSampleStats () const inline virtual inherited
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::getSampleStats().
SampleTagIterator nidas::core::DSMSensor::getSampleTagIterator () const inline virtual inherited
Implements nidas::core::SampleSource.
Referenced by A2DSensorItem::child(), nidas::core::SamplePipeline::connect(), CounterClient::CounterClient(), nidas::core::SamplePipeline::disconnect(), nidas::core::CharacterSensor::doesAsciiSscanfs(), nidas::core::Site::findSensor(), A2DSensorItem::getA2DTempSuffix(), Document::getAvailableA2DChannels(), nidas::dynld::WxtSensor::init(), parseAnalog(), parseOther(), A2DSensorItem::refreshChildItems(), StatsProcess::run(), DataPrep::run(), A2DSensorItem::setNidasA2DTempSuffix(), PConfig::showAll(), nidas::core::DSMSensor::toDOMParent(), and Document::validateSampleInfo().
std::list<const SampleTag*> nidas::core::DSMSensor::getSampleTags () const inline virtual inherited
Implementation of SampleSource::getSampleTags().
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::getSampleTags().
Referenced by nidas::dynld::psql::PSQLProcessor::connect(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::SampleTagIterator::hasNext(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::core::CharacterSensor::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::TwoD64_USB::init_parameters(), SensorItem::removeChild(), A2DSensorItem::removeChild(), nidas::dynld::raf::SyncRecordSource::selectVariablesFromSensor(), AutoCalClient::Setup(), PConfig::showCalFiles(), nidas::core::CharacterSensor::validate(), nidas::dynld::raf::SppSerial::validate(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
std::list<SampleTag*>& nidas::core::DSMSensor::getSampleTags () inline inherited
Non-const method to get a list of non-const pointers to SampleTags.
References nidas::core::DSMSensor::_sampleTags.
const std::list<AsciiSscanf*>& nidas::core::CharacterSensor::getScanfers () const inline inherited
Return the list of AsciiSscanfs requested for this CharacterSensor.
This list is only valid after the init() method has been called.
References nidas::core::CharacterSensor::_sscanfers.
Referenced by nidas::dynld::WxtSensor::init().
unsigned int nidas::core::DSMSensor::getSensorId () const inline inherited
References nidas::core::DSMSensor::_id, and GET_SPS_ID.
Referenced by nidas::core::Site::findSensor(), nidas::core::DSMSensor::fromDOMElement(), Document::insertA2DVariable(), ARLIngest::prepareHeaderIds(), AutoCalClient::readCalFile(), nidas::core::DSMSensor::readSamples(), sensorTitle(), Calibrator::setup(), AutoCalClient::Setup(), PConfig::showAll(), PConfig::showSensorClasses(), Document::updateSensor(), nidas::core::Site::validate(), nidas::core::DSMSensor::validate(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
const Site * DSMSensor::getSite () const inherited
What Site am I associated with?
References nidas::core::DSMSensor::_dsm, and nidas::core::DSMConfig::getSite().
Referenced by nidas::core::DSMSensor::fromDOMElement(), Document::insertA2DVariable(), and Document::updateVariable().
int nidas::core::DSMSensor::getStation () const inline inherited
References nidas::core::DSMSensor::_station.
Referenced by nidas::core::DSMSensor::fromDOMElement().
const std::string& nidas::core::DSMSensor::getSuffix () const inline inherited
Sensor suffix, which is added to variable names.
It is only necessary to have a sensor suffix to make variable names unique. For example, if there are multiple sensors at the same height, with common variable names, then one can use a sensor suffix to make unique names. The sensor suffix is the second dot-separated word in a variable name, where only the first word is required: variable[.sensor][.height][.site]
References nidas::core::DSMSensor::_suffix.
Referenced by Extract2D::countParticles(), nidas::core::DSMSensor::fromDOMElement(), VariableItem::getBaseName(), nidas::core::DSMSensor::MyDictionary::getTokenValue(), Extract2D::run(), sensorTitle(), nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setHeight(), and Document::updateSensor().
double nidas::dynld::isff::SonicAnemometer::getTcOffset () const inline
References _tcOffset.
double nidas::dynld::isff::SonicAnemometer::getTcSlope () const inline
References _tcSlope.
const nidas::util::Termios& nidas::core::SerialSensor::getTermios () const inline inherited
Get a read-only copy of the Termios.
int nidas::core::DSMSensor::getTimeoutCount () const inline inherited
References nidas::core::DSMSensor::_nTimeouts.
Referenced by nidas::core::DSMSensor::close().
virtual int nidas::core::DSMSensor::getTimeoutMsecs () const inline virtual inherited
References nidas::core::DSMSensor::_timeoutMsecs.
Referenced by nidas::core::RemoteSerialConnection::close(), nidas::core::SensorHandler::PolledDSMSensor::getTimeoutMsecs(), and nidas::core::RemoteSerialConnection::setSensor().
bool nidas::core::DSMSensor::getTokenValue (const std::string & token, std::string & value) const inline inherited
Implement a lookup for tokens that I know about, like $HEIGHT.
For other tokens, call getDSMConfig()->getTokenValue(token,value);
References nidas::core::DSMSensor::_dictionary, and nidas::core::DSMSensor::MyDictionary::getTokenValue().
virtual const std::string& nidas::core::DSMSensor::getTypeName (void) const inline virtual inherited
Get the type name of this sensor.
References nidas::core::DSMSensor::_typeName.
int SerialSensor::getUsecsPerByte () const inherited
If the underlying IODevice is a SerialPortIODevice, return the value of SerialPortIODevice::getUsecsPerByte(), otherwise return 0, which means no timetag correction for transmission delay will be applied.
References nidas::core::SerialSensor::_serialDevice, and nidas::core::SerialPortIODevice::getUsecsPerByte().
Referenced by nidas::core::SerialSensor::buildSampleScanner().
VariableIterator DSMSensor::getVariableIterator () const inherited
Referenced by nidas::core::DSMSensor::fromDOMElement(), DataPrep::matchVariables(), and nidas::core::Site::validate().
double nidas::dynld::isff::SonicAnemometer::getVazimuth () const inline
References _rotator, and nidas::dynld::isff::WindRotator::getAngleDegrees().
virtual int nidas::core::DSMSensor::getWriteFd () const inline virtual inherited
References nidas::core::DSMSensor::_iodev, and nidas::core::IODevice::getWriteFd().
Referenced by main().
void nidas::core::DSMSensor::incrementTimeoutCount () inline inherited
References nidas::core::DSMSensor::_nTimeouts.
Referenced by nidas::core::SensorOpener::run().
void CharacterSensor::init () throw (nidas::util::InvalidParameterException) virtual inherited
Initialize the CharacterSensor instance for post-processing.
This should only be done after the CharacterSensor has been initialized with fromDOMElement. Calls validateSscanfs.
Reimplemented from nidas::core::DSMSensor.
Reimplemented in nidas::dynld::raf::SidsNetSensor, nidas::dynld::WxtSensor, nidas::dynld::raf::UHSAS_Serial, and nidas::dynld::IEEE_Float.
References nidas::core::CharacterSensor::_maxScanfFields, nidas::core::CharacterSensor::_nextSscanfer, nidas::core::CharacterSensor::_sscanfers, nidas::core::Variable::getLength(), nidas::core::DSMSensor::getName(), nidas::core::AsciiSscanf::getNumberOfFields(), nidas::core::DSMSensor::getSampleTags(), nidas::core::SampleTag::getScanfFormat(), nidas::core::SampleTag::getVariables(), nidas::core::DSMSensor::init(), nidas::util::replaceBackslashSequences(), nidas::core::AsciiSscanf::setFormat(), nidas::core::AsciiSscanf::setSampleTag(), nidas::core::CharacterSensor::validateSscanfs(), and nidas::util::Exception::what().
Referenced by nidas::dynld::raf::UHSAS_Serial::init(), and nidas::dynld::WxtSensor::init().
void SerialSensor::initPrompting () throw (nidas::util::IOException) protected inherited
Perform whatever is necessary to initialize prompting right after the device is opened.
References nidas::core::SerialSensor::_prompters, nidas::core::Prompt::getOffset(), nidas::core::CharacterSensor::getPrompts(), nidas::core::Prompt::getRate(), nidas::core::Prompt::getString(), nidas::core::CharacterSensor::isPrompted(), MSECS_PER_SEC, nidas::util::replaceBackslashSequences(), nidas::core::SerialSensor::Prompter::setPrompt(), nidas::core::SerialSensor::Prompter::setPromptOffsetMsec(), nidas::core::SerialSensor::Prompter::setPromptPeriodMsec(), and nidas::core::SerialSensor::startPrompting().
virtual void nidas::core::DSMSensor::ioctl (int request, void * buf, size_t len) throw (nidas::util::IOException) inline virtual inherited
Perform an ioctl on the device.
request is an integer value which must be supported by the device. Normally this is a value from a header file for the device.
References nidas::core::DSMSensor::_iodev, nidas::core::IODevice::ioctl(), and len.
virtual bool nidas::core::CharacterSensor::isPrompted () const inline virtual inherited
Is this a prompted sensor.
Will be true if setPromptString() has been called with a non-empty string, and setPromptRate() has been called with a rate other than IRIG_ZERO_HZ.
References nidas::core::CharacterSensor::_prompted.
Referenced by nidas::core::SerialSensor::initPrompting(), nidas::core::SerialSensor::startPrompting(), and nidas::core::SerialSensor::stopPrompting().
bool nidas::core::SerialSensor::isPrompting () const inline virtual inherited
Is prompting active, i.e.
isPrompted() is true, and startPrompting has been called?
Reimplemented from nidas::core::CharacterSensor.
virtual Sample* nidas::core::DSMSensor::nextSample () inline virtual inherited
Extract the next sample from the buffer.
Returns a null pointer if there are no samples left in the buffer.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::nextSample().
Referenced by nidas::core::DSMSensor::readSamples(), and nidas::dynld::raf::UHSAS_Serial::sendInitString().
void SonicAnemometer::offsetsTiltAndRotate (nidas::core::dsm_time_t tt, float * uvwt) throw ()
Do standard bias removal, tilt correction and horizontal rotation of 3d sonic anemometer data.
time tag of the data, used to search for a parameter a file containing a calibration time series.
Parameters
uvwt Pointer to an array of 4 floats, containing u,v,w and tc(virtual temperature). New values are written back via the pointers.
References nidas::core::floatNAN, nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_WARNING, and nidas::util::Exception::what().
void SerialSensor::open (int flags) throw (nidas::util::IOException, nidas::util::InvalidParameterException) virtual inherited
Open the device connected to the sensor.
This calls CharacterSensor::open(), and then sets up the port prompting if it is required.
Reimplemented from nidas::core::CharacterSensor.
Reimplemented in nidas::dynld::isff::CSAT3_Sonic, nidas::dynld::raf::PPT_Serial, nidas::dynld::raf::UHSAS_Serial, nidas::dynld::raf::VCSEL_Serial, nidas::dynld::raf::VCSEL2_Serial, nidas::dynld::isff::CSI_IRGA_Sonic, and nidas::dynld::isff::MOSMote.
References nidas::core::CharacterSensor::open().
Referenced by nidas::dynld::isff::MOSMote::open(), nidas::dynld::isff::CSI_IRGA_Sonic::open(), nidas::dynld::raf::UHSAS_Serial::open(), and nidas::dynld::isff::CSAT3_Sonic::open().
SonicAnemometer& nidas::dynld::isff::SonicAnemometer::operator= (const SonicAnemometer & x) private
void SonicAnemometer::parseParameters () throw (nidas::util::InvalidParameterException) virtual
Parse the list of nidas::core::Parameter that are associated with this sensor.
This also checks the parameters "wind3d_tilt_correction", and "wind3d_horiz_rotation" that may have been set on the Project singleton, calls setDoTiltCorrection() and setDoHorizontalRotation() accordingly.
Reimplemented in nidas::dynld::isff::CSAT3_Sonic, nidas::dynld::isff::CSI_IRGA_Sonic, and nidas::dynld::isff::ATIK_Sonic.
References nidas::core::Parameter::BOOL_PARAM, nidas::core::Project::expandString(), nidas::core::Parameter::FLOAT_PARAM, nidas::core::Project::getInstance(), nidas::core::Parameter::getLength(), nidas::core::Parameter::getName(), nidas::core::Parameter::getNumericValue(), nidas::core::Project::getParameter(), nidas::core::Parameter::getStringValue(), nidas::core::Parameter::getType(), nidas::core::Parameter::INT_PARAM, and nidas::core::Parameter::STRING_PARAM.
Referenced by nidas::dynld::isff::ATIK_Sonic::parseParameters(), and nidas::dynld::isff::CSAT3_Sonic::parseParameters().
void SerialSensor::printStatus (std::ostream & ostr) throw () virtual inherited
Reimplemented from nidas::core::DSMSensor.
References nidas::util::Logger::getInstance(), nidas::util::Logger::log(), LOG_ERR, nidas::core::DSMSensor::printStatus(), and nidas::util::Exception::what().
void DSMSensor::printStatusHeader (std::ostream & ostr) throw () inherited
References nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getLocation(), nidas::core::DSMSensor::getName(), and nidas::core::DSMSensor::zebra.
Referenced by nidas::core::DSMEngineStat::run().
void DSMSensor::printStatusTrailer (std::ostream & ostr) throw () inherited
Referenced by nidas::core::DSMEngineStat::run().
bool SonicAnemometer::process (const nidas::core::Sample * samp, std::list< const nidas::core::Sample * > & results) throw ()
Basic process method for sonic anemometer wind plus temperature: u,v,w,tc parsed from an ASCII sample.
Applies despiking, orientation corrections, bias, tilts and horizontal rotations, as configured.
References nidas::core::floatNAN, nidas::core::Sample::freeReference(), nidas::core::Sample::getConstVoidDataPtr(), nidas::core::Sample::getDataByteLength(), nidas::core::Sample::getDataLength(), nidas::core::Sample::getTimeTag(), and nidas::core::CharacterSensor::process().
bool CharacterSensor::process (const Sample * , std::list< const Sample * > & result) throw () virtual inherited
Process a raw sample, which in this case means do a sscanf on the character string contents, creating a processed sample of binary floating point data.
Implements nidas::core::DSMSensor.
Reimplemented in nidas::dynld::WxtSensor, nidas::dynld::isff::CSAT3_Sonic, nidas::dynld::isff::PropVane, nidas::dynld::raf::SidsNetSensor, nidas::dynld::raf::VCSEL_Serial, nidas::dynld::raf::PPT_Serial, nidas::dynld::raf::UHSAS_Serial, nidas::dynld::raf::PSI9116_Sensor, nidas::dynld::IEEE_Float, nidas::dynld::isff::CSI_IRGA_Sonic, nidas::dynld::raf::LamsNetSensor, nidas::dynld::GPS_NMEA_Serial, nidas::dynld::GPS_Novatel_Serial, nidas::dynld::raf::TwoD_House, nidas::dynld::TSI_CPC3772, nidas::dynld::isff::MOSMote, nidas::dynld::raf::BCPD_Serial, nidas::dynld::raf::CDP_Serial, nidas::dynld::raf::SPP100_Serial, nidas::dynld::raf::SPP200_Serial, and nidas::dynld::raf::SPP300_Serial.
References nidas::util::LogContext::active(), nidas::core::CHAR_ST, nidas::core::VariableConverter::convert(), nidas::core::floatNAN, fp, nidas::core::SampleT< DataT >::freeReference(), nidas::core::SampleT< DataT >::getConstVoidDataPtr(), nidas::core::Variable::getConverter(), nidas::core::SampleT< DataT >::getDataPtr(), nidas::core::AsciiSscanf::getFormat(), nidas::core::Variable::getLength(), nidas::core::Variable::getMaxValue(), nidas::core::Variable::getMissingValue(), nidas::core::AsciiSscanf::getNumberOfFields(), nidas::core::AsciiSscanf::getSampleTag(), nidas::util::LogContext::log(), LOG_DEBUG, nidas::core::SampleT< DataT >::setDataLength(), nidas::core::Sample::setId(), and nidas::core::Sample::setTimeTag().
Referenced by nidas::dynld::isff::Licor7500::process(), nidas::dynld::isff::ATIK_Sonic::process(), nidas::dynld::isff::MOSMote::process(), nidas::dynld::isff::NCAR_TRH::process(), nidas::dynld::isff::CSI_IRGA_Sonic::process(), nidas::dynld::raf::CVI_LV_Input::process(), nidas::dynld::isff::PropVane::process(), nidas::dynld::WxtSensor::process(), and process().
virtual size_t nidas::core::DSMSensor::read (void * buf, size_t len) throw (nidas::util::IOException) inline virtual inherited
Read from the device (duh).
Behaves like the read(2) system call, without a file descriptor argument, and with an IOException.
References nidas::core::DSMSensor::_iodev, len, and nidas::core::IODevice::read().
Referenced by main().
virtual size_t nidas::core::DSMSensor::read (void * buf, size_t len, int msecTimeout) throw (nidas::util::IOException) inline virtual inherited
Read from the device with a timeout.
References nidas::core::DSMSensor::_iodev, len, and nidas::core::IODevice::read().
bool nidas::core::DSMSensor::readBuffer () throw (nidas::util::IOException) inline protected inherited
Read into my SampleScanner's buffer.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::readBuffer().
Referenced by nidas::core::DSMSensor::readSamples(), and nidas::dynld::raf::UHSAS_Serial::sendInitString().
bool nidas::core::DSMSensor::readBuffer (int msecTimeout) throw (nidas::util::IOException) inline protected inherited
Read into my SampleScanner's buffer.
References nidas::core::DSMSensor::_scanner, and nidas::core::SampleScanner::readBuffer().
bool DSMSensor::readSamples () throw (nidas::util::IOException) virtual inherited
Read samples from my associated file descriptor, and distribute() them to my RawSampleClient's.
This method is called by SensorHander, when select/poll indicates that data is available on the file descriptor returned by getReadFd(). This is a convienence method which does a readBuffer() to read available data from the DSMSensor into a buffer, and then repeatedly calls nextSample() to extract all samples out of that buffer.
References nidas::core::DSMSensor::_rawSource, nidas::core::SampleSourceSupport::distribute(), DLOG, nidas::core::DSMSensor::getDSMConfig(), nidas::core::DSMSensor::getDSMId(), nidas::core::Project::getName(), nidas::core::DSMSensor::getName(), nidas::core::DSMConfig::getProject(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMSensor::nextSample(), and nidas::core::DSMSensor::readBuffer().
bool DSMSensor::receive (const Sample * s) throw () virtual inherited
A DSMSensor can be used as a SampleClient, meaning it receives its own raw samples.
In real-time operations, a DSMSensor can be added as a raw SampleClient of itself, using addRawSampleClient(). In post-processing, a DSMSensor typically receives samples with its own sample id from a SampleSorter. receive() then applies further processing via the process() method.
Implements nidas::core::SampleClient.
void DSMSensor::removeCalFiles () inherited
Remove all CalFiles.
References nidas::core::DSMSensor::_calFiles.
Referenced by Calibrator::setup(), and nidas::core::DSMSensor::~DSMSensor().
void nidas::core::DSMSensor::removeSampleClient (SampleClient * c) throw () inline virtual inherited
Remove a SampleClient from this SampleSource This will also remove a SampleClient if it has been added with addSampleClientForTag().
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::removeSampleClient().
Referenced by nidas::core::SamplePipeline::removeSampleClient(), and nidas::core::SamplePipeline::removeSampleClientForTag().
void nidas::core::DSMSensor::removeSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::DSMSensor::_source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
Referenced by nidas::core::SamplePipeline::removeSampleClientForTag().
void DSMSensor::removeSampleTag (SampleTag * val) throw () virtual inherited
Remove val from the list of SampleTags, and delete it.
Referenced by Document::insertA2DVariable(), SensorItem::removeChild(), and A2DSensorItem::removeChild().
virtual bool nidas::core::DSMSensor::reopenOnIOException () const inline virtual inherited
Whether to reopen this sensor on an IOException.
The base method returns true. Over-ride if a reopen should not be attempted.
int CharacterSensor::scanSample (AsciiSscanf * sscanf, const char * inputstr, float * data_ptr) protected virtual inherited
Reimplemented in nidas::dynld::WxtSensor.
References nidas::core::AsciiSscanf::getNumberOfFields(), and nidas::core::AsciiSscanf::sscanf().
void CharacterSensor::sendInitString () throw (nidas::util::IOException) virtual inherited
Reimplemented in nidas::dynld::raf::UHSAS_Serial, nidas::dynld::raf::BCPD_Serial, nidas::dynld::raf::CDP_Serial, nidas::dynld::raf::SPP100_Serial, nidas::dynld::raf::SPP200_Serial, and nidas::dynld::raf::SPP300_Serial.
References DLOG, nidas::core::DSMSensor::getDeviceName(), nidas::core::CharacterSensor::getInitString(), nidas::util::replaceBackslashSequences(), and nidas::core::DSMSensor::write().
virtual void nidas::core::DSMSensor::setApplyVariableConversions (bool val) inline virtual inherited
References nidas::core::DSMSensor::_applyVariableConversions.
Referenced by nidas::core::DSMSensor::fromDOMElement().
void nidas::dynld::isff::SonicAnemometer::setBias (int i, double val) inline
References _bias.
virtual void nidas::core::DSMSensor::setCatalogName (const std::string & val) inline virtual inherited
Set the name of the catalog entry for this sensor.
References nidas::core::DSMSensor::_catalogName.
Referenced by nidas::core::DSMSensor::fromDOMElement().
virtual void nidas::core::DSMSensor::setClassName (const std::string & val) inline virtual inherited
Set the class name.
In the usual usage this method is not used, and getClassName() is over-ridden in a derived class to return a constant string.
References nidas::core::DSMSensor::_className.
Referenced by nidas::core::DSMSensor::fromDOMElement().
virtual void nidas::core::DSMSensor::setDefaultMode (int val) inline virtual inherited
References nidas::core::DSMSensor::_defaultMode.
Referenced by nidas::core::DSMSensor::fromDOMElement(), nidas::core::SerialSensor::SerialSensor(), and nidas::dynld::raf::TwoD_USB::TwoD_USB().
void DSMSensor::setDepth (const std::string & val) inherited
Set sensor depth below ground via a string which is added to variable names.
Parameters
val String containing sensor below and units in meters (m) or centimeters(cm), e.g. "5cm". This depth string is added to all the variable names, with a "." separator, so that a variable "Tsoil" for this sensor becomes "Tsoil.5cm".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::floatNAN, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
void DSMSensor::setDepth (float val) inherited
Set sensor depth below ground.
Parameters
val depth below ground, in meters. The depth is converted to centimeters and is added to all the variable names, with a "." separator, so that a variable "Tsoil" for this sensor becomes "Tsoil.5cm".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
void nidas::dynld::isff::SonicAnemometer::setDespike (bool val) inline
References _despike.
virtual void nidas::core::DSMSensor::setDeviceName (const std::string & val) inline virtual inherited
Set the name of the system device that the sensor is connected to.
Parameters
val Name of device, e.g. "/dev/xxx0".
References nidas::core::DSMSensor::_devname.
Referenced by nidas::core::DSMSensor::fromDOMElement(), and main().
void nidas::dynld::isff::SonicAnemometer::setDiscLevelMultiplier (double val) inline
References _despiker.
void nidas::dynld::isff::SonicAnemometer::setDoHorizontalRotation (bool val) inline
Should 2D horizontal rotations of U,V be applied?
References _horizontalRotation.
void nidas::dynld::isff::SonicAnemometer::setDoTiltCorrection (bool val) inline
Should 3D tilt corrections be applied?
References _tiltCorrection.
virtual void nidas::core::DSMSensor::setDriverTimeTagUsecs (int val) inline virtual inherited
References nidas::core::DSMSensor::_driverTimeTagUsecs.
Referenced by nidas::dynld::raf::DSMArincSensor::buildIODevice().
void DSMSensor::setDSMConfig (const DSMConfig * val) inherited
Set the DSMConfig for this sensor.
References nidas::core::DSMSensor::_dsm, nidas::core::DSMConfig::getId(), and nidas::core::DSMSensor::setDSMId().
Referenced by nidas::core::DSMConfig::sensorFromDOMElement(), and nidas::core::SensorHandler::~SensorHandler().
void nidas::core::DSMSensor::setDSMId (unsigned int val) inline inherited
References nidas::core::DSMSensor::_id, and SET_DSM_ID.
Referenced by nidas::core::DSMSensor::setDSMConfig().
void nidas::core::DSMSensor::setDuplicateIdOK (bool val) inline inherited
Set the duplicate ID attribute of this DSMSensor.
References nidas::core::DSMSensor::_duplicateIdOK.
Referenced by nidas::core::DSMSensor::fromDOMElement().
void nidas::core::DSMSensor::setFullSuffix (const std::string & val) inline protected inherited
References nidas::core::DSMSensor::_fullSuffix.
Referenced by nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setHeight(), and nidas::core::DSMSensor::setSuffix().
void DSMSensor::setHeight (const std::string & val) inherited
Set sensor height above ground via a string which is added to variable names.
Parameters
val String containing sensor height and units in meters (m) or centimeters(cm), e.g. "15m". This height string is added to all the variable names, with a "." separator, so that a variable "u" for this sensor becomes "u.15m".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::floatNAN, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
void DSMSensor::setHeight (float val) inherited
Set sensor height above ground.
Parameters
val height above ground, in meters. The height is added to all the variable names, with a "." separator, so that a variable "u" for this sensor becomes "u.15m".
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_height, nidas::core::DSMSensor::_heightString, nidas::core::DSMSensor::getSuffix(), and nidas::core::DSMSensor::setFullSuffix().
void nidas::core::DSMSensor::setId (dsm_sample_id_t val) inline inherited
Set the various levels of the sensor identification.
A sensor ID is a 32-bit value comprised of four parts: 6-bit sample type id (not used by DSMSensor), 10-bit DSM id, and 16-bit sensor+sample ids.
References nidas::core::DSMSensor::_id, and SET_FULL_ID.
void nidas::core::CharacterSensor::setInitString (const std::string & val) inline inherited
Set the initialization string(s) for this sensor.
The init string may contain backslash escape sequences like the prompt string.
References nidas::core::CharacterSensor::_initString.
void nidas::core::DSMSensor::setIODevice (IODevice * val) inline inherited
Set the IODevice for this sensor.
DSMSensor then owns the pointer and will delete it in its destructor.
References nidas::core::DSMSensor::_iodev.
virtual void nidas::core::DSMSensor::setLagSecs (double val) inline protected virtual inherited
Set the sampling lag for this sensor in seconds.
This lag should then used to correct the timetags of the processed samples in the process() method of derived classes. Note that this lag is not used to alter the timetags of the raw samples. Raw samples are saved with the un-altered timetag that was determined at the moment they were sampled.
The lag is stored as a signed integer of microseconds, so lags should be between += 2147 seconds. No warning or exception is given if the value exceeds that limit. If your lag is greater than that I suggest you junk your sensor! A positive lag means one should adjust the sample time tags for this sensor earlier in time to achieve a better estimate of the actual time to be associated for each sample. A fixed sample lag, in fractional seconds, can be set for a sensor in the XML:
* <parameter name="lag" type = "float" value="0.186"/>
*
The DSMSensor::fromDOM() method parses this parameter and calls this method to set the lag. process() methods in derived classes must apply this lag value. The DSMSensor base class does not adjust time tags of processed samples.
References nidas::core::DSMSensor::_lag, and USECS_PER_SEC.
Referenced by nidas::core::DSMSensor::fromDOMElement().
virtual void nidas::core::DSMSensor::setLatency (float val) throw (nidas::util::InvalidParameterException) inline virtual inherited
Set desired latency, providing some control over the response time vs buffer efficiency tradeoff.
Setting a latency of 1/10 sec means buffer data in the driver for a 1/10 sec, then send the data to user space. Generally it should be set before doing a sensor open().
Parameters
val Latency, in seconds.
References nidas::core::DSMSensor::_latency.
Referenced by nidas::dynld::A2DSensor::A2DSensor(), and nidas::core::DSMSensor::fromDOMElement().
void nidas::dynld::isff::SonicAnemometer::setLeanAzimuthDegrees (double val) inline
References _tilter, and nidas::dynld::isff::WindTilter::setLeanAzimuthDegrees().
void nidas::dynld::isff::SonicAnemometer::setLeanDegrees (double val) inline
References _tilter, and nidas::dynld::isff::WindTilter::setLeanDegrees().
void nidas::core::DSMSensor::setLocation (const std::string & val) inline inherited
References nidas::core::DSMSensor::_location.
Referenced by nidas::core::DSMSensor::fromDOMElement().
void SerialSensor::setMessageParameters (unsigned int len, const std::string & sep, bool eom) throw (nidas::util::InvalidParameterException, nidas::util::IOException) virtual inherited
Set message separator and message length parameters, which are used to parse and time-tag samples from the IODevice.
Reimplemented from nidas::core::CharacterSensor.
References len, and nidas::core::CharacterSensor::setMessageParameters().
void nidas::dynld::isff::SonicAnemometer::setOutlierProbability (double val) inline
References _despiker.
void nidas::core::CharacterSensor::setPromptOffset (const double val) inline protected inherited
References nidas::core::CharacterSensor::_promptOffset.
void nidas::core::CharacterSensor::setPromptRate (const double val) inline protected inherited
Set the rate at which <sensor> prompts are sent to this sensor.
This will be set on a CharacterSensor if a <prompt> element is found for <sensor>, not as a sub-element of <sample>.
References nidas::core::CharacterSensor::_promptRate.
void nidas::core::CharacterSensor::setPromptString (const std::string & val) inline protected inherited
Set the <sensor> prompt string for this sensor.
The prompt string may contain backslash escape sequences.
References nidas::core::CharacterSensor::_promptString.
void nidas::core::DSMSensor::setSampleScanner (SampleScanner * val) inline inherited
Set the SampleScanner for this sensor.
DSMSensor then owns the pointer and will delete it in its destructor.
References nidas::core::DSMSensor::_scanner.
void nidas::core::DSMSensor::setSensorId (unsigned int val) inline inherited
References nidas::core::DSMSensor::_id, and SET_SPS_ID.
Referenced by nidas::core::DSMSensor::fromDOMElement().
void DSMSensor::setStation (int val) inherited
References nidas::core::DSMSensor::_sampleTags, nidas::core::DSMSensor::_station, and nidas::core::SampleTag::setStation().
Referenced by nidas::core::DSMSensor::fromDOMElement().
void DSMSensor::setSuffix (const std::string & val) inherited
References nidas::core::DSMSensor::_depthString, nidas::core::DSMSensor::_heightString, nidas::core::DSMSensor::_suffix, and nidas::core::DSMSensor::setFullSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
void nidas::dynld::isff::SonicAnemometer::setTcOffset (double val) inline
References _tcOffset.
void nidas::dynld::isff::SonicAnemometer::setTcSlope (double val) inline
References _tcSlope.
virtual void nidas::core::DSMSensor::setTimeoutMsecs (int val) inline virtual inherited
Set the sensor timeout value in milliseconds.
A value of 0 means no timeout (e.g. infinite). If no data is received for this period, then the sensor is closed, and re-opened. For efficiency reasons, the system may not actually detect a sensor timeout of less than 1 second, so setting it to less than 1000 milliseconds will likely not reduce the time before a sensor timeout is detected.
References nidas::core::DSMSensor::_timeoutMsecs.
Referenced by nidas::core::RemoteSerialConnection::close(), and nidas::core::DSMSensor::fromDOMElement().
virtual void nidas::core::DSMSensor::setTypeName (const std::string & val) inline virtual inherited
Set the type name of this sensor, e.g.
: "ACME Model 99 Mach7 Particle Disambiguator". This is meant for descriptive purposes only, and is not meant to change the behavior of a sensor object.
References nidas::core::DSMSensor::_typeName.
Referenced by nidas::core::DSMSensor::fromDOMElement().
void nidas::dynld::isff::SonicAnemometer::setVazimuth (double val) inline
Wind vectors in geographic coordinates are expressed by U, the component of the wind blowing toward the east, and V, the component of the wind blowing toward the north.
If the V axis of a sonic anemometer is pointing north then no rotation is necessary to convert from sonic coordinates to geographic. So the compass azimuth (0=north,90=east, etc) of the sonic +V axis is the angle between geographic and sonic coordinates.
References _rotator, and nidas::dynld::isff::WindRotator::setAngleDegrees().
void SerialSensor::shutdownPrompting () throw (nidas::util::IOException) protected inherited
Shutdown prompting, typically done when a device is closed.
References nidas::core::SerialSensor::_prompters, and nidas::core::SerialSensor::stopPrompting().
Referenced by nidas::core::SerialSensor::close().
void SerialSensor::startPrompting () throw (nidas::util::IOException) virtual inherited
Start the prompters.
They can be started and stopped multiple times once a SerialSensor is opened.
Reimplemented from nidas::core::CharacterSensor.
References nidas::core::SerialSensor::_prompters, nidas::core::SerialSensor::_prompting, nidas::core::Looper::addClient(), nidas::core::DSMSensor::getLooper(), nidas::core::SerialSensor::Prompter::getPromptOffsetMsec(), nidas::core::SerialSensor::Prompter::getPromptPeriodMsec(), and nidas::core::CharacterSensor::isPrompted().
Referenced by nidas::core::SerialSensor::initPrompting().
void SerialSensor::stopPrompting () throw (nidas::util::IOException) virtual inherited
Reimplemented from nidas::core::CharacterSensor.
References nidas::core::SerialSensor::_prompters, nidas::core::SerialSensor::_prompting, nidas::core::DSMSensor::getLooper(), nidas::core::CharacterSensor::isPrompted(), and nidas::core::Looper::removeClient().
Referenced by nidas::core::SerialSensor::shutdownPrompting().
nidas::util::Termios& nidas::core::SerialSensor::termios () inline inherited
Expose the Termios.
One must call applyTermios() to apply any changes to the serial port.
xercesc::DOMElement * DSMSensor::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented from nidas::core::DOMable.
Referenced by nidas::core::DSMSensor::toDOMParent().
xercesc::DOMElement * DSMSensor::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented from nidas::core::DOMable.
References nidas::core::DOMable::getNamespaceURI(), nidas::core::DSMSensor::getSampleTagIterator(), nidas::core::SampleTagIterator::hasNext(), nidas::core::DSMSensor::toDOMElement(), and nidas::core::SampleTag::toDOMParent().
Referenced by nidas::core::DSMConfig::toDOMElement().
virtual void nidas::core::CharacterSensor::togglePrompting () throw (nidas::util::IOException) inline virtual inherited
References nidas::core::CharacterSensor::isPrompting(), nidas::core::CharacterSensor::startPrompting(), and nidas::core::CharacterSensor::stopPrompting().
void nidas::core::SerialSensor::unixDevInit (int flags) throw (nidas::util::IOException) protected inherited
void SonicAnemometer::validate () throw (nidas::util::InvalidParameterException) virtual
Validate the configuration of this sensor.
Calls the base class validate(), parseParameters(), and checkSampleTags().
Reimplemented from nidas::core::CharacterSensor.
References nidas::core::CharacterSensor::validate().
void SonicAnemometer::validateSscanfs () throw (nidas::util::InvalidParameterException) virtual
Warn user if number of scanf fields does not match number expected from variables in sample.
Reimplemented from nidas::core::CharacterSensor.
References nidas::core::AsciiSscanf::getNumberOfFields().
virtual size_t nidas::core::DSMSensor::write (const void * buf, size_t len) throw (nidas::util::IOException) inline virtual inherited
Write to the device (duh).
Behaves like write(2) system call, without a file descriptor argument, and with an IOException.
References nidas::core::DSMSensor::_iodev, len, and nidas::core::IODevice::write().
Referenced by nidas::dynld::raf::UHSAS_Serial::sendInitString(), and nidas::core::CharacterSensor::sendInitString().
Member Data Documentation
bool nidas::dynld::isff::SonicAnemometer::_allBiasesNaN protected
double nidas::dynld::isff::SonicAnemometer::_bias[3] protected
Referenced by getBias(), and setBias().
bool nidas::dynld::isff::SonicAnemometer::_despike protected
Referenced by getDespike(), and setDespike().
nidas::core::AdaptiveDespiker nidas::dynld::isff::SonicAnemometer::_despiker[4] protected
Referenced by getDiscLevel(), getDiscLevelMultiplier(), getOutlierProbability(), setDiscLevelMultiplier(), and setOutlierProbability().
int nidas::dynld::isff::SonicAnemometer::_diagIndex protected
If user requests "diag" or "status", its index in the output sample.
int nidas::dynld::isff::SonicAnemometer::_dirIndex protected
If user requests wind direction, variable name "dir", its index in the output sample.
bool nidas::dynld::isff::SonicAnemometer::_horizontalRotation protected
Should horizontal rotation of U,V be performed?
Referenced by setDoHorizontalRotation().
int nidas::dynld::isff::SonicAnemometer::_ldiagIndex protected
If user requests "ldiag", its index in the output sample.
unsigned int nidas::dynld::isff::SonicAnemometer::_noutVals protected
unsigned int nidas::dynld::isff::SonicAnemometer::_numParsed protected
Number of variables that are parsed from input, i.e.
not derived.
nidas::core::CalFile* nidas::dynld::isff::SonicAnemometer::_oaCalFile protected
CalFile containing wind offsets and rotation angles.
WindRotator nidas::dynld::isff::SonicAnemometer::_rotator protected
Referenced by getVazimuth(), and setVazimuth().
nidas::core::dsm_sample_id_t nidas::dynld::isff::SonicAnemometer::_sampleId protected
Id of output sample.
double nidas::dynld::isff::SonicAnemometer::_shadowFactor protected
Transducer shadow (aka flow distortion) correction factor.
This value can be set in the XML with a sensor parameter called "shadowFactor".
int nidas::dynld::isff::SonicAnemometer::_spdIndex protected
If user requests wind speed, variable name "spd", its index in the output sample.
int nidas::dynld::isff::SonicAnemometer::_sx[3] protected
Wind component sign conversion.
Also used for unusual sonic orientations, as when the sonic is hanging down, and the sign of v is flipped.
double nidas::dynld::isff::SonicAnemometer::_tcOffset protected
Referenced by getTcOffset(), and setTcOffset().
double nidas::dynld::isff::SonicAnemometer::_tcSlope protected
Referenced by getTcSlope(), and setTcSlope().
bool nidas::dynld::isff::SonicAnemometer::_tiltCorrection protected
Should 3D tilt correction be applied?
Referenced by setDoTiltCorrection().
WindTilter nidas::dynld::isff::SonicAnemometer::_tilter protected
Referenced by getLeanAzimuthDegrees(), getLeanDegrees(), setLeanAzimuthDegrees(), and setLeanDegrees().
nidas::core::dsm_time_t nidas::dynld::isff::SonicAnemometer::_ttlast[4] protected
int nidas::dynld::isff::SonicAnemometer::_tx[3] protected
Index transform vector for wind components.
Used for unusual sonic orientations, as when the sonic is hanging down, when the usual sonic w axis becomes the new u axis, u becomes w and v becomes -v.
bool nidas::dynld::isff::SonicAnemometer::_unusualOrientation protected
Is the sonic oriented in a unusual way, e.g.
upside-down, etc?
const int nidas::dynld::isff::SonicAnemometer::DATA_GAP_USEC = 60000000 static protected
The documentation for this class was generated from the following files:
nidas/dynld/isff/SonicAnemometer.h
nidas/dynld/isff/SonicAnemometer.cc