nidas: nidas::dynld::raf::SyncRecordGenerator Class Reference
nidas::dynld::raf::SyncRecordGenerator Class Reference
#include <SyncRecordGenerator.h>
Public Member Functions
SyncRecordGenerator ()
Constructor.
virtual ~SyncRecordGenerator ()
void connect (SampleSource *source) throw ()
Implementation of SampleIOProcessor::connect(SampleSource*).
void disconnect (SampleSource *source) throw ()
Implementation of SampleIOProcessor::disconnect(SampleSource*).
void connect (SampleOutput *output) throw ()
Implementation of SampleConnectionRequester::connect(SampleOutput*).
void disconnect (SampleOutput *output) throw ()
Implementation of SampleConnectionRequester::disconnect(SampleOutput*).
void sendHeader (dsm_time_t thead, SampleOutput *output) throw (nidas::util::IOException)
Method called to write a header to an SampleOutput.
void init (dsm_time_t sampleTime) throw ()
std::list< const SampleTag * > getSampleTags () const
Implementation of SampleSource::getSampleTags().
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void flush () throw ()
Implementation of SampleSource::flush().
const SampleStats & getSampleStats () const
void printStatus (std::ostream &, float deltat, int &) throw ()
SyncRecordSource * getSyncRecordSource ()
virtual const std::string & getName () const
virtual void setName (const std::string &val)
virtual void setOptional (bool val)
virtual bool isOptional () const
virtual const DSMService * getService () const
What DSMService am I associated with?
virtual void setService (const DSMService *val)
virtual const DSMConfig * getDSMConfig () const
What DSM am I associated with?
virtual void setDSMConfig (const DSMConfig *val)
dsm_sample_id_t getId () const
void setSampleId (int val)
unsigned int getSampleId () const
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual void addRequestedSampleTag (SampleTag *tag) throw (nidas::util::InvalidParameterException)
Add a request for a SampleTag from this SampleIOProcessor.
virtual std::list< const
SampleTag * > getRequestedSampleTags () const
void addSampleTag (const SampleTag *tag) throw ()
Implementation of SampleSource::addSampleTag().
void removeSampleTag (const SampleTag *tag) throw ()
virtual void addOutput (SampleOutput *val)
Add an SampleOutput to this SampleIOProcessor.
virtual const std::list
< SampleOutput * > & getOutputs () const
void addParameter (Parameter *val) throw (nidas::util::InvalidParameterException)
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
static void setDefaults (SampleInputHeader &header)
static void sendDefaultHeader (SampleOutput *output) throw (nidas::util::IOException)
Protected Member Functions
void scanSensors (const std::list< DSMSensor * > &sensors)
void allocateRecord (dsm_time_t timetag)
void removeRequestedSampleTag (SampleTag *tag)
Allow subclasses to remove requested SampleTags.
Protected Attributes
SampleSourceSupport _source
nidas::util::Mutex _tagsMutex
std::list< SampleTag * > _requestedTags
Private Member Functions
SyncRecordGenerator (const SyncRecordGenerator &)
No copying.
SyncRecordGenerator & operator= (const SyncRecordGenerator &)
No assignment.
Private Attributes
nidas::util::Mutex _connectionMutex
std::set< SampleSource * > _connectedSources
std::set< SampleOutput * > _connectedOutputs
SyncRecordSource _syncRecSource
size_t _numInputSampsLast
size_t _numOutputSampsLast
long long _numInputBytesLast
long long _numOutputBytesLast
Constructor & Destructor Documentation
SyncRecordGenerator::SyncRecordGenerator ()
Constructor.
References nidas::core::SampleIOProcessor::setName().
SyncRecordGenerator::~SyncRecordGenerator () virtual
References _connectedOutputs, _connectionMutex, _syncRecSource, nidas::core::SampleOutput::close(), nidas::core::SampleClient::flush(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getName(), nidas::core::SampleOutput::getOriginal(), nidas::util::Mutex::lock(), nidas::util::Logger::log(), LOG_ERR, nidas::dynld::raf::SyncRecordSource::removeSampleClient(), nidas::util::Mutex::unlock(), and nidas::util::Exception::what().
nidas::dynld::raf::SyncRecordGenerator::SyncRecordGenerator (const SyncRecordGenerator &) private
No copying.
Member Function Documentation
virtual void nidas::core::SampleIOProcessor::addOutput (SampleOutput * val) inline virtual inherited
Add an SampleOutput to this SampleIOProcessor.
This is used to add a desired SampleOutput to this SampleIOProcessor. SampleIOProcessor will own the SampleOutput. Once a SampleSource has connected, then SampleIOProcessor is responsible for do SampleOutput::requestConnection, or SampleOutputRequestThread::addConnectRequest() on all these as-yet disconnected outputs.
References nidas::core::SampleIOProcessor::_origOutputs.
void SampleIOProcessor::addParameter (Parameter * val) throw (nidas::util::InvalidParameterException) inherited
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
If a Parameter exists with the same name, it will be replaced with the new Parameter.
void SampleIOProcessor::addRequestedSampleTag (SampleTag * tag) throw (nidas::util::InvalidParameterException) virtual inherited
Add a request for a SampleTag from this SampleIOProcessor.
This SampleIOProcessor will own the SampleTag.
Reimplemented in nidas::dynld::raf::CVIProcessor, and nidas::dynld::StatisticsProcessor.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), and nidas::dynld::raf::CVIProcessor::addRequestedSampleTag().
void SyncRecordGenerator::addSampleClient (SampleClient * client) throw () virtual
Implementation of SampleSource::addSampleClient().
Reimplemented from nidas::core::SampleIOProcessor.
References DLOG.
Referenced by nidas::dynld::raf::SyncServer::init().
void nidas::dynld::raf::SyncRecordGenerator::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Reimplemented from nidas::core::SampleIOProcessor.
void SampleIOProcessor::addSampleTag (const SampleTag * tag) throw () virtual inherited
Implementation of SampleSource::addSampleTag().
Implements nidas::core::SampleSource.
void nidas::dynld::raf::SyncRecordGenerator::allocateRecord (dsm_time_t timetag) protected
void SyncRecordGenerator::connect (SampleSource * source) throw () virtual
Implementation of SampleIOProcessor::connect(SampleSource*).
Implements nidas::core::SampleIOProcessor.
References nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutput::addSourceSampleTags(), and nidas::core::SampleOutputRequestThread::getInstance().
Referenced by nidas::dynld::raf::SyncServer::init().
void SyncRecordGenerator::connect (SampleOutput * output) throw () virtual
Implementation of SampleConnectionRequester::connect(SampleOutput*).
Implements nidas::core::SampleConnectionRequester.
void SyncRecordGenerator::disconnect (SampleSource * source) throw () virtual
Implementation of SampleIOProcessor::disconnect(SampleSource*).
Implements nidas::core::SampleIOProcessor.
Referenced by nidas::dynld::raf::SyncServer::stop().
void SyncRecordGenerator::disconnect (SampleOutput * output) throw () virtual
Implementation of SampleConnectionRequester::disconnect(SampleOutput*).
Implements nidas::core::SampleConnectionRequester.
References nidas::core::SampleOutputRequestThread::addConnectRequest(), nidas::core::SampleOutputRequestThread::addDeleteRequest(), nidas::core::SampleOutputRequestThread::getInstance(), nidas::util::Logger::getInstance(), nidas::core::SampleOutput::getOriginal(), nidas::core::SampleOutput::getReconnectDelaySecs(), nidas::util::Logger::log(), LOG_ERR, and nidas::util::Exception::what().
void nidas::dynld::raf::SyncRecordGenerator::flush () throw () inline virtual
Implementation of SampleSource::flush().
Implements nidas::core::SampleSource.
void SampleIOProcessor::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual inherited
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::raf::CVIProcessor.
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Parameter::createParameter(), nidas::core::DOMable::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::Project::getInstance(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::SampleTag::getSampleId(), nidas::core::SampleTag::setSampleId(), nidas::core::SampleTag::setSensorId(), and nidas::util::Exception::what().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), and nidas::core::DSMConfig::fromDOMElement().
int nidas::dynld::raf::SyncRecordGenerator::getClientCount () const throw () inline virtual
How many SampleClients are currently in my list.
Reimplemented from nidas::core::SampleIOProcessor.
virtual const DSMConfig* nidas::core::SampleIOProcessor::getDSMConfig () const inline virtual inherited
What DSM am I associated with?
References nidas::core::SampleIOProcessor::_dsm.
dsm_sample_id_t nidas::core::SampleIOProcessor::getId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_FULL_ID.
const std::string & SampleIOProcessor::getName () const virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by nidas::dynld::raf::CVIProcessor::fromDOMElement(), nidas::dynld::RawSampleService::schedule(), and nidas::dynld::StatisticsProcessor::~StatisticsProcessor().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
virtual const std::list<SampleOutput*>& nidas::core::SampleIOProcessor::getOutputs () const inline virtual inherited
References nidas::core::SampleIOProcessor::_origOutputs.
Referenced by nidas::core::Project::findServerSampleOutputStreamFileSets(), nidas::dynld::isff::GOESProject::GOESProject(), and StatsProcess::run().
const std::list<const Parameter*>& nidas::core::SampleIOProcessor::getParameters () const inline inherited
Get list of parameters.
References nidas::core::SampleIOProcessor::_constParameters.
SampleSource* nidas::core::SampleIOProcessor::getProcessedSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References nidas::core::SampleIOProcessor::_source.
SampleSource* nidas::core::SampleIOProcessor::getRawSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
std::list< const SampleTag * > SampleIOProcessor::getRequestedSampleTags () const virtual inherited
References nidas::core::SampleIOProcessor::_constRequestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::core::SampleTagIterator::hasNext(), and StatsProcess::listOutputSamples().
unsigned int nidas::core::SampleIOProcessor::getSampleId () const inline inherited
References nidas::core::SampleIOProcessor::_id, and GET_SPS_ID.
Referenced by StatsProcess::listOutputSamples(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
const SampleStats& nidas::dynld::raf::SyncRecordGenerator::getSampleStats () const inline virtual
Reimplemented from nidas::core::SampleIOProcessor.
SampleTagIterator nidas::dynld::raf::SyncRecordGenerator::getSampleTagIterator () const inline virtual
Implementation of SampleSource::getSampleTagIterator().
Reimplemented from nidas::core::SampleIOProcessor.
std::list<const SampleTag*> nidas::dynld::raf::SyncRecordGenerator::getSampleTags () const inline virtual
Implementation of SampleSource::getSampleTags().
Reimplemented from nidas::core::SampleIOProcessor.
virtual const DSMService* nidas::core::SampleIOProcessor::getService () const inline virtual inherited
What DSMService am I associated with?
References nidas::core::SampleIOProcessor::_service.
SyncRecordSource* nidas::dynld::raf::SyncRecordGenerator::getSyncRecordSource () inline
void SyncRecordGenerator::init (dsm_time_t sampleTime) throw () virtual
Reimplemented from nidas::core::SampleIOProcessor.
References DLOG.
Referenced by nidas::dynld::raf::SyncServer::init().
virtual bool nidas::core::SampleIOProcessor::isOptional () const inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
Referenced by nidas::dynld::RawSampleService::schedule().
SyncRecordGenerator& nidas::dynld::raf::SyncRecordGenerator::operator= (const SyncRecordGenerator &) private
No assignment.
void SyncRecordGenerator::printStatus (std::ostream & , float deltat, int &) throw () virtual
Reimplemented from nidas::core::SampleIOProcessor.
References nidas::util::UTime::format(), nidas::core::SampleStats::getLastTimeTag(), nidas::core::SampleStats::getNumBytes(), nidas::core::SampleStats::getNumSamples(), and nidas::core::SampleSource::getSampleStats().
void SampleIOProcessor::removeRequestedSampleTag (SampleTag * tag) protected inherited
Allow subclasses to remove requested SampleTags.
The tag will be deleted.
References nidas::core::SampleIOProcessor::_constRequestedTags, nidas::core::SampleIOProcessor::_requestedTags, and nidas::core::SampleIOProcessor::_tagsMutex.
Referenced by nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
void nidas::dynld::raf::SyncRecordGenerator::removeSampleClient (SampleClient * c) throw () inline virtual
Remove a SampleClient from this SampleSource.
Reimplemented from nidas::core::SampleIOProcessor.
Referenced by nidas::dynld::raf::SyncServer::stop().
void nidas::dynld::raf::SyncRecordGenerator::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Reimplemented from nidas::core::SampleIOProcessor.
void SampleIOProcessor::removeSampleTag (const SampleTag * tag) throw () virtual inherited
Implements nidas::core::SampleSource.
void nidas::dynld::raf::SyncRecordGenerator::scanSensors (const std::list< DSMSensor * > & sensors) protected
void HeaderSource::sendDefaultHeader (SampleOutput * output) throw (nidas::util::IOException) static inherited
References nidas::core::SampleInputHeader::write().
Referenced by nidas::core::SampleOutputBase::createNextFile(), and sendHeader().
void SyncRecordGenerator::sendHeader (dsm_time_t thead, SampleOutput * output) throw (nidas::util::IOException) virtual
Method called to write a header to an SampleOutput.
Implements nidas::core::HeaderSource.
References DLOG, and nidas::core::HeaderSource::sendDefaultHeader().
void HeaderSource::setDefaults (SampleInputHeader & header) static inherited
References nidas::core::Version::getArchiveVersion(), nidas::core::Project::getInstance(), nidas::core::Version::getSoftwareVersion(), nidas::core::Project::getSystemName(), nidas::core::SampleInputHeader::setArchiveVersion(), nidas::core::SampleInputHeader::setConfigName(), nidas::core::SampleInputHeader::setConfigVersion(), nidas::core::SampleInputHeader::setProjectName(), nidas::core::SampleInputHeader::setSoftwareVersion(), and nidas::core::SampleInputHeader::setSystemName().
virtual void nidas::core::SampleIOProcessor::setDSMConfig (const DSMConfig * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_dsm.
Referenced by nidas::core::DSMConfig::fromDOMElement().
void SampleIOProcessor::setName (const std::string & val) virtual inherited
References nidas::core::SampleIOProcessor::_name.
Referenced by nidas::dynld::psql::PSQLProcessor::PSQLProcessor(), nidas::core::SampleArchiver::SampleArchiver(), nidas::dynld::StatisticsProcessor::StatisticsProcessor(), and SyncRecordGenerator().
virtual void nidas::core::SampleIOProcessor::setOptional (bool val) inline virtual inherited
References nidas::core::SampleIOProcessor::_optional.
void nidas::core::SampleIOProcessor::setSampleId (int val) inline inherited
References nidas::core::SampleIOProcessor::_id, and SET_SPS_ID.
virtual void nidas::core::SampleIOProcessor::setService (const DSMService * val) inline virtual inherited
References nidas::core::SampleIOProcessor::_service.
Referenced by nidas::core::DSMService::fromDOMElement().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
std::set<SampleOutput*> nidas::dynld::raf::SyncRecordGenerator::_connectedOutputs private
Referenced by ~SyncRecordGenerator().
std::set<SampleSource*> nidas::dynld::raf::SyncRecordGenerator::_connectedSources private
nidas::util::Mutex nidas::dynld::raf::SyncRecordGenerator::_connectionMutex private
Referenced by ~SyncRecordGenerator().
long long nidas::dynld::raf::SyncRecordGenerator::_numInputBytesLast private
size_t nidas::dynld::raf::SyncRecordGenerator::_numInputSampsLast private
long long nidas::dynld::raf::SyncRecordGenerator::_numOutputBytesLast private
size_t nidas::dynld::raf::SyncRecordGenerator::_numOutputSampsLast private
std::list<SampleTag*> nidas::core::SampleIOProcessor::_requestedTags protected inherited
Referenced by nidas::core::SampleIOProcessor::removeRequestedSampleTag(), nidas::dynld::StatisticsProcessor::selectRequestedSampleTags(), and nidas::core::SampleIOProcessor::~SampleIOProcessor().
SampleSourceSupport nidas::core::SampleIOProcessor::_source protected inherited
Referenced by nidas::core::SampleIOProcessor::addSampleClient(), nidas::core::SampleIOProcessor::addSampleClientForTag(), nidas::core::SampleIOProcessor::getClientCount(), nidas::core::SampleIOProcessor::getProcessedSampleSource(), nidas::core::SampleIOProcessor::getSampleStats(), nidas::core::SampleIOProcessor::getSampleTagIterator(), nidas::core::SampleIOProcessor::getSampleTags(), nidas::core::SampleIOProcessor::removeSampleClient(), and nidas::core::SampleIOProcessor::removeSampleClientForTag().
SyncRecordSource nidas::dynld::raf::SyncRecordGenerator::_syncRecSource private
Referenced by ~SyncRecordGenerator().
nidas::util::Mutex nidas::core::SampleIOProcessor::_tagsMutex mutable protected inherited
Referenced by nidas::core::SampleIOProcessor::getRequestedSampleTags(), nidas::core::SampleIOProcessor::removeRequestedSampleTag(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
The documentation for this class was generated from the following files:
nidas/dynld/raf/SyncRecordGenerator.h
nidas/dynld/raf/SyncRecordGenerator.cc