nidas: CuteLoggingExceptionHandler Class Reference
CuteLoggingExceptionHandler Class Reference
#include <CuteLoggingExceptionHandler.h>
Public Member Functions
CuteLoggingExceptionHandler (QWidget *parent=0)
~CuteLoggingExceptionHandler ()
virtual void display (std::string &where, std::string &what)
virtual void log (std::string &where, std::string &what)
virtual void show ()
virtual void hide ()
virtual void setVisible (bool checked=true)
virtual void handle (std::string &where)
void handle (const char *where)
void display (const char *where, std::string &what)
void display (std::string &where, const char *what)
void display (const char *where, const char *what)
Protected Attributes
QTextEdit * textwin
Constructor & Destructor Documentation
CuteLoggingExceptionHandler::CuteLoggingExceptionHandler (QWidget * parent = 0)
References hide(), and textwin.
CuteLoggingExceptionHandler::~CuteLoggingExceptionHandler () inline
Member Function Documentation
void CuteLoggingExceptionHandler::display (std::string & where, std::string & what) virtual
Implements UserFriendlyExceptionHandler.
Reimplemented in CuteLoggingStreamHandler.
References log(), and show().
void UserFriendlyExceptionHandler::display (const char * where, std::string & what) inline inherited
References UserFriendlyExceptionHandler::display().
void UserFriendlyExceptionHandler::display (std::string & where, const char * what) inline inherited
References UserFriendlyExceptionHandler::display().
void UserFriendlyExceptionHandler::display (const char * where, const char * what) inline inherited
References UserFriendlyExceptionHandler::display().
virtual void UserFriendlyExceptionHandler::handle (std::string & where) inline virtual inherited
References UserFriendlyExceptionHandler::display(), and nidas::util::Exception::what().
Referenced by UserFriendlyExceptionHandler::handle(), and ConfigWindow::openFile().
void UserFriendlyExceptionHandler::handle (const char * where) inline inherited
References UserFriendlyExceptionHandler::handle().
void CuteLoggingExceptionHandler::hide () virtual
Reimplemented from UserFriendlyExceptionHandler.
Referenced by CuteLoggingExceptionHandler().
virtual void CuteLoggingExceptionHandler::log (std::string & where, std::string & what) inline virtual
Reimplemented from UserFriendlyExceptionHandler.
References textwin.
Referenced by display(), and CuteLoggingStreamHandler::display().
void CuteLoggingExceptionHandler::setVisible (bool checked = true) virtual
Reimplemented from UserFriendlyExceptionHandler.
void CuteLoggingExceptionHandler::show () virtual
Reimplemented from UserFriendlyExceptionHandler.
Referenced by display(), and CuteLoggingStreamHandler::display().
Member Data Documentation
QTextEdit* CuteLoggingExceptionHandler::textwin protected
Referenced by CuteLoggingExceptionHandler(), CuteLoggingStreamHandler::display(), log(), CuteLoggingStreamHandler::overflow(), and CuteLoggingStreamHandler::xsputn().
The documentation for this class was generated from the following files:
nidas/apps/config/exceptions/CuteLoggingExceptionHandler.h
nidas/apps/config/exceptions/CuteLoggingExceptionHandler.cc