nidas: TestSource Class Reference
TestSource Class Reference
Public Types
enum runStatus { RUN_CANCELED = -1, RUN_OK = 0, NOT_RUNNING = 1, RUN_EXCEPTION = 2 }
Values that can be returned by run method.
enum SchedPolicy { NU_THREAD_OTHER =SCHED_OTHER, NU_THREAD_FIFO =SCHED_FIFO, NU_THREAD_RR =SCHED_RR }
Public Member Functions
TestSource ()
int run () throw (n_u::Exception)
The method which will run in its own thread.
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
void addSampleTag (const SampleTag *tag) throw ()
Add a SampleTag to this SampleSource.
void removeSampleTag (const SampleTag *tag) throw ()
std::list< const SampleTag * > getSampleTags () const
What SampleTags am I a SampleSource for?
SampleTagIterator getSampleTagIterator () const
void addSampleClient (SampleClient *c) throw ()
Add a SampleClient to this SampleSource.
void removeSampleClient (SampleClient *c) throw ()
Remove a SampleClient from this SampleSource This will also remove a SampleClient if it has been added with addSampleClientForTag().
void addSampleClientForTag (SampleClient *c, const SampleTag *) throw ()
Add a SampleClient to this SampleSource.
void removeSampleClientForTag (SampleClient *c, const SampleTag *) throw ()
Add a SampleClient to this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void removeAllSampleClients () throw ()
Big cleanup.
void distribute (const Sample *s) throw ()
Distribute a sample to my clients, calling the receive() method of each client, passing the const pointer to the Sample.
void distribute (const std::list< const Sample * > &samps) throw ()
Distribute a list of samples to my clients.
void flush () throw ()
This implementation of SampleSource::flush() does nothing.
const SampleStats & getSampleStats () const
void setKeepStats (bool val)
bool getKeepStats () const
virtual void start () throw (Exception)
Start the thread running, meaning execute the run method in a separate thread.
virtual int join () throw (Exception)
The calling thread joins this thread, waiting until the thread finishes, which means either that the run() method returned, the thread called pthread_exit() or the thread was cancelled.
virtual void kill (int sig) throw (Exception)
Send a signal to this thread.
virtual void cancel () throw (Exception)
Cancel this thread.
virtual void interrupt ()
Interrupt this thread.
virtual bool isInterrupted () const
Return true when this thread has been interrupted.
virtual bool isRunning () const
Is this thread running?
virtual bool isJoined () const
Has this thread been joined?
virtual bool isDetached () const
Is this a detached thread.
bool isCancelEnabled () const
Return true if the cancel state of this thread is PTHREAD_CANCEL_ENABLE.
bool isCancelDeferred () const
Return true if the cancel type of this thread is PTHREAD_CANCEL_DEFERRED.
const std::string & getName () const throw ()
Return the name of this thread.
const std::string & getFullName () throw ()
Return a name with a bunch of descriptive fields, specifying whether it is detached, the real-time priority, etc.
bool setRealTimeRoundRobinPriority (int val) throw (Exception)
bool setRealTimeFIFOPriority (int val) throw (Exception)
bool setNonRealTimePriority () throw (Exception)
void setThreadScheduler (enum SchedPolicy policy, int priority) throw (Exception)
void blockSignal (int)
Block a signal in this thread.
void unblockSignal (int)
Install a signal handler and unblock the signal.
Static Public Member Functions
static Thread * currentThread ()
Return the thread object for the current thread.
static pthread_t currentThreadId ()
static Thread * lookupThread (pthread_t id)
static const std::string & currentName ()
Convenience routine to return the name for the current thread, or a string indicating that the name of the thread is unknown.
static std::string getPolicyString (int policy)
Convenience function to return a string for the given scheduler policy: "Non-RT", "RT:FIFO", "RT:RR" or "RT:Unknown".
static int test (int argc, char **argv)
a test method.
Public Attributes
unsigned long nsamples
Protected Member Functions
void setCancelEnabled (bool val)
Set the cancel state for this thread - false means cancel requests are ignored.
void setCancelDeferred (bool val)
Set the cancel type for this thread.
pthread_t getId () const
void testCancel () const
Check if we have been cancelled.
virtual bool amInterrupted () const
Call testCancel, and return true when this thread has been interrupted.
Private Attributes
SampleTag _stag
Member Enumeration Documentation
enum nidas::util::Thread::runStatus inherited
Values that can be returned by run method.
User can define other values greater than RUN_EXCEPTION. These values are then returned by int join(). Note that PTHREAD_CANCELLED is -1
Enumerator
RUN_CANCELED
RUN_OK
NOT_RUNNING
RUN_EXCEPTION
enum nidas::util::Thread::SchedPolicy inherited
Enumerator
NU_THREAD_OTHER
NU_THREAD_FIFO
NU_THREAD_RR
Constructor & Destructor Documentation
TestSource::TestSource () inline
Member Function Documentation
void SampleSourceSupport::addSampleClient (SampleClient * c) throw () virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
Referenced by nidas::core::NearestResampler::addSampleClient(), nidas::core::SampleAverager::addSampleClient(), nidas::core::SampleBuffer::addSampleClient(), nidas::core::SampleSorter::addSampleClient(), nidas::core::NearestResamplerAtRate::addSampleClient(), nidas::core::SampleIOProcessor::addSampleClient(), nidas::dynld::SampleInputStream::addSampleClient(), nidas::core::DSMSensor::addSampleClient(), nidas::core::NearestResampler::addSampleClientForTag(), nidas::core::SampleAverager::addSampleClientForTag(), and nidas::core::NearestResamplerAtRate::addSampleClientForTag().
void SampleSourceSupport::addSampleClientForTag (SampleClient * c, const SampleTag * tag) throw () virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::core::SampleClientList::add().
Referenced by nidas::core::SampleBuffer::addSampleClientForTag(), nidas::core::SampleSorter::addSampleClientForTag(), nidas::core::SampleIOProcessor::addSampleClientForTag(), nidas::dynld::SampleInputStream::addSampleClientForTag(), and nidas::core::DSMSensor::addSampleClientForTag().
void SampleSourceSupport::addSampleTag (const SampleTag *) throw () virtual inherited
Add a SampleTag to this SampleSource.
This SampleSource does not own the SampleTag.
Implements nidas::core::SampleSource.
Referenced by nidas::core::SampleBuffer::addSampleTag(), nidas::core::SampleSorter::addSampleTag(), nidas::core::SampleAverager::addSampleTag(), nidas::core::NearestResampler::addSampleTag(), nidas::dynld::SampleInputStream::addSampleTag(), nidas::core::NearestResamplerAtRate::addSampleTag(), nidas::dynld::raf::SyncRecordSource::addSampleTag(), and nidas::core::DSMSensor::fromDOMElement().
bool Runnable::amInterrupted () const protected virtual inherited
Call testCancel, and return true when this thread has been interrupted.
This is protected because it should only called within the run method of the thread.
Referenced by nidas::core::SampleOutputRequestThread::run(), nidas::core::Looper::run(), nidas::core::DSMServerStat::run(), nidas::dynld::isff::GOESOutput::run(), and nidas::util::Thread::test().
void Thread::blockSignal (int sig) inherited
Block a signal in this thread.
This method is usually called before this Thread has started. If this Thread is currently running, then this method is only effective if called from this Thread, i.e. from its own run() method.
Because SIGINT, SIGTERM and SIGHUP are typically caught in the main thread, they are blocked by default in a Thread. Call unblockSignal(sig) if you want to catch them in a Thread.
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_unblockedSignals, nidas::util::Thread::currentThread(), nidas::util::Thread::isRunning(), and nidas::util::Thread::thr_add_sig().
Referenced by nidas::dynld::UDPSampleOutput::ConnectionMonitor::ConnectionMonitor(), nidas::core::ServerSocket::ConnectionThread::ConnectionThread(), nidas::core::DerivedDataReader::DerivedDataReader(), nidas::util::McSocketListener::McSocketListener(), nidas::util::McSocketMulticaster< SocketTT >::McSocketMulticaster(), nidas::core::SensorHandler::SensorHandler(), nidas::core::SensorOpener::SensorOpener(), nidas::util::Thread::test(), nidas::dynld::RawSampleService::Worker::Worker(), nidas::core::XmlRpcThread::XmlRpcThread(), and nidas::dynld::UDPSampleOutput::XMLSocketListener::XMLSocketListener().
void Thread::cancel () throw (Exception) virtual inherited
Cancel this thread.
References nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), and nidas::util::Thread::getName().
Referenced by nidas::core::DSMService::cancel(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::core::DerivedDataReader::deleteInstance(), and nidas::core::DSMEngine::joinDataThreads().
static const std::string& nidas::util::Thread::currentName () inline static inherited
Convenience routine to return the name for the current thread, or a string indicating that the name of the thread is unknown.
References nidas::util::Thread::currentThread(), nidas::util::Thread::getName(), and nidas::util::Thread::unknownName.
Referenced by nidas::util::Logger::msg_locked().
Thread * Thread::currentThread () static inherited
Return the thread object for the current thread.
Returns null if not found.
Referenced by nidas::util::Thread::blockSignal(), nidas::util::Thread::currentName(), and nidas::util::Thread::unblockSignal().
pthread_t Thread::currentThreadId () static inherited
Referenced by nidas::core::Looper::removeClient().
void SampleSourceSupport::distribute (const Sample * s) throw () inherited
Distribute a sample to my clients, calling the receive() method of each client, passing the const pointer to the Sample.
Does a s->freeReference() on the sample when done, which means you should assume that the pointer to the Sample is invalid after the call to distribute(), unless the owner has done an additional holdReference(). If so, it is very bad form to make any changes to Sample after the distribute() - the clients may get a half-changed Sample.
References nidas::core::SampleClientList::begin(), and nidas::core::SampleClientList::end().
Referenced by nidas::dynld::StatisticsCruncher::computeStats(), nidas::dynld::SampleInputStream::distribute(), nidas::core::DSMSensor::distributeRaw(), nidas::core::SampleAverager::flush(), nidas::core::NearestResampler::flush(), nidas::dynld::SampleInputStream::flush(), nidas::dynld::isff::PacketInputStream::readSamples(), nidas::core::DSMSensor::readSamples(), nidas::core::SampleBuffer::run(), nidas::core::SampleSorter::run(), nidas::dynld::raf::SyncRecordSource::sendSyncHeader(), and nidas::dynld::raf::SyncRecordSource::sendSyncRecord().
void SampleSourceSupport::distribute (const std::list< const Sample * > & samps) throw () inherited
Distribute a list of samples to my clients.
Calls receive() method of each client, passing the pointer to the Sample. Does a s->freeReference() on each sample in the list.
void nidas::core::SampleSourceSupport::flush () throw () inline virtual inherited
This implementation of SampleSource::flush() does nothing.
Implements nidas::core::SampleSource.
int SampleSourceSupport::getClientCount () const throw () virtual inherited
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
References nidas::core::SampleSourceSupport::_clientSet.
Referenced by nidas::dynld::SampleInputStream::flush(), nidas::core::NearestResampler::getClientCount(), nidas::core::SampleAverager::getClientCount(), nidas::core::SampleBuffer::getClientCount(), nidas::core::SampleSorter::getClientCount(), nidas::core::NearestResamplerAtRate::getClientCount(), nidas::core::SampleIOProcessor::getClientCount(), nidas::dynld::SampleInputStream::getClientCount(), and nidas::core::DSMSensor::getClientCount().
const std::string & Thread::getFullName () throw () inherited
Return a name with a bunch of descriptive fields, specifying whether it is detached, the real-time priority, etc.
References nidas::util::Thread::_fullname.
Referenced by nidas::util::Thread::pRun(), nidas::util::Thread::test(), nidas::util::Thread::thr_cleanup(), and nidas::util::Thread::thr_cleanup_delete().
pthread_t nidas::util::Thread::getId () const inline protected inherited
References nidas::util::Thread::_id, and nidas::util::Thread::_mutex.
Referenced by nidas::util::Thread::isJoined(), nidas::util::Thread::join(), nidas::util::Thread::pRun(), and nidas::core::Looper::removeClient().
bool nidas::core::SampleSourceSupport::getKeepStats () const inline inherited
References nidas::core::SampleSourceSupport::_keepStats.
Referenced by nidas::core::SampleBuffer::getKeepStats(), and nidas::core::SampleSorter::getKeepStats().
const std::string & Thread::getName () const throw () inherited
Return the name of this thread.
References nidas::util::Thread::_name.
Referenced by nidas::core::DSMService::cancel(), nidas::util::Thread::cancel(), nidas::core::DSMService::checkSubThreads(), nidas::core::SensorHandler::PolledDSMSensor::checkTimeout(), nidas::util::Thread::currentName(), nidas::core::SensorHandler::PolledDSMSensor::handlePollEvents(), nidas::core::SampleSorter::heapDecrement(), nidas::core::DSMService::interrupt(), nidas::core::DSMService::join(), nidas::util::Thread::join(), nidas::core::SamplePipeline::join(), nidas::core::FsMountWorkerThread::run(), nidas::core::SampleSorter::run(), nidas::util::ThreadJoiner::run(), nidas::util::Thread::sigAction(), nidas::util::Thread::start(), nidas::util::Thread::test(), nidas::util::LogContext::threadName(), nidas::core::SampleSorter::~SampleSorter(), and nidas::util::Thread::~Thread().
string Thread::getPolicyString (int policy) static inherited
Convenience function to return a string for the given scheduler policy: "Non-RT", "RT:FIFO", "RT:RR" or "RT:Unknown".
References nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_OTHER, and nidas::util::Thread::NU_THREAD_RR.
Referenced by nidas::core::DSMSensor::getLooper(), and nidas::util::Thread::makeFullName().
SampleSource* nidas::core::SampleSourceSupport::getProcessedSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References nidas::core::SampleSourceSupport::_raw.
Referenced by nidas::core::SampleBuffer::getProcessedSampleSource(), nidas::core::SampleSorter::getProcessedSampleSource(), and nidas::dynld::SampleInputStream::getProcessedSampleSource().
SampleSource* nidas::core::SampleSourceSupport::getRawSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
References nidas::core::SampleSourceSupport::_raw.
Referenced by nidas::core::SampleSorter::flush(), nidas::core::SampleBuffer::getRawSampleSource(), nidas::core::SampleSorter::getRawSampleSource(), nidas::dynld::SampleInputStream::getRawSampleSource(), nidas::core::SampleBuffer::run(), and nidas::core::SampleSorter::run().
const SampleStats& nidas::core::SampleSourceSupport::getSampleStats () const inline virtual inherited
Implements nidas::core::SampleSource.
References nidas::core::SampleSourceSupport::_stats.
Referenced by nidas::core::NearestResampler::getSampleStats(), nidas::core::SampleAverager::getSampleStats(), nidas::core::SampleBuffer::getSampleStats(), nidas::core::SampleSorter::getSampleStats(), nidas::core::SampleIOProcessor::getSampleStats(), nidas::core::NearestResamplerAtRate::getSampleStats(), nidas::dynld::SampleInputStream::getSampleStats(), and nidas::core::DSMSensor::getSampleStats().
SampleTagIterator SampleSourceSupport::getSampleTagIterator () const virtual inherited
Implements nidas::core::SampleSource.
Referenced by nidas::core::NearestResampler::getSampleTagIterator(), nidas::core::SampleAverager::getSampleTagIterator(), nidas::core::SampleBuffer::getSampleTagIterator(), nidas::core::SampleSorter::getSampleTagIterator(), nidas::core::NearestResamplerAtRate::getSampleTagIterator(), nidas::core::SampleIOProcessor::getSampleTagIterator(), and nidas::dynld::SampleInputStream::getSampleTagIterator().
list< const SampleTag * > SampleSourceSupport::getSampleTags () const virtual inherited
What SampleTags am I a SampleSource for?
Implements nidas::core::SampleSource.
References nidas::core::SampleSourceSupport::_sampleTags, and nidas::core::SampleSourceSupport::_tagsMutex.
Referenced by nidas::core::NearestResampler::getSampleTags(), nidas::core::SampleAverager::getSampleTags(), nidas::core::SampleBuffer::getSampleTags(), nidas::core::SampleSorter::getSampleTags(), nidas::core::NearestResamplerAtRate::getSampleTags(), nidas::core::SampleIOProcessor::getSampleTags(), nidas::dynld::SampleInputStream::getSampleTags(), and nidas::core::DSMSensor::getSampleTags().
void Thread::interrupt () virtual inherited
Interrupt this thread.
This sets a boolean which can be tested with isInterrupted(). It is up to the run() implementation to return when interrupted. This is a "soft" request to terminate the thread.
What follows is a discussion of when to use cancel(), kill(), or interrupt() to terminate a thread.
If you can consistently check the state of isInterrupted() in the run method, and return if it is true, at a time interval which is an acceptable amount of time to wait for the thread to terminate, then using interrupt() should work well.
If the run method does I/O, then things are usually a bit more complicated.
If all I/O is guaranteed to finish quickly, which is a rare situation, or is done with a timeout, such as using select/poll with a timeout before every read/write, then one could still use interrupt() as above, and the thread will terminate within the timeout period.
If the thread does blocking I/O operations, and the I/O might block for a period of time longer than you're willing to wait for the thread to terminate, then you need to use kill(sig) or cancel().
If a signal is sent to the thread with kill(sig) while the thread is blocking on an I/O operation, the I/O will immediately return with an errno of EINTR, and one could then return from the run method, after any necessary cleanup.
However there is a possibility that the signal could be missed. In order to make sure you receive a signal, you must block it, so that any received signals are held as pending, and then atomically unblock it with pselect/ppoll/epoll_pwait before performing the I/O operation.
If you do not use I/O timeouts, or kill(sig) with pselect/ppoll/epoll_pwait, or other tricks such as writing to a pipe that is watched with select/poll in the run method, then using cancel() is the only way to guarantee that your thread will terminate in an acceptable amount of time.
All NIDAS Threads support deferred cancelation. Immediate asynchronous cancellation is not fully supported (and is very hard to get right). Deferred cancelation means that cancellation is delayed until the thread next calls a system function that is a cancellation point. At that point the thread run method will simply terminate without any return value from the system function, and then execute any cleanup methods that may have been registered with pthread_cleanup_push.
A list of cancellation points is provided in the pthreads(7) man page. Cancellation points are typically I/O operations, waits or sleeps.
This immediate thread termination can be a problem if there is a possibility that your objects could be left in a bad state, such as with a mutex locked, though it isn't generally a good practice to hold mutexes during a time-consuming I/O operation, wait or sleep.
One should check the run method to see if the state of the objects is OK if execution stops at any of the cancellation points. Note that logging a message, or writing to cerr is a cancellation point. Typically there is error/exception handling associated with an I/O operation. Ensuring the state is OK upon a cancellation is similar to preparation for a fatal I/O error that requires a return of the run method. One can use setCancelEnabled() to defer cancellation.
One can use pthread_cleanup_push and pthread_cleanup_pop to register cleanup routines that are called when a thread is cancelled if special handling is required.
Implements nidas::util::Runnable.
Reimplemented in nidas::util::McSocketMulticaster< SocketTT >, nidas::util::ThreadRunnable, nidas::util::McSocketListener, nidas::core::ServerSocket::ConnectionThread, nidas::core::Socket::ConnectionThread, nidas::dynld::RawSampleService::Worker, nidas::dynld::UDPSampleOutput::XMLSocketListener, nidas::core::SampleSorter, nidas::core::SensorHandler, nidas::core::SampleBuffer, nidas::dynld::UDPSampleOutput::VariableListWorker, nidas::dynld::raf::SyncServer, nidas::core::DerivedDataReader, nidas::core::SensorOpener, nidas::dynld::XMLConfigService::Worker, nidas::core::SampleOutputRequestThread, and nidas::core::XmlRpcThread.
References nidas::util::Thread::_interrupted, and nidas::util::Thread::_mutex.
Referenced by nidas::dynld::UDPSampleOutput::close(), nidas::util::McSocket< SocketT >::close(), nidas::core::SampleOutputRequestThread::interrupt(), nidas::core::SensorOpener::interrupt(), nidas::dynld::raf::SyncServer::interrupt(), nidas::core::DSMService::interrupt(), nidas::core::SampleSorter::interrupt(), nidas::core::SamplePipeline::interrupt(), nidas::core::DSMEngine::interrupt(), nidas::util::McSocketListener::interrupt(), nidas::core::SamplePipeline::join(), nidas::core::Looper::removeClient(), and nidas::dynld::UDPSampleOutput::~UDPSampleOutput().
bool Thread::isCancelDeferred () const inherited
Return true if the cancel type of this thread is PTHREAD_CANCEL_DEFERRED.
References nidas::util::Thread::_cancel_deferred.
bool Thread::isCancelEnabled () const inherited
Return true if the cancel state of this thread is PTHREAD_CANCEL_ENABLE.
References nidas::util::Thread::_cancel_enabled.
virtual bool nidas::util::Thread::isDetached () const inline virtual inherited
Is this a detached thread.
References nidas::util::Thread::_detached.
virtual bool nidas::util::Thread::isInterrupted () const inline virtual inherited
Return true when this thread has been interrupted.
Implements nidas::util::Runnable.
References nidas::util::Thread::_interrupted, and nidas::util::Thread::_mutex.
Referenced by nidas::core::SampleSorter::flush(), nidas::core::SampleOutputRequestThread::run(), nidas::core::StatusListener::run(), nidas::core::DerivedDataReader::run(), nidas::core::DSMEngineStat::run(), nidas::core::SensorOpener::run(), Sender::run(), nidas::core::SensorHandler::run(), nidas::core::FsMountWorkerThread::run(), ModemLineSetter::run(), ModemLineMonitor::run(), nidas::core::SampleBuffer::run(), nidas::core::SampleSorter::run(), ServerThread::run(), and nidas::util::McSocketListener::run().
virtual bool nidas::util::Thread::isJoined () const inline virtual inherited
Has this thread been joined?
References nidas::util::Thread::getId().
Referenced by nidas::core::FsMount::cancel(), nidas::core::DerivedDataReader::deleteInstance(), nidas::core::SensorHandler::join(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::util::Thread::test(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), and nidas::util::Thread::~Thread().
virtual bool nidas::util::Thread::isRunning () const inline virtual inherited
Is this thread running?
References nidas::util::Thread::_mutex, and nidas::util::Thread::_running.
Referenced by nidas::util::Thread::blockSignal(), nidas::core::DSMService::cancel(), nidas::core::FsMount::cancel(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::core::DSMService::checkSubThreads(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::dynld::UDPSampleOutput::close(), nidas::util::McSocket< SocketT >::close(), nidas::core::DerivedDataReader::deleteInstance(), nidas::core::DSMService::interrupt(), nidas::core::SamplePipeline::join(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::core::DSMServerApp::killStatusThread(), nidas::dynld::isff::GOESOutput::killThread(), nidas::core::Looper::removeClient(), nidas::core::SensorHandler::run(), nidas::core::Looper::setupClientMaps(), nidas::util::Thread::test(), nidas::util::Thread::unblockSignal(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), nidas::util::Thread::~Thread(), and nidas::dynld::UDPSampleOutput::~UDPSampleOutput().
int Thread::join () throw (Exception) virtual inherited
The calling thread joins this thread, waiting until the thread finishes, which means either that the run() method returned, the thread called pthread_exit() or the thread was cancelled.
The return value is the int return value of the run method, or PTHREAD_CANCELED (-1). If the run method threw an Exception, it will be caught and then re-thrown by join.
Reimplemented in nidas::core::SensorHandler.
References nidas::util::Thread::_exception, nidas::util::Thread::_id, nidas::util::Thread::_mutex, nidas::util::Exception::errnoToString(), nidas::util::Thread::getId(), nidas::util::Thread::getName(), nidas::util::Thread::RUN_EXCEPTION, and nidas::util::Thread::RUN_OK.
Referenced by nidas::core::DSMService::checkSubThreads(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::dynld::UDPSampleOutput::close(), nidas::util::McSocketListener::close(), nidas::core::DerivedDataReader::deleteInstance(), nidas::dynld::UDPSampleOutput::XMLSocketListener::fireWorkers(), nidas::core::DSMService::join(), nidas::core::SensorHandler::join(), nidas::core::SamplePipeline::join(), nidas::core::DSMEngine::joinDataThreads(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::core::DSMServerApp::killStatusThread(), nidas::core::DSMServerApp::killXmlRpcThread(), nidas::core::DSMEngine::killXmlRpcThread(), main(), nidas::core::Looper::removeClient(), nidas::util::ThreadJoiner::run(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::core::SampleSorter::~SampleSorter(), nidas::core::ServerSocket::~ServerSocket(), and nidas::dynld::UDPSampleOutput::~UDPSampleOutput().
void Thread::kill (int sig) throw (Exception) virtual inherited
Send a signal to this thread.
References nidas::util::Exception::errnoToString().
Referenced by nidas::core::FsMount::cancel(), nidas::core::XmlRpcThread::interrupt(), nidas::core::SensorOpener::interrupt(), nidas::core::DerivedDataReader::interrupt(), nidas::core::SensorHandler::interrupt(), nidas::util::McSocketListener::interrupt(), nidas::core::DSMServerApp::killStatusThread(), nidas::dynld::isff::GOESOutput::killThread(), main(), nidas::core::SensorHandler::scheduleAdd(), nidas::core::SensorHandler::scheduleClose(), nidas::core::SensorHandler::scheduleReopen(), and nidas::core::SensorHandler::sensorIsOpen().
Thread * Thread::lookupThread (pthread_t id) static inherited
Referenced by nidas::util::LogContext::threadName().
void nidas::core::SampleSourceSupport::removeAllSampleClients () throw () inline inherited
Big cleanup.
References nidas::core::SampleSourceSupport::_clientMapLock, nidas::core::SampleSourceSupport::_clients, nidas::core::SampleSourceSupport::_clientSet, nidas::util::Mutex::lock(), nidas::core::SampleClientList::removeAll(), and nidas::util::Mutex::unlock().
void SampleSourceSupport::removeSampleClient (SampleClient * c) throw () virtual inherited
Remove a SampleClient from this SampleSource This will also remove a SampleClient if it has been added with addSampleClientForTag().
Implements nidas::core::SampleSource.
Referenced by nidas::core::NearestResampler::removeSampleClient(), nidas::core::SampleAverager::removeSampleClient(), nidas::core::SampleBuffer::removeSampleClient(), nidas::core::SampleSorter::removeSampleClient(), nidas::core::NearestResamplerAtRate::removeSampleClient(), nidas::core::SampleIOProcessor::removeSampleClient(), nidas::dynld::SampleInputStream::removeSampleClient(), nidas::core::DSMSensor::removeSampleClient(), nidas::core::NearestResampler::removeSampleClientForTag(), nidas::core::SampleAverager::removeSampleClientForTag(), and nidas::core::NearestResamplerAtRate::removeSampleClientForTag().
void SampleSourceSupport::removeSampleClientForTag (SampleClient * c, const SampleTag * tag) throw () virtual inherited
Add a SampleClient to this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
Referenced by nidas::core::SampleBuffer::removeSampleClientForTag(), nidas::core::SampleSorter::removeSampleClientForTag(), nidas::core::SampleIOProcessor::removeSampleClientForTag(), nidas::dynld::SampleInputStream::removeSampleClientForTag(), and nidas::core::DSMSensor::removeSampleClientForTag().
void SampleSourceSupport::removeSampleTag (const SampleTag * tag) throw () virtual inherited
Implements nidas::core::SampleSource.
Referenced by nidas::core::SampleBuffer::removeSampleTag(), nidas::core::SampleSorter::removeSampleTag(), nidas::core::SampleAverager::removeSampleTag(), nidas::core::NearestResampler::removeSampleTag(), nidas::dynld::SampleInputStream::removeSampleTag(), and nidas::core::NearestResamplerAtRate::removeSampleTag().
int TestSource::run () throw (n_u::Exception) virtual
The method which will run in its own thread.
This method must be supplied by the Runnable or Thread subclass.
Implements nidas::util::Runnable.
References nidas::core::SampleT< DataT >::freeReference(), nidas::core::SampleTag::getId(), nidas::util::getSystemTime(), nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), and USECS_PER_MSEC.
void Thread::setCancelDeferred (bool val) protected inherited
Set the cancel type for this thread.
true means cancel requests are deferred until the next cancellation point. false means they occur instantly. This is protected, it should be called only from a thread's own run method. See the pthreads(7) man page for a list of the cancellation points.
Note: non-deferred canceling is difficult to get right. It has not been tested with this class, and is not recommended.
References nidas::util::Thread::_cancel_deferred.
void Thread::setCancelEnabled (bool val) protected inherited
Set the cancel state for this thread - false means cancel requests are ignored.
See pthread_setcancelstate. This is protected, it should be called only from a thread's own run method.
References nidas::util::Thread::_cancel_enabled.
void nidas::core::SampleSourceSupport::setKeepStats (bool val) inline inherited
References nidas::core::SampleSourceSupport::_keepStats.
Referenced by nidas::core::SampleBuffer::setKeepStats(), nidas::core::SampleSorter::setKeepStats(), and nidas::dynld::SampleInputStream::setKeepStats().
bool Thread::setNonRealTimePriority () throw (Exception) inherited
References nidas::util::Thread::NU_THREAD_OTHER, and nidas::util::Thread::setThreadScheduler().
bool Thread::setRealTimeFIFOPriority (int val) throw (Exception) inherited
Referenced by nidas::core::DSMEngine::openSensors(), nidas::core::SamplePipeline::procinit(), and nidas::core::SamplePipeline::rawinit().
bool Thread::setRealTimeRoundRobinPriority (int val) throw (Exception) inherited
void Thread::setThreadScheduler (enum SchedPolicy policy, int priority) throw (Exception) inherited
Referenced by nidas::dynld::RawSampleService::connect(), nidas::core::DSMSensor::getLooper(), and nidas::util::Thread::setNonRealTimePriority().
void Thread::start () throw (Exception) virtual inherited
Start the thread running, meaning execute the run method in a separate thread.
References nidas::util::Thread::_id, nidas::util::Thread::_interrupted, nidas::util::Thread::_mutex, nidas::util::Thread::_running, nidas::util::Thread::_thread_attr, nidas::util::Exception::errnoToString(), nidas::util::Thread::getName(), ILOG, nidas::util::Thread::makeFullName(), nidas::util::Thread::NU_THREAD_FIFO, nidas::util::Thread::NU_THREAD_OTHER, nidas::util::Thread::NU_THREAD_RR, nidas::util::Thread::registerThread(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::thr_run(), and nidas::util::Thread::thr_run_detached().
Referenced by nidas::util::McSocketListener::accept(), nidas::dynld::RawSampleService::connect(), nidas::core::DerivedDataReader::createInstance(), nidas::util::McSocket< SocketT >::joinMulticaster(), main(), nidas::core::DSMEngine::openSensors(), nidas::core::SamplePipeline::procinit(), nidas::core::SamplePipeline::rawinit(), nidas::util::McSocket< SocketT >::request(), nidas::core::DSMServerApp::run(), nidas::core::DSMEngine::run(), PSI::run(), nidas::core::SensorHandler::run(), nidas::core::FsMountWorkerThread::run(), nidas::dynld::UDPSampleOutput::XMLSocketListener::run(), nidas::core::Socket::ConnectionThread::run(), ServerThread::run(), nidas::core::Looper::setupClientMaps(), nidas::core::DSMServerApp::startXmlRpcThread(), and nidas::core::DSMEngine::startXmlRpcThread().
int Thread::test (int argc, char ** argv) static inherited
a test method.
References nidas::util::Runnable::amInterrupted(), nidas::util::Thread::blockSignal(), nidas::util::Thread::getFullName(), nidas::util::Thread::getName(), nidas::util::Thread::isJoined(), nidas::util::Thread::isRunning(), nidas::util::Runnable::run(), nidas::util::Thread::Thread(), and nidas::util::Exception::what().
void nidas::util::Runnable::testCancel () const inline protected inherited
Check if we have been cancelled.
Calls pthread_testcancel. This is protected since it only checks the current thread - i.e. it must be called within the run method. Since it just calls pthread_testcancel, it is a cancellation point.
void Thread::unblockSignal (int sig) inherited
Install a signal handler and unblock the signal.
The signal handler will log a message about the receipt of the signal at severity LOG_INFO using the nidas::util::Logger. Then, if the signal handler is being invoked from a registered Thread, the virtual method signalHandler() for that Thread will be called.
The signal handler is installed with the sigaction() system call, and will be the action for the given signal in all threads, including the main() thread. If other threads do not wish to take action on a given signal, they should call blockSignal(sig). Or they can define their own signalHandler() method.
After installing the signal handler, the signal is added to those that are unblocked for the thread, or if the Thread is not yet running, the signal will be unblocked in the thread once it runs.
As with blockSignal(), this method is typically called on this Thread before it has started. If this Thread has started, then the signal will only be unblocked if the method is called from this Thread, i.e. from its own run() method.
To install a signal handler, and then block the signal so that it is held as pending until it is later unblocked, typically with pselect(), or sigwaitinfo(), do:
* void Thread::run()
* {
*     // get the existing signal mask
*     sigset_t sigmask;
*     pthread_sigmask(SIG_BLOCK,NULL,&sigmask);
*     // remove SIGUSR1 from the mask passed to pselect
*     sigdelset(&sigmask,SIGUSR1);
*
*     for (;;) {
*         pselect(nfd,&readfds,0,0,0,&sigmask);
*         ...
*     }
* }
* ...
* thread.unblockSignal(SIGUSR1);
* thread.blockSignal(SIGUSR1);
* thread.start();
* ...
* try {
*     if (thread.isRunning()) {
*         thread.kill(SIGUSR1);
*         thread.join()
*     }
* }
*
References nidas::util::Thread::_blockedSignals, nidas::util::Thread::_unblockedSignals, nidas::util::Thread::currentThread(), nidas::util::Thread::isRunning(), and nidas::util::Thread::thr_add_sig().
Referenced by nidas::core::DerivedDataReader::DerivedDataReader(), nidas::core::FsMountWorkerThread::FsMountWorkerThread(), nidas::core::StatusListener::StatusListener(), nidas::core::StatusThread::StatusThread(), nidas::dynld::XMLConfigService::Worker::Worker(), nidas::core::XmlRpcThread::XmlRpcThread(), and nidas::dynld::UDPSampleOutput::XMLSocketListener::XMLSocketListener().
Member Data Documentation
SampleTag TestSource::_stag private
unsigned long TestSource::nsamples
The documentation for this class was generated from the following file:
nidas/apps/sample_test.cc