nidas: nidas::core::SampleIOProcessor Class Reference
nidas::core::SampleIOProcessor Class Reference abstract
Interface of a processor of samples.
#include <SampleIOProcessor.h>
Public Member Functions
SampleIOProcessor (bool raw)
Does this processor generate raw or processed samples.
virtual ~SampleIOProcessor ()
virtual const std::string & getName () const
virtual void setName (const std::string &val)
virtual void setOptional (bool val)
virtual bool isOptional () const
virtual const DSMService * getService () const
What DSMService am I associated with?
virtual void setService (const DSMService *val)
virtual const DSMConfig * getDSMConfig () const
What DSM am I associated with?
virtual void setDSMConfig (const DSMConfig *val)
dsm_sample_id_t getId () const
void setSampleId (int val)
unsigned int getSampleId () const
virtual void connect (SampleSource *)=0 throw (nidas::util::InvalidParameterException,nidas::util::IOException)
Connect a SampleSource to this SampleIOProcessor.
virtual void disconnect (SampleSource *)=0 throw ()
Disconnect a SampleSource from this SampleIOProcessor.
SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
virtual void addRequestedSampleTag (SampleTag *tag) throw (nidas::util::InvalidParameterException)
Add a request for a SampleTag from this SampleIOProcessor.
virtual std::list< const
SampleTag * > getRequestedSampleTags () const
void addSampleTag (const SampleTag *tag) throw ()
Implementation of SampleSource::addSampleTag().
void removeSampleTag (const SampleTag *tag) throw ()
std::list< const SampleTag * > getSampleTags () const
Implementation of SampleSource::getSampleTags().
SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (SampleClient *client, const SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
const SampleStats & getSampleStats () const
virtual void addOutput (SampleOutput *val)
Add an SampleOutput to this SampleIOProcessor.
virtual const std::list
< SampleOutput * > & getOutputs () const
void addParameter (Parameter *val) throw (nidas::util::InvalidParameterException)
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
const std::list< const
Parameter * > & getParameters () const
Get list of parameters.
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
virtual void printStatus (std::ostream &, float, int &) throw ()
virtual void init (dsm_time_t) throw ()
virtual void flush ()=0 throw ()
Request that this SampleSource flush it's samples.
virtual void connect (SampleOutput *output)=0 throw ()
How SampleOutputs notify their SampleConnectionRequester that they are connected.
virtual void disconnect (SampleOutput *output)=0 throw ()
How SampleOutputs notify their SampleConnectionRequester that they wish to be closed, likely do to an IOException.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void removeRequestedSampleTag (SampleTag *tag)
Allow subclasses to remove requested SampleTags.
Protected Attributes
SampleSourceSupport _source
nidas::util::Mutex _tagsMutex
std::list< SampleTag * > _requestedTags
Private Member Functions
SampleIOProcessor (const SampleIOProcessor &)
Copy not supported.
SampleIOProcessor & operator= (const SampleIOProcessor &)
Assignment not supported.
Private Attributes
std::string _name
dsm_sample_id_t _id
std::list< const SampleTag * > _constRequestedTags
std::list< SampleOutput * > _origOutputs
bool _optional
const DSMService * _service
What service am I a part of?
const DSMConfig * _dsm
Or, what DSM am I a part of?
std::list< Parameter * > _parameters
std::list< const Parameter * > _constParameters
Detailed Description
Interface of a processor of samples.
A SampleIOProcessor reads input Samples from a SamplePipeline, and sends its processed output Samples to one or more SampleOutputs.
Constructor & Destructor Documentation
SampleIOProcessor::SampleIOProcessor (bool raw)
Does this processor generate raw or processed samples.
Typically they are processed samples (duh), but not always.
SampleIOProcessor::~SampleIOProcessor () virtual
References _origOutputs, _parameters, _requestedTags, nidas::core::SampleOutput::close(), nidas::core::SampleClient::flush(), and nidas::core::SampleOutput::getName().
nidas::core::SampleIOProcessor::SampleIOProcessor (const SampleIOProcessor &) private
Copy not supported.
Member Function Documentation
virtual void nidas::core::SampleIOProcessor::addOutput (SampleOutput * val) inline virtual
Add an SampleOutput to this SampleIOProcessor.
This is used to add a desired SampleOutput to this SampleIOProcessor. SampleIOProcessor will own the SampleOutput. Once a SampleSource has connected, then SampleIOProcessor is responsible for do SampleOutput::requestConnection, or SampleOutputRequestThread::addConnectRequest() on all these as-yet disconnected outputs.
References _origOutputs.
void SampleIOProcessor::addParameter (Parameter * val) throw (nidas::util::InvalidParameterException)
Add a parameter to this SampleIOProcessor, which will then own the pointer and will delete it in its destructor.
If a Parameter exists with the same name, it will be replaced with the new Parameter.
void SampleIOProcessor::addRequestedSampleTag (SampleTag * tag) throw (nidas::util::InvalidParameterException) virtual
Add a request for a SampleTag from this SampleIOProcessor.
This SampleIOProcessor will own the SampleTag.
Reimplemented in nidas::dynld::raf::CVIProcessor, and nidas::dynld::StatisticsProcessor.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), and nidas::dynld::raf::CVIProcessor::addRequestedSampleTag().
void nidas::core::SampleIOProcessor::addSampleClient (SampleClient * client) throw () inline virtual
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References _source, and nidas::core::SampleSourceSupport::addSampleClient().
void nidas::core::SampleIOProcessor::addSampleClientForTag (SampleClient * client, const SampleTag * tag) throw () inline virtual
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References _source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
void SampleIOProcessor::addSampleTag (const SampleTag * tag) throw () virtual
Implementation of SampleSource::addSampleTag().
Implements nidas::core::SampleSource.
virtual void nidas::core::SampleConnectionRequester::connect (SampleOutput * output) throw () pure virtual inherited
How SampleOutputs notify their SampleConnectionRequester that they are connected.
Implemented in nidas::core::DSMEngine, nidas::dynld::raf::SyncServer, nidas::core::SampleArchiver, nidas::dynld::StatisticsProcessor, nidas::dynld::raf::CVIProcessor, nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::SampleProcessor.
virtual void nidas::core::SampleIOProcessor::connect (SampleSource *) throw (nidas::util::InvalidParameterException, nidas::util::IOException) pure virtual
Connect a SampleSource to this SampleIOProcessor.
SampleIOProcessor does not own the SampleSource.
Implemented in nidas::core::SampleArchiver, nidas::dynld::StatisticsProcessor, nidas::dynld::raf::CVIProcessor, nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::SampleProcessor.
Referenced by nidas::dynld::psql::PSQLProcessor::connect(), nidas::core::DSMEngine::connectProcessors(), and nidas::dynld::RawSampleService::schedule().
virtual void nidas::core::SampleConnectionRequester::disconnect (SampleOutput * output) throw () pure virtual inherited
How SampleOutputs notify their SampleConnectionRequester that they wish to be closed, likely do to an IOException.
Implemented in nidas::core::DSMEngine, nidas::dynld::raf::SyncServer, nidas::dynld::StatisticsProcessor, nidas::core::SampleArchiver, nidas::dynld::raf::CVIProcessor, nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::SampleProcessor.
Referenced by nidas::core::SampleOutputBase::disconnect().
virtual void nidas::core::SampleIOProcessor::disconnect (SampleSource *) throw () pure virtual
Disconnect a SampleSource from this SampleIOProcessor.
Implemented in nidas::core::SampleArchiver, nidas::dynld::StatisticsProcessor, nidas::dynld::raf::CVIProcessor, nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::SampleProcessor.
Referenced by nidas::dynld::psql::PSQLProcessor::disconnect(), nidas::core::DSMEngine::disconnectProcessors(), and nidas::dynld::RawSampleService::interrupt().
virtual void nidas::core::SampleSource::flush () throw () pure virtual inherited
Request that this SampleSource flush it's samples.
One must think about whether to call flush() on SampleClients of this SampleSource. A SampleClient may have multiple SampleSources and a flush() of it when one SampleSource() is done may not be what is wanted.
Implemented in nidas::core::DSMSensor, nidas::dynld::raf::SyncRecordSource, nidas::dynld::SampleInputStream, nidas::core::NearestResamplerAtRate, nidas::core::SamplePipeline, nidas::core::SampleSorter, nidas::core::SampleSourceSupport, nidas::core::SampleBuffer, nidas::core::NearestResampler, nidas::dynld::StatisticsCruncher, nidas::dynld::raf::SyncRecordGenerator, nidas::core::SampleAverager, nidas::dynld::isff::PacketInputStream, nidas::dynld::StatisticsProcessor, nidas::core::SampleThread, nidas::dynld::raf::CVIProcessor, nidas::core::SampleArchiver, nidas::core::Resampler, and nidas::dynld::SampleProcessor.
Referenced by nidas::core::DSMEngine::disconnectProcessors().
void SampleIOProcessor::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
Reimplemented in nidas::dynld::raf::CVIProcessor.
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Parameter::createParameter(), nidas::core::DOMable::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::Project::getInstance(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), nidas::core::SampleTag::getSampleId(), nidas::core::SampleTag::setSampleId(), nidas::core::SampleTag::setSensorId(), and nidas::util::Exception::what().
Referenced by nidas::core::DSMService::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), and nidas::core::DSMConfig::fromDOMElement().
int nidas::core::SampleIOProcessor::getClientCount () const throw () inline virtual
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References _source, and nidas::core::SampleSourceSupport::getClientCount().
virtual const DSMConfig* nidas::core::SampleIOProcessor::getDSMConfig () const inline virtual
What DSM am I associated with?
References _dsm.
dsm_sample_id_t nidas::core::SampleIOProcessor::getId () const inline
References _id, and GET_FULL_ID.
const std::string & SampleIOProcessor::getName () const virtual
References _name.
Referenced by nidas::dynld::raf::CVIProcessor::fromDOMElement(), nidas::dynld::RawSampleService::schedule(), and nidas::dynld::StatisticsProcessor::~StatisticsProcessor().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
virtual const std::list<SampleOutput*>& nidas::core::SampleIOProcessor::getOutputs () const inline virtual
References _origOutputs.
Referenced by nidas::core::Project::findServerSampleOutputStreamFileSets(), nidas::dynld::isff::GOESProject::GOESProject(), and StatsProcess::run().
const std::list<const Parameter*>& nidas::core::SampleIOProcessor::getParameters () const inline
Get list of parameters.
References _constParameters.
SampleSource* nidas::core::SampleIOProcessor::getProcessedSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References _source.
SampleSource* nidas::core::SampleIOProcessor::getRawSampleSource () inline virtual
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
std::list< const SampleTag * > SampleIOProcessor::getRequestedSampleTags () const virtual
References _constRequestedTags, and _tagsMutex.
Referenced by nidas::core::SampleTagIterator::hasNext(), and StatsProcess::listOutputSamples().
unsigned int nidas::core::SampleIOProcessor::getSampleId () const inline
References _id, and GET_SPS_ID.
Referenced by StatsProcess::listOutputSamples(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
const SampleStats& nidas::core::SampleIOProcessor::getSampleStats () const inline virtual
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References _source, and nidas::core::SampleSourceSupport::getSampleStats().
SampleTagIterator nidas::core::SampleIOProcessor::getSampleTagIterator () const inline virtual
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References _source, and nidas::core::SampleSourceSupport::getSampleTagIterator().
std::list<const SampleTag*> nidas::core::SampleIOProcessor::getSampleTags () const inline virtual
Implementation of SampleSource::getSampleTags().
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator, and nidas::dynld::psql::PSQLProcessor.
References _source, and nidas::core::SampleSourceSupport::getSampleTags().
virtual const DSMService* nidas::core::SampleIOProcessor::getService () const inline virtual
What DSMService am I associated with?
References _service.
virtual void nidas::core::SampleIOProcessor::init (dsm_time_t) throw () inline virtual
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
Referenced by nidas::dynld::RawSampleService::schedule().
virtual bool nidas::core::SampleIOProcessor::isOptional () const inline virtual
References _optional.
Referenced by nidas::dynld::RawSampleService::schedule().
SampleIOProcessor& nidas::core::SampleIOProcessor::operator= (const SampleIOProcessor &) private
Assignment not supported.
virtual void nidas::core::SampleIOProcessor::printStatus (std::ostream & , float , int &) throw () inline virtual
Reimplemented in nidas::dynld::raf::SyncRecordGenerator, and nidas::core::SampleArchiver.
Referenced by nidas::dynld::RawSampleService::printStatus().
void SampleIOProcessor::removeRequestedSampleTag (SampleTag * tag) protected
Allow subclasses to remove requested SampleTags.
The tag will be deleted.
References _constRequestedTags, _requestedTags, and _tagsMutex.
Referenced by nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
void nidas::core::SampleIOProcessor::removeSampleClient (SampleClient * c) throw () inline virtual
Remove a SampleClient from this SampleSource.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References _source, and nidas::core::SampleSourceSupport::removeSampleClient().
void nidas::core::SampleIOProcessor::removeSampleClientForTag (SampleClient * c, const SampleTag *) throw () inline virtual
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
Reimplemented in nidas::dynld::raf::SyncRecordGenerator.
References _source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
void SampleIOProcessor::removeSampleTag (const SampleTag * tag) throw () virtual
Implements nidas::core::SampleSource.
virtual void nidas::core::SampleIOProcessor::setDSMConfig (const DSMConfig * val) inline virtual
References _dsm.
Referenced by nidas::core::DSMConfig::fromDOMElement().
void SampleIOProcessor::setName (const std::string & val) virtual
References _name.
Referenced by nidas::dynld::psql::PSQLProcessor::PSQLProcessor(), nidas::core::SampleArchiver::SampleArchiver(), nidas::dynld::StatisticsProcessor::StatisticsProcessor(), and nidas::dynld::raf::SyncRecordGenerator::SyncRecordGenerator().
virtual void nidas::core::SampleIOProcessor::setOptional (bool val) inline virtual
References _optional.
void nidas::core::SampleIOProcessor::setSampleId (int val) inline
References _id, and SET_SPS_ID.
virtual void nidas::core::SampleIOProcessor::setService (const DSMService * val) inline virtual
References _service.
Referenced by nidas::core::DSMService::fromDOMElement().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
std::list<const Parameter*> nidas::core::SampleIOProcessor::_constParameters private
Referenced by getParameters().
std::list<const SampleTag*> nidas::core::SampleIOProcessor::_constRequestedTags private
Referenced by getRequestedSampleTags(), and removeRequestedSampleTag().
const DSMConfig* nidas::core::SampleIOProcessor::_dsm private
Or, what DSM am I a part of?
Referenced by getDSMConfig(), and setDSMConfig().
dsm_sample_id_t nidas::core::SampleIOProcessor::_id private
Referenced by getId(), getSampleId(), and setSampleId().
std::string nidas::core::SampleIOProcessor::_name private
Referenced by getName(), and setName().
bool nidas::core::SampleIOProcessor::_optional private
Referenced by isOptional(), and setOptional().
std::list<SampleOutput*> nidas::core::SampleIOProcessor::_origOutputs private
Referenced by addOutput(), getOutputs(), and ~SampleIOProcessor().
std::list<Parameter*> nidas::core::SampleIOProcessor::_parameters private
Referenced by ~SampleIOProcessor().
std::list<SampleTag*> nidas::core::SampleIOProcessor::_requestedTags protected
Referenced by removeRequestedSampleTag(), nidas::dynld::StatisticsProcessor::selectRequestedSampleTags(), and ~SampleIOProcessor().
const DSMService* nidas::core::SampleIOProcessor::_service private
What service am I a part of?
Referenced by getService(), and setService().
SampleSourceSupport nidas::core::SampleIOProcessor::_source protected
Referenced by addSampleClient(), addSampleClientForTag(), getClientCount(), getProcessedSampleSource(), getSampleStats(), getSampleTagIterator(), getSampleTags(), removeSampleClient(), and removeSampleClientForTag().
nidas::util::Mutex nidas::core::SampleIOProcessor::_tagsMutex mutable protected
Referenced by getRequestedSampleTags(), removeRequestedSampleTag(), and nidas::dynld::StatisticsProcessor::selectRequestedSampleTags().
The documentation for this class was generated from the following files:
nidas/core/SampleIOProcessor.h
nidas/core/SampleIOProcessor.cc