nidas: nidas::util::Runnable Class Reference
nidas::util::Runnable Class Reference abstract
#include <Thread.h>
Public Member Functions
virtual ~Runnable ()
virtual int run ()=0 throw (Exception)
The method which will run in its own thread.
virtual void interrupt ()=0
Interrupt this run method.
virtual bool isInterrupted () const =0
Has the run method been interrupted?
Protected Member Functions
void testCancel () const
Check if we have been cancelled.
virtual bool amInterrupted () const
Call testCancel, and return true when this thread has been interrupted.
Constructor & Destructor Documentation
virtual nidas::util::Runnable::~Runnable () inline virtual
Member Function Documentation
bool Runnable::amInterrupted () const protected virtual
Call testCancel, and return true when this thread has been interrupted.
This is protected because it should only called within the run method of the thread.
Referenced by nidas::core::SampleOutputRequestThread::run(), nidas::core::Looper::run(), nidas::core::DSMServerStat::run(), nidas::dynld::isff::GOESOutput::run(), and nidas::util::Thread::test().
virtual void nidas::util::Runnable::interrupt () pure virtual
Interrupt this run method.
This sets a flag which can be tested with isInterrupted(). It is up to the run() implementation to return when interrupted.
Implemented in nidas::util::McSocketMulticaster< SocketTT >, nidas::util::ThreadRunnable, nidas::util::McSocketListener, nidas::core::ServerSocket::ConnectionThread, nidas::util::Thread, nidas::core::Socket::ConnectionThread, nidas::dynld::RawSampleService::Worker, nidas::dynld::UDPSampleOutput::XMLSocketListener, nidas::core::SampleSorter, nidas::core::SensorHandler, nidas::core::SampleBuffer, nidas::dynld::isff::GOESOutput, nidas::dynld::UDPSampleOutput::VariableListWorker, nidas::dynld::raf::SyncServer, nidas::core::DerivedDataReader, nidas::core::SensorOpener, nidas::dynld::XMLConfigService::Worker, nidas::core::SampleOutputRequestThread, and nidas::core::XmlRpcThread.
Referenced by nidas::util::ThreadRunnable::interrupt().
virtual bool nidas::util::Runnable::isInterrupted () const pure virtual
Has the run method been interrupted?
Implemented in nidas::util::Thread, and nidas::dynld::isff::GOESOutput.
virtual int nidas::util::Runnable::run () throw (Exception) pure virtual
The method which will run in its own thread.
This method must be supplied by the Runnable or Thread subclass.
Implemented in nidas::util::ThreadJoiner, nidas::util::McSocketMulticaster< SocketTT >, nidas::util::ThreadRunnable, nidas::util::McSocketListener, nidas::core::ServerSocket::ConnectionThread, ServerThread, WriterThread, nidas::core::SampleSorter, nidas::core::SampleBuffer, nidas::core::Socket::ConnectionThread, ModemLineMonitor, ModemLineSetter, nidas::dynld::RawSampleService::Worker, nidas::dynld::UDPSampleOutput::XMLSocketListener, nidas::core::FsMountWorkerThread, nidas::core::SensorHandler, nidas::dynld::UDPSampleOutput::ConnectionMonitor, nidas::dynld::isff::GOESOutput, nidas::dynld::UDPSampleOutput::VariableListWorker, TestSource, PSI, Sender, nidas::dynld::raf::SyncServer, nidas::core::DSMServerStat, nidas::core::Looper, nidas::core::SensorOpener, nidas::dynld::XMLConfigService::Worker, nidas::core::DSMEngineStat, nidas::core::DSMServerIntf, nidas::core::DerivedDataReader, DataWriter, nidas::core::SampleOutputRequestThread, nidas::core::StatusListener, and nidas::core::DSMEngineIntf.
Referenced by nidas::util::Thread::pRun(), nidas::util::ThreadRunnable::run(), and nidas::util::Thread::test().
void nidas::util::Runnable::testCancel () const inline protected
Check if we have been cancelled.
Calls pthread_testcancel. This is protected since it only checks the current thread - i.e. it must be called within the run method. Since it just calls pthread_testcancel, it is a cancellation point.
The documentation for this class was generated from the following files:
nidas/util/Thread.h
nidas/util/Thread.cc