nidas: nidas::util::DatagramPacket Class Reference
nidas::util::DatagramPacket Class Reference
#include <DatagramPacket.h>
Public Member Functions
DatagramPacket (char *buf, int length)
DatagramPacket (char *buf, int length, const Inet4Address &add, int port)
Create a DatagramPacket for sending.
DatagramPacket (char *buf, int length, const SocketAddress &add)
virtual void * getDataVoidPtr ()
Get the pointer to the data portion of the packet.
virtual const void * getConstDataVoidPtr () const
char * getData ()
void setData (char *val)
Set the pointer to the data portion of the packet.
SocketAddress & getSocketAddress () const
void setSocketAddress (const SocketAddress &val)
struct sockaddr * getSockAddrPtr ()
struct sockaddr * getConstSockAddrPtr () const
int getSockAddrLen () const
virtual void setLength (int val)
Set the value for the current number of bytes in data.
virtual int getLength () const
Get the value for the current number of bytes in data.
void setMaxLength (int val)
Set the allocated length in bytes of the data.
int getMaxLength () const
Return the allocated length in bytes of the data.
Protected Attributes
char * data
int maxlength
allocated length in bytes of contents.
int length
length of datagram that was read or will be sent.
SocketAddress * addr
The destination address for a send, or the remote senders address after a receive.
Constructor & Destructor Documentation
nidas::util::DatagramPacket::DatagramPacket (char * buf, int length) inline
nidas::util::DatagramPacket::DatagramPacket (char * buf, int length, const Inet4Address & add, int port) inline
Create a DatagramPacket for sending.
Parameters
buf allocated space for contents. Pointer is owned by caller, not by the DatagramPacket - the DatagramPacket destructor does not delete it in its destructor.
length length of allocated space. Inet4Address to send packet to. port number to send packet to.
nidas::util::DatagramPacket::DatagramPacket (char * buf, int length, const SocketAddress & add) inline
Member Function Documentation
virtual const void* nidas::util::DatagramPacketT< char >::getConstDataVoidPtr () const inline virtual inherited
Implements nidas::util::DatagramPacketBase.
References nidas::util::DatagramPacketT< DataT >::data.
struct sockaddr* nidas::util::DatagramPacketBase::getConstSockAddrPtr () const inline inherited
References nidas::util::DatagramPacketBase::addr, and nidas::util::SocketAddress::getConstSockAddrPtr().
char * nidas::util::DatagramPacketT< char >::getData () inline inherited
References nidas::util::DatagramPacketT< DataT >::data.
virtual void* nidas::util::DatagramPacketT< char >::getDataVoidPtr () inline virtual inherited
Get the pointer to the data portion of the packet.
Implements nidas::util::DatagramPacketBase.
References nidas::util::DatagramPacketT< DataT >::data.
virtual int nidas::util::DatagramPacketBase::getLength () const inline virtual inherited
Get the value for the current number of bytes in data.
Either the number of bytes read in a received packet, or the number of bytes to send().
References nidas::util::DatagramPacketBase::length.
Referenced by PacketReader::checkPacket(), PacketReader::logBadPacket(), PacketReader::loop(), nidas::core::DerivedDataReader::run(), WriterThread::run(), and nidas::util::McSocketMulticaster< SocketTT >::run().
int nidas::util::DatagramPacketBase::getMaxLength () const inline inherited
Return the allocated length in bytes of the data.
References nidas::util::DatagramPacketBase::maxlength.
int nidas::util::DatagramPacketBase::getSockAddrLen () const inline inherited
References nidas::util::DatagramPacketBase::addr, and nidas::util::SocketAddress::getSockAddrLen().
struct sockaddr* nidas::util::DatagramPacketBase::getSockAddrPtr () inline inherited
References nidas::util::DatagramPacketBase::addr, and nidas::util::SocketAddress::getSockAddrPtr().
SocketAddress& nidas::util::DatagramPacketBase::getSocketAddress () const inline inherited
References nidas::util::DatagramPacketBase::addr.
Referenced by PacketReader::logBadPacket(), PacketReader::loop(), and nidas::util::McSocketMulticaster< SocketTT >::run().
void nidas::util::DatagramPacketT< char >::setData (char * val) inline inherited
Set the pointer to the data portion of the packet.
/param val Pointer to an allocated section of memory. This pointer is owned by the caller, it is not deleted by the DatagramPacket destructor.
References nidas::util::DatagramPacketT< DataT >::data.
virtual void nidas::util::DatagramPacketBase::setLength (int val) inline virtual inherited
Set the value for the current number of bytes in data.
/param val Number of bytes, must be <= max length.
References nidas::util::DatagramPacketBase::length.
Referenced by PacketReader::checkPacket().
void nidas::util::DatagramPacketBase::setMaxLength (int val) inline inherited
Set the allocated length in bytes of the data.
/param val Number of bytes allocated in data.
References nidas::util::DatagramPacketBase::maxlength.
void nidas::util::DatagramPacketBase::setSocketAddress (const SocketAddress & val) inline inherited
References nidas::util::DatagramPacketBase::addr, and nidas::util::SocketAddress::clone().
Referenced by nidas::util::McSocketMulticaster< SocketTT >::run().
Member Data Documentation
SocketAddress* nidas::util::DatagramPacketBase::addr protected inherited
The destination address for a send, or the remote senders address after a receive.
Referenced by nidas::util::DatagramPacketBase::getConstSockAddrPtr(), nidas::util::DatagramPacketBase::getSockAddrLen(), nidas::util::DatagramPacketBase::getSockAddrPtr(), nidas::util::DatagramPacketBase::getSocketAddress(), nidas::util::DatagramPacketBase::operator=(), nidas::util::DatagramPacketBase::setSocketAddress(), and nidas::util::DatagramPacketBase::~DatagramPacketBase().
char * nidas::util::DatagramPacketT< char >::data protected inherited
int nidas::util::DatagramPacketBase::length protected inherited
length of datagram that was read or will be sent.
Must be <= maxlength.
Referenced by nidas::util::DatagramPacketBase::getLength(), nidas::util::DatagramPacketBase::operator=(), and nidas::util::DatagramPacketBase::setLength().
int nidas::util::DatagramPacketBase::maxlength protected inherited
allocated length in bytes of contents.
Referenced by nidas::util::DatagramPacketBase::getMaxLength(), nidas::util::DatagramPacketBase::operator=(), and nidas::util::DatagramPacketBase::setMaxLength().
The documentation for this class was generated from the following file:
nidas/util/DatagramPacket.h