nidas: nidas::core::ParameterT< T > Class Template Reference
nidas::core::ParameterT< T > Class Template Reference
A typed Parameter, with data of type T.
#include <Parameter.h>
Public Types
enum parType { STRING_PARAM, FLOAT_PARAM, INT_PARAM, BOOL_PARAM }
typedef enum parType parType
Public Member Functions
ParameterT ()
ParameterT * clone () const
void assign (const Parameter &x)
A virtual assignment operator.
int getLength () const
const std::vector< T > getValues () const
void setValues (const std::vector< T > &vals)
void setValue (unsigned int i, const T &val)
Set ith value.
void setValue (const T &val)
For parameters of length one, set its value.
T getValue (int i) const
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
void fromDOMElement (const xercesc::DOMElement *, const Dictionary *dict) throw (nidas::util::InvalidParameterException)
const std::string & getName () const
void setName (const std::string &val)
parType getType () const
virtual double getNumericValue (int i) const
virtual std::string getStringValue (int i) const
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static Parameter * createParameter (const xercesc::DOMElement *, const Dictionary *d=0) throw (nidas::util::InvalidParameterException)
static const XMLCh * getNamespaceURI ()
Protected Attributes
std::vector< T > _values
Vector of values.
std::string _name
parType _type
Detailed Description
template<class T>
class nidas::core::ParameterT< T >
A typed Parameter, with data of type T.
Member Typedef Documentation
typedef enum parType nidas::core::Parameter::parType inherited
Member Enumeration Documentation
enum nidas::core::Parameter::parType inherited
Enumerator
STRING_PARAM
FLOAT_PARAM
INT_PARAM
BOOL_PARAM
Constructor & Destructor Documentation
template<class T> nidas::core::ParameterT< T >::ParameterT () inline
Member Function Documentation
template<class T > void ParameterT::assign (const Parameter & x) virtual
A virtual assignment operator.
Implements nidas::core::Parameter.
References nidas::core::ParameterT< T >::_values, nidas::core::Parameter::getName(), and nidas::core::Parameter::getType().
template<class T > ParameterT< T > * ParameterT::clone () const virtual
Implements nidas::core::Parameter.
Parameter * Parameter::createParameter (const xercesc::DOMElement * node, const Dictionary * d = 0) throw (nidas::util::InvalidParameterException) static inherited
References nidas::core::Parameter::fromDOMElement(), nidas::core::Parameter::getLength(), and nidas::core::XDOMAttr::getName().
Referenced by nidas::core::VariableConverter::fromDOMElement(), nidas::core::Project::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::Site::fromDOMElement(), nidas::core::SampleTag::fromDOMElement(), nidas::core::Variable::fromDOMElement(), and nidas::core::DSMSensor::fromDOMElement().
template<class T > void ParameterT::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
template<class T > void ParameterT::fromDOMElement (const xercesc::DOMElement * node, const Dictionary * dict) throw (nidas::util::InvalidParameterException) virtual
Implements nidas::core::Parameter.
References nidas::core::XDOMElement::getAttributeValue(), nidas::core::XDOMAttr::getName(), nidas::core::ParameterT< T >::setValue(), and T().
template<class T> int nidas::core::ParameterT< T >::getLength () const inline virtual
Implements nidas::core::Parameter.
References nidas::core::ParameterT< T >::_values.
Referenced by nidas::dynld::isff::PacketInputStream::getGOESProject(), and nidas::dynld::isff::GOESProject::GOESProject().
const std::string& nidas::core::Parameter::getName () const inline inherited
References nidas::core::Parameter::_name.
Referenced by nidas::core::VariableConverter::addParameter(), nidas::core::Site::addParameter(), nidas::core::SampleOutputBase::addParameter(), nidas::core::SampleTag::addParameter(), nidas::core::DSMSensor::addParameter(), nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::A2DSensor::addSampleTag(), nidas::core::ParameterT< T >::assign(), nidas::dynld::A2DSensor::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::Project::getParameter(), nidas::core::SampleTag::getParameter(), nidas::core::ParameterNameTypeComparator::operator()(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSI_IRGA_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::SonicAnemometer::parseParameters(), nidas::dynld::ParoSci_202BG_P::readParams(), nidas::dynld::ParoSci_202BG_T::readParams(), nidas::dynld::DSC_FreqCounter::readParams(), and nidas::dynld::IEEE_Float::validate().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
double Parameter::getNumericValue (int i) const virtual inherited
References nidas::core::floatNAN.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::A2DSensor::addSampleTag(), nidas::dynld::isff::GOESOutput::addSourceSampleTag(), nidas::dynld::isff::WisardMote::createSampleTags(), nidas::dynld::raf::LamsSensor::fromDOMElement(), nidas::dynld::Twins::fromDOMElement(), nidas::dynld::A2DSensor::fromDOMElement(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::dynld::isff::CS_Krypton::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::TwoD_USB::init_parameters(), nidas::dynld::isff::MOSMote::open(), nidas::dynld::raf::UHSAS_Serial::open(), parseAnalog(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSI_IRGA_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::SonicAnemometer::parseParameters(), nidas::dynld::ParoSci_202BG_P::readParams(), nidas::dynld::ParoSci_202BG_T::readParams(), nidas::dynld::DSC_FreqCounter::readParams(), Extract2D::run(), AutoCalClient::Setup(), nidas::dynld::raf::CDP_Serial::validate(), nidas::dynld::raf::SPP300_Serial::validate(), nidas::dynld::raf::SPP100_Serial::validate(), nidas::dynld::raf::SPP200_Serial::validate(), nidas::dynld::raf::SppSerial::validate(), and nidas::dynld::isff::WisardMote::validate().
std::string Parameter::getStringValue (int i) const virtual inherited
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::A2DSensor::addSampleTag(), nidas::dynld::isff::PropVane::fromDOMElement(), nidas::dynld::raf::CVIProcessor::fromDOMElement(), PMSSensorItem::getSerialNumberString(), nidas::dynld::raf::Aircraft::getTailNumber(), nidas::dynld::WxtSensor::init(), nidas::dynld::raf::DSMAnalogSensor::open(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::SonicAnemometer::parseParameters(), Extract2D::run(), nidas::dynld::raf::DSMMesaSensor::sendFPGACodeToDriver(), sensorTitle(), and nidas::dynld::IEEE_Float::validate().
parType nidas::core::Parameter::getType () const inline inherited
References nidas::core::Parameter::_type.
Referenced by nidas::dynld::StatisticsProcessor::addRequestedSampleTag(), nidas::dynld::isff::GOESOutput::addRequestedSampleTag(), nidas::dynld::A2DSensor::addSampleTag(), nidas::core::ParameterT< T >::assign(), nidas::dynld::isff::WisardMote::createSampleTags(), nidas::dynld::UDPSampleOutput::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::isff::PacketInputStream::getGOESProject(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::dynld::isff::MOSMote::open(), nidas::dynld::raf::DSMAnalogSensor::open(), nidas::core::ParameterNameTypeComparator::operator()(), nidas::dynld::isff::ATIK_Sonic::parseParameters(), nidas::dynld::isff::CSI_IRGA_Sonic::parseParameters(), nidas::dynld::isff::CSAT3_Sonic::parseParameters(), nidas::dynld::isff::SonicAnemometer::parseParameters(), nidas::dynld::ParoSci_202BG_P::readParams(), nidas::dynld::ParoSci_202BG_T::readParams(), nidas::dynld::DSC_FreqCounter::readParams(), nidas::dynld::raf::DSMMesaSensor::sendFPGACodeToDriver(), nidas::dynld::IEEE_Float::validate(), and nidas::dynld::isff::WisardMote::validate().
template<class T> T nidas::core::ParameterT< T >::getValue (int i) const inline
References nidas::core::ParameterT< T >::_values.
Referenced by nidas::dynld::isff::PacketInputStream::getGOESProject(), and nidas::dynld::isff::GOESProject::GOESProject().
template<class T> const std::vector<T> nidas::core::ParameterT< T >::getValues () const inline
References nidas::core::ParameterT< T >::_values.
void nidas::core::Parameter::setName (const std::string & val) inline inherited
References nidas::core::Parameter::_name.
Referenced by main(), and nidas::dynld::raf::Aircraft::setTailNumber().
template<class T> void nidas::core::ParameterT< T >::setValue (unsigned int i, const T & val) inline
Set ith value.
References nidas::core::ParameterT< T >::_values, and T().
Referenced by nidas::core::ParameterT< T >::fromDOMElement(), main(), and nidas::dynld::raf::Aircraft::setTailNumber().
template<class T> void nidas::core::ParameterT< T >::setValue (const T & val) inline
For parameters of length one, set its value.
References nidas::core::ParameterT< T >::_values.
template<class T> void nidas::core::ParameterT< T >::setValues (const std::vector< T > & vals) inline
References nidas::core::ParameterT< T >::_values.
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
std::string nidas::core::Parameter::_name protected inherited
Referenced by nidas::core::Parameter::getName(), and nidas::core::Parameter::setName().
parType nidas::core::Parameter::_type protected inherited
Referenced by nidas::core::Parameter::getType().
template<class T> std::vector<T> nidas::core::ParameterT< T >::_values protected
Vector of values.
Referenced by nidas::core::ParameterT< T >::assign(), nidas::core::ParameterT< T >::getLength(), nidas::core::ParameterT< T >::getValue(), nidas::core::ParameterT< T >::getValues(), nidas::core::ParameterT< T >::setValue(), and nidas::core::ParameterT< T >::setValues().
The documentation for this class was generated from the following files:
nidas/core/Parameter.h
nidas/core/Parameter.cc