nidas: ConfigWindow Class Reference
ConfigWindow Class Reference
#include <configwindow.h>
Public Slots
void newFile ()
void openFile ()
void newProj ()
void saveOldFile ()
bool saveFile (std::string origFile)
bool saveAsFile ()
void editProjName ()
void toggleErrorsWindow (bool)
void addSensorCombo ()
void editSensorCombo ()
void deleteSensor ()
void addDSMCombo ()
void editDSMCombo ()
void deleteDSM ()
void editA2DVariableCombo ()
void addA2DVariableCombo ()
void editVariableCombo ()
void deleteA2DVariable ()
void quit ()
void changeToIndex (const QModelIndex &)
Display and setup the correct actions for the current index.
void changeToIndex (const QItemSelection &)
Display and setup the correct actions for the index in selections.
void setFilename (QString filename)
void writeProjectName (QString projName)
Public Member Functions
ConfigWindow ()
~ConfigWindow ()
NidasModel * getModel () const
QTableView * getTableView () const
void show ()
virtual void closeEvent (QCloseEvent *event)
Private Member Functions
void buildMenus ()
void buildFileMenu ()
void buildWindowMenu ()
void buildAddMenu ()
void buildSensorCatalog ()
void buildA2DVarDB ()
void buildSensorMenu ()
void buildSensorActions ()
void buildDSMMenu ()
void buildDSMActions ()
void buildVariableMenu ()
void buildVariableActions ()
void buildA2DVariableMenu ()
void buildA2DVariableActions ()
void buildProjectMenu ()
void getFile ()
void setupDefaultDir ()
bool fileExists (QString filename)
bool saveFileCopy (std::string origFile)
bool askSaveFileAndContinue ()
void setupModelView (QSplitter *splitter)
Private Attributes
UserFriendlyExceptionHandler * exceptionHandler
AddSensorComboDialog * sensorComboDialog
AddDSMComboDialog * dsmComboDialog
AddA2DVariableComboDialog * a2dVariableComboDialog
VariableComboDialog * variableComboDialog
NewProjectDialog * newProjDialog
QMessageBox * _errorMessage
Document * _doc
bool doCalibrations
std::string _defaultDir
bool _noProjDir
QString _projDir
QString _defaultCaption
const QString _gvDefault
const QString _c130Default
const QString _a2dCalDir
const QString _engCalDirRoot
const QString _pmsSpecsFile
QString _filename
bool _fileOpen
NidasModel * model
QTreeView * treeview
QTableView * tableview
QSplitter * mainSplitter
QMenu * sensorMenu
QAction * addSensorAction
QAction * editSensorAction
QAction * deleteSensorAction
QMenu * dsmMenu
QAction * addDSMAction
QAction * editDSMAction
QAction * deleteDSMAction
QMenu * sampleMenu
QMenu * variableMenu
QAction * editVariableAction
QMenu * a2dVariableMenu
QAction * editA2DVariableAction
QAction * addA2DVariableAction
QAction * deleteA2DVariableAction
Constructor & Destructor Documentation
ConfigWindow::ConfigWindow ()
References _a2dCalDir, _errorMessage, _pmsSpecsFile, _projDir, a2dVariableComboDialog, buildMenus(), dsmComboDialog, exceptionHandler, newProjDialog, sensorComboDialog, setupDefaultDir(), variableComboDialog, and nidas::util::Exception::what().
ConfigWindow::~ConfigWindow () inline
Member Function Documentation
void ConfigWindow::addA2DVariableCombo () slot
References a2dVariableComboDialog, model, config::AddA2DVariableComboDialog::show(), and tableview.
Referenced by buildA2DVariableActions().
void ConfigWindow::addDSMCombo () slot
References dsmComboDialog, model, config::AddDSMComboDialog::show(), and tableview.
Referenced by buildDSMActions().
void ConfigWindow::addSensorCombo () slot
References model, sensorComboDialog, config::AddSensorComboDialog::show(), and tableview.
Referenced by buildSensorActions().
bool ConfigWindow::askSaveFileAndContinue () private
References _doc, Document::getFilename(), Document::isChanged(), Document::isChangedBig(), saveAsFile(), and saveFile().
Referenced by newFile(), and quit().
void ConfigWindow::buildA2DVarDB () private
void ConfigWindow::buildA2DVariableActions () private
References addA2DVariableAction, addA2DVariableCombo(), deleteA2DVariable(), deleteA2DVariableAction, editA2DVariableAction, and editA2DVariableCombo().
Referenced by buildA2DVariableMenu().
void ConfigWindow::buildA2DVariableMenu () private
References a2dVariableMenu, addA2DVariableAction, buildA2DVariableActions(), deleteA2DVariableAction, and editA2DVariableAction.
Referenced by buildMenus().
void ConfigWindow::buildAddMenu () private
void ConfigWindow::buildDSMActions () private
References addDSMAction, addDSMCombo(), deleteDSM(), deleteDSMAction, editDSMAction, and editDSMCombo().
Referenced by buildDSMMenu().
void ConfigWindow::buildDSMMenu () private
References addDSMAction, buildDSMActions(), deleteDSMAction, dsmMenu, and editDSMAction.
Referenced by buildMenus().
void ConfigWindow::buildFileMenu () private
References newFile(), newProj(), quit(), saveAsFile(), and saveOldFile().
Referenced by buildMenus().
void ConfigWindow::buildMenus () private
References buildA2DVariableMenu(), buildDSMMenu(), buildFileMenu(), buildProjectMenu(), buildSensorMenu(), buildVariableMenu(), and buildWindowMenu().
Referenced by ConfigWindow().
void ConfigWindow::buildProjectMenu () private
References editProjName().
Referenced by buildMenus().
void ConfigWindow::buildSensorActions () private
References addSensorAction, addSensorCombo(), deleteSensor(), deleteSensorAction, editSensorAction, and editSensorCombo().
Referenced by buildSensorMenu().
void ConfigWindow::buildSensorCatalog () private
References _doc, config::AddSensorComboDialog::addSensorDev(), config::AddSensorComboDialog::addSensorSfx(), config::AddSensorComboDialog::clearDevMap(), config::AddSensorComboDialog::clearSfxMap(), nidas::core::XDOMElement::getAttributeValue(), nidas::core::SensorCatalog::getMap(), nidas::core::Project::getSensorCatalog(), sensorComboDialog, and config::AddSensorComboDialog::setDocument().
Referenced by openFile().
void ConfigWindow::buildSensorMenu () private
References addSensorAction, buildSensorActions(), deleteSensorAction, editSensorAction, and sensorMenu.
Referenced by buildMenus().
void ConfigWindow::buildVariableActions () private
References editVariableAction, and editVariableCombo().
Referenced by buildVariableMenu().
void ConfigWindow::buildVariableMenu () private
References buildVariableActions(), editVariableAction, and variableMenu.
Referenced by buildMenus().
void ConfigWindow::buildWindowMenu () private
References toggleErrorsWindow().
Referenced by buildMenus().
void ConfigWindow::changeToIndex (const QModelIndex & index) slot
Display and setup the correct actions for the current index.
Set the table view's root index to the parent of index and tell the model same so it returns correct headerData. En/dis-able appropriate actions, e.g. add or delete choices...
References a2dVariableMenu, dsmMenu, NidasModel::getItem(), model, sensorMenu, NidasModel::setCurrentRootIndex(), tableview, and variableMenu.
Referenced by changeToIndex(), and setupModelView().
void ConfigWindow::changeToIndex (const QItemSelection & selections) slot
Display and setup the correct actions for the index in selections.
This version is for selectionModel's selectionChanged signal. We use only the first element of selections, expecting that the view(s) allow only one selection at a time.
References changeToIndex(), and tableview.
virtual void ConfigWindow::closeEvent (QCloseEvent * event) inline virtual
void ConfigWindow::deleteA2DVariable () slot
References _doc, model, NidasModel::removeIndexes(), Document::setIsChangedBig(), and tableview.
Referenced by buildA2DVariableActions().
void ConfigWindow::deleteDSM () slot
References _doc, model, NidasModel::removeIndexes(), Document::setIsChangedBig(), and tableview.
Referenced by buildDSMActions().
void ConfigWindow::deleteSensor () slot
References _doc, model, NidasModel::removeIndexes(), Document::setIsChangedBig(), and tableview.
Referenced by buildSensorActions().
void ConfigWindow::editA2DVariableCombo () slot
References a2dVariableComboDialog, model, config::AddA2DVariableComboDialog::show(), and tableview.
Referenced by buildA2DVariableActions().
void ConfigWindow::editDSMCombo () slot
References dsmComboDialog, model, config::AddDSMComboDialog::show(), and tableview.
Referenced by buildDSMActions().
void ConfigWindow::editProjName () slot
References _doc, Document::getProjectName(), and writeProjectName().
Referenced by buildProjectMenu().
void ConfigWindow::editSensorCombo () slot
References model, sensorComboDialog, config::AddSensorComboDialog::show(), and tableview.
Referenced by buildSensorActions().
void ConfigWindow::editVariableCombo () slot
References model, config::VariableComboDialog::show(), tableview, and variableComboDialog.
Referenced by buildVariableActions().
bool ConfigWindow::fileExists (QString filename) private
References buffer.
void ConfigWindow::getFile () private
References _defaultCaption, _defaultDir, and _filename.
Referenced by newFile().
NidasModel* ConfigWindow::getModel () const inline
QTableView* ConfigWindow::getTableView () const inline
void ConfigWindow::newFile () slot
References _fileOpen, askSaveFileAndContinue(), getFile(), and openFile().
Referenced by buildFileMenu().
void ConfigWindow::newProj () slot
References _errorMessage, _filename, newProjDialog, and config::NewProjectDialog::show().
Referenced by buildFileMenu().
void ConfigWindow::openFile () slot
References _doc, _engCalDirRoot, _errorMessage, _filename, _fileOpen, _projDir, a2dVariableComboDialog, buildSensorCatalog(), dsmComboDialog, Document::engCalDirExists(), exceptionHandler, Document::getEngCalDir(), Document::getSiteNames(), UserFriendlyExceptionHandler::handle(), mainSplitter, Document::parseFile(), Document::printSiteNames(), config::AddDSMComboDialog::setDocument(), config::VariableComboDialog::setDocument(), config::AddA2DVariableComboDialog::setDocument(), Document::setFilename(), config::AddA2DVariableComboDialog::setup(), setupModelView(), show(), tableview, nidas::util::Exception::toString(), variableComboDialog, and nidas::util::Exception::what().
Referenced by config::NewProjectDialog::accept(), and newFile().
void ConfigWindow::quit () slot
References _fileOpen, and askSaveFileAndContinue().
Referenced by buildFileMenu().
bool ConfigWindow::saveAsFile () slot
References _doc, _errorMessage, _filename, Document::getDirectory(), Document::getFilename(), saveFile(), and Document::setFilename().
Referenced by askSaveFileAndContinue(), and buildFileMenu().
bool ConfigWindow::saveFile (std::string origFile) slot
References _c130Default, _doc, _errorMessage, _filename, _gvDefault, _projDir, Document::getFilename(), Document::getMissingEngCalFiles(), saveFileCopy(), Document::setIsChanged(), Document::setIsChangedBig(), and Document::writeDocument().
Referenced by askSaveFileAndContinue(), saveAsFile(), and saveOldFile().
bool ConfigWindow::saveFileCopy (std::string origFile) private
References _doc, and Document::getFilename().
Referenced by saveFile().
void ConfigWindow::saveOldFile () slot
References saveFile().
Referenced by buildFileMenu().
void ConfigWindow::setFilename (QString filename) inline slot
Referenced by config::NewProjectDialog::accept().
void ConfigWindow::setupDefaultDir () private
References _defaultCaption, _defaultDir, _errorMessage, _noProjDir, and _projDir.
Referenced by ConfigWindow().
void ConfigWindow::setupModelView (QSplitter * splitter) private
References _doc, changeToIndex(), Document::getDomDocument(), model, tableview, and treeview.
Referenced by openFile().
void ConfigWindow::show ()
Referenced by main(), and openFile().
void ConfigWindow::toggleErrorsWindow (bool checked) slot
References exceptionHandler, and UserFriendlyExceptionHandler::setVisible().
Referenced by buildWindowMenu().
void ConfigWindow::writeProjectName (QString projName) slot
References _doc, _errorMessage, Document::getDirectory(), and Document::setProjectName().
Referenced by config::NewProjectDialog::accept(), and editProjName().
Member Data Documentation
const QString ConfigWindow::_a2dCalDir private
Referenced by ConfigWindow().
const QString ConfigWindow::_c130Default private
Referenced by saveFile().
QString ConfigWindow::_defaultCaption private
Referenced by getFile(), and setupDefaultDir().
std::string ConfigWindow::_defaultDir private
Referenced by getFile(), and setupDefaultDir().
Document* ConfigWindow::_doc private
Referenced by askSaveFileAndContinue(), buildSensorCatalog(), deleteA2DVariable(), deleteDSM(), deleteSensor(), editProjName(), openFile(), saveAsFile(), saveFile(), saveFileCopy(), setupModelView(), and writeProjectName().
const QString ConfigWindow::_engCalDirRoot private
Referenced by openFile().
QMessageBox* ConfigWindow::_errorMessage private
Referenced by ConfigWindow(), newProj(), openFile(), saveAsFile(), saveFile(), setupDefaultDir(), and writeProjectName().
QString ConfigWindow::_filename private
Referenced by getFile(), newProj(), openFile(), saveAsFile(), and saveFile().
bool ConfigWindow::_fileOpen private
Referenced by newFile(), openFile(), and quit().
const QString ConfigWindow::_gvDefault private
Referenced by saveFile().
bool ConfigWindow::_noProjDir private
Referenced by setupDefaultDir().
const QString ConfigWindow::_pmsSpecsFile private
Referenced by ConfigWindow().
QString ConfigWindow::_projDir private
Referenced by ConfigWindow(), openFile(), saveFile(), and setupDefaultDir().
AddA2DVariableComboDialog* ConfigWindow::a2dVariableComboDialog private
Referenced by addA2DVariableCombo(), ConfigWindow(), editA2DVariableCombo(), and openFile().
QMenu* ConfigWindow::a2dVariableMenu private
Referenced by buildA2DVariableMenu(), and changeToIndex().
QAction* ConfigWindow::addA2DVariableAction private
Referenced by buildA2DVariableActions(), and buildA2DVariableMenu().
QAction* ConfigWindow::addDSMAction private
Referenced by buildDSMActions(), and buildDSMMenu().
QAction* ConfigWindow::addSensorAction private
Referenced by buildSensorActions(), and buildSensorMenu().
QAction* ConfigWindow::deleteA2DVariableAction private
Referenced by buildA2DVariableActions(), and buildA2DVariableMenu().
QAction* ConfigWindow::deleteDSMAction private
Referenced by buildDSMActions(), and buildDSMMenu().
QAction* ConfigWindow::deleteSensorAction private
Referenced by buildSensorActions(), and buildSensorMenu().
bool ConfigWindow::doCalibrations private
AddDSMComboDialog* ConfigWindow::dsmComboDialog private
Referenced by addDSMCombo(), ConfigWindow(), editDSMCombo(), and openFile().
QMenu* ConfigWindow::dsmMenu private
Referenced by buildDSMMenu(), and changeToIndex().
QAction* ConfigWindow::editA2DVariableAction private
Referenced by buildA2DVariableActions(), and buildA2DVariableMenu().
QAction* ConfigWindow::editDSMAction private
Referenced by buildDSMActions(), and buildDSMMenu().
QAction* ConfigWindow::editSensorAction private
Referenced by buildSensorActions(), and buildSensorMenu().
QAction* ConfigWindow::editVariableAction private
Referenced by buildVariableActions(), and buildVariableMenu().
UserFriendlyExceptionHandler* ConfigWindow::exceptionHandler private
Referenced by ConfigWindow(), openFile(), and toggleErrorsWindow().
QSplitter* ConfigWindow::mainSplitter private
Referenced by openFile().
NidasModel* ConfigWindow::model private
Referenced by addA2DVariableCombo(), addDSMCombo(), addSensorCombo(), changeToIndex(), deleteA2DVariable(), deleteDSM(), deleteSensor(), editA2DVariableCombo(), editDSMCombo(), editSensorCombo(), editVariableCombo(), and setupModelView().
NewProjectDialog* ConfigWindow::newProjDialog private
Referenced by ConfigWindow(), and newProj().
QMenu* ConfigWindow::sampleMenu private
AddSensorComboDialog* ConfigWindow::sensorComboDialog private
Referenced by addSensorCombo(), buildSensorCatalog(), ConfigWindow(), and editSensorCombo().
QMenu* ConfigWindow::sensorMenu private
Referenced by buildSensorMenu(), and changeToIndex().
QTableView* ConfigWindow::tableview private
Referenced by addA2DVariableCombo(), addDSMCombo(), addSensorCombo(), changeToIndex(), deleteA2DVariable(), deleteDSM(), deleteSensor(), editA2DVariableCombo(), editDSMCombo(), editSensorCombo(), editVariableCombo(), openFile(), and setupModelView().
QTreeView* ConfigWindow::treeview private
Referenced by setupModelView().
VariableComboDialog* ConfigWindow::variableComboDialog private
Referenced by ConfigWindow(), editVariableCombo(), and openFile().
QMenu* ConfigWindow::variableMenu private
Referenced by buildVariableMenu(), and changeToIndex().
The documentation for this class was generated from the following files:
nidas/apps/config/configwindow.h
nidas/apps/config/configwindow.cc