nidas: Calibrator Class Reference
Calibrator Class Reference
Thread to collect data from dsm_server via AutoCalClient for both auto cal and diagnostic modes.
#include <Calibrator.h>
Public Slots
void cancel ()
Signals
void setValue (int progress)
Public Member Functions
Calibrator (AutoCalClient *acc)
~Calibrator ()
void setTestVoltage ()
bool setup (QString host) throw ()
void run ()
Private Attributes
bool testVoltage
bool canceled
AutoCalClient * _acc
RawSampleInputStream * _sis
SamplePipeline * _pipeline
map< dsm_sample_id_t, string > dsmLocations
Detailed Description
Thread to collect data from dsm_server via AutoCalClient for both auto cal and diagnostic modes.
Constructor & Destructor Documentation
Calibrator::Calibrator (AutoCalClient * acc)
Calibrator::~Calibrator ()
References _acc, _pipeline, _sis, cancel(), nidas::core::SamplePipeline::getProcessedSampleSource(), and nidas::core::SampleSource::removeSampleClient().
Member Function Documentation
void Calibrator::cancel () slot
References canceled.
Referenced by CalibrationWizard::accept(), CalibrationWizard::closeEvent(), and ~Calibrator().
void Calibrator::run ()
References _acc, _pipeline, _sis, nidas::core::SampleSource::addSampleClient(), canceled, nidas::dynld::SampleInputStream::close(), nidas::core::SamplePipeline::connect(), DEAD, nidas::core::SamplePipeline::disconnect(), AutoCalClient::DisplayResults(), DONE, GATHER, AutoCalClient::Gathered(), nidas::core::SamplePipeline::getProcessedSampleSource(), AutoCalClient::progress, nidas::dynld::SampleInputStream::readSamples(), nidas::core::SampleSource::removeSampleClient(), AutoCalClient::SetNextCalVoltage(), nidas::core::SamplePipeline::setProcSorterLength(), nidas::core::SamplePipeline::setRealTime(), setValue(), stateEnumDesc, testVoltage, and nidas::util::Exception::what().
void Calibrator::setTestVoltage () inline
Referenced by TestA2DPage::initializePage().
bool Calibrator::setup (QString host) throw ()
References nidas::core::FileSet::connect(), nidas::util::Inet4Address::getByName(), nidas::core::DSMSensor::getClassName(), nidas::core::DSMSensor::getDSMId(), nidas::core::FileSet::getFileSet(), nidas::core::DSMConfig::getId(), nidas::core::DSMConfig::getLocation(), nidas::core::DSMSensor::getRawSampleTag(), nidas::core::DSMSensor::getSensorId(), nidas::core::DSMConfig::getSensors(), nidas::core::DSMConfigIterator::hasNext(), nidas::core::DSMSensor::init(), nidas::core::DSMConfigIterator::next(), NIDAS_SVC_REQUEST_PORT_UDP, nidas::core::DSMSensor::removeCalFiles(), nidas::core::requestXMLConfig(), and nidas::util::Exception::what().
Referenced by AutoCalPage::initializePage(), and TestA2DPage::initializePage().
void Calibrator::setValue (int progress) signal
Referenced by run().
Member Data Documentation
AutoCalClient* Calibrator::_acc private
Referenced by run(), and ~Calibrator().
SamplePipeline* Calibrator::_pipeline private
Referenced by run(), and ~Calibrator().
RawSampleInputStream* Calibrator::_sis private
Referenced by run(), and ~Calibrator().
bool Calibrator::canceled private
Referenced by cancel(), and run().
map<dsm_sample_id_t, string> Calibrator::dsmLocations private
bool Calibrator::testVoltage private
Referenced by run().
The documentation for this class was generated from the following files:
nidas/apps/auto_cal/Calibrator.h
nidas/apps/auto_cal/Calibrator.cc