nidas: nidas::core::NidasAppInputFilesArg Class Reference
nidas::core::NidasAppInputFilesArg Class Reference
Extend NidasAppArg so the default input specifier and port can be customized, which in turn updates the usage string.
#include <NidasApp.h>
Public Member Functions
void setDefaultInput (const std::string &spec, int default_port_=0)
void setDeprecatedFlag (const std::string &flag)
Provide an alternative but deprecated flag for the argument.
void acceptShortFlag (bool enable)
Set whether short flags are enabled or not.
operator nidas_app_arglist_t ()
Provide conversion to an arglist so a single NidasAppArg can be passed where an arglist is expected.
std::string usage ()
Return the usage string for this particular argument.
Public Attributes
bool allowFiles
bool allowSockets
bool enabled
Indicates whether this argument is accepted by it's NidasApp instance.
Protected Member Functions
bool accept (const std::string &flag)
void setUsageString (const std::string &text)
Private Member Functions
NidasAppInputFilesArg ()
void updateUsage ()
virtual ~NidasAppInputFilesArg ()
Private Attributes
std::string default_input
int default_port
Friends
class NidasApp
Detailed Description
Extend NidasAppArg so the default input specifier and port can be customized, which in turn updates the usage string.
Constructor & Destructor Documentation
nidas::core::NidasAppInputFilesArg::NidasAppInputFilesArg () inline private
virtual nidas::core::NidasAppInputFilesArg::~NidasAppInputFilesArg () inline private virtual
Member Function Documentation
bool nidas::core::NidasAppArg::accept (const std::string & flag) inline protected inherited
References nidas::core::NidasAppArg::deprecatedFlag, nidas::core::NidasAppArg::enabled, nidas::core::NidasAppArg::enableShortFlag, nidas::core::NidasAppArg::flag, and nidas::core::NidasAppArg::longFlag.
void nidas::core::NidasAppArg::acceptShortFlag (bool enable) inline inherited
Set whether short flags are enabled or not.
Pass enable as false to disable short flags and require only long flags instead. By default short flags are enabled.
References nidas::core::NidasAppArg::enableShortFlag.
nidas::core::NidasAppArg::operator nidas_app_arglist_t () inline inherited
Provide conversion to an arglist so a single NidasAppArg can be passed where an arglist is expected.
void nidas::core::NidasAppInputFilesArg::setDefaultInput (const std::string & spec, int default_port_ = 0) inline
References default_input, default_port, and updateUsage().
Referenced by DataDump::parseRunstring().
void nidas::core::NidasAppArg::setDeprecatedFlag (const std::string & flag) inline inherited
Provide an alternative but deprecated flag for the argument.
References nidas::core::NidasAppArg::deprecatedFlag, and nidas::core::NidasAppArg::flag.
void nidas::core::NidasAppArg::setUsageString (const std::string & text) inline protected inherited
References nidas::core::NidasAppArg::usageString.
Referenced by updateUsage().
void NidasAppInputFilesArg::updateUsage () private
References allowFiles, allowSockets, default_port, and nidas::core::NidasAppArg::setUsageString().
Referenced by setDefaultInput().
std::string nidas::core::NidasAppArg::usage () inline inherited
Return the usage string for this particular argument.
References nidas::core::NidasAppArg::usageString.
Referenced by nidas::core::NidasApp::usage().
Friends And Related Function Documentation
friend class NidasApp friend
Member Data Documentation
bool nidas::core::NidasAppInputFilesArg::allowFiles
Referenced by DataDump::parseRunstring(), and updateUsage().
bool nidas::core::NidasAppInputFilesArg::allowSockets
Referenced by DataDump::parseRunstring(), and updateUsage().
std::string nidas::core::NidasAppInputFilesArg::default_input private
Referenced by setDefaultInput().
int nidas::core::NidasAppInputFilesArg::default_port private
Referenced by setDefaultInput(), and updateUsage().
bool nidas::core::NidasAppArg::enabled inherited
Indicates whether this argument is accepted by it's NidasApp instance.
Referenced by nidas::core::NidasAppArg::accept(), and nidas::core::NidasApp::usage().
The documentation for this class was generated from the following files:
nidas/core/NidasApp.h
nidas/core/NidasApp.cc