nidas: InvalidConstructorException Class Reference
InvalidConstructorException Class Reference
#include <InvalidConstructorException.h>
Public Member Functions
InvalidConstructorException (const std::string &msg)
InvalidConstructorException (const nidas::util::Exception &e)
InvalidConstructorException * clone () const
virtual int getErrno () const
virtual std::string toString () const throw ()
virtual const char * what () const throw ()
Static Public Member Functions
static std::string errnoToString (int err)
Return string description of an errno (from errno.h).
Protected Attributes
std::string _what
int _errno
Constructor & Destructor Documentation
InvalidConstructorException::InvalidConstructorException (const std::string & msg) inline
Referenced by clone().
InvalidConstructorException::InvalidConstructorException (const nidas::util::Exception & e) inline
Member Function Documentation
InvalidConstructorException* InvalidConstructorException::clone () const inline virtual
Reimplemented from nidas::util::Exception.
References InvalidConstructorException().
string nidas::util::Exception::errnoToString (int err) static inherited
Return string description of an errno (from errno.h).
A convienence method that uses strerror_r(int) from <string.h>.
Referenced by nidas::util::Thread::cancel(), nidas::util::Inet4Address::getHostName(), nidas::util::Process::getMaxRSS(), nidas::util::Process::getVMemSize(), nidas::util::Thread::join(), nidas::util::Thread::kill(), nidas::core::DSMServerApp::parseRunstring(), nidas::core::DSMEngine::parseRunstring(), nidas::util::Thread::setThreadSchedulerNolock(), nidas::util::Thread::start(), nidas::core::DSMServerApp::waitForSignal(), and nidas::core::DSMEngine::waitForSignal().
virtual int nidas::util::Exception::getErrno () const inline virtual inherited
References nidas::util::Exception::_errno.
Referenced by nidas::util::FileSet::createFile(), nidas::dynld::SampleOutputStream::flush(), nidas::core::IOStream::flush(), nidas::core::SensorHandler::PolledDSMSensor::handlePollEvents(), nidas::dynld::SampleOutputStream::receive(), nidas::core::DerivedDataReader::run(), NidsMerge::run(), MergeVerifier::run(), nidas::core::FsMountWorkerThread::run(), nidas::core::Socket::ConnectionThread::run(), WriterThread::run(), ServerThread::run(), nidas::util::McSocketListener::run(), and nidas::core::IOStream::write().
virtual std::string nidas::util::Exception::toString () const throw () inline virtual inherited
References nidas::util::Exception::_what.
Referenced by config::AddSensorComboDialog::accept(), config::VariableComboDialog::accept(), config::AddA2DVariableComboDialog::accept(), config::AddDSMComboDialog::accept(), A2DVariableItem::dataField(), nidas::dynld::isff::SE_GOESXmtr::detectModel(), VariableItem::getCalDate(), VariableItem::getCalValues(), nidas::core::DSMServerApp::initLogger(), nidas::core::DSMEngine::initLogger(), StatsProcess::main(), RemoteSerial::main(), main(), ConfigWindow::openFile(), config::AddDSMComboDialog::setUpDialog(), and config::AddSensorComboDialog::setUpDialog().
virtual const char* nidas::util::Exception::what () const throw () inline virtual inherited
References nidas::util::Exception::_what.
Referenced by nidas::core::SensorHandler::add(), nidas::core::DSMService::cancel(), nidas::core::FsMount::cancel(), nidas::dynld::isff::GOESOutput::cancelThread(), nidas::dynld::isff::SE_GOESXmtr::cancelTransmit(), Garmin::checkPPS(), nidas::core::DSMService::checkSubThreads(), nidas::dynld::UDPSampleOutput::XMLSocketListener::checkWorkers(), nidas::util::McSocket< SocketT >::close(), nidas::core::DSMEngine::closeOutputs(), ConfigWindow::ConfigWindow(), nidas::dynld::RawSampleService::connect(), nidas::core::DatagramSocket::connect(), nidas::dynld::UDPSampleOutput::connected(), nidas::util::FileSet::createFile(), nidas::core::DOMObjectFactory::createObject(), nidas::dynld::isff::WisardMote::createSampleTag(), nidas::core::VariableConverter::createVariableConverter(), nidas::core::DerivedDataReader::deleteInstance(), nidas::core::SampleOutputRequestThread::destroyInstance(), Garmin::disableAllMessages(), Garmin::disableMessage(), Garmin::disablePPS(), nidas::dynld::SampleProcessor::disconnect(), nidas::dynld::raf::SyncRecordGenerator::disconnect(), nidas::dynld::raf::CVIProcessor::disconnect(), nidas::core::SampleArchiver::disconnect(), nidas::dynld::StatisticsProcessor::disconnect(), nidas::core::DSMEngine::disconnect(), nidas::core::RemoteSerialConnection::doEscCmds(), nidas::dynld::psql::PSQLSampleOutput::dropAllTables(), nidas::core::DSMEngine::DSMEngine(), Garmin::enableAllMessages(), Garmin::enableMessage(), Garmin::enablePPS(), nidas::dynld::raf::PSI9116_Sensor::executeXmlRpc(), nidas::core::Project::findDSM(), nidas::dynld::UDPSampleOutput::XMLSocketListener::fireWorkers(), nidas::dynld::SampleOutputStream::flush(), nidas::core::ProjectConfig::fromDOMElement(), nidas::core::DSMServer::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::core::DatagramSocket::fromDOMElement(), nidas::core::DSMConfig::fromDOMElement(), nidas::core::Socket::fromDOMElement(), nidas::core::Project::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::CharacterSensor::fromDOMElement(), nidas::core::Variable::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::DSMAnalogSensor::getA2DSetup(), nidas::core::DSMSensor::getLooper(), nidas::core::Socket::getRemoteInet4Address(), UserFriendlyExceptionHandler::handle(), nidas::core::RemoteSerialListener::handlePollEvents(), nidas::core::RemoteSerialConnection::handlePollEvents(), nidas::core::SensorHandler::PolledDSMSensor::handlePollEvents(), nidas::core::SensorHandler::NotifyPipe::handlePollEvents(), nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::psql::PSQLSampleOutput::init(), nidas::dynld::isff::SE_GOESXmtr::init(), nidas::core::CharacterSensor::init(), nidas::dynld::raf::SyncRecordReader::init(), nidas::core::DSMServerApp::initProcess(), nidas::core::DSMEngine::initProcess(), nidas::core::XmlRpcThread::interrupt(), nidas::core::SensorOpener::interrupt(), nidas::core::DerivedDataReader::interrupt(), nidas::core::DSMService::interrupt(), nidas::util::McSocketListener::interrupt(), nidas::util::McSocketMulticaster< SocketTT >::interrupt(), nidas::core::DSMService::join(), nidas::core::SamplePipeline::join(), nidas::core::DSMEngine::joinDataThreads(), nidas::util::McSocket< SocketT >::joinMulticaster(), nidas::dynld::isff::GOESOutput::joinThread(), nidas::core::DSMServerApp::killStatusThread(), nidas::dynld::isff::GOESOutput::killThread(), nidas::core::DSMServerApp::killXmlRpcThread(), nidas::core::DSMEngine::killXmlRpcThread(), nidas::util::McSocket< SocketT >::listen(), StatsProcess::listOutputSamples(), PacketReader::loop(), nidas::dynld::isff::MOSMote::MOS_TimeSyncer::looperNotify(), SensorSimulator::looperNotify(), nidas::core::SerialSensor::Prompter::looperNotify(), nidas::core::DSMServerApp::main(), PConfig::main(), nidas::core::DSMEngine::main(), PSI::main(), main(), DataDump::main(), SensorSimApp::main(), nidas::core::FsMount::mount(), nidas::core::SensorHandler::NotifyPipe::notify(), nidas::dynld::isff::SonicAnemometer::offsetsTiltAndRotate(), nidas::dynld::raf::DSMAnalogSensor::open(), nidas::core::SocketIODevice::open(), nidas::dynld::isff::CSAT3_Sonic::open(), nidas::core::ServerSocketIODevice::open(), ConfigWindow::openFile(), nidas::dynld::SampleInputStream::parseInputHeader(), nidas::core::NidasApp::parseInputs(), ProjConfigIO::parseRunstring(), NidsMerge::parseRunstring(), SyncDumper::parseRunstring(), MergeVerifier::parseRunstring(), TeeTTy::parseRunstring(), SensorExtract::parseRunstring(), StatsProcess::parseRunstring(), PacketReader::parseRunstring(), nidas::core::DSMEngine::parseRunstring(), DataPrep::parseRunstring(), DataStats::parseRunstring(), nidas::core::CalFile::parseTime(), nidas::core::NidasApp::parseTime(), nidas::dynld::raf::LamsSensor::printStatus(), nidas::dynld::DSC_A2DSensor::printStatus(), nidas::dynld::DSC_FreqCounter::printStatus(), nidas::dynld::DSC_PulseCounter::printStatus(), nidas::dynld::DSC_Event::printStatus(), nidas::dynld::raf::DSMAnalogSensor::printStatus(), nidas::dynld::raf::IRIGSensor::printStatus(), nidas::dynld::raf::TwoD_USB::printStatus(), nidas::dynld::raf::DSMArincSensor::printStatus(), nidas::core::SerialSensor::printStatus(), nidas::dynld::isff::SE_GOESXmtr::printStatus(), nidas::core::SampleInputHeader::read(), nidas::dynld::raf::SyncServer::read(), nidas::dynld::ParoSci_202BG_Calibration::readCalFile(), AutoCalClient::readCalFile(), nidas::dynld::raf::DSMAnalogSensor::readCalFile(), nidas::dynld::isff::CS_Krypton::readCalFile(), nidas::core::Linear::readCalFile(), nidas::core::Polynomial::readCalFile(), Garmin::readInit(), nidas::dynld::isff::PacketInputStream::readSamples(), nidas::dynld::raf::CVIOutput::receive(), nidas::dynld::UDPSampleOutput::receive(), nidas::dynld::SampleOutputStream::receive(), nidas::dynld::AsciiOutput::receive(), nidas::dynld::psql::PSQLSampleOutput::receive(), nidas::dynld::raf::CVIProcessor::receive(), nidas::util::SocketImpl::receive(), nidas::core::SensorHandler::remove(), nidas::util::McSocket< SocketT >::request(), nidas::core::Socket::requestConnection(), nidas::core::ServerSocket::requestConnection(), nidas::core::requestXMLConfig(), FileSim::rewind(), HeaderUtil::run(), Garmin::run(), DatasetsApp::run(), nidas::core::SampleOutputRequestThread::run(), ProjConfigIO::run(), nidas::core::StatusListener::run(), nidas::core::DerivedDataReader::run(), NidsMerge::run(), GPS_SetClock::run(), PacketDecode::run(), MergeVerifier::run(), TeeTTy::run(), nidas::core::DSMServerApp::run(), StatsProcess::run(), SensorExtract::run(), SyncDumper::run(), Calibrator::run(), nidas::core::DSMEngineStat::run(), nidas::core::SensorOpener::run(), ARLIngest::run(), nidas::core::DSMEngine::run(), nidas::core::DSMServerStat::run(), RemoteSerial::run(), nidas::dynld::raf::SyncServer::run(), nidas::dynld::isff::GOESOutput::run(), DataPrep::run(), nidas::core::SensorHandler::run(), nidas::core::FsMountWorkerThread::run(), nidas::dynld::UDPSampleOutput::XMLSocketListener::run(), Extract2D::run(), ublox::run(), nidas::dynld::RawSampleService::Worker::run(), TeeI2C::run(), nidas::core::Socket::ConnectionThread::run(), DataStats::run(), WriterThread::run(), DataDump::run(), ServerThread::run(), nidas::util::McSocketListener::run(), nidas::util::McSocketMulticaster< SocketTT >::run(), nidas::util::ThreadJoiner::run(), nidas::dynld::raf::SyncRecordReader::scanHeader(), Garmin::scanMessages(), nidas::dynld::RawSampleService::schedule(), nidas::dynld::raf::PSI9116_Sensor::sendCommand(), Garmin::sendInit(), nidas::dynld::raf::SppSerial::sendInitPacketAndCheckAck(), nidas::dynld::raf::SPP300_Serial::sendInitString(), nidas::dynld::raf::CDP_Serial::sendInitString(), nidas::dynld::raf::SPP200_Serial::sendInitString(), nidas::dynld::raf::SPP100_Serial::sendInitString(), nidas::dynld::raf::BCPD_Serial::sendInitString(), nidas::core::DSMConfig::sensorFromDOMElement(), Garmin::setBaudRateOption(), TeeTTy::setFIFOPriority(), TeeI2C::setFIFOPriority(), Calibrator::setup(), PConfig::showCalFiles(), nidas::dynld::raf::PSI9116_Sensor::stopStreams(), nidas::dynld::isff::CSAT3_Sonic::terminalMode(), nidas::util::Thread::test(), nidas::dynld::isff::SE_GOESXmtr::testTransmitSE120(), nidas::dynld::raf::DSMAnalogSensor::testVoltage(), nidas::dynld::isff::SE_GOESXmtr::transmitData(), ubx_config(), nidas::dynld::raf::CDP_Serial::validate(), nidas::core::MultipleUDPSockets::write(), nidas::util::Cond::~Cond(), nidas::dynld::raf::CVIProcessor::~CVIProcessor(), nidas::core::DatagramSocket::~DatagramSocket(), nidas::util::Mutex::~Mutex(), nidas::core::SensorHandler::NotifyPipe::~NotifyPipe(), PacketReader::~PacketReader(), nidas::core::RemoteSerialConnection::~RemoteSerialConnection(), nidas::core::RemoteSerialListener::~RemoteSerialListener(), nidas::util::RWLock::~RWLock(), nidas::core::SampleArchiver::~SampleArchiver(), nidas::core::SampleBuffer::~SampleBuffer(), nidas::dynld::SampleProcessor::~SampleProcessor(), nidas::core::SampleSorter::~SampleSorter(), nidas::core::ServerSocket::~ServerSocket(), nidas::core::Socket::~Socket(), nidas::dynld::StatisticsProcessor::~StatisticsProcessor(), nidas::dynld::raf::SyncRecordGenerator::~SyncRecordGenerator(), and nidas::util::Thread::~Thread().
Member Data Documentation
int nidas::util::Exception::_errno protected inherited
Referenced by nidas::util::Exception::getErrno().
std::string nidas::util::Exception::_what protected inherited
Referenced by nidas::core::SampleLengthException::SampleLengthException(), nidas::util::Exception::toString(), nidas::util::Exception::what(), and nidas::core::XMLException::XMLException().
The documentation for this class was generated from the following file:
nidas/apps/config/exceptions/InvalidConstructorException.h