nidas: nidas::core::McSocketUDP Class Reference
nidas::core::McSocketUDP Class Reference
Implementation of an IOChannel, using nidas::util::McSocket<nidas::util::DatagramSocket> to establish a pair of communicating UDP sockets.
#include <McSocketUDP.h>
Classes
class MyMcSocket
Public Member Functions
McSocketUDP ()
Constructor.
McSocketUDP (const McSocketUDP &)
Copy constructor.
~McSocketUDP ()
McSocketUDP * clone () const
Derived classes must provide clone.
void setRequestType (enum McSocketRequest val)
enum McSocketRequest getRequestType () const
bool isRequester () const
Does this McSocket request connections, or does it listen for incoming connections.
void setRequester (bool val)
void setName (const std::string &val)
const std::string & getName () const
void requestConnection (IOChannelRequester *service) throw (nidas::util::IOException)
After the IOChannel is configured, a user of IOChannel calls requestConnection to get things started.
IOChannel * connect () throw (nidas::util::IOException)
Establish a connection.
virtual bool isNewInput () const
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
virtual void connected (nidas::util::DatagramSocket *sock, const nidas::util::Inet4PacketInfoX &pktinfo)
void setNonBlocking (bool val) throw (nidas::util::IOException)
Do setNonBlocking(val) on underlying socket.
bool isNonBlocking () const throw (nidas::util::IOException)
Return isNonBlocking() of underlying socket.
size_t read (void *, size_t) throw (nidas::util::IOException)
A McSocketUDP shouldn't be used to do any actual reads or writes, it just sets up the connection.
size_t write (const void *, size_t) throw (nidas::util::IOException)
A McSocketUDP shouldn't be used to do any actual reads or writes, it just sets up the connection.
size_t write (const struct iovec *, int) throw (nidas::util::IOException)
A McSocketUDP shouldn't be used to do any actual reads or writes, it just sets up the connection.
void close () throw (nidas::util::IOException)
int getFd () const
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
void setInet4McastSocketAddress (const nidas::util::Inet4SocketAddress &val)
const
nidas::util::Inet4SocketAddress & getInet4McastSocketAddress () const
virtual int getReconnectDelaySecs () const
virtual const ConnectionInfo & getConnectionInfo () const
What is the IP address of the host at the other end of the connection.
virtual void setConnectionInfo (const ConnectionInfo &val)
virtual size_t getBufferSize () const throw ()
Return suggested buffer length.
virtual void flush () throw (nidas::util::IOException)
Default flush implementation does nothing.
virtual dsm_time_t createFile (dsm_time_t t, bool exact)
Request that an IOChannel open a new file, with a name based on a time.
virtual bool writeNidasHeader () const
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
virtual void setDSMConfig (const DSMConfig *val)
What DSM is this IOChannel connected to?
virtual const DSMConfig * getDSMConfig () const
What DSM is this IOChannel connected to? May be NULL.
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static IOChannel * createIOChannel (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
static const XMLCh * getNamespaceURI ()
Protected Attributes
IOChannelRequester * _iochanRequester
MyMcSocket _mcsocket
Private Member Functions
McSocketUDP & operator= (const McSocketUDP &)
No assignment.
Private Attributes
std::string _name
bool _amRequester
bool _firstRead
bool _newInput
bool _nonBlocking
Detailed Description
Implementation of an IOChannel, using nidas::util::McSocket<nidas::util::DatagramSocket> to establish a pair of communicating UDP sockets.
Implementation of an IOChannel, using McSocket to establish connections
Constructor & Destructor Documentation
McSocketUDP::McSocketUDP ()
Constructor.
References setName().
Referenced by clone().
McSocketUDP::McSocketUDP (const McSocketUDP & x)
Copy constructor.
Should only be called before nidas::util::Socket is connected.
nidas::core::McSocketUDP::~McSocketUDP () inline
Member Function Documentation
McSocketUDP * McSocketUDP::clone () const virtual
Derived classes must provide clone.
Implements nidas::core::IOChannel.
Reimplemented in nidas::core::MultipleUDPSockets.
References McSocketUDP().
void McSocketUDP::close () throw (nidas::util::IOException) virtual
Implements nidas::core::IOChannel.
Reimplemented in nidas::core::MultipleUDPSockets.
References _mcsocket, and nidas::util::McSocket< SocketT >::close().
IOChannel * McSocketUDP::connect () throw (nidas::util::IOException) virtual
Establish a connection.
On return, the connection has been established. It may return a new instance of an IOChannel.
Implements nidas::core::IOChannel.
Reimplemented in nidas::core::MultipleUDPSockets.
References _mcsocket, nidas::util::McSocket< SocketT >::accept(), nidas::util::McSocket< SocketT >::connect(), nidas::util::Inet4PacketInfo::getDestinationAddress(), nidas::util::Inet4PacketInfo::getInterface(), nidas::util::Inet4PacketInfoX::getRemoteSocketAddress(), isNonBlocking(), isRequester(), nidas::core::IOChannel::setConnectionInfo(), and nidas::util::DatagramSocket::setNonBlocking().
void McSocketUDP::connected (nidas::util::DatagramSocket * sock, const nidas::util::Inet4PacketInfoX & pktinfo) virtual
Reimplemented in nidas::core::MultipleUDPSockets.
References _iochanRequester, nidas::core::IOChannelRequester::connected(), nidas::util::Inet4PacketInfo::getDestinationAddress(), nidas::util::Inet4PacketInfo::getInterface(), nidas::util::Inet4PacketInfoX::getRemoteSocketAddress(), isNonBlocking(), nidas::core::IOChannel::setConnectionInfo(), and nidas::util::DatagramSocket::setNonBlocking().
virtual dsm_time_t nidas::core::IOChannel::createFile (dsm_time_t t, bool exact) inline virtual inherited
Request that an IOChannel open a new file, with a name based on a time.
This should be implemented by derived classes which write to disk files. Other derived classes (e.g. sockets) can just use this default implementation - basically ignoring the request.
Parameters
t Time to use when creating file name.
exact Use exact time when creating file name, else the time is adjusted to an even time interval.
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::IOStream::createFile().
IOChannel * IOChannel::createIOChannel (const xercesc::DOMElement * node) throw (nidas::util::InvalidParameterException) static inherited
References nidas::core::DOMObjectFactory::createObject(), nidas::core::Socket::createSocket(), nidas::util::Process::expandEnvVars(), nidas::core::XDOMElement::getAttributeValue(), and nidas::core::XDOMElement::getNodeName().
Referenced by nidas::dynld::psql::PSQLSampleOutput::fromDOMElement(), nidas::core::DSMService::fromDOMElement(), nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::core::SampleOutputBase::fromDOMElement(), and nidas::dynld::SampleInputStream::fromDOMElement().
virtual void nidas::core::IOChannel::flush () throw (nidas::util::IOException) inline virtual inherited
Default flush implementation does nothing.
Reimplemented in nidas::dynld::isff::GOESXmtr, nidas::dynld::isff::SE_GOESXmtr, and nidas::dynld::psql::PSQLChannel.
Referenced by nidas::core::SampleArchiver::disconnect(), and nidas::core::IOStream::flush().
void McSocketUDP::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
Reimplemented in nidas::core::MultipleUDPSockets.
References nidas::util::Process::expandEnvVars(), nidas::util::Inet4Address::getByName(), nidas::util::Logger::getInstance(), nidas::core::XDOMAttr::getName(), nidas::util::Logger::log(), LOG_WARNING, NIDAS_MULTICAST_ADDR, NIDAS_SVC_REQUEST_PORT_UDP, and port.
virtual size_t nidas::core::IOChannel::getBufferSize () const throw () inline virtual inherited
Return suggested buffer length.
Reimplemented in nidas::core::Socket, nidas::core::DatagramSocket, and nidas::core::MultipleUDPSockets.
Referenced by nidas::dynld::isff::PacketInputStream::init(), nidas::dynld::isff::PacketInputStream::PacketInputStream(), and nidas::dynld::SampleInputStream::SampleInputStream().
virtual const ConnectionInfo& nidas::core::IOChannel::getConnectionInfo () const inline virtual inherited
What is the IP address of the host at the other end of the connection.
If this IOChannel is not a socket then return INADDR_ANY, using the default constructor of an Inet4Address. Socket subclasses should override this.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
virtual const DSMConfig* nidas::core::IOChannel::getDSMConfig () const inline virtual inherited
What DSM is this IOChannel connected to? May be NULL.
Referenced by nidas::core::FileSet::setDir(), and nidas::core::FileSet::setFileName().
int McSocketUDP::getFd () const virtual
Implements nidas::core::IOChannel.
Reimplemented in nidas::core::MultipleUDPSockets.
const nidas::util::Inet4SocketAddress& nidas::core::McSocketUDP::getInet4McastSocketAddress () const inline
References _mcsocket, and nidas::util::McSocket< SocketT >::getInet4McastSocketAddress().
Referenced by nidas::core::MultipleUDPSockets::addClient().
const std::string& nidas::core::McSocketUDP::getName () const inline virtual
Implements nidas::core::IOChannel.
References _name.
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
virtual int nidas::core::IOChannel::getReconnectDelaySecs () const inline virtual inherited
Reimplemented in nidas::core::FileSet.
Referenced by nidas::core::SampleOutputBase::getReconnectDelaySecs().
enum McSocketRequest nidas::core::McSocketUDP::getRequestType () const inline virtual
Reimplemented from nidas::core::IOChannel.
References _mcsocket, and nidas::util::McSocket< SocketT >::getRequestType().
virtual bool nidas::core::McSocketUDP::isNewInput () const inline virtual
Some IOChannels, namely FileSet, which opens successive files, need to indicate when a read is from the start of a new file.
This method is used by code which may need to do special things at the beginning of a file, like read a SampleInputHeader.
Reimplemented from nidas::core::IOChannel.
References _newInput.
bool nidas::core::McSocketUDP::isNonBlocking () const throw (nidas::util::IOException) inline virtual
Return isNonBlocking() of underlying socket.
Implements nidas::core::IOChannel.
References _nonBlocking.
Referenced by nidas::core::MultipleUDPSockets::connect(), connect(), and connected().
bool nidas::core::McSocketUDP::isRequester () const inline
Does this McSocket request connections, or does it listen for incoming connections.
References _amRequester.
Referenced by connect().
McSocketUDP& nidas::core::McSocketUDP::operator= (const McSocketUDP &) private
No assignment.
size_t nidas::core::McSocketUDP::read (void * , size_t) throw (nidas::util::IOException) inline virtual
A McSocketUDP shouldn't be used to do any actual reads or writes, it just sets up the connection.
The returned IOChannel should be used to read/write. Calling this method will fail with an assert.
Implements nidas::core::IOChannel.
Reimplemented in nidas::core::MultipleUDPSockets.
void McSocketUDP::requestConnection (IOChannelRequester *) throw (nidas::util::IOException) virtual
After the IOChannel is configured, a user of IOChannel calls requestConnection to get things started.
It is like opening a device, but in the case of server sockets, it just starts a thread to wait on connections. Only when the IOChannelRequester::connected() method is called back is the channel actually open and ready for IO. The IOChannel* returned by IOChannelRequester::connected may be another instance of an IOChannel.
Implements nidas::core::IOChannel.
virtual void nidas::core::IOChannel::setConnectionInfo (const ConnectionInfo & val) inline virtual inherited
Referenced by nidas::core::MultipleUDPSockets::connect(), nidas::core::Socket::connect(), nidas::core::McSocket::connect(), connect(), nidas::core::McSocket::connected(), and connected().
virtual void nidas::core::IOChannel::setDSMConfig (const DSMConfig * val) inline virtual inherited
What DSM is this IOChannel connected to?
Referenced by nidas::core::SampleOutputBase::fromDOMElement(), nidas::core::SampleOutputBase::SampleOutputBase(), and nidas::core::SampleOutputBase::setIOChannel().
void nidas::core::McSocketUDP::setInet4McastSocketAddress (const nidas::util::Inet4SocketAddress & val) inline
References _mcsocket, and nidas::util::McSocket< SocketT >::setInet4McastSocketAddress().
void nidas::core::McSocketUDP::setName (const std::string & val) inline virtual
Implements nidas::core::IOChannel.
References _name.
Referenced by McSocketUDP(), and nidas::core::MultipleUDPSockets::MultipleUDPSockets().
void nidas::core::McSocketUDP::setNonBlocking (bool val) throw (nidas::util::IOException) inline virtual
Do setNonBlocking(val) on underlying socket.
Implements nidas::core::IOChannel.
References _nonBlocking.
void nidas::core::McSocketUDP::setRequester (bool val) inline
References _amRequester.
void nidas::core::McSocketUDP::setRequestType (enum McSocketRequest val) inline virtual
Reimplemented from nidas::core::IOChannel.
References _mcsocket, and nidas::util::McSocket< SocketT >::setRequestType().
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
size_t nidas::core::McSocketUDP::write (const void * , size_t) throw (nidas::util::IOException) inline virtual
A McSocketUDP shouldn't be used to do any actual reads or writes, it just sets up the connection.
The returned IOChannel should be used to read/write. Calling this method will fail with an assert.
Implements nidas::core::IOChannel.
Reimplemented in nidas::core::MultipleUDPSockets.
size_t nidas::core::McSocketUDP::write (const struct iovec * , int) throw (nidas::util::IOException) inline virtual
A McSocketUDP shouldn't be used to do any actual reads or writes, it just sets up the connection.
The returned IOChannel should be used to read/write. Calling this method will fail with an assert.
Implements nidas::core::IOChannel.
Reimplemented in nidas::core::MultipleUDPSockets.
virtual bool nidas::core::IOChannel::writeNidasHeader () const inline virtual inherited
Should the NIDAS header be written to this IOChannel? NIDAS headers are not written to DatagramSockets, because there is no guarantee they will get there.
Reimplemented in nidas::core::DatagramSocket.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
Member Data Documentation
bool nidas::core::McSocketUDP::_amRequester private
Referenced by isRequester(), and setRequester().
bool nidas::core::McSocketUDP::_firstRead private
IOChannelRequester* nidas::core::McSocketUDP::_iochanRequester protected
Referenced by connected().
MyMcSocket nidas::core::McSocketUDP::_mcsocket protected
Referenced by close(), nidas::core::MultipleUDPSockets::connect(), connect(), getInet4McastSocketAddress(), getRequestType(), setInet4McastSocketAddress(), and setRequestType().
std::string nidas::core::McSocketUDP::_name private
Referenced by getName(), and setName().
bool nidas::core::McSocketUDP::_newInput private
Referenced by isNewInput().
bool nidas::core::McSocketUDP::_nonBlocking private
Referenced by isNonBlocking(), and setNonBlocking().
The documentation for this class was generated from the following files:
nidas/core/McSocketUDP.h
nidas/core/McSocketUDP.cc