nidas: nidas::core::MessageSampleScanner Class Reference
nidas::core::MessageSampleScanner Class Reference
A DriverSampleScanner which supports the set/get of message separation parameters.
#include <SampleScanner.h>
Public Member Functions
MessageSampleScanner (int bufsize=8192)
void setMessageParameters (unsigned int len, const std::string &val, bool eom) throw (nidas::util::InvalidParameterException)
Set the parameters which delineate a message for this scanner.
const std::string & getMessageSeparator () const
Get message separator string.
const std::string getBackslashedMessageSeparator () const
Get message separator with backslash sequences added back.
bool getMessageSeparatorAtEOM () const
Is the message separator at the end of the message (true), or at the beginning (false)?
unsigned int getMessageLength () const
Returns 0.
Sample * nextSample (DSMSensor *sensor)
Extract the next sample from the buffer.
virtual void init ()
Initialize the scanner.
virtual bool getNullTerminate () const
Should the SampleScanner append a null character, '\0', to the messages.
void setUsecsPerByte (int val)
int getUsecsPerByte () const
virtual size_t readBuffer (DSMSensor *sensor, bool &exhausted) throw (nidas::util::IOException)
Read from the sensor into the internal buffer of this SampleScanner.
virtual size_t readBuffer (DSMSensor *sensor, bool &exhausted, int msecTimeout) throw (nidas::util::IOException)
Read from the sensor into the internal buffer of this SampleScanner, providing a timeout in milliseconds.
virtual void clearBuffer ()
unsigned int getBytesInBuffer () const
virtual void resetStatistics ()
virtual void calcStatistics (unsigned int periodUsec)
Update the sensor sampling statistics: samples/sec, bytes/sec, min/max sample size, that can be accessed via getObservedSamplingRate(), getObservedDataRate() etc.
unsigned int getMaxSampleLength () const
unsigned int getMinSampleLength () const
unsigned int getBadTimeTagCount () const
float getObservedSamplingRate () const
float getObservedDataRate () const
void addNumBytesToStats (size_t val)
void addSampleToStats (unsigned int val)
void incrementBadTimeTags ()
Protected Attributes
const unsigned int BUFSIZE
Buffer size for reading from sensor.
char * _buffer
unsigned int _bufhead
unsigned int _buftail
Sample * _osamp
struct dsm_sample _header
unsigned int _outSampRead
unsigned int _outSampToRead
char * _outSampDataPtr
std::string _messageSeparator
int _messageLength
bool _separatorAtEOM
char * _separator
messageSeparator in a C string.
int _separatorLen
Length of messageSeparator.
Detailed Description
A DriverSampleScanner which supports the set/get of message separation parameters.
Typically these parameters are sent down to a driver module by an implementation of DSMSensor.
Constructor & Destructor Documentation
MessageSampleScanner::MessageSampleScanner (int bufsize = 8192)
Member Function Documentation
void nidas::core::SampleScanner::addNumBytesToStats (size_t val) inline inherited
References nidas::core::SampleScanner::_nbytes.
void nidas::core::SampleScanner::addSampleToStats (unsigned int val) inline inherited
References nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_maxSampleLength, nidas::core::SampleScanner::_minSampleLength, and nidas::core::SampleScanner::_nsamples.
Referenced by nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), nidas::core::MessageStreamScanner::nextSampleSepEOM(), and nidas::core::MessageStreamScanner::requestBiggerSample().
void SampleScanner::calcStatistics (unsigned int periodUsec) virtual inherited
Update the sensor sampling statistics: samples/sec, bytes/sec, min/max sample size, that can be accessed via getObservedSamplingRate(), getObservedDataRate() etc.
Should be called every periodUsec by a user of this sensor.
Parameters
periodUsec Statistics period.
References nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_dataRateObs, nidas::core::SampleScanner::_maxSampleLength, nidas::core::SampleScanner::_minSampleLength, nidas::core::SampleScanner::_nbytes, nidas::core::SampleScanner::_nsamples, nidas::core::SampleScanner::_reportIndex, nidas::core::SampleScanner::_sampleRateObs, and USECS_PER_SEC.
Referenced by nidas::core::DSMSensor::calcStatistics().
void SampleScanner::clearBuffer () virtual inherited
References nidas::core::SampleScanner::_bufhead, and nidas::core::SampleScanner::_buftail.
Referenced by nidas::core::DSMSensor::clearBuffer().
const string MessageSampleScanner::getBackslashedMessageSeparator () const virtual
Get message separator with backslash sequences added back.
Reimplemented from nidas::core::SampleScanner.
References nidas::core::SampleScanner::_messageSeparator, and nidas::util::addBackslashSequences().
unsigned int nidas::core::SampleScanner::getBadTimeTagCount () const inline inherited
References nidas::core::SampleScanner::_badTimeTags.
Referenced by nidas::core::DSMSensor::getBadTimeTagCount().
unsigned int nidas::core::SampleScanner::getBytesInBuffer () const inline inherited
References nidas::core::SampleScanner::_bufhead, and nidas::core::SampleScanner::_buftail.
unsigned int nidas::core::SampleScanner::getMaxSampleLength () const inline inherited
References nidas::core::SampleScanner::_maxSampleLength, and nidas::core::SampleScanner::_reportIndex.
Referenced by nidas::core::DSMSensor::getMaxSampleLength().
unsigned int nidas::core::MessageSampleScanner::getMessageLength () const inline virtual
Returns 0.
Reimplemented from nidas::core::SampleScanner.
References nidas::core::SampleScanner::_messageLength.
const std::string& nidas::core::MessageSampleScanner::getMessageSeparator () const inline virtual
Get message separator string.
Any backslash sequences will have been replaced by their intended value.
Reimplemented from nidas::core::SampleScanner.
References nidas::core::SampleScanner::_messageSeparator.
bool nidas::core::MessageSampleScanner::getMessageSeparatorAtEOM () const inline virtual
Is the message separator at the end of the message (true), or at the beginning (false)?
Reimplemented from nidas::core::SampleScanner.
References nidas::core::SampleScanner::_separatorAtEOM.
unsigned int nidas::core::SampleScanner::getMinSampleLength () const inline inherited
References nidas::core::SampleScanner::_maxSampleLength, nidas::core::SampleScanner::_minSampleLength, and nidas::core::SampleScanner::_reportIndex.
Referenced by nidas::core::DSMSensor::getMinSampleLength().
virtual bool nidas::core::SampleScanner::getNullTerminate () const inline virtual inherited
Should the SampleScanner append a null character, '\0', to the messages.
Reimplemented in nidas::core::DatagramSampleScanner, and nidas::core::MessageStreamScanner.
Referenced by nidas::core::CharacterSensor::getNullTerminated().
float SampleScanner::getObservedDataRate () const inherited
References nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_dataRateObs, nidas::core::SampleScanner::_initialTimeSecs, nidas::core::SampleScanner::_nbytes, and nidas::core::SampleScanner::_reportIndex.
Referenced by nidas::core::DSMSensor::getObservedDataRate().
float SampleScanner::getObservedSamplingRate () const inherited
References nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_initialTimeSecs, nidas::core::SampleScanner::_nsamples, nidas::core::SampleScanner::_reportIndex, and nidas::core::SampleScanner::_sampleRateObs.
Referenced by nidas::core::DSMSensor::getObservedSamplingRate().
int nidas::core::SampleScanner::getUsecsPerByte () const inline inherited
References nidas::core::SampleScanner::_usecsPerByte.
Referenced by nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), and nidas::core::MessageStreamScanner::nextSampleSepEOM().
void nidas::core::SampleScanner::incrementBadTimeTags () inline inherited
References nidas::core::SampleScanner::_badTimeTags.
Referenced by nidas::core::DriverSampleScanner::nextSample().
void SampleScanner::init () virtual inherited
Initialize the scanner.
Must be called by a user of SampleScanner prior to calling readSamples().
References nidas::core::SampleScanner::resetStatistics().
Sample * DriverSampleScanner::nextSample (DSMSensor * sensor) virtual inherited
Extract the next sample from the buffer.
Returns NULL if there are no more samples in the buffer.
Implements nidas::core::SampleScanner.
References nidas::core::SampleScanner::_buffer, nidas::core::SampleScanner::_bufhead, nidas::core::SampleScanner::_buftail, nidas::core::SampleScanner::_header, nidas::core::SampleScanner::_osamp, nidas::core::SampleScanner::_outSampDataPtr, nidas::core::SampleScanner::_outSampRead, nidas::core::SampleScanner::_outSampToRead, nidas::core::SampleClock::addSampleDate(), nidas::core::SampleScanner::addSampleToStats(), nidas::core::Sample::freeReference(), nidas::core::Sample::getDataByteLength(), nidas::core::DSMSensor::getDriverTimeTagUsecs(), nidas::core::DSMSensor::getId(), nidas::core::SampleClock::getInstance(), nidas::core::Sample::getVoidDataPtr(), nidas::core::SampleScanner::incrementBadTimeTags(), len, dsm_sample::length, nidas::core::SampleClock::OK, nidas::core::Sample::setDataLength(), nidas::core::Sample::setId(), nidas::core::Sample::setTimeTag(), SIZEOF_DSM_SAMPLE_HEADER, and dsm_sample::timetag.
size_t SampleScanner::readBuffer (DSMSensor * sensor, bool & exhausted) throw (nidas::util::IOException) virtual inherited
Read from the sensor into the internal buffer of this SampleScanner.
Reimplemented in nidas::core::DatagramSampleScanner, and nidas::core::MessageStreamScanner.
References DLOG, nidas::core::Project::getInstance(), and len.
Referenced by nidas::core::SampleScanner::readBuffer(), nidas::core::MessageStreamScanner::readBuffer(), and nidas::core::DSMSensor::readBuffer().
size_t SampleScanner::readBuffer (DSMSensor * sensor, bool & exhausted, int msecTimeout) throw (nidas::util::IOException) virtual inherited
Read from the sensor into the internal buffer of this SampleScanner, providing a timeout in milliseconds.
This will throw nidas::util::IOTimeoutException if the read fails due to a timeout.
Reimplemented in nidas::core::MessageStreamScanner.
References MSECS_PER_SEC, NLOG, NSECS_PER_MSEC, and nidas::core::SampleScanner::readBuffer().
void SampleScanner::resetStatistics () virtual inherited
References nidas::core::SampleScanner::_badTimeTags, nidas::core::SampleScanner::_currentIndex, nidas::core::SampleScanner::_dataRateObs, nidas::core::SampleScanner::_initialTimeSecs, nidas::core::SampleScanner::_maxSampleLength, nidas::core::SampleScanner::_minSampleLength, nidas::core::SampleScanner::_nbytes, nidas::core::SampleScanner::_nsamples, nidas::core::SampleScanner::_reportIndex, and nidas::core::SampleScanner::_sampleRateObs.
Referenced by nidas::core::SampleScanner::init(), and nidas::core::SampleScanner::SampleScanner().
void MessageSampleScanner::setMessageParameters (unsigned int len, const std::string & val, bool eom) throw (nidas::util::InvalidParameterException) virtual
Set the parameters which delineate a message for this scanner.
The messageSeparator is the string of bytes that a sensor outputs between messages. The string may contain baskslash sequences.
Parameters
len The message length in bytes. A value of zero means the message length is completely variable, and that a scanner is should always be looking for a messageSeparator in the data. A positive value means read in messageLength number of bytes and then start looking for the messageSeparator. The messageLength does not include the length of the messageSeparator.
Setting a positive message length is only necessary if there is a chance that the message separator could be found in the data portion of the message. This may be the case if the sensor is generating binary data. A positive message length causes the parser to read messageLength number of bytes before again searching for the separator. This also makes the parsing a bit more efficient. If the messageLength is too small it will not necessarily cause messages to be truncated - all the data up to, and including the separator is still read and passed along for processing. If the value is larger than the actual message length it will cause two or more messages to be concatenated into one.
Parameters
eom True means the message scanner expects the separator at the end of the message, and the next byte read after the separator is the first byte of the next message. The timetag of a sample is the receipt time of the first byte after the separator of the previous message. False means the scanner expects the separator at the beginning of the message, in which case the timetag of a sample is the receipt time of the first byte of the messageSeparator.
See Also
* nidas::util::replaceBackslashSequences()
Reimplemented from nidas::core::DriverSampleScanner.
References len, and nidas::util::replaceBackslashSequences().
void nidas::core::SampleScanner::setUsecsPerByte (int val) inline inherited
References nidas::core::SampleScanner::_usecsPerByte.
Referenced by nidas::dynld::GPS_NMEA_Serial::buildSampleScanner(), and nidas::core::SerialSensor::buildSampleScanner().
Member Data Documentation
char* nidas::core::SampleScanner::_buffer protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), nidas::core::MessageStreamScanner::nextSampleSepEOM(), and nidas::core::SampleScanner::~SampleScanner().
unsigned int nidas::core::SampleScanner::_bufhead protected inherited
Referenced by nidas::core::SampleScanner::clearBuffer(), nidas::core::SampleScanner::getBytesInBuffer(), nidas::core::DriverSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), and nidas::core::MessageStreamScanner::nextSampleSepEOM().
unsigned int nidas::core::SampleScanner::_buftail protected inherited
Referenced by nidas::core::SampleScanner::clearBuffer(), nidas::core::SampleScanner::getBytesInBuffer(), nidas::core::DriverSampleScanner::nextSample(), nidas::core::DatagramSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), and nidas::core::MessageStreamScanner::nextSampleSepEOM().
struct dsm_sample nidas::core::SampleScanner::_header protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample().
int nidas::core::SampleScanner::_messageLength protected inherited
Referenced by getMessageLength(), and nidas::core::MessageStreamScanner::getMessageLength().
std::string nidas::core::SampleScanner::_messageSeparator protected inherited
Referenced by getBackslashedMessageSeparator(), nidas::core::MessageStreamScanner::getBackslashedMessageSeparator(), getMessageSeparator(), and nidas::core::MessageStreamScanner::getMessageSeparator().
Sample* nidas::core::SampleScanner::_osamp protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), nidas::core::MessageStreamScanner::nextSampleSepEOM(), nidas::core::MessageStreamScanner::requestBiggerSample(), and nidas::core::SampleScanner::~SampleScanner().
char* nidas::core::SampleScanner::_outSampDataPtr protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), nidas::core::MessageStreamScanner::nextSampleSepEOM(), and nidas::core::MessageStreamScanner::requestBiggerSample().
unsigned int nidas::core::SampleScanner::_outSampRead protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample(), nidas::core::MessageStreamScanner::nextSampleByLength(), nidas::core::MessageStreamScanner::nextSampleSepBOM(), nidas::core::MessageStreamScanner::nextSampleSepEOM(), and nidas::core::MessageStreamScanner::requestBiggerSample().
unsigned int nidas::core::SampleScanner::_outSampToRead protected inherited
Referenced by nidas::core::DriverSampleScanner::nextSample().
char* nidas::core::SampleScanner::_separator protected inherited
messageSeparator in a C string.
Referenced by nidas::core::MessageStreamScanner::nextSampleSepBOM(), nidas::core::MessageStreamScanner::nextSampleSepEOM(), and nidas::core::SampleScanner::~SampleScanner().
bool nidas::core::SampleScanner::_separatorAtEOM protected inherited
Referenced by getMessageSeparatorAtEOM(), and nidas::core::MessageStreamScanner::getMessageSeparatorAtEOM().
int nidas::core::SampleScanner::_separatorLen protected inherited
Length of messageSeparator.
Referenced by nidas::core::MessageStreamScanner::nextSampleSepBOM(), and nidas::core::MessageStreamScanner::nextSampleSepEOM().
const unsigned int nidas::core::SampleScanner::BUFSIZE protected inherited
Buffer size for reading from sensor.
The documentation for this class was generated from the following files:
nidas/core/SampleScanner.h
nidas/core/SampleScanner.cc