nidas: nidas::core::TCPSocketIODevice Class Reference
nidas::core::TCPSocketIODevice Class Reference
An IODevice consisting of a TCP socket.
#include <TCPSocketIODevice.h>
Public Member Functions
TCPSocketIODevice ()
Create a TCPSocketIODevice.
~TCPSocketIODevice ()
void open (int flags) throw (nidas::util::IOException,nidas::util::InvalidParameterException)
Open the socket, which does a socket connect to the remote address which is parsed from the contents of getName().
int getReadFd () const
The file descriptor used when reading from this SocketIODevice.
int getWriteFd () const
The file descriptor used when writing to this device.
size_t read (void *buf, size_t len) throw (nidas::util::IOException)
Read from the device.
size_t read (void *buf, size_t len, int msecTimeout) throw (nidas::util::IOException)
Read from the device with a timeout in milliseconds.
size_t write (const void *buf, size_t len) throw (nidas::util::IOException)
Write to the device.
void close () throw (nidas::util::IOException)
close the device.
void setTcpNoDelay (bool val) throw (nidas::util::IOException)
bool getTcpNoDelay () throw (nidas::util::IOException)
void setKeepAliveIdleSecs (int val) throw (nidas::util::IOException)
int getKeepAliveIdleSecs () const throw (nidas::util::IOException)
void ioctl (int, void *, size_t) throw (nidas::util::IOException)
virtual void setName (const std::string &val)
Set the device name to be opened for this sensor.
virtual const std::string & getName () const
virtual size_t getBytesAvailable () const throw (nidas::util::IOException)
Return how many bytes are available to read on this IODevice.
Static Public Member Functions
static void parseAddress (const std::string &name, int &addrtype, std::string &hostname, int &port, std::string &bindaddr) throw (nidas::util::ParseException)
Parse the getName() string to extract a socket type, destination address and optional port number.
Protected Member Functions
TCPSocketIODevice (const TCPSocketIODevice &)
No copy.
TCPSocketIODevice & operator= (const TCPSocketIODevice &)
No assignment.
Protected Attributes
nidas::util::Socket * _socket
The socket.
bool _tcpNoDelay
int _keepAliveIdleSecs
int _addrtype
The type of the destination address, AF_INET or AF_UNIX.
std::string _desthost
Destination host name from sensor name.
int _port
Port number that is parsed from sensor name.
nidas::util::auto_ptr
< nidas::util::SocketAddress > _sockAddr
The destination socket address.
std::string _bindAddr
The local bind socket address.
Detailed Description
An IODevice consisting of a TCP socket.
Constructor & Destructor Documentation
TCPSocketIODevice::TCPSocketIODevice ()
Create a TCPSocketIODevice.
No IO operations are performed in the constructor, hence no IOExceptions.
TCPSocketIODevice::~TCPSocketIODevice ()
References close().
nidas::core::TCPSocketIODevice::TCPSocketIODevice (const TCPSocketIODevice &) protected
No copy.
Member Function Documentation
void TCPSocketIODevice::close () throw (nidas::util::IOException) virtual
close the device.
Implements nidas::core::IODevice.
References _socket, nidas::util::Socket::close(), nidas::util::Socket::getFd(), nidas::util::Logger::getInstance(), nidas::core::IODevice::getName(), nidas::util::Logger::log(), and LOG_INFO.
Referenced by ~TCPSocketIODevice().
virtual size_t nidas::core::IODevice::getBytesAvailable () const throw (nidas::util::IOException) inline virtual inherited
Return how many bytes are available to read on this IODevice.
This method is only useful when ioctl FIONREAD is supported on this this IODevice, as for example with a UDP socket. It is not available, and not necessary, on most other devices, like serial ports, TCP sockets, or devices with nidas driver module support, in which case it will return an nidas::util::IOException. It is an optimization for use with UDP sockets, where after select determines that data is available on the socket file descriptor, a read will only read one datagram, even if there are more than one packet available, which would not be optimal if a sensor generated many small packets. Rather than returning back to select, we check if there are more datagrams to read. This is not necessary on other types of IODevices, where it is just a matter of using a big enough buffer to get all (or most) available data after a select.
References err, nidas::core::IODevice::getName(), nidas::core::IODevice::getReadFd(), and nidas::core::IODevice::ioctl().
Referenced by nidas::core::DSMSensor::getBytesAvailable().
int nidas::core::TCPSocketIODevice::getKeepAliveIdleSecs () const throw (nidas::util::IOException) inline
References _keepAliveIdleSecs.
virtual const std::string& nidas::core::IODevice::getName () const inline virtual inherited
References nidas::core::IODevice::_devname.
Referenced by nidas::core::SerialPortIODevice::applyTermios(), close(), nidas::core::UDPSocketIODevice::close(), nidas::core::ServerSocketIODevice::close(), nidas::core::UnixIODevice::close(), nidas::core::IODevice::getBytesAvailable(), nidas::core::SocketIODevice::ioctl(), nidas::core::ServerSocketIODevice::ioctl(), nidas::core::UnixIODevice::ioctl(), nidas::core::SocketIODevice::open(), nidas::core::ServerSocketIODevice::open(), nidas::core::UnixIODevice::open(), nidas::core::UnixIODevice::read(), and nidas::core::UnixIODevice::write().
int nidas::core::TCPSocketIODevice::getReadFd () const inline virtual
The file descriptor used when reading from this SocketIODevice.
Implements nidas::core::IODevice.
References _socket, and nidas::util::Socket::getFd().
bool nidas::core::TCPSocketIODevice::getTcpNoDelay () throw (nidas::util::IOException) inline
References _tcpNoDelay.
int nidas::core::TCPSocketIODevice::getWriteFd () const inline virtual
The file descriptor used when writing to this device.
Implements nidas::core::IODevice.
References _socket, and nidas::util::Socket::getFd().
void nidas::core::SocketIODevice::ioctl (int , void * , size_t) throw (nidas::util::IOException) inline virtual inherited
Implements nidas::core::IODevice.
References nidas::core::IODevice::getName().
void TCPSocketIODevice::open (int flags) throw (nidas::util::IOException, nidas::util::InvalidParameterException) virtual
Open the socket, which does a socket connect to the remote address which is parsed from the contents of getName().
See SocketIODevice::open() and SocketIODevice::parseAddress().
Reimplemented from nidas::core::SocketIODevice.
References nidas::core::SocketIODevice::open().
TCPSocketIODevice& nidas::core::TCPSocketIODevice::operator= (const TCPSocketIODevice &) protected
No assignment.
void SocketIODevice::parseAddress (const std::string & name, int & addrtype, std::string & hostname, int & port, std::string & bindaddr) throw (nidas::util::ParseException) static inherited
Parse the getName() string to extract a socket type, destination address and optional port number.
The syntax of the set/getName() string is: ("inet" | "sock" | "unix" | "blue" | "btspp") ':' address [:port] "inet" or "sock" indicate a TCP or UDP connection for use by derived classes implementing a TCP or UDP socket. The address field should then be a hostname which can be resolved to an IP address, or an IP address in dot notation. A port number is required for TCP/UDP socket connection. "unix" indicates a Unix socket connection, where address is the path name of the unix socket, for process to process communications. The port value is not used by unix sockets.
References port.
Referenced by nidas::dynld::raf::PSI9116_Sensor::open(), nidas::core::SocketIODevice::open(), and nidas::core::ServerSocketIODevice::open().
size_t nidas::core::TCPSocketIODevice::read (void * buf, size_t len) throw (nidas::util::IOException) inline virtual
Read from the device.
Implements nidas::core::IODevice.
References _socket, len, and nidas::util::Socket::recv().
size_t TCPSocketIODevice::read (void * buf, size_t len, int msecTimeout) throw (nidas::util::IOException) virtual
Read from the device with a timeout in milliseconds.
Implements nidas::core::IODevice.
References len.
void nidas::core::TCPSocketIODevice::setKeepAliveIdleSecs (int val) throw (nidas::util::IOException) inline
References _keepAliveIdleSecs.
Referenced by nidas::dynld::raf::PSI9116_Sensor::buildIODevice().
virtual void nidas::core::IODevice::setName (const std::string & val) inline virtual inherited
Set the device name to be opened for this sensor.
References nidas::core::IODevice::_devname.
Referenced by nidas::core::UnixIODevice::UnixIODevice().
void nidas::core::TCPSocketIODevice::setTcpNoDelay (bool val) throw (nidas::util::IOException) inline
References _tcpNoDelay.
Referenced by nidas::dynld::raf::PSI9116_Sensor::buildIODevice().
size_t nidas::core::TCPSocketIODevice::write (const void * buf, size_t len) throw (nidas::util::IOException) inline virtual
Write to the device.
Implements nidas::core::IODevice.
References _socket, len, and nidas::util::Socket::send().
Member Data Documentation
int nidas::core::SocketIODevice::_addrtype protected inherited
The type of the destination address, AF_INET or AF_UNIX.
Referenced by nidas::core::SocketIODevice::open().
std::string nidas::core::SocketIODevice::_bindAddr protected inherited
The local bind socket address.
Referenced by nidas::core::SocketIODevice::open().
std::string nidas::core::SocketIODevice::_desthost protected inherited
Destination host name from sensor name.
Referenced by nidas::core::SocketIODevice::open().
int nidas::core::TCPSocketIODevice::_keepAliveIdleSecs protected
Referenced by getKeepAliveIdleSecs(), and setKeepAliveIdleSecs().
int nidas::core::SocketIODevice::_port protected inherited
Port number that is parsed from sensor name.
For a server socket this is the local port number to listen on. For a remote connection socket this is the remote port number.
Referenced by nidas::core::SocketIODevice::open().
nidas::util::auto_ptr<nidas::util::SocketAddress> nidas::core::SocketIODevice::_sockAddr protected inherited
The destination socket address.
Referenced by nidas::core::SocketIODevice::open().
nidas::util::Socket* nidas::core::TCPSocketIODevice::_socket protected
The socket.
This isn't in an auto_ptr because one must close the socket prior to deleting it. The nidas::util::Socket destructor does not close the file descriptor.
Referenced by close(), getReadFd(), getWriteFd(), read(), and write().
bool nidas::core::TCPSocketIODevice::_tcpNoDelay protected
Referenced by getTcpNoDelay(), and setTcpNoDelay().
The documentation for this class was generated from the following files:
nidas/core/TCPSocketIODevice.h
nidas/core/TCPSocketIODevice.cc