nidas: nidas::core::SampleTag Class Reference
nidas::core::SampleTag Class Reference
Class describing a group of variables that are sampled and handled together.
#include <SampleTag.h>
Public Member Functions
SampleTag ()
Constructor.
SampleTag (const DSMSensor *sensor)
Constructor of a sample for a given sensor.
SampleTag (const SampleTag &)
Copy constructor.
virtual ~SampleTag ()
SampleTag & operator= (const SampleTag &rhs)
void setSampleId (unsigned int val)
Set the sample portion of the shortId.
unsigned int getSampleId () const
Get the sample portion of the shortId.
void setSensorId (unsigned int val)
Set the sensor portion of the shortId.
unsigned int getSensorId () const
Get the sensor portion of the shortId.
void setDSMId (unsigned int val)
Set the DSM portion of the id.
unsigned int getDSMId () const
Get the DSM portion of the id.
dsm_sample_id_t getId () const
Get the 26 bit id, containing the DSM id and the sensor+sample id.
unsigned int getSpSId () const
Get the sensor+sample portion of the id.
const std::string & getSuffix () const
Suffix, which is appended to variable names.
void setSuffix (const std::string &val)
const DSMConfig * getDSMConfig () const
void setDSMConfig (const DSMConfig *val)
const DSMSensor * getDSMSensor () const
void setDSMSensor (const DSMSensor *val)
int getStation () const
Station number, which is also known as the Site number.
void setStation (int val)
const Site * getSite () const
Get the Site of this SampleTag, which will be non-NULL only if getDSMConfig() returns non-NULL.
virtual void setRate (double val) throw (nidas::util::InvalidParameterException)
Set sampling rate in samples/sec.
virtual double getRate () const
Get sampling rate in samples/sec.
virtual void setPeriod (double val) throw (nidas::util::InvalidParameterException)
Set sampling period (1/rate) in sec.
virtual double getPeriod () const
Get sampling period (1/rate) in sec.
void setProcessed (bool val) throw (nidas::util::InvalidParameterException)
Set if this sample is going to be post processed.
bool isProcessed () const
Test to see if this sample is to be post processed.
void setScanfFormat (const std::string &val)
const std::string & getScanfFormat () const
void setPromptString (const std::string &val)
const std::string & getPromptString () const
void setPromptOffset (double val)
double getPromptOffset () const
virtual void addVariable (Variable *var) throw (nidas::util::InvalidParameterException)
Add a variable to this SampleTag.
const std::vector< const
Variable * > & getVariables () const
const std::vector< Variable * > & getVariables ()
void removeVariable (const Variable *var)
Variable & getVariable (int i)
Provide a reference to a variable - allowing one to modify it.
void addParameter (Parameter *val)
Add a parameter to this SampleTag.
const std::list< const
Parameter * > & getParameters () const
const Parameter * getParameter (const std::string &name) const
void setEnabled (bool val)
bool isEnabled () const
unsigned int getDataIndex (const Variable *var) const
What is the index of a Variable into the data of a sample from this SampleTag.
VariableIterator getVariableIterator () const
void fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
void setId (dsm_sample_id_t val)
Set the full id.
void setSpSId (unsigned int val)
Set the sensor + sample portions of the id.
Private Attributes
dsm_sample_id_t _id
unsigned int _sampleId
unsigned int _sensorId
std::string _suffix
int _station
double _rate
bool _processed
const DSMConfig * _dsm
const DSMSensor * _sensor
std::vector< const Variable * > _constVariables
std::vector< Variable * > _variables
std::vector< std::string > _variableNames
std::string _scanfFormat
std::string _promptString
double _promptOffset
std::list< Parameter * > _parameters
List of pointers to Parameters.
std::list< const Parameter * > _constParameters
List of const pointers to Parameters for providing via getParameters().
bool _enabled
Detailed Description
Class describing a group of variables that are sampled and handled together.
A SampleTag has an integer ID. This is the same ID that is associated with Sample objects, allowing software to map between a data sample and the meta-data associated with it.
A SampleTag/Sample ID is a 32-bit value comprised of four parts: 6-bit type_id, 10-bit DSM_id, 16-bit sensor+sample id.
The type id specifies the data type (float, int, double, etc), The type_id is only meaningful in an actual data Sample, and is not accessible in the SampleTag class.
The 26 bits of DSM_id and sensor+sample are known simply as the Id (or full id), and is accessible with the getId() method.
The DSM_id contains the id of the data acquisition system that collected the data, and can be accessed separately from the other fields with getDSMId() and setDSMId().
The 16-bit sensor+sample id is also known as the shortId. To maintain flexibility, the shortId has not been divided further into bit fields of sensor and sample id, but is a sum of the two. This means that you cannot set the shortId without losing track of the sensor and sample ids. For this reason, methods to set the shortId and fullId are protected.
To access the portions of the shortId, use getSensorId(), setSensorId(), getSampleId() and setSampleId().
Example: a DSMSensor has an id of 200, and four associated SampleTags with sample ids of 1,2,3 and 4. Therefore one should do a setSensorId(200) on each of the SampleTags, so that their shortIds become 201,202,203, and 204. The convention is that processed samples have sample ids >= 1. Raw, unprocessed Samples from this sensor have a sample id of 0, and therefore a shortId of 200.
A SampleTag also has a rate attribute, indicating the requested sampling rate for the variables.
Constructor & Destructor Documentation
SampleTag::SampleTag ()
Constructor.
SampleTag::SampleTag (const DSMSensor * sensor)
Constructor of a sample for a given sensor.
References _dsm, _sensor, nidas::core::DSMConfig::getId(), nidas::core::DSMSensor::getId(), setDSMId(), and setSensorId().
SampleTag::SampleTag (const SampleTag & x)
Copy constructor.
References addParameter(), addVariable(), nidas::core::Parameter::clone(), getParameters(), and getVariables().
SampleTag::~SampleTag () virtual
References _parameters, and _variables.
Member Function Documentation
void SampleTag::addParameter (Parameter * val)
Add a parameter to this SampleTag.
SampleTag will then own the pointer and will delete it in its destructor. If a Parameter already exists with the same name, that Parameter will be removed and deleted.
References _constParameters, _parameters, and nidas::core::Parameter::getName().
Referenced by operator=(), and SampleTag().
void SampleTag::addVariable (Variable * var) throw (nidas::util::InvalidParameterException) virtual
Add a variable to this SampleTag.
SampleTag will own the Variable, and will delete it in its destructor.
Referenced by nidas::core::SampleAverager::addVariable(), nidas::dynld::isff::WisardMote::createSampleTag(), nidas::core::NearestResampler::ctorCommon(), nidas::core::NearestResamplerAtRate::ctorCommon(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::dynld::StatisticsCruncher::initStats(), Document::insertA2DVariable(), nidas::dynld::raf::SyncRecordSource::layoutSyncRecord(), main(), operator=(), SampleTag(), nidas::dynld::raf::SyncRecordReader::scanHeader(), nidas::dynld::StatisticsCruncher::setupCovariances(), nidas::dynld::StatisticsCruncher::setupFluxes(), nidas::dynld::StatisticsCruncher::setupMinMax(), nidas::dynld::StatisticsCruncher::setupMoments(), nidas::dynld::StatisticsCruncher::setupPrunedTrivariances(), nidas::dynld::StatisticsCruncher::setupReducedFluxes(), nidas::dynld::StatisticsCruncher::setupReducedScalarFluxes(), nidas::dynld::StatisticsCruncher::setupTrivariances(), and nidas::dynld::StatisticsCruncher::setupWindDir().
void SampleTag::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
References nidas::core::Parameter::createParameter(), nidas::core::Project::expandString(), nidas::core::Variable::fromDOMElement(), GET_DSM_ID, GET_SPS_ID, nidas::core::XDOMElement::getAttributeValue(), nidas::core::VariableConverter::getCalFile(), nidas::core::Variable::getConverter(), nidas::core::Project::getInstance(), nidas::core::XDOMAttr::getName(), nidas::core::XDOMElement::getNodeName(), rate, nidas::core::CalFile::setDSMSensor(), nidas::core::Variable::setSampleTag(), nidas::core::Variable::setSite(), and nidas::core::Variable::setStation().
Referenced by nidas::dynld::isff::GOESOutput::fromDOMElement(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), Document::insertA2DVariable(), and Document::updateVariable().
unsigned int SampleTag::getDataIndex (const Variable * var) const
What is the index of a Variable into the data of a sample from this SampleTag.
Returns
UINT_MAX: 'tain't here
References _constVariables.
Referenced by nidas::dynld::StatisticsCruncher::attach(), nidas::core::NearestResampler::connect(), nidas::core::SampleAverager::connect(), and nidas::core::NearestResamplerAtRate::connect().
const DSMConfig* nidas::core::SampleTag::getDSMConfig () const inline
References _dsm.
unsigned int nidas::core::SampleTag::getDSMId () const inline
Get the DSM portion of the id.
References _id, and GET_DSM_ID.
Referenced by nidas::dynld::isff::WisardMote::addMoteSampleTag(), nidas::dynld::StatisticsCruncher::attach(), nidas::dynld::psql::PSQLProcessor::connect(), nidas::dynld::StatisticsProcessor::connect(), nidas::core::NearestResamplerAtRate::connect(), nidas::core::NearestResamplerAtRate::ctorCommon(), nidas::core::DSMSensor::fromDOMElement(), and nidas::dynld::StatisticsCruncher::StatisticsCruncher().
const DSMSensor* nidas::core::SampleTag::getDSMSensor () const inline
References _sensor.
Referenced by nidas::core::SamplePipeline::addSampleClient(), nidas::core::SamplePipeline::connect(), nidas::core::SamplePipeline::disconnect(), nidas::core::VariableConverter::getDSMSensor(), and nidas::core::SamplePipeline::removeSampleClient().
dsm_sample_id_t nidas::core::SampleTag::getId () const inline
Get the 26 bit id, containing the DSM id and the sensor+sample id.
References _id, and GET_FULL_ID.
Referenced by nidas::dynld::isff::WisardMote::addMoteSampleTag(), nidas::dynld::StatisticsCruncher::attach(), nidas::dynld::isff::CSAT3_Sonic::checkSampleTags(), nidas::dynld::isff::SonicAnemometer::checkSampleTags(), nidas::dynld::StatisticsCruncher::computeStats(), nidas::dynld::raf::CVIProcessor::connect(), nidas::dynld::StatisticsProcessor::connect(), nidas::core::SamplePipeline::connect(), nidas::core::NearestResampler::connect(), nidas::core::SampleAverager::connect(), nidas::dynld::StatisticsCruncher::connect(), nidas::core::NearestResamplerAtRate::connect(), nidas::dynld::isff::GOESOutput::connected(), CounterClient::CounterClient(), nidas::core::NearestResampler::ctorCommon(), nidas::core::NearestResamplerAtRate::ctorCommon(), nidas::core::Project::findSensor(), nidas::core::Site::findSensor(), nidas::core::SampleAverager::flush(), nidas::core::NearestResampler::flush(), nidas::dynld::raf::IRIGSensor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::Project::getUniqueSampleId(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::dynld::raf::A2DBoardTempSensor::init(), nidas::dynld::DSC_Event::init(), nidas::dynld::WxtSensor::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::TwoD64_USB::init_parameters(), nidas::dynld::raf::SyncRecordSource::layoutSyncRecord(), nidas::dynld::raf::SortByRateThenLabel::operator()(), nidas::dynld::isff::CU_Coldwire::process(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::A2DSensor::process(), nidas::dynld::isff::CSAT3_Sonic::process(), nidas::dynld::raf::DSMAnalogSensor::process(), nidas::dynld::isff::WisardMote::process(), nidas::dynld::isff::PacketInputStream::readSamples(), TestSource::run(), nidas::dynld::isff::GOESOutput::run(), nidas::dynld::WxtSensor::scanSample(), nidas::dynld::raf::SyncRecordSource::selectVariablesFromSensor(), AutoCalClient::Setup(), nidas::dynld::isff::WisardMote::unpackTsoil(), nidas::dynld::isff::CSI_CRX_Binary::validate(), nidas::dynld::DSC_PulseCounter::validate(), nidas::dynld::DSC_FreqCounter::validate(), Document::validateSampleInfo(), and nidas::core::DSMConfig::validateSensorAndSampleIds().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
const Parameter * SampleTag::getParameter (const std::string & name) const
References _constParameters, and nidas::core::Parameter::getName().
Referenced by Document::insertA2DVariable().
const std::list<const Parameter*>& nidas::core::SampleTag::getParameters () const inline
References _constParameters.
Referenced by operator=(), SampleTag(), and nidas::dynld::DSC_FreqCounter::validate().
virtual double nidas::core::SampleTag::getPeriod () const inline virtual
Get sampling period (1/rate) in sec.
A value of 0.0 means an unknown rate.
References _rate.
Referenced by nidas::dynld::isff::GOESOutput::connected(), and nidas::dynld::isff::GOESOutput::run().
double nidas::core::SampleTag::getPromptOffset () const inline
References _promptOffset.
Referenced by nidas::core::CharacterSensor::validate().
const std::string& nidas::core::SampleTag::getPromptString () const inline
References _promptString.
Referenced by nidas::core::CharacterSensor::validate().
virtual double nidas::core::SampleTag::getRate () const inline virtual
Get sampling rate in samples/sec.
A value of 0.0 means an unknown rate.
References _rate.
Referenced by nidas::dynld::isff::ATIK_Sonic::checkSampleTags(), nidas::dynld::isff::CSAT3_Sonic::checkSampleTags(), nidas::dynld::Twins::fromDOMElement(), nidas::dynld::raf::IRIGSensor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::core::Variable::getSampleRate(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::raf::TwoD64_USB::init_parameters(), Document::insertA2DVariable(), nidas::dynld::raf::SyncRecordSource::layoutSyncRecord(), nidas::dynld::raf::DSMArincSensor::open(), nidas::dynld::raf::SortByRateThenLabel::operator()(), parseAnalog(), parseOther(), nidas::dynld::psql::PSQLSampleOutput::receive(), AutoCalClient::Setup(), nidas::dynld::StatisticsCruncher::StatisticsCruncher(), nidas::dynld::DSC_PulseCounter::validate(), nidas::dynld::DSC_FreqCounter::validate(), and nidas::core::CharacterSensor::validate().
unsigned int nidas::core::SampleTag::getSampleId () const inline
Get the sample portion of the shortId.
References _sampleId.
Referenced by nidas::dynld::raf::CVIProcessor::connect(), nidas::core::SamplePipeline::connect(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::raf::DSMArincSensor::init(), Document::insertA2DVariable(), nidas::dynld::raf::DSMArincSensor::open(), parseAnalog(), parseOther(), SensorItem::removeChild(), A2DSensorItem::removeChild(), PConfig::showAll(), and VariableItem::VariableItem().
const std::string& nidas::core::SampleTag::getScanfFormat () const inline
References _scanfFormat.
Referenced by nidas::core::CharacterSensor::doesAsciiSscanfs(), and nidas::core::CharacterSensor::init().
unsigned int nidas::core::SampleTag::getSensorId () const inline
Get the sensor portion of the shortId.
References _sensorId.
const Site * SampleTag::getSite () const
Get the Site of this SampleTag, which will be non-NULL only if getDSMConfig() returns non-NULL.
References _dsm, and nidas::core::DSMConfig::getSite().
Referenced by Document::insertA2DVariable(), and nidas::core::Variable::setSampleTag().
unsigned int nidas::core::SampleTag::getSpSId () const inline
Get the sensor+sample portion of the id.
References _id, and GET_SPS_ID.
Referenced by nidas::dynld::isff::WisardMote::addMoteSampleTag(), nidas::dynld::StatisticsCruncher::attach(), nidas::dynld::StatisticsProcessor::connect(), nidas::core::NearestResamplerAtRate::connect(), nidas::core::NearestResamplerAtRate::ctorCommon(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::isff::GOESProject::GOESProject(), StatsProcess::listOutputSamples(), nidas::dynld::StatisticsProcessor::selectRequestedSampleTags(), and nidas::dynld::StatisticsCruncher::StatisticsCruncher().
int nidas::core::SampleTag::getStation () const inline
Station number, which is also known as the Site number.
A station number of 0 is the "non" station. Otherwise positive integers are used when a project consists of more than one similar station, where one can differentiate between the variables by a station number (which maps to a station dimension in a NetCDF file). Setting the station on a SampleTag will set the: the station on all its variables.
References _station.
Referenced by nidas::core::Variable::setSampleTag().
const std::string& nidas::core::SampleTag::getSuffix () const inline
Suffix, which is appended to variable names.
References _suffix.
Variable& nidas::core::SampleTag::getVariable (int i) inline
Provide a reference to a variable - allowing one to modify it.
References _variables.
Referenced by nidas::dynld::StatisticsProcessor::connect(), nidas::dynld::StatisticsCruncher::createCombinations(), nidas::dynld::isff::WisardMote::createSampleTags(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::dynld::raf::DSMArincSensor::init(), AutoCalClient::Setup(), nidas::dynld::StatisticsCruncher::setupCovariances(), nidas::dynld::StatisticsCruncher::setupFluxes(), nidas::dynld::StatisticsCruncher::setupMinMax(), nidas::dynld::StatisticsCruncher::setupMoments(), nidas::dynld::StatisticsCruncher::setupPrunedTrivariances(), nidas::dynld::StatisticsCruncher::setupReducedFluxes(), nidas::dynld::StatisticsCruncher::setupReducedScalarFluxes(), nidas::dynld::StatisticsCruncher::setupTrivariances(), and nidas::dynld::isff::WisardMote::unpackTRH().
VariableIterator SampleTag::getVariableIterator () const
Referenced by nidas::dynld::isff::GOESOutput::addSourceSampleTag(), nidas::dynld::StatisticsCruncher::attach(), nidas::dynld::isff::CSI_IRGA_Sonic::checkSampleTags(), nidas::dynld::isff::SonicAnemometer::checkSampleTags(), A2DSensorItem::child(), SensorItem::child(), nidas::dynld::StatisticsProcessor::connect(), nidas::core::NearestResampler::connect(), nidas::core::SampleAverager::connect(), nidas::dynld::StatisticsCruncher::connect(), nidas::core::NearestResamplerAtRate::connect(), nidas::dynld::isff::GOESOutput::connected(), nidas::dynld::StatisticsCruncher::createCombinations(), A2DSensorItem::getA2DTempSuffix(), Document::getAvailableA2DChannels(), nidas::dynld::WxtSensor::init(), parseAnalog(), parseOther(), A2DSensorItem::refreshChildItems(), SensorItem::refreshChildItems(), SensorItem::removeChild(), A2DSensorItem::removeChild(), A2DSensorItem::setNidasA2DTempSuffix(), and PConfig::showAll().
const std::vector< const Variable * > & SampleTag::getVariables () const
References _constVariables.
Referenced by nidas::dynld::isff::ATIK_Sonic::checkSampleTags(), nidas::dynld::isff::CSI_IRGA_Sonic::checkSampleTags(), nidas::dynld::isff::CSAT3_Sonic::checkSampleTags(), nidas::dynld::psql::PSQLProcessor::connect(), nidas::dynld::StatisticsProcessor::connect(), nidas::dynld::isff::GOESOutput::connected(), nidas::dynld::isff::WisardMote::convert(), CounterClient::CounterClient(), nidas::dynld::StatisticsCruncher::createCombinations(), nidas::dynld::isff::WisardMote::createSampleTags(), nidas::dynld::psql::PSQLSampleOutput::createTables(), nidas::dynld::Twins::fromDOMElement(), nidas::dynld::raf::IRIGSensor::fromDOMElement(), nidas::dynld::isff::GOESProject::GOESProject(), nidas::core::VariableIterator::hasNext(), nidas::dynld::raf::UHSAS_Serial::init(), nidas::dynld::DSC_Event::init(), nidas::dynld::WxtSensor::init(), nidas::core::CharacterSensor::init(), nidas::dynld::raf::TwoD_USB::init(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::StatisticsCruncher::initStats(), nidas::dynld::raf::SyncRecordSource::layoutSyncRecord(), StatsProcess::listOutputSamples(), nidas::dynld::raf::DSMArincSensor::open(), operator=(), nidas::dynld::isff::CU_Coldwire::process(), nidas::dynld::isff::CSI_IRGA_Sonic::process(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::A2DSensor::process(), nidas::dynld::isff::CSAT3_Sonic::process(), nidas::dynld::raf::DSMAnalogSensor::process(), nidas::dynld::isff::WisardMote::process(), nidas::dynld::isff::PacketInputStream::readSamples(), nidas::dynld::isff::GOESOutput::run(), SampleTag(), nidas::dynld::raf::SyncRecordSource::selectVariablesFromSensor(), AutoCalClient::Setup(), nidas::dynld::StatisticsCruncher::setupCovariances(), nidas::dynld::StatisticsCruncher::setupFluxes(), nidas::dynld::StatisticsCruncher::setupMinMax(), nidas::dynld::StatisticsCruncher::setupMoments(), nidas::dynld::StatisticsCruncher::setupPrunedTrivariances(), nidas::dynld::StatisticsCruncher::setupReducedFluxes(), nidas::dynld::StatisticsCruncher::setupReducedScalarFluxes(), nidas::dynld::StatisticsCruncher::setupTrivariances(), PConfig::showCalFiles(), nidas::dynld::isff::WisardMote::unpackTsoil(), nidas::dynld::isff::Licor7500::validate(), nidas::dynld::isff::CSI_CRX_Binary::validate(), nidas::dynld::isff::NCAR_TRH::validate(), nidas::dynld::DSC_PulseCounter::validate(), nidas::dynld::DSC_FreqCounter::validate(), nidas::dynld::raf::SppSerial::validate(), nidas::dynld::isff::PropVane::validateSscanfs(), and nidas::core::CharacterSensor::validateSscanfs().
const std::vector<Variable*>& nidas::core::SampleTag::getVariables () inline
References _variables.
bool nidas::core::SampleTag::isEnabled () const inline
References _enabled.
bool nidas::core::SampleTag::isProcessed () const inline
Test to see if this sample is to be post processed.
References _processed.
Referenced by nidas::dynld::psql::PSQLProcessor::connect(), nidas::dynld::raf::DSMArincSensor::init(), nidas::dynld::raf::DSMArincSensor::open(), parseAnalog(), parseOther(), nidas::dynld::raf::SyncRecordSource::selectVariablesFromSensor(), and PConfig::showAll().
SampleTag & SampleTag::operator= (const SampleTag & rhs)
References _dsm, _enabled, _id, _processed, _promptOffset, _promptString, _rate, _sampleId, _scanfFormat, _sensor, _sensorId, _station, _suffix, addParameter(), addVariable(), nidas::core::Parameter::clone(), getParameters(), and getVariables().
void SampleTag::removeVariable (const Variable * var)
References _constVariables, _variables, and nidas::core::Variable::getName().
Referenced by Document::insertA2DVariable(), SensorItem::removeChild(), and A2DSensorItem::removeChild().
void nidas::core::SampleTag::setDSMConfig (const DSMConfig * val) inline
References _dsm.
Referenced by nidas::core::DSMSensor::fromDOMElement().
void nidas::core::SampleTag::setDSMId (unsigned int val) inline
Set the DSM portion of the id.
References _id, and SET_DSM_ID.
Referenced by nidas::dynld::StatisticsProcessor::connect(), nidas::core::NearestResampler::ctorCommon(), nidas::core::NearestResamplerAtRate::ctorCommon(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::isff::GOESProject::GOESProject(), Document::insertA2DVariable(), main(), SampleTag(), nidas::dynld::StatisticsCruncher::StatisticsCruncher(), and nidas::dynld::raf::SyncRecordSource::SyncRecordSource().
void SampleTag::setDSMSensor (const DSMSensor * val)
References _dsm, _sensor, and nidas::core::DSMSensor::getDSMConfig().
Referenced by nidas::core::DSMSensor::fromDOMElement().
void nidas::core::SampleTag::setEnabled (bool val) inline
References _enabled.
void nidas::core::SampleTag::setId (dsm_sample_id_t val) inline protected
Set the full id.
We don't make this public, because when you use it you can't keep track of the sensor and sample portions of the shortID.
References _id, and SET_FULL_ID.
virtual void nidas::core::SampleTag::setPeriod (double val) throw (nidas::util::InvalidParameterException) inline virtual
Set sampling period (1/rate) in sec.
A value of 0.0 means an unknown period.
References _rate.
Referenced by nidas::dynld::isff::GOESProject::GOESProject().
void nidas::core::SampleTag::setProcessed (bool val) throw (nidas::util::InvalidParameterException) inline
Set if this sample is going to be post processed.
References _processed.
void nidas::core::SampleTag::setPromptOffset (double val) inline
References _promptOffset.
void nidas::core::SampleTag::setPromptString (const std::string & val) inline
References _promptString.
virtual void nidas::core::SampleTag::setRate (double val) throw (nidas::util::InvalidParameterException) inline virtual
Set sampling rate in samples/sec.
Derived SampleTags can override this method and throw an InvalidParameterException if they can't support the rate value. Sometimes a rate of 0.0 may mean don't sample the variables in the SampleTag.
References _rate.
Referenced by nidas::dynld::raf::IRIGSensor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), main(), DataPrep::run(), nidas::dynld::raf::SyncRecordReader::scanHeader(), nidas::core::SampleAverager::setAveragePeriodSecs(), nidas::dynld::StatisticsCruncher::StatisticsCruncher(), nidas::dynld::raf::SyncRecordSource::SyncRecordSource(), and nidas::core::CharacterSensor::validate().
void nidas::core::SampleTag::setSampleId (unsigned int val) inline
Set the sample portion of the shortId.
References _id, _sampleId, _sensorId, and SET_SPS_ID.
Referenced by nidas::dynld::isff::WisardMote::createSampleTag(), nidas::dynld::isff::WisardMote::createSampleTags(), nidas::core::NearestResampler::ctorCommon(), nidas::core::NearestResamplerAtRate::ctorCommon(), nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), nidas::dynld::isff::GOESProject::GOESProject(), main(), nidas::core::SampleAverager::SampleAverager(), nidas::dynld::StatisticsCruncher::StatisticsCruncher(), and nidas::dynld::raf::SyncRecordSource::SyncRecordSource().
void nidas::core::SampleTag::setScanfFormat (const std::string & val) inline
References _scanfFormat.
void nidas::core::SampleTag::setSensorId (unsigned int val) inline
Set the sensor portion of the shortId.
References _id, _sampleId, _sensorId, and SET_SPS_ID.
Referenced by nidas::core::SampleIOProcessor::fromDOMElement(), nidas::core::DSMSensor::fromDOMElement(), Document::insertA2DVariable(), main(), SampleTag(), and nidas::dynld::raf::SyncRecordSource::SyncRecordSource().
void nidas::core::SampleTag::setSpSId (unsigned int val) inline protected
Set the sensor + sample portions of the id.
We don't make this public, because when you use it you can't keep track of the sensor and sample portions of the shortID.
References _id, and SET_SPS_ID.
void SampleTag::setStation (int val)
References _station, _variables, and nidas::core::Variable::setStation().
Referenced by nidas::core::DSMSensor::fromDOMElement(), and nidas::core::DSMSensor::setStation().
void SampleTag::setSuffix (const std::string & val)
References _suffix, _variables, and nidas::core::Variable::setSuffix().
Referenced by nidas::core::DSMSensor::fromDOMElement().
xercesc::DOMElement * SampleTag::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual
Add my content into a DOMElement.
Reimplemented from nidas::core::DOMable.
References nidas::core::VariableIterator::hasNext(), nidas::core::XDOMElement::setAttributeValue(), and nidas::core::Variable::toDOMParent().
xercesc::DOMElement * SampleTag::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual
Create a DOMElement and append it to the parent.
Reimplemented from nidas::core::DOMable.
References nidas::core::DOMable::getNamespaceURI().
Referenced by nidas::core::DSMSensor::toDOMParent().
Member Data Documentation
std::list<const Parameter*> nidas::core::SampleTag::_constParameters private
List of const pointers to Parameters for providing via getParameters().
Referenced by addParameter(), getParameter(), and getParameters().
std::vector<const Variable*> nidas::core::SampleTag::_constVariables private
Referenced by getDataIndex(), getVariables(), and removeVariable().
const DSMConfig* nidas::core::SampleTag::_dsm private
Referenced by getDSMConfig(), getSite(), operator=(), SampleTag(), setDSMConfig(), and setDSMSensor().
bool nidas::core::SampleTag::_enabled private
Referenced by isEnabled(), operator=(), and setEnabled().
dsm_sample_id_t nidas::core::SampleTag::_id private
Referenced by getDSMId(), getId(), getSpSId(), operator=(), setDSMId(), setId(), setSampleId(), setSensorId(), and setSpSId().
std::list<Parameter*> nidas::core::SampleTag::_parameters private
List of pointers to Parameters.
Referenced by addParameter(), and ~SampleTag().
bool nidas::core::SampleTag::_processed private
Referenced by isProcessed(), operator=(), and setProcessed().
double nidas::core::SampleTag::_promptOffset private
Referenced by getPromptOffset(), operator=(), and setPromptOffset().
std::string nidas::core::SampleTag::_promptString private
Referenced by getPromptString(), operator=(), and setPromptString().
double nidas::core::SampleTag::_rate private
Referenced by getPeriod(), getRate(), operator=(), setPeriod(), and setRate().
unsigned int nidas::core::SampleTag::_sampleId private
Referenced by getSampleId(), operator=(), setSampleId(), and setSensorId().
std::string nidas::core::SampleTag::_scanfFormat private
Referenced by getScanfFormat(), operator=(), and setScanfFormat().
const DSMSensor* nidas::core::SampleTag::_sensor private
Referenced by getDSMSensor(), operator=(), SampleTag(), and setDSMSensor().
unsigned int nidas::core::SampleTag::_sensorId private
Referenced by getSensorId(), operator=(), setSampleId(), and setSensorId().
int nidas::core::SampleTag::_station private
Referenced by getStation(), operator=(), and setStation().
std::string nidas::core::SampleTag::_suffix private
Referenced by getSuffix(), operator=(), and setSuffix().
std::vector<std::string> nidas::core::SampleTag::_variableNames private
std::vector<Variable*> nidas::core::SampleTag::_variables private
Referenced by getVariable(), getVariables(), removeVariable(), setStation(), setSuffix(), and ~SampleTag().
The documentation for this class was generated from the following files:
nidas/core/SampleTag.h
nidas/core/SampleTag.cc