nidas: nidas::util::LogScheme Class Reference
nidas::util::LogScheme Class Reference
Logging
A LogScheme is a vector of LogConfig's and the vector of fields to show in log messages.
#include <Logger.h>
Public Types
enum LogField {
NoneField = 0, ThreadField = 1, FunctionField = 2, FileField = 4,
LevelField = 8, MessageField = 16, TimeField = 32, AllFields = 63
}
typedef std::vector< LogConfig > log_configs_v
The type for the vector of LogConfigs returned by getConfigs().
Public Member Functions
LogScheme (const std::string &name="default")
The default LogScheme has show fields set to "time,level,message" and a single LogConfig to enable all messages with level LOGGER_WARNING and above.
LogScheme & setName (const std::string &name)
LogScheme names must not be empty, so this method has no effect unless name.length() > 0.
const std::string & getName () const
LogScheme & clearConfigs ()
Clear the set of LogConfig's in this scheme.
LogScheme & addConfig (const LogConfig &lc)
Push a new LogConfig onto the list of existing configs.
log_configs_v getConfigs ()
Return a copy of the LogConfig instances added to this LogScheme.
int logLevel ()
Return the highest level of log messages enabled in all the LogConfig instances added to this LogScheme.
LogScheme & setShowFields (const std::vector< LogField > &fields)
Set the fields to show in log messages and their order.
LogScheme & setShowFields (const std::string &fields)
Parse a comma-separated string of field names, with no spaces, into a vector of LogField values, and pass that to setShowFields().
std::string getShowFieldsString () const
Return a comma-separated string describing the list of fields to be shown by this scheme.
bool parseParameter (const std::string &text)
Parse a parameter setting using syntax <name>=.
void setParameter (const std::string &name, const std::string &value)
Set a parameter for this scheme.
std::string getParameter (const std::string &name, const std::string &dvalue="")
Return the value of the parameter.
template<typename T >
T getParameterT (const std::string &name, const T &dvalue=T())
std::string getEnvParameter (const std::string &name, const std::string &dvalue="")
Return the value of the parameter.
void showLogPoints (bool show)
If show is true, then all the known log points will be listed in log messages, and all future log points will be logged as they are created.
bool getShowLogPoints ()
Return true if showLogPoints() is enabled.
Static Public Member Functions
static LogField stringToField (const std::string &s)
Convert the name of a log information field to its enum, such as Logger::ThreadField.
static std::string fieldToString (LogScheme::LogField lf)
Convert a LogField to its lower-case string name.
static LogScheme current ()
Return the LogScheme currently in effect for the global Logger instance.
Private Member Functions
void show_log_point (LogContext &lp)
Private Attributes
std::string _name
log_configs_v log_configs
std::vector< LogField > log_fields
std::map< std::string,
std::string > _parameters
bool _showlogpoints
Friends
class nidas::util::LoggerPrivate
class nidas::util::Logger
class nidas::util::LogContext
Detailed Description
A LogScheme is a vector of LogConfig's and the vector of fields to show in log messages.
Member Typedef Documentation
typedef std::vector<LogConfig> nidas::util::LogScheme::log_configs_v
The type for the vector of LogConfigs returned by getConfigs().
Member Enumeration Documentation
enum nidas::util::LogScheme::LogField
Enumerator
NoneField
ThreadField
FunctionField
FileField
LevelField
MessageField
TimeField
AllFields
Constructor & Destructor Documentation
LogScheme::LogScheme (const std::string & name = "default") explicit
The default LogScheme has show fields set to "time,level,message" and a single LogConfig to enable all messages with level LOGGER_WARNING and above.
The default name is "default". Explicitly passing an empty name will also force a name of "default", since a LogScheme is prohibited from having an empty name.
Initially a LogScheme has no LogConfig entries, and so a default scheme does not enable any log messages,
References _name, and setShowFields().
Member Function Documentation
LogScheme & LogScheme::addConfig (const LogConfig & lc)
Push a new LogConfig onto the list of existing configs.
This config will be applied to any log points which it matches. For example, if the activate flag of this config is false, then any matching log points will be disabled. The configurations are cumulative, so the latest config on the list will take precedence. For example, if an earlier config enables all points, then further configs can disable a subset of log points.
Parameters
lc The LogConfig to be added to this scheme.
Returns
This scheme.
References log_configs.
Referenced by nidas::core::DSMServerApp::initLogger(), nidas::core::DSMEngine::initLogger(), LogSchemeFromDOMElement(), main(), StatsProcess::main(), nidas::core::NidasApp::NidasApp(), nidas::core::NidasApp::parseLogConfig(), nidas::core::NidasApp::resetLogging(), TeeTTy::run(), and TeeI2C::run().
LogScheme & LogScheme::clearConfigs ()
Clear the set of LogConfig's in this scheme.
An empty set of LogConfig's disables all logging for this scheme.
References log_configs.
Referenced by main().
LogScheme LogScheme::current () static
Return the LogScheme currently in effect for the global Logger instance.
References nidas::util::Logger::getInstance(), and nidas::util::Logger::getScheme().
Referenced by nidas::core::SampleSorter::SampleSorter().
std::string LogScheme::fieldToString (LogScheme::LogField lf) static
Convert a LogField to its lower-case string name.
Returns "none" if the LogField is NoneField or invalid.
Referenced by getShowFieldsString().
LogScheme::log_configs_v LogScheme::getConfigs ()
Return a copy of the LogConfig instances added to this LogScheme.
References log_configs.
std::string LogScheme::getEnvParameter (const std::string & name, const std::string & dvalue = "")
Return the value of the parameter.
If the parameter has not been set, then look for a value in the environment, and otherwise return the default.
References _parameters.
const std::string& nidas::util::LogScheme::getName () const inline
References _name.
Referenced by nidas::core::Project::fromDOMElement(), nidas::core::NidasApp::NidasApp(), nidas::util::LoggerPrivate::reconfig(), nidas::util::Logger::setScheme(), and nidas::util::Logger::updateScheme().
std::string LogScheme::getParameter (const std::string & name, const std::string & dvalue = "")
Return the value of the parameter.
If the parameter has not been set, then return the default.
References _parameters.
Referenced by getParameterT(), and nidas::core::SampleTracer::SampleTracer().
std::string LogScheme::getShowFieldsString () const
Return a comma-separated string describing the list of fields to be shown by this scheme.
References fieldToString(), and log_fields.
Referenced by nidas::util::LoggerPrivate::reconfig().
bool nidas::util::LogScheme::getShowLogPoints () inline
Return true if showLogPoints() is enabled.
References _showlogpoints.
Referenced by nidas::util::LogContext::LogContext().
int LogScheme::logLevel ()
Return the highest level of log messages enabled in all the LogConfig instances added to this LogScheme.
For basic configurations, where a single LogConfig just enables all messages of a certain level, this method returns that level. In more complicated configurations, there may be only a few log messages enabled at the returned level, but there will be no messages enabled at a higher level.
Since a LogScheme with no configs enables no messages, it returns LOGGER_NONE.
References nidas::util::LoggerPrivate::DEFAULT_LOGLEVEL, log_configs, and nidas::util::LOGGER_NONE.
Referenced by nidas::core::NidasApp::logLevel().
bool LogScheme::parseParameter (const std::string & text)
Parse a parameter setting using syntax <name>=.
References setParameter().
Referenced by nidas::core::NidasApp::parseArguments().
LogScheme& nidas::util::LogScheme::setName (const std::string & name) inline
LogScheme names must not be empty, so this method has no effect unless name.length() > 0.
References _name.
Referenced by LogSchemeFromDOMElement().
void LogScheme::setParameter (const std::string & name, const std::string & value)
Set a parameter for this scheme.
References _parameters.
Referenced by parseParameter().
LogScheme & LogScheme::setShowFields (const std::vector< LogField > & fields)
Set the fields to show in log messages and their order.
The fields in fields will be shown in the same order as in the vector. Any fields not included will be omitted.
Parameters
fields A vector<LogField>.
References log_fields.
Referenced by nidas::core::DSMServerApp::initLogger(), nidas::core::DSMEngine::initLogger(), LogScheme(), LogSchemeFromDOMElement(), StatsProcess::main(), main(), nidas::core::NidasApp::parseArguments(), parseRunstring(), and setShowFields().
LogScheme & LogScheme::setShowFields (const std::string & fields)
Parse a comma-separated string of field names, with no spaces, into a vector of LogField values, and pass that to setShowFields().
Valid fields: thread,function,file,level,time,message
References setShowFields(), and stringToField().
void LogScheme::show_log_point (LogContext & lp) private
References nidas::util::LogContext::active(), nidas::util::LogContext::filename(), nidas::util::LogContext::function(), nidas::util::Logger::getInstance(), nidas::util::LogContext::levelName(), nidas::util::LogContext::line(), nidas::util::Logger::msg_locked(), show_point, and nidas::util::LogContext::tags().
Referenced by nidas::util::LogContext::LogContext(), and showLogPoints().
void LogScheme::showLogPoints (bool show)
If show is true, then all the known log points will be listed in log messages, and all future log points will be logged as they are created.
Disable this logging by passing false.
References _showlogpoints, log_points, nidas::util::Logger::mutex, and show_log_point().
Referenced by nidas::core::NidasApp::parseArguments().
LogScheme::LogField LogScheme::stringToField (const std::string & s) static
Convert the name of a log information field to its enum, such as Logger::ThreadField.
Returns NoneField if the name is not recognized.
References NoneField.
Referenced by setShowFields().
Friends And Related Function Documentation
friend class nidas::util::LogContext friend
friend class nidas::util::Logger friend
friend class nidas::util::LoggerPrivate friend
Member Data Documentation
std::string nidas::util::LogScheme::_name private
Referenced by getName(), LogScheme(), and setName().
std::map<std::string, std::string> nidas::util::LogScheme::_parameters private
Referenced by getEnvParameter(), getParameter(), and setParameter().
bool nidas::util::LogScheme::_showlogpoints private
Referenced by getShowLogPoints(), and showLogPoints().
log_configs_v nidas::util::LogScheme::log_configs private
Referenced by addConfig(), clearConfigs(), nidas::util::LoggerPrivate::get_active_flag(), getConfigs(), logLevel(), and nidas::util::LoggerPrivate::reconfig().
std::vector<LogField> nidas::util::LogScheme::log_fields private
Referenced by getShowFieldsString(), nidas::util::Logger::msg_locked(), and setShowFields().
The documentation for this class was generated from the following files:
nidas/util/Logger.h
nidas/util/Logger.cc