nidas: ublox_pkt Class Reference
ublox_pkt Class Reference
Public Member Functions
ublox_pkt (uint8_t uclass, uint8_t id, uint16_t paylen)
ublox_pkt (uint16_t paylen)
~ublox_pkt ()
uint8_t sync1 () const
uint8_t sync2 () const
uint8_t uclass () const
uint8_t id () const
uint8_t * payload () const
void payload (void *ptr)
int16_t len () const
char * beginp () const
char * endp () const
int16_t paylen () const
uint8_t * cksump () const
void cksum ()
Private Member Functions
ublox_pkt (const ublox_pkt &)
ublox_pkt & operator= (const ublox_pkt &)
Private Attributes
int16_t _paylen
uint8_t * _pkt
Constructor & Destructor Documentation
ublox_pkt::ublox_pkt (uint8_t uclass, uint8_t id, uint16_t paylen)
References _paylen, _pkt, id(), len(), and uclass().
ublox_pkt::ublox_pkt (uint16_t paylen)
References _pkt, and len().
ublox_pkt::~ublox_pkt ()
References _pkt.
ublox_pkt::ublox_pkt (const ublox_pkt &) private
Member Function Documentation
char* ublox_pkt::beginp () const inline
Referenced by ublox::write_rdwr().
void ublox_pkt::cksum ()
References _pkt, and cksump().
Referenced by ublox::config_nmea(), ublox::config_nmea_all_targets(), ublox::config_port(), ublox::reset(), and ublox::set_rate().
uint8_t* ublox_pkt::cksump () const inline
Referenced by cksum().
char* ublox_pkt::endp () const inline
References len.
uint8_t ublox_pkt::id () const inline
Referenced by ublox_pkt(), and ublox::write_rdwr().
int16_t ublox_pkt::len () const inline
Referenced by ublox_pkt(), and ublox::write_rdwr().
ublox_pkt& ublox_pkt::operator= (const ublox_pkt &) private
int16_t ublox_pkt::paylen () const inline
uint8_t* ublox_pkt::payload () const inline
Referenced by ublox::config_nmea(), ublox::config_nmea_all_targets(), ublox::config_port(), ublox::reset(), ublox::set_rate(), and ublox::write_rdwr().
void ublox_pkt::payload (void * ptr) inline
References payload().
Referenced by payload().
uint8_t ublox_pkt::sync1 () const inline
Referenced by ublox::write_rdwr().
uint8_t ublox_pkt::sync2 () const inline
Referenced by ublox::write_rdwr().
uint8_t ublox_pkt::uclass () const inline
Referenced by ublox_pkt(), and ublox::write_rdwr().
Member Data Documentation
int16_t ublox_pkt::_paylen private
Referenced by ublox_pkt().
uint8_t* ublox_pkt::_pkt private
Referenced by cksum(), ublox_pkt(), and ~ublox_pkt().
The documentation for this class was generated from the following file:
nidas/apps/ublox.cc