nidas: nidas::dynld::RawSampleInputStream Class Reference
nidas::dynld::RawSampleInputStream Class Reference
#include <RawSampleInputStream.h>
Public Member Functions
RawSampleInputStream ()
Default constructor.
RawSampleInputStream (nidas::core::IOChannel *iochannel)
Constructor with a connected IOChannel.
RawSampleInputStream * clone (nidas::core::IOChannel *)
Create a copy with a different, connected IOChannel.
virtual ~RawSampleInputStream ()
void fromDOMElement (const xercesc::DOMElement *node) throw (nidas::util::InvalidParameterException)
Initialize myself from a xercesc::DOMElement.
std::string getName () const
int getFd () const
virtual void setIOChannel (nidas::core::IOChannel *val)
Set the IOChannel for this SampleInputStream.h.
void readInputHeader () throw (nidas::util::IOException)
Read archive information at beginning of input stream or file.
bool parseInputHeader () throw (nidas::util::IOException)
const
nidas::core::SampleInputHeader & getInputHeader () const
void requestConnection (nidas::core::DSMService *) throw (nidas::util::IOException)
virtual nidas::core::SampleInput * getOriginal () const
nidas::core::SampleInput * connected (nidas::core::IOChannel *iochan) throw ()
Implementation of IOChannelRequester::connected.
void setNonBlocking (bool val) throw (nidas::util::IOException)
bool isNonBlocking () const throw (nidas::util::IOException)
const nidas::core::DSMConfig * getDSMConfig () const
What DSM am I connnected to? May be NULL if it cannot be determined.
void setKeepStats (bool val)
void addSampleTag (const nidas::core::SampleTag *tag) throw ()
Implementation of SampleInput::addSampleTag().
void removeSampleTag (const nidas::core::SampleTag *tag) throw ()
nidas::core::SampleSource * getRawSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
nidas::core::SampleSource * getProcessedSampleSource ()
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
std::list< const
nidas::core::SampleTag * > getSampleTags () const
Get the output SampleTags.
nidas::core::SampleTagIterator getSampleTagIterator () const
Implementation of SampleSource::getSampleTagIterator().
void addSampleClient (nidas::core::SampleClient *client) throw ()
Implementation of SampleSource::addSampleClient().
void removeSampleClient (nidas::core::SampleClient *client) throw ()
Remove a SampleClient from this SampleSource.
void addSampleClientForTag (nidas::core::SampleClient *client, const nidas::core::SampleTag *tag) throw ()
Add a Client for a given SampleTag.
void removeSampleClientForTag (nidas::core::SampleClient *client, const nidas::core::SampleTag *tag) throw ()
Remove a SampleClient for a given SampleTag from this SampleSource.
int getClientCount () const throw ()
How many SampleClients are currently in my list.
void flush () throw ()
Implementation of SampleSource::flush(), unpacks and distributes any samples currently in the read buffer.
const nidas::core::SampleStats & getSampleStats () const
bool readSamples () throw (nidas::util::IOException)
Read a buffer of data, serialize the data into samples, and distribute() samples to the receive() method of my SampleClients and DSMSensors.
void search (const nidas::util::UTime &tt) throw (nidas::util::IOException)
Search forward until a sample header is read whose time is greater than or equal to tt.
nidas::core::Sample * readSample () throw (nidas::util::IOException)
Read the next sample from the InputStream.
void distribute (const nidas::core::Sample *s) throw ()
Distribute a sample to my clients.
size_t getBadSamples () const
void close () throw (nidas::util::IOException)
void newFile () throw (nidas::util::IOException)
void setFilterBadSamples (bool val)
void setMaxDsmId (int val)
void setMaxSampleLength (unsigned int val)
void setMinSampleTime (const nidas::util::UTime &val)
void setMaxSampleTime (const nidas::util::UTime &val)
void setExpectHeader (bool val)
bool getExpectHeader () const
virtual xercesc::DOMElement * toDOMParent (xercesc::DOMElement *parent, bool complete) const throw (xercesc::DOMException)
Create a DOMElement and append it to the parent.
virtual xercesc::DOMElement * toDOMElement (xercesc::DOMElement *node, bool complete) const throw (xercesc::DOMException)
Add my content into a DOMElement.
Static Public Member Functions
static const XMLCh * getNamespaceURI ()
Protected Member Functions
RawSampleInputStream (RawSampleInputStream &x, nidas::core::IOChannel *)
Create a copy, but with a new IOChannel.
Protected Attributes
nidas::core::IOChannel * _iochan
nidas::core::SampleSourceSupport _source
Constructor & Destructor Documentation
RawSampleInputStream::RawSampleInputStream ()
Default constructor.
Referenced by clone().
RawSampleInputStream::RawSampleInputStream (nidas::core::IOChannel * iochannel)
Constructor with a connected IOChannel.
Parameters
iochannel The IOChannel that we use for data input. RawSampleInputStream will own the pointer to the IOChannel, and will delete it in ~RawSampleInputStream().
RawSampleInputStream::~RawSampleInputStream () virtual
RawSampleInputStream::RawSampleInputStream (RawSampleInputStream & x, nidas::core::IOChannel * iochannel) protected
Create a copy, but with a new IOChannel.
Member Function Documentation
void nidas::dynld::SampleInputStream::addSampleClient (nidas::core::SampleClient * client) throw () inline virtual inherited
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::addSampleClient().
Referenced by DataStats::run().
void nidas::dynld::SampleInputStream::addSampleClientForTag (nidas::core::SampleClient * client, const nidas::core::SampleTag * tag) throw () inline virtual inherited
Add a Client for a given SampleTag.
Implementation of SampleSource::addSampleClient().
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::addSampleClientForTag().
void nidas::dynld::SampleInputStream::addSampleTag (const nidas::core::SampleTag * tag) throw () inline virtual inherited
Implementation of SampleInput::addSampleTag().
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::addSampleTag().
Referenced by nidas::dynld::raf::SyncServer::initSensors(), StatsProcess::run(), DataPrep::run(), and DataStats::run().
RawSampleInputStream * RawSampleInputStream::clone (nidas::core::IOChannel * iochannel) virtual
Create a copy with a different, connected IOChannel.
Create a clone, with a new, connected IOChannel.
Reimplemented from nidas::dynld::SampleInputStream.
References RawSampleInputStream().
void SampleInputStream::close () throw (nidas::util::IOException) virtual inherited
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_iochan, nidas::dynld::SampleInputStream::_iostream, and nidas::core::IOChannel::close().
Referenced by StatsProcess::run(), Calibrator::run(), DataPrep::run(), DataStats::run(), and nidas::dynld::raf::SyncServer::stop().
SampleInput * SampleInputStream::connected (nidas::core::IOChannel * iochan) throw () virtual inherited
Implementation of IOChannelRequester::connected.
One can use this method to notify SampleInputStream that the IOChannel is connected, which will cause SampleInputStream to open the IOStream.
Implements nidas::core::IOChannelRequester.
void nidas::dynld::SampleInputStream::distribute (const nidas::core::Sample * s) throw () inline inherited
Distribute a sample to my clients.
One could use this to insert a sample into the stream.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::distribute().
Referenced by nidas::dynld::raf::SyncServer::handleSample().
void SampleInputStream::flush () throw () virtual inherited
Implementation of SampleSource::flush(), unpacks and distributes any samples currently in the read buffer.
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, nidas::core::SampleSourceSupport::distribute(), nidas::core::SampleSourceSupport::getClientCount(), nidas::dynld::SampleInputStream::getName(), and nidas::dynld::SampleInputStream::nextSample().
void RawSampleInputStream::fromDOMElement (const xercesc::DOMElement *) throw (nidas::util::InvalidParameterException) virtual
Initialize myself from a xercesc::DOMElement.
Implements nidas::core::DOMable.
References nidas::dynld::SampleInputStream::fromDOMElement(), and nidas::core::RAW_SAMPLE.
size_t nidas::dynld::SampleInputStream::getBadSamples () const inline inherited
References nidas::dynld::SampleInputStream::_badSamples.
int nidas::dynld::SampleInputStream::getClientCount () const throw () inline virtual inherited
How many SampleClients are currently in my list.
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::getClientCount().
const DSMConfig * SampleInputStream::getDSMConfig () const virtual inherited
What DSM am I connnected to? May be NULL if it cannot be determined.
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_dsm.
bool nidas::dynld::SampleInputStream::getExpectHeader () const inline inherited
References nidas::dynld::SampleInputStream::_expectHeader.
int SampleInputStream::getFd () const virtual inherited
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_iochan, and nidas::core::IOChannel::getFd().
const nidas::core::SampleInputHeader& nidas::dynld::SampleInputStream::getInputHeader () const inline inherited
References nidas::dynld::SampleInputStream::_inputHeader.
Referenced by nidas::dynld::raf::SyncRecordReader::init(), nidas::dynld::raf::SyncServer::openStream(), NidsMerge::run(), SensorExtract::run(), StatsProcess::run(), DataPrep::run(), Extract2D::run(), and DataStats::run().
string SampleInputStream::getName () const virtual inherited
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_iochan, and nidas::core::IOChannel::getName().
Referenced by nidas::dynld::SampleInputStream::flush(), nidas::dynld::SampleInputStream::parseInputHeader(), MergeVerifier::reportBackward(), MergeVerifier::reportDuplicate(), MergeVerifier::reportMissing(), and MergeVerifier::run().
static const XMLCh* nidas::core::DOMable::getNamespaceURI () inline static inherited
References nidas::core::DOMable::namespaceURI.
Referenced by nidas::dynld::UDPSampleOutput::getProjectDOM(), nidas::core::Dataset::toDOMElement(), nidas::core::ProjectConfig::toDOMElement(), nidas::core::Dataset::toDOMParent(), nidas::core::ProjectConfig::toDOMParent(), nidas::core::Datasets::toDOMParent(), nidas::core::ProjectConfigs::toDOMParent(), nidas::core::DSMConfig::toDOMParent(), nidas::core::Project::toDOMParent(), nidas::core::Site::toDOMParent(), nidas::core::SampleTag::toDOMParent(), nidas::core::Variable::toDOMParent(), nidas::core::DSMSensor::toDOMParent(), nidas::core::Datasets::writeXML(), and nidas::core::ProjectConfigs::writeXML().
virtual nidas::core::SampleInput* nidas::dynld::SampleInputStream::getOriginal () const inline virtual inherited
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_original.
nidas::core::SampleSource* nidas::dynld::SampleInputStream::getProcessedSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of processed samples.
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::getProcessedSampleSource().
nidas::core::SampleSource* nidas::dynld::SampleInputStream::getRawSampleSource () inline virtual inherited
Several objects in NIDAS can be both a SampleSource of raw Samples and processed Samples.
SampleClients use this method to get a pointer to whatever sample source they are interested in. Derived classes can return NULL if they are not a SampleSource of raw samples.
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::getRawSampleSource().
const nidas::core::SampleStats& nidas::dynld::SampleInputStream::getSampleStats () const inline virtual inherited
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::getSampleStats().
nidas::core::SampleTagIterator nidas::dynld::SampleInputStream::getSampleTagIterator () const inline virtual inherited
Implementation of SampleSource::getSampleTagIterator().
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::getSampleTagIterator().
std::list<const nidas::core::SampleTag*> nidas::dynld::SampleInputStream::getSampleTags () const inline virtual inherited
Get the output SampleTags.
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::getSampleTags().
bool SampleInputStream::isNonBlocking () const throw (nidas::util::IOException) virtual inherited
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_iochan, and nidas::core::IOChannel::isNonBlocking().
void nidas::dynld::SampleInputStream::newFile () throw (nidas::util::IOException) inherited
bool SampleInputStream::parseInputHeader () throw (nidas::util::IOException) inherited
References nidas::dynld::SampleInputStream::_dataToRead, nidas::dynld::SampleInputStream::_expectHeader, nidas::dynld::SampleInputStream::_headerToRead, nidas::dynld::SampleInputStream::_hptr, nidas::dynld::SampleInputStream::_inputHeader, nidas::dynld::SampleInputStream::_inputHeaderParsed, nidas::dynld::SampleInputStream::_iostream, nidas::dynld::SampleInputStream::_samp, nidas::dynld::SampleInputStream::_sheader, nidas::core::Sample::freeReference(), nidas::dynld::SampleInputStream::getName(), nidas::core::SampleHeader::getSizeOf(), nidas::core::SampleInputHeader::parse(), and nidas::util::Exception::what().
void SampleInputStream::readInputHeader () throw (nidas::util::IOException) inherited
Read archive information at beginning of input stream or file.
References nidas::dynld::SampleInputStream::_dataToRead, nidas::dynld::SampleInputStream::_headerToRead, nidas::dynld::SampleInputStream::_hptr, nidas::dynld::SampleInputStream::_inputHeader, nidas::dynld::SampleInputStream::_inputHeaderParsed, nidas::dynld::SampleInputStream::_iostream, nidas::dynld::SampleInputStream::_samp, nidas::dynld::SampleInputStream::_sheader, nidas::core::Sample::freeReference(), nidas::core::SampleHeader::getSizeOf(), and nidas::core::SampleInputHeader::read().
Referenced by nidas::dynld::raf::SyncRecordReader::init(), nidas::dynld::raf::SyncServer::openStream(), NidsMerge::run(), MergeVerifier::run(), StatsProcess::run(), SensorExtract::run(), DataPrep::run(), Extract2D::run(), and DataStats::run().
Sample * SampleInputStream::readSample () throw (nidas::util::IOException) virtual inherited
Read the next sample from the InputStream.
The caller must call freeReference on the sample when they're done with it. This method may perform zero or more reads of the IOChannel.
Returns
pointer to a sample, never NULL.
Implements nidas::core::SampleInput.
Referenced by nidas::dynld::raf::SyncRecordReader::init(), nidas::dynld::raf::SyncServer::openStream(), nidas::dynld::raf::SyncServer::read(), NidsMerge::run(), MergeVerifier::run(), SensorExtract::run(), and Extract2D::run().
bool SampleInputStream::readSamples () throw (nidas::util::IOException) virtual inherited
Read a buffer of data, serialize the data into samples, and distribute() samples to the receive() method of my SampleClients and DSMSensors.
This will perform only one physical read of the underlying IOChannel and so is appropriate to use when a select() or poll() has determined that there is data available on the file descriptor, or when the physical device is configured for non-blocking reads.
Returns
false: no data available for physical read, likely the result of an EAGAIN from a non-blocking read on a file descriptor. true: physical read did not necessarily consume all available data.
Implements nidas::core::SampleInput.
Referenced by StatsProcess::run(), Calibrator::run(), DataPrep::run(), and DataStats::run().
void nidas::dynld::SampleInputStream::removeSampleClient (nidas::core::SampleClient * c) throw () inline virtual inherited
Remove a SampleClient from this SampleSource.
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::removeSampleClient().
Referenced by DataStats::run().
void nidas::dynld::SampleInputStream::removeSampleClientForTag (nidas::core::SampleClient * c, const nidas::core::SampleTag *) throw () inline virtual inherited
Remove a SampleClient for a given SampleTag from this SampleSource.
The pointer to the SampleClient must remain valid, until after it is removed.
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::removeSampleClientForTag().
void nidas::dynld::SampleInputStream::removeSampleTag (const nidas::core::SampleTag * tag) throw () inline virtual inherited
Implements nidas::core::SampleSource.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::removeSampleTag().
void SampleInputStream::requestConnection (nidas::core::DSMService * requester) throw (nidas::util::IOException) virtual inherited
Implements nidas::core::SampleInput.
void SampleInputStream::search (const nidas::util::UTime & tt) throw (nidas::util::IOException) inherited
Search forward until a sample header is read whose time is greater than or equal to tt.
Leaves the InputStream positioned so that the next call to readSample() or readSamples() will read the rest of the sample.
References nidas::core::CHAR_ST, GET_DSM_ID, nidas::core::getSample(), len, nidas::core::Sample::setTimeTag(), and nidas::core::UNKNOWN_ST.
Referenced by StatsProcess::run(), and DataPrep::run().
void nidas::dynld::SampleInputStream::setExpectHeader (bool val) inline inherited
References nidas::dynld::SampleInputStream::_expectHeader.
Referenced by nidas::dynld::SampleInputStream::setIOChannel().
void nidas::dynld::SampleInputStream::setFilterBadSamples (bool val) inline inherited
References nidas::dynld::SampleInputStream::_filterBadSamples.
Referenced by nidas::dynld::SampleInputStream::setMaxDsmId(), nidas::dynld::SampleInputStream::setMaxSampleLength(), nidas::dynld::SampleInputStream::setMaxSampleTime(), and nidas::dynld::SampleInputStream::setMinSampleTime().
void SampleInputStream::setIOChannel (nidas::core::IOChannel * val) virtual inherited
Set the IOChannel for this SampleInputStream.h.
References nidas::dynld::SampleInputStream::_dsm, nidas::dynld::SampleInputStream::_iochan, nidas::core::IOChannel::close(), nidas::core::Project::findDSM(), nidas::core::IOChannel::getConnectionInfo(), nidas::util::Inet4SocketAddress::getInet4Address(), nidas::core::Project::getInstance(), nidas::core::ConnectionInfo::getRemoteSocketAddress(), nidas::dynld::SampleInputStream::setExpectHeader(), and nidas::core::IOChannel::writeNidasHeader().
Referenced by nidas::dynld::SampleInputStream::SampleInputStream().
void nidas::dynld::SampleInputStream::setKeepStats (bool val) inline virtual inherited
Implements nidas::core::SampleInput.
References nidas::dynld::SampleInputStream::_source, and nidas::core::SampleSourceSupport::setKeepStats().
void nidas::dynld::SampleInputStream::setMaxDsmId (int val) inline inherited
References nidas::dynld::SampleInputStream::_maxDsmId, and nidas::dynld::SampleInputStream::setFilterBadSamples().
Referenced by nidas::dynld::raf::SyncServer::openStream().
void nidas::dynld::SampleInputStream::setMaxSampleLength (unsigned int val) inline inherited
References nidas::dynld::SampleInputStream::_maxSampleLength, and nidas::dynld::SampleInputStream::setFilterBadSamples().
Referenced by nidas::dynld::raf::SyncServer::openStream(), NidsMerge::run(), MergeVerifier::run(), SensorExtract::run(), DataStats::run(), and DataDump::run().
void nidas::dynld::SampleInputStream::setMaxSampleTime (const nidas::util::UTime & val) inline inherited
References nidas::dynld::SampleInputStream::_maxSampleTime, nidas::dynld::SampleInputStream::setFilterBadSamples(), and nidas::util::UTime::toUsecs().
Referenced by nidas::dynld::raf::SyncServer::openStream(), NidsMerge::run(), and MergeVerifier::run().
void nidas::dynld::SampleInputStream::setMinSampleTime (const nidas::util::UTime & val) inline inherited
References nidas::dynld::SampleInputStream::_minSampleTime, nidas::dynld::SampleInputStream::setFilterBadSamples(), and nidas::util::UTime::toUsecs().
Referenced by nidas::dynld::raf::SyncServer::openStream(), NidsMerge::run(), and MergeVerifier::run().
void SampleInputStream::setNonBlocking (bool val) throw (nidas::util::IOException) virtual inherited
Implements nidas::core::SampleInput.
xercesc::DOMElement * DOMable::toDOMElement (xercesc::DOMElement * node, bool complete) const throw (xercesc::DOMException) virtual inherited
Add my content into a DOMElement.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
xercesc::DOMElement * DOMable::toDOMParent (xercesc::DOMElement * parent, bool complete) const throw (xercesc::DOMException) virtual inherited
Create a DOMElement and append it to the parent.
Reimplemented in nidas::core::DSMSensor, nidas::core::Variable, nidas::core::SampleTag, nidas::core::Site, nidas::core::Project, and nidas::core::DSMConfig.
Member Data Documentation
nidas::core::IOChannel* nidas::dynld::SampleInputStream::_iochan protected inherited
Referenced by nidas::dynld::SampleInputStream::close(), nidas::dynld::SampleInputStream::getFd(), nidas::dynld::SampleInputStream::getName(), nidas::dynld::SampleInputStream::isNonBlocking(), nidas::dynld::SampleInputStream::SampleInputStream(), nidas::dynld::SampleInputStream::setIOChannel(), and nidas::dynld::SampleInputStream::~SampleInputStream().
nidas::core::SampleSourceSupport nidas::dynld::SampleInputStream::_source protected inherited
Referenced by nidas::dynld::SampleInputStream::addSampleClient(), nidas::dynld::SampleInputStream::addSampleClientForTag(), nidas::dynld::SampleInputStream::addSampleTag(), nidas::dynld::SampleInputStream::distribute(), nidas::dynld::SampleInputStream::flush(), nidas::dynld::SampleInputStream::getClientCount(), nidas::dynld::SampleInputStream::getProcessedSampleSource(), nidas::dynld::SampleInputStream::getRawSampleSource(), nidas::dynld::SampleInputStream::getSampleStats(), nidas::dynld::SampleInputStream::getSampleTagIterator(), nidas::dynld::SampleInputStream::getSampleTags(), nidas::dynld::isff::PacketInputStream::readSamples(), nidas::dynld::SampleInputStream::removeSampleClient(), nidas::dynld::SampleInputStream::removeSampleClientForTag(), nidas::dynld::SampleInputStream::removeSampleTag(), and nidas::dynld::SampleInputStream::setKeepStats().
The documentation for this class was generated from the following files:
nidas/dynld/RawSampleInputStream.h
nidas/dynld/RawSampleInputStream.cc