nidas: nidas/apps/extract2d.cc File Reference
extract2d.cc File Reference
#include <nidas/core/Project.h>
#include <nidas/core/FileSet.h>
#include <nidas/dynld/SampleInputStream.h>
#include <nidas/dynld/SampleOutputStream.h>
#include <nidas/core/XMLParser.h>
#include <nidas/core/DSMConfig.h>
#include <nidas/core/DSMSensor.h>
#include <nidas/core/SampleInputHeader.h>
#include <nidas/core/HeaderSource.h>
#include <nidas/util/EndianConverter.h>
#include <nidas/util/UTime.h>
#include <nidas/util/util.h>
#include <nidas/util/EOFException.h>
#include <nidas/util/Process.h>
#include <nidas/util/auto_ptr.h>
#include <nidas/dynld/raf/TwoD64_USB.h>
#include <nidas/dynld/raf/TwoD32_USB.h>
#include <fstream>
#include <sys/stat.h>
#include <unistd.h>
#include <getopt.h>
#include <csignal>
#include <climits>
#include <iomanip>
Classes
class Probe
struct P2d_rec
class Extract2D
class AutoProject
Typedefs
typedef struct P2d_rec P2d_rec
Functions
int main (int argc, char **argv)
Variables
static const int FILE_VERSION = 1
Version of the output OAP/PMS2D file.
static const int P2D_DATA = 4096
static const unsigned char Fast2DsyncStr [] = { 0xAA, 0xAA, 0xAA }
static const unsigned char FastOverloadSync [] = { 0x55, 0x55, 0xAA }
static const unsigned char overLoadSync [] = { 0x55, 0xAA }
static const size_t DefaultMinimumNumberParticlesRequired = 5
const n_u::EndianConverter * bigEndian = n_u::EndianConverter::getConverter(n_u::EndianConverter::EC_BIG_ENDIAN)
Typedef Documentation
typedef struct P2d_rec P2d_rec
Function Documentation
int main (int argc, char ** argv)
References Extract2D::main().
Variable Documentation
const n_u::EndianConverter* bigEndian = n_u::EndianConverter::getConverter(n_u::EndianConverter::EC_BIG_ENDIAN)
Referenced by nidas::dynld::raf::TwoD64_USB::process(), nidas::dynld::raf::TwoD32_USB::process(), nidas::dynld::raf::TwoD32_USB::processImage(), nidas::dynld::raf::TwoD64_USB::processImageRecord(), nidas::dynld::raf::TwoD64_USB::processSOR(), and Extract2D::run().
const size_t DefaultMinimumNumberParticlesRequired = 5 static
const unsigned char Fast2DsyncStr[] = { 0xAA, 0xAA, 0xAA } static
Referenced by Extract2D::computeDiodeCount(), and Extract2D::countParticles().
const unsigned char FastOverloadSync[] = { 0x55, 0x55, 0xAA } static
Referenced by Extract2D::computeDiodeCount(), and Extract2D::countParticles().
const int FILE_VERSION = 1 static
Version of the output OAP/PMS2D file.
Increment this when changes occur. Change log: 03/25/2011 - version 1: tas should be tas as int, drop the '* 255 / 125' encoding. add nDiodes attribute to probe element. Change PMS2D in XML to OAP. add version. :)
Referenced by Extract2D::run().
const unsigned char overLoadSync[] = { 0x55, 0xAA } static
Referenced by Extract2D::run().
const int P2D_DATA = 4096 static
Referenced by Extract2D::computeDiodeCount(), and Extract2D::run().