nidas: nidas::core Namespace Reference
nidas::core Namespace Reference
The essential core classes of nidas.
Classes
class AdaptiveDespiker
Adaptive forecaster for despiking of time-series data.
class AsciiSscanf
Class providing sscanf functionality for parsing ASCII data.
class CalFile
A class for reading ASCII files containing a time series of calibration data.
class CharacterSensor
Implementation of support for a sensor which generates character output.
class ConnectionInfo
Extra information associated with an IOChannel concerning the connection.
class SampleConnectionRequester
Interface for an object that requests connections SampleOutputs.
class DatagramSocket
Implementation of an IOChannel, over a DatagramSocket.
class Dataset
A Dataset is a named collection of parameters, that are used in data processing.
class Datasets
A collection of Datasets.
class DerivedDataClient
Interface of a DerivedDataClient of the DerivedDataReader.
class DerivedDataReader
This class will read, parse and make available the parameters in the onboard real-time broadcast of data.
class Dictionary
Interface for a Dictionary class, which can return a string value for a string token name.
class DOMable
Interface of an object that can be instantiated from a DOM element, via the fromDOMElement method, or that can be serialized into a DOM, via the toDOMParent/toDOMElement method.
class DOMObjectFactory
Class that supports creating instances of DOMable objects from a string containing the class name of the object to be created.
class DSMCatalog
A catalog of DSM DOMElements, implemented with std::map, containing dsm DOMElements, keyed by the ID attributes.
class DSMConfig
Class that should include all that is configurable about a DSM.
class DSMEngine
Application for running the NIDAS data acquistion process.
class DSMEngineIntf
A thread that provides XML-based Remote Procedure Calls to web interfaces from the DSMEngine.
class DSMSensor
DSMSensor provides the basic support for reading, processing and distributing samples from a sensor attached to a DSM.
class DSMServer
A provider of services to a DSM.
class DSMServerApp
class DSMServerIntf
A thread that provides XML-based Remote Procedure Calls to web interfaces from the DSMServer.
class GetDsmList
gets a list of DSMs and their locations from the configuration
class GetAdsFileName
gets the name of the current .ads file
class DSMService
Base class for a service, as built from a <service> XML tag.
class DynamicLoader
Class providing dynamic loader functionality of system functions dlopen() and dlsym() to look up symbols.
class FileSet
Implementation of an IOChannel using an nidas::util::FileSet.
class FsMount
Filesystem mounter/unmounter.
class FsMountWorkerThread
Filesystem mounter/unmounter.
class HeaderSource
An interface for sending a SampleHeader to a SampleOutput.
class IOChannelRequester
Interface for an object that requests connections to Inputs or Outputs.
class IOChannel
A channel for Input or Output of data.
class IODevice
An interface to an IO device.
class IOStream
A base class for buffering data.
class Looper
Looper is a Thread that periodically loops, calling the LooperClient::looperNotify() method of LooperClients at the requested intervals.
class LooperClient
Interface of a client of Looper.
class McSocket
Implementation of an IOChannel, using nidas::util::McSocket<nidas::util::Socket> to establish a TCP connection.
class McSocketUDP
Implementation of an IOChannel, using nidas::util::McSocket<nidas::util::DatagramSocket> to establish a pair of communicating UDP sockets.
class MultipleUDPSockets
class NearestResampler
A simple, nearest-point resampler, for generating merged samples from variables from one or more sample sources.
class NearestResamplerAtRate
A simple, nearest-point resampler, for generating merged samples from variables from one or more sample sources.
class NidasAppException
The NidasApp class throws a NidasAppException when command-line options do not parse.
class NidasAppArg
A NidasAppArg identifies a particular kind of command-line argument which can be handled by NidasApp.
class NidasAppInputFilesArg
Extend NidasAppArg so the default input specifier and port can be customized, which in turn updates the usage string.
class NidasApp
Handle common options for NIDAS applications.
struct NidasAppArgv
Convert vector<string> args to dynamically allocated (argc, argv) pair which will be freed when the instance is destroyed.
class SiteIterator
Class for iterating over the Sites of a Project, or the Sites served by a DSMServer.
class DSMServerIterator
Class for iterating over the DSMServers of a Project.
class DSMServiceIterator
Class for iterating over the DSMServices of a DSMServer.
class DSMConfigIterator
Class for iterating over the DSMConfigs of a Project or Site.
class ProcessorIterator
Class for iterating over the Processors of a DSMServer or DSMConfig.
class SensorIterator
Class for iterating over the DSMSensors of a Project, Site, or DSMConfig.
class SampleTagIterator
Class for iterating over the SampleTags of a Project, Site, DSMConfig, or a SampleSource.
class VariableIterator
Class for iterating over the Variables of a Project, Site, DSMConfig, DSMSensor, or SampleTag.
class Parameter
class ParameterT
A typed Parameter, with data of type T.
class ParameterNameTypeComparator
Functor class for Parameter, doing an equality check of parameter name and type.
class Polled
Interface for objects with a file descriptor, providing a virtual method to be called when system calls such as select, poll, or epoll indicate an event is pending on the file descriptor.
class Project
class ProjectConfig
class ProjectConfigTimeComparator
Sample time tag comparator.
class ProjectConfigs
class Prompt
Class to contain prompt information - string and rate.
class RemoteSerialConnection
class RemoteSerialListener
class Resampler
Interface for a resampler, simply a SampleClient and a SampleSource.
class SampleHeader
The header fields of a Sample: a time_tag, a data length field, and an identifier.
class Sample
Interface to a data sample.
class SampleT
A typed Sample, with data of type DataT.
class SampleArchiver
class SampleAverager
class SampleBuffer
A SampleClient that buffers its received samples, using a pair of STL vectors, and then sends the buffered samples onto its SampleClients.
class SampleClient
Pure virtual interface of a client of Samples.
class SampleClientList
A list of SampleClients.
class SampleClock
SampleClock adds date information to sample time tags.
class SampleInput
Interface of an input SampleSource.
class SampleInputHeader
class SampleIOProcessor
Interface of a processor of samples.
class SampleLengthException
class SampleMatcher
Match samples according to DSM and Sample ID ranges, and configure the ranges with criteria in text format.
class SampleOutput
Interface of an output stream of samples.
class SampleOutputBase
Implementation of portions of SampleOutput.
class SampleOutputRequestThread
Interface of an output stream of samples.
class SampleParseException
class SamplePipeline
SamplePipeline sorts samples that are coming from one or more inputs.
class SamplePoolInterface
class SamplePools
class SamplePool
A pool of Samples.
class SampleScanner
A scanner of sample data.
class DriverSampleScanner
A SampleScanner for reading samples that have been pre-formatted by a device driver - they already have a header consisting of a timetag, and a data length.
class MessageSampleScanner
A DriverSampleScanner which supports the set/get of message separation parameters.
class MessageStreamScanner
A SampleScanner which supports the set/get of message separation parameters and extracts samples from the internal buffer by recognizing separators in the message stream.
class DatagramSampleScanner
class SampleSorter
A SampleClient that sorts its received samples, using an STL multiset, and then sends the sorted samples onto its SampleClients.
class SampleSource
Pure virtual interface for a source of Samples.
class SampleSourceSupport
A source of samples.
class SampleStats
A source of samples.
class SampleTag
Class describing a group of variables that are sampled and handled together.
class SampleThread
Interface for a Thread for buffering samples.
class SampleTracer
SampleTracer uses a Logger to log messages about samples as they are encountered in the code.
class SensorCatalog
A catalog of sensor DOMElements, implemented with std::map, containing sensor DOMElements, keyed by the ID attributes.
class SensorHandler
SensorHandler implements a DSMSensor event loop.
class SensorOpener
Thread which opens DSMSensors.
class SerialPortIODevice
A serial port.
class SerialSensor
Support for a sensor that is sending packets on a TCP socket, a UDP socket, a Bluetooth RF Comm socket, or a good old RS232/422/485 serial port.
class ServerSocketIODevice
An IODevice supporting a TCP or UNIX server socket.
class ServiceCatalog
A catalog of dsm DOMElements, implemented with std::map, containing dsm DOMElements, keyed by the ID attributes.
class Site
A measurement site.
class Socket
Implementation of an IOChannel, over a Socket.
class ServerSocket
Implementation of an IOChannel, over a ServerSocket.
class SocketIODevice
A IODevice providing support for UDP and TCP sockets.
class SampleTimetagComparator
Sample time tag comparator.
class SampleHeaderComparator
Timetag and Id comparator of pointers to Samples: if two timetags are the same, then compare Ids, and if they're equal, compare data length.
class FullSampleComparator
Comparator of pointers to Samples, does the same checks as SampleHeaderComparator, but in addition, if two samples compare as equal, then compares their data.
class StatusHandler
This class implements handling routines for the SAX2 parser.
class StatusListener
thread that listens to multicast messages from all of the DSMs.
class GetClocks
gets a list of current clock times for each broadcasting DSM.
class GetStatus
gets a list of current status reports for each broadcasting DSM.
class StatusThread
A thread that runs periodically checking and multicasting the status of a DSMEngine.
class DSMEngineStat
class DSMServerStat
class TCPSocketIODevice
An IODevice consisting of a TCP socket.
class UDPSocketIODevice
An IODevice consisting of an UDP socket.
class UnixIOChannel
Simple implementation of an IOChannel, over an opened file descriptor.
class UnixIODevice
A basic Unix I/O device, such as a named pipe, or a watched file.
class Variable
Class describing a sampled variable.
class VariableConverter
class Linear
class Polynomial
class Version
Class of static member functions providing version strings.
class XDOMElement
Wrapper class providing convienence methods to access the string attributes of a DOMElement.
class XDOMAttr
Class providing convienence methods to access the string attributes of a DOMAttr.
class XMLConfigInput
class XMLConfigWriterFilter
class XMLConfigWriter
An XMLWriter which writes the NIDAS XML configuration.
class XMLException
Exception which can be built from an xerces::XMLException, xercesc::SAXException, or xercesc::DOMException.
class XMLFdBinInputStream
Implemenation of xercesc::BinInputStream, which reads from a unix file descriptor.
class XMLFdFormatTarget
Extension of xercesc::XMLFormatTarget support writing XML to an open device (socket for example).
class XMLFdInputSource
Implemenation of xercesc::InputSource, that returns an XMLFdBinInputStream for reading from a Unix file descriptor - i.e.
class XMLImplementation
class XMLErrorHandler
class XMLParser
Wrapper class around xerces-c DOMBuilder to parse XML.
class XMLCachingParser
Derived class of XMLParser that keeps its DOMDocuments when parsing an XML disk file, and returns the cached DOMDocument if the file hasn't changed.
class XmlRpcThread
A thread that provides XML-based Remote Procedure Calls to web interfaces.
class XMLStringConverter
Class providing conversions between string and XMLCh* using the Xerces-c transcode and release methods.
class XMLWriter
Wrapper class around xerces-c DOMWriter to write XML.
Typedefs
typedef std::vector
< NidasAppArg * > nidas_app_arglist_t
Sets of arguments can be manipulated together by putting them into this container type.
typedef long long dsm_time_t
Posix time in microseconds, the number of non-leap microseconds since 1970 Jan 1 00:00 UTC.
typedef unsigned int dsm_sample_id_t
typedef enum
nidas::core::sampleType sampleType
typedef std::multiset< const
Sample
*, SampleTimetagComparator > SortedSampleSet
A multiset for storing samples sorted by timetag.
typedef std::set< const Sample
*, SampleHeaderComparator > SortedSampleSet2
A set for storing samples sorted by the timetag, id and data length.
typedef std::set< const Sample
*, FullSampleComparator > SortedSampleSet3
Enumerations
enum McSocketRequest {
XML_CONFIG = 0, RAW_SAMPLE, UDP_PROCESSED_SAMPLE_FEED, XML_ALL_CONFIG,
UNKNOWN_REQUEST
}
enum sampleType {
CHAR_ST, UCHAR_ST, SHORT_ST, USHORT_ST,
INT32_ST, UINT32_ST, FLOAT_ST, DOUBLE_ST,
INT64_ST, UNKNOWN_ST
}
Functions
nidas_app_arglist_t operator| (nidas_app_arglist_t arglist1, nidas_app_arglist_t arglist2)
Parameter::parType getParamType (std::string)
Overloaded function to return a enumerated value corresponding to the type pointed to by the argument.
Parameter::parType getParamType (float)
Parameter::parType getParamType (int)
Parameter::parType getParamType (bool)
xercesc::DOMDocument * requestXMLConfig (bool all, const n_u::Inet4SocketAddress &mcastAddr, sigset_t *signalMask=(sigset_t *) 0) throw (n_u::Exception)
Request the XML configuration via a McSocket request to a given multicast socket address.
unsigned int maxValue (unsigned short)
The gcc buildin atomic operations are not supported on arm, and one must use -march=i686 for them to work on 32 bit x86.
unsigned int maxValue (short)
unsigned int maxValue (int)
sampleType getSampleType (char *)
Overloaded function to return a enumerated value corresponding to the type pointed to by the argument.
sampleType getSampleType (unsigned char *)
sampleType getSampleType (unsigned short *)
sampleType getSampleType (short *)
sampleType getSampleType (unsigned int *)
sampleType getSampleType (int *)
sampleType getSampleType (float *)
sampleType getSampleType (double *)
sampleType getSampleType (long long *)
sampleType getSampleType (void *)
Sample * getSample (sampleType type, unsigned int len)
A convienence method for getting a sample of an enumerated type from a pool.
template<class T >
SampleT< T > * getSample (unsigned int len) throw (SampleLengthException)
A convenience function for getting a typed sample from a pool.
xercesc::DOMDocument * parseXMLConfigFile (const std::string &xmlFileName) throw (nidas::core::XMLException)
Utility function which creates a temporary XMLParser, sets the options we typically want and parses the XML into a DOMDocument.
std::ostream & operator<< (std::ostream &target, const XMLStringConverter &toDump)
Variables
const double MS_PER_KNOT = 1852.0 / 3600.0
const float MBAR_PER_PSI = 68.9476
const float MBAR_PER_KPA = 10.0
const float KELVIN_AT_0C = 273.15
const float floatNAN = nanf("")
Value of a float NAN for general use.
const double doubleNAN = nan("")
Detailed Description
The essential core classes of nidas.
Typedef Documentation
typedef unsigned int nidas::core::dsm_sample_id_t
typedef long long nidas::core::dsm_time_t
Posix time in microseconds, the number of non-leap microseconds since 1970 Jan 1 00:00 UTC.
typedef std::vector<NidasAppArg*> nidas::core::nidas_app_arglist_t
Sets of arguments can be manipulated together by putting them into this container type.
The container can be generated using operator|().
typedef enum nidas::core::sampleType nidas::core::sampleType
typedef std::multiset<const Sample*,SampleTimetagComparator> nidas::core::SortedSampleSet
A multiset for storing samples sorted by timetag.
It is a multiset rather than a set because it is OK to have samples with the same timetag.
typedef std::set<const Sample*,SampleHeaderComparator> nidas::core::SortedSampleSet2
A set for storing samples sorted by the timetag, id and data length.
Duplicate samples which compare as equal (!(x<y) & !(y<x)) to another are not inserted. This is used for merging archives containing duplicate samples. Note that we're not comparing the data in the sample. Also note: you must check the return of insert(const Sample*) to know whether a sample was inserted. If a sample wasn't inserted you likely want to do a Sample::freeReference() on it.
typedef std::set<const Sample*,FullSampleComparator> nidas::core::SortedSampleSet3
Enumeration Type Documentation
enum nidas::core::McSocketRequest
Enumerator
XML_CONFIG
Request for a TCP feed of the configuration in XML.
RAW_SAMPLE
Request for a TCP feed of raw samples.
UDP_PROCESSED_SAMPLE_FEED
Request for feed of processed samples on a UDP socket, and a listing of variables on a TCP socket.
XML_ALL_CONFIG
Request for a TCP feed of the entire configuration in XML.
UNKNOWN_REQUEST
enum nidas::core::sampleType
Enumerator
CHAR_ST
UCHAR_ST
SHORT_ST
USHORT_ST
INT32_ST
UINT32_ST
FLOAT_ST
DOUBLE_ST
INT64_ST
UNKNOWN_ST
Function Documentation
Parameter::parType nidas::core::getParamType (std::string) inline
Overloaded function to return a enumerated value corresponding to the type pointed to by the argument.
References nidas::core::Parameter::STRING_PARAM.
Parameter::parType nidas::core::getParamType (float) inline
References nidas::core::Parameter::FLOAT_PARAM.
Parameter::parType nidas::core::getParamType (int) inline
References nidas::core::Parameter::INT_PARAM.
Parameter::parType nidas::core::getParamType (bool) inline
References nidas::core::Parameter::BOOL_PARAM.
Sample * nidas::core::getSample (sampleType type, unsigned int len)
A convienence method for getting a sample of an enumerated type from a pool.
Returns NULL if type is unknown or len is out of range.
References CHAR_ST, DOUBLE_ST, FLOAT_ST, INT32_ST, INT64_ST, len, SHORT_ST, UCHAR_ST, UINT32_ST, UNKNOWN_ST, and USHORT_ST.
Referenced by nidas::core::SamplePool< SampleType >::getSample(), nidas::dynld::SampleInputStream::sampleFromHeader(), and nidas::dynld::SampleInputStream::search().
template<class T > SampleT<T>* nidas::core::getSample (unsigned int len) throw (SampleLengthException)
A convenience function for getting a typed sample from a pool.
References nidas::core::SamplePool< SampleType >::getSample(), and len.
sampleType nidas::core::getSampleType (char *) inline
Overloaded function to return a enumerated value corresponding to the type pointed to by the argument.
References CHAR_ST.
Referenced by nidas::core::SampleT< char >::getType().
sampleType nidas::core::getSampleType (unsigned char *) inline
References UCHAR_ST.
sampleType nidas::core::getSampleType (unsigned short *) inline
References USHORT_ST.
sampleType nidas::core::getSampleType (short *) inline
References SHORT_ST.
sampleType nidas::core::getSampleType (unsigned int *) inline
References UINT32_ST.
sampleType nidas::core::getSampleType (int *) inline
References INT32_ST.
sampleType nidas::core::getSampleType (float *) inline
References FLOAT_ST.
sampleType nidas::core::getSampleType (double *) inline
References DOUBLE_ST.
sampleType nidas::core::getSampleType (long long *) inline
References INT64_ST.
sampleType nidas::core::getSampleType (void *) inline
References UNKNOWN_ST.
unsigned int nidas::core::maxValue (unsigned short) inline
The gcc buildin atomic operations are not supported on arm, and one must use -march=i686 for them to work on 32 bit x86.
maxValue is an overloaded function returning the maximum value of its integer argument.
Referenced by nidas::core::SampleHeader::getMaxDataLength().
unsigned int nidas::core::maxValue (short) inline
unsigned int nidas::core::maxValue (int) inline
std::ostream& nidas::core::operator<< (std::ostream & target, const XMLStringConverter & toDump) inline
nidas_app_arglist_t nidas::core::operator| (nidas_app_arglist_t arglist1, nidas_app_arglist_t arglist2)
xercesc::DOMDocument * nidas::core::parseXMLConfigFile (const std::string & xmlFileName) throw (nidas::core::XMLException)
Utility function which creates a temporary XMLParser, sets the options we typically want and parses the XML into a DOMDocument.
Referenced by nidas::core::ProjectConfig::initProject(), StatsProcess::listOutputSamples(), ARLIngest::prepareHeaderIds(), StatsProcess::run(), nidas::core::DSMEngine::run(), DataPrep::run(), Extract2D::run(), DataStats::run(), DataDump::run(), and nidas::core::Project::throw().
xercesc::DOMDocument * nidas::core::requestXMLConfig (bool all, const n_u::Inet4SocketAddress & mcastAddr, sigset_t * signalMask = (sigset_t*)0) throw (n_u::Exception)
Request the XML configuration via a McSocket request to a given multicast socket address.
Parameters
all,: If true, request the entire project XML, otherwise just the XML which corresponds to the address of the calling DSM.
References nidas::util::McSocket< SocketT >::close(), nidas::util::McSocket< SocketT >::connect(), DLOG, PLOG, nidas::util::McSocket< SocketT >::setInet4McastSocketAddress(), nidas::util::McSocket< SocketT >::setRequestType(), nidas::util::Exception::what(), and XML_ALL_CONFIG.
Referenced by nidas::core::DSMEngine::run(), and Calibrator::setup().
Variable Documentation
const double nidas::core::doubleNAN = nan("")
Referenced by nidas::dynld::raf::SyncRecordSource::allocateRecord(), nidas::dynld::GPS_Novatel_Serial::parseBESTPOS(), nidas::dynld::GPS_Novatel_Serial::parseBESTVEL(), nidas::dynld::GPS_NMEA_Serial::parseGGA(), nidas::dynld::GPS_NMEA_Serial::parseHDT(), nidas::dynld::GPS_NMEA_Serial::parseRMC(), nidas::dynld::raf::IRS_HW_YG1854::processLabel(), nidas::dynld::raf::ADC_HW_EB7022597::processLabel(), nidas::dynld::raf::LSZ_HW_EB7032239::processLabel(), nidas::dynld::raf::IRS_HW_HG2001GD::processLabel(), and nidas::dynld::raf::GPS_HW_HG2021GB02::processLabel().
const float nidas::core::floatNAN = nanf("")
Value of a float NAN for general use.
Referenced by nidas::dynld::DSC_FreqCounter::calculatePeriodUsec(), nidas::dynld::StatisticsCruncher::computeStats(), nidas::dynld::isff::GOESOutput::connected(), nidas::dynld::isff::RebsLinear::convert(), nidas::dynld::isff::WisardMote::convert(), nidas::dynld::ParoSci_202BG_P::createPressureSample(), nidas::core::NearestResampler::ctorCommon(), nidas::core::NearestResamplerAtRate::ctorCommon(), nidas::core::SampleAverager::flush(), nidas::core::NearestResampler::flush(), nidas::dynld::isff::SE_GOESXmtr::getBatteryVoltages(), nidas::dynld::A2DSensor::getIntercept(), nidas::core::Parameter::getNumericValue(), AutoCalClient::GetOldTemperature(), nidas::dynld::ParoSci_202BG_T::getPeriodUsec(), nidas::core::SamplePool< SampleType >::getSample(), nidas::dynld::A2DSensor::getSlope(), nidas::dynld::isff::SonicAnemometer::offsetsTiltAndRotate(), nidas::dynld::ParoSci_202BG_Calibration::ParoSci_202BG_Calibration(), nidas::dynld::GPS_Novatel_Serial::parseBESTPOS(), nidas::dynld::isff::PacketParser::parseData(), nidas::core::DerivedDataReader::parseIWGADTS(), nidas::dynld::isff::Licor7500::process(), nidas::dynld::isff::ATIK_Sonic::process(), nidas::dynld::isff::CU_Coldwire::process(), nidas::dynld::isff::CSI_CRX_Binary::process(), nidas::dynld::isff::NCAR_TRH::process(), nidas::dynld::ParoSci_202BG_T::process(), nidas::dynld::isff::CSI_IRGA_Sonic::process(), nidas::dynld::raf::LamsNetSensor::process(), nidas::dynld::IEEE_Float::process(), nidas::dynld::iss::WICORSensor::process(), nidas::dynld::raf::UHSAS_Serial::process(), nidas::dynld::raf::VCSEL_Serial::process(), nidas::dynld::raf::LamsSensor::process(), nidas::dynld::isff::PropVane::process(), nidas::dynld::A2DSensor::process(), nidas::dynld::isff::CSAT3_Sonic::process(), nidas::dynld::DSC_FreqCounter::process(), nidas::dynld::raf::IRIGSensor::process(), nidas::dynld::raf::DSMAnalogSensor::process(), nidas::dynld::isff::SonicAnemometer::process(), nidas::core::CharacterSensor::process(), nidas::dynld::ParoSci_202BG_Calibration::readCalFile(), nidas::dynld::isff::CS_Krypton::readCalFile(), nidas::core::Linear::readCalFile(), nidas::core::Polynomial::readCalFile(), nidas::core::CalFile::readCFNoLock(), nidas::core::NearestResampler::receive(), nidas::core::SampleAverager::receive(), nidas::dynld::isff::GOESOutput::run(), nidas::dynld::WxtSensor::scanSample(), nidas::core::NearestResamplerAtRate::sendSample(), nidas::core::DSMSensor::setDepth(), nidas::core::DSMSensor::setHeight(), nidas::core::AsciiSscanf::sscanf(), nidas::dynld::isff::ATIK_Sonic::transducerShadowCorrection(), nidas::dynld::isff::WisardMote::TsoilData::TsoilData(), nidas::dynld::isff::WisardMote::unpack100thSec(), nidas::dynld::isff::WisardMote::unpack10thSec(), nidas::dynld::isff::WisardMote::unpackAccumSec(), nidas::dynld::isff::WisardMote::unpackCNR2(), nidas::dynld::isff::WisardMote::unpackGsoil(), nidas::dynld::isff::WisardMote::unpackInt16(), nidas::dynld::isff::WisardMote::unpackInt32(), nidas::dynld::isff::WisardMote::unpackNR01(), nidas::dynld::isff::WisardMote::unpackPicTime(), nidas::dynld::isff::WisardMote::unpackPicTimeFields(), nidas::dynld::isff::WisardMote::unpackPower(), nidas::dynld::isff::WisardMote::unpackQsoil(), nidas::dynld::isff::WisardMote::unpackRlw(), nidas::dynld::isff::WisardMote::unpackRlwKZ(), nidas::dynld::isff::WisardMote::unpackRnet(), nidas::dynld::isff::WisardMote::unpackRsw(), nidas::dynld::isff::WisardMote::unpackRsw2(), nidas::dynld::isff::WisardMote::unpackStatus(), nidas::dynld::isff::WisardMote::unpackTP01(), nidas::dynld::isff::WisardMote::unpackTRH(), nidas::dynld::isff::WisardMote::unpackTsoil(), nidas::dynld::isff::WisardMote::unpackUint16(), nidas::dynld::isff::WisardMote::unpackUint32(), nidas::dynld::isff::WisardMote::unpackXbee(), and nidas::core::Variable::Variable().
const float nidas::core::KELVIN_AT_0C = 273.15
Referenced by nidas::dynld::isff::ATIK_Sonic::process(), and nidas::dynld::isff::CSAT3_Sonic::process().
const float nidas::core::MBAR_PER_KPA = 10.0
Referenced by nidas::dynld::ParoSci_202BG_Calibration::readCalFile().
const float nidas::core::MBAR_PER_PSI = 68.9476
const double nidas::core::MS_PER_KNOT = 1852.0 / 3600.0
Referenced by nidas::dynld::GPS_NMEA_Serial::parseRMC().