nidas: numeric Namespace Reference
numeric Namespace Reference
Functions
double PolyEval (double *cof, unsigned int order, double target)
double PolyEval (std::vector< double > cof, double target)
Function Documentation
double numeric::PolyEval (double * cof, unsigned int order, double target) inline
Referenced by TestA2DPage::dispVolts(), and PolyEval().
double numeric::PolyEval (std::vector< double > cof, double target) inline
References PolyEval().