nidas: nidas/linux/util/nidas_util.c File Reference
nidas_util.c File Reference
#include <nidas/linux/util.h>
#include <nidas/linux/klog.h>
#include <nidas/linux/Revision.h>
#include <linux/module.h>
#include <linux/init.h>
#include <linux/sched.h>
#include <linux/slab.h>
#include <asm/uaccess.h>
Macros
#define REPO_REVISION "unknown"
Functions
MODULE_AUTHOR ("Gordon Maclean <maclean@ucar.edu>")
MODULE_DESCRIPTION ("NCAR nidas utilities")
MODULE_LICENSE ("GPL")
MODULE_VERSION (REPO_REVISION)
int alloc_dsm_circ_buf (struct dsm_sample_circ_buf *c, size_t dlen, int blen)
void free_dsm_circ_buf (struct dsm_sample_circ_buf *c)
int realloc_dsm_circ_buf (struct dsm_sample_circ_buf *c, size_t dlen, int blen)
void init_dsm_circ_buf (struct dsm_sample_circ_buf *c)
ssize_t nidas_circbuf_read_nowait (struct file *filp, char __user *buf, size_t count, struct dsm_sample_circ_buf *cbuf, struct sample_read_state *state)
ssize_t nidas_circbuf_read (struct file *filp, char __user *buf, size_t count, struct dsm_sample_circ_buf *cbuf, struct sample_read_state *state, wait_queue_head_t *readq)
static void __exit nidas_util_cleanup (void)
static int __init nidas_util_init (void)
EXPORT_SYMBOL (alloc_dsm_circ_buf)
EXPORT_SYMBOL (free_dsm_circ_buf)
EXPORT_SYMBOL (realloc_dsm_circ_buf)
EXPORT_SYMBOL (init_dsm_circ_buf)
EXPORT_SYMBOL (nidas_circbuf_read)
EXPORT_SYMBOL (nidas_circbuf_read_nowait)
module_init (nidas_util_init)
module_exit (nidas_util_cleanup)
Macro Definition Documentation
#define REPO_REVISION "unknown"
Referenced by nidas_util_init().
Function Documentation
int alloc_dsm_circ_buf (struct dsm_sample_circ_buf * c, size_t dlen, int blen)
References SIZEOF_DSM_SAMPLE_HEADER.
Referenced by init_cntr(), init_event(), init_fcntrs(), ir104_init(), lams_open(), mesa_ioctl(), realloc_dsm_circ_buf(), and startA2D().
EXPORT_SYMBOL (alloc_dsm_circ_buf)
EXPORT_SYMBOL (free_dsm_circ_buf)
EXPORT_SYMBOL (realloc_dsm_circ_buf)
EXPORT_SYMBOL (init_dsm_circ_buf)
EXPORT_SYMBOL (nidas_circbuf_read)
EXPORT_SYMBOL (nidas_circbuf_read_nowait)
void free_dsm_circ_buf (struct dsm_sample_circ_buf * c)
Referenced by arinc_cleanup(), arinc_release(), cleanup_a2d(), cleanup_cntr(), cleanup_event(), cleanup_fcntrs(), close_ports(), ir104_cleanup(), lams_release(), mesa_ioctl(), ncar_a2d_cleanup(), pc104sg_release(), realloc_dsm_circ_buf(), resetA2D_processing(), startA2D(), and stopBoard().
void init_dsm_circ_buf (struct dsm_sample_circ_buf * c)
MODULE_AUTHOR ("Gordon Maclean <maclean@ucar.edu>")
MODULE_DESCRIPTION ("NCAR nidas utilities")
module_exit (nidas_util_cleanup)
module_init (nidas_util_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (REPO_REVISION)
ssize_t nidas_circbuf_read (struct file * filp, char __user * buf, size_t count, struct dsm_sample_circ_buf * cbuf, struct sample_read_state * state, wait_queue_head_t * readq)
References nidas_circbuf_read_nowait().
Referenced by arinc_read(), dmmat_read_a2d(), dmmat_read_cntr(), dmmat_read_d2d(), gpio_mm_read_event(), gpio_mm_read_fcntr(), ir104_relay_read(), mesa_read(), ncar_a2d_read(), and pc104sg_read().
ssize_t nidas_circbuf_read_nowait (struct file * filp, char __user * buf, size_t count, struct dsm_sample_circ_buf * cbuf, struct sample_read_state * state)
References dsm_sample::length, and SIZEOF_DSM_SAMPLE_HEADER.
Referenced by lams_read(), and nidas_circbuf_read().
static void __exit nidas_util_cleanup (void) static
static int __init nidas_util_init (void) static
References REPO_REVISION.
int realloc_dsm_circ_buf (struct dsm_sample_circ_buf * c, size_t dlen, int blen)
References alloc_dsm_circ_buf(), and free_dsm_circ_buf().
Referenced by arinc_open(), pc104sg_open(), and startBoard().