nidas: nidas/apps/nidas_udp_relay.cc File Reference
nidas_udp_relay.cc File Reference
#include <deque>
#include <nidas/util/Process.h>
#include <nidas/util/Socket.h>
#include <nidas/util/Thread.h>
#include <nidas/util/Logger.h>
#include <nidas/util/UTime.h>
#include <nidas/core/Socket.h>
#include <nidas/core/IOStream.h>
#include <nidas/core/Sample.h>
#include <unistd.h>
#include <getopt.h>
Classes
class PacketReader
class WriterThread
class ServerThread
Functions
static bool serverSocketRetry (int err)
int main (int argc, char **argv)
Variables
static bool interrupted = false
Function Documentation
int main (int argc, char ** argv)
References nidas::util::LogScheme::addConfig(), nidas::util::Process::addEffectiveCapability(), nidas::util::Logger::createInstance(), PacketReader::debug(), nidas::util::LogConfig::level, PacketReader::loop(), NLOG, PacketReader::parseRunstring(), nidas::util::Logger::setScheme(), nidas::util::LogScheme::setShowFields(), nidas::util::Thread::start(), nidas::util::Exception::toString(), and nidas::util::Exception::what().
static bool serverSocketRetry (int err) static
Referenced by ServerThread::run().
Variable Documentation
bool interrupted = false static
Referenced by RemoteSerial::interrupt(), PacketReader::loop(), TeeTTy::run(), Sender::run(), Receiver::run(), ModemLineSetter::run(), ModemLineMonitor::run(), TeeI2C::run(), WriterThread::run(), ServerThread::run(), and sigAction().