nidas: nidas/apps/sensor_extract.cc File Reference
sensor_extract.cc File Reference
#include <nidas/dynld/RawSampleInputStream.h>
#include <nidas/dynld/RawSampleOutputStream.h>
#include <nidas/core/HeaderSource.h>
#include <nidas/core/FileSet.h>
#include <nidas/core/Bzip2FileSet.h>
#include <nidas/core/Socket.h>
#include <nidas/util/Logger.h>
#include <nidas/util/UTime.h>
#include <nidas/util/EOFException.h>
#include <nidas/util/auto_ptr.h>
#include <csignal>
#include <climits>
#include <iomanip>
#include <unistd.h>
#include <getopt.h>
Classes
class SensorExtract
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References nidas::util::Logger::getInstance(), nidas::util::LogConfig::level, nidas::util::LOGGER_INFO, SensorExtract::main(), and nidas::util::Logger::setScheme().