nidas: nidas/apps/statsproc.cc File Reference
statsproc.cc File Reference
#include <ctime>
#include <unistd.h>
#include <iomanip>
#include <nidas/core/Project.h>
#include <nidas/core/DSMConfig.h>
#include <nidas/core/Datasets.h>
#include <nidas/core/ProjectConfigs.h>
#include <nidas/core/DSMServer.h>
#include <nidas/core/DSMSensor.h>
#include <nidas/core/Variable.h>
#include <nidas/core/FileSet.h>
#include <nidas/core/Socket.h>
#include <nidas/dynld/RawSampleInputStream.h>
#include <nidas/dynld/StatisticsProcessor.h>
#include <nidas/dynld/AsciiOutput.h>
#include <nidas/core/SampleOutputRequestThread.h>
#include <nidas/core/XMLParser.h>
#include <nidas/core/Version.h>
#include <nidas/util/Logger.h>
#include <nidas/util/Process.h>
Classes
class StatsProcess
Functions
int main (int argc, char **argv)
void getmyhostname ()
Variables
string _hostname = string()
Function Documentation
void getmyhostname ()
References _hostname.
Referenced by StatsProcess::main().
int main (int argc, char ** argv)
References StatsProcess::main().
Variable Documentation
string _hostname = string()
Referenced by getmyhostname(), StatsProcess::getStatisticsProcessor(), StatsProcess::listOutputSamples(), and StatsProcess::run().