nidas: nidas/dynld/twins_ramp.c File Reference
twins_ramp.c File Reference
Functions
llmain c void CreateRamp ()
uniparm dat!Starting current
for laser!Range of current for
scan!Number of scans to
average!Number of chunks per
write!Number of ARINC words to
catch P T (divide by 5) 12.43!R-number for short path 3.694!R-number for Hcell 140!DC offset for power calcs 150!left end of search region 410!right end of search region 0.0!pr1 100.0!pr2 0.0!pr3 23.0!tr1 0.0!tr2 0.0!tr3 68.60169!c0_h 0.69185!c1_h 3.09883e-4!c2_h 0!File write_flag(1
Variables
Vmin = 0.0F
Vmax = 10.0F
Vconvert = 32767.0F / 10.0F
VIconvert = 10.0F / 125.0F
Vstart = uNIRparms.istart * VIconvert
Vend = Vstart + (uNIRparms.irange * VIconvert)
Vstep = (Vend - Vstart) / (float)(NPTS - 1)
Function Documentation
llmain c void CreateRamp ()
References printf(), Vconvert, Vstart, and Vstep.
uniparm dat ! Starting current for laser ! Range of current for scan ! Number of scans to average ! Number of chunks per write ! Number of ARINC words to catch P T (divide by 5)
Referenced by nidas::util::RunningAverage< unsigned short, 44 >::average(), nidas::core::ParameterT< T >::fromDOMElement(), nidas::util::LogScheme::getParameterT(), and nidas::core::ParameterT< T >::setValue().
Variable Documentation
Vconvert = 32767.0F / 10.0F
Referenced by CreateRamp().
Vend = Vstart + (uNIRparms.irange * VIconvert)
Referenced by nidas::dynld::Twins::createRamp().
VIconvert = 10.0F / 125.0F
Referenced by nidas::dynld::Twins::createRamp().
Vmax = 10.0F
Vmin = 0.0F
Vstart = uNIRparms.istart * VIconvert
Referenced by CreateRamp(), and nidas::dynld::Twins::createRamp().
Vstep = (Vend - Vstart) / (float)(NPTS - 1)
Referenced by CreateRamp(), and nidas::dynld::Twins::createRamp().