nidas: nidas/linux/viper/viper_dio.c File Reference
viper_dio.c File Reference
#include "viper_dio.h"
#include <linux/module.h>
#include <linux/init.h>
#include <asm/uaccess.h>
#include <mach/hardware.h>
#include <linux/gpio.h>
#include <mach/pxa2xx-regs.h>
#include <nidas/linux/ver_macros.h>
#include <nidas/linux/Revision.h>
#include <nidas/linux/klog.h>
#include <nidas/linux/isa_bus.h>
Macros
#define REPO_REVISION "unknown"
Functions
MODULE_AUTHOR ("Gordon Maclean <maclean@ucar.edu>")
MODULE_LICENSE ("GPL")
MODULE_DESCRIPTION ("Driver for VIPER DIO pins")
MODULE_VERSION (REPO_REVISION)
static void set_douts (unsigned char bits)
static void clear_douts (unsigned char bits)
static void set_douts_val (unsigned char bits, unsigned char value)
static unsigned char get_douts (void)
static unsigned char get_dins (void)
static int viper_dio_open (struct inode *inode, struct file *filp)
static int viper_dio_release (struct inode *inode, struct file *filp)
static long viper_dio_ioctl (struct file *filp, unsigned int cmd, unsigned long arg)
static void viper_dio_cleanup (void)
static int __init viper_dio_init (void)
module_init (viper_dio_init)
module_exit (viper_dio_cleanup)
Variables
static struct VIPER_DIO viper_dio
static int _ngpio
static struct file_operations viper_dio_fops
Macro Definition Documentation
#define REPO_REVISION "unknown"
Referenced by viper_dio_init().
Function Documentation
static void clear_douts (unsigned char bits) static
Referenced by set_douts_val(), and viper_dio_ioctl().
static unsigned char get_dins (void) static
Referenced by viper_dio_ioctl().
static unsigned char get_douts (void) static
Referenced by viper_dio_ioctl().
MODULE_AUTHOR ("Gordon Maclean <maclean@ucar.edu>")
MODULE_DESCRIPTION ("Driver for VIPER DIO pins")
module_exit (viper_dio_cleanup)
module_init (viper_dio_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (REPO_REVISION)
static void set_douts (unsigned char bits) static
Referenced by set_douts_val(), and viper_dio_ioctl().
static void set_douts_val (unsigned char bits, unsigned char value) static
References clear_douts(), and set_douts().
Referenced by viper_dio_ioctl().
static void viper_dio_cleanup (void) static
References _ngpio, and viper_dio.
Referenced by viper_dio_init().
static int __init viper_dio_init (void) static
References _ngpio, err, REPO_REVISION, viper_dio, viper_dio_cleanup(), and viper_dio_fops.
static long viper_dio_ioctl (struct file * filp, unsigned int cmd, unsigned long arg) static
References clear_douts(), err, get_dins(), get_douts(), set_douts(), set_douts_val(), viper_dio, VIPER_DIO_CLEAR, VIPER_DIO_GET_DIN, VIPER_DIO_GET_DOUT, VIPER_DIO_GET_NIN, VIPER_DIO_GET_NOUT, VIPER_DIO_IOC_MAGIC, VIPER_DIO_IOC_MAXNR, VIPER_DIO_NOUT, VIPER_DIO_SET, and VIPER_DIO_SET_TO_VAL.
static int viper_dio_open (struct inode * inode, struct file * filp) static
static int viper_dio_release (struct inode * inode, struct file * filp) static
Variable Documentation
int _ngpio static
Referenced by viper_dio_cleanup(), and viper_dio_init().
struct VIPER_DIO viper_dio static
Referenced by viper_dio_cleanup(), viper_dio_init(), and viper_dio_ioctl().
struct file_operations viper_dio_fops static
Initial value:
= {
        .owner   = THIS_MODULE,
        .open    = viper_dio_open,
        .unlocked_ioctl   = viper_dio_ioctl,
        .release = viper_dio_release,
        .llseek  = no_llseek,
}
Referenced by viper_dio_init().