#!/bin/sh

# Sample script to unload the Seamac device driver and 
# HDLC line discipline driver
#

# All utilities will be looked for in these directories, if you have
# a nonstandard setup, you may have to add another directory to this list
PATH=/sbin:/usr/sbin:/bin:/usr/bin


( lsmod | grep -i "seamac"     >/dev/null) && modprobe -r seamac
( lsmod | grep -i "n_hdlc"     >/dev/null) && modprobe -r n_hdlc

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Note that it is no longer necessary to manually remove device files        !
# because of udev                                                            !
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
